import type { BlogPost } from '../types';

const IMG_TERMINAL = '/images/quick-start/4_1.webp';
const IMG_DEMO = '/images/quick-start/6_1.webp';

export const howToTradeOnPocketOption: BlogPost = {
  slug: 'how-to-trade-on-pocket-option',
  category: 'tutorial',
  cover: '/images/blog/pocket-option-trading-terminal-guide.webp',
  publishedAt: '2026-09-18',
  updatedAt: '2026-09-26',
  readingMinutes: 9,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'How to trade on Pocket Option: a beginner’s guide to the trading terminal',
      metaTitle: 'How to Trade on Pocket Option – Beginner Terminal Guide',
      metaDescription:
        'Learn how to trade on Pocket Option: choose an asset, set expiration and amount, read the payout, place Up/Down trades and manage risk. Beginner tutorial with FAQ.',
      excerpt:
        'Everything a first-time trader needs to place a trade on the pocketoption terminal: assets, expiration, amount, payout, indicators and the mistakes to avoid.',
      coverAlt: 'Trader analysing charts in the Pocket Option trading terminal on a desktop monitor',
      keyTakeaways: [
        'A Pocket Option trade has four inputs: asset, expiration time, amount and direction (Up or Down).',
        'The payout percentage is shown before you click — it is what you receive on a correct forecast, not a guarantee.',
        'Start on the $50,000 demo account, then switch to real with the $5 minimum deposit and $1 minimum trade.',
        'Risk no more than 1–2% of your balance per trade and pick expirations that match your analysis.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option is built around one screen: the trading terminal. Once you understand its five zones — asset selector, chart, trade panel, payout indicator and the trade history — you can open a position in under ten seconds. This guide walks through the pocketoption terminal exactly as a beginner sees it, from the first login to the first closed trade.' },
        { type: 'h2', id: 'terminal', text: 'What the Pocket Option terminal looks like' },
        { type: 'p', text: 'After you log in (or open the demo account), the terminal is split into three areas. On the left is the asset list and the tool sidebar (indicators, drawing tools, signals, social trading). In the centre is the price chart. On the right is the trade panel, where you set the time, the amount and choose the direction.' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Pocket Option terminal with chart and Up/Down trade panel', caption: 'The trade panel: expiration time, amount, payout and the Up / Down buttons.' },
        { type: 'ul', items: [
          'Asset name and payout — shown at the top of the chart, e.g. “EUR/USD OTC · 92%”.',
          'Chart type and timeframe — candles, bars, line or area; from 5 seconds to 1 day.',
          'Time — how long the trade stays open before it expires.',
          'Amount — the sum you invest in this single trade (minimum $1).',
          'Up / Down — your forecast: will the price be higher or lower at expiration?',
        ] },
        { type: 'h2', id: 'asset', text: 'Step 1 — choose an asset and check the payout' },
        { type: 'p', text: 'Click the asset name to open the list. Pocket Option groups 100+ instruments into currencies, cryptocurrencies, commodities, stocks and indices. Next to each asset you see the current payout — the percentage added to your stake if the forecast is correct. Payouts change during the day and differ between regular and OTC assets, so beginners usually filter the list by highest payout and stick to two or three liquid pairs such as EUR/USD, GBP/USD or BTC/USD.' },
        { type: 'tip', title: 'Why OTC assets are everywhere', text: 'OTC (over-the-counter) quotes are provided by the platform itself, which is why they trade 24/7, including weekends. The behaviour differs from exchange hours, so practise OTC and regular assets separately on demo.' },
        { type: 'h2', id: 'expiration', text: 'Step 2 — set the expiration time' },
        { type: 'p', text: 'Expiration is when the trade closes and the result is fixed. Pocket Option offers two modes: a fixed duration (from 5 seconds to several hours) and a specific closing time on the clock. Short expirations (5 s – 1 min) are fast but noisy; 5–15 minutes give most indicators time to work. Match the expiration to the timeframe you analyse: if you read 1-minute candles, an expiration of 3–5 minutes is a common starting point.' },
        { type: 'h2', id: 'amount', text: 'Step 3 — enter the trade amount' },
        { type: 'p', text: 'Type the sum or use the +/− buttons. The minimum trade on pocketoption is $1, which lets you trade real money with a $5 deposit. Professional money management keeps a single trade at 1–2% of the balance: with $100 on the account that is $1–$2 per trade. The panel instantly shows the potential profit, e.g. “$10 → +$9.20” on a 92% payout.' },
        { type: 'h2', id: 'direction', text: 'Step 4 — pick a direction: Up or Down' },
        { type: 'p', text: 'Click the green Up button if you expect the price at expiration to be higher than the entry price, or the red Down button if you expect it to be lower. The trade appears on the chart as a horizontal line at the entry price with a countdown. When time runs out, the trade closes automatically: a correct forecast returns your stake plus the payout, an incorrect one loses the stake.' },
        { type: 'table', head: ['Result', 'Trade $10, payout 92%', 'Balance change'], rows: [
          ['Forecast correct', 'Stake returned + $9.20 profit', '+$9.20'],
          ['Forecast wrong', 'Stake lost', '−$10.00'],
          ['Price unchanged (tie)', 'Stake returned', '$0.00'],
        ] },
        { type: 'h2', id: 'tools', text: 'Step 5 — add indicators and read the chart' },
        { type: 'p', text: 'The sidebar contains more than 30 built-in indicators (RSI, MACD, Bollinger Bands, moving averages, Stochastic and others) plus drawing tools for trend lines and support/resistance. Add one or two indicators at most — a beginner set is a 20-period EMA for trend direction and RSI(14) for overbought/oversold zones. The terminal also shows the “traders’ choice” bar (the share of traders buying Up vs Down) and optional signals; treat these as context, not as a trigger.' },
        { type: 'h2', id: 'demo', text: 'Practise on the demo account first' },
        { type: 'image', src: IMG_DEMO, alt: 'Pocket Option demo account with $50,000 virtual balance', caption: 'The demo balance can be refilled to $50,000 at any moment.' },
        { type: 'p', text: 'The Pocket Option demo account gives you $50,000 of virtual funds on the same terminal, the same assets and the same payouts as the real account. Use it to test expirations, indicator settings and your money-management rules until you have at least 50–100 demo trades with stable results. Switching between demo and real is one click at the top of the balance panel.' },
        { type: 'h2', id: 'mistakes', text: 'Five beginner mistakes to avoid' },
        { type: 'ol', items: [
          'Increasing the amount after a loss (“martingale”) — the fastest way to zero a small balance.',
          'Trading 5-second expirations without a strategy — this is noise, not analysis.',
          'Opening trades on ten assets at once instead of learning two or three deeply.',
          'Ignoring the economic calendar — news spikes break most technical setups.',
          'Skipping the demo stage or leaving it too early.',
        ] },
        { type: 'warn', title: 'Risk warning', text: 'Trading involves a high level of risk and you can lose your entire investment. Payout percentages are not a promise of profit. Never trade with money you cannot afford to lose.' },
        { type: 'cta', text: 'Ready to try the terminal? Open the free demo, place a few Up/Down trades and come back to this guide when you switch to a real account.', label: 'Open Pocket Option demo' },
      ],
      faq: [
        { q: 'How much money do I need to start trading on Pocket Option?', a: 'The minimum deposit is $5 and the minimum trade is $1, so a real account can be started with $5. The demo account requires no deposit at all.' },
        { q: 'What is the best expiration time for beginners?', a: 'Most beginners start with 3–5 minute expirations on 1-minute candles. Very short expirations (5–30 seconds) are dominated by noise and are hard to trade with indicators.' },
        { q: 'Is the payout on Pocket Option guaranteed?', a: 'No. The payout shown before you open a trade is the percentage you receive if the forecast is correct. It changes during the day and differs by asset; a wrong forecast loses the invested amount.' },
        { q: 'Can I trade on Pocket Option from my phone?', a: 'Yes. The terminal works in a mobile browser and through the official iOS and Android apps with the same assets, indicators and demo account.' },
        { q: 'What does OTC mean next to an asset name?', a: 'OTC stands for over-the-counter: quotes are provided by the platform rather than an exchange, which is why OTC assets are available 24/7 including weekends.' },
      ],
    },

    pt: {
      title: 'Como operar na Pocket Option: guia do terminal de trading para iniciantes',
      metaTitle: 'Como Operar na Pocket Option – Guia do Terminal para Iniciantes',
      metaDescription:
        'Aprenda como operar na Pocket Option: escolha o ativo, defina expiração e valor, leia o payout, abra operações Para cima/Para baixo e gerencie o risco. Tutorial com FAQ.',
      excerpt:
        'Tudo o que um trader iniciante precisa para abrir a primeira operação no terminal pocketoption: ativos, expiração, valor, payout, indicadores e os erros a evitar.',
      coverAlt: 'Trader analisando gráficos no terminal de trading da Pocket Option em um monitor',
      keyTakeaways: [
        'Uma operação na Pocket Option tem quatro entradas: ativo, tempo de expiração, valor e direção (Para cima ou Para baixo).',
        'O payout aparece antes do clique — é o que você recebe em uma previsão correta, não uma garantia.',
        'Comece na conta demo de $50.000 e depois passe para a conta real com depósito mínimo de $5 e operação mínima de $1.',
        'Arrisque no máximo 1–2% do saldo por operação e escolha expirações compatíveis com sua análise.',
      ],
      blocks: [
        { type: 'p', text: 'A Pocket Option gira em torno de uma única tela: o terminal de trading. Quando você entende suas cinco zonas — seletor de ativos, gráfico, painel de operação, indicador de payout e histórico — consegue abrir uma posição em menos de dez segundos. Este guia percorre o terminal pocketoption exatamente como um iniciante o vê, do primeiro login à primeira operação encerrada.' },
        { type: 'h2', id: 'terminal', text: 'Como é o terminal da Pocket Option' },
        { type: 'p', text: 'Após o login (ou ao abrir a conta demo), o terminal se divide em três áreas. À esquerda ficam a lista de ativos e a barra de ferramentas (indicadores, ferramentas de desenho, sinais, social trading). No centro está o gráfico de preço. À direita, o painel de operação, onde você define o tempo, o valor e a direção.' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal da Pocket Option com gráfico e painel Para cima/Para baixo', caption: 'O painel de operação: tempo de expiração, valor, payout e os botões Para cima / Para baixo.' },
        { type: 'ul', items: [
          'Nome do ativo e payout — no topo do gráfico, por exemplo “EUR/USD OTC · 92%”.',
          'Tipo de gráfico e timeframe — candles, barras, linha ou área; de 5 segundos a 1 dia.',
          'Tempo — por quanto tempo a operação fica aberta até expirar.',
          'Valor — a quantia investida nesta operação (mínimo $1).',
          'Para cima / Para baixo — sua previsão: o preço estará mais alto ou mais baixo na expiração?',
        ] },
        { type: 'h2', id: 'asset', text: 'Passo 1 — escolha um ativo e verifique o payout' },
        { type: 'p', text: 'Clique no nome do ativo para abrir a lista. A Pocket Option agrupa mais de 100 instrumentos em moedas, criptomoedas, commodities, ações e índices. Ao lado de cada ativo aparece o payout atual — a porcentagem somada à sua aposta se a previsão estiver correta. Os payouts mudam ao longo do dia e diferem entre ativos regulares e OTC; iniciantes costumam filtrar por maior payout e ficar em dois ou três pares líquidos como EUR/USD, GBP/USD ou BTC/USD.' },
        { type: 'tip', title: 'Por que há tantos ativos OTC', text: 'As cotações OTC (over-the-counter) são fornecidas pela própria plataforma, por isso funcionam 24/7, inclusive nos fins de semana. O comportamento é diferente do horário de bolsa, então pratique OTC e ativos regulares separadamente na demo.' },
        { type: 'h2', id: 'expiration', text: 'Passo 2 — defina o tempo de expiração' },
        { type: 'p', text: 'Expiração é o momento em que a operação fecha e o resultado é fixado. A Pocket Option oferece dois modos: duração fixa (de 5 segundos a várias horas) e horário específico de fechamento. Expirações curtas (5 s – 1 min) são rápidas, mas cheias de ruído; 5–15 minutos dão tempo para a maioria dos indicadores funcionar. Combine a expiração com o timeframe analisado: se você lê candles de 1 minuto, 3–5 minutos é um ponto de partida comum.' },
        { type: 'h2', id: 'amount', text: 'Passo 3 — insira o valor da operação' },
        { type: 'p', text: 'Digite o valor ou use os botões +/−. A operação mínima na pocketoption é $1, o que permite operar com dinheiro real a partir de um depósito de $5. Uma gestão de capital profissional mantém cada operação em 1–2% do saldo: com $100 na conta, isso significa $1–$2 por operação. O painel mostra na hora o lucro potencial, por exemplo “$10 → +$9,20” com payout de 92%.' },
        { type: 'h2', id: 'direction', text: 'Passo 4 — escolha a direção: Para cima ou Para baixo' },
        { type: 'p', text: 'Clique no botão verde Para cima se espera que o preço na expiração seja maior que o de entrada, ou no vermelho Para baixo se espera que seja menor. A operação aparece no gráfico como uma linha horizontal no preço de entrada com contagem regressiva. Ao terminar o tempo, ela fecha automaticamente: previsão correta devolve a aposta mais o payout; previsão errada perde a aposta.' },
        { type: 'table', head: ['Resultado', 'Operação de $10, payout 92%', 'Variação do saldo'], rows: [
          ['Previsão correta', 'Aposta devolvida + $9,20 de lucro', '+$9,20'],
          ['Previsão errada', 'Aposta perdida', '−$10,00'],
          ['Preço inalterado (empate)', 'Aposta devolvida', '$0,00'],
        ] },
        { type: 'h2', id: 'tools', text: 'Passo 5 — adicione indicadores e leia o gráfico' },
        { type: 'p', text: 'A barra lateral traz mais de 30 indicadores integrados (RSI, MACD, Bandas de Bollinger, médias móveis, Estocástico e outros) além de ferramentas de desenho para linhas de tendência e suporte/resistência. Use no máximo um ou dois indicadores — um conjunto inicial é a EMA de 20 períodos para a direção da tendência e o RSI(14) para zonas de sobrecompra/sobrevenda. O terminal também mostra a barra “escolha dos traders” (proporção de compras Para cima vs Para baixo) e sinais opcionais; trate-os como contexto, não como gatilho.' },
        { type: 'h2', id: 'demo', text: 'Pratique primeiro na conta demo' },
        { type: 'image', src: IMG_DEMO, alt: 'Conta demo da Pocket Option com saldo virtual de $50.000', caption: 'O saldo demo pode ser recarregado para $50.000 a qualquer momento.' },
        { type: 'p', text: 'A conta demo da Pocket Option oferece $50.000 em fundos virtuais no mesmo terminal, com os mesmos ativos e payouts da conta real. Use-a para testar expirações, configurações de indicadores e regras de gestão de capital até ter pelo menos 50–100 operações demo com resultados estáveis. Alternar entre demo e real é um clique no topo do painel de saldo.' },
        { type: 'h2', id: 'mistakes', text: 'Cinco erros de iniciante a evitar' },
        { type: 'ol', items: [
          'Aumentar o valor após uma perda (“martingale”) — a forma mais rápida de zerar um saldo pequeno.',
          'Operar expirações de 5 segundos sem estratégia — isso é ruído, não análise.',
          'Abrir operações em dez ativos ao mesmo tempo em vez de dominar dois ou três.',
          'Ignorar o calendário econômico — picos de notícias quebram a maioria dos setups técnicos.',
          'Pular a fase demo ou sair dela cedo demais.',
        ] },
        { type: 'warn', title: 'Aviso de risco', text: 'Operar envolve alto nível de risco e você pode perder todo o investimento. As porcentagens de payout não são promessa de lucro. Nunca opere com dinheiro que não pode perder.' },
        { type: 'cta', text: 'Pronto para testar o terminal? Abra a demo gratuita, faça algumas operações Para cima/Para baixo e volte a este guia quando passar para a conta real.', label: 'Abrir demo da Pocket Option' },
      ],
      faq: [
        { q: 'Quanto dinheiro preciso para começar a operar na Pocket Option?', a: 'O depósito mínimo é $5 e a operação mínima é $1, então uma conta real pode começar com $5. A conta demo não exige depósito.' },
        { q: 'Qual é o melhor tempo de expiração para iniciantes?', a: 'A maioria começa com expirações de 3–5 minutos em candles de 1 minuto. Expirações muito curtas (5–30 segundos) são dominadas por ruído e difíceis de operar com indicadores.' },
        { q: 'O payout na Pocket Option é garantido?', a: 'Não. O payout exibido antes de abrir a operação é a porcentagem recebida se a previsão estiver correta. Ele muda ao longo do dia e varia por ativo; uma previsão errada perde o valor investido.' },
        { q: 'Posso operar na Pocket Option pelo celular?', a: 'Sim. O terminal funciona no navegador do celular e nos aplicativos oficiais para iOS e Android, com os mesmos ativos, indicadores e conta demo.' },
        { q: 'O que significa OTC ao lado do nome do ativo?', a: 'OTC significa over-the-counter: as cotações são fornecidas pela plataforma e não por uma bolsa, por isso os ativos OTC ficam disponíveis 24/7, inclusive nos fins de semana.' },
      ],
    },

    es: {
      title: 'Cómo operar en Pocket Option: guía del terminal de trading para principiantes',
      metaTitle: 'Cómo Operar en Pocket Option – Guía del Terminal para Novatos',
      metaDescription:
        'Aprende cómo operar en Pocket Option: elige el activo, define expiración e importe, lee el payout, abre operaciones Arriba/Abajo y gestiona el riesgo. Tutorial con FAQ.',
      excerpt:
        'Todo lo que un trader principiante necesita para abrir su primera operación en el terminal pocketoption: activos, expiración, importe, payout, indicadores y los errores que debe evitar.',
      coverAlt: 'Trader analizando gráficos en el terminal de trading de Pocket Option en un monitor',
      keyTakeaways: [
        'Una operación en Pocket Option tiene cuatro datos: activo, tiempo de expiración, importe y dirección (Arriba o Abajo).',
        'El payout se muestra antes de hacer clic: es lo que recibes con un pronóstico correcto, no una garantía.',
        'Empieza en la cuenta demo de $50.000 y pasa a la real con el depósito mínimo de $5 y la operación mínima de $1.',
        'No arriesgues más del 1–2% del saldo por operación y elige expiraciones acordes a tu análisis.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option gira en torno a una sola pantalla: el terminal de trading. Cuando entiendes sus cinco zonas —selector de activos, gráfico, panel de operación, indicador de payout e historial— puedes abrir una posición en menos de diez segundos. Esta guía recorre el terminal pocketoption tal como lo ve un principiante, desde el primer inicio de sesión hasta la primera operación cerrada.' },
        { type: 'h2', id: 'terminal', text: 'Cómo es el terminal de Pocket Option' },
        { type: 'p', text: 'Tras iniciar sesión (o abrir la cuenta demo), el terminal se divide en tres áreas. A la izquierda están la lista de activos y la barra de herramientas (indicadores, herramientas de dibujo, señales, social trading). En el centro, el gráfico de precios. A la derecha, el panel de operación, donde defines el tiempo, el importe y la dirección.' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal de Pocket Option con gráfico y panel Arriba/Abajo', caption: 'El panel de operación: tiempo de expiración, importe, payout y los botones Arriba / Abajo.' },
        { type: 'ul', items: [
          'Nombre del activo y payout — en la parte superior del gráfico, p. ej. “EUR/USD OTC · 92%”.',
          'Tipo de gráfico y marco temporal — velas, barras, línea o área; de 5 segundos a 1 día.',
          'Tiempo — cuánto permanece abierta la operación antes de expirar.',
          'Importe — la suma invertida en esta operación (mínimo $1).',
          'Arriba / Abajo — tu pronóstico: ¿el precio estará más alto o más bajo al expirar?',
        ] },
        { type: 'h2', id: 'asset', text: 'Paso 1 — elige un activo y revisa el payout' },
        { type: 'p', text: 'Haz clic en el nombre del activo para abrir la lista. Pocket Option agrupa más de 100 instrumentos en divisas, criptomonedas, materias primas, acciones e índices. Junto a cada activo ves el payout actual: el porcentaje que se suma a tu inversión si el pronóstico es correcto. Los payouts cambian durante el día y difieren entre activos regulares y OTC, así que los principiantes suelen filtrar por mayor payout y quedarse con dos o tres pares líquidos como EUR/USD, GBP/USD o BTC/USD.' },
        { type: 'tip', title: 'Por qué hay tantos activos OTC', text: 'Las cotizaciones OTC (over-the-counter) las proporciona la propia plataforma, por eso operan 24/7, incluidos los fines de semana. Su comportamiento difiere del horario bursátil; practica OTC y activos regulares por separado en la demo.' },
        { type: 'h2', id: 'expiration', text: 'Paso 2 — define el tiempo de expiración' },
        { type: 'p', text: 'La expiración es el momento en que la operación se cierra y el resultado queda fijado. Pocket Option ofrece dos modos: duración fija (de 5 segundos a varias horas) y una hora de cierre concreta. Las expiraciones cortas (5 s – 1 min) son rápidas pero ruidosas; 5–15 minutos dan tiempo a que funcionen la mayoría de indicadores. Ajusta la expiración al marco temporal que analizas: si lees velas de 1 minuto, 3–5 minutos es un punto de partida habitual.' },
        { type: 'h2', id: 'amount', text: 'Paso 3 — introduce el importe de la operación' },
        { type: 'p', text: 'Escribe la suma o usa los botones +/−. La operación mínima en pocketoption es $1, lo que permite operar con dinero real desde un depósito de $5. Una gestión de capital profesional mantiene cada operación en el 1–2% del saldo: con $100 en la cuenta, eso son $1–$2 por operación. El panel muestra al instante el beneficio potencial, p. ej. “$10 → +$9,20” con un payout del 92%.' },
        { type: 'h2', id: 'direction', text: 'Paso 4 — elige la dirección: Arriba o Abajo' },
        { type: 'p', text: 'Pulsa el botón verde Arriba si esperas que el precio al expirar sea mayor que el de entrada, o el rojo Abajo si esperas que sea menor. La operación aparece en el gráfico como una línea horizontal en el precio de entrada con cuenta atrás. Al agotarse el tiempo, se cierra automáticamente: un pronóstico correcto devuelve la inversión más el payout; uno incorrecto pierde la inversión.' },
        { type: 'table', head: ['Resultado', 'Operación de $10, payout 92%', 'Cambio en el saldo'], rows: [
          ['Pronóstico correcto', 'Inversión devuelta + $9,20 de beneficio', '+$9,20'],
          ['Pronóstico incorrecto', 'Inversión perdida', '−$10,00'],
          ['Precio sin cambios (empate)', 'Inversión devuelta', '$0,00'],
        ] },
        { type: 'h2', id: 'tools', text: 'Paso 5 — añade indicadores y lee el gráfico' },
        { type: 'p', text: 'La barra lateral incluye más de 30 indicadores integrados (RSI, MACD, Bandas de Bollinger, medias móviles, Estocástico y otros) y herramientas de dibujo para líneas de tendencia y soportes/resistencias. Usa uno o dos indicadores como máximo: un conjunto inicial es la EMA de 20 periodos para la dirección de la tendencia y el RSI(14) para zonas de sobrecompra/sobreventa. El terminal también muestra la barra de “elección de los traders” (proporción de compras Arriba vs Abajo) y señales opcionales; tómalos como contexto, no como disparador.' },
        { type: 'h2', id: 'demo', text: 'Practica primero en la cuenta demo' },
        { type: 'image', src: IMG_DEMO, alt: 'Cuenta demo de Pocket Option con saldo virtual de $50.000', caption: 'El saldo demo puede recargarse a $50.000 en cualquier momento.' },
        { type: 'p', text: 'La cuenta demo de Pocket Option ofrece $50.000 en fondos virtuales en el mismo terminal, con los mismos activos y payouts que la cuenta real. Úsala para probar expiraciones, ajustes de indicadores y tus reglas de gestión de capital hasta acumular al menos 50–100 operaciones demo con resultados estables. Cambiar entre demo y real es un clic en la parte superior del panel de saldo.' },
        { type: 'h2', id: 'mistakes', text: 'Cinco errores de principiante que debes evitar' },
        { type: 'ol', items: [
          'Aumentar el importe tras una pérdida (“martingala”): la forma más rápida de vaciar un saldo pequeño.',
          'Operar expiraciones de 5 segundos sin estrategia: eso es ruido, no análisis.',
          'Abrir operaciones en diez activos a la vez en lugar de dominar dos o tres.',
          'Ignorar el calendario económico: los picos por noticias rompen la mayoría de configuraciones técnicas.',
          'Saltarse la fase demo o abandonarla demasiado pronto.',
        ] },
        { type: 'warn', title: 'Advertencia de riesgo', text: 'Operar implica un alto nivel de riesgo y puedes perder toda tu inversión. Los porcentajes de payout no son una promesa de beneficio. Nunca operes con dinero que no puedas permitirte perder.' },
        { type: 'cta', text: '¿Listo para probar el terminal? Abre la demo gratuita, realiza algunas operaciones Arriba/Abajo y vuelve a esta guía cuando pases a la cuenta real.', label: 'Abrir demo de Pocket Option' },
      ],
      faq: [
        { q: '¿Cuánto dinero necesito para empezar a operar en Pocket Option?', a: 'El depósito mínimo es $5 y la operación mínima es $1, así que una cuenta real puede empezar con $5. La cuenta demo no requiere depósito.' },
        { q: '¿Cuál es el mejor tiempo de expiración para principiantes?', a: 'La mayoría empieza con expiraciones de 3–5 minutos en velas de 1 minuto. Las expiraciones muy cortas (5–30 segundos) están dominadas por el ruido y son difíciles de operar con indicadores.' },
        { q: '¿El payout en Pocket Option está garantizado?', a: 'No. El payout mostrado antes de abrir la operación es el porcentaje que recibes si el pronóstico es correcto. Cambia durante el día y varía por activo; un pronóstico incorrecto pierde el importe invertido.' },
        { q: '¿Puedo operar en Pocket Option desde el móvil?', a: 'Sí. El terminal funciona en el navegador móvil y en las apps oficiales para iOS y Android con los mismos activos, indicadores y cuenta demo.' },
        { q: '¿Qué significa OTC junto al nombre del activo?', a: 'OTC significa over-the-counter: las cotizaciones las proporciona la plataforma y no una bolsa, por eso los activos OTC están disponibles 24/7, incluidos los fines de semana.' },
      ],
    },

    ru: {
      title: 'Как торговать на Pocket Option: руководство по торговому терминалу для новичков',
      metaTitle: 'Как торговать на Pocket Option – руководство для новичков',
      metaDescription:
        'Узнайте, как торговать на Pocket Option: выбор актива, экспирация и сумма сделки, чтение выплаты, сделки Вверх/Вниз и управление риском. Статья для новичков с FAQ.',
      excerpt:
        'Всё, что нужно начинающему трейдеру для первой сделки в терминале pocketoption: активы, экспирация, сумма, выплата, индикаторы и ошибки, которых стоит избегать.',
      coverAlt: 'Трейдер анализирует графики в торговом терминале Pocket Option на мониторе',
      keyTakeaways: [
        'У сделки на Pocket Option четыре параметра: актив, время экспирации, сумма и направление (Вверх или Вниз).',
        'Процент выплаты виден до нажатия — это то, что вы получите при верном прогнозе, а не гарантия.',
        'Начните с демо-счёта на $50 000, затем переходите на реальный с минимальным депозитом $5 и сделкой от $1.',
        'Рискуйте не более 1–2% баланса на сделку и подбирайте экспирацию под свой анализ.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option построен вокруг одного экрана — торгового терминала. Когда вы понимаете его пять зон (выбор актива, график, панель сделки, индикатор выплаты и история сделок), открыть позицию можно менее чем за десять секунд. Это руководство проходит по терминалу pocketoption так, как его видит новичок: от первого входа до первой закрытой сделки.' },
        { type: 'h2', id: 'terminal', text: 'Как выглядит терминал Pocket Option' },
        { type: 'p', text: 'После входа (или открытия демо-счёта) терминал делится на три области. Слева — список активов и панель инструментов (индикаторы, инструменты рисования, сигналы, социальный трейдинг). В центре — график цены. Справа — панель сделки, где вы задаёте время, сумму и направление.' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Терминал Pocket Option с графиком и панелью Вверх/Вниз', caption: 'Панель сделки: время экспирации, сумма, выплата и кнопки Вверх / Вниз.' },
        { type: 'ul', items: [
          'Название актива и выплата — вверху графика, например «EUR/USD OTC · 92%».',
          'Тип графика и таймфрейм — свечи, бары, линия или область; от 5 секунд до 1 дня.',
          'Время — сколько сделка остаётся открытой до экспирации.',
          'Сумма — сколько вы вкладываете в эту сделку (минимум $1).',
          'Вверх / Вниз — ваш прогноз: будет ли цена выше или ниже на момент экспирации?',
        ] },
        { type: 'h2', id: 'asset', text: 'Шаг 1 — выберите актив и проверьте выплату' },
        { type: 'p', text: 'Нажмите на название актива, чтобы открыть список. Pocket Option группирует 100+ инструментов на валюты, криптовалюты, сырьё, акции и индексы. Рядом с каждым активом указана текущая выплата — процент, который добавляется к ставке при верном прогнозе. Выплаты меняются в течение дня и различаются у обычных и OTC-активов, поэтому новички обычно фильтруют список по максимальной выплате и работают с двумя-тремя ликвидными парами, например EUR/USD, GBP/USD или BTC/USD.' },
        { type: 'tip', title: 'Почему так много OTC-активов', text: 'Котировки OTC (внебиржевые) предоставляет сама платформа, поэтому они торгуются 24/7, включая выходные. Их поведение отличается от биржевых часов — отрабатывайте OTC и обычные активы на демо отдельно.' },
        { type: 'h2', id: 'expiration', text: 'Шаг 2 — задайте время экспирации' },
        { type: 'p', text: 'Экспирация — момент закрытия сделки и фиксации результата. Pocket Option предлагает два режима: фиксированную длительность (от 5 секунд до нескольких часов) и конкретное время закрытия по часам. Короткие экспирации (5 с – 1 мин) быстрые, но шумные; 5–15 минут дают большинству индикаторов время отработать. Подбирайте экспирацию под анализируемый таймфрейм: если вы читаете минутные свечи, 3–5 минут — распространённая отправная точка.' },
        { type: 'h2', id: 'amount', text: 'Шаг 3 — введите сумму сделки' },
        { type: 'p', text: 'Введите сумму или используйте кнопки +/−. Минимальная сделка на pocketoption — $1, что позволяет торговать реальными деньгами с депозитом $5. Профессиональный мани-менеджмент держит одну сделку в пределах 1–2% баланса: при $100 на счёте это $1–$2 на сделку. Панель сразу показывает потенциальную прибыль, например «$10 → +$9,20» при выплате 92%.' },
        { type: 'h2', id: 'direction', text: 'Шаг 4 — выберите направление: Вверх или Вниз' },
        { type: 'p', text: 'Нажмите зелёную кнопку Вверх, если ожидаете, что цена на момент экспирации будет выше цены входа, или красную Вниз, если ниже. Сделка отображается на графике горизонтальной линией на цене входа с обратным отсчётом. Когда время истекает, сделка закрывается автоматически: верный прогноз возвращает ставку плюс выплату, неверный — теряет ставку.' },
        { type: 'table', head: ['Результат', 'Сделка $10, выплата 92%', 'Изменение баланса'], rows: [
          ['Прогноз верный', 'Возврат ставки + $9,20 прибыли', '+$9,20'],
          ['Прогноз неверный', 'Ставка потеряна', '−$10,00'],
          ['Цена не изменилась (ничья)', 'Возврат ставки', '$0,00'],
        ] },
        { type: 'h2', id: 'tools', text: 'Шаг 5 — добавьте индикаторы и читайте график' },
        { type: 'p', text: 'В боковой панели более 30 встроенных индикаторов (RSI, MACD, полосы Боллинджера, скользящие средние, Стохастик и другие) и инструменты рисования для трендовых линий и уровней поддержки/сопротивления. Добавляйте максимум один-два индикатора — стартовый набор: EMA(20) для направления тренда и RSI(14) для зон перекупленности/перепроданности. Терминал также показывает шкалу «выбор трейдеров» (доля покупающих Вверх и Вниз) и опциональные сигналы; воспринимайте их как контекст, а не как триггер.' },
        { type: 'h2', id: 'demo', text: 'Сначала потренируйтесь на демо-счёте' },
        { type: 'image', src: IMG_DEMO, alt: 'Демо-счёт Pocket Option с виртуальным балансом $50 000', caption: 'Демо-баланс можно пополнить до $50 000 в любой момент.' },
        { type: 'p', text: 'Демо-счёт Pocket Option даёт $50 000 виртуальных средств в том же терминале, с теми же активами и выплатами, что и реальный счёт. Используйте его, чтобы проверить экспирации, настройки индикаторов и правила мани-менеджмента, пока не наберёте хотя бы 50–100 демо-сделок со стабильным результатом. Переключение между демо и реальным счётом — один клик вверху панели баланса.' },
        { type: 'h2', id: 'mistakes', text: 'Пять ошибок новичка, которых стоит избегать' },
        { type: 'ol', items: [
          'Увеличивать сумму после убытка («мартингейл») — самый быстрый способ обнулить небольшой баланс.',
          'Торговать 5-секундные экспирации без стратегии — это шум, а не анализ.',
          'Открывать сделки по десяти активам сразу вместо глубокого изучения двух-трёх.',
          'Игнорировать экономический календарь — новостные всплески ломают большинство технических сетапов.',
          'Пропускать демо-этап или уходить с него слишком рано.',
        ] },
        { type: 'warn', title: 'Предупреждение о рисках', text: 'Торговля связана с высоким уровнем риска, и вы можете потерять все вложенные средства. Проценты выплат не являются обещанием прибыли. Никогда не торгуйте на деньги, которые не можете позволить себе потерять.' },
        { type: 'cta', text: 'Готовы попробовать терминал? Откройте бесплатное демо, совершите несколько сделок Вверх/Вниз и вернитесь к этому руководству при переходе на реальный счёт.', label: 'Открыть демо Pocket Option' },
      ],
      faq: [
        { q: 'Сколько денег нужно, чтобы начать торговать на Pocket Option?', a: 'Минимальный депозит — $5, минимальная сделка — $1, поэтому реальный счёт можно открыть с $5. Демо-счёт вообще не требует депозита.' },
        { q: 'Какое время экспирации лучше для новичков?', a: 'Большинство новичков начинают с экспирации 3–5 минут на минутных свечах. Очень короткие экспирации (5–30 секунд) полны шума, и торговать их по индикаторам сложно.' },
        { q: 'Гарантирована ли выплата на Pocket Option?', a: 'Нет. Выплата, показанная перед открытием сделки, — это процент, который вы получите при верном прогнозе. Она меняется в течение дня и различается по активам; неверный прогноз теряет вложенную сумму.' },
        { q: 'Можно ли торговать на Pocket Option с телефона?', a: 'Да. Терминал работает в мобильном браузере и в официальных приложениях для iOS и Android с теми же активами, индикаторами и демо-счётом.' },
        { q: 'Что означает OTC рядом с названием актива?', a: 'OTC — over-the-counter, внебиржевой: котировки предоставляет платформа, а не биржа, поэтому OTC-активы доступны 24/7, включая выходные.' },
      ],
    },

    id: {
      title: 'Cara trading di Pocket Option: panduan terminal trading untuk pemula',
      metaTitle: 'Cara Trading di Pocket Option – Panduan Terminal untuk Pemula',
      metaDescription:
        'Pelajari cara trading di Pocket Option: pilih aset, atur waktu kedaluwarsa dan jumlah, baca payout, buka trade Naik/Turun, dan kelola risiko. Tutorial pemula dengan FAQ.',
      excerpt:
        'Semua yang dibutuhkan trader pemula untuk membuka trade pertama di terminal pocketoption: aset, kedaluwarsa, jumlah, payout, indikator, dan kesalahan yang harus dihindari.',
      coverAlt: 'Trader menganalisis grafik di terminal trading Pocket Option pada monitor desktop',
      keyTakeaways: [
        'Sebuah trade di Pocket Option punya empat input: aset, waktu kedaluwarsa, jumlah, dan arah (Naik atau Turun).',
        'Persentase payout terlihat sebelum Anda klik — itu yang Anda terima saat prediksi benar, bukan jaminan.',
        'Mulai di akun demo $50.000, lalu beralih ke akun riil dengan deposit minimum $5 dan trade minimum $1.',
        'Risikokan maksimal 1–2% saldo per trade dan pilih kedaluwarsa yang sesuai dengan analisis Anda.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option berpusat pada satu layar: terminal trading. Setelah Anda memahami lima zonanya — pemilih aset, grafik, panel trade, indikator payout, dan riwayat trade — Anda bisa membuka posisi dalam waktu kurang dari sepuluh detik. Panduan ini menelusuri terminal pocketoption persis seperti yang dilihat pemula, dari login pertama hingga trade pertama yang ditutup.' },
        { type: 'h2', id: 'terminal', text: 'Seperti apa terminal Pocket Option' },
        { type: 'p', text: 'Setelah login (atau membuka akun demo), terminal terbagi menjadi tiga area. Di kiri ada daftar aset dan sidebar alat (indikator, alat gambar, sinyal, social trading). Di tengah adalah grafik harga. Di kanan adalah panel trade, tempat Anda mengatur waktu, jumlah, dan memilih arah.' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal Pocket Option dengan grafik dan panel trade Naik/Turun', caption: 'Panel trade: waktu kedaluwarsa, jumlah, payout, dan tombol Naik / Turun.' },
        { type: 'ul', items: [
          'Nama aset dan payout — ditampilkan di atas grafik, misalnya “EUR/USD OTC · 92%”.',
          'Jenis grafik dan timeframe — candle, bar, garis, atau area; dari 5 detik hingga 1 hari.',
          'Waktu — berapa lama trade tetap terbuka sebelum kedaluwarsa.',
          'Jumlah — dana yang Anda investasikan pada satu trade ini (minimum $1).',
          'Naik / Turun — prediksi Anda: apakah harga akan lebih tinggi atau lebih rendah saat kedaluwarsa?',
        ] },
        { type: 'h2', id: 'asset', text: 'Langkah 1 — pilih aset dan cek payout' },
        { type: 'p', text: 'Klik nama aset untuk membuka daftar. Pocket Option mengelompokkan 100+ instrumen ke dalam mata uang, kripto, komoditas, saham, dan indeks. Di samping setiap aset Anda melihat payout saat ini — persentase yang ditambahkan ke modal jika prediksi benar. Payout berubah sepanjang hari dan berbeda antara aset reguler dan OTC, jadi pemula biasanya menyaring daftar berdasarkan payout tertinggi dan fokus pada dua atau tiga pasangan likuid seperti EUR/USD, GBP/USD, atau BTC/USD.' },
        { type: 'tip', title: 'Mengapa aset OTC ada di mana-mana', text: 'Kuotasi OTC (over-the-counter) disediakan oleh platform itu sendiri, itulah sebabnya bisa ditradingkan 24/7 termasuk akhir pekan. Perilakunya berbeda dari jam bursa, jadi latih OTC dan aset reguler secara terpisah di demo.' },
        { type: 'h2', id: 'expiration', text: 'Langkah 2 — atur waktu kedaluwarsa' },
        { type: 'p', text: 'Kedaluwarsa adalah saat trade ditutup dan hasilnya ditetapkan. Pocket Option menawarkan dua mode: durasi tetap (dari 5 detik hingga beberapa jam) dan waktu penutupan tertentu di jam. Kedaluwarsa pendek (5 dtk – 1 mnt) cepat tetapi penuh noise; 5–15 menit memberi waktu bagi kebanyakan indikator untuk bekerja. Sesuaikan kedaluwarsa dengan timeframe yang Anda analisis: jika membaca candle 1 menit, kedaluwarsa 3–5 menit adalah titik awal yang umum.' },
        { type: 'h2', id: 'amount', text: 'Langkah 3 — masukkan jumlah trade' },
        { type: 'p', text: 'Ketik jumlahnya atau gunakan tombol +/−. Trade minimum di pocketoption adalah $1, sehingga Anda bisa trading uang riil dengan deposit $5. Manajemen modal profesional menjaga satu trade di 1–2% saldo: dengan $100 di akun, itu berarti $1–$2 per trade. Panel langsung menampilkan potensi profit, misalnya “$10 → +$9,20” pada payout 92%.' },
        { type: 'h2', id: 'direction', text: 'Langkah 4 — pilih arah: Naik atau Turun' },
        { type: 'p', text: 'Klik tombol hijau Naik jika Anda memperkirakan harga saat kedaluwarsa lebih tinggi dari harga masuk, atau tombol merah Turun jika lebih rendah. Trade muncul di grafik sebagai garis horizontal pada harga masuk dengan hitungan mundur. Saat waktu habis, trade ditutup otomatis: prediksi benar mengembalikan modal plus payout, prediksi salah kehilangan modal.' },
        { type: 'table', head: ['Hasil', 'Trade $10, payout 92%', 'Perubahan saldo'], rows: [
          ['Prediksi benar', 'Modal kembali + profit $9,20', '+$9,20'],
          ['Prediksi salah', 'Modal hilang', '−$10,00'],
          ['Harga tidak berubah (seri)', 'Modal kembali', '$0,00'],
        ] },
        { type: 'h2', id: 'tools', text: 'Langkah 5 — tambahkan indikator dan baca grafik' },
        { type: 'p', text: 'Sidebar berisi lebih dari 30 indikator bawaan (RSI, MACD, Bollinger Bands, moving average, Stochastic, dan lainnya) plus alat gambar untuk garis tren dan support/resistance. Tambahkan maksimal satu atau dua indikator — set pemula adalah EMA 20 periode untuk arah tren dan RSI(14) untuk zona overbought/oversold. Terminal juga menampilkan bar “pilihan trader” (persentase trader yang membeli Naik vs Turun) dan sinyal opsional; anggap itu sebagai konteks, bukan pemicu.' },
        { type: 'h2', id: 'demo', text: 'Berlatih dulu di akun demo' },
        { type: 'image', src: IMG_DEMO, alt: 'Akun demo Pocket Option dengan saldo virtual $50.000', caption: 'Saldo demo dapat diisi ulang ke $50.000 kapan saja.' },
        { type: 'p', text: 'Akun demo Pocket Option memberi Anda $50.000 dana virtual di terminal yang sama, aset yang sama, dan payout yang sama seperti akun riil. Gunakan untuk menguji kedaluwarsa, pengaturan indikator, dan aturan manajemen modal Anda hingga memiliki setidaknya 50–100 trade demo dengan hasil stabil. Beralih antara demo dan riil hanya satu klik di bagian atas panel saldo.' },
        { type: 'h2', id: 'mistakes', text: 'Lima kesalahan pemula yang harus dihindari' },
        { type: 'ol', items: [
          'Menaikkan jumlah setelah rugi (“martingale”) — cara tercepat menghabiskan saldo kecil.',
          'Trading kedaluwarsa 5 detik tanpa strategi — itu noise, bukan analisis.',
          'Membuka trade di sepuluh aset sekaligus alih-alih mendalami dua atau tiga.',
          'Mengabaikan kalender ekonomi — lonjakan berita merusak sebagian besar setup teknikal.',
          'Melewatkan tahap demo atau meninggalkannya terlalu cepat.',
        ] },
        { type: 'warn', title: 'Peringatan risiko', text: 'Trading melibatkan risiko tinggi dan Anda bisa kehilangan seluruh investasi. Persentase payout bukan janji profit. Jangan pernah trading dengan uang yang tidak sanggup Anda rugikan.' },
        { type: 'cta', text: 'Siap mencoba terminal? Buka demo gratis, lakukan beberapa trade Naik/Turun, dan kembali ke panduan ini saat beralih ke akun riil.', label: 'Buka demo Pocket Option' },
      ],
      faq: [
        { q: 'Berapa uang yang saya butuhkan untuk mulai trading di Pocket Option?', a: 'Deposit minimum $5 dan trade minimum $1, sehingga akun riil bisa dimulai dengan $5. Akun demo tidak memerlukan deposit sama sekali.' },
        { q: 'Berapa waktu kedaluwarsa terbaik untuk pemula?', a: 'Kebanyakan pemula mulai dengan kedaluwarsa 3–5 menit pada candle 1 menit. Kedaluwarsa sangat pendek (5–30 detik) didominasi noise dan sulit ditradingkan dengan indikator.' },
        { q: 'Apakah payout di Pocket Option dijamin?', a: 'Tidak. Payout yang ditampilkan sebelum membuka trade adalah persentase yang Anda terima jika prediksi benar. Nilainya berubah sepanjang hari dan berbeda per aset; prediksi salah kehilangan jumlah yang diinvestasikan.' },
        { q: 'Bisakah saya trading di Pocket Option dari ponsel?', a: 'Ya. Terminal berjalan di browser ponsel dan melalui aplikasi resmi iOS dan Android dengan aset, indikator, dan akun demo yang sama.' },
        { q: 'Apa arti OTC di samping nama aset?', a: 'OTC berarti over-the-counter: kuotasi disediakan oleh platform, bukan bursa, sehingga aset OTC tersedia 24/7 termasuk akhir pekan.' },
      ],
    },
  },
};
