import type { BlogPost } from '../types';

const IMG_REGISTER = '/images/blog/po-registration-form.webp';
const IMG_LOGIN = '/images/blog/po-login-form.webp';

export const pocketOptionLoginRegistration: BlogPost = {
  slug: 'pocket-option-login-registration',
  category: 'tutorial',
  cover: '/images/blog/pocket-option-login-registration.webp',
  publishedAt: '2026-09-25',
  updatedAt: '2026-09-25',
  readingMinutes: 7,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option login and registration: how to sign up, sign in and recover your password',
      metaTitle: 'Pocket Option Login & Sign Up – Register, Sign In, Recover',
      metaDescription:
        'Pocket Option login and registration guide: create an account with e-mail, Google or Facebook, confirm your e-mail, sign in safely, enable 2FA and fix common login errors.',
      excerpt:
        'Step-by-step pocketoption sign-up and login: the registration form, social sign-in, e-mail confirmation, password recovery, 2FA and troubleshooting.',
      coverAlt: 'Pocket Option homepage with the registration and login panel',
      keyTakeaways: [
        'Registration on Pocket Option takes about a minute: e-mail + password, or one-click sign-up with Google or Facebook.',
        'Confirm your e-mail right after registering — it is required for withdrawals and password recovery.',
        'Log in at pocketoption.com or in the mobile/desktop app with the same credentials; enable two-factor authentication in Profile → Security.',
        'Forgot your password? Use “Password recovery” on the login form and follow the e-mail link.',
        'Most login problems are caused by an unconfirmed e-mail, a typo, a blocked country or an outdated app version.',
      ],
      blocks: [
        { type: 'p', text: 'Every Pocket Option journey starts with two screens: the registration form and the login form. Both are simple, but a few details — confirming your e-mail, choosing the right country, enabling 2FA — save you trouble later, especially at withdrawal time. This guide walks through pocketoption sign-up and login on the website and in the app, plus what to do when you cannot get in.' },
        { type: 'h2', id: 'requirements', text: 'Before you register' },
        { type: 'ul', items: [
          'You must be 18 or older and live in a country served by Pocket Option (the USA, EU/EEA, UK, Canada, Australia and Israel are not accepted).',
          'Use an e-mail you control — it will be needed for confirmation, withdrawal approval and password resets.',
          'Register in your own name only. Duplicate accounts or accounts for other people are closed during verification.',
          'Have a promo code ready if you want one (e.g. 50START for +50% on the first deposit); it is entered at registration.',
        ] },
        { type: 'h2', id: 'register', text: 'How to register on Pocket Option (step by step)' },
        { type: 'image', src: IMG_REGISTER, alt: 'Pocket Option registration form with e-mail, password, promo code and Sign up button', caption: 'The registration form: e-mail, password, optional promo code, agreement checkbox.' },
        { type: 'ol', items: [
          'Open the official website and click Registration (top-right on desktop, in the menu on mobile).',
          'Enter your e-mail and create a password of at least 8 characters with letters and numbers.',
          'Optionally enter a promo code in the “Enter promo code (if you have one)” field.',
          'Tick “I have read and accepted the Public offer agreement”.',
          'Click Sign up. The account is created and you land straight in the trading terminal with a $50,000 demo balance.',
          'Open the confirmation e-mail and click the link. Your e-mail is now verified.',
        ] },
        { type: 'tip', title: 'One-click sign-up', text: 'Prefer not to type? Click “Facebook” or “Google” under the form. The account is created with the e-mail of your social profile — you can still set a separate password later in Profile.' },
        { type: 'h2', id: 'login', text: 'How to log in to Pocket Option' },
        { type: 'image', src: IMG_LOGIN, alt: 'Pocket Option Sign In form with e-mail, password, Remember me and Password recovery', caption: 'The Sign In form: e-mail, password, “Remember me” and the “Password recovery” link.' },
        { type: 'ol', items: [
          'Go to the website and click Log In, or open the app.',
          'Enter the e-mail and password used at registration (or click Google/Facebook if you registered that way).',
          'Tick “Remember me” only on your own device.',
          'Click Sign In. If 2FA is enabled, enter the code from your authenticator app.',
        ] },
        { type: 'p', text: 'The same login works everywhere: the web terminal, the Android and iOS apps and the Windows/macOS desktop apps. You can be logged in on several devices at once; the balance and open trades sync in real time.' },
        { type: 'h2', id: 'recovery', text: 'Forgot your password? Password recovery' },
        { type: 'ol', items: [
          'On the login form click “Password recovery”.',
          'Enter the e-mail of your account and submit.',
          'Open the e-mail from Pocket Option and click the reset link (check Spam/Promotions if it is not in Inbox).',
          'Set a new password and log in.',
        ] },
        { type: 'p', text: 'If you registered via Google or Facebook and never set a password, simply use the social button again — no recovery is needed. If you no longer have access to the registration e-mail, contact support from inside the app or via the contact form; they will ask you to verify your identity before changing the e-mail.' },
        { type: 'h2', id: 'security', text: 'Securing your account' },
        { type: 'ul', items: [
          'Enable two-factor authentication (Profile → Security) with Google Authenticator or a similar app.',
          'Use a unique password not reused from other websites; a password manager helps.',
          'Only log in via the official domain or official apps. Bookmark the site and ignore “login” links from e-mails or social media.',
          'Complete identity verification early so that withdrawals are not delayed later.',
        ] },
        { type: 'warn', title: 'Beware of fake login pages', text: 'Phishing sites copy the Pocket Option login form to steal credentials. Check the address bar before typing your password and never share your 2FA code with anyone, including people claiming to be support.' },
        { type: 'h2', id: 'problems', text: 'Common login problems and fixes' },
        { type: 'table', head: ['Problem', 'Likely cause', 'Fix'], rows: [
          ['“Wrong e-mail or password”', 'Typo, Caps Lock, old password', 'Retype carefully or use Password recovery'],
          ['Login works but withdrawal is blocked', 'E-mail not confirmed / KYC pending', 'Confirm e-mail, upload documents in Profile'],
          ['Site does not open or shows a country notice', 'Region not served or ISP block', 'Check the accepted countries; use the mobile app'],
          ['App keeps logging out', 'Outdated app version or cache', 'Update the app, clear cache, log in again'],
          ['No confirmation or recovery e-mail', 'Filtered as spam', 'Check Spam/Promotions; add the sender to contacts; request again'],
          ['Account blocked', 'Duplicate account or terms violation', 'Contact support with your account e-mail'],
        ] },
        { type: 'cta', text: 'Ready to start? Registration takes a minute and the demo account is available immediately after sign-up.', label: 'Register on Pocket Option' },
      ],
      faq: [
        { q: 'How do I create a Pocket Option account?', a: 'Click Registration, enter e-mail and password (or use Google/Facebook), accept the agreement and click Sign up. Then confirm your e-mail.' },
        { q: 'Is registration free?', a: 'Yes. Creating an account costs nothing and gives instant access to the $50,000 demo. A deposit is needed only for real trading (from $5).' },
        { q: 'Can I log in without a password?', a: 'Yes, if you registered with Google or Facebook — use the same button on the login form.' },
        { q: 'How do I reset my Pocket Option password?', a: 'Click “Password recovery” on the login form, enter your e-mail and follow the link in the message you receive.' },
        { q: 'Can I have two Pocket Option accounts?', a: 'No. One account per person is allowed; duplicates are closed during verification and may cause withdrawal issues.' },
        { q: 'Why can’t I log in from my country?', a: 'Pocket Option does not serve some regions (USA, EU/EEA, UK, Canada, Australia, Israel and others). Check the current list in the terms.' },
      ],
    },
    pt: {
      title: 'Login e cadastro na Pocket Option: como criar conta, entrar e recuperar a senha',
      metaTitle: 'Pocket Option Login e Cadastro – Criar Conta, Entrar, Senha',
      metaDescription:
        'Guia de login e cadastro na Pocket Option: crie a conta com e-mail, Google ou Facebook, confirme o e-mail, entre com segurança, ative 2FA e resolva erros de login.',
      excerpt:
        'Cadastro e login pocketoption passo a passo: formulário de registro, login social, confirmação de e-mail, recuperação de senha, 2FA e solução de problemas.',
      coverAlt: 'Página inicial da Pocket Option com o painel de cadastro e login',
      keyTakeaways: [
        'O cadastro na Pocket Option leva cerca de um minuto: e-mail + senha, ou um clique com Google ou Facebook.',
        'Confirme seu e-mail logo após o cadastro — é obrigatório para saques e recuperação de senha.',
        'Entre em pocketoption.com ou no app mobile/desktop com as mesmas credenciais; ative a autenticação em dois fatores em Perfil → Segurança.',
        'Esqueceu a senha? Use “Recuperar senha” no formulário de login e siga o link enviado por e-mail.',
        'A maioria dos problemas de login vem de e-mail não confirmado, erro de digitação, país bloqueado ou app desatualizado.',
      ],
      blocks: [
        { type: 'p', text: 'Toda jornada na Pocket Option começa em duas telas: o formulário de cadastro e o de login. Ambos são simples, mas alguns detalhes — confirmar o e-mail, escolher o país correto, ativar 2FA — evitam dores de cabeça depois, principalmente na hora do saque. Este guia mostra o cadastro e o login pocketoption no site e no app, além do que fazer quando não consegue entrar.' },
        { type: 'h2', id: 'requirements', text: 'Antes de se cadastrar' },
        { type: 'ul', items: [
          'Você precisa ter 18 anos ou mais e morar em um país atendido pela Pocket Option (EUA, UE/EEE, Reino Unido, Canadá, Austrália e Israel não são aceitos).',
          'Use um e-mail que você controla — será necessário para confirmação, aprovação de saques e redefinição de senha.',
          'Cadastre-se apenas em seu próprio nome. Contas duplicadas ou para terceiros são encerradas na verificação.',
          'Tenha um código promocional em mãos se quiser (ex.: 50START para +50% no primeiro depósito); ele é inserido no cadastro.',
        ] },
        { type: 'h2', id: 'register', text: 'Como se cadastrar na Pocket Option (passo a passo)' },
        { type: 'image', src: IMG_REGISTER, alt: 'Formulário de cadastro da Pocket Option com e-mail, senha, código promocional e botão Cadastrar', caption: 'Formulário de cadastro: e-mail, senha, código promocional opcional, caixa de aceite.' },
        { type: 'ol', items: [
          'Abra o site oficial e clique em Cadastro (canto superior direito no desktop, no menu no mobile).',
          'Informe seu e-mail e crie uma senha com pelo menos 8 caracteres, letras e números.',
          'Opcionalmente, insira um código promocional no campo “Digite o código promocional (se tiver)”.',
          'Marque “Li e aceito o Contrato de oferta pública”.',
          'Clique em Cadastrar. A conta é criada e você entra direto no terminal com saldo demo de $50.000.',
          'Abra o e-mail de confirmação e clique no link. Seu e-mail está verificado.',
        ] },
        { type: 'tip', title: 'Cadastro em um clique', text: 'Prefere não digitar? Clique em “Facebook” ou “Google” abaixo do formulário. A conta é criada com o e-mail do seu perfil social — você ainda pode definir uma senha separada depois, no Perfil.' },
        { type: 'h2', id: 'login', text: 'Como fazer login na Pocket Option' },
        { type: 'image', src: IMG_LOGIN, alt: 'Formulário de login da Pocket Option com e-mail, senha, Lembrar-me e Recuperar senha', caption: 'Formulário de login: e-mail, senha, “Lembrar-me” e o link “Recuperar senha”.' },
        { type: 'ol', items: [
          'Acesse o site e clique em Entrar, ou abra o app.',
          'Digite o e-mail e a senha usados no cadastro (ou clique em Google/Facebook se cadastrou assim).',
          'Marque “Lembrar-me” apenas no seu próprio dispositivo.',
          'Clique em Entrar. Se o 2FA estiver ativo, informe o código do app autenticador.',
        ] },
        { type: 'p', text: 'O mesmo login funciona em todo lugar: terminal web, apps Android e iOS e apps desktop Windows/macOS. Você pode estar logado em vários dispositivos ao mesmo tempo; saldo e operações abertas sincronizam em tempo real.' },
        { type: 'h2', id: 'recovery', text: 'Esqueceu a senha? Recuperação de senha' },
        { type: 'ol', items: [
          'No formulário de login, clique em “Recuperar senha”.',
          'Informe o e-mail da conta e envie.',
          'Abra o e-mail da Pocket Option e clique no link de redefinição (verifique Spam/Promoções se não estiver na caixa de entrada).',
          'Defina uma nova senha e faça login.',
        ] },
        { type: 'p', text: 'Se você se cadastrou via Google ou Facebook e nunca definiu senha, basta usar o botão social novamente — não precisa recuperar nada. Se não tem mais acesso ao e-mail do cadastro, contate o suporte pelo app ou pelo formulário de contato; eles pedirão verificação de identidade antes de trocar o e-mail.' },
        { type: 'h2', id: 'security', text: 'Protegendo sua conta' },
        { type: 'ul', items: [
          'Ative a autenticação em dois fatores (Perfil → Segurança) com Google Authenticator ou app similar.',
          'Use uma senha única, não reaproveitada de outros sites; um gerenciador de senhas ajuda.',
          'Entre apenas pelo domínio oficial ou apps oficiais. Salve o site nos favoritos e ignore links de “login” vindos de e-mails ou redes sociais.',
          'Faça a verificação de identidade cedo para que os saques não atrasem depois.',
        ] },
        { type: 'warn', title: 'Cuidado com páginas de login falsas', text: 'Sites de phishing copiam o formulário de login da Pocket Option para roubar credenciais. Confira a barra de endereço antes de digitar a senha e nunca compartilhe seu código 2FA com ninguém, inclusive quem diz ser do suporte.' },
        { type: 'h2', id: 'problems', text: 'Problemas comuns de login e soluções' },
        { type: 'table', head: ['Problema', 'Causa provável', 'Solução'], rows: [
          ['“E-mail ou senha incorretos”', 'Erro de digitação, Caps Lock, senha antiga', 'Digite com cuidado ou use Recuperar senha'],
          ['Login funciona, mas o saque está bloqueado', 'E-mail não confirmado / KYC pendente', 'Confirme o e-mail, envie documentos no Perfil'],
          ['Site não abre ou mostra aviso de país', 'Região não atendida ou bloqueio do provedor', 'Verifique os países aceitos; use o app mobile'],
          ['App desloga sozinho', 'Versão desatualizada ou cache', 'Atualize o app, limpe o cache, entre de novo'],
          ['Não chega e-mail de confirmação ou recuperação', 'Filtrado como spam', 'Verifique Spam/Promoções; adicione o remetente aos contatos; solicite de novo'],
          ['Conta bloqueada', 'Conta duplicada ou violação dos termos', 'Contate o suporte com o e-mail da conta'],
        ] },
        { type: 'cta', text: 'Pronto para começar? O cadastro leva um minuto e a conta demo fica disponível logo após.', label: 'Cadastrar na Pocket Option' },
      ],
      faq: [
        { q: 'Como criar uma conta na Pocket Option?', a: 'Clique em Cadastro, informe e-mail e senha (ou use Google/Facebook), aceite o contrato e clique em Cadastrar. Depois confirme o e-mail.' },
        { q: 'O cadastro é gratuito?', a: 'Sim. Criar a conta não custa nada e dá acesso imediato à demo de $50.000. O depósito só é necessário para operar com dinheiro real (a partir de $5).' },
        { q: 'Posso entrar sem senha?', a: 'Sim, se você se cadastrou com Google ou Facebook — use o mesmo botão no formulário de login.' },
        { q: 'Como redefinir a senha da Pocket Option?', a: 'Clique em “Recuperar senha” no formulário de login, informe seu e-mail e siga o link da mensagem recebida.' },
        { q: 'Posso ter duas contas na Pocket Option?', a: 'Não. É permitida uma conta por pessoa; duplicadas são encerradas na verificação e podem causar problemas de saque.' },
        { q: 'Por que não consigo entrar do meu país?', a: 'A Pocket Option não atende algumas regiões (EUA, UE/EEE, Reino Unido, Canadá, Austrália, Israel e outras). Consulte a lista atual nos termos.' },
      ],
    },
    es: {
      title: 'Login y registro en Pocket Option: cómo crear una cuenta, iniciar sesión y recuperar la contraseña',
      metaTitle: 'Pocket Option Login y Registro – Crear Cuenta, Entrar, Clave',
      metaDescription:
        'Guía de login y registro en Pocket Option: crea la cuenta con e-mail, Google o Facebook, confirma el e-mail, inicia sesión seguro, activa 2FA y soluciona errores de acceso.',
      excerpt:
        'Registro e inicio de sesión en pocketoption paso a paso: formulario, acceso social, confirmación de e-mail, recuperación de contraseña, 2FA y solución de problemas.',
      coverAlt: 'Página de inicio de Pocket Option con el panel de registro e inicio de sesión',
      keyTakeaways: [
        'El registro en Pocket Option toma un minuto: e-mail + contraseña, o un clic con Google o Facebook.',
        'Confirma tu e-mail justo después de registrarte: es obligatorio para retiros y recuperación de contraseña.',
        'Inicia sesión en pocketoption.com o en la app móvil/de escritorio con las mismas credenciales; activa la autenticación en dos pasos en Perfil → Seguridad.',
        '¿Olvidaste la contraseña? Usa “Recuperar contraseña” en el formulario de acceso y sigue el enlace del e-mail.',
        'La mayoría de problemas de acceso se deben a un e-mail sin confirmar, un error de escritura, un país bloqueado o una app desactualizada.',
      ],
      blocks: [
        { type: 'p', text: 'Todo camino en Pocket Option empieza en dos pantallas: el formulario de registro y el de inicio de sesión. Ambos son sencillos, pero algunos detalles — confirmar el e-mail, elegir el país correcto, activar 2FA — te ahorran problemas después, sobre todo al retirar. Esta guía recorre el registro y el login de pocketoption en la web y en la app, y qué hacer cuando no puedes entrar.' },
        { type: 'h2', id: 'requirements', text: 'Antes de registrarte' },
        { type: 'ul', items: [
          'Debes tener 18 años o más y residir en un país atendido por Pocket Option (EE. UU., UE/EEE, Reino Unido, Canadá, Australia e Israel no se aceptan).',
          'Usa un e-mail que controles: lo necesitarás para confirmar, aprobar retiros y restablecer la contraseña.',
          'Regístrate solo a tu nombre. Las cuentas duplicadas o de terceros se cierran en la verificación.',
          'Ten a mano un código promocional si quieres uno (p. ej. 50START para +50% en el primer depósito); se introduce al registrarte.',
        ] },
        { type: 'h2', id: 'register', text: 'Cómo registrarse en Pocket Option (paso a paso)' },
        { type: 'image', src: IMG_REGISTER, alt: 'Formulario de registro de Pocket Option con e-mail, contraseña, código promocional y botón Registrarse', caption: 'El formulario de registro: e-mail, contraseña, código promocional opcional y casilla de aceptación.' },
        { type: 'ol', items: [
          'Abre el sitio oficial y pulsa Registro (arriba a la derecha en escritorio, en el menú en móvil).',
          'Introduce tu e-mail y crea una contraseña de al menos 8 caracteres con letras y números.',
          'Opcionalmente introduce un código promocional en el campo “Introduce el código promocional (si lo tienes)”.',
          'Marca “He leído y acepto el Acuerdo de oferta pública”.',
          'Pulsa Registrarse. La cuenta se crea y entras directamente al terminal con un saldo demo de $50.000.',
          'Abre el e-mail de confirmación y haz clic en el enlace. Tu e-mail queda verificado.',
        ] },
        { type: 'tip', title: 'Registro en un clic', text: '¿Prefieres no escribir? Pulsa “Facebook” o “Google” bajo el formulario. La cuenta se crea con el e-mail de tu perfil social; luego puedes fijar una contraseña propia en Perfil.' },
        { type: 'h2', id: 'login', text: 'Cómo iniciar sesión en Pocket Option' },
        { type: 'image', src: IMG_LOGIN, alt: 'Formulario de inicio de sesión de Pocket Option con e-mail, contraseña, Recordarme y Recuperar contraseña', caption: 'El formulario de acceso: e-mail, contraseña, “Recordarme” y el enlace “Recuperar contraseña”.' },
        { type: 'ol', items: [
          'Entra en el sitio y pulsa Iniciar sesión, o abre la app.',
          'Introduce el e-mail y la contraseña del registro (o pulsa Google/Facebook si te registraste así).',
          'Marca “Recordarme” solo en tu propio dispositivo.',
          'Pulsa Iniciar sesión. Si tienes 2FA activo, introduce el código de tu app de autenticación.',
        ] },
        { type: 'p', text: 'El mismo acceso funciona en todas partes: terminal web, apps de Android e iOS y apps de escritorio para Windows/macOS. Puedes estar conectado en varios dispositivos a la vez; el saldo y las operaciones abiertas se sincronizan en tiempo real.' },
        { type: 'h2', id: 'recovery', text: '¿Olvidaste la contraseña? Recuperación' },
        { type: 'ol', items: [
          'En el formulario de acceso pulsa “Recuperar contraseña”.',
          'Introduce el e-mail de tu cuenta y envía.',
          'Abre el e-mail de Pocket Option y pulsa el enlace de restablecimiento (revisa Spam/Promociones si no está en la bandeja de entrada).',
          'Fija una nueva contraseña e inicia sesión.',
        ] },
        { type: 'p', text: 'Si te registraste con Google o Facebook y nunca fijaste contraseña, simplemente usa de nuevo el botón social; no hace falta recuperar nada. Si ya no tienes acceso al e-mail del registro, contacta con soporte desde la app o el formulario de contacto; te pedirán verificar tu identidad antes de cambiar el e-mail.' },
        { type: 'h2', id: 'security', text: 'Cómo proteger tu cuenta' },
        { type: 'ul', items: [
          'Activa la autenticación en dos pasos (Perfil → Seguridad) con Google Authenticator o una app similar.',
          'Usa una contraseña única, no reutilizada de otros sitios; un gestor de contraseñas ayuda.',
          'Inicia sesión solo a través del dominio oficial o las apps oficiales. Guarda el sitio en favoritos e ignora enlaces de “login” en e-mails o redes sociales.',
          'Completa la verificación de identidad pronto para que los retiros no se retrasen después.',
        ] },
        { type: 'warn', title: 'Cuidado con páginas de acceso falsas', text: 'Los sitios de phishing copian el formulario de Pocket Option para robar credenciales. Revisa la barra de direcciones antes de escribir tu contraseña y nunca compartas tu código 2FA con nadie, ni siquiera con quien diga ser del soporte.' },
        { type: 'h2', id: 'problems', text: 'Problemas frecuentes de acceso y soluciones' },
        { type: 'table', head: ['Problema', 'Causa probable', 'Solución'], rows: [
          ['“E-mail o contraseña incorrectos”', 'Error de escritura, Bloq Mayús, contraseña antigua', 'Vuelve a escribir con cuidado o usa Recuperar contraseña'],
          ['El acceso funciona pero el retiro está bloqueado', 'E-mail sin confirmar / KYC pendiente', 'Confirma el e-mail, sube documentos en Perfil'],
          ['El sitio no abre o muestra un aviso de país', 'Región no atendida o bloqueo del proveedor', 'Revisa los países aceptados; usa la app móvil'],
          ['La app cierra la sesión sola', 'Versión desactualizada o caché', 'Actualiza la app, borra la caché, vuelve a entrar'],
          ['No llega el e-mail de confirmación o recuperación', 'Filtrado como spam', 'Revisa Spam/Promociones; añade el remitente a contactos; solicítalo de nuevo'],
          ['Cuenta bloqueada', 'Cuenta duplicada o incumplimiento de términos', 'Contacta con soporte con el e-mail de la cuenta'],
        ] },
        { type: 'cta', text: '¿Listo para empezar? El registro toma un minuto y la cuenta demo está disponible justo después.', label: 'Registrarse en Pocket Option' },
      ],
      faq: [
        { q: '¿Cómo creo una cuenta en Pocket Option?', a: 'Pulsa Registro, introduce e-mail y contraseña (o usa Google/Facebook), acepta el acuerdo y pulsa Registrarse. Después confirma tu e-mail.' },
        { q: '¿El registro es gratis?', a: 'Sí. Crear la cuenta no cuesta nada y da acceso inmediato a la demo de $50.000. El depósito solo es necesario para operar con dinero real (desde $5).' },
        { q: '¿Puedo entrar sin contraseña?', a: 'Sí, si te registraste con Google o Facebook: usa el mismo botón en el formulario de acceso.' },
        { q: '¿Cómo restablezco mi contraseña de Pocket Option?', a: 'Pulsa “Recuperar contraseña” en el formulario de acceso, introduce tu e-mail y sigue el enlace del mensaje que recibas.' },
        { q: '¿Puedo tener dos cuentas en Pocket Option?', a: 'No. Se permite una cuenta por persona; las duplicadas se cierran en la verificación y pueden causar problemas con los retiros.' },
        { q: '¿Por qué no puedo entrar desde mi país?', a: 'Pocket Option no atiende algunas regiones (EE. UU., UE/EEE, Reino Unido, Canadá, Australia, Israel y otras). Consulta la lista actual en los términos.' },
      ],
    },
    ru: {
      title: 'Вход и регистрация в Pocket Option: как создать аккаунт, войти и восстановить пароль',
      metaTitle: 'Pocket Option Вход и Регистрация – Создать Аккаунт, Войти',
      metaDescription:
        'Гид по входу и регистрации в Pocket Option: создание аккаунта через e-mail, Google или Facebook, подтверждение почты, безопасный вход, 2FA и решение ошибок входа.',
      excerpt:
        'Регистрация и вход в pocketoption по шагам: форма регистрации, вход через соцсети, подтверждение e-mail, восстановление пароля, 2FA и устранение проблем.',
      coverAlt: 'Главная страница Pocket Option с панелью регистрации и входа',
      keyTakeaways: [
        'Регистрация в Pocket Option занимает около минуты: e-mail + пароль либо вход в один клик через Google или Facebook.',
        'Подтвердите e-mail сразу после регистрации — он нужен для вывода средств и восстановления пароля.',
        'Входите на pocketoption.com или в мобильное/десктопное приложение с одними и теми же данными; включите двухфакторную аутентификацию в Профиль → Безопасность.',
        'Забыли пароль? Нажмите «Восстановление пароля» в форме входа и перейдите по ссылке из письма.',
        'Большинство проблем со входом связаны с неподтверждённым e-mail, опечаткой, заблокированной страной или устаревшей версией приложения.',
      ],
      blocks: [
        { type: 'p', text: 'Любой путь в Pocket Option начинается с двух экранов: формы регистрации и формы входа. Обе просты, но несколько деталей — подтверждение e-mail, правильная страна, включённая 2FA — избавят от проблем позже, особенно при выводе средств. В этом руководстве — регистрация и вход в pocketoption на сайте и в приложении, а также что делать, если войти не получается.' },
        { type: 'h2', id: 'requirements', text: 'Перед регистрацией' },
        { type: 'ul', items: [
          'Вам должно быть 18 лет или больше, и вы должны проживать в стране, которую обслуживает Pocket Option (США, ЕС/ЕЭЗ, Великобритания, Канада, Австралия и Израиль не принимаются).',
          'Используйте e-mail, к которому у вас есть доступ, — он понадобится для подтверждения, одобрения вывода и сброса пароля.',
          'Регистрируйтесь только на своё имя. Дубликаты и аккаунты на других людей закрываются при верификации.',
          'Подготовьте промокод, если хотите его использовать (например, 50START для +50% к первому депозиту); он вводится при регистрации.',
        ] },
        { type: 'h2', id: 'register', text: 'Как зарегистрироваться в Pocket Option (по шагам)' },
        { type: 'image', src: IMG_REGISTER, alt: 'Форма регистрации Pocket Option с полями e-mail, пароль, промокод и кнопкой Регистрация', caption: 'Форма регистрации: e-mail, пароль, необязательный промокод, чекбокс согласия.' },
        { type: 'ol', items: [
          'Откройте официальный сайт и нажмите «Регистрация» (справа сверху на компьютере, в меню на телефоне).',
          'Введите e-mail и придумайте пароль не короче 8 символов с буквами и цифрами.',
          'При желании введите промокод в поле «Введите промокод (если есть)».',
          'Отметьте «Я прочитал и принимаю Публичную оферту».',
          'Нажмите «Регистрация». Аккаунт создан, и вы сразу попадаете в терминал с демо-балансом $50 000.',
          'Откройте письмо с подтверждением и перейдите по ссылке. E-mail подтверждён.',
        ] },
        { type: 'tip', title: 'Регистрация в один клик', text: 'Не хотите ничего вводить? Нажмите «Facebook» или «Google» под формой. Аккаунт создаётся с e-mail вашего профиля в соцсети — отдельный пароль можно задать позже в Профиле.' },
        { type: 'h2', id: 'login', text: 'Как войти в Pocket Option' },
        { type: 'image', src: IMG_LOGIN, alt: 'Форма входа Pocket Option с полями e-mail, пароль, «Запомнить меня» и «Восстановление пароля»', caption: 'Форма входа: e-mail, пароль, «Запомнить меня» и ссылка «Восстановление пароля».' },
        { type: 'ol', items: [
          'Перейдите на сайт и нажмите «Войти» или откройте приложение.',
          'Введите e-mail и пароль, указанные при регистрации (или нажмите Google/Facebook, если регистрировались так).',
          'Отмечайте «Запомнить меня» только на своём устройстве.',
          'Нажмите «Войти». Если включена 2FA, введите код из приложения-аутентификатора.',
        ] },
        { type: 'p', text: 'Один и тот же логин работает везде: в веб-терминале, приложениях для Android и iOS и десктопных приложениях для Windows/macOS. Можно быть авторизованным на нескольких устройствах одновременно; баланс и открытые сделки синхронизируются в реальном времени.' },
        { type: 'h2', id: 'recovery', text: 'Забыли пароль? Восстановление' },
        { type: 'ol', items: [
          'В форме входа нажмите «Восстановление пароля».',
          'Введите e-mail аккаунта и отправьте.',
          'Откройте письмо от Pocket Option и перейдите по ссылке сброса (проверьте «Спам»/«Промоакции», если письма нет во входящих).',
          'Задайте новый пароль и войдите.',
        ] },
        { type: 'p', text: 'Если вы регистрировались через Google или Facebook и не задавали пароль, просто снова нажмите кнопку соцсети — восстанавливать ничего не нужно. Если доступа к e-mail регистрации больше нет, обратитесь в поддержку из приложения или через форму связи; перед сменой e-mail вас попросят подтвердить личность.' },
        { type: 'h2', id: 'security', text: 'Защита аккаунта' },
        { type: 'ul', items: [
          'Включите двухфакторную аутентификацию (Профиль → Безопасность) через Google Authenticator или аналог.',
          'Используйте уникальный пароль, не повторяющий пароли с других сайтов; поможет менеджер паролей.',
          'Входите только через официальный домен или официальные приложения. Добавьте сайт в закладки и игнорируйте ссылки «войти» из писем и соцсетей.',
          'Пройдите верификацию личности заранее, чтобы позже не задерживались выводы.',
        ] },
        { type: 'warn', title: 'Остерегайтесь поддельных страниц входа', text: 'Фишинговые сайты копируют форму входа Pocket Option, чтобы украсть данные. Проверяйте адресную строку перед вводом пароля и никогда не сообщайте код 2FA никому, включая «сотрудников поддержки».' },
        { type: 'h2', id: 'problems', text: 'Частые проблемы со входом и их решение' },
        { type: 'table', head: ['Проблема', 'Вероятная причина', 'Решение'], rows: [
          ['«Неверный e-mail или пароль»', 'Опечатка, Caps Lock, старый пароль', 'Введите внимательно или воспользуйтесь восстановлением пароля'],
          ['Вход работает, но вывод заблокирован', 'E-mail не подтверждён / KYC не пройдена', 'Подтвердите e-mail, загрузите документы в Профиле'],
          ['Сайт не открывается или показывает уведомление о стране', 'Регион не обслуживается или блокировка провайдера', 'Проверьте список стран; используйте мобильное приложение'],
          ['Приложение постоянно выходит из аккаунта', 'Устаревшая версия или кэш', 'Обновите приложение, очистите кэш, войдите снова'],
          ['Не приходит письмо подтверждения или восстановления', 'Попало в спам', 'Проверьте «Спам»/«Промоакции»; добавьте отправителя в контакты; запросите повторно'],
          ['Аккаунт заблокирован', 'Дубликат аккаунта или нарушение условий', 'Обратитесь в поддержку, указав e-mail аккаунта'],
        ] },
        { type: 'cta', text: 'Готовы начать? Регистрация занимает минуту, а демо-счёт доступен сразу после неё.', label: 'Регистрация на Pocket Option' },
      ],
      faq: [
        { q: 'Как создать аккаунт Pocket Option?', a: 'Нажмите «Регистрация», введите e-mail и пароль (или используйте Google/Facebook), примите соглашение и нажмите кнопку регистрации. Затем подтвердите e-mail.' },
        { q: 'Регистрация бесплатная?', a: 'Да. Создание аккаунта ничего не стоит и сразу открывает демо на $50 000. Депозит нужен только для реальной торговли (от $5).' },
        { q: 'Можно ли войти без пароля?', a: 'Да, если вы регистрировались через Google или Facebook — нажмите ту же кнопку в форме входа.' },
        { q: 'Как сбросить пароль Pocket Option?', a: 'Нажмите «Восстановление пароля» в форме входа, введите e-mail и перейдите по ссылке из полученного письма.' },
        { q: 'Можно ли иметь два аккаунта Pocket Option?', a: 'Нет. Разрешён один аккаунт на человека; дубликаты закрываются при верификации и могут привести к проблемам с выводом.' },
        { q: 'Почему я не могу войти из своей страны?', a: 'Pocket Option не обслуживает некоторые регионы (США, ЕС/ЕЭЗ, Великобритания, Канада, Австралия, Израиль и другие). Актуальный список — в условиях.' },
      ],
    },
    id: {
      title: 'Login dan registrasi Pocket Option: cara daftar, masuk, dan memulihkan kata sandi',
      metaTitle: 'Pocket Option Login & Daftar – Registrasi, Masuk, Pulihkan',
      metaDescription:
        'Panduan login dan registrasi Pocket Option: buat akun dengan e-mail, Google, atau Facebook, konfirmasi e-mail, masuk dengan aman, aktifkan 2FA, dan atasi error login.',
      excerpt:
        'Daftar dan login pocketoption langkah demi langkah: formulir registrasi, login sosial, konfirmasi e-mail, pemulihan kata sandi, 2FA, dan pemecahan masalah.',
      coverAlt: 'Halaman utama Pocket Option dengan panel registrasi dan login',
      keyTakeaways: [
        'Registrasi di Pocket Option memakan waktu sekitar satu menit: e-mail + kata sandi, atau satu klik dengan Google atau Facebook.',
        'Konfirmasi e-mail segera setelah mendaftar — wajib untuk penarikan dan pemulihan kata sandi.',
        'Login di pocketoption.com atau aplikasi mobile/desktop dengan kredensial yang sama; aktifkan autentikasi dua faktor di Profil → Keamanan.',
        'Lupa kata sandi? Gunakan “Pemulihan kata sandi” di formulir login dan ikuti tautan di e-mail.',
        'Sebagian besar masalah login disebabkan e-mail belum dikonfirmasi, salah ketik, negara diblokir, atau aplikasi usang.',
      ],
      blocks: [
        { type: 'p', text: 'Setiap perjalanan di Pocket Option dimulai dari dua layar: formulir registrasi dan formulir login. Keduanya sederhana, tetapi beberapa detail — konfirmasi e-mail, memilih negara yang benar, mengaktifkan 2FA — menghemat masalah di kemudian hari, terutama saat penarikan. Panduan ini membahas daftar dan login pocketoption di situs web dan aplikasi, plus apa yang harus dilakukan jika tidak bisa masuk.' },
        { type: 'h2', id: 'requirements', text: 'Sebelum mendaftar' },
        { type: 'ul', items: [
          'Anda harus berusia 18 tahun ke atas dan tinggal di negara yang dilayani Pocket Option (AS, UE/EEA, Inggris, Kanada, Australia, dan Israel tidak diterima).',
          'Gunakan e-mail yang Anda kendalikan — dibutuhkan untuk konfirmasi, persetujuan penarikan, dan reset kata sandi.',
          'Daftar hanya atas nama sendiri. Akun ganda atau akun untuk orang lain ditutup saat verifikasi.',
          'Siapkan kode promo jika ingin (misalnya 50START untuk +50% deposit pertama); kode dimasukkan saat registrasi.',
        ] },
        { type: 'h2', id: 'register', text: 'Cara daftar di Pocket Option (langkah demi langkah)' },
        { type: 'image', src: IMG_REGISTER, alt: 'Formulir registrasi Pocket Option dengan e-mail, kata sandi, kode promo, dan tombol Daftar', caption: 'Formulir registrasi: e-mail, kata sandi, kode promo opsional, kotak persetujuan.' },
        { type: 'ol', items: [
          'Buka situs resmi dan klik Registrasi (kanan atas di desktop, di menu pada mobile).',
          'Masukkan e-mail dan buat kata sandi minimal 8 karakter dengan huruf dan angka.',
          'Opsional: masukkan kode promo di kolom “Masukkan kode promo (jika ada)”.',
          'Centang “Saya telah membaca dan menyetujui Perjanjian penawaran publik”.',
          'Klik Daftar. Akun dibuat dan Anda langsung masuk ke terminal trading dengan saldo demo $50.000.',
          'Buka e-mail konfirmasi dan klik tautannya. E-mail Anda kini terverifikasi.',
        ] },
        { type: 'tip', title: 'Daftar satu klik', text: 'Tidak ingin mengetik? Klik “Facebook” atau “Google” di bawah formulir. Akun dibuat dengan e-mail profil sosial Anda — kata sandi terpisah tetap bisa diatur nanti di Profil.' },
        { type: 'h2', id: 'login', text: 'Cara login ke Pocket Option' },
        { type: 'image', src: IMG_LOGIN, alt: 'Formulir Masuk Pocket Option dengan e-mail, kata sandi, Ingat saya, dan Pemulihan kata sandi', caption: 'Formulir Masuk: e-mail, kata sandi, “Ingat saya”, dan tautan “Pemulihan kata sandi”.' },
        { type: 'ol', items: [
          'Buka situs dan klik Masuk, atau buka aplikasi.',
          'Masukkan e-mail dan kata sandi yang dipakai saat registrasi (atau klik Google/Facebook jika mendaftar dengan cara itu).',
          'Centang “Ingat saya” hanya di perangkat Anda sendiri.',
          'Klik Masuk. Jika 2FA aktif, masukkan kode dari aplikasi autentikator.',
        ] },
        { type: 'p', text: 'Login yang sama berlaku di mana saja: terminal web, aplikasi Android dan iOS, serta aplikasi desktop Windows/macOS. Anda bisa login di beberapa perangkat sekaligus; saldo dan trade terbuka tersinkron secara real time.' },
        { type: 'h2', id: 'recovery', text: 'Lupa kata sandi? Pemulihan kata sandi' },
        { type: 'ol', items: [
          'Di formulir login klik “Pemulihan kata sandi”.',
          'Masukkan e-mail akun Anda dan kirim.',
          'Buka e-mail dari Pocket Option dan klik tautan reset (cek Spam/Promosi jika tidak ada di Kotak Masuk).',
          'Atur kata sandi baru dan login.',
        ] },
        { type: 'p', text: 'Jika Anda mendaftar via Google atau Facebook dan belum pernah mengatur kata sandi, cukup gunakan tombol sosial lagi — tidak perlu pemulihan. Jika Anda tidak lagi bisa mengakses e-mail registrasi, hubungi dukungan dari dalam aplikasi atau lewat formulir kontak; mereka akan meminta verifikasi identitas sebelum mengganti e-mail.' },
        { type: 'h2', id: 'security', text: 'Mengamankan akun Anda' },
        { type: 'ul', items: [
          'Aktifkan autentikasi dua faktor (Profil → Keamanan) dengan Google Authenticator atau aplikasi serupa.',
          'Gunakan kata sandi unik yang tidak dipakai di situs lain; pengelola kata sandi membantu.',
          'Login hanya lewat domain resmi atau aplikasi resmi. Bookmark situsnya dan abaikan tautan “login” dari e-mail atau media sosial.',
          'Selesaikan verifikasi identitas lebih awal agar penarikan tidak tertunda nanti.',
        ] },
        { type: 'warn', title: 'Waspadai halaman login palsu', text: 'Situs phishing meniru formulir login Pocket Option untuk mencuri kredensial. Periksa bilah alamat sebelum mengetik kata sandi dan jangan pernah membagikan kode 2FA kepada siapa pun, termasuk yang mengaku dari dukungan.' },
        { type: 'h2', id: 'problems', text: 'Masalah login umum dan solusinya' },
        { type: 'table', head: ['Masalah', 'Kemungkinan penyebab', 'Solusi'], rows: [
          ['“E-mail atau kata sandi salah”', 'Salah ketik, Caps Lock, kata sandi lama', 'Ketik ulang dengan teliti atau gunakan Pemulihan kata sandi'],
          ['Login berhasil tetapi penarikan diblokir', 'E-mail belum dikonfirmasi / KYC tertunda', 'Konfirmasi e-mail, unggah dokumen di Profil'],
          ['Situs tidak terbuka atau menampilkan pemberitahuan negara', 'Wilayah tidak dilayani atau blokir ISP', 'Cek negara yang diterima; gunakan aplikasi mobile'],
          ['Aplikasi terus logout', 'Versi aplikasi usang atau cache', 'Perbarui aplikasi, hapus cache, login lagi'],
          ['E-mail konfirmasi atau pemulihan tidak masuk', 'Tersaring sebagai spam', 'Cek Spam/Promosi; tambahkan pengirim ke kontak; minta ulang'],
          ['Akun diblokir', 'Akun ganda atau pelanggaran ketentuan', 'Hubungi dukungan dengan e-mail akun Anda'],
        ] },
        { type: 'cta', text: 'Siap memulai? Registrasi hanya satu menit dan akun demo tersedia langsung setelah daftar.', label: 'Daftar di Pocket Option' },
      ],
      faq: [
        { q: 'Bagaimana cara membuat akun Pocket Option?', a: 'Klik Registrasi, masukkan e-mail dan kata sandi (atau gunakan Google/Facebook), setujui perjanjian, dan klik Daftar. Lalu konfirmasi e-mail Anda.' },
        { q: 'Apakah registrasi gratis?', a: 'Ya. Membuat akun tidak dipungut biaya dan langsung memberi akses ke demo $50.000. Deposit hanya diperlukan untuk trading riil (mulai $5).' },
        { q: 'Bisakah login tanpa kata sandi?', a: 'Ya, jika Anda mendaftar dengan Google atau Facebook — gunakan tombol yang sama di formulir login.' },
        { q: 'Bagaimana cara reset kata sandi Pocket Option?', a: 'Klik “Pemulihan kata sandi” di formulir login, masukkan e-mail, dan ikuti tautan di pesan yang Anda terima.' },
        { q: 'Bisakah punya dua akun Pocket Option?', a: 'Tidak. Hanya satu akun per orang; akun ganda ditutup saat verifikasi dan bisa menimbulkan masalah penarikan.' },
        { q: 'Mengapa saya tidak bisa login dari negara saya?', a: 'Pocket Option tidak melayani beberapa wilayah (AS, UE/EEA, Inggris, Kanada, Australia, Israel, dan lainnya). Cek daftar terkini di syarat layanan.' },
      ],
    },
  },
};
