import type { BlogPost } from '../types';

const IMG_CHART = '/images/quick-start/5_1.webp';
const IMG_TRADE = '/images/quick-start/5_2.webp';

export const pocketOptionIndicators: BlogPost = {
  slug: 'pocket-option-indicators',
  category: 'strategy',
  cover: '/images/blog/pocket-option-indicators.webp',
  publishedAt: '2026-09-24',
  updatedAt: '2026-09-24',
  readingMinutes: 9,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option indicators for beginners: the 5 tools worth learning first and how to combine them',
      metaTitle: 'Best Pocket Option Indicators for Beginners – MA, RSI, MACD',
      metaDescription:
        'Pocket Option indicators for beginners: how to add them, how Moving Average, RSI, Bollinger Bands, MACD and Stochastic work, starter settings and a simple strategy.',
      excerpt:
        'The pocketoption terminal has dozens of indicators — beginners need five. This guide explains each one, the settings to start with and a simple two-indicator strategy to test on demo.',
      coverAlt: 'Trader analysing indicator charts on two laptops — technical analysis on Pocket Option',
      keyTakeaways: [
        'Indicators are added in one click from the sidebar of the Pocket Option chart and can be combined freely.',
        'Start with five: Moving Average (trend), RSI and Stochastic (momentum), Bollinger Bands (volatility), MACD (trend + momentum).',
        'One indicator alone gives too many false signals; two from different families that agree is the beginner standard.',
        'Test any combination on the $50,000 demo for at least 50 trades before using it with real money.',
      ],
      blocks: [
        { type: 'p', text: 'Indicators turn raw price movement into readable signals: is the market trending or moving sideways, is it overbought, is momentum fading? Pocket Option includes dozens of them built into the chart, free on both demo and real accounts. The problem for beginners is choice. This guide narrows pocketoption indicators to five that cover the essentials, explains what each one measures and shows how to combine two into a strategy you can actually test.' },
        { type: 'h2', id: 'add', text: 'How to add an indicator on Pocket Option' },
        { type: 'image', src: IMG_CHART, alt: 'Pocket Option chart with indicators panel open', caption: 'Indicators are added from the left sidebar of the chart.' },
        { type: 'ol', items: [
          'Open the terminal (demo or real) and click the “Indicators” icon in the left sidebar of the chart.',
          'Choose an indicator from the list — they are grouped as Trend, Oscillators, Volatility and others.',
          'Adjust the period and colours if needed and click Apply. The indicator draws on the chart or in a panel below it.',
          'Click the gear icon next to the indicator name to change settings later, or the cross to remove it.',
          'Switch the chart to candlesticks and a 1–5 minute timeframe — most indicator strategies for short expirations are built on that.',
        ] },
        { type: 'h2', id: 'ma', text: '1. Moving Average (MA) — the trend filter' },
        { type: 'p', text: 'A moving average smooths price over a set number of candles. When price is above a rising MA, the trend is up; below a falling MA, it is down. Beginners typically use an exponential MA (EMA) with a period of 20 or 50 on 1-minute candles. Its most useful job is not to give signals but to filter them: only take Up trades when price is above the EMA, Down trades when it is below.' },
        { type: 'h2', id: 'rsi', text: '2. RSI — overbought and oversold' },
        { type: 'p', text: 'The Relative Strength Index oscillates between 0 and 100. Readings above 70 mean the asset has risen fast and may pause or reverse (overbought); below 30 means the opposite (oversold). The default period of 14 works well. RSI is most reliable in a sideways market; in a strong trend it can stay overbought for a long time, which is why it is paired with a trend filter.' },
        { type: 'h2', id: 'bb', text: '3. Bollinger Bands — volatility and the “rubber band” effect' },
        { type: 'p', text: 'Bollinger Bands draw a moving average with two bands at a set number of standard deviations (default 20 periods, 2 deviations). Price touching the upper band in a quiet market often returns toward the middle; a squeeze — bands narrowing — usually precedes a burst of movement. In Pocket Option’s short-expiration trades, a touch of the outer band combined with an RSI extreme is a classic reversal setup.' },
        { type: 'h2', id: 'macd', text: '4. MACD — trend and momentum in one panel' },
        { type: 'p', text: 'MACD shows the difference between two EMAs (12 and 26) and a signal line (9). When the MACD line crosses above the signal line, momentum is turning up; a cross below means down. The histogram shows how strong the momentum is. MACD lags slightly, so it suits expirations of 5 minutes and longer rather than 30-second trades.' },
        { type: 'h2', id: 'stoch', text: '5. Stochastic Oscillator — the faster cousin of RSI' },
        { type: 'p', text: 'Stochastic compares the closing price to the recent range and produces two lines (%K and %D) on a 0–100 scale. Above 80 is overbought, below 20 oversold, and a cross of the two lines in those zones is the signal. It reacts faster than RSI, which makes it popular for 1–3 minute expirations — and also noisier, so always confirm with the trend.' },
        { type: 'h2', id: 'combine', text: 'A simple two-indicator strategy to test on demo' },
        { type: 'image', src: IMG_TRADE, alt: 'Placing a trade on Pocket Option after an indicator signal', caption: 'Enter only when the trend filter and the oscillator agree.' },
        { type: 'table', head: ['Element', 'Setting', 'Rule'], rows: [
          ['Chart', 'Candles, 1 minute', 'Liquid asset with payout ≥ 80%, e.g. EUR/USD'],
          ['Trend filter', 'EMA 50', 'Up trades only above EMA, Down trades only below'],
          ['Signal', 'RSI 14', 'Up: RSI leaves the zone below 30 upward. Down: RSI leaves the zone above 70 downward'],
          ['Expiration', '3–5 minutes', 'Three to five candles of the analysed timeframe'],
          ['Amount', '1–2% of balance', 'Minimum $1 on Pocket Option'],
          ['Stop for the day', '3 losses in a row or −5%', 'Review the journal before continuing'],
        ] },
        { type: 'p', text: 'The logic is simple: the EMA tells you which direction is allowed, the RSI tells you when a pullback inside that trend is ending. Skip signals against the trend, skip signals in the first minutes after news, and log every trade. After 50 demo trades you will know whether this setup suits your asset and schedule.' },
        { type: 'tip', title: 'Fewer indicators, clearer chart', text: 'Three indicators on one chart is the practical maximum. If you cannot explain in one sentence why each indicator is there, remove it.' },
        { type: 'h2', id: 'mistakes', text: 'Beginner mistakes with indicators' },
        { type: 'ul', items: [
          'Stacking five indicators from the same family (RSI + Stochastic + CCI) — they say the same thing and create false confidence.',
          'Changing settings after every losing trade instead of collecting a sample of 50+ trades.',
          'Trading oscillator signals against a strong trend.',
          'Using 5-second expirations, where indicator readings are mostly noise.',
          'Skipping the demo stage. Indicators feel obvious in hindsight and much less obvious in real time.',
        ] },
        { type: 'warn', title: 'No indicator predicts the market', text: 'Indicators describe what price has already done; they improve the odds of a well-timed entry but never remove risk. Trading on Pocket Option involves the risk of losing your deposit — use position sizing you can afford.' },
        { type: 'cta', text: 'Try these indicators on the free Pocket Option demo account — $50,000 in virtual funds, all indicators unlocked.', label: 'Open free demo account' },
      ],
      faq: [
        { q: 'Which indicators are available on Pocket Option?', a: 'Dozens, including Moving Averages, RSI, MACD, Bollinger Bands, Stochastic, CCI, ATR, Parabolic SAR, Ichimoku, Alligator and more, plus drawing tools. All of them are free on demo and real accounts.' },
        { q: 'What is the best indicator for beginners on Pocket Option?', a: 'There is no single best one. A trend filter (EMA 50) combined with a momentum oscillator (RSI 14) is the most common starting point because the two are easy to read and complement each other.' },
        { q: 'How many indicators should I use at once?', a: 'Two, at most three, from different families — for example one trend indicator and one oscillator. More indicators usually mean more conflicting signals, not more accuracy.' },
        { q: 'Do indicators work for 1-minute trades?', a: 'They can, but the shorter the expiration, the more noise there is. Most beginners get more consistent readings with 3–5 minute expirations on a 1-minute chart.' },
        { q: 'Can I save my indicator setup on Pocket Option?', a: 'Indicators stay on the chart for the asset while you are logged in, and the platform lets you keep several chart templates. Check the chart settings menu for saving options in your version of the terminal.' },
        { q: 'Are Pocket Option signals the same as indicators?', a: 'No. The Signals section shows ready-made trade ideas provided by the platform, while indicators are analysis tools you read yourself. Signals can be a starting point, but they still need risk management.' },
      ],
    },
    pt: {
      title: 'Indicadores da Pocket Option para iniciantes: as 5 ferramentas para aprender primeiro e como combiná-las',
      metaTitle: 'Melhores Indicadores Pocket Option para Iniciantes – MA, RSI',
      metaDescription:
        'Indicadores da Pocket Option para iniciantes: como adicioná-los, como funcionam Média Móvel, RSI, Bollinger, MACD e Estocástico e uma estratégia simples.',
      excerpt:
        'O terminal pocketoption tem dezenas de indicadores — iniciantes precisam de cinco. Este guia explica cada um, as configurações iniciais e uma estratégia simples com dois indicadores para testar na demo.',
      coverAlt: 'Trader analisando gráficos de indicadores em dois laptops — análise técnica na Pocket Option',
      keyTakeaways: [
        'Indicadores são adicionados com um clique na barra lateral do gráfico da Pocket Option e podem ser combinados livremente.',
        'Comece com cinco: Média Móvel (tendência), RSI e Estocástico (momento), Bandas de Bollinger (volatilidade), MACD (tendência + momento).',
        'Um indicador sozinho gera muitos sinais falsos; dois de famílias diferentes que concordam é o padrão para iniciantes.',
        'Teste qualquer combinação na demo de $50.000 por pelo menos 50 operações antes de usar dinheiro real.',
      ],
      blocks: [
        { type: 'p', text: 'Indicadores transformam o movimento bruto do preço em sinais legíveis: o mercado está em tendência ou lateral, está sobrecomprado, o momento está perdendo força? A Pocket Option inclui dezenas deles no gráfico, gratuitos tanto na demo quanto na conta real. O problema para iniciantes é a escolha. Este guia reduz os indicadores pocketoption a cinco que cobrem o essencial, explica o que cada um mede e mostra como combinar dois em uma estratégia que você realmente pode testar.' },
        { type: 'h2', id: 'add', text: 'Como adicionar um indicador na Pocket Option' },
        { type: 'image', src: IMG_CHART, alt: 'Gráfico da Pocket Option com o painel de indicadores aberto', caption: 'Indicadores são adicionados pela barra lateral esquerda do gráfico.' },
        { type: 'ol', items: [
          'Abra o terminal (demo ou real) e clique no ícone “Indicadores” na barra lateral esquerda do gráfico.',
          'Escolha um indicador da lista — agrupados em Tendência, Osciladores, Volatilidade e outros.',
          'Ajuste período e cores se necessário e clique em Aplicar. O indicador é desenhado no gráfico ou em um painel abaixo.',
          'Clique na engrenagem ao lado do nome do indicador para alterar configurações depois, ou no X para removê-lo.',
          'Coloque o gráfico em candles e timeframe de 1–5 minutos — a maioria das estratégias com indicadores para expirações curtas é construída assim.',
        ] },
        { type: 'h2', id: 'ma', text: '1. Média Móvel (MA) — o filtro de tendência' },
        { type: 'p', text: 'A média móvel suaviza o preço ao longo de um número definido de candles. Quando o preço está acima de uma MA ascendente, a tendência é de alta; abaixo de uma MA descendente, de baixa. Iniciantes geralmente usam uma média exponencial (EMA) de período 20 ou 50 em candles de 1 minuto. Sua função mais útil não é dar sinais, mas filtrá-los: só entre em Para cima quando o preço está acima da EMA, e em Para baixo quando está abaixo.' },
        { type: 'h2', id: 'rsi', text: '2. RSI — sobrecompra e sobrevenda' },
        { type: 'p', text: 'O Índice de Força Relativa oscila entre 0 e 100. Leituras acima de 70 indicam que o ativo subiu rápido e pode pausar ou reverter (sobrecomprado); abaixo de 30 é o oposto (sobrevendido). O período padrão de 14 funciona bem. O RSI é mais confiável em mercado lateral; em tendência forte pode ficar sobrecomprado por muito tempo, por isso é combinado com um filtro de tendência.' },
        { type: 'h2', id: 'bb', text: '3. Bandas de Bollinger — volatilidade e o efeito “elástico”' },
        { type: 'p', text: 'As Bandas de Bollinger desenham uma média móvel com duas bandas a um número definido de desvios-padrão (padrão 20 períodos, 2 desvios). O preço tocando a banda superior em mercado calmo costuma voltar para o meio; um aperto — bandas se estreitando — normalmente precede um movimento forte. Nas operações de expiração curta da Pocket Option, o toque na banda externa combinado com um extremo do RSI é um setup clássico de reversão.' },
        { type: 'h2', id: 'macd', text: '4. MACD — tendência e momento em um painel' },
        { type: 'p', text: 'O MACD mostra a diferença entre duas EMAs (12 e 26) e uma linha de sinal (9). Quando a linha MACD cruza acima da linha de sinal, o momento está virando para cima; cruzamento abaixo indica baixa. O histograma mostra a força do momento. O MACD tem leve atraso, então serve melhor para expirações de 5 minutos ou mais do que para operações de 30 segundos.' },
        { type: 'h2', id: 'stoch', text: '5. Oscilador Estocástico — o primo mais rápido do RSI' },
        { type: 'p', text: 'O Estocástico compara o fechamento com a faixa recente e produz duas linhas (%K e %D) em escala 0–100. Acima de 80 é sobrecompra, abaixo de 20 sobrevenda, e o cruzamento das duas linhas nessas zonas é o sinal. Reage mais rápido que o RSI, o que o torna popular para expirações de 1–3 minutos — e também mais ruidoso, então sempre confirme com a tendência.' },
        { type: 'h2', id: 'combine', text: 'Uma estratégia simples com dois indicadores para testar na demo' },
        { type: 'image', src: IMG_TRADE, alt: 'Abrindo uma operação na Pocket Option após sinal de indicador', caption: 'Entre apenas quando o filtro de tendência e o oscilador concordarem.' },
        { type: 'table', head: ['Elemento', 'Configuração', 'Regra'], rows: [
          ['Gráfico', 'Candles, 1 minuto', 'Ativo líquido com payout ≥ 80%, ex. EUR/USD'],
          ['Filtro de tendência', 'EMA 50', 'Para cima só acima da EMA, Para baixo só abaixo'],
          ['Sinal', 'RSI 14', 'Alta: RSI sai da zona abaixo de 30 para cima. Baixa: RSI sai da zona acima de 70 para baixo'],
          ['Expiração', '3–5 minutos', 'Três a cinco candles do timeframe analisado'],
          ['Valor', '1–2% do saldo', 'Mínimo $1 na Pocket Option'],
          ['Parar no dia', '3 perdas seguidas ou −5%', 'Revise o diário antes de continuar'],
        ] },
        { type: 'p', text: 'A lógica é simples: a EMA diz qual direção é permitida, o RSI diz quando um recuo dentro dessa tendência está terminando. Ignore sinais contra a tendência, ignore sinais nos primeiros minutos após notícias e registre cada operação. Após 50 operações na demo você saberá se esse setup serve para o seu ativo e horário.' },
        { type: 'tip', title: 'Menos indicadores, gráfico mais claro', text: 'Três indicadores em um gráfico é o máximo prático. Se você não consegue explicar em uma frase por que cada indicador está ali, remova-o.' },
        { type: 'h2', id: 'mistakes', text: 'Erros de iniciantes com indicadores' },
        { type: 'ul', items: [
          'Empilhar cinco indicadores da mesma família (RSI + Estocástico + CCI) — dizem a mesma coisa e criam falsa confiança.',
          'Mudar as configurações após cada perda em vez de coletar uma amostra de 50+ operações.',
          'Operar sinais de osciladores contra uma tendência forte.',
          'Usar expirações de 5 segundos, onde as leituras dos indicadores são quase só ruído.',
          'Pular a etapa da demo. Indicadores parecem óbvios em retrospecto e muito menos óbvios em tempo real.',
        ] },
        { type: 'warn', title: 'Nenhum indicador prevê o mercado', text: 'Indicadores descrevem o que o preço já fez; melhoram as chances de uma entrada bem cronometrada, mas nunca eliminam o risco. Negociar na Pocket Option envolve risco de perder o depósito — use um tamanho de posição que possa suportar.' },
        { type: 'cta', text: 'Experimente esses indicadores na conta demo gratuita da Pocket Option — $50.000 em fundos virtuais, todos os indicadores liberados.', label: 'Abrir conta demo grátis' },
      ],
      faq: [
        { q: 'Quais indicadores estão disponíveis na Pocket Option?', a: 'Dezenas, incluindo Médias Móveis, RSI, MACD, Bandas de Bollinger, Estocástico, CCI, ATR, Parabolic SAR, Ichimoku, Alligator e outros, além de ferramentas de desenho. Todos gratuitos na demo e na conta real.' },
        { q: 'Qual é o melhor indicador para iniciantes na Pocket Option?', a: 'Não existe um único melhor. Um filtro de tendência (EMA 50) combinado com um oscilador de momento (RSI 14) é o ponto de partida mais comum porque os dois são fáceis de ler e se complementam.' },
        { q: 'Quantos indicadores devo usar ao mesmo tempo?', a: 'Dois, no máximo três, de famílias diferentes — por exemplo um de tendência e um oscilador. Mais indicadores geralmente significam mais sinais conflitantes, não mais precisão.' },
        { q: 'Indicadores funcionam em operações de 1 minuto?', a: 'Podem funcionar, mas quanto menor a expiração, mais ruído. A maioria dos iniciantes obtém leituras mais consistentes com expirações de 3–5 minutos em gráfico de 1 minuto.' },
        { q: 'Posso salvar minha configuração de indicadores na Pocket Option?', a: 'Os indicadores permanecem no gráfico do ativo enquanto você está logado, e a plataforma permite manter vários modelos de gráfico. Verifique o menu de configurações do gráfico na sua versão do terminal.' },
        { q: 'Os sinais da Pocket Option são o mesmo que indicadores?', a: 'Não. A seção Sinais mostra ideias de operação prontas fornecidas pela plataforma, enquanto indicadores são ferramentas de análise que você mesmo lê. Sinais podem ser um ponto de partida, mas ainda exigem gestão de risco.' },
      ],
    },
    es: {
      title: 'Indicadores de Pocket Option para principiantes: las 5 herramientas que aprender primero y cómo combinarlas',
      metaTitle: 'Mejores Indicadores Pocket Option para Principiantes – MA, RSI',
      metaDescription:
        'Indicadores de Pocket Option para principiantes: cómo añadirlos, cómo funcionan Media Móvil, RSI, Bollinger, MACD y Estocástico y una estrategia sencilla.',
      excerpt:
        'El terminal pocketoption tiene decenas de indicadores — los principiantes necesitan cinco. Esta guía explica cada uno, los ajustes iniciales y una estrategia sencilla de dos indicadores para probar en demo.',
      coverAlt: 'Trader analizando gráficos de indicadores en dos portátiles — análisis técnico en Pocket Option',
      keyTakeaways: [
        'Los indicadores se añaden con un clic desde la barra lateral del gráfico de Pocket Option y se combinan libremente.',
        'Empieza con cinco: Media Móvil (tendencia), RSI y Estocástico (momento), Bandas de Bollinger (volatilidad), MACD (tendencia + momento).',
        'Un indicador solo da demasiadas señales falsas; dos de familias distintas que coincidan es el estándar para principiantes.',
        'Prueba cualquier combinación en la demo de $50.000 durante al menos 50 operaciones antes de usar dinero real.',
      ],
      blocks: [
        { type: 'p', text: 'Los indicadores convierten el movimiento bruto del precio en señales legibles: ¿el mercado está en tendencia o lateral, está sobrecomprado, se agota el momento? Pocket Option incluye decenas de ellos integrados en el gráfico, gratuitos tanto en demo como en cuenta real. El problema para los principiantes es elegir. Esta guía reduce los indicadores pocketoption a cinco que cubren lo esencial, explica qué mide cada uno y muestra cómo combinar dos en una estrategia que realmente puedes probar.' },
        { type: 'h2', id: 'add', text: 'Cómo añadir un indicador en Pocket Option' },
        { type: 'image', src: IMG_CHART, alt: 'Gráfico de Pocket Option con el panel de indicadores abierto', caption: 'Los indicadores se añaden desde la barra lateral izquierda del gráfico.' },
        { type: 'ol', items: [
          'Abre el terminal (demo o real) y pulsa el icono “Indicadores” en la barra lateral izquierda del gráfico.',
          'Elige un indicador de la lista — están agrupados en Tendencia, Osciladores, Volatilidad y otros.',
          'Ajusta el periodo y los colores si es necesario y pulsa Aplicar. El indicador se dibuja sobre el gráfico o en un panel inferior.',
          'Pulsa el engranaje junto al nombre del indicador para cambiar ajustes más tarde, o la cruz para quitarlo.',
          'Pon el gráfico en velas y un marco de 1–5 minutos — la mayoría de estrategias con indicadores para expiraciones cortas se construyen así.',
        ] },
        { type: 'h2', id: 'ma', text: '1. Media Móvil (MA) — el filtro de tendencia' },
        { type: 'p', text: 'Una media móvil suaviza el precio a lo largo de un número fijo de velas. Cuando el precio está por encima de una MA ascendente, la tendencia es alcista; por debajo de una MA descendente, bajista. Los principiantes suelen usar una media exponencial (EMA) de periodo 20 o 50 en velas de 1 minuto. Su función más útil no es dar señales sino filtrarlas: solo operaciones Arriba cuando el precio está sobre la EMA, Abajo cuando está debajo.' },
        { type: 'h2', id: 'rsi', text: '2. RSI — sobrecompra y sobreventa' },
        { type: 'p', text: 'El Índice de Fuerza Relativa oscila entre 0 y 100. Lecturas por encima de 70 indican que el activo ha subido rápido y puede pausar o girar (sobrecomprado); por debajo de 30 ocurre lo contrario (sobrevendido). El periodo por defecto de 14 funciona bien. El RSI es más fiable en mercado lateral; en una tendencia fuerte puede permanecer sobrecomprado mucho tiempo, por eso se combina con un filtro de tendencia.' },
        { type: 'h2', id: 'bb', text: '3. Bandas de Bollinger — volatilidad y el efecto “goma elástica”' },
        { type: 'p', text: 'Las Bandas de Bollinger dibujan una media móvil con dos bandas a un número fijo de desviaciones típicas (por defecto 20 periodos, 2 desviaciones). El precio tocando la banda superior en un mercado tranquilo suele volver hacia el centro; un estrechamiento de las bandas normalmente precede a un movimiento fuerte. En las operaciones de expiración corta de Pocket Option, el toque de la banda externa combinado con un extremo del RSI es un setup clásico de reversión.' },
        { type: 'h2', id: 'macd', text: '4. MACD — tendencia y momento en un panel' },
        { type: 'p', text: 'El MACD muestra la diferencia entre dos EMAs (12 y 26) y una línea de señal (9). Cuando la línea MACD cruza por encima de la señal, el momento gira al alza; un cruce por debajo indica baja. El histograma muestra la fuerza del momento. El MACD tiene un ligero retraso, así que encaja mejor con expiraciones de 5 minutos o más que con operaciones de 30 segundos.' },
        { type: 'h2', id: 'stoch', text: '5. Oscilador Estocástico — el primo rápido del RSI' },
        { type: 'p', text: 'El Estocástico compara el cierre con el rango reciente y produce dos líneas (%K y %D) en una escala 0–100. Por encima de 80 es sobrecompra, por debajo de 20 sobreventa, y el cruce de ambas líneas en esas zonas es la señal. Reacciona más rápido que el RSI, lo que lo hace popular para expiraciones de 1–3 minutos — y también más ruidoso, así que confirma siempre con la tendencia.' },
        { type: 'h2', id: 'combine', text: 'Una estrategia sencilla de dos indicadores para probar en demo' },
        { type: 'image', src: IMG_TRADE, alt: 'Abriendo una operación en Pocket Option tras una señal de indicador', caption: 'Entra solo cuando el filtro de tendencia y el oscilador coincidan.' },
        { type: 'table', head: ['Elemento', 'Ajuste', 'Regla'], rows: [
          ['Gráfico', 'Velas, 1 minuto', 'Activo líquido con pago ≥ 80%, p. ej. EUR/USD'],
          ['Filtro de tendencia', 'EMA 50', 'Arriba solo sobre la EMA, Abajo solo debajo'],
          ['Señal', 'RSI 14', 'Alza: el RSI sale de la zona bajo 30 hacia arriba. Baja: el RSI sale de la zona sobre 70 hacia abajo'],
          ['Expiración', '3–5 minutos', 'De tres a cinco velas del marco analizado'],
          ['Importe', '1–2% del saldo', 'Mínimo $1 en Pocket Option'],
          ['Parar por hoy', '3 pérdidas seguidas o −5%', 'Revisa el diario antes de continuar'],
        ] },
        { type: 'p', text: 'La lógica es simple: la EMA dice qué dirección está permitida, el RSI dice cuándo termina un retroceso dentro de esa tendencia. Omite señales contra la tendencia, omite señales en los primeros minutos tras noticias y registra cada operación. Tras 50 operaciones en demo sabrás si este setup encaja con tu activo y horario.' },
        { type: 'tip', title: 'Menos indicadores, gráfico más claro', text: 'Tres indicadores en un gráfico es el máximo práctico. Si no puedes explicar en una frase por qué está cada indicador, quítalo.' },
        { type: 'h2', id: 'mistakes', text: 'Errores de principiante con indicadores' },
        { type: 'ul', items: [
          'Apilar cinco indicadores de la misma familia (RSI + Estocástico + CCI) — dicen lo mismo y crean falsa confianza.',
          'Cambiar los ajustes tras cada operación perdedora en lugar de reunir una muestra de 50+ operaciones.',
          'Operar señales de osciladores contra una tendencia fuerte.',
          'Usar expiraciones de 5 segundos, donde las lecturas de los indicadores son casi todo ruido.',
          'Saltarse la etapa demo. Los indicadores parecen obvios a posteriori y mucho menos obvios en tiempo real.',
        ] },
        { type: 'warn', title: 'Ningún indicador predice el mercado', text: 'Los indicadores describen lo que el precio ya ha hecho; mejoran las probabilidades de una entrada oportuna pero nunca eliminan el riesgo. Operar en Pocket Option implica riesgo de perder el depósito — usa un tamaño de posición que puedas asumir.' },
        { type: 'cta', text: 'Prueba estos indicadores en la cuenta demo gratuita de Pocket Option — $50.000 en fondos virtuales, todos los indicadores desbloqueados.', label: 'Abrir cuenta demo gratis' },
      ],
      faq: [
        { q: '¿Qué indicadores hay disponibles en Pocket Option?', a: 'Decenas, incluidos Medias Móviles, RSI, MACD, Bandas de Bollinger, Estocástico, CCI, ATR, Parabolic SAR, Ichimoku, Alligator y más, además de herramientas de dibujo. Todos gratuitos en demo y cuenta real.' },
        { q: '¿Cuál es el mejor indicador para principiantes en Pocket Option?', a: 'No hay uno solo. Un filtro de tendencia (EMA 50) combinado con un oscilador de momento (RSI 14) es el punto de partida más común porque ambos son fáciles de leer y se complementan.' },
        { q: '¿Cuántos indicadores debo usar a la vez?', a: 'Dos, como máximo tres, de familias distintas — por ejemplo uno de tendencia y un oscilador. Más indicadores suelen significar más señales contradictorias, no más precisión.' },
        { q: '¿Funcionan los indicadores en operaciones de 1 minuto?', a: 'Pueden, pero cuanto más corta la expiración, más ruido. La mayoría de principiantes obtiene lecturas más consistentes con expiraciones de 3–5 minutos en un gráfico de 1 minuto.' },
        { q: '¿Puedo guardar mi configuración de indicadores en Pocket Option?', a: 'Los indicadores permanecen en el gráfico del activo mientras estás conectado, y la plataforma permite mantener varias plantillas de gráfico. Revisa el menú de ajustes del gráfico en tu versión del terminal.' },
        { q: '¿Las señales de Pocket Option son lo mismo que los indicadores?', a: 'No. La sección Señales muestra ideas de operación listas que ofrece la plataforma, mientras que los indicadores son herramientas de análisis que lees tú mismo. Las señales pueden ser un punto de partida, pero siguen necesitando gestión del riesgo.' },
      ],
    },
    ru: {
      title: 'Индикаторы Pocket Option для начинающих: 5 инструментов, которые стоит изучить первыми, и как их сочетать',
      metaTitle: 'Лучшие индикаторы Pocket Option для новичков – MA, RSI, MACD',
      metaDescription:
        'Индикаторы Pocket Option для новичков: как добавить на график, как работают скользящая средняя, RSI, Боллинджер, MACD и Стохастик, простая стратегия.',
      excerpt:
        'В терминале pocketoption десятки индикаторов — новичку нужно пять. В этом руководстве — каждый из них, стартовые настройки и простая стратегия на двух индикаторах для проверки на демо.',
      coverAlt: 'Трейдер анализирует графики с индикаторами на двух ноутбуках — технический анализ на Pocket Option',
      keyTakeaways: [
        'Индикаторы добавляются в один клик из боковой панели графика Pocket Option и свободно комбинируются.',
        'Начните с пяти: скользящая средняя (тренд), RSI и Стохастик (импульс), полосы Боллинджера (волатильность), MACD (тренд + импульс).',
        'Один индикатор даёт слишком много ложных сигналов; два из разных групп, которые согласуются, — стандарт для новичка.',
        'Проверяйте любую комбинацию на демо с $50 000 минимум на 50 сделках, прежде чем использовать реальные деньги.',
      ],
      blocks: [
        { type: 'p', text: 'Индикаторы превращают движение цены в читаемые сигналы: рынок в тренде или во флэте, перекуплен ли он, угасает ли импульс? В Pocket Option десятки индикаторов встроены в график и бесплатны на демо и реальном счёте. Проблема новичка — выбор. Это руководство сужает индикаторы pocketoption до пяти, покрывающих основное, объясняет, что измеряет каждый, и показывает, как объединить два в стратегию, которую реально можно протестировать.' },
        { type: 'h2', id: 'add', text: 'Как добавить индикатор на Pocket Option' },
        { type: 'image', src: IMG_CHART, alt: 'График Pocket Option с открытой панелью индикаторов', caption: 'Индикаторы добавляются из левой боковой панели графика.' },
        { type: 'ol', items: [
          'Откройте терминал (демо или реальный) и нажмите значок «Индикаторы» в левой боковой панели графика.',
          'Выберите индикатор из списка — они сгруппированы по разделам: трендовые, осцилляторы, волатильность и другие.',
          'При необходимости настройте период и цвета и нажмите «Применить». Индикатор появится на графике или в панели под ним.',
          'Нажмите шестерёнку рядом с названием индикатора, чтобы изменить настройки позже, или крестик, чтобы удалить его.',
          'Переключите график на свечи и таймфрейм 1–5 минут — большинство индикаторных стратегий для коротких экспираций строится на них.',
        ] },
        { type: 'h2', id: 'ma', text: '1. Скользящая средняя (MA) — фильтр тренда' },
        { type: 'p', text: 'Скользящая средняя сглаживает цену за заданное число свечей. Когда цена выше растущей MA — тренд восходящий; ниже падающей MA — нисходящий. Новички обычно используют экспоненциальную MA (EMA) с периодом 20 или 50 на минутных свечах. Её главная задача — не давать сигналы, а фильтровать их: сделки «Вверх» только когда цена выше EMA, «Вниз» — только когда ниже.' },
        { type: 'h2', id: 'rsi', text: '2. RSI — перекупленность и перепроданность' },
        { type: 'p', text: 'Индекс относительной силы колеблется от 0 до 100. Значения выше 70 означают, что актив быстро вырос и может остановиться или развернуться (перекупленность); ниже 30 — обратная ситуация (перепроданность). Стандартный период 14 работает хорошо. RSI надёжнее всего во флэте; в сильном тренде он может долго оставаться в зоне перекупленности, поэтому его сочетают с фильтром тренда.' },
        { type: 'h2', id: 'bb', text: '3. Полосы Боллинджера — волатильность и эффект «резинки»' },
        { type: 'p', text: 'Полосы Боллинджера — это скользящая средняя с двумя полосами на заданном числе стандартных отклонений (по умолчанию 20 периодов, 2 отклонения). Касание верхней полосы на спокойном рынке часто заканчивается возвратом к середине; сжатие полос обычно предвещает всплеск движения. В коротких сделках Pocket Option касание внешней полосы в сочетании с экстремумом RSI — классический разворотный сетап.' },
        { type: 'h2', id: 'macd', text: '4. MACD — тренд и импульс в одной панели' },
        { type: 'p', text: 'MACD показывает разницу между двумя EMA (12 и 26) и сигнальную линию (9). Когда линия MACD пересекает сигнальную снизу вверх, импульс разворачивается вверх; пересечение сверху вниз — вниз. Гистограмма показывает силу импульса. MACD слегка запаздывает, поэтому подходит для экспираций от 5 минут, а не для 30-секундных сделок.' },
        { type: 'h2', id: 'stoch', text: '5. Стохастический осциллятор — быстрый родственник RSI' },
        { type: 'p', text: 'Стохастик сравнивает цену закрытия с недавним диапазоном и рисует две линии (%K и %D) по шкале 0–100. Выше 80 — перекупленность, ниже 20 — перепроданность, а пересечение линий в этих зонах — сигнал. Он реагирует быстрее RSI, поэтому популярен для экспираций 1–3 минуты — и при этом более шумный, так что всегда подтверждайте трендом.' },
        { type: 'h2', id: 'combine', text: 'Простая стратегия на двух индикаторах для проверки на демо' },
        { type: 'image', src: IMG_TRADE, alt: 'Открытие сделки на Pocket Option после сигнала индикатора', caption: 'Входите только когда фильтр тренда и осциллятор согласуются.' },
        { type: 'table', head: ['Элемент', 'Настройка', 'Правило'], rows: [
          ['График', 'Свечи, 1 минута', 'Ликвидный актив с выплатой ≥ 80%, например EUR/USD'],
          ['Фильтр тренда', 'EMA 50', '«Вверх» только выше EMA, «Вниз» только ниже'],
          ['Сигнал', 'RSI 14', 'Вверх: RSI выходит из зоны ниже 30 вверх. Вниз: RSI выходит из зоны выше 70 вниз'],
          ['Экспирация', '3–5 минут', 'Три–пять свечей анализируемого таймфрейма'],
          ['Сумма', '1–2% баланса', 'Минимум $1 на Pocket Option'],
          ['Стоп на день', '3 убытка подряд или −5%', 'Проанализируйте дневник перед продолжением'],
        ] },
        { type: 'p', text: 'Логика проста: EMA говорит, какое направление разрешено, RSI — когда откат внутри этого тренда заканчивается. Пропускайте сигналы против тренда, пропускайте сигналы в первые минуты после новостей и записывайте каждую сделку. После 50 демо-сделок вы поймёте, подходит ли этот сетап вашему активу и расписанию.' },
        { type: 'tip', title: 'Меньше индикаторов — чище график', text: 'Три индикатора на одном графике — практический максимум. Если вы не можете одним предложением объяснить, зачем нужен каждый индикатор, удалите его.' },
        { type: 'h2', id: 'mistakes', text: 'Ошибки новичков с индикаторами' },
        { type: 'ul', items: [
          'Нагромождение пяти индикаторов одной группы (RSI + Стохастик + CCI) — они говорят одно и то же и создают ложную уверенность.',
          'Изменение настроек после каждой убыточной сделки вместо набора выборки из 50+ сделок.',
          'Торговля по сигналам осцилляторов против сильного тренда.',
          'Использование 5-секундных экспираций, где показания индикаторов — в основном шум.',
          'Пропуск этапа демо. Индикаторы кажутся очевидными постфактум и гораздо менее очевидны в реальном времени.',
        ] },
        { type: 'warn', title: 'Ни один индикатор не предсказывает рынок', text: 'Индикаторы описывают то, что цена уже сделала; они повышают шансы на своевременный вход, но никогда не устраняют риск. Торговля на Pocket Option связана с риском потери депозита — используйте размер позиции, который можете себе позволить.' },
        { type: 'cta', text: 'Попробуйте эти индикаторы на бесплатном демо-счёте Pocket Option — $50 000 виртуальных средств, все индикаторы доступны.', label: 'Открыть бесплатный демо-счёт' },
      ],
      faq: [
        { q: 'Какие индикаторы доступны на Pocket Option?', a: 'Десятки, включая скользящие средние, RSI, MACD, полосы Боллинджера, Стохастик, CCI, ATR, Parabolic SAR, Ишимоку, Аллигатор и другие, плюс инструменты рисования. Все они бесплатны на демо и реальном счёте.' },
        { q: 'Какой индикатор лучший для новичка на Pocket Option?', a: 'Единственного лучшего нет. Фильтр тренда (EMA 50) в сочетании с осциллятором импульса (RSI 14) — самая распространённая отправная точка, потому что оба легко читаются и дополняют друг друга.' },
        { q: 'Сколько индикаторов использовать одновременно?', a: 'Два, максимум три, из разных групп — например один трендовый и один осциллятор. Больше индикаторов обычно означает больше противоречивых сигналов, а не больше точности.' },
        { q: 'Работают ли индикаторы на минутных сделках?', a: 'Могут, но чем короче экспирация, тем больше шума. Большинство новичков получают более стабильные показания при экспирации 3–5 минут на минутном графике.' },
        { q: 'Можно ли сохранить настройки индикаторов на Pocket Option?', a: 'Индикаторы остаются на графике актива, пока вы в системе, и платформа позволяет хранить несколько шаблонов графика. Проверьте меню настроек графика в вашей версии терминала.' },
        { q: 'Сигналы Pocket Option — это то же самое, что индикаторы?', a: 'Нет. Раздел «Сигналы» показывает готовые торговые идеи от платформы, а индикаторы — инструменты анализа, которые вы читаете сами. Сигналы могут быть отправной точкой, но всё равно требуют управления риском.' },
      ],
    },
    id: {
      title: 'Indikator Pocket Option untuk pemula: 5 alat yang layak dipelajari lebih dulu dan cara menggabungkannya',
      metaTitle: 'Indikator Pocket Option Terbaik untuk Pemula – MA, RSI, MACD',
      metaDescription:
        'Indikator Pocket Option untuk pemula: cara menambahkan ke grafik, cara kerja Moving Average, RSI, Bollinger Bands, MACD dan Stochastic, dan strategi sederhana.',
      excerpt:
        'Terminal pocketoption punya puluhan indikator — pemula hanya butuh lima. Panduan ini menjelaskan masing-masing, pengaturan awalnya, dan strategi dua indikator sederhana untuk diuji di demo.',
      coverAlt: 'Trader menganalisis grafik indikator di dua laptop — analisis teknikal di Pocket Option',
      keyTakeaways: [
        'Indikator ditambahkan satu klik dari sidebar grafik Pocket Option dan bisa dikombinasikan bebas.',
        'Mulai dengan lima: Moving Average (tren), RSI dan Stochastic (momentum), Bollinger Bands (volatilitas), MACD (tren + momentum).',
        'Satu indikator saja memberi terlalu banyak sinyal palsu; dua dari keluarga berbeda yang sepakat adalah standar pemula.',
        'Uji kombinasi apa pun di demo $50.000 minimal 50 trade sebelum memakainya dengan uang riil.',
      ],
      blocks: [
        { type: 'p', text: 'Indikator mengubah pergerakan harga mentah menjadi sinyal yang mudah dibaca: apakah pasar sedang tren atau sideways, apakah overbought, apakah momentum memudar? Pocket Option menyertakan puluhan indikator di grafik, gratis di akun demo maupun riil. Masalah pemula adalah memilih. Panduan ini mempersempit indikator pocketoption menjadi lima yang mencakup hal esensial, menjelaskan apa yang diukur masing-masing, dan menunjukkan cara menggabungkan dua indikator menjadi strategi yang benar-benar bisa Anda uji.' },
        { type: 'h2', id: 'add', text: 'Cara menambahkan indikator di Pocket Option' },
        { type: 'image', src: IMG_CHART, alt: 'Grafik Pocket Option dengan panel indikator terbuka', caption: 'Indikator ditambahkan dari sidebar kiri grafik.' },
        { type: 'ol', items: [
          'Buka terminal (demo atau riil) dan klik ikon “Indikator” di sidebar kiri grafik.',
          'Pilih indikator dari daftar — dikelompokkan menjadi Tren, Osilator, Volatilitas, dan lainnya.',
          'Sesuaikan periode dan warna jika perlu, lalu klik Terapkan. Indikator tergambar di grafik atau di panel bawah.',
          'Klik ikon roda gigi di sebelah nama indikator untuk mengubah pengaturan nanti, atau tanda silang untuk menghapusnya.',
          'Ubah grafik ke candlestick dan timeframe 1–5 menit — sebagian besar strategi indikator untuk kedaluwarsa pendek dibangun di situ.',
        ] },
        { type: 'h2', id: 'ma', text: '1. Moving Average (MA) — filter tren' },
        { type: 'p', text: 'Moving average menghaluskan harga selama sejumlah candle tertentu. Saat harga di atas MA yang naik, tren naik; di bawah MA yang turun, tren turun. Pemula biasanya memakai exponential MA (EMA) periode 20 atau 50 pada candle 1 menit. Fungsi paling bergunanya bukan memberi sinyal tetapi menyaringnya: hanya ambil trade Naik saat harga di atas EMA, trade Turun saat di bawahnya.' },
        { type: 'h2', id: 'rsi', text: '2. RSI — overbought dan oversold' },
        { type: 'p', text: 'Relative Strength Index berosilasi antara 0 dan 100. Nilai di atas 70 berarti aset naik cepat dan mungkin berhenti atau berbalik (overbought); di bawah 30 kebalikannya (oversold). Periode default 14 bekerja baik. RSI paling andal di pasar sideways; dalam tren kuat ia bisa lama bertahan overbought, karena itu dipasangkan dengan filter tren.' },
        { type: 'h2', id: 'bb', text: '3. Bollinger Bands — volatilitas dan efek “karet gelang”' },
        { type: 'p', text: 'Bollinger Bands menggambar moving average dengan dua pita pada sejumlah standar deviasi (default 20 periode, 2 deviasi). Harga yang menyentuh pita atas di pasar tenang sering kembali ke tengah; squeeze — pita menyempit — biasanya mendahului ledakan pergerakan. Pada trade kedaluwarsa pendek Pocket Option, sentuhan pita luar yang dikombinasikan dengan ekstrem RSI adalah setup pembalikan klasik.' },
        { type: 'h2', id: 'macd', text: '4. MACD — tren dan momentum dalam satu panel' },
        { type: 'p', text: 'MACD menunjukkan selisih dua EMA (12 dan 26) dan garis sinyal (9). Saat garis MACD memotong ke atas garis sinyal, momentum berbalik naik; potongan ke bawah berarti turun. Histogram menunjukkan kekuatan momentum. MACD sedikit terlambat, sehingga cocok untuk kedaluwarsa 5 menit atau lebih, bukan trade 30 detik.' },
        { type: 'h2', id: 'stoch', text: '5. Stochastic Oscillator — saudara RSI yang lebih cepat' },
        { type: 'p', text: 'Stochastic membandingkan harga penutupan dengan rentang terkini dan menghasilkan dua garis (%K dan %D) pada skala 0–100. Di atas 80 overbought, di bawah 20 oversold, dan persilangan kedua garis di zona tersebut adalah sinyalnya. Ia bereaksi lebih cepat dari RSI, sehingga populer untuk kedaluwarsa 1–3 menit — tetapi juga lebih bising, jadi selalu konfirmasi dengan tren.' },
        { type: 'h2', id: 'combine', text: 'Strategi dua indikator sederhana untuk diuji di demo' },
        { type: 'image', src: IMG_TRADE, alt: 'Membuka trade di Pocket Option setelah sinyal indikator', caption: 'Masuk hanya saat filter tren dan osilator sepakat.' },
        { type: 'table', head: ['Elemen', 'Pengaturan', 'Aturan'], rows: [
          ['Grafik', 'Candle, 1 menit', 'Aset likuid dengan payout ≥ 80%, mis. EUR/USD'],
          ['Filter tren', 'EMA 50', 'Naik hanya di atas EMA, Turun hanya di bawah'],
          ['Sinyal', 'RSI 14', 'Naik: RSI keluar dari zona di bawah 30 ke atas. Turun: RSI keluar dari zona di atas 70 ke bawah'],
          ['Kedaluwarsa', '3–5 menit', 'Tiga sampai lima candle dari timeframe yang dianalisis'],
          ['Jumlah', '1–2% saldo', 'Minimum $1 di Pocket Option'],
          ['Berhenti hari ini', '3 rugi berturut atau −5%', 'Tinjau jurnal sebelum lanjut'],
        ] },
        { type: 'p', text: 'Logikanya sederhana: EMA memberi tahu arah yang diizinkan, RSI memberi tahu kapan pullback dalam tren itu berakhir. Lewati sinyal melawan tren, lewati sinyal di menit-menit pertama setelah berita, dan catat setiap trade. Setelah 50 trade demo Anda akan tahu apakah setup ini cocok dengan aset dan jadwal Anda.' },
        { type: 'tip', title: 'Lebih sedikit indikator, grafik lebih jelas', text: 'Tiga indikator dalam satu grafik adalah batas praktis. Jika Anda tidak bisa menjelaskan dalam satu kalimat mengapa setiap indikator ada di sana, hapus.' },
        { type: 'h2', id: 'mistakes', text: 'Kesalahan pemula dengan indikator' },
        { type: 'ul', items: [
          'Menumpuk lima indikator dari keluarga yang sama (RSI + Stochastic + CCI) — semuanya mengatakan hal yang sama dan menciptakan rasa percaya diri palsu.',
          'Mengubah pengaturan setiap kali rugi alih-alih mengumpulkan sampel 50+ trade.',
          'Trading sinyal osilator melawan tren kuat.',
          'Memakai kedaluwarsa 5 detik, di mana pembacaan indikator sebagian besar hanya noise.',
          'Melewatkan tahap demo. Indikator terasa jelas saat melihat ke belakang dan jauh lebih tidak jelas secara real-time.',
        ] },
        { type: 'warn', title: 'Tidak ada indikator yang memprediksi pasar', text: 'Indikator menggambarkan apa yang sudah dilakukan harga; mereka meningkatkan peluang masuk di waktu tepat tetapi tidak pernah menghilangkan risiko. Trading di Pocket Option mengandung risiko kehilangan deposit — gunakan ukuran posisi yang sanggup Anda tanggung.' },
        { type: 'cta', text: 'Coba indikator ini di akun demo gratis Pocket Option — $50.000 dana virtual, semua indikator terbuka.', label: 'Buka akun demo gratis' },
      ],
      faq: [
        { q: 'Indikator apa saja yang tersedia di Pocket Option?', a: 'Puluhan, termasuk Moving Average, RSI, MACD, Bollinger Bands, Stochastic, CCI, ATR, Parabolic SAR, Ichimoku, Alligator dan lainnya, plus alat gambar. Semuanya gratis di akun demo dan riil.' },
        { q: 'Indikator terbaik untuk pemula di Pocket Option?', a: 'Tidak ada satu yang terbaik. Filter tren (EMA 50) yang dikombinasikan dengan osilator momentum (RSI 14) adalah titik awal paling umum karena keduanya mudah dibaca dan saling melengkapi.' },
        { q: 'Berapa indikator yang sebaiknya dipakai sekaligus?', a: 'Dua, maksimal tiga, dari keluarga berbeda — misalnya satu indikator tren dan satu osilator. Lebih banyak indikator biasanya berarti lebih banyak sinyal bertentangan, bukan lebih akurat.' },
        { q: 'Apakah indikator berfungsi untuk trade 1 menit?', a: 'Bisa, tetapi semakin pendek kedaluwarsa, semakin banyak noise. Kebanyakan pemula mendapat pembacaan lebih konsisten dengan kedaluwarsa 3–5 menit pada grafik 1 menit.' },
        { q: 'Bisakah saya menyimpan setup indikator di Pocket Option?', a: 'Indikator tetap ada di grafik aset selama Anda login, dan platform memungkinkan menyimpan beberapa template grafik. Periksa menu pengaturan grafik di versi terminal Anda.' },
        { q: 'Apakah sinyal Pocket Option sama dengan indikator?', a: 'Tidak. Bagian Sinyal menampilkan ide trade siap pakai yang disediakan platform, sedangkan indikator adalah alat analisis yang Anda baca sendiri. Sinyal bisa menjadi titik awal, tetapi tetap membutuhkan manajemen risiko.' },
      ],
    },
  },
};
