import type { BlogPost } from '../types';

const IMG_TERMINAL = '/images/blog/po-trading-terminal.webp';
const IMG_COINBASE = '/images/blog/po-coinbase-otc-chart.webp';
const IMG_VIX = '/images/blog/po-vix-otc-chart.webp';
const IMG_SETTINGS = '/images/blog/po-settings-trading-mode.webp';

export const pocketOptionPayoutAndAssets: BlogPost = {
  slug: 'pocket-option-payout-and-assets',
  category: 'payments',
  cover: '/images/blog/pocket-option-payout-and-assets.webp',
  publishedAt: '2026-09-11',
  updatedAt: '2026-09-11',
  readingMinutes: 9,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option payout percentage and best assets to trade: how payouts work and how to find the highest ones',
      metaTitle: 'Pocket Option Payout % & Best Assets to Trade (2026)',
      metaDescription:
        'How Pocket Option payouts work: why they range from 50% to 92%, what changes them, the break-even win rate you need, and which assets and hours usually offer the highest payout.',
      excerpt:
        'A clear guide to pocketoption payout percentages: what “up to 92%” really means, how to sort assets by payout, and which forex, crypto, stock and OTC assets typically pay the most.',
      coverAlt: 'Pocket Option trading terminal — payout percentage shown next to the asset',
      keyTakeaways: [
        'Payout is the profit on a winning trade: at 92% a $10 trade returns $19.20. A losing trade loses the full $10.',
        'Payouts on Pocket Option vary by asset, time of day, expiry and account status — from about 50% up to 92%, with occasional boosts above that via achievements.',
        'The higher the payout, the lower the win rate you need: 92% → 52.1% break-even, 80% → 55.6%, 70% → 58.8%.',
        'Major forex pairs during active sessions and OTC pairs at weekends usually pay the most; exotic or illiquid assets pay less.',
        'Sort the asset list by payout in the terminal before every session — never trade an asset just because you like it if its payout dropped to 60%.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option advertises payouts “up to 92%”. Many beginners read that as “92% on every trade”, then discover that their favourite pair pays 78% or even 55% at a given moment. This guide explains how pocketoption payouts are formed, why they change during the day, how to calculate the win rate you need for each payout level, and which assets and hours typically offer the best conditions.' },
        { type: 'h2', id: 'what', text: 'What the payout percentage means' },
        { type: 'p', text: 'In binary options the payout is the fixed profit you receive if your prediction is correct, expressed as a percentage of the trade amount. If a trade of $10 has a payout of 92% and closes in the money, you get back $19.20 ($10 investment + $9.20 profit). If it closes out of the money, you lose the $10. The asymmetry — winning less than you risk — is why the payout percentage matters so much.' },
        { type: 'table', head: ['Trade amount', 'Payout', 'Return if win', 'Profit', 'Loss if lose'], rows: [
          ['$10', '92%', '$19.20', '$9.20', '$10'],
          ['$10', '80%', '$18.00', '$8.00', '$10'],
          ['$10', '70%', '$17.00', '$7.00', '$10'],
          ['$10', '50%', '$15.00', '$5.00', '$10'],
        ] },
        { type: 'h2', id: 'breakeven', text: 'Break-even win rate for each payout' },
        { type: 'p', text: 'The minimum win rate needed to avoid losing money is 1 / (1 + payout). It rises quickly as the payout falls, which is why trading low-payout assets is so much harder in the long run.' },
        { type: 'table', head: ['Payout', 'Break-even win rate', 'Win rate for +10% per 100 trades'], rows: [
          ['92%', '52.1%', '57.3%'],
          ['85%', '54.1%', '59.5%'],
          ['80%', '55.6%', '61.1%'],
          ['70%', '58.8%', '64.7%'],
          ['60%', '62.5%', '68.8%'],
          ['50%', '66.7%', '73.3%'],
        ] },
        { type: 'tip', title: 'Set a minimum payout for yourself', text: 'Most consistent traders refuse to open a trade below 75–80%. Losing three trades at 60% payout costs more than winning three back earns — the mathematics simply works against you.' },
        { type: 'h2', id: 'factors', text: 'What changes the payout on Pocket Option' },
        { type: 'ul', items: [
          'Asset — liquid majors (EUR/USD, GBP/USD, BTC/USD) usually sit at the top; exotic pairs and less traded stocks pay less.',
          'Time of day — payouts on forex are highest during the London and New York sessions and fall during quiet Asian hours or right before market close.',
          'Expiry — payouts can differ between 5-second, 1-minute and 5-minute expiries on the same asset; quick trades sometimes pay less.',
          'Market conditions — during high-impact news or extreme volatility the platform may lower payouts temporarily.',
          'Account status and achievements — the Gems/Achievements system and higher account levels can add a payout boost (for example +2–10%) on top of the base percentage.',
          'Trading mode — Pocket Option offers Quick trading (fixed time) and Digital trading (expiry at a set moment); payouts for the same asset can differ between modes.',
        ] },
        { type: 'image', src: IMG_SETTINGS, alt: 'Pocket Option settings dialog with Trading mode: Quick trading or Digital trading', caption: 'Trading mode is chosen in Settings; check the payout in both modes for the same asset.' },
        { type: 'h2', id: 'find', text: 'How to find the highest payout right now' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Pocket Option terminal with asset list and payout percentages', caption: 'The asset list shows the current payout next to every instrument and can be sorted.' },
        { type: 'ol', items: [
          'Open the terminal and click the current asset name at the top left to open the asset list.',
          'Switch between the tabs (Currencies, Crypto, Commodities, Stocks, Indices) — each shows the payout percentage in the right column.',
          'Sort by payout (click the percentage header) or scan for the highest values; add the best 3–5 assets to Favourites.',
          'Check the same asset with your usual expiry — the percentage shown updates when you change the expiry time.',
          'Re-check before each session: the ranking changes during the day.',
        ] },
        { type: 'h2', id: 'best', text: 'Assets that usually pay the most' },
        { type: 'table', head: ['Category', 'Typical high-payout examples', 'Best hours (UTC)', 'Typical payout*'], rows: [
          ['Forex majors', 'EUR/USD, GBP/USD, AUD/USD, USD/JPY', '07:00–16:00 (London/NY overlap 12:00–16:00)', '80–92%'],
          ['OTC forex (weekends)', 'EUR/USD OTC, GBP/USD OTC, AUD/CAD OTC', 'Sat–Sun, all day', '85–92%'],
          ['Crypto', 'BTC/USD, ETH/USD', '24/7, most liquid 13:00–21:00', '70–90%'],
          ['Commodities', 'Gold, Silver, Brent', '08:00–17:00', '60–85%'],
          ['Stocks', 'Apple, Tesla, Microsoft (and OTC versions)', '13:30–20:00 (US session)', '50–80%'],
          ['Indices', 'S&P 500, DAX, Nikkei 225 (and OTC)', 'Local session hours', '50–80%'],
        ] },
        { type: 'p', text: '*Ranges are indicative, based on observations in 2026; the platform sets payouts dynamically and they can be outside these ranges at any moment. Always rely on the live percentage in the terminal.' },
        { type: 'image', src: IMG_COINBASE, alt: 'Coinbase OTC chart on Pocket Option', caption: 'OTC versions of stocks such as Coinbase let you trade outside exchange hours, often with competitive payouts.' },
        { type: 'h2', id: 'strategy', text: 'Payout-aware trading: a simple routine' },
        { type: 'ul', items: [
          'Before the session, list the 3–5 assets above your minimum payout (say 80%).',
          'Trade only those assets and only during their active hours.',
          'If the payout on your asset drops below your minimum mid-session, stop trading it — do not compensate with larger amounts.',
          'Keep a journal with the payout of each trade; after 100 trades compare your real win rate with the break-even table above.',
          'Use the achievements system: some rewards add a temporary payout boost — activate them during your best hours.',
        ] },
        { type: 'image', src: IMG_VIX, alt: 'VIX OTC chart on Pocket Option', caption: 'Volatility indices like VIX OTC can offer high payouts but move sharply — size positions accordingly.' },
        { type: 'warn', title: 'High payout does not mean easy profit', text: 'A 92% payout still means you lose more on a losing trade than you win on a winning one. Payout only reduces the win rate you need; it does not create an edge. Binary options carry a high risk of loss — trade with amounts you can afford to lose and test every idea on the demo first.' },
        { type: 'cta', text: 'See live payouts for yourself: open a free demo, sort the asset list by payout and practise with the top assets before depositing from $5.', label: 'Open a free demo account' },
      ],
      faq: [
        { q: 'What is the maximum payout on Pocket Option?', a: 'Up to 92% on selected assets at certain times, with possible boosts from achievements. Typical live payouts on major assets are 70–90%.' },
        { q: 'Why does the payout change during the day?', a: 'Payouts depend on liquidity, volatility, session and expiry. They are highest during active market hours for the asset and fall during quiet periods or news events.' },
        { q: 'Which asset has the highest payout on Pocket Option?', a: 'It changes constantly. Major forex pairs during the London/New York sessions and OTC pairs at weekends are usually at the top. Sort the asset list by payout to see the current leader.' },
        { q: 'Is the payout the same on demo and real accounts?', a: 'Yes, the demo uses the same payout percentages as the real account for the same asset, expiry and moment.' },
        { q: 'What win rate do I need at 80% payout?', a: 'At least 55.6% just to break even; around 61% to make a meaningful profit over time.' },
        { q: 'Do OTC assets really pay more?', a: 'OTC pairs at weekends often show 85–92% payouts because they are among the most traded assets at that time. They are quoted by the platform, so check our OTC guide for the specifics.' },
      ],
    },
    pt: {
      title: 'Payout da Pocket Option e melhores ativos para operar: como funcionam os payouts e como achar os mais altos',
      metaTitle: 'Payout Pocket Option e Melhores Ativos para Operar (2026)',
      metaDescription:
        'Como funcionam os payouts da Pocket Option: por que variam de 50% a 92%, o que os altera, a taxa de acerto necessária para empatar e quais ativos e horários costumam pagar mais.',
      excerpt:
        'Guia claro sobre o percentual de payout da pocketoption: o que “até 92%” realmente significa, como ordenar ativos por payout e quais ativos de forex, cripto, ações e OTC pagam mais.',
      coverAlt: 'Terminal de trading da Pocket Option — percentual de payout mostrado ao lado do ativo',
      keyTakeaways: [
        'Payout é o lucro de uma operação vencedora: a 92%, uma operação de $10 devolve $19,20. Uma operação perdedora perde os $10 inteiros.',
        'Os payouts na Pocket Option variam por ativo, horário, expiração e status da conta — de cerca de 50% até 92%, com aumentos ocasionais via conquistas.',
        'Quanto maior o payout, menor a taxa de acerto necessária: 92% → 52,1% para empatar, 80% → 55,6%, 70% → 58,8%.',
        'Pares de forex principais em sessões ativas e pares OTC no fim de semana costumam pagar mais; ativos exóticos ou ilíquidos pagam menos.',
        'Ordene a lista de ativos por payout no terminal antes de cada sessão — nunca opere um ativo só porque gosta dele se o payout caiu para 60%.',
      ],
      blocks: [
        { type: 'p', text: 'A Pocket Option anuncia payouts “até 92%”. Muitos iniciantes leem isso como “92% em toda operação” e depois descobrem que seu par favorito paga 78% ou até 55% em certo momento. Este guia explica como os payouts da pocketoption são formados, por que mudam durante o dia, como calcular a taxa de acerto necessária para cada nível e quais ativos e horários costumam oferecer as melhores condições.' },
        { type: 'h2', id: 'what', text: 'O que significa o percentual de payout' },
        { type: 'p', text: 'Em opções binárias, o payout é o lucro fixo recebido se a previsão estiver correta, expresso como percentual do valor da operação. Se uma operação de $10 tem payout de 92% e fecha no dinheiro, você recebe $19,20 ($10 de investimento + $9,20 de lucro). Se fechar fora do dinheiro, perde os $10. A assimetria — ganhar menos do que arrisca — é o motivo de o payout importar tanto.' },
        { type: 'table', head: ['Valor', 'Payout', 'Retorno se ganhar', 'Lucro', 'Perda se perder'], rows: [
          ['$10', '92%', '$19,20', '$9,20', '$10'],
          ['$10', '80%', '$18,00', '$8,00', '$10'],
          ['$10', '70%', '$17,00', '$7,00', '$10'],
          ['$10', '50%', '$15,00', '$5,00', '$10'],
        ] },
        { type: 'h2', id: 'breakeven', text: 'Taxa de acerto de equilíbrio para cada payout' },
        { type: 'p', text: 'A taxa mínima de acerto para não perder dinheiro é 1 / (1 + payout). Ela sobe rápido conforme o payout cai — por isso operar ativos de payout baixo é muito mais difícil no longo prazo.' },
        { type: 'table', head: ['Payout', 'Acerto para empatar', 'Acerto para +10% a cada 100 operações'], rows: [
          ['92%', '52,1%', '57,3%'],
          ['85%', '54,1%', '59,5%'],
          ['80%', '55,6%', '61,1%'],
          ['70%', '58,8%', '64,7%'],
          ['60%', '62,5%', '68,8%'],
          ['50%', '66,7%', '73,3%'],
        ] },
        { type: 'tip', title: 'Defina um payout mínimo para você', text: 'A maioria dos traders consistentes se recusa a abrir operação abaixo de 75–80%. Perder três operações a 60% custa mais do que ganhar três de volta — a matemática simplesmente trabalha contra você.' },
        { type: 'h2', id: 'factors', text: 'O que altera o payout na Pocket Option' },
        { type: 'ul', items: [
          'Ativo — majors líquidos (EUR/USD, GBP/USD, BTC/USD) costumam ficar no topo; pares exóticos e ações menos negociadas pagam menos.',
          'Horário — payouts de forex são maiores nas sessões de Londres e Nova York e caem nas horas asiáticas calmas ou perto do fechamento.',
          'Expiração — payouts podem diferir entre 5 segundos, 1 minuto e 5 minutos no mesmo ativo; operações rápidas às vezes pagam menos.',
          'Condições de mercado — em notícias de alto impacto ou volatilidade extrema a plataforma pode reduzir payouts temporariamente.',
          'Status da conta e conquistas — o sistema Gems/Conquistas e níveis mais altos podem adicionar um aumento (por exemplo +2–10%) sobre o percentual base.',
          'Modo de trading — a Pocket Option oferece Quick trading (tempo fixo) e Digital trading (expiração em momento definido); payouts do mesmo ativo podem diferir entre modos.',
        ] },
        { type: 'image', src: IMG_SETTINGS, alt: 'Configurações da Pocket Option com modo de trading: Quick trading ou Digital trading', caption: 'O modo de trading é escolhido em Configurações; confira o payout nos dois modos para o mesmo ativo.' },
        { type: 'h2', id: 'find', text: 'Como achar o maior payout agora' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal da Pocket Option com lista de ativos e percentuais de payout', caption: 'A lista de ativos mostra o payout atual ao lado de cada instrumento e pode ser ordenada.' },
        { type: 'ol', items: [
          'Abra o terminal e clique no nome do ativo atual (canto superior esquerdo) para abrir a lista.',
          'Alterne entre as abas (Moedas, Cripto, Commodities, Ações, Índices) — cada uma mostra o payout na coluna direita.',
          'Ordene por payout (clique no cabeçalho do percentual) ou procure os maiores valores; adicione os 3–5 melhores aos Favoritos.',
          'Confira o mesmo ativo com sua expiração habitual — o percentual muda quando você altera o tempo.',
          'Reveja antes de cada sessão: o ranking muda ao longo do dia.',
        ] },
        { type: 'h2', id: 'best', text: 'Ativos que costumam pagar mais' },
        { type: 'table', head: ['Categoria', 'Exemplos típicos de payout alto', 'Melhores horários (UTC)', 'Payout típico*'], rows: [
          ['Forex majors', 'EUR/USD, GBP/USD, AUD/USD, USD/JPY', '07:00–16:00 (sobreposição Londres/NY 12:00–16:00)', '80–92%'],
          ['Forex OTC (fim de semana)', 'EUR/USD OTC, GBP/USD OTC, AUD/CAD OTC', 'Sáb–Dom, o dia todo', '85–92%'],
          ['Cripto', 'BTC/USD, ETH/USD', '24/7, mais líquido 13:00–21:00', '70–90%'],
          ['Commodities', 'Ouro, Prata, Brent', '08:00–17:00', '60–85%'],
          ['Ações', 'Apple, Tesla, Microsoft (e versões OTC)', '13:30–20:00 (sessão EUA)', '50–80%'],
          ['Índices', 'S&P 500, DAX, Nikkei 225 (e OTC)', 'Horário da sessão local', '50–80%'],
        ] },
        { type: 'p', text: '*Faixas indicativas, baseadas em observações de 2026; a plataforma define payouts dinamicamente e eles podem sair dessas faixas a qualquer momento. Confie sempre no percentual ao vivo do terminal.' },
        { type: 'image', src: IMG_COINBASE, alt: 'Gráfico Coinbase OTC na Pocket Option', caption: 'Versões OTC de ações como Coinbase permitem operar fora do horário da bolsa, muitas vezes com payouts competitivos.' },
        { type: 'h2', id: 'strategy', text: 'Trading consciente do payout: uma rotina simples' },
        { type: 'ul', items: [
          'Antes da sessão, liste os 3–5 ativos acima do seu payout mínimo (digamos 80%).',
          'Opere só esses ativos e só nos horários ativos deles.',
          'Se o payout do seu ativo cair abaixo do mínimo no meio da sessão, pare de operá-lo — não compense com valores maiores.',
          'Mantenha um diário com o payout de cada operação; após 100 operações compare sua taxa real de acerto com a tabela acima.',
          'Use o sistema de conquistas: algumas recompensas dão aumento temporário de payout — ative nos seus melhores horários.',
        ] },
        { type: 'image', src: IMG_VIX, alt: 'Gráfico VIX OTC na Pocket Option', caption: 'Índices de volatilidade como VIX OTC podem oferecer payouts altos, mas se movem bruscamente — dimensione as posições.' },
        { type: 'warn', title: 'Payout alto não significa lucro fácil', text: 'Um payout de 92% ainda significa que você perde mais na operação perdedora do que ganha na vencedora. O payout só reduz a taxa de acerto necessária; não cria vantagem. Opções binárias têm alto risco de perda — opere com valores que pode perder e teste toda ideia na demo primeiro.' },
        { type: 'cta', text: 'Veja os payouts ao vivo você mesmo: abra uma demo gratuita, ordene a lista de ativos por payout e pratique com os melhores antes de depositar a partir de $5.', label: 'Abrir conta demo gratuita' },
      ],
      faq: [
        { q: 'Qual é o payout máximo na Pocket Option?', a: 'Até 92% em ativos selecionados em certos horários, com possíveis aumentos por conquistas. Payouts típicos ao vivo nos principais ativos ficam entre 70–90%.' },
        { q: 'Por que o payout muda durante o dia?', a: 'Payouts dependem de liquidez, volatilidade, sessão e expiração. São maiores nos horários ativos do ativo e caem em períodos calmos ou eventos de notícias.' },
        { q: 'Qual ativo tem o maior payout na Pocket Option?', a: 'Muda constantemente. Pares de forex principais nas sessões Londres/NY e pares OTC no fim de semana costumam liderar. Ordene a lista por payout para ver o líder atual.' },
        { q: 'O payout é igual na demo e na conta real?', a: 'Sim, a demo usa os mesmos percentuais da conta real para o mesmo ativo, expiração e momento.' },
        { q: 'Que taxa de acerto preciso com payout de 80%?', a: 'Pelo menos 55,6% só para empatar; cerca de 61% para lucro significativo ao longo do tempo.' },
        { q: 'Ativos OTC realmente pagam mais?', a: 'Pares OTC no fim de semana frequentemente mostram 85–92% porque estão entre os mais negociados nesse período. São cotados pela plataforma — veja nosso guia de OTC para detalhes.' },
      ],
    },
    es: {
      title: 'Payout de Pocket Option y mejores activos para operar: cómo funcionan los payouts y cómo encontrar los más altos',
      metaTitle: 'Payout Pocket Option y Mejores Activos para Operar (2026)',
      metaDescription:
        'Cómo funcionan los payouts de Pocket Option: por qué van del 50% al 92%, qué los cambia, la tasa de acierto necesaria para no perder y qué activos y horas suelen pagar más.',
      excerpt:
        'Guía clara sobre el porcentaje de payout de pocketoption: qué significa realmente “hasta 92%”, cómo ordenar activos por payout y qué activos de forex, cripto, acciones y OTC pagan más.',
      coverAlt: 'Terminal de trading de Pocket Option — porcentaje de payout junto al activo',
      keyTakeaways: [
        'El payout es el beneficio de una operación ganadora: al 92%, una operación de $10 devuelve $19,20. Una operación perdedora pierde los $10 completos.',
        'Los payouts en Pocket Option varían según activo, hora, expiración y estado de la cuenta — desde cerca del 50% hasta el 92%, con aumentos ocasionales vía logros.',
        'Cuanto mayor el payout, menor la tasa de acierto necesaria: 92% → 52,1% para no perder, 80% → 55,6%, 70% → 58,8%.',
        'Los pares de forex principales en sesiones activas y los pares OTC en fin de semana suelen pagar más; los activos exóticos o ilíquidos pagan menos.',
        'Ordena la lista de activos por payout en el terminal antes de cada sesión — nunca operes un activo solo porque te gusta si su payout bajó al 60%.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option anuncia payouts “hasta 92%”. Muchos principiantes lo leen como “92% en cada operación” y luego descubren que su par favorito paga 78% o incluso 55% en un momento dado. Esta guía explica cómo se forman los payouts de pocketoption, por qué cambian durante el día, cómo calcular la tasa de acierto que necesitas para cada nivel y qué activos y horas suelen ofrecer las mejores condiciones.' },
        { type: 'h2', id: 'what', text: 'Qué significa el porcentaje de payout' },
        { type: 'p', text: 'En opciones binarias, el payout es el beneficio fijo que recibes si tu predicción es correcta, expresado como porcentaje del importe de la operación. Si una operación de $10 tiene un payout del 92% y cierra dentro del dinero, recibes $19,20 ($10 de inversión + $9,20 de beneficio). Si cierra fuera del dinero, pierdes los $10. La asimetría — ganar menos de lo que arriesgas — es la razón por la que el payout importa tanto.' },
        { type: 'table', head: ['Importe', 'Payout', 'Retorno si ganas', 'Beneficio', 'Pérdida si pierdes'], rows: [
          ['$10', '92%', '$19,20', '$9,20', '$10'],
          ['$10', '80%', '$18,00', '$8,00', '$10'],
          ['$10', '70%', '$17,00', '$7,00', '$10'],
          ['$10', '50%', '$15,00', '$5,00', '$10'],
        ] },
        { type: 'h2', id: 'breakeven', text: 'Tasa de acierto de equilibrio para cada payout' },
        { type: 'p', text: 'La tasa mínima de acierto para no perder dinero es 1 / (1 + payout). Sube rápido a medida que baja el payout, y por eso operar activos de payout bajo es mucho más difícil a largo plazo.' },
        { type: 'table', head: ['Payout', 'Acierto para no perder', 'Acierto para +10% por cada 100 operaciones'], rows: [
          ['92%', '52,1%', '57,3%'],
          ['85%', '54,1%', '59,5%'],
          ['80%', '55,6%', '61,1%'],
          ['70%', '58,8%', '64,7%'],
          ['60%', '62,5%', '68,8%'],
          ['50%', '66,7%', '73,3%'],
        ] },
        { type: 'tip', title: 'Fija un payout mínimo para ti', text: 'La mayoría de los traders consistentes se niegan a abrir operaciones por debajo del 75–80%. Perder tres operaciones al 60% cuesta más de lo que ganan tres aciertos — la matemática simplemente juega en tu contra.' },
        { type: 'h2', id: 'factors', text: 'Qué cambia el payout en Pocket Option' },
        { type: 'ul', items: [
          'Activo — los majors líquidos (EUR/USD, GBP/USD, BTC/USD) suelen estar arriba; los pares exóticos y las acciones menos operadas pagan menos.',
          'Hora del día — los payouts de forex son más altos en las sesiones de Londres y Nueva York y bajan en las horas asiáticas tranquilas o justo antes del cierre.',
          'Expiración — los payouts pueden diferir entre 5 segundos, 1 minuto y 5 minutos en el mismo activo; las operaciones rápidas a veces pagan menos.',
          'Condiciones de mercado — durante noticias de alto impacto o volatilidad extrema la plataforma puede bajar los payouts temporalmente.',
          'Estado de la cuenta y logros — el sistema Gems/Logros y los niveles superiores pueden añadir un aumento (por ejemplo +2–10%) sobre el porcentaje base.',
          'Modo de trading — Pocket Option ofrece Quick trading (tiempo fijo) y Digital trading (expiración en un momento fijado); los payouts del mismo activo pueden diferir entre modos.',
        ] },
        { type: 'image', src: IMG_SETTINGS, alt: 'Ajustes de Pocket Option con modo de trading: Quick trading o Digital trading', caption: 'El modo de trading se elige en Ajustes; revisa el payout en ambos modos para el mismo activo.' },
        { type: 'h2', id: 'find', text: 'Cómo encontrar el payout más alto ahora mismo' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal de Pocket Option con lista de activos y porcentajes de payout', caption: 'La lista de activos muestra el payout actual junto a cada instrumento y se puede ordenar.' },
        { type: 'ol', items: [
          'Abre el terminal y haz clic en el nombre del activo actual (arriba a la izquierda) para abrir la lista.',
          'Cambia entre pestañas (Divisas, Cripto, Materias primas, Acciones, Índices) — cada una muestra el payout en la columna derecha.',
          'Ordena por payout (clic en el encabezado del porcentaje) o busca los valores más altos; añade los 3–5 mejores a Favoritos.',
          'Comprueba el mismo activo con tu expiración habitual — el porcentaje cambia al modificar el tiempo.',
          'Revísalo antes de cada sesión: el ranking cambia a lo largo del día.',
        ] },
        { type: 'h2', id: 'best', text: 'Activos que suelen pagar más' },
        { type: 'table', head: ['Categoría', 'Ejemplos típicos de payout alto', 'Mejores horas (UTC)', 'Payout típico*'], rows: [
          ['Forex majors', 'EUR/USD, GBP/USD, AUD/USD, USD/JPY', '07:00–16:00 (solapamiento Londres/NY 12:00–16:00)', '80–92%'],
          ['Forex OTC (fin de semana)', 'EUR/USD OTC, GBP/USD OTC, AUD/CAD OTC', 'Sáb–Dom, todo el día', '85–92%'],
          ['Cripto', 'BTC/USD, ETH/USD', '24/7, más líquido 13:00–21:00', '70–90%'],
          ['Materias primas', 'Oro, Plata, Brent', '08:00–17:00', '60–85%'],
          ['Acciones', 'Apple, Tesla, Microsoft (y versiones OTC)', '13:30–20:00 (sesión EE. UU.)', '50–80%'],
          ['Índices', 'S&P 500, DAX, Nikkei 225 (y OTC)', 'Horario de sesión local', '50–80%'],
        ] },
        { type: 'p', text: '*Rangos indicativos, basados en observaciones de 2026; la plataforma fija los payouts dinámicamente y pueden salir de estos rangos en cualquier momento. Confía siempre en el porcentaje en vivo del terminal.' },
        { type: 'image', src: IMG_COINBASE, alt: 'Gráfico Coinbase OTC en Pocket Option', caption: 'Las versiones OTC de acciones como Coinbase permiten operar fuera del horario bursátil, a menudo con payouts competitivos.' },
        { type: 'h2', id: 'strategy', text: 'Trading consciente del payout: una rutina simple' },
        { type: 'ul', items: [
          'Antes de la sesión, lista los 3–5 activos por encima de tu payout mínimo (digamos 80%).',
          'Opera solo esos activos y solo en sus horas activas.',
          'Si el payout de tu activo baja de tu mínimo a mitad de sesión, deja de operarlo — no compenses con importes mayores.',
          'Lleva un diario con el payout de cada operación; tras 100 operaciones compara tu tasa real de acierto con la tabla anterior.',
          'Usa el sistema de logros: algunas recompensas añaden un aumento temporal de payout — actívalas en tus mejores horas.',
        ] },
        { type: 'image', src: IMG_VIX, alt: 'Gráfico VIX OTC en Pocket Option', caption: 'Los índices de volatilidad como VIX OTC pueden ofrecer payouts altos pero se mueven bruscamente — dimensiona las posiciones en consecuencia.' },
        { type: 'warn', title: 'Payout alto no significa beneficio fácil', text: 'Un payout del 92% sigue significando que pierdes más en una operación perdedora de lo que ganas en una ganadora. El payout solo reduce la tasa de acierto que necesitas; no crea ventaja. Las opciones binarias tienen un alto riesgo de pérdida — opera con importes que puedas perder y prueba cada idea en demo primero.' },
        { type: 'cta', text: 'Mira los payouts en vivo por ti mismo: abre una demo gratuita, ordena la lista de activos por payout y practica con los mejores antes de depositar desde $5.', label: 'Abrir cuenta demo gratis' },
      ],
      faq: [
        { q: '¿Cuál es el payout máximo en Pocket Option?', a: 'Hasta 92% en activos seleccionados en ciertos momentos, con posibles aumentos por logros. Los payouts típicos en vivo en los activos principales son 70–90%.' },
        { q: '¿Por qué cambia el payout durante el día?', a: 'Los payouts dependen de liquidez, volatilidad, sesión y expiración. Son más altos en las horas activas del activo y bajan en periodos tranquilos o eventos de noticias.' },
        { q: '¿Qué activo tiene el mayor payout en Pocket Option?', a: 'Cambia constantemente. Los pares de forex principales en las sesiones de Londres/NY y los pares OTC en fin de semana suelen liderar. Ordena la lista por payout para ver el líder actual.' },
        { q: '¿El payout es igual en demo y en cuenta real?', a: 'Sí, la demo usa los mismos porcentajes que la cuenta real para el mismo activo, expiración y momento.' },
        { q: '¿Qué tasa de acierto necesito con un payout del 80%?', a: 'Al menos 55,6% solo para no perder; alrededor del 61% para obtener un beneficio significativo con el tiempo.' },
        { q: '¿Los activos OTC realmente pagan más?', a: 'Los pares OTC en fin de semana suelen mostrar payouts del 85–92% porque están entre los activos más operados en ese momento. Los cotiza la plataforma — consulta nuestra guía de OTC para los detalles.' },
      ],
    },
    ru: {
      title: 'Процент выплат Pocket Option и лучшие активы для торговли: как работают выплаты и где найти самые высокие',
      metaTitle: 'Выплаты Pocket Option и лучшие активы для торговли (2026)',
      metaDescription:
        'Как работают выплаты Pocket Option: почему они от 50% до 92%, что на них влияет, какой винрейт нужен для безубытка и какие активы и часы обычно дают самую высокую выплату.',
      excerpt:
        'Понятный гайд по процентам выплат pocketoption: что на самом деле значит «до 92%», как сортировать активы по выплате и какие форекс, крипто, акции и OTC-активы платят больше всего.',
      coverAlt: 'Торговый терминал Pocket Option — процент выплаты рядом с активом',
      keyTakeaways: [
        'Выплата — это прибыль по выигрышной сделке: при 92% сделка на $10 возвращает $19,20. Проигрышная сделка теряет все $10.',
        'Выплаты на Pocket Option зависят от актива, времени суток, экспирации и статуса аккаунта — примерно от 50% до 92%, иногда выше за счёт бустов достижений.',
        'Чем выше выплата, тем ниже нужный винрейт: 92% → безубыток при 52,1%, 80% → 55,6%, 70% → 58,8%.',
        'Мажорные форекс-пары в активные сессии и OTC-пары по выходным обычно платят больше всего; экзотические и неликвидные активы — меньше.',
        'Сортируйте список активов по выплате в терминале перед каждой сессией — не торгуйте актив «по привычке», если выплата упала до 60%.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option заявляет выплаты «до 92%». Многие новички читают это как «92% на каждой сделке», а потом обнаруживают, что любимая пара платит 78% или даже 55% в конкретный момент. В этом гайде разбираем, как формируются выплаты pocketoption, почему они меняются в течение дня, как посчитать нужный винрейт для каждого уровня выплаты и какие активы и часы обычно дают лучшие условия.' },
        { type: 'h2', id: 'what', text: 'Что означает процент выплаты' },
        { type: 'p', text: 'В бинарных опционах выплата — это фиксированная прибыль при верном прогнозе, выраженная в процентах от суммы сделки. Если сделка на $10 с выплатой 92% закрывается в плюс, вы получаете $19,20 ($10 вложения + $9,20 прибыли). Если в минус — теряете $10. Асимметрия — выигрыш меньше риска — и есть причина, почему процент выплаты так важен.' },
        { type: 'table', head: ['Сумма сделки', 'Выплата', 'Возврат при выигрыше', 'Прибыль', 'Убыток при проигрыше'], rows: [
          ['$10', '92%', '$19,20', '$9,20', '$10'],
          ['$10', '80%', '$18,00', '$8,00', '$10'],
          ['$10', '70%', '$17,00', '$7,00', '$10'],
          ['$10', '50%', '$15,00', '$5,00', '$10'],
        ] },
        { type: 'h2', id: 'breakeven', text: 'Винрейт безубытка для каждой выплаты' },
        { type: 'p', text: 'Минимальный винрейт, чтобы не терять деньги, равен 1 / (1 + выплата). Он быстро растёт с падением выплаты — поэтому торговать активы с низкой выплатой в долгосрочной перспективе намного сложнее.' },
        { type: 'table', head: ['Выплата', 'Винрейт безубытка', 'Винрейт для +10% на 100 сделок'], rows: [
          ['92%', '52,1%', '57,3%'],
          ['85%', '54,1%', '59,5%'],
          ['80%', '55,6%', '61,1%'],
          ['70%', '58,8%', '64,7%'],
          ['60%', '62,5%', '68,8%'],
          ['50%', '66,7%', '73,3%'],
        ] },
        { type: 'tip', title: 'Установите себе минимальную выплату', text: 'Большинство стабильных трейдеров не открывают сделки ниже 75–80%. Три проигрыша при выплате 60% стоят больше, чем приносят три выигрыша — математика просто работает против вас.' },
        { type: 'h2', id: 'factors', text: 'Что меняет выплату на Pocket Option' },
        { type: 'ul', items: [
          'Актив — ликвидные мажоры (EUR/USD, GBP/USD, BTC/USD) обычно в топе; экзотические пары и малоторгуемые акции платят меньше.',
          'Время суток — выплаты по форексу максимальны в лондонскую и нью-йоркскую сессии и падают в тихие азиатские часы или перед закрытием рынка.',
          'Экспирация — выплаты могут отличаться для 5 секунд, 1 минуты и 5 минут на одном активе; быстрые сделки иногда платят меньше.',
          'Рыночные условия — во время важных новостей или экстремальной волатильности платформа может временно снижать выплаты.',
          'Статус аккаунта и достижения — система Gems/Достижений и высокие уровни аккаунта могут добавлять буст (например, +2–10%) к базовому проценту.',
          'Режим торговли — Pocket Option предлагает Quick trading (фиксированное время) и Digital trading (экспирация в заданный момент); выплаты по одному активу могут отличаться между режимами.',
        ] },
        { type: 'image', src: IMG_SETTINGS, alt: 'Настройки Pocket Option с выбором режима: Quick trading или Digital trading', caption: 'Режим торговли выбирается в Настройках; проверьте выплату в обоих режимах для одного актива.' },
        { type: 'h2', id: 'find', text: 'Как найти самую высокую выплату прямо сейчас' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Терминал Pocket Option со списком активов и процентами выплат', caption: 'Список активов показывает текущую выплату рядом с каждым инструментом и сортируется.' },
        { type: 'ol', items: [
          'Откройте терминал и нажмите на название текущего актива слева сверху, чтобы открыть список.',
          'Переключайтесь между вкладками (Валюты, Крипто, Сырьё, Акции, Индексы) — в правой колонке показан процент выплаты.',
          'Отсортируйте по выплате (клик по заголовку процента) или найдите максимальные значения; добавьте лучшие 3–5 активов в Избранное.',
          'Проверьте тот же актив с вашей обычной экспирацией — процент обновляется при смене времени.',
          'Перепроверяйте перед каждой сессией: рейтинг меняется в течение дня.',
        ] },
        { type: 'h2', id: 'best', text: 'Активы, которые обычно платят больше' },
        { type: 'table', head: ['Категория', 'Типичные примеры с высокой выплатой', 'Лучшие часы (UTC)', 'Типичная выплата*'], rows: [
          ['Форекс-мажоры', 'EUR/USD, GBP/USD, AUD/USD, USD/JPY', '07:00–16:00 (пересечение Лондон/НЙ 12:00–16:00)', '80–92%'],
          ['OTC-форекс (выходные)', 'EUR/USD OTC, GBP/USD OTC, AUD/CAD OTC', 'Сб–Вс, весь день', '85–92%'],
          ['Крипто', 'BTC/USD, ETH/USD', '24/7, максимум ликвидности 13:00–21:00', '70–90%'],
          ['Сырьё', 'Золото, Серебро, Brent', '08:00–17:00', '60–85%'],
          ['Акции', 'Apple, Tesla, Microsoft (и OTC-версии)', '13:30–20:00 (сессия США)', '50–80%'],
          ['Индексы', 'S&P 500, DAX, Nikkei 225 (и OTC)', 'Часы локальной сессии', '50–80%'],
        ] },
        { type: 'p', text: '*Диапазоны ориентировочные, по наблюдениям 2026 года; платформа задаёт выплаты динамически, и они могут выходить за эти рамки в любой момент. Всегда опирайтесь на живой процент в терминале.' },
        { type: 'image', src: IMG_COINBASE, alt: 'График Coinbase OTC на Pocket Option', caption: 'OTC-версии акций, например Coinbase, позволяют торговать вне биржевых часов, часто с конкурентной выплатой.' },
        { type: 'h2', id: 'strategy', text: 'Торговля с учётом выплаты: простая рутина' },
        { type: 'ul', items: [
          'Перед сессией составьте список 3–5 активов выше вашей минимальной выплаты (например, 80%).',
          'Торгуйте только их и только в активные часы.',
          'Если выплата по активу упала ниже минимума посреди сессии — прекращайте торговать его; не компенсируйте большими суммами.',
          'Ведите журнал с выплатой каждой сделки; после 100 сделок сравните реальный винрейт с таблицей безубытка выше.',
          'Используйте систему достижений: некоторые награды дают временный буст выплаты — активируйте их в лучшие часы.',
        ] },
        { type: 'image', src: IMG_VIX, alt: 'График VIX OTC на Pocket Option', caption: 'Индексы волатильности вроде VIX OTC могут давать высокую выплату, но резко двигаются — подбирайте размер позиции.' },
        { type: 'warn', title: 'Высокая выплата — не лёгкая прибыль', text: 'Выплата 92% всё равно значит, что на проигрышной сделке вы теряете больше, чем зарабатываете на выигрышной. Выплата лишь снижает нужный винрейт, но не создаёт преимущества. Бинарные опционы несут высокий риск потерь — торгуйте на суммы, которые можете позволить себе потерять, и сначала проверяйте каждую идею на демо.' },
        { type: 'cta', text: 'Посмотрите живые выплаты сами: откройте бесплатное демо, отсортируйте список активов по выплате и потренируйтесь на топовых активах до депозита от $5.', label: 'Открыть бесплатный демо-счёт' },
      ],
      faq: [
        { q: 'Какая максимальная выплата на Pocket Option?', a: 'До 92% на отдельных активах в определённое время, возможны бусты за достижения. Типичные живые выплаты по основным активам — 70–90%.' },
        { q: 'Почему выплата меняется в течение дня?', a: 'Выплаты зависят от ликвидности, волатильности, сессии и экспирации. Они максимальны в активные часы актива и падают в спокойные периоды или во время новостей.' },
        { q: 'Какой актив имеет самую высокую выплату на Pocket Option?', a: 'Это постоянно меняется. Обычно лидируют мажорные форекс-пары в сессии Лондона/Нью-Йорка и OTC-пары по выходным. Отсортируйте список по выплате, чтобы увидеть текущего лидера.' },
        { q: 'Одинаковы ли выплаты на демо и реальном счёте?', a: 'Да, демо использует те же проценты выплат, что и реальный счёт для того же актива, экспирации и момента.' },
        { q: 'Какой винрейт нужен при выплате 80%?', a: 'Минимум 55,6% для безубытка; около 61% — для ощутимой прибыли со временем.' },
        { q: 'OTC-активы действительно платят больше?', a: 'OTC-пары по выходным часто показывают 85–92%, поскольку в это время они среди самых торгуемых. Котировки формирует платформа — подробности в нашем гайде по OTC.' },
      ],
    },
    id: {
      title: 'Persentase payout Pocket Option dan aset terbaik untuk trading: cara kerja payout dan cara menemukan yang tertinggi',
      metaTitle: 'Payout Pocket Option & Aset Terbaik untuk Trading (2026)',
      metaDescription:
        'Cara kerja payout Pocket Option: mengapa berkisar 50% hingga 92%, apa yang mengubahnya, win rate impas yang dibutuhkan, serta aset dan jam mana yang biasanya memberi payout tertinggi.',
      excerpt:
        'Panduan jelas persentase payout pocketoption: arti sebenarnya “hingga 92%”, cara mengurutkan aset berdasarkan payout, dan aset forex, kripto, saham, serta OTC mana yang biasanya membayar paling besar.',
      coverAlt: 'Terminal trading Pocket Option — persentase payout tampil di samping aset',
      keyTakeaways: [
        'Payout adalah profit dari trade yang menang: pada 92%, trade $10 mengembalikan $19,20. Trade yang kalah kehilangan seluruh $10.',
        'Payout di Pocket Option bervariasi menurut aset, waktu, expiry, dan status akun — dari sekitar 50% hingga 92%, dengan boost sesekali di atas itu lewat achievement.',
        'Semakin tinggi payout, semakin rendah win rate yang dibutuhkan: 92% → impas 52,1%, 80% → 55,6%, 70% → 58,8%.',
        'Pasangan forex mayor saat sesi aktif dan pasangan OTC di akhir pekan biasanya membayar paling besar; aset eksotis atau tidak likuid membayar lebih rendah.',
        'Urutkan daftar aset berdasarkan payout di terminal sebelum setiap sesi — jangan trading aset hanya karena suka jika payout-nya turun ke 60%.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option mengiklankan payout “hingga 92%”. Banyak pemula membacanya sebagai “92% di setiap trade”, lalu mendapati pasangan favoritnya membayar 78% atau bahkan 55% pada saat tertentu. Panduan ini menjelaskan bagaimana payout pocketoption terbentuk, mengapa berubah sepanjang hari, cara menghitung win rate yang dibutuhkan untuk setiap level payout, dan aset serta jam mana yang biasanya menawarkan kondisi terbaik.' },
        { type: 'h2', id: 'what', text: 'Arti persentase payout' },
        { type: 'p', text: 'Dalam opsi biner, payout adalah profit tetap yang diterima jika prediksi Anda benar, dinyatakan sebagai persentase dari nominal trade. Jika trade $10 memiliki payout 92% dan ditutup in the money, Anda menerima $19,20 ($10 modal + $9,20 profit). Jika ditutup out of the money, Anda kehilangan $10. Asimetri ini — menang lebih kecil dari risiko — adalah alasan persentase payout begitu penting.' },
        { type: 'table', head: ['Nominal trade', 'Payout', 'Kembali jika menang', 'Profit', 'Rugi jika kalah'], rows: [
          ['$10', '92%', '$19,20', '$9,20', '$10'],
          ['$10', '80%', '$18,00', '$8,00', '$10'],
          ['$10', '70%', '$17,00', '$7,00', '$10'],
          ['$10', '50%', '$15,00', '$5,00', '$10'],
        ] },
        { type: 'h2', id: 'breakeven', text: 'Win rate impas untuk setiap payout' },
        { type: 'p', text: 'Win rate minimum agar tidak rugi adalah 1 / (1 + payout). Angkanya naik cepat saat payout turun, itulah sebabnya trading aset payout rendah jauh lebih sulit dalam jangka panjang.' },
        { type: 'table', head: ['Payout', 'Win rate impas', 'Win rate untuk +10% per 100 trade'], rows: [
          ['92%', '52,1%', '57,3%'],
          ['85%', '54,1%', '59,5%'],
          ['80%', '55,6%', '61,1%'],
          ['70%', '58,8%', '64,7%'],
          ['60%', '62,5%', '68,8%'],
          ['50%', '66,7%', '73,3%'],
        ] },
        { type: 'tip', title: 'Tetapkan payout minimum untuk diri sendiri', text: 'Kebanyakan trader konsisten menolak membuka trade di bawah 75–80%. Kalah tiga trade di payout 60% biayanya lebih besar daripada hasil menang tiga trade — matematikanya memang melawan Anda.' },
        { type: 'h2', id: 'factors', text: 'Apa yang mengubah payout di Pocket Option' },
        { type: 'ul', items: [
          'Aset — mayor likuid (EUR/USD, GBP/USD, BTC/USD) biasanya di puncak; pasangan eksotis dan saham yang kurang diperdagangkan membayar lebih rendah.',
          'Waktu — payout forex tertinggi saat sesi London dan New York dan turun di jam Asia yang tenang atau tepat sebelum pasar tutup.',
          'Expiry — payout bisa berbeda antara expiry 5 detik, 1 menit, dan 5 menit pada aset yang sama; trade cepat kadang membayar lebih rendah.',
          'Kondisi pasar — saat berita berdampak tinggi atau volatilitas ekstrem, platform bisa menurunkan payout sementara.',
          'Status akun dan achievement — sistem Gems/Achievement dan level akun lebih tinggi bisa menambah payout boost (misalnya +2–10%) di atas persentase dasar.',
          'Mode trading — Pocket Option menawarkan Quick trading (waktu tetap) dan Digital trading (expiry pada momen tertentu); payout aset yang sama bisa berbeda antar mode.',
        ] },
        { type: 'image', src: IMG_SETTINGS, alt: 'Dialog pengaturan Pocket Option dengan mode trading: Quick trading atau Digital trading', caption: 'Mode trading dipilih di Settings; cek payout di kedua mode untuk aset yang sama.' },
        { type: 'h2', id: 'find', text: 'Cara menemukan payout tertinggi saat ini' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal Pocket Option dengan daftar aset dan persentase payout', caption: 'Daftar aset menampilkan payout saat ini di samping setiap instrumen dan bisa diurutkan.' },
        { type: 'ol', items: [
          'Buka terminal dan klik nama aset saat ini di kiri atas untuk membuka daftar aset.',
          'Beralih antar tab (Currencies, Crypto, Commodities, Stocks, Indices) — masing-masing menampilkan persentase payout di kolom kanan.',
          'Urutkan berdasarkan payout (klik header persentase) atau cari nilai tertinggi; tambahkan 3–5 aset terbaik ke Favorit.',
          'Cek aset yang sama dengan expiry yang biasa Anda pakai — persentase berubah saat waktu expiry diubah.',
          'Cek ulang sebelum setiap sesi: peringkat berubah sepanjang hari.',
        ] },
        { type: 'h2', id: 'best', text: 'Aset yang biasanya membayar paling besar' },
        { type: 'table', head: ['Kategori', 'Contoh payout tinggi tipikal', 'Jam terbaik (UTC)', 'Payout tipikal*'], rows: [
          ['Forex mayor', 'EUR/USD, GBP/USD, AUD/USD, USD/JPY', '07:00–16:00 (overlap London/NY 12:00–16:00)', '80–92%'],
          ['Forex OTC (akhir pekan)', 'EUR/USD OTC, GBP/USD OTC, AUD/CAD OTC', 'Sab–Min, sepanjang hari', '85–92%'],
          ['Kripto', 'BTC/USD, ETH/USD', '24/7, paling likuid 13:00–21:00', '70–90%'],
          ['Komoditas', 'Emas, Perak, Brent', '08:00–17:00', '60–85%'],
          ['Saham', 'Apple, Tesla, Microsoft (dan versi OTC)', '13:30–20:00 (sesi AS)', '50–80%'],
          ['Indeks', 'S&P 500, DAX, Nikkei 225 (dan OTC)', 'Jam sesi lokal', '50–80%'],
        ] },
        { type: 'p', text: '*Rentang bersifat indikatif, berdasarkan pengamatan 2026; platform menetapkan payout secara dinamis dan bisa di luar rentang ini kapan saja. Selalu andalkan persentase langsung di terminal.' },
        { type: 'image', src: IMG_COINBASE, alt: 'Grafik Coinbase OTC di Pocket Option', caption: 'Versi OTC saham seperti Coinbase memungkinkan trading di luar jam bursa, sering dengan payout kompetitif.' },
        { type: 'h2', id: 'strategy', text: 'Trading sadar payout: rutinitas sederhana' },
        { type: 'ul', items: [
          'Sebelum sesi, daftar 3–5 aset di atas payout minimum Anda (misalnya 80%).',
          'Trading hanya aset tersebut dan hanya di jam aktifnya.',
          'Jika payout aset turun di bawah minimum di tengah sesi, berhenti trading aset itu — jangan kompensasi dengan nominal lebih besar.',
          'Catat jurnal dengan payout setiap trade; setelah 100 trade, bandingkan win rate riil Anda dengan tabel impas di atas.',
          'Manfaatkan sistem achievement: beberapa reward menambah payout boost sementara — aktifkan di jam terbaik Anda.',
        ] },
        { type: 'image', src: IMG_VIX, alt: 'Grafik VIX OTC di Pocket Option', caption: 'Indeks volatilitas seperti VIX OTC bisa memberi payout tinggi tetapi bergerak tajam — sesuaikan ukuran posisi.' },
        { type: 'warn', title: 'Payout tinggi bukan berarti profit mudah', text: 'Payout 92% tetap berarti kerugian di trade yang kalah lebih besar dari keuntungan di trade yang menang. Payout hanya mengurangi win rate yang dibutuhkan; tidak menciptakan keunggulan. Opsi biner berisiko tinggi — trading dengan nominal yang sanggup Anda rugikan dan uji setiap ide di demo dulu.' },
        { type: 'cta', text: 'Lihat payout langsung sendiri: buka demo gratis, urutkan daftar aset berdasarkan payout, dan berlatih dengan aset teratas sebelum deposit mulai $5.', label: 'Buka akun demo gratis' },
      ],
      faq: [
        { q: 'Berapa payout maksimum di Pocket Option?', a: 'Hingga 92% pada aset tertentu di waktu tertentu, dengan kemungkinan boost dari achievement. Payout langsung tipikal pada aset utama adalah 70–90%.' },
        { q: 'Kenapa payout berubah sepanjang hari?', a: 'Payout bergantung pada likuiditas, volatilitas, sesi, dan expiry. Tertinggi saat jam pasar aktif untuk aset tersebut dan turun saat periode tenang atau event berita.' },
        { q: 'Aset mana yang payout-nya tertinggi di Pocket Option?', a: 'Berubah terus. Pasangan forex mayor saat sesi London/New York dan pasangan OTC di akhir pekan biasanya di puncak. Urutkan daftar aset berdasarkan payout untuk melihat pemimpin saat ini.' },
        { q: 'Apakah payout sama di akun demo dan riil?', a: 'Ya, demo memakai persentase payout yang sama dengan akun riil untuk aset, expiry, dan momen yang sama.' },
        { q: 'Win rate berapa yang dibutuhkan di payout 80%?', a: 'Minimal 55,6% hanya untuk impas; sekitar 61% untuk profit yang berarti seiring waktu.' },
        { q: 'Apakah aset OTC benar-benar membayar lebih besar?', a: 'Pasangan OTC di akhir pekan sering menunjukkan payout 85–92% karena termasuk aset paling diperdagangkan saat itu. Kuotasinya ditetapkan platform — lihat panduan OTC kami untuk detailnya.' },
      ],
    },
  },
};
