import type { BlogPost } from '../types';

const IMG_CONDITIONS = '/images/blog/po-trading-conditions.webp';
const IMG_DEPOSIT = '/images/blog/po-deposit-page.webp';

export const pocketOptionMinimumDeposit: BlogPost = {
  slug: 'pocket-option-minimum-deposit',
  category: 'payments',
  cover: '/images/blog/pocket-option-minimum-deposit.webp',
  publishedAt: '2026-09-29',
  updatedAt: '2026-09-29',
  readingMinutes: 6,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option Minimum Deposit',
      metaTitle: 'Pocket Option Minimum Deposit: $5 Explained (2026)',
      metaDescription:
        'The Pocket Option minimum deposit is $5. Which methods allow it, minimum trade of $1, what a $5, $10 or $50 account can do and how to make the first deposit count.',
      excerpt:
        '$5 is enough to open a real account on pocketoption. Here is which payment methods support the minimum, what you can trade with it and a realistic plan for a small first deposit.',
      coverAlt: 'Pocket Option trading conditions: $5 minimum deposit, $1 minimum trade, $0 commission',
      keyTakeaways: [
        'The Pocket Option minimum deposit is $5 for most methods; a few local providers require $10.',
        'Minimum trade is $1, so a $5 account allows five trades — good for testing, not for a strategy.',
        'No deposit fee on the platform side; only bank or network fees may apply.',
        'A $20–$50 first deposit is the practical minimum for following the 1–2% risk rule.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option has one of the lowest entry thresholds among trading platforms: the minimum deposit is $5 and the minimum trade is $1. That makes it possible to test the real account for the price of a coffee. This guide explains which methods support the $5 minimum, what such a small balance realistically allows and how much you should actually start with.' },
        { type: 'h2', id: 'amount', text: 'How much is the minimum deposit on Pocket Option?' },
        { type: 'p', text: 'The official minimum is $5 (or the equivalent in your account currency). It applies to cards, most e-wallets and cryptocurrencies. Some local payment providers — certain bank transfers or mobile money services — set their own floor of $10. The exact minimum is always shown next to the method on the deposit page before you confirm.' },
        { type: 'image', src: IMG_CONDITIONS, alt: 'Pocket Option conditions: $5 minimum investment, $1 minimum trade, $0 commission on deposit and withdrawal', caption: 'Trading conditions from the official homepage.' },
        { type: 'table', head: ['Method', 'Minimum deposit', 'Crediting time'], rows: [
          ['Visa / Mastercard', '$5', 'Instant – a few hours'],
          ['Crypto (USDT, BTC, ETH, LTC…)', '$5 (network fee extra)', '5–30 minutes'],
          ['E-wallets (Skrill, Neteller, Perfect Money…)', '$5', 'Instant'],
          ['Local methods (Pix, UPI, M-Pesa, bKash…)', '$5–$10', 'Instant – 1 hour'],
          ['Bank transfer', '$10', '1–3 business days'],
        ] },
        { type: 'h2', id: 'fees', text: 'Are there fees on the minimum deposit?' },
        { type: 'p', text: 'Pocket Option itself charges no deposit fee — a $5 deposit shows up as $5 on the balance. What can reduce the amount is on the payment side: a blockchain network fee for crypto (USDT TRC-20 is the cheapest option), a currency conversion by your card issuer or an e-wallet commission. For very small deposits choose a method with no fixed fee, otherwise a $1–$2 charge on a $5 deposit is significant.' },
        { type: 'tip', title: 'Cheapest way to deposit $5', text: 'A card in your account currency or USDT on the TRC-20 network usually arrives with zero or near-zero deduction.' },
        { type: 'h2', id: 'what-you-can-do', text: 'What can you do with a $5 account?' },
        { type: 'p', text: 'With a $1 minimum trade, $5 gives you five trades at the smallest size. That is enough to verify that deposits, the terminal, execution and withdrawals work on a real account — and that is exactly what a first $5 deposit should be used for. It is not enough to run a strategy: one trade is 20% of the balance, so two losses in a row wipe out almost half of it.' },
        { type: 'ul', items: [
          '$5 — test the full cycle: deposit, a few $1 trades, withdrawal request.',
          '$20 — allows $1 trades at 5% risk each; still aggressive, but you can trade for a week.',
          '$50 — the first balance where the 1–2% rule becomes workable with $1 trades.',
          '$100+ — comfortable for a beginner following a plan and journaling trades.',
        ] },
        { type: 'h2', id: 'how-to', text: 'How to make the minimum deposit' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Pocket Option deposit page with payment methods and amount field', caption: 'Finance → Deposit: pick a method and enter at least $5.' },
        { type: 'ol', items: [
          'Log in and open Finance → Deposit.',
          'Choose a method that shows a $5 minimum.',
          'Enter 5 (or more) in the amount field. If a bonus appears, decide whether you want it — a bonus adds a turnover requirement before withdrawal.',
          'Confirm on the provider’s page and return to the platform; the balance updates when the payment is processed.',
        ] },
        { type: 'warn', title: 'Bonus on a small deposit', text: 'A +50% bonus on $5 is $2.50 — but it locks the whole balance behind a turnover rule until you trade the required volume. For a test deposit, skip the bonus.' },
        { type: 'h2', id: 'withdraw', text: 'Can you withdraw a $5 deposit?' },
        { type: 'p', text: 'The minimum withdrawal is $10, so you cannot withdraw exactly $5. Either deposit $10 to test the withdrawal path, or trade the $5 up to $10 first. Verification is required before the first withdrawal, so complete it right after depositing.' },
        { type: 'cta', text: 'Ready to open a real account from $5? Register and choose your payment method.', label: 'Open Pocket Option account' },
      ],
      faq: [
        { q: 'What is the minimum deposit on Pocket Option?', a: '$5 for cards, crypto and most e-wallets. Some local methods and bank transfers require $10.' },
        { q: 'What is the minimum trade on Pocket Option?', a: '$1 per trade on both quick and binary trading.' },
        { q: 'Is there a fee for depositing $5?', a: 'Not from Pocket Option. Your bank, e-wallet or the crypto network may charge its own fee.' },
        { q: 'Can I start trading with $5?', a: 'Yes, technically — five $1 trades. For a real strategy with proper risk management plan on $50 or more.' },
        { q: 'Can I withdraw $5?', a: 'No, the minimum withdrawal is $10. Deposit $10 or grow the balance first.' },
        { q: 'Is there a minimum deposit for the demo account?', a: 'No. The demo account is free with a $50,000 virtual balance and requires no deposit.' },
      ],
    },
    pt: {
      title: 'Depósito mínimo na Pocket Option',
      metaTitle: 'Depósito mínimo Pocket Option: $5 explicado (2026)',
      metaDescription:
        'O depósito mínimo na Pocket Option é $5. Quais métodos aceitam, operação mínima de $1, o que dá para fazer com $5, $10 ou $50 e como aproveitar o primeiro depósito.',
      excerpt:
        '$5 bastam para abrir conta real na pocketoption. Veja quais métodos aceitam o mínimo, o que dá para operar e um plano realista para um primeiro depósito pequeno.',
      coverAlt: 'Condições da Pocket Option: depósito mínimo $5, operação mínima $1, comissão $0',
      keyTakeaways: [
        'O depósito mínimo na Pocket Option é $5 na maioria dos métodos; alguns provedores locais exigem $10.',
        'A operação mínima é $1, então uma conta de $5 permite cinco operações — bom para testar, não para estratégia.',
        'Sem taxa de depósito do lado da plataforma; só podem existir taxas do banco ou da rede.',
        'Um primeiro depósito de $20–$50 é o mínimo prático para seguir a regra de risco de 1–2%.',
      ],
      blocks: [
        { type: 'p', text: 'A Pocket Option tem um dos menores valores de entrada entre as plataformas de trading: depósito mínimo de $5 e operação mínima de $1. Isso permite testar a conta real pelo preço de um café. Este guia explica quais métodos aceitam o mínimo de $5, o que um saldo tão pequeno permite de verdade e com quanto você deveria começar.' },
        { type: 'h2', id: 'amount', text: 'Qual é o depósito mínimo na Pocket Option?' },
        { type: 'p', text: 'O mínimo oficial é $5 (ou o equivalente na moeda da conta). Vale para cartões, a maioria das carteiras eletrônicas e criptomoedas. Alguns provedores locais — certas transferências bancárias ou serviços de dinheiro móvel — definem piso próprio de $10. O mínimo exato aparece sempre ao lado do método na página de depósito antes de confirmar.' },
        { type: 'image', src: IMG_CONDITIONS, alt: 'Condições da Pocket Option: investimento mínimo $5, operação mínima $1, comissão $0 em depósito e saque', caption: 'Condições de negociação da página inicial oficial.' },
        { type: 'table', head: ['Método', 'Depósito mínimo', 'Prazo de crédito'], rows: [
          ['Visa / Mastercard', '$5', 'Instantâneo – algumas horas'],
          ['Cripto (USDT, BTC, ETH, LTC…)', '$5 (+ taxa de rede)', '5–30 minutos'],
          ['E-wallets (Skrill, Neteller, Perfect Money…)', '$5', 'Instantâneo'],
          ['Métodos locais (Pix, UPI, M-Pesa, bKash…)', '$5–$10', 'Instantâneo – 1 hora'],
          ['Transferência bancária', '$10', '1–3 dias úteis'],
        ] },
        { type: 'h2', id: 'fees', text: 'Há taxas no depósito mínimo?' },
        { type: 'p', text: 'A Pocket Option não cobra taxa de depósito — $5 depositados aparecem como $5 no saldo. O que pode reduzir o valor está do lado do pagamento: taxa de rede em cripto (USDT TRC-20 é a opção mais barata), conversão de moeda do emissor do cartão ou comissão da carteira eletrônica. Para depósitos muito pequenos escolha um método sem taxa fixa, senão $1–$2 sobre $5 pesam muito.' },
        { type: 'tip', title: 'Jeito mais barato de depositar $5', text: 'Cartão na moeda da conta ou USDT na rede TRC-20 costuma chegar com desconto zero ou quase zero.' },
        { type: 'h2', id: 'what-you-can-do', text: 'O que dá para fazer com uma conta de $5?' },
        { type: 'p', text: 'Com operação mínima de $1, $5 rendem cinco operações no menor tamanho. É suficiente para confirmar que depósito, terminal, execução e saque funcionam na conta real — e é exatamente para isso que um primeiro depósito de $5 deve servir. Não basta para rodar uma estratégia: uma operação é 20% do saldo, e duas perdas seguidas eliminam quase metade.' },
        { type: 'ul', items: [
          '$5 — teste o ciclo completo: depósito, algumas operações de $1, pedido de saque.',
          '$20 — permite operações de $1 com 5% de risco cada; ainda agressivo, mas dá para operar uma semana.',
          '$50 — primeiro saldo em que a regra de 1–2% funciona com operações de $1.',
          '$100+ — confortável para iniciante que segue um plano e registra as operações.',
        ] },
        { type: 'h2', id: 'how-to', text: 'Como fazer o depósito mínimo' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Página de depósito da Pocket Option com métodos de pagamento e campo de valor', caption: 'Finanças → Depósito: escolha o método e insira pelo menos $5.' },
        { type: 'ol', items: [
          'Faça login e abra Finanças → Depósito.',
          'Escolha um método que mostre mínimo de $5.',
          'Digite 5 (ou mais) no campo de valor. Se aparecer bônus, decida se quer — bônus adiciona exigência de giro antes do saque.',
          'Confirme na página do provedor e volte à plataforma; o saldo atualiza quando o pagamento é processado.',
        ] },
        { type: 'warn', title: 'Bônus em depósito pequeno', text: 'Um bônus de +50% sobre $5 são $2,50 — mas trava todo o saldo atrás da regra de giro até você operar o volume exigido. Para um depósito de teste, dispense o bônus.' },
        { type: 'h2', id: 'withdraw', text: 'Dá para sacar um depósito de $5?' },
        { type: 'p', text: 'O saque mínimo é $10, então não dá para sacar exatamente $5. Deposite $10 para testar o caminho do saque ou opere os $5 até chegar a $10. A verificação é obrigatória antes do primeiro saque — conclua logo após depositar.' },
        { type: 'cta', text: 'Pronto para abrir conta real a partir de $5? Cadastre-se e escolha seu método de pagamento.', label: 'Abrir conta Pocket Option' },
      ],
      faq: [
        { q: 'Qual é o depósito mínimo na Pocket Option?', a: '$5 para cartões, cripto e a maioria das e-wallets. Alguns métodos locais e transferências bancárias exigem $10.' },
        { q: 'Qual é a operação mínima na Pocket Option?', a: '$1 por operação, tanto em quick trading quanto em opções binárias.' },
        { q: 'Há taxa para depositar $5?', a: 'Não da Pocket Option. Seu banco, carteira eletrônica ou a rede cripto podem cobrar taxa própria.' },
        { q: 'Posso começar a operar com $5?', a: 'Tecnicamente sim — cinco operações de $1. Para uma estratégia real com gestão de risco, planeje $50 ou mais.' },
        { q: 'Posso sacar $5?', a: 'Não, o saque mínimo é $10. Deposite $10 ou aumente o saldo antes.' },
        { q: 'Há depósito mínimo para a conta demo?', a: 'Não. A demo é gratuita, com $50.000 virtuais, sem depósito.' },
      ],
    },
    es: {
      title: 'Depósito mínimo en Pocket Option',
      metaTitle: 'Depósito mínimo Pocket Option: $5 explicado (2026)',
      metaDescription:
        'El depósito mínimo en Pocket Option es $5. Qué métodos lo permiten, operación mínima de $1, qué se puede hacer con $5, $10 o $50 y cómo aprovechar el primer depósito.',
      excerpt:
        'Con $5 basta para abrir una cuenta real en pocketoption. Qué métodos aceptan el mínimo, qué puedes operar con él y un plan realista para un primer depósito pequeño.',
      coverAlt: 'Condiciones de Pocket Option: depósito mínimo $5, operación mínima $1, comisión $0',
      keyTakeaways: [
        'El depósito mínimo en Pocket Option es $5 en la mayoría de métodos; algunos proveedores locales exigen $10.',
        'La operación mínima es $1, así que una cuenta de $5 permite cinco operaciones — sirve para probar, no para una estrategia.',
        'Sin comisión de depósito por parte de la plataforma; solo pueden aplicarse comisiones del banco o de la red.',
        'Un primer depósito de $20–$50 es el mínimo práctico para seguir la regla de riesgo del 1–2%.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option tiene uno de los umbrales de entrada más bajos entre las plataformas de trading: depósito mínimo de $5 y operación mínima de $1. Eso permite probar la cuenta real por el precio de un café. Esta guía explica qué métodos admiten el mínimo de $5, qué permite realmente un saldo tan pequeño y con cuánto deberías empezar.' },
        { type: 'h2', id: 'amount', text: '¿Cuál es el depósito mínimo en Pocket Option?' },
        { type: 'p', text: 'El mínimo oficial es $5 (o el equivalente en la moneda de tu cuenta). Aplica a tarjetas, la mayoría de monederos electrónicos y criptomonedas. Algunos proveedores locales — ciertas transferencias bancarias o servicios de dinero móvil — fijan su propio mínimo de $10. El mínimo exacto siempre aparece junto al método en la página de depósito antes de confirmar.' },
        { type: 'image', src: IMG_CONDITIONS, alt: 'Condiciones de Pocket Option: inversión mínima $5, operación mínima $1, comisión $0 en depósito y retiro', caption: 'Condiciones de trading de la página oficial.' },
        { type: 'table', head: ['Método', 'Depósito mínimo', 'Tiempo de acreditación'], rows: [
          ['Visa / Mastercard', '$5', 'Instantáneo – unas horas'],
          ['Cripto (USDT, BTC, ETH, LTC…)', '$5 (+ comisión de red)', '5–30 minutos'],
          ['Monederos (Skrill, Neteller, Perfect Money…)', '$5', 'Instantáneo'],
          ['Métodos locales (Pix, UPI, Mercado Pago, M-Pesa…)', '$5–$10', 'Instantáneo – 1 hora'],
          ['Transferencia bancaria', '$10', '1–3 días hábiles'],
        ] },
        { type: 'h2', id: 'fees', text: '¿Hay comisiones en el depósito mínimo?' },
        { type: 'p', text: 'Pocket Option no cobra comisión por depositar — $5 depositados aparecen como $5 en el saldo. Lo que puede reducir el importe está del lado del pago: la comisión de red en cripto (USDT TRC-20 es la opción más barata), la conversión de divisa del emisor de tu tarjeta o la comisión del monedero. Para depósitos muy pequeños elige un método sin comisión fija; si no, $1–$2 sobre $5 pesan mucho.' },
        { type: 'tip', title: 'La forma más barata de depositar $5', text: 'Una tarjeta en la moneda de tu cuenta o USDT por la red TRC-20 suele llegar con descuento cero o casi cero.' },
        { type: 'h2', id: 'what-you-can-do', text: '¿Qué puedes hacer con una cuenta de $5?' },
        { type: 'p', text: 'Con operación mínima de $1, $5 dan para cinco operaciones al tamaño más pequeño. Es suficiente para comprobar que depósito, terminal, ejecución y retiros funcionan en la cuenta real — y exactamente para eso debería servir un primer depósito de $5. No alcanza para ejecutar una estrategia: una operación es el 20% del saldo, y dos pérdidas seguidas borran casi la mitad.' },
        { type: 'ul', items: [
          '$5 — prueba el ciclo completo: depósito, unas operaciones de $1, solicitud de retiro.',
          '$20 — permite operaciones de $1 al 5% de riesgo; aún agresivo, pero puedes operar una semana.',
          '$50 — el primer saldo donde la regla del 1–2% funciona con operaciones de $1.',
          '$100+ — cómodo para un principiante que sigue un plan y lleva un diario.',
        ] },
        { type: 'h2', id: 'how-to', text: 'Cómo hacer el depósito mínimo' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Página de depósito de Pocket Option con métodos de pago y campo de importe', caption: 'Finanzas → Depósito: elige un método e introduce al menos $5.' },
        { type: 'ol', items: [
          'Inicia sesión y abre Finanzas → Depósito.',
          'Elige un método que muestre un mínimo de $5.',
          'Escribe 5 (o más) en el campo de importe. Si aparece un bono, decide si lo quieres — el bono añade un requisito de volumen antes de retirar.',
          'Confirma en la página del proveedor y vuelve a la plataforma; el saldo se actualiza cuando se procesa el pago.',
        ] },
        { type: 'warn', title: 'Bono en un depósito pequeño', text: 'Un bono del +50% sobre $5 son $2,50 — pero bloquea todo el saldo tras la regla de volumen hasta que operes lo exigido. Para un depósito de prueba, omite el bono.' },
        { type: 'h2', id: 'withdraw', text: '¿Se puede retirar un depósito de $5?' },
        { type: 'p', text: 'El retiro mínimo es $10, así que no puedes retirar exactamente $5. Deposita $10 para probar el retiro o haz crecer los $5 hasta $10. La verificación es obligatoria antes del primer retiro — complétala justo después de depositar.' },
        { type: 'cta', text: '¿Listo para abrir una cuenta real desde $5? Regístrate y elige tu método de pago.', label: 'Abrir cuenta Pocket Option' },
      ],
      faq: [
        { q: '¿Cuál es el depósito mínimo en Pocket Option?', a: '$5 para tarjetas, cripto y la mayoría de monederos. Algunos métodos locales y transferencias bancarias exigen $10.' },
        { q: '¿Cuál es la operación mínima en Pocket Option?', a: '$1 por operación, tanto en quick trading como en opciones binarias.' },
        { q: '¿Hay comisión por depositar $5?', a: 'No por parte de Pocket Option. Tu banco, monedero o la red cripto pueden cobrar la suya.' },
        { q: '¿Puedo empezar a operar con $5?', a: 'Técnicamente sí — cinco operaciones de $1. Para una estrategia real con gestión de riesgo, planifica $50 o más.' },
        { q: '¿Puedo retirar $5?', a: 'No, el retiro mínimo es $10. Deposita $10 o aumenta el saldo primero.' },
        { q: '¿Hay depósito mínimo para la cuenta demo?', a: 'No. La demo es gratis, con $50,000 virtuales y sin depósito.' },
      ],
    },
    ru: {
      title: 'Минимальный депозит Pocket Option',
      metaTitle: 'Минимальный депозит Pocket Option: $5 — что это даёт (2026)',
      metaDescription:
        'Минимальный депозит на Pocket Option — $5. Какие способы его поддерживают, минимальная сделка $1, что можно сделать с $5, $10 или $50 и как правильно внести первый депозит.',
      excerpt:
        '$5 достаточно, чтобы открыть реальный счёт на pocketoption. Какие способы оплаты поддерживают минимум, что на него можно наторговать и реалистичный план для небольшого первого депозита.',
      coverAlt: 'Условия Pocket Option: минимальный депозит $5, минимальная сделка $1, комиссия $0',
      keyTakeaways: [
        'Минимальный депозит Pocket Option — $5 для большинства способов; некоторые локальные провайдеры требуют $10.',
        'Минимальная сделка — $1, поэтому счёт на $5 даёт пять сделок: хорошо для теста, но не для стратегии.',
        'Комиссии за депозит со стороны платформы нет — только возможные сборы банка или сети.',
        'Первый депозит $20–$50 — практический минимум для соблюдения правила риска 1–2%.',
      ],
      blocks: [
        { type: 'p', text: 'У Pocket Option один из самых низких порогов входа среди торговых платформ: минимальный депозит $5 и минимальная сделка $1. Это позволяет протестировать реальный счёт по цене чашки кофе. В этом руководстве — какие способы поддерживают минимум $5, что реально даёт такой маленький баланс и с какой суммы стоит начинать на самом деле.' },
        { type: 'h2', id: 'amount', text: 'Какой минимальный депозит на Pocket Option?' },
        { type: 'p', text: 'Официальный минимум — $5 (или эквивалент в валюте счёта). Он действует для карт, большинства электронных кошельков и криптовалют. Некоторые локальные провайдеры — отдельные банковские переводы или сервисы мобильных денег — устанавливают свой порог в $10. Точный минимум всегда показан рядом со способом на странице пополнения до подтверждения.' },
        { type: 'image', src: IMG_CONDITIONS, alt: 'Условия Pocket Option: минимальная инвестиция $5, минимальная сделка $1, комиссия $0 за депозит и вывод', caption: 'Торговые условия с официальной главной страницы.' },
        { type: 'table', head: ['Способ', 'Минимальный депозит', 'Время зачисления'], rows: [
          ['Visa / Mastercard', '$5', 'Мгновенно – несколько часов'],
          ['Крипта (USDT, BTC, ETH, LTC…)', '$5 (+ комиссия сети)', '5–30 минут'],
          ['Электронные кошельки (Skrill, Neteller, Perfect Money…)', '$5', 'Мгновенно'],
          ['Локальные способы (Pix, UPI, M-Pesa, bKash…)', '$5–$10', 'Мгновенно – 1 час'],
          ['Банковский перевод', '$10', '1–3 рабочих дня'],
        ] },
        { type: 'h2', id: 'fees', text: 'Есть ли комиссии на минимальном депозите?' },
        { type: 'p', text: 'Сама Pocket Option комиссию за депозит не берёт — внесённые $5 отображаются как $5 на балансе. Уменьшить сумму может только платёжная сторона: комиссия сети при крипте (USDT TRC-20 — самый дешёвый вариант), конвертация валюты банком-эмитентом или комиссия кошелька. Для очень маленьких депозитов выбирайте способ без фиксированного сбора — иначе $1–$2 с $5 это ощутимо.' },
        { type: 'tip', title: 'Самый дешёвый способ внести $5', text: 'Карта в валюте счёта или USDT в сети TRC-20 обычно приходят с нулевым или почти нулевым удержанием.' },
        { type: 'h2', id: 'what-you-can-do', text: 'Что можно сделать со счётом на $5?' },
        { type: 'p', text: 'При минимальной сделке $1 на $5 можно открыть пять сделок минимального размера. Этого достаточно, чтобы убедиться, что пополнение, терминал, исполнение и вывод работают на реальном счёте — именно для этого и нужен первый депозит в $5. Для стратегии этого мало: одна сделка — это 20% баланса, и два убытка подряд съедают почти половину.' },
        { type: 'ul', items: [
          '$5 — протестировать полный цикл: депозит, несколько сделок по $1, заявка на вывод.',
          '$20 — сделки по $1 при риске 5% каждая; всё ещё агрессивно, но можно торговать неделю.',
          '$50 — первый баланс, на котором правило 1–2% работает со сделками по $1.',
          '$100+ — комфортно для новичка, который следует плану и ведёт журнал сделок.',
        ] },
        { type: 'h2', id: 'how-to', text: 'Как внести минимальный депозит' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Страница пополнения Pocket Option со способами оплаты и полем суммы', caption: 'Финансы → Пополнение: выберите способ и введите не менее $5.' },
        { type: 'ol', items: [
          'Войдите в аккаунт и откройте Финансы → Пополнение.',
          'Выберите способ с минимумом $5.',
          'Введите 5 (или больше) в поле суммы. Если предлагается бонус, решите, нужен ли он — бонус добавляет требование по обороту перед выводом.',
          'Подтвердите на странице провайдера и вернитесь на платформу; баланс обновится после обработки платежа.',
        ] },
        { type: 'warn', title: 'Бонус на маленький депозит', text: 'Бонус +50% на $5 — это $2,50, но он блокирует весь баланс правилом оборота, пока вы не наторгуете требуемый объём. Для тестового депозита от бонуса лучше отказаться.' },
        { type: 'h2', id: 'withdraw', text: 'Можно ли вывести депозит в $5?' },
        { type: 'p', text: 'Минимальный вывод — $10, поэтому ровно $5 вывести нельзя. Либо внесите $10, чтобы протестировать вывод, либо сначала наторгуйте с $5 до $10. Перед первым выводом обязательна верификация — пройдите её сразу после пополнения.' },
        { type: 'cta', text: 'Готовы открыть реальный счёт от $5? Зарегистрируйтесь и выберите способ оплаты.', label: 'Открыть счёт Pocket Option' },
      ],
      faq: [
        { q: 'Какой минимальный депозит на Pocket Option?', a: '$5 для карт, крипты и большинства электронных кошельков. Некоторые локальные способы и банковские переводы требуют $10.' },
        { q: 'Какая минимальная сделка на Pocket Option?', a: '$1 за сделку — и в быстрой торговле, и в бинарных опционах.' },
        { q: 'Есть ли комиссия за депозит $5?', a: 'Со стороны Pocket Option — нет. Ваш банк, кошелёк или криптосеть могут взять свою комиссию.' },
        { q: 'Можно ли начать торговать с $5?', a: 'Технически да — пять сделок по $1. Для реальной стратегии с управлением риском планируйте от $50.' },
        { q: 'Можно ли вывести $5?', a: 'Нет, минимальный вывод — $10. Внесите $10 или сначала увеличьте баланс.' },
        { q: 'Есть ли минимальный депозит для демо-счёта?', a: 'Нет. Демо бесплатно, с виртуальным балансом $50 000 и без депозита.' },
      ],
    },
    id: {
      title: 'Deposit Minimum Pocket Option',
      metaTitle: 'Deposit Minimum Pocket Option: $5 Dijelaskan (2026)',
      metaDescription:
        'Deposit minimum Pocket Option adalah $5. Metode mana yang mendukungnya, trade minimum $1, apa yang bisa dilakukan dengan $5, $10 atau $50, dan cara memanfaatkan deposit pertama.',
      excerpt:
        '$5 cukup untuk membuka akun riil di pocketoption. Ini metode pembayaran yang mendukung minimum, apa yang bisa Anda tradingkan, dan rencana realistis untuk deposit pertama yang kecil.',
      coverAlt: 'Kondisi trading Pocket Option: deposit minimum $5, trade minimum $1, komisi $0',
      keyTakeaways: [
        'Deposit minimum Pocket Option adalah $5 untuk sebagian besar metode; beberapa penyedia lokal mensyaratkan $10.',
        'Trade minimum $1, jadi akun $5 memungkinkan lima trade — bagus untuk uji coba, bukan untuk strategi.',
        'Tidak ada biaya deposit dari sisi platform; hanya biaya bank atau jaringan yang mungkin berlaku.',
        'Deposit pertama $20–$50 adalah minimum praktis untuk mengikuti aturan risiko 1–2%.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option punya salah satu ambang masuk terendah di antara platform trading: deposit minimum $5 dan trade minimum $1. Artinya Anda bisa menguji akun riil seharga secangkir kopi. Panduan ini menjelaskan metode mana yang mendukung minimum $5, apa yang realistis bisa dilakukan dengan saldo sekecil itu, dan sebenarnya berapa yang sebaiknya Anda mulai.' },
        { type: 'h2', id: 'amount', text: 'Berapa deposit minimum di Pocket Option?' },
        { type: 'p', text: 'Minimum resmi adalah $5 (atau setara dalam mata uang akun). Berlaku untuk kartu, sebagian besar e-wallet, dan kripto. Beberapa penyedia pembayaran lokal — transfer bank tertentu atau layanan uang seluler — menetapkan batas sendiri $10. Minimum pastinya selalu ditampilkan di samping metode pada halaman deposit sebelum Anda konfirmasi.' },
        { type: 'image', src: IMG_CONDITIONS, alt: 'Kondisi Pocket Option: investasi minimum $5, trade minimum $1, komisi $0 untuk deposit dan penarikan', caption: 'Kondisi trading dari beranda resmi.' },
        { type: 'table', head: ['Metode', 'Deposit minimum', 'Waktu masuk'], rows: [
          ['Visa / Mastercard', '$5', 'Instan – beberapa jam'],
          ['Kripto (USDT, BTC, ETH, LTC…)', '$5 (+ biaya jaringan)', '5–30 menit'],
          ['E-wallet (Skrill, Neteller, Perfect Money…)', '$5', 'Instan'],
          ['Metode lokal (QRIS, DANA, OVO, bank lokal…)', '$5–$10', 'Instan – 1 jam'],
          ['Transfer bank', '$10', '1–3 hari kerja'],
        ] },
        { type: 'h2', id: 'fees', text: 'Apakah ada biaya untuk deposit minimum?' },
        { type: 'p', text: 'Pocket Option sendiri tidak mengenakan biaya deposit — $5 yang disetor muncul sebagai $5 di saldo. Yang bisa mengurangi jumlah ada di sisi pembayaran: biaya jaringan blockchain untuk kripto (USDT TRC-20 paling murah), konversi mata uang oleh penerbit kartu, atau komisi e-wallet. Untuk deposit sangat kecil pilih metode tanpa biaya tetap, karena potongan $1–$2 dari $5 sangat terasa.' },
        { type: 'tip', title: 'Cara termurah deposit $5', text: 'Kartu dalam mata uang akun atau USDT jaringan TRC-20 biasanya masuk tanpa potongan atau nyaris nol.' },
        { type: 'h2', id: 'what-you-can-do', text: 'Apa yang bisa dilakukan dengan akun $5?' },
        { type: 'p', text: 'Dengan trade minimum $1, $5 memberi lima trade ukuran terkecil. Itu cukup untuk memastikan deposit, terminal, eksekusi, dan penarikan berfungsi di akun riil — dan memang untuk itulah deposit pertama $5 sebaiknya digunakan. Tidak cukup untuk menjalankan strategi: satu trade = 20% saldo, dua kerugian beruntun menghapus hampir setengahnya.' },
        { type: 'ul', items: [
          '$5 — uji siklus penuh: deposit, beberapa trade $1, permintaan penarikan.',
          '$20 — memungkinkan trade $1 dengan risiko 5% per trade; masih agresif, tetapi bisa trading seminggu.',
          '$50 — saldo pertama di mana aturan 1–2% bisa dijalankan dengan trade $1.',
          '$100+ — nyaman untuk pemula yang mengikuti rencana dan mencatat jurnal trading.',
        ] },
        { type: 'h2', id: 'how-to', text: 'Cara melakukan deposit minimum' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Halaman deposit Pocket Option dengan metode pembayaran dan kolom jumlah', caption: 'Keuangan → Deposit: pilih metode dan masukkan minimal $5.' },
        { type: 'ol', items: [
          'Masuk dan buka Keuangan → Deposit.',
          'Pilih metode yang menampilkan minimum $5.',
          'Masukkan 5 (atau lebih) di kolom jumlah. Jika muncul bonus, putuskan apakah Anda mau — bonus menambah syarat turnover sebelum penarikan.',
          'Konfirmasi di halaman penyedia dan kembali ke platform; saldo diperbarui setelah pembayaran diproses.',
        ] },
        { type: 'warn', title: 'Bonus pada deposit kecil', text: 'Bonus +50% dari $5 hanya $2,50 — tetapi mengunci seluruh saldo di balik aturan turnover sampai Anda mencapai volume yang disyaratkan. Untuk deposit uji coba, lewati bonus.' },
        { type: 'h2', id: 'withdraw', text: 'Bisakah deposit $5 ditarik?' },
        { type: 'p', text: 'Penarikan minimum $10, jadi Anda tidak bisa menarik tepat $5. Setor $10 untuk menguji jalur penarikan, atau tradingkan $5 hingga menjadi $10 dulu. Verifikasi wajib sebelum penarikan pertama — selesaikan segera setelah deposit.' },
        { type: 'cta', text: 'Siap membuka akun riil mulai $5? Daftar dan pilih metode pembayaran Anda.', label: 'Buka akun Pocket Option' },
      ],
      faq: [
        { q: 'Berapa deposit minimum di Pocket Option?', a: '$5 untuk kartu, kripto, dan sebagian besar e-wallet. Beberapa metode lokal dan transfer bank mensyaratkan $10.' },
        { q: 'Berapa trade minimum di Pocket Option?', a: '$1 per trade, baik quick trading maupun opsi biner.' },
        { q: 'Apakah ada biaya untuk deposit $5?', a: 'Tidak dari Pocket Option. Bank, e-wallet, atau jaringan kripto Anda mungkin mengenakan biaya sendiri.' },
        { q: 'Bisakah mulai trading dengan $5?', a: 'Secara teknis ya — lima trade $1. Untuk strategi nyata dengan manajemen risiko, rencanakan $50 atau lebih.' },
        { q: 'Bisakah menarik $5?', a: 'Tidak, penarikan minimum $10. Setor $10 atau tumbuhkan saldo dulu.' },
        { q: 'Apakah ada deposit minimum untuk akun demo?', a: 'Tidak. Akun demo gratis dengan saldo virtual $50.000 dan tidak butuh deposit.' },
      ],
    },
  },
};
