import type { BlogPost } from '../types';

const IMG_PROFILE = '/images/quick-start/2_1.webp';
const IMG_DOCS = '/images/quick-start/2_2.webp';
const IMG_WALLET = '/images/quick-start/6_2.webp';

export const pocketOptionAccountVerification: BlogPost = {
  slug: 'pocket-option-account-verification',
  category: 'tutorial',
  cover: '/images/blog/pocket-option-account-verification.webp',
  publishedAt: '2026-09-21',
  updatedAt: '2026-09-21',
  readingMinutes: 8,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option account verification (KYC): documents, steps, timing and why it gets rejected',
      metaTitle: 'Pocket Option Verification (KYC) – Documents, Steps, Timing',
      metaDescription:
        'Pocket Option account verification guide: which documents are accepted, how to upload ID, address and card proofs, how long review takes, rejection reasons and withdrawal rules.',
      excerpt:
        'Everything about pocketoption KYC: identity, address and payment-method verification, the upload process in Profile, typical review time and how to avoid a rejected document.',
      coverAlt: 'Identity document, bank card and security lock — Pocket Option account verification',
      keyTakeaways: [
        'Verification (KYC) on Pocket Option has three parts: identity (passport/ID/driving licence), address (utility bill or bank statement) and payment method (card photo).',
        'You can register, use the demo, deposit and trade before verification, but withdrawals are typically held until KYC is complete.',
        'Documents are uploaded in Profile → Verification; review usually takes from a few hours up to 1–3 business days.',
        'Most rejections are caused by blurry photos, cropped edges, expired documents or a name/address that does not match the registration data.',
        'Verify right after your first deposit — not at the moment you want to withdraw — to avoid delays.',
      ],
      blocks: [
        { type: 'p', text: 'Sooner or later every Pocket Option trader meets the verification screen — usually when requesting the first withdrawal. KYC (Know Your Customer) is a standard anti-money-laundering requirement, and on pocketoption it is straightforward if you know which documents are accepted and how to photograph them. This guide covers the full process, timing, and the mistakes that get documents rejected.' },
        { type: 'h2', id: 'why', text: 'Why Pocket Option asks for verification' },
        { type: 'ul', items: [
          'Regulatory requirement (AML/KYC) — the platform must confirm that the account holder is a real adult person.',
          'Protection against fraud: it prevents withdrawals to stolen cards and stops duplicate accounts.',
          'Payment security: the payment method used for deposits must belong to you, so withdrawals go back to the same person.',
        ] },
        { type: 'p', text: 'You do not need to verify to register, use the $50,000 demo, deposit or trade on a real account. However, the first withdrawal request normally triggers a verification check, and the payout is held until the documents are approved. The platform may also request verification at any time if it detects unusual activity.' },
        { type: 'h2', id: 'documents', text: 'Which documents are accepted' },
        { type: 'image', src: IMG_DOCS, alt: 'ID card, bank card and padlock — documents for Pocket Option verification', caption: 'Three document types: identity, address and payment method.' },
        { type: 'table', head: ['Verification', 'Accepted documents', 'Requirements'], rows: [
          ['Identity', 'Passport, national ID card, driving licence', 'Valid (not expired), full document visible, photo and date of birth readable'],
          ['Address', 'Utility bill, bank statement, tax letter, internet/phone bill', 'Issued within the last 3 months, showing your name and full address'],
          ['Payment method', 'Photo of the bank card used for deposit', 'First 6 and last 4 digits visible, middle digits and CVV covered; e-wallet: screenshot of the account page'],
        ] },
        { type: 'tip', title: 'Match the data exactly', text: 'The name, date of birth and address in your Pocket Option profile must be identical to the documents. Fill in the profile first (Profile → Personal data), then upload — a mismatch is the number-one reason for rejection.' },
        { type: 'h2', id: 'steps', text: 'How to verify your Pocket Option account step by step' },
        { type: 'image', src: IMG_PROFILE, alt: 'Profile avatar being scanned — personal data section on Pocket Option', caption: 'Verification starts in the Profile section of the platform.' },
        { type: 'ol', items: [
          'Log in and open Profile (click your avatar or name in the top-right corner).',
          'Fill in Personal data: full name as in your ID, date of birth, country, city and address. Save.',
          'Open the Verification tab. Confirm your e-mail and phone number if you have not yet.',
          'Identity: choose the document type and upload a clear photo or scan (JPG/PNG/PDF, all four corners visible, no glare).',
          'Address: upload a document issued within the last 3 months with your name and address.',
          'Payment method: upload a photo of your card (cover the middle 6 digits and the CVV) or an e-wallet screenshot.',
          'Submit. The status changes to “Under review”. You will receive an e-mail when each document is approved or rejected.',
        ] },
        { type: 'h2', id: 'timing', text: 'How long does verification take?' },
        { type: 'p', text: 'In our experience identity documents are typically checked within a few hours on business days; the full set usually takes up to 1–3 business days. Delays happen when the queue is long (after big promotions or tournaments) or when a document needs manual review. If the status has not changed after 3 business days, contact support via the chat inside the platform with your account e-mail.' },
        { type: 'h2', id: 'rejected', text: 'Why documents get rejected — and how to fix it' },
        { type: 'table', head: ['Rejection reason', 'How to fix'], rows: [
          ['Blurry or dark photo, glare on the document', 'Shoot in daylight, on a flat dark surface, without flash; check that all text is readable'],
          ['Edges cropped', 'The whole document, including all four corners, must be in the frame'],
          ['Expired document', 'Use a valid ID; expired passports are not accepted'],
          ['Name or address does not match the profile', 'Edit Personal data to match the document exactly, then re-upload'],
          ['Address proof older than 3 months', 'Download a fresh bank statement or the latest utility bill'],
          ['Screenshot or photocopy instead of the original', 'Photograph the physical document; for digital statements upload the original PDF'],
          ['Card digits fully visible or fully hidden', 'Show the first 6 and last 4 digits, cover the rest and the CVV'],
        ] },
        { type: 'warn', title: 'Never send documents outside the platform', text: 'Upload documents only through Profile → Verification. Pocket Option support does not ask for documents via Telegram, WhatsApp or e-mail attachments — anyone doing so is a scammer.' },
        { type: 'h2', id: 'withdrawal', text: 'Verification and withdrawals' },
        { type: 'image', src: IMG_WALLET, alt: 'Wallet with coins — withdrawals on Pocket Option after verification', caption: 'Once verified, withdrawals are processed normally, usually within 24 hours.' },
        { type: 'p', text: 'A withdrawal request made before verification is not cancelled — it stays in “Pending” until your documents are approved, then continues processing (usually within 24 hours). If you deposited with several cards or wallets, each payment method may need its own proof. Verification is done once; you will not be asked to repeat it unless your documents expire or your personal data changes.' },
        { type: 'cta', text: 'Not registered yet? Create an account, verify it after your first deposit and your withdrawals will never wait for documents.', label: 'Register on Pocket Option' },
      ],
      faq: [
        { q: 'Is verification mandatory on Pocket Option?', a: 'You can trade without it, but withdrawals are typically held until identity, address and payment-method verification is complete.' },
        { q: 'What documents do I need for Pocket Option verification?', a: 'A valid passport, ID card or driving licence; a proof of address issued within 3 months; and a photo of the bank card or e-wallet used for deposit.' },
        { q: 'How long does Pocket Option verification take?', a: 'Usually from a few hours to 1–3 business days. Contact support if there is no update after 3 business days.' },
        { q: 'Can I withdraw without verification?', a: 'Generally no — the withdrawal request waits in Pending until documents are approved, then continues automatically.' },
        { q: 'Why was my document rejected?', a: 'Most often because of a blurry photo, cropped edges, an expired document or a mismatch between the document and your profile data.' },
        { q: 'Is it safe to upload my documents?', a: 'Documents are uploaded over an encrypted connection inside your account and used only for verification. Never send them to anyone via messengers or e-mail.' },
      ],
    },
    pt: {
      title: 'Verificação de conta Pocket Option (KYC): documentos, passos, prazos e por que é recusada',
      metaTitle: 'Verificação Pocket Option (KYC) – Documentos, Passos, Prazos',
      metaDescription:
        'Guia de verificação de conta na Pocket Option: documentos aceitos, como enviar comprovantes de identidade, endereço e cartão, prazo de análise, motivos de recusa e regras de saque.',
      excerpt:
        'Tudo sobre o KYC da pocketoption: verificação de identidade, endereço e método de pagamento, envio no Perfil, prazo típico de análise e como evitar documento recusado.',
      coverAlt: 'Documento de identidade, cartão bancário e cadeado de segurança — verificação de conta Pocket Option',
      keyTakeaways: [
        'A verificação (KYC) na Pocket Option tem três partes: identidade (passaporte/RG/CNH), endereço (conta de consumo ou extrato bancário) e método de pagamento (foto do cartão).',
        'Você pode se cadastrar, usar a demo, depositar e operar antes da verificação, mas os saques geralmente ficam retidos até o KYC ser concluído.',
        'Os documentos são enviados em Perfil → Verificação; a análise costuma levar de algumas horas a 1–3 dias úteis.',
        'A maioria das recusas vem de fotos borradas, bordas cortadas, documentos vencidos ou nome/endereço diferente dos dados do cadastro.',
        'Verifique logo após o primeiro depósito — não na hora de sacar — para evitar atrasos.',
      ],
      blocks: [
        { type: 'p', text: 'Mais cedo ou mais tarde todo trader da Pocket Option encontra a tela de verificação — normalmente ao solicitar o primeiro saque. O KYC (Know Your Customer) é uma exigência padrão de prevenção à lavagem de dinheiro, e na pocketoption é simples se você sabe quais documentos são aceitos e como fotografá-los. Este guia cobre o processo completo, prazos e os erros que fazem documentos serem recusados.' },
        { type: 'h2', id: 'why', text: 'Por que a Pocket Option pede verificação' },
        { type: 'ul', items: [
          'Exigência regulatória (AML/KYC) — a plataforma precisa confirmar que o titular é uma pessoa real e maior de idade.',
          'Proteção contra fraude: impede saques para cartões roubados e bloqueia contas duplicadas.',
          'Segurança dos pagamentos: o método usado para depositar deve ser seu, para que os saques voltem à mesma pessoa.',
        ] },
        { type: 'p', text: 'Não é preciso verificar para se cadastrar, usar a demo de $50.000, depositar ou operar na conta real. Porém, o primeiro pedido de saque normalmente aciona a verificação, e o pagamento fica retido até a aprovação dos documentos. A plataforma também pode solicitar verificação a qualquer momento se detectar atividade incomum.' },
        { type: 'h2', id: 'documents', text: 'Quais documentos são aceitos' },
        { type: 'image', src: IMG_DOCS, alt: 'Documento de identidade, cartão bancário e cadeado — documentos para verificação na Pocket Option', caption: 'Três tipos de documento: identidade, endereço e método de pagamento.' },
        { type: 'table', head: ['Verificação', 'Documentos aceitos', 'Requisitos'], rows: [
          ['Identidade', 'Passaporte, RG/documento nacional, CNH', 'Válido (não vencido), documento inteiro visível, foto e data de nascimento legíveis'],
          ['Endereço', 'Conta de luz/água, extrato bancário, correspondência fiscal, conta de internet/telefone', 'Emitido nos últimos 3 meses, com seu nome e endereço completo'],
          ['Método de pagamento', 'Foto do cartão usado no depósito', 'Primeiros 6 e últimos 4 dígitos visíveis, dígitos do meio e CVV cobertos; carteira digital: captura da página da conta'],
        ] },
        { type: 'tip', title: 'Dados devem bater exatamente', text: 'Nome, data de nascimento e endereço no perfil da Pocket Option devem ser idênticos aos documentos. Preencha o perfil primeiro (Perfil → Dados pessoais) e depois envie — divergência é o motivo número um de recusa.' },
        { type: 'h2', id: 'steps', text: 'Como verificar sua conta Pocket Option passo a passo' },
        { type: 'image', src: IMG_PROFILE, alt: 'Avatar de perfil sendo escaneado — seção de dados pessoais na Pocket Option', caption: 'A verificação começa na seção Perfil da plataforma.' },
        { type: 'ol', items: [
          'Faça login e abra o Perfil (clique no avatar ou nome no canto superior direito).',
          'Preencha os Dados pessoais: nome completo como no documento, data de nascimento, país, cidade e endereço. Salve.',
          'Abra a aba Verificação. Confirme e-mail e telefone, se ainda não fez.',
          'Identidade: escolha o tipo de documento e envie foto ou digitalização nítida (JPG/PNG/PDF, quatro cantos visíveis, sem reflexo).',
          'Endereço: envie um documento emitido nos últimos 3 meses com seu nome e endereço.',
          'Método de pagamento: envie foto do cartão (cubra os 6 dígitos do meio e o CVV) ou captura da carteira digital.',
          'Envie. O status muda para “Em análise”. Você receberá e-mail quando cada documento for aprovado ou recusado.',
        ] },
        { type: 'h2', id: 'timing', text: 'Quanto tempo leva a verificação?' },
        { type: 'p', text: 'Pela nossa experiência, documentos de identidade costumam ser analisados em poucas horas em dias úteis; o conjunto completo geralmente leva até 1–3 dias úteis. Atrasos ocorrem quando a fila está grande (após grandes promoções ou torneios) ou quando um documento exige análise manual. Se o status não mudar em 3 dias úteis, contate o suporte pelo chat da plataforma informando o e-mail da conta.' },
        { type: 'h2', id: 'rejected', text: 'Por que documentos são recusados — e como corrigir' },
        { type: 'table', head: ['Motivo da recusa', 'Como corrigir'], rows: [
          ['Foto borrada ou escura, reflexo no documento', 'Fotografe com luz natural, sobre superfície plana e escura, sem flash; confira se todo o texto está legível'],
          ['Bordas cortadas', 'O documento inteiro, com os quatro cantos, deve estar no quadro'],
          ['Documento vencido', 'Use um documento válido; passaportes vencidos não são aceitos'],
          ['Nome ou endereço diferente do perfil', 'Edite os Dados pessoais para bater exatamente com o documento e reenvie'],
          ['Comprovante de endereço com mais de 3 meses', 'Baixe um extrato bancário recente ou a última conta de consumo'],
          ['Captura de tela ou fotocópia em vez do original', 'Fotografe o documento físico; para extratos digitais, envie o PDF original'],
          ['Dígitos do cartão totalmente visíveis ou totalmente ocultos', 'Mostre os primeiros 6 e últimos 4 dígitos, cubra o restante e o CVV'],
        ] },
        { type: 'warn', title: 'Nunca envie documentos fora da plataforma', text: 'Envie documentos apenas por Perfil → Verificação. O suporte da Pocket Option não pede documentos via Telegram, WhatsApp ou anexos de e-mail — quem fizer isso é golpista.' },
        { type: 'h2', id: 'withdrawal', text: 'Verificação e saques' },
        { type: 'image', src: IMG_WALLET, alt: 'Carteira com moedas — saques na Pocket Option após a verificação', caption: 'Depois de verificado, os saques são processados normalmente, em geral em até 24 horas.' },
        { type: 'p', text: 'Um pedido de saque feito antes da verificação não é cancelado — fica “Pendente” até a aprovação dos documentos e então segue o processamento (normalmente em até 24 horas). Se você depositou com vários cartões ou carteiras, cada método pode exigir seu próprio comprovante. A verificação é feita uma vez; não será pedida novamente, a menos que os documentos vençam ou seus dados pessoais mudem.' },
        { type: 'cta', text: 'Ainda não tem conta? Cadastre-se, verifique após o primeiro depósito e seus saques nunca vão esperar por documentos.', label: 'Cadastrar na Pocket Option' },
      ],
      faq: [
        { q: 'A verificação é obrigatória na Pocket Option?', a: 'Você pode operar sem ela, mas os saques geralmente ficam retidos até a verificação de identidade, endereço e método de pagamento ser concluída.' },
        { q: 'Quais documentos preciso para a verificação na Pocket Option?', a: 'Passaporte, RG ou CNH válidos; comprovante de endereço emitido em até 3 meses; e foto do cartão bancário ou carteira digital usada no depósito.' },
        { q: 'Quanto tempo leva a verificação na Pocket Option?', a: 'Normalmente de algumas horas a 1–3 dias úteis. Contate o suporte se não houver atualização após 3 dias úteis.' },
        { q: 'Posso sacar sem verificação?', a: 'Em geral não — o pedido de saque fica Pendente até a aprovação dos documentos e depois continua automaticamente.' },
        { q: 'Por que meu documento foi recusado?', a: 'Na maioria das vezes por foto borrada, bordas cortadas, documento vencido ou divergência entre o documento e os dados do perfil.' },
        { q: 'É seguro enviar meus documentos?', a: 'Os documentos são enviados por conexão criptografada dentro da conta e usados apenas para verificação. Nunca os envie a ninguém por mensageiros ou e-mail.' },
      ],
    },
    es: {
      title: 'Verificación de cuenta en Pocket Option (KYC): documentos, pasos, plazos y por qué se rechaza',
      metaTitle: 'Verificación Pocket Option (KYC) – Documentos, Pasos, Plazos',
      metaDescription:
        'Guía de verificación de cuenta en Pocket Option: documentos aceptados, cómo subir pruebas de identidad, domicilio y tarjeta, cuánto tarda la revisión, motivos de rechazo y retiros.',
      excerpt:
        'Todo sobre el KYC de pocketoption: verificación de identidad, domicilio y método de pago, el proceso de subida en Perfil, tiempo típico de revisión y cómo evitar un documento rechazado.',
      coverAlt: 'Documento de identidad, tarjeta bancaria y candado de seguridad — verificación de cuenta Pocket Option',
      keyTakeaways: [
        'La verificación (KYC) en Pocket Option tiene tres partes: identidad (pasaporte/DNI/licencia de conducir), domicilio (factura de servicios o extracto bancario) y método de pago (foto de la tarjeta).',
        'Puedes registrarte, usar la demo, depositar y operar antes de verificar, pero los retiros suelen quedar retenidos hasta completar el KYC.',
        'Los documentos se suben en Perfil → Verificación; la revisión suele tardar de unas horas a 1–3 días hábiles.',
        'La mayoría de rechazos se deben a fotos borrosas, bordes recortados, documentos caducados o un nombre/domicilio que no coincide con los datos del registro.',
        'Verifica justo después de tu primer depósito, no en el momento de retirar, para evitar demoras.',
      ],
      blocks: [
        { type: 'p', text: 'Tarde o temprano todo trader de Pocket Option se encuentra con la pantalla de verificación, normalmente al solicitar el primer retiro. El KYC (Know Your Customer) es un requisito estándar contra el blanqueo de capitales, y en pocketoption es sencillo si sabes qué documentos se aceptan y cómo fotografiarlos. Esta guía cubre el proceso completo, los plazos y los errores que hacen que se rechacen documentos.' },
        { type: 'h2', id: 'why', text: 'Por qué Pocket Option pide verificación' },
        { type: 'ul', items: [
          'Requisito regulatorio (AML/KYC): la plataforma debe confirmar que el titular es una persona real y mayor de edad.',
          'Protección contra el fraude: evita retiros a tarjetas robadas y frena las cuentas duplicadas.',
          'Seguridad de pagos: el método usado para depositar debe ser tuyo, para que los retiros vuelvan a la misma persona.',
        ] },
        { type: 'p', text: 'No necesitas verificar para registrarte, usar la demo de $50.000, depositar u operar en cuenta real. Sin embargo, la primera solicitud de retiro normalmente activa la verificación, y el pago queda retenido hasta que se aprueban los documentos. La plataforma también puede pedir verificación en cualquier momento si detecta actividad inusual.' },
        { type: 'h2', id: 'documents', text: 'Qué documentos se aceptan' },
        { type: 'image', src: IMG_DOCS, alt: 'Documento de identidad, tarjeta bancaria y candado — documentos para la verificación en Pocket Option', caption: 'Tres tipos de documento: identidad, domicilio y método de pago.' },
        { type: 'table', head: ['Verificación', 'Documentos aceptados', 'Requisitos'], rows: [
          ['Identidad', 'Pasaporte, DNI/cédula, licencia de conducir', 'Vigente (no caducado), documento completo visible, foto y fecha de nacimiento legibles'],
          ['Domicilio', 'Factura de servicios, extracto bancario, carta fiscal, factura de internet/teléfono', 'Emitido en los últimos 3 meses, con tu nombre y dirección completa'],
          ['Método de pago', 'Foto de la tarjeta usada para depositar', 'Primeros 6 y últimos 4 dígitos visibles, dígitos centrales y CVV cubiertos; monedero: captura de la página de la cuenta'],
        ] },
        { type: 'tip', title: 'Los datos deben coincidir exactamente', text: 'El nombre, la fecha de nacimiento y la dirección de tu perfil en Pocket Option deben ser idénticos a los documentos. Rellena primero el perfil (Perfil → Datos personales) y luego sube los archivos: la discrepancia es la causa número uno de rechazo.' },
        { type: 'h2', id: 'steps', text: 'Cómo verificar tu cuenta de Pocket Option paso a paso' },
        { type: 'image', src: IMG_PROFILE, alt: 'Avatar de perfil escaneado — sección de datos personales en Pocket Option', caption: 'La verificación empieza en la sección Perfil de la plataforma.' },
        { type: 'ol', items: [
          'Inicia sesión y abre Perfil (pulsa tu avatar o nombre en la esquina superior derecha).',
          'Rellena los Datos personales: nombre completo como en tu documento, fecha de nacimiento, país, ciudad y dirección. Guarda.',
          'Abre la pestaña Verificación. Confirma tu e-mail y teléfono si aún no lo hiciste.',
          'Identidad: elige el tipo de documento y sube una foto o escaneo nítido (JPG/PNG/PDF, las cuatro esquinas visibles, sin reflejos).',
          'Domicilio: sube un documento emitido en los últimos 3 meses con tu nombre y dirección.',
          'Método de pago: sube una foto de tu tarjeta (cubre los 6 dígitos centrales y el CVV) o una captura del monedero.',
          'Envía. El estado cambia a “En revisión”. Recibirás un e-mail cuando cada documento sea aprobado o rechazado.',
        ] },
        { type: 'h2', id: 'timing', text: '¿Cuánto tarda la verificación?' },
        { type: 'p', text: 'Según nuestra experiencia, los documentos de identidad suelen revisarse en unas horas en días hábiles; el conjunto completo tarda normalmente hasta 1–3 días hábiles. Hay demoras cuando la cola es larga (tras grandes promociones o torneos) o cuando un documento requiere revisión manual. Si el estado no cambia en 3 días hábiles, contacta con soporte por el chat de la plataforma indicando el e-mail de tu cuenta.' },
        { type: 'h2', id: 'rejected', text: 'Por qué se rechazan documentos y cómo solucionarlo' },
        { type: 'table', head: ['Motivo de rechazo', 'Cómo solucionarlo'], rows: [
          ['Foto borrosa u oscura, reflejos en el documento', 'Fotografía con luz natural, sobre una superficie plana y oscura, sin flash; comprueba que todo el texto se lea'],
          ['Bordes recortados', 'Todo el documento, con sus cuatro esquinas, debe estar en el encuadre'],
          ['Documento caducado', 'Usa un documento vigente; los pasaportes caducados no se aceptan'],
          ['Nombre o dirección no coincide con el perfil', 'Edita los Datos personales para que coincidan exactamente con el documento y vuelve a subirlo'],
          ['Prueba de domicilio de más de 3 meses', 'Descarga un extracto bancario reciente o la última factura de servicios'],
          ['Captura de pantalla o fotocopia en lugar del original', 'Fotografía el documento físico; para extractos digitales sube el PDF original'],
          ['Dígitos de la tarjeta totalmente visibles o totalmente ocultos', 'Muestra los primeros 6 y últimos 4 dígitos, cubre el resto y el CVV'],
        ] },
        { type: 'warn', title: 'Nunca envíes documentos fuera de la plataforma', text: 'Sube los documentos solo a través de Perfil → Verificación. El soporte de Pocket Option no pide documentos por Telegram, WhatsApp ni adjuntos de e-mail; quien lo haga es un estafador.' },
        { type: 'h2', id: 'withdrawal', text: 'Verificación y retiros' },
        { type: 'image', src: IMG_WALLET, alt: 'Cartera con monedas — retiros en Pocket Option tras la verificación', caption: 'Una vez verificado, los retiros se procesan con normalidad, normalmente en 24 horas.' },
        { type: 'p', text: 'Una solicitud de retiro hecha antes de verificar no se cancela: queda “Pendiente” hasta que se aprueban los documentos y luego continúa el procesamiento (normalmente en 24 horas). Si depositaste con varias tarjetas o monederos, cada método puede necesitar su propia prueba. La verificación se hace una sola vez; no te la pedirán de nuevo salvo que caduquen tus documentos o cambien tus datos personales.' },
        { type: 'cta', text: '¿Aún no estás registrado? Crea una cuenta, verifícala tras tu primer depósito y tus retiros nunca esperarán por documentos.', label: 'Registrarse en Pocket Option' },
      ],
      faq: [
        { q: '¿La verificación es obligatoria en Pocket Option?', a: 'Puedes operar sin ella, pero los retiros suelen quedar retenidos hasta completar la verificación de identidad, domicilio y método de pago.' },
        { q: '¿Qué documentos necesito para la verificación en Pocket Option?', a: 'Un pasaporte, DNI o licencia de conducir vigente; una prueba de domicilio emitida en los últimos 3 meses; y una foto de la tarjeta o monedero usado para depositar.' },
        { q: '¿Cuánto tarda la verificación en Pocket Option?', a: 'Normalmente de unas horas a 1–3 días hábiles. Contacta con soporte si no hay novedades tras 3 días hábiles.' },
        { q: '¿Puedo retirar sin verificación?', a: 'En general no: la solicitud de retiro espera en Pendiente hasta que se aprueban los documentos y después continúa automáticamente.' },
        { q: '¿Por qué rechazaron mi documento?', a: 'Casi siempre por una foto borrosa, bordes recortados, un documento caducado o una discrepancia entre el documento y los datos de tu perfil.' },
        { q: '¿Es seguro subir mis documentos?', a: 'Los documentos se suben por una conexión cifrada dentro de tu cuenta y se usan solo para la verificación. Nunca los envíes a nadie por mensajería o e-mail.' },
      ],
    },
    ru: {
      title: 'Верификация аккаунта Pocket Option (KYC): документы, шаги, сроки и причины отказа',
      metaTitle: 'Верификация Pocket Option (KYC) – Документы, Шаги, Сроки',
      metaDescription:
        'Гид по верификации аккаунта Pocket Option: какие документы принимаются, как загрузить подтверждение личности, адреса и карты, сколько идёт проверка, причины отказа и вывод.',
      excerpt:
        'Всё о KYC на pocketoption: верификация личности, адреса и платёжного метода, загрузка в Профиле, типичные сроки проверки и как избежать отклонённого документа.',
      coverAlt: 'Документ, банковская карта и замок безопасности — верификация аккаунта Pocket Option',
      keyTakeaways: [
        'Верификация (KYC) на Pocket Option состоит из трёх частей: личность (паспорт/ID/водительское удостоверение), адрес (коммунальный счёт или банковская выписка) и платёжный метод (фото карты).',
        'Регистрироваться, пользоваться демо, пополнять счёт и торговать можно до верификации, но вывод средств, как правило, удерживается до завершения KYC.',
        'Документы загружаются в Профиль → Верификация; проверка обычно занимает от нескольких часов до 1–3 рабочих дней.',
        'Большинство отказов вызваны размытыми фото, обрезанными краями, просроченными документами или несовпадением имени/адреса с данными регистрации.',
        'Проходите верификацию сразу после первого депозита, а не в момент вывода, чтобы избежать задержек.',
      ],
      blocks: [
        { type: 'p', text: 'Рано или поздно каждый трейдер Pocket Option сталкивается с экраном верификации — обычно при первом запросе на вывод. KYC (Know Your Customer) — стандартное требование по противодействию отмыванию денег, и на pocketoption процедура проста, если знать, какие документы принимаются и как их фотографировать. В этом гиде — весь процесс, сроки и ошибки, из-за которых документы отклоняют.' },
        { type: 'h2', id: 'why', text: 'Зачем Pocket Option требует верификацию' },
        { type: 'ul', items: [
          'Регуляторное требование (AML/KYC) — платформа должна подтвердить, что владелец счёта — реальный совершеннолетний человек.',
          'Защита от мошенничества: предотвращает вывод на украденные карты и блокирует дубликаты аккаунтов.',
          'Безопасность платежей: метод, которым пополняли счёт, должен принадлежать вам, чтобы вывод возвращался тому же человеку.',
        ] },
        { type: 'p', text: 'Для регистрации, демо на $50 000, пополнения и торговли на реальном счёте верификация не нужна. Однако первый запрос на вывод обычно запускает проверку, и выплата удерживается до одобрения документов. Платформа также может запросить верификацию в любой момент при обнаружении необычной активности.' },
        { type: 'h2', id: 'documents', text: 'Какие документы принимаются' },
        { type: 'image', src: IMG_DOCS, alt: 'ID-карта, банковская карта и замок — документы для верификации Pocket Option', caption: 'Три типа документов: личность, адрес и платёжный метод.' },
        { type: 'table', head: ['Верификация', 'Принимаемые документы', 'Требования'], rows: [
          ['Личность', 'Паспорт, национальная ID-карта, водительское удостоверение', 'Действующий (не просроченный), документ виден полностью, фото и дата рождения читаемы'],
          ['Адрес', 'Коммунальный счёт, банковская выписка, налоговое письмо, счёт за интернет/телефон', 'Выдан за последние 3 месяца, с вашим именем и полным адресом'],
          ['Платёжный метод', 'Фото банковской карты, использованной для депозита', 'Видны первые 6 и последние 4 цифры, средние цифры и CVV закрыты; кошелёк: скриншот страницы аккаунта'],
        ] },
        { type: 'tip', title: 'Данные должны совпадать точно', text: 'Имя, дата рождения и адрес в профиле Pocket Option должны быть идентичны документам. Сначала заполните профиль (Профиль → Личные данные), затем загружайте — несовпадение является причиной отказа номер один.' },
        { type: 'h2', id: 'steps', text: 'Как пройти верификацию Pocket Option по шагам' },
        { type: 'image', src: IMG_PROFILE, alt: 'Сканирование аватара профиля — раздел личных данных на Pocket Option', caption: 'Верификация начинается в разделе «Профиль» платформы.' },
        { type: 'ol', items: [
          'Войдите в аккаунт и откройте Профиль (нажмите на аватар или имя в правом верхнем углу).',
          'Заполните Личные данные: полное имя как в документе, дата рождения, страна, город и адрес. Сохраните.',
          'Откройте вкладку Верификация. Подтвердите e-mail и номер телефона, если ещё не сделали.',
          'Личность: выберите тип документа и загрузите чёткое фото или скан (JPG/PNG/PDF, видны все четыре угла, без бликов).',
          'Адрес: загрузите документ, выданный за последние 3 месяца, с вашим именем и адресом.',
          'Платёжный метод: загрузите фото карты (закройте средние 6 цифр и CVV) или скриншот кошелька.',
          'Отправьте. Статус изменится на «На проверке». Вы получите e-mail, когда каждый документ будет одобрен или отклонён.',
        ] },
        { type: 'h2', id: 'timing', text: 'Сколько длится верификация?' },
        { type: 'p', text: 'По нашему опыту документы, подтверждающие личность, обычно проверяют за несколько часов в рабочие дни; полный комплект — как правило, до 1–3 рабочих дней. Задержки бывают при большой очереди (после крупных акций или турниров) или когда документ требует ручной проверки. Если статус не изменился через 3 рабочих дня, обратитесь в поддержку через чат в платформе, указав e-mail аккаунта.' },
        { type: 'h2', id: 'rejected', text: 'Почему документы отклоняют — и как это исправить' },
        { type: 'table', head: ['Причина отказа', 'Как исправить'], rows: [
          ['Размытое или тёмное фото, блики на документе', 'Снимайте при дневном свете, на ровной тёмной поверхности, без вспышки; проверьте читаемость всего текста'],
          ['Обрезаны края', 'В кадре должен быть весь документ, включая все четыре угла'],
          ['Просроченный документ', 'Используйте действующий документ; просроченные паспорта не принимаются'],
          ['Имя или адрес не совпадают с профилем', 'Отредактируйте Личные данные так, чтобы они точно совпадали с документом, и загрузите повторно'],
          ['Подтверждение адреса старше 3 месяцев', 'Скачайте свежую банковскую выписку или последний коммунальный счёт'],
          ['Скриншот или ксерокопия вместо оригинала', 'Сфотографируйте физический документ; для электронных выписок загрузите оригинальный PDF'],
          ['Цифры карты полностью видны или полностью скрыты', 'Покажите первые 6 и последние 4 цифры, закройте остальные и CVV'],
        ] },
        { type: 'warn', title: 'Никогда не отправляйте документы вне платформы', text: 'Загружайте документы только через Профиль → Верификация. Поддержка Pocket Option не запрашивает документы через Telegram, WhatsApp или вложения в e-mail — тот, кто это делает, мошенник.' },
        { type: 'h2', id: 'withdrawal', text: 'Верификация и вывод средств' },
        { type: 'image', src: IMG_WALLET, alt: 'Кошелёк с монетами — вывод средств с Pocket Option после верификации', caption: 'После верификации выводы обрабатываются в обычном режиме, как правило, в течение 24 часов.' },
        { type: 'p', text: 'Заявка на вывод, поданная до верификации, не отменяется — она остаётся в статусе «В ожидании» до одобрения документов, после чего обработка продолжается (обычно в течение 24 часов). Если вы пополняли счёт с нескольких карт или кошельков, для каждого платёжного метода может понадобиться отдельное подтверждение. Верификация проходится один раз; повторно её не запросят, если только документы не истекут или не изменятся ваши личные данные.' },
        { type: 'cta', text: 'Ещё не зарегистрированы? Создайте аккаунт, пройдите верификацию после первого депозита — и ваши выводы никогда не будут ждать документов.', label: 'Регистрация на Pocket Option' },
      ],
      faq: [
        { q: 'Обязательна ли верификация на Pocket Option?', a: 'Торговать можно и без неё, но вывод средств, как правило, удерживается до завершения верификации личности, адреса и платёжного метода.' },
        { q: 'Какие документы нужны для верификации Pocket Option?', a: 'Действующий паспорт, ID-карта или водительское удостоверение; подтверждение адреса не старше 3 месяцев; фото банковской карты или кошелька, использованного для депозита.' },
        { q: 'Сколько занимает верификация на Pocket Option?', a: 'Обычно от нескольких часов до 1–3 рабочих дней. Если через 3 рабочих дня ничего не изменилось, обратитесь в поддержку.' },
        { q: 'Можно ли вывести деньги без верификации?', a: 'Как правило, нет — заявка на вывод ждёт в статусе «В ожидании» до одобрения документов, затем продолжается автоматически.' },
        { q: 'Почему мой документ отклонили?', a: 'Чаще всего из-за размытого фото, обрезанных краёв, просроченного документа или несовпадения документа с данными профиля.' },
        { q: 'Безопасно ли загружать документы?', a: 'Документы загружаются по зашифрованному соединению внутри аккаунта и используются только для верификации. Никогда не отправляйте их никому через мессенджеры или e-mail.' },
      ],
    },
    id: {
      title: 'Verifikasi akun Pocket Option (KYC): dokumen, langkah, waktu, dan alasan ditolak',
      metaTitle: 'Verifikasi Pocket Option (KYC) – Dokumen, Langkah, Waktu',
      metaDescription:
        'Panduan verifikasi akun Pocket Option: dokumen yang diterima, cara mengunggah bukti identitas, alamat, dan kartu, lama peninjauan, alasan penolakan, dan aturan penarikan.',
      excerpt:
        'Semua tentang KYC pocketoption: verifikasi identitas, alamat, dan metode pembayaran, proses unggah di Profil, waktu peninjauan umum, dan cara menghindari dokumen ditolak.',
      coverAlt: 'Dokumen identitas, kartu bank, dan gembok keamanan — verifikasi akun Pocket Option',
      keyTakeaways: [
        'Verifikasi (KYC) di Pocket Option terdiri dari tiga bagian: identitas (paspor/KTP/SIM), alamat (tagihan utilitas atau rekening koran), dan metode pembayaran (foto kartu).',
        'Anda bisa mendaftar, memakai demo, deposit, dan trading sebelum verifikasi, tetapi penarikan biasanya ditahan sampai KYC selesai.',
        'Dokumen diunggah di Profil → Verifikasi; peninjauan biasanya memakan waktu beberapa jam hingga 1–3 hari kerja.',
        'Sebagian besar penolakan disebabkan foto buram, tepi terpotong, dokumen kedaluwarsa, atau nama/alamat yang tidak sesuai data registrasi.',
        'Verifikasi segera setelah deposit pertama — bukan saat ingin menarik — untuk menghindari penundaan.',
      ],
      blocks: [
        { type: 'p', text: 'Cepat atau lambat setiap trader Pocket Option akan bertemu layar verifikasi — biasanya saat mengajukan penarikan pertama. KYC (Know Your Customer) adalah persyaratan standar anti pencucian uang, dan di pocketoption prosesnya mudah jika Anda tahu dokumen apa yang diterima dan cara memotretnya. Panduan ini mencakup proses lengkap, waktu, dan kesalahan yang membuat dokumen ditolak.' },
        { type: 'h2', id: 'why', text: 'Mengapa Pocket Option meminta verifikasi' },
        { type: 'ul', items: [
          'Persyaratan regulasi (AML/KYC) — platform harus memastikan pemilik akun adalah orang dewasa yang nyata.',
          'Perlindungan dari penipuan: mencegah penarikan ke kartu curian dan menghentikan akun ganda.',
          'Keamanan pembayaran: metode yang dipakai untuk deposit harus milik Anda, agar penarikan kembali ke orang yang sama.',
        ] },
        { type: 'p', text: 'Anda tidak perlu verifikasi untuk mendaftar, memakai demo $50.000, deposit, atau trading di akun riil. Namun, permintaan penarikan pertama biasanya memicu pemeriksaan verifikasi, dan pembayaran ditahan sampai dokumen disetujui. Platform juga dapat meminta verifikasi kapan saja jika mendeteksi aktivitas tidak biasa.' },
        { type: 'h2', id: 'documents', text: 'Dokumen yang diterima' },
        { type: 'image', src: IMG_DOCS, alt: 'Kartu identitas, kartu bank, dan gembok — dokumen untuk verifikasi Pocket Option', caption: 'Tiga jenis dokumen: identitas, alamat, dan metode pembayaran.' },
        { type: 'table', head: ['Verifikasi', 'Dokumen yang diterima', 'Persyaratan'], rows: [
          ['Identitas', 'Paspor, KTP, SIM', 'Masih berlaku, seluruh dokumen terlihat, foto dan tanggal lahir terbaca'],
          ['Alamat', 'Tagihan listrik/air, rekening koran, surat pajak, tagihan internet/telepon', 'Diterbitkan dalam 3 bulan terakhir, menampilkan nama dan alamat lengkap Anda'],
          ['Metode pembayaran', 'Foto kartu bank yang dipakai untuk deposit', '6 digit pertama dan 4 digit terakhir terlihat, digit tengah dan CVV ditutup; e-wallet: tangkapan layar halaman akun'],
        ] },
        { type: 'tip', title: 'Data harus sama persis', text: 'Nama, tanggal lahir, dan alamat di profil Pocket Option harus identik dengan dokumen. Isi profil dulu (Profil → Data pribadi), lalu unggah — ketidaksesuaian adalah alasan penolakan nomor satu.' },
        { type: 'h2', id: 'steps', text: 'Cara verifikasi akun Pocket Option langkah demi langkah' },
        { type: 'image', src: IMG_PROFILE, alt: 'Avatar profil yang dipindai — bagian data pribadi di Pocket Option', caption: 'Verifikasi dimulai dari bagian Profil di platform.' },
        { type: 'ol', items: [
          'Login dan buka Profil (klik avatar atau nama Anda di pojok kanan atas).',
          'Isi Data pribadi: nama lengkap sesuai identitas, tanggal lahir, negara, kota, dan alamat. Simpan.',
          'Buka tab Verifikasi. Konfirmasi e-mail dan nomor telepon jika belum.',
          'Identitas: pilih jenis dokumen dan unggah foto atau scan yang jelas (JPG/PNG/PDF, keempat sudut terlihat, tanpa silau).',
          'Alamat: unggah dokumen yang diterbitkan dalam 3 bulan terakhir dengan nama dan alamat Anda.',
          'Metode pembayaran: unggah foto kartu (tutup 6 digit tengah dan CVV) atau tangkapan layar e-wallet.',
          'Kirim. Status berubah menjadi “Dalam peninjauan”. Anda akan menerima e-mail saat tiap dokumen disetujui atau ditolak.',
        ] },
        { type: 'h2', id: 'timing', text: 'Berapa lama verifikasi?' },
        { type: 'p', text: 'Dari pengalaman kami, dokumen identitas biasanya diperiksa dalam beberapa jam pada hari kerja; set lengkap biasanya hingga 1–3 hari kerja. Penundaan terjadi saat antrean panjang (setelah promosi besar atau turnamen) atau saat dokumen memerlukan peninjauan manual. Jika status belum berubah setelah 3 hari kerja, hubungi dukungan lewat chat di platform dengan e-mail akun Anda.' },
        { type: 'h2', id: 'rejected', text: 'Mengapa dokumen ditolak — dan cara memperbaikinya' },
        { type: 'table', head: ['Alasan penolakan', 'Cara memperbaiki'], rows: [
          ['Foto buram atau gelap, silau pada dokumen', 'Foto dengan cahaya siang, di permukaan datar berwarna gelap, tanpa flash; pastikan semua teks terbaca'],
          ['Tepi terpotong', 'Seluruh dokumen, termasuk keempat sudut, harus masuk dalam bingkai'],
          ['Dokumen kedaluwarsa', 'Gunakan identitas yang masih berlaku; paspor kedaluwarsa tidak diterima'],
          ['Nama atau alamat tidak sesuai profil', 'Ubah Data pribadi agar sama persis dengan dokumen, lalu unggah ulang'],
          ['Bukti alamat lebih dari 3 bulan', 'Unduh rekening koran terbaru atau tagihan utilitas terakhir'],
          ['Tangkapan layar atau fotokopi, bukan asli', 'Foto dokumen fisik; untuk rekening digital unggah PDF asli'],
          ['Digit kartu terlihat semua atau tertutup semua', 'Tampilkan 6 digit pertama dan 4 digit terakhir, tutup sisanya dan CVV'],
        ] },
        { type: 'warn', title: 'Jangan pernah mengirim dokumen di luar platform', text: 'Unggah dokumen hanya lewat Profil → Verifikasi. Dukungan Pocket Option tidak meminta dokumen via Telegram, WhatsApp, atau lampiran e-mail — siapa pun yang melakukannya adalah penipu.' },
        { type: 'h2', id: 'withdrawal', text: 'Verifikasi dan penarikan' },
        { type: 'image', src: IMG_WALLET, alt: 'Dompet dengan koin — penarikan di Pocket Option setelah verifikasi', caption: 'Setelah terverifikasi, penarikan diproses normal, biasanya dalam 24 jam.' },
        { type: 'p', text: 'Permintaan penarikan yang dibuat sebelum verifikasi tidak dibatalkan — tetap “Pending” sampai dokumen disetujui, lalu pemrosesan berlanjut (biasanya dalam 24 jam). Jika Anda deposit dengan beberapa kartu atau wallet, tiap metode pembayaran mungkin memerlukan buktinya sendiri. Verifikasi dilakukan sekali; Anda tidak akan diminta mengulang kecuali dokumen kedaluwarsa atau data pribadi berubah.' },
        { type: 'cta', text: 'Belum terdaftar? Buat akun, verifikasi setelah deposit pertama, dan penarikan Anda tidak akan pernah menunggu dokumen.', label: 'Daftar di Pocket Option' },
      ],
      faq: [
        { q: 'Apakah verifikasi wajib di Pocket Option?', a: 'Anda bisa trading tanpanya, tetapi penarikan biasanya ditahan sampai verifikasi identitas, alamat, dan metode pembayaran selesai.' },
        { q: 'Dokumen apa yang dibutuhkan untuk verifikasi Pocket Option?', a: 'Paspor, KTP, atau SIM yang masih berlaku; bukti alamat yang diterbitkan dalam 3 bulan; dan foto kartu bank atau e-wallet yang dipakai untuk deposit.' },
        { q: 'Berapa lama verifikasi Pocket Option?', a: 'Biasanya beberapa jam hingga 1–3 hari kerja. Hubungi dukungan jika tidak ada pembaruan setelah 3 hari kerja.' },
        { q: 'Bisakah menarik dana tanpa verifikasi?', a: 'Umumnya tidak — permintaan penarikan menunggu di Pending sampai dokumen disetujui, lalu berlanjut otomatis.' },
        { q: 'Mengapa dokumen saya ditolak?', a: 'Paling sering karena foto buram, tepi terpotong, dokumen kedaluwarsa, atau ketidaksesuaian antara dokumen dan data profil Anda.' },
        { q: 'Apakah aman mengunggah dokumen saya?', a: 'Dokumen diunggah lewat koneksi terenkripsi di dalam akun dan hanya dipakai untuk verifikasi. Jangan pernah mengirimnya ke siapa pun via aplikasi pesan atau e-mail.' },
      ],
    },
  },
};
