import type { BlogPost } from '../types';

const IMG_VERIFY = '/images/quick-start/2_2.webp';
const IMG_WITHDRAW = '/images/quick-start/6_2.webp';

export const pocketOptionWithdrawal: BlogPost = {
  slug: 'pocket-option-withdrawal',
  category: 'payments',
  cover: '/images/blog/pocket-option-withdrawal-guide.webp',
  publishedAt: '2026-09-23',
  updatedAt: '2026-09-26',
  readingMinutes: 8,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option withdrawal: how to withdraw money, processing time, limits and fees',
      metaTitle: 'Pocket Option withdrawal guide: how to withdraw money, time, limits and fees',
      metaDescription:
        'How to withdraw money from Pocket Option step by step: verification, choosing a payment method, minimum $10, processing time around 24 hours, zero platform fees and how to fix a pending or rejected withdrawal.',
      excerpt:
        'A complete pocketoption withdrawal walkthrough: what to verify before the first request, which methods are fastest, how long it takes and why some withdrawals get delayed.',
      coverAlt: 'Gold coins in front of a trading chart — withdrawing profit from Pocket Option',
      keyTakeaways: [
        'Withdrawals go to the same method you deposited with; the minimum is $10 for most methods.',
        'Pocket Option does not charge a withdrawal fee — your bank or crypto network may.',
        'Typical processing is around 24 hours; verified accounts and crypto wallets are usually fastest.',
        'Complete KYC (ID + address) before the first withdrawal to avoid a “pending” request.',
      ],
      blocks: [
        { type: 'p', text: 'Withdrawing money from Pocket Option is a four-step process: verify the account, open the Finance section, choose the payout method and confirm the amount. Most requests are processed within a day. This guide explains each step of a pocketoption withdrawal, the limits and fees you should expect, and the reasons a request can end up pending or rejected.' },
        { type: 'h2', id: 'before', text: 'Before you withdraw: verification and the deposit rule' },
        { type: 'image', src: IMG_VERIFY, alt: 'Pocket Option profile verification — identity and address documents', caption: 'Verification (KYC) is required once, before the first withdrawal.' },
        { type: 'p', text: 'Two rules govern every Pocket Option withdrawal. First, the account must be verified: upload a photo of your ID (passport, national ID or driving licence) and a proof of address (utility bill or bank statement no older than three months) in Profile → Verification. Second, funds are returned to the same payment method used for the deposit — a card deposit is withdrawn to the same card, a USDT deposit to a USDT wallet. Profit above the deposited amount can usually be sent to any supported method, including crypto.' },
        { type: 'tip', title: 'Verify on day one', text: 'Verification takes from a few minutes to a couple of days. Doing it right after registration means your first withdrawal is not held up while documents are reviewed.' },
        { type: 'h2', id: 'steps', text: 'How to withdraw from Pocket Option step by step' },
        { type: 'ol', items: [
          'Log in to your pocketoption account and open Finance → Withdrawal in the left menu.',
          'Select the payment method. Only methods you have deposited with (plus crypto for profit) are shown.',
          'Enter the amount — at least $10 for most methods — and the wallet address, card or account details.',
          'Confirm the request. It appears in Finance → Transaction history with the status “Requested”.',
          'Wait for processing. The status changes to “Approved” and the money arrives according to the method’s own transfer time.',
        ] },
        { type: 'image', src: IMG_WITHDRAW, alt: 'Pocket Option withdrawal request confirmed in the Finance section', caption: 'Track every request in Finance → Transaction history.' },
        { type: 'h2', id: 'methods', text: 'Withdrawal methods and how long they take' },
        { type: 'p', text: 'Pocket Option supports 50+ payment methods; availability depends on your country. The platform side is usually finished within 24 hours; the rest of the time is the transfer itself.' },
        { type: 'table', head: ['Method', 'Typical arrival after approval', 'Notes'], rows: [
          ['Cryptocurrency (USDT, BTC, ETH, LTC…)', 'Minutes to a few hours', 'Fastest option; network fee applies'],
          ['E-wallets (Skrill, Neteller, Perfect Money, AdvCash)', 'Same day', 'Wallet must be in your name'],
          ['Local methods (Pix, UPI, M-Pesa, bKash, Mercado Pago…)', 'Same day – 1 business day', 'Depends on the local provider'],
          ['Visa / Mastercard', '1–5 business days', 'Bank processing time varies by issuer'],
          ['Bank transfer', '2–7 business days', 'Available in selected countries'],
        ] },
        { type: 'h2', id: 'limits', text: 'Minimum, maximum and fees' },
        { type: 'ul', items: [
          'Minimum withdrawal: $10 (some methods have their own, higher minimum).',
          'Maximum per request: depends on the method and account level; large amounts can be split into several requests.',
          'Platform fee: none — Pocket Option does not charge for deposits or withdrawals.',
          'Third-party fees: crypto network fees, bank or e-wallet charges and currency conversion may apply.',
          'Bonus funds: if you accepted a deposit bonus, the required trading turnover must be met before withdrawing the bonus part.',
        ] },
        { type: 'h2', id: 'pending', text: 'Why a withdrawal is pending or rejected' },
        { type: 'p', text: 'Most delays have a simple cause. Check these before contacting support:' },
        { type: 'ul', items: [
          'Verification not complete or documents rejected (blurry photo, cropped edges, expired ID).',
          'Withdrawal method differs from the deposit method — return the deposited sum first, then withdraw profit.',
          'Wallet address or card number entered incorrectly — cancel the request while it is still “Requested” and create a new one.',
          'Unfinished bonus turnover.',
          'Weekend or public holiday — the platform processes requests, but banks do not transfer funds.',
        ] },
        { type: 'p', text: 'If the status is still “Requested” after 24 hours and none of the above applies, open the support chat inside the platform and quote the transaction ID from the history.' },
        { type: 'warn', title: 'Security note', text: 'Pocket Option never asks for card PINs, wallet seed phrases or a “release fee” to process a withdrawal. Requests of this kind are scams — use only the support chat inside your account.' },
        { type: 'cta', text: 'New to the platform? Open an account, complete verification and test the whole cycle with a small $5 deposit before trading bigger sums.', label: 'Open Pocket Option account' },
      ],
      faq: [
        { q: 'How long does a Pocket Option withdrawal take?', a: 'The platform typically processes a request within 24 hours. After approval, crypto and e-wallets arrive within hours, cards within 1–5 business days and bank transfers within 2–7 business days.' },
        { q: 'What is the minimum withdrawal on Pocket Option?', a: 'The minimum withdrawal is $10 for most payment methods. Some methods set a higher minimum of their own.' },
        { q: 'Does Pocket Option charge withdrawal fees?', a: 'No, the platform does not charge for deposits or withdrawals. Bank, e-wallet or blockchain network fees may still apply on the receiving side.' },
        { q: 'Can I withdraw to a different method than I deposited with?', a: 'The deposited amount is returned to the original method. Profit above that amount can usually be withdrawn to another supported method, including cryptocurrency wallets.' },
        { q: 'Why is my Pocket Option withdrawal pending?', a: 'Common reasons are incomplete verification, a method mismatch, incorrect payment details, unfinished bonus turnover or bank holidays. Check these first, then contact support with the transaction ID.' },
        { q: 'Can I withdraw money from the demo account?', a: 'No. Demo funds are virtual and cannot be withdrawn. Only real-account balance can be withdrawn.' },
      ],
    },

    pt: {
      title: 'Saque na Pocket Option: como retirar dinheiro, prazo, limites e taxas',
      metaTitle: 'Guia de saque na Pocket Option: como retirar dinheiro, prazo, limites e taxas',
      metaDescription:
        'Como sacar da Pocket Option passo a passo: verificação, escolha do método de pagamento, mínimo de $10, processamento em cerca de 24 horas, sem taxas da plataforma e como resolver um saque pendente ou rejeitado.',
      excerpt:
        'Passo a passo completo do saque na pocketoption: o que verificar antes do primeiro pedido, quais métodos são mais rápidos, quanto tempo leva e por que alguns saques atrasam.',
      coverAlt: 'Moedas de ouro em frente a um gráfico de trading — sacando lucro da Pocket Option',
      keyTakeaways: [
        'Os saques vão para o mesmo método usado no depósito; o mínimo é $10 na maioria dos métodos.',
        'A Pocket Option não cobra taxa de saque — seu banco ou rede cripto pode cobrar.',
        'O processamento típico é de cerca de 24 horas; contas verificadas e carteiras cripto costumam ser as mais rápidas.',
        'Conclua o KYC (documento + endereço) antes do primeiro saque para evitar um pedido “pendente”.',
      ],
      blocks: [
        { type: 'p', text: 'Sacar dinheiro da Pocket Option é um processo de quatro passos: verificar a conta, abrir a seção Finanças, escolher o método de pagamento e confirmar o valor. A maioria dos pedidos é processada em um dia. Este guia explica cada etapa do saque na pocketoption, os limites e taxas esperados e os motivos pelos quais um pedido pode ficar pendente ou ser rejeitado.' },
        { type: 'h2', id: 'before', text: 'Antes de sacar: verificação e a regra do depósito' },
        { type: 'image', src: IMG_VERIFY, alt: 'Verificação de perfil na Pocket Option — documentos de identidade e endereço', caption: 'A verificação (KYC) é exigida uma vez, antes do primeiro saque.' },
        { type: 'p', text: 'Duas regras valem para todo saque na Pocket Option. Primeiro, a conta deve estar verificada: envie a foto do documento (passaporte, RG ou CNH) e um comprovante de endereço (conta de consumo ou extrato bancário com até três meses) em Perfil → Verificação. Segundo, os fundos voltam para o mesmo método usado no depósito — depósito por cartão é sacado para o mesmo cartão, depósito em USDT para uma carteira USDT. O lucro acima do valor depositado normalmente pode ser enviado a qualquer método suportado, inclusive cripto.' },
        { type: 'tip', title: 'Verifique no primeiro dia', text: 'A verificação leva de alguns minutos a dois dias. Fazê-la logo após o cadastro evita que o primeiro saque fique parado enquanto os documentos são analisados.' },
        { type: 'h2', id: 'steps', text: 'Como sacar da Pocket Option passo a passo' },
        { type: 'ol', items: [
          'Entre na sua conta pocketoption e abra Finanças → Saque no menu esquerdo.',
          'Selecione o método de pagamento. Só aparecem os métodos com os quais você depositou (mais cripto para o lucro).',
          'Insira o valor — no mínimo $10 na maioria dos métodos — e os dados da carteira, cartão ou conta.',
          'Confirme o pedido. Ele aparece em Finanças → Histórico de transações com o status “Solicitado”.',
          'Aguarde o processamento. O status muda para “Aprovado” e o dinheiro chega conforme o prazo do próprio método.',
        ] },
        { type: 'image', src: IMG_WITHDRAW, alt: 'Pedido de saque confirmado na seção Finanças da Pocket Option', caption: 'Acompanhe cada pedido em Finanças → Histórico de transações.' },
        { type: 'h2', id: 'methods', text: 'Métodos de saque e prazos' },
        { type: 'p', text: 'A Pocket Option aceita mais de 50 métodos de pagamento; a disponibilidade depende do seu país. O lado da plataforma normalmente conclui em até 24 horas; o restante é o tempo da transferência em si.' },
        { type: 'table', head: ['Método', 'Chegada típica após aprovação', 'Observações'], rows: [
          ['Criptomoedas (USDT, BTC, ETH, LTC…)', 'Minutos a algumas horas', 'Opção mais rápida; taxa de rede se aplica'],
          ['Carteiras eletrônicas (Skrill, Neteller, Perfect Money, AdvCash)', 'Mesmo dia', 'A carteira deve estar em seu nome'],
          ['Métodos locais (Pix, UPI, M-Pesa, bKash, Mercado Pago…)', 'Mesmo dia – 1 dia útil', 'Depende do provedor local'],
          ['Visa / Mastercard', '1–5 dias úteis', 'O prazo do banco varia por emissor'],
          ['Transferência bancária', '2–7 dias úteis', 'Disponível em países selecionados'],
        ] },
        { type: 'h2', id: 'limits', text: 'Mínimo, máximo e taxas' },
        { type: 'ul', items: [
          'Saque mínimo: $10 (alguns métodos têm mínimo próprio, mais alto).',
          'Máximo por pedido: depende do método e do nível da conta; valores grandes podem ser divididos em vários pedidos.',
          'Taxa da plataforma: nenhuma — a Pocket Option não cobra por depósitos ou saques.',
          'Taxas de terceiros: taxas de rede cripto, cobranças de banco ou carteira e conversão de moeda podem se aplicar.',
          'Fundos de bônus: se aceitou um bônus de depósito, o volume de negociação exigido deve ser cumprido antes de sacar a parte do bônus.',
        ] },
        { type: 'h2', id: 'pending', text: 'Por que um saque fica pendente ou é rejeitado' },
        { type: 'p', text: 'A maioria dos atrasos tem causa simples. Verifique estes pontos antes de contatar o suporte:' },
        { type: 'ul', items: [
          'Verificação incompleta ou documentos rejeitados (foto borrada, bordas cortadas, documento vencido).',
          'Método de saque diferente do método de depósito — devolva primeiro o valor depositado e depois saque o lucro.',
          'Endereço da carteira ou número do cartão digitado errado — cancele o pedido enquanto ainda está “Solicitado” e crie um novo.',
          'Volume de bônus não concluído.',
          'Fim de semana ou feriado — a plataforma processa os pedidos, mas os bancos não transferem.',
        ] },
        { type: 'p', text: 'Se o status continuar “Solicitado” após 24 horas e nenhum dos itens acima se aplicar, abra o chat de suporte dentro da plataforma e informe o ID da transação do histórico.' },
        { type: 'warn', title: 'Nota de segurança', text: 'A Pocket Option nunca pede senha do cartão, frase-semente da carteira ou uma “taxa de liberação” para processar um saque. Pedidos desse tipo são golpes — use apenas o chat de suporte dentro da sua conta.' },
        { type: 'cta', text: 'Novo na plataforma? Abra uma conta, conclua a verificação e teste todo o ciclo com um depósito pequeno de $5 antes de operar valores maiores.', label: 'Abrir conta na Pocket Option' },
      ],
      faq: [
        { q: 'Quanto tempo leva um saque na Pocket Option?', a: 'A plataforma normalmente processa o pedido em até 24 horas. Após a aprovação, cripto e carteiras eletrônicas chegam em horas, cartões em 1–5 dias úteis e transferências bancárias em 2–7 dias úteis.' },
        { q: 'Qual é o saque mínimo na Pocket Option?', a: 'O saque mínimo é $10 na maioria dos métodos de pagamento. Alguns métodos definem um mínimo próprio mais alto.' },
        { q: 'A Pocket Option cobra taxa de saque?', a: 'Não, a plataforma não cobra por depósitos ou saques. Taxas de banco, carteira eletrônica ou rede blockchain ainda podem se aplicar no lado do recebimento.' },
        { q: 'Posso sacar para um método diferente do que usei no depósito?', a: 'O valor depositado retorna ao método original. O lucro acima desse valor normalmente pode ser sacado para outro método suportado, inclusive carteiras de criptomoedas.' },
        { q: 'Por que meu saque na Pocket Option está pendente?', a: 'Motivos comuns: verificação incompleta, método diferente, dados de pagamento incorretos, volume de bônus não concluído ou feriados bancários. Verifique isso primeiro e depois contate o suporte com o ID da transação.' },
        { q: 'Posso sacar dinheiro da conta demo?', a: 'Não. Os fundos demo são virtuais e não podem ser sacados. Apenas o saldo da conta real pode ser retirado.' },
      ],
    },

    es: {
      title: 'Retiro en Pocket Option: cómo retirar dinero, tiempos, límites y comisiones',
      metaTitle: 'Guía de retiro en Pocket Option: cómo retirar dinero, tiempos, límites y comisiones',
      metaDescription:
        'Cómo retirar dinero de Pocket Option paso a paso: verificación, elección del método de pago, mínimo de $10, procesamiento en unas 24 horas, sin comisiones de la plataforma y cómo resolver un retiro pendiente o rechazado.',
      excerpt:
        'Recorrido completo del retiro en pocketoption: qué verificar antes de la primera solicitud, qué métodos son más rápidos, cuánto tarda y por qué algunos retiros se retrasan.',
      coverAlt: 'Monedas de oro frente a un gráfico de trading — retirando beneficios de Pocket Option',
      keyTakeaways: [
        'Los retiros van al mismo método con el que depositaste; el mínimo es $10 en la mayoría de métodos.',
        'Pocket Option no cobra comisión por retiro; tu banco o la red cripto pueden hacerlo.',
        'El procesamiento típico es de unas 24 horas; las cuentas verificadas y las carteras cripto suelen ser las más rápidas.',
        'Completa el KYC (documento + domicilio) antes del primer retiro para evitar una solicitud “pendiente”.',
      ],
      blocks: [
        { type: 'p', text: 'Retirar dinero de Pocket Option es un proceso de cuatro pasos: verificar la cuenta, abrir la sección Finanzas, elegir el método de pago y confirmar el importe. La mayoría de solicitudes se procesan en un día. Esta guía explica cada paso del retiro en pocketoption, los límites y comisiones que debes esperar y las razones por las que una solicitud puede quedar pendiente o ser rechazada.' },
        { type: 'h2', id: 'before', text: 'Antes de retirar: verificación y la regla del depósito' },
        { type: 'image', src: IMG_VERIFY, alt: 'Verificación de perfil en Pocket Option — documentos de identidad y domicilio', caption: 'La verificación (KYC) se exige una vez, antes del primer retiro.' },
        { type: 'p', text: 'Dos reglas rigen todo retiro en Pocket Option. Primera, la cuenta debe estar verificada: sube una foto de tu documento (pasaporte, DNI o licencia de conducir) y un comprobante de domicilio (factura de servicios o extracto bancario de menos de tres meses) en Perfil → Verificación. Segunda, los fondos vuelven al mismo método usado para depositar: un depósito con tarjeta se retira a la misma tarjeta, un depósito en USDT a una cartera USDT. El beneficio por encima del importe depositado normalmente puede enviarse a cualquier método admitido, incluidas criptomonedas.' },
        { type: 'tip', title: 'Verifica el primer día', text: 'La verificación tarda de unos minutos a un par de días. Hacerla justo después del registro evita que tu primer retiro se detenga mientras se revisan los documentos.' },
        { type: 'h2', id: 'steps', text: 'Cómo retirar de Pocket Option paso a paso' },
        { type: 'ol', items: [
          'Inicia sesión en tu cuenta pocketoption y abre Finanzas → Retiro en el menú izquierdo.',
          'Selecciona el método de pago. Solo aparecen los métodos con los que has depositado (más cripto para el beneficio).',
          'Introduce el importe —al menos $10 en la mayoría de métodos— y los datos de la cartera, tarjeta o cuenta.',
          'Confirma la solicitud. Aparece en Finanzas → Historial de transacciones con el estado “Solicitado”.',
          'Espera el procesamiento. El estado cambia a “Aprobado” y el dinero llega según el plazo propio del método.',
        ] },
        { type: 'image', src: IMG_WITHDRAW, alt: 'Solicitud de retiro confirmada en la sección Finanzas de Pocket Option', caption: 'Sigue cada solicitud en Finanzas → Historial de transacciones.' },
        { type: 'h2', id: 'methods', text: 'Métodos de retiro y cuánto tardan' },
        { type: 'p', text: 'Pocket Option admite más de 50 métodos de pago; la disponibilidad depende de tu país. La parte de la plataforma suele completarse en 24 horas; el resto es el tiempo de la transferencia en sí.' },
        { type: 'table', head: ['Método', 'Llegada típica tras la aprobación', 'Notas'], rows: [
          ['Criptomonedas (USDT, BTC, ETH, LTC…)', 'Minutos a unas horas', 'Opción más rápida; se aplica comisión de red'],
          ['Monederos electrónicos (Skrill, Neteller, Perfect Money, AdvCash)', 'Mismo día', 'El monedero debe estar a tu nombre'],
          ['Métodos locales (Pix, UPI, M-Pesa, bKash, Mercado Pago…)', 'Mismo día – 1 día hábil', 'Depende del proveedor local'],
          ['Visa / Mastercard', '1–5 días hábiles', 'El plazo bancario varía según el emisor'],
          ['Transferencia bancaria', '2–7 días hábiles', 'Disponible en países seleccionados'],
        ] },
        { type: 'h2', id: 'limits', text: 'Mínimo, máximo y comisiones' },
        { type: 'ul', items: [
          'Retiro mínimo: $10 (algunos métodos tienen su propio mínimo, más alto).',
          'Máximo por solicitud: depende del método y del nivel de cuenta; los importes grandes pueden dividirse en varias solicitudes.',
          'Comisión de la plataforma: ninguna — Pocket Option no cobra por depósitos ni retiros.',
          'Comisiones de terceros: pueden aplicarse comisiones de red cripto, cargos bancarios o de monedero y conversión de divisa.',
          'Fondos de bono: si aceptaste un bono de depósito, debes cumplir el volumen de operaciones requerido antes de retirar la parte del bono.',
        ] },
        { type: 'h2', id: 'pending', text: 'Por qué un retiro queda pendiente o es rechazado' },
        { type: 'p', text: 'La mayoría de retrasos tienen una causa sencilla. Revisa esto antes de contactar con soporte:' },
        { type: 'ul', items: [
          'Verificación incompleta o documentos rechazados (foto borrosa, bordes recortados, documento caducado).',
          'El método de retiro difiere del de depósito: devuelve primero la suma depositada y luego retira el beneficio.',
          'Dirección de cartera o número de tarjeta mal introducidos: cancela la solicitud mientras siga “Solicitado” y crea una nueva.',
          'Volumen de bono sin completar.',
          'Fin de semana o festivo: la plataforma procesa solicitudes, pero los bancos no transfieren fondos.',
        ] },
        { type: 'p', text: 'Si el estado sigue en “Solicitado” tras 24 horas y no aplica ninguno de los puntos anteriores, abre el chat de soporte dentro de la plataforma e indica el ID de transacción del historial.' },
        { type: 'warn', title: 'Nota de seguridad', text: 'Pocket Option nunca pide el PIN de la tarjeta, la frase semilla de la cartera ni una “tasa de liberación” para procesar un retiro. Ese tipo de solicitudes son estafas: usa solo el chat de soporte dentro de tu cuenta.' },
        { type: 'cta', text: '¿Nuevo en la plataforma? Abre una cuenta, completa la verificación y prueba todo el ciclo con un depósito pequeño de $5 antes de operar sumas mayores.', label: 'Abrir cuenta en Pocket Option' },
      ],
      faq: [
        { q: '¿Cuánto tarda un retiro en Pocket Option?', a: 'La plataforma suele procesar la solicitud en 24 horas. Tras la aprobación, cripto y monederos electrónicos llegan en horas, las tarjetas en 1–5 días hábiles y las transferencias bancarias en 2–7 días hábiles.' },
        { q: '¿Cuál es el retiro mínimo en Pocket Option?', a: 'El retiro mínimo es $10 en la mayoría de métodos de pago. Algunos métodos fijan un mínimo propio más alto.' },
        { q: '¿Pocket Option cobra comisiones por retiro?', a: 'No, la plataforma no cobra por depósitos ni retiros. Pueden aplicarse comisiones del banco, del monedero o de la red blockchain en el lado receptor.' },
        { q: '¿Puedo retirar a un método distinto del que usé para depositar?', a: 'El importe depositado se devuelve al método original. El beneficio por encima de ese importe normalmente puede retirarse a otro método admitido, incluidas carteras de criptomonedas.' },
        { q: '¿Por qué mi retiro en Pocket Option está pendiente?', a: 'Las causas habituales son verificación incompleta, método distinto, datos de pago incorrectos, volumen de bono sin completar o festivos bancarios. Revísalo primero y luego contacta con soporte con el ID de transacción.' },
        { q: '¿Puedo retirar dinero de la cuenta demo?', a: 'No. Los fondos demo son virtuales y no pueden retirarse. Solo se puede retirar el saldo de la cuenta real.' },
      ],
    },

    ru: {
      title: 'Вывод средств с Pocket Option: как вывести деньги, сроки, лимиты и комиссии',
      metaTitle: 'Вывод средств с Pocket Option: как вывести деньги, сроки, лимиты и комиссии',
      metaDescription:
        'Как вывести деньги с Pocket Option пошагово: верификация, выбор платёжного метода, минимум $10, обработка около 24 часов, без комиссии платформы и что делать с ожидающей или отклонённой заявкой.',
      excerpt:
        'Полный разбор вывода средств с pocketoption: что проверить перед первой заявкой, какие методы быстрее, сколько это занимает и почему некоторые выводы задерживаются.',
      coverAlt: 'Золотые монеты на фоне торгового графика — вывод прибыли с Pocket Option',
      keyTakeaways: [
        'Вывод идёт на тот же метод, которым вы пополняли счёт; минимум — $10 для большинства методов.',
        'Pocket Option не берёт комиссию за вывод — её может взять банк или криптосеть.',
        'Типичная обработка — около 24 часов; верифицированные аккаунты и криптокошельки обычно быстрее всех.',
        'Пройдите KYC (документ + адрес) до первого вывода, чтобы заявка не зависла в статусе «ожидание».',
      ],
      blocks: [
        { type: 'p', text: 'Вывод денег с Pocket Option — процесс из четырёх шагов: верифицировать аккаунт, открыть раздел «Финансы», выбрать метод выплаты и подтвердить сумму. Большинство заявок обрабатывается в течение дня. В этом руководстве — каждый шаг вывода с pocketoption, лимиты и комиссии, которых стоит ожидать, а также причины, по которым заявка может зависнуть или быть отклонена.' },
        { type: 'h2', id: 'before', text: 'Перед выводом: верификация и правило депозита' },
        { type: 'image', src: IMG_VERIFY, alt: 'Верификация профиля Pocket Option — документы, удостоверяющие личность и адрес', caption: 'Верификация (KYC) требуется один раз, перед первым выводом.' },
        { type: 'p', text: 'Каждый вывод на Pocket Option подчиняется двум правилам. Первое: аккаунт должен быть верифицирован — загрузите фото документа (паспорт, ID-карта или водительские права) и подтверждение адреса (счёт за коммунальные услуги или банковская выписка не старше трёх месяцев) в разделе Профиль → Верификация. Второе: средства возвращаются на тот же метод, которым был сделан депозит — депозит с карты выводится на ту же карту, депозит в USDT — на USDT-кошелёк. Прибыль сверх внесённой суммы обычно можно отправить на любой поддерживаемый метод, включая криптовалюту.' },
        { type: 'tip', title: 'Верифицируйтесь в первый день', text: 'Верификация занимает от нескольких минут до пары дней. Если пройти её сразу после регистрации, первый вывод не будет задержан из-за проверки документов.' },
        { type: 'h2', id: 'steps', text: 'Как вывести деньги с Pocket Option пошагово' },
        { type: 'ol', items: [
          'Войдите в аккаунт pocketoption и откройте Финансы → Вывод в левом меню.',
          'Выберите платёжный метод. Показываются только методы, которыми вы пополняли счёт (плюс крипто для прибыли).',
          'Введите сумму — не менее $10 для большинства методов — и адрес кошелька, номер карты или реквизиты счёта.',
          'Подтвердите заявку. Она появится в Финансы → История транзакций со статусом «Запрошено».',
          'Дождитесь обработки. Статус сменится на «Одобрено», и деньги придут в срок, зависящий от самого метода.',
        ] },
        { type: 'image', src: IMG_WITHDRAW, alt: 'Подтверждённая заявка на вывод в разделе «Финансы» Pocket Option', caption: 'Отслеживайте каждую заявку в Финансы → История транзакций.' },
        { type: 'h2', id: 'methods', text: 'Методы вывода и сроки' },
        { type: 'p', text: 'Pocket Option поддерживает 50+ платёжных методов; доступность зависит от страны. Сторона платформы обычно завершает обработку в течение 24 часов; остальное время — сам перевод.' },
        { type: 'table', head: ['Метод', 'Типичное зачисление после одобрения', 'Примечания'], rows: [
          ['Криптовалюта (USDT, BTC, ETH, LTC…)', 'От минут до нескольких часов', 'Самый быстрый вариант; комиссия сети'],
          ['Электронные кошельки (Skrill, Neteller, Perfect Money, AdvCash)', 'В тот же день', 'Кошелёк должен быть на ваше имя'],
          ['Локальные методы (Pix, UPI, M-Pesa, bKash, Mercado Pago…)', 'В тот же день – 1 рабочий день', 'Зависит от локального провайдера'],
          ['Visa / Mastercard', '1–5 рабочих дней', 'Срок зависит от банка-эмитента'],
          ['Банковский перевод', '2–7 рабочих дней', 'Доступен в отдельных странах'],
        ] },
        { type: 'h2', id: 'limits', text: 'Минимум, максимум и комиссии' },
        { type: 'ul', items: [
          'Минимальный вывод: $10 (у некоторых методов свой, более высокий минимум).',
          'Максимум на заявку: зависит от метода и уровня аккаунта; крупные суммы можно разбить на несколько заявок.',
          'Комиссия платформы: отсутствует — Pocket Option не берёт плату за депозиты и выводы.',
          'Сторонние комиссии: комиссия криптосети, банка или кошелька и конвертация валюты.',
          'Бонусные средства: если вы приняли бонус на депозит, перед выводом бонусной части нужно выполнить требуемый торговый оборот.',
        ] },
        { type: 'h2', id: 'pending', text: 'Почему вывод в ожидании или отклонён' },
        { type: 'p', text: 'У большинства задержек простая причина. Проверьте это перед обращением в поддержку:' },
        { type: 'ul', items: [
          'Верификация не завершена или документы отклонены (размытое фото, обрезанные края, просроченный документ).',
          'Метод вывода отличается от метода депозита — сначала верните внесённую сумму, затем выводите прибыль.',
          'Неверно введён адрес кошелька или номер карты — отмените заявку, пока она в статусе «Запрошено», и создайте новую.',
          'Не выполнен бонусный оборот.',
          'Выходной или праздник — платформа обрабатывает заявки, но банки не проводят переводы.',
        ] },
        { type: 'p', text: 'Если через 24 часа статус всё ещё «Запрошено» и ничего из перечисленного не подходит, откройте чат поддержки внутри платформы и укажите ID транзакции из истории.' },
        { type: 'warn', title: 'О безопасности', text: 'Pocket Option никогда не запрашивает PIN-код карты, seed-фразу кошелька или «комиссию за разблокировку» для обработки вывода. Такие запросы — мошенничество; используйте только чат поддержки внутри аккаунта.' },
        { type: 'cta', text: 'Новичок на платформе? Откройте счёт, пройдите верификацию и проверьте весь цикл на небольшом депозите $5, прежде чем торговать крупными суммами.', label: 'Открыть счёт Pocket Option' },
      ],
      faq: [
        { q: 'Сколько длится вывод с Pocket Option?', a: 'Платформа обычно обрабатывает заявку в течение 24 часов. После одобрения крипто и электронные кошельки приходят за часы, карты — за 1–5 рабочих дней, банковские переводы — за 2–7 рабочих дней.' },
        { q: 'Какой минимальный вывод на Pocket Option?', a: 'Минимальный вывод — $10 для большинства платёжных методов. У некоторых методов установлен собственный, более высокий минимум.' },
        { q: 'Берёт ли Pocket Option комиссию за вывод?', a: 'Нет, платформа не берёт плату за депозиты и выводы. Комиссии банка, кошелька или блокчейн-сети могут взиматься на стороне получателя.' },
        { q: 'Можно ли вывести на другой метод, не тот, которым пополнял?', a: 'Внесённая сумма возвращается на исходный метод. Прибыль сверх этой суммы обычно можно вывести на другой поддерживаемый метод, включая криптокошельки.' },
        { q: 'Почему мой вывод с Pocket Option в ожидании?', a: 'Частые причины: незавершённая верификация, несовпадение метода, неверные реквизиты, невыполненный бонусный оборот или банковские выходные. Проверьте это, затем обратитесь в поддержку с ID транзакции.' },
        { q: 'Можно ли вывести деньги с демо-счёта?', a: 'Нет. Демо-средства виртуальные и не выводятся. Вывести можно только баланс реального счёта.' },
      ],
    },

    id: {
      title: 'Penarikan Pocket Option: cara withdraw, waktu proses, limit, dan biaya',
      metaTitle: 'Panduan penarikan Pocket Option: cara withdraw, waktu proses, limit, dan biaya',
      metaDescription:
        'Cara menarik uang dari Pocket Option langkah demi langkah: verifikasi, memilih metode pembayaran, minimum $10, waktu proses sekitar 24 jam, tanpa biaya platform, dan cara mengatasi penarikan pending atau ditolak.',
      excerpt:
        'Panduan lengkap penarikan pocketoption: apa yang harus diverifikasi sebelum permintaan pertama, metode mana yang tercepat, berapa lama prosesnya, dan mengapa beberapa penarikan tertunda.',
      coverAlt: 'Koin emas di depan grafik trading — menarik profit dari Pocket Option',
      keyTakeaways: [
        'Penarikan dikirim ke metode yang sama dengan deposit Anda; minimumnya $10 untuk sebagian besar metode.',
        'Pocket Option tidak mengenakan biaya penarikan — bank atau jaringan kripto Anda mungkin mengenakannya.',
        'Proses umumnya sekitar 24 jam; akun terverifikasi dan dompet kripto biasanya paling cepat.',
        'Selesaikan KYC (identitas + alamat) sebelum penarikan pertama agar permintaan tidak “pending”.',
      ],
      blocks: [
        { type: 'p', text: 'Menarik uang dari Pocket Option adalah proses empat langkah: verifikasi akun, buka bagian Keuangan, pilih metode pembayaran, dan konfirmasi jumlah. Sebagian besar permintaan diproses dalam satu hari. Panduan ini menjelaskan setiap langkah penarikan pocketoption, limit dan biaya yang perlu diketahui, serta alasan sebuah permintaan bisa berakhir pending atau ditolak.' },
        { type: 'h2', id: 'before', text: 'Sebelum menarik: verifikasi dan aturan deposit' },
        { type: 'image', src: IMG_VERIFY, alt: 'Verifikasi profil Pocket Option — dokumen identitas dan alamat', caption: 'Verifikasi (KYC) diwajibkan sekali, sebelum penarikan pertama.' },
        { type: 'p', text: 'Dua aturan mengatur setiap penarikan Pocket Option. Pertama, akun harus terverifikasi: unggah foto identitas (paspor, KTP, atau SIM) dan bukti alamat (tagihan utilitas atau rekening koran tidak lebih dari tiga bulan) di Profil → Verifikasi. Kedua, dana dikembalikan ke metode pembayaran yang sama dengan deposit — deposit kartu ditarik ke kartu yang sama, deposit USDT ke dompet USDT. Profit di atas jumlah deposit biasanya bisa dikirim ke metode apa pun yang didukung, termasuk kripto.' },
        { type: 'tip', title: 'Verifikasi di hari pertama', text: 'Verifikasi memakan waktu beberapa menit hingga beberapa hari. Melakukannya tepat setelah registrasi berarti penarikan pertama Anda tidak tertahan saat dokumen ditinjau.' },
        { type: 'h2', id: 'steps', text: 'Cara withdraw dari Pocket Option langkah demi langkah' },
        { type: 'ol', items: [
          'Login ke akun pocketoption Anda dan buka Keuangan → Penarikan di menu kiri.',
          'Pilih metode pembayaran. Hanya metode yang pernah Anda gunakan untuk deposit (plus kripto untuk profit) yang ditampilkan.',
          'Masukkan jumlah — minimal $10 untuk sebagian besar metode — dan alamat dompet, kartu, atau detail rekening.',
          'Konfirmasi permintaan. Permintaan muncul di Keuangan → Riwayat transaksi dengan status “Diminta”.',
          'Tunggu proses. Status berubah menjadi “Disetujui” dan uang tiba sesuai waktu transfer metode masing-masing.',
        ] },
        { type: 'image', src: IMG_WITHDRAW, alt: 'Permintaan penarikan Pocket Option terkonfirmasi di bagian Keuangan', caption: 'Lacak setiap permintaan di Keuangan → Riwayat transaksi.' },
        { type: 'h2', id: 'methods', text: 'Metode penarikan dan lamanya' },
        { type: 'p', text: 'Pocket Option mendukung 50+ metode pembayaran; ketersediaan bergantung pada negara Anda. Sisi platform biasanya selesai dalam 24 jam; sisanya adalah waktu transfer itu sendiri.' },
        { type: 'table', head: ['Metode', 'Waktu tiba setelah disetujui', 'Catatan'], rows: [
          ['Kripto (USDT, BTC, ETH, LTC…)', 'Menit hingga beberapa jam', 'Opsi tercepat; biaya jaringan berlaku'],
          ['E-wallet (Skrill, Neteller, Perfect Money, AdvCash)', 'Hari yang sama', 'Dompet harus atas nama Anda'],
          ['Metode lokal (Pix, UPI, M-Pesa, bKash, Mercado Pago…)', 'Hari yang sama – 1 hari kerja', 'Bergantung pada penyedia lokal'],
          ['Visa / Mastercard', '1–5 hari kerja', 'Waktu proses bank bervariasi per penerbit'],
          ['Transfer bank', '2–7 hari kerja', 'Tersedia di negara tertentu'],
        ] },
        { type: 'h2', id: 'limits', text: 'Minimum, maksimum, dan biaya' },
        { type: 'ul', items: [
          'Penarikan minimum: $10 (beberapa metode punya minimum sendiri yang lebih tinggi).',
          'Maksimum per permintaan: bergantung pada metode dan level akun; jumlah besar bisa dipecah menjadi beberapa permintaan.',
          'Biaya platform: tidak ada — Pocket Option tidak memungut biaya deposit maupun penarikan.',
          'Biaya pihak ketiga: biaya jaringan kripto, biaya bank atau e-wallet, dan konversi mata uang bisa berlaku.',
          'Dana bonus: jika Anda menerima bonus deposit, turnover trading yang disyaratkan harus dipenuhi sebelum menarik bagian bonus.',
        ] },
        { type: 'h2', id: 'pending', text: 'Mengapa penarikan pending atau ditolak' },
        { type: 'p', text: 'Sebagian besar penundaan penyebabnya sederhana. Periksa ini sebelum menghubungi dukungan:' },
        { type: 'ul', items: [
          'Verifikasi belum selesai atau dokumen ditolak (foto buram, tepi terpotong, identitas kedaluwarsa).',
          'Metode penarikan berbeda dari metode deposit — kembalikan dulu jumlah deposit, lalu tarik profitnya.',
          'Alamat dompet atau nomor kartu salah — batalkan permintaan selagi masih “Diminta” dan buat yang baru.',
          'Turnover bonus belum selesai.',
          'Akhir pekan atau hari libur — platform memproses permintaan, tetapi bank tidak mentransfer dana.',
        ] },
        { type: 'p', text: 'Jika status masih “Diminta” setelah 24 jam dan tidak ada poin di atas yang berlaku, buka chat dukungan di dalam platform dan sebutkan ID transaksi dari riwayat.' },
        { type: 'warn', title: 'Catatan keamanan', text: 'Pocket Option tidak pernah meminta PIN kartu, seed phrase dompet, atau “biaya pelepasan” untuk memproses penarikan. Permintaan semacam itu adalah penipuan — gunakan hanya chat dukungan di dalam akun Anda.' },
        { type: 'cta', text: 'Baru di platform? Buka akun, selesaikan verifikasi, dan uji seluruh siklus dengan deposit kecil $5 sebelum trading dengan jumlah lebih besar.', label: 'Buka akun Pocket Option' },
      ],
      faq: [
        { q: 'Berapa lama penarikan Pocket Option?', a: 'Platform biasanya memproses permintaan dalam 24 jam. Setelah disetujui, kripto dan e-wallet tiba dalam hitungan jam, kartu 1–5 hari kerja, dan transfer bank 2–7 hari kerja.' },
        { q: 'Berapa penarikan minimum di Pocket Option?', a: 'Penarikan minimum adalah $10 untuk sebagian besar metode pembayaran. Beberapa metode menetapkan minimum sendiri yang lebih tinggi.' },
        { q: 'Apakah Pocket Option mengenakan biaya penarikan?', a: 'Tidak, platform tidak memungut biaya deposit maupun penarikan. Biaya bank, e-wallet, atau jaringan blockchain mungkin tetap berlaku di sisi penerima.' },
        { q: 'Bisakah saya menarik ke metode yang berbeda dari deposit?', a: 'Jumlah deposit dikembalikan ke metode asal. Profit di atas jumlah itu biasanya bisa ditarik ke metode lain yang didukung, termasuk dompet kripto.' },
        { q: 'Mengapa penarikan Pocket Option saya pending?', a: 'Alasan umum: verifikasi belum lengkap, metode tidak cocok, detail pembayaran salah, turnover bonus belum selesai, atau libur bank. Periksa ini dulu, lalu hubungi dukungan dengan ID transaksi.' },
        { q: 'Bisakah saya menarik uang dari akun demo?', a: 'Tidak. Dana demo bersifat virtual dan tidak bisa ditarik. Hanya saldo akun riil yang bisa ditarik.' },
      ],
    },
  },
};
