import type { BlogPost } from '../types';

const IMG_STATS = '/images/blog/po-about-stats.webp';
const IMG_REGISTER = '/images/blog/po-registration-form.webp';

export const pocketOptionCountries: BlogPost = {
  slug: 'pocket-option-countries',
  category: 'platform',
  cover: '/images/blog/pocket-option-countries.webp',
  publishedAt: '2026-09-28',
  updatedAt: '2026-09-28',
  readingMinutes: 6,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option Countries',
      metaTitle: 'Pocket Option Countries: Where It Is Available and Restricted (2026)',
      metaDescription:
        'Which countries Pocket Option accepts and which are restricted (USA, EU, UK, Canada, Australia…). Regional payment methods, languages, and what happens if you trade from a banned country.',
      excerpt:
        'Pocket Option serves traders in 90+ countries but blocks the USA, EU, UK and several others. Here is the availability map, regional payment options and the rules you should know.',
      coverAlt: 'Pocket Option statistics: active users, trading turnover and 94+ countries and regions',
      keyTakeaways: [
        'Pocket Option accepts clients from most of Asia, Latin America, Africa, the Middle East and the CIS.',
        'Restricted: USA, EU/EEA countries, UK, Canada, Australia, Israel, Japan, Switzerland and a few others.',
        'Local payment methods (Pix, UPI, M-Pesa, QRIS, bKash…) and 15+ interface languages are tailored per region.',
        'Using a VPN to register from a restricted country violates the terms and can lead to account closure without payout.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option is a global broker — according to its own figures it serves traders from more than 90 countries and regions. But it is not available everywhere: as an offshore platform offering binary options, it does not accept residents of jurisdictions where this product is banned for retail clients. This guide lists where pocketoption is available, where it is restricted, and what differs by region.' },
        { type: 'h2', id: 'available', text: 'Countries where Pocket Option is available' },
        { type: 'p', text: 'Registration is open to most of the world outside North America, Western Europe and Oceania. The largest user bases are in these regions:' },
        { type: 'table', head: ['Region', 'Examples of accepted countries', 'Popular local payments'], rows: [
          ['South & Southeast Asia', 'India, Indonesia, Pakistan, Bangladesh, Vietnam, Thailand, Philippines, Malaysia', 'UPI, QRIS, DANA, bKash, JazzCash, PromptPay, GCash'],
          ['Latin America', 'Brazil, Mexico, Colombia, Argentina, Peru, Chile', 'Pix, Mercado Pago, SPEI, PSE, Nequi'],
          ['Africa', 'Nigeria, South Africa, Kenya, Ghana, Uganda, Egypt', 'M-Pesa, MTN Mobile Money, Airtel Money, bank transfer'],
          ['Middle East', 'UAE, Saudi Arabia, Turkey, Iraq', 'Cards, crypto, local bank transfer'],
          ['CIS', 'Kazakhstan, Uzbekistan, Kyrgyzstan, Azerbaijan, Armenia', 'Cards, Kaspi, crypto'],
        ] },
        { type: 'image', src: IMG_STATS, alt: 'Pocket Option company figures: 99,000+ active users, 94+ countries and regions', caption: 'Company figures published on the official About page.' },
        { type: 'h2', id: 'restricted', text: 'Restricted countries' },
        { type: 'p', text: 'Pocket Option does not open accounts for residents of the following jurisdictions. The list comes from the platform’s Terms and Conditions and can change without notice:' },
        { type: 'ul', items: [
          'United States and its territories',
          'European Union / EEA member states (Germany, France, Spain, Italy, Poland, Netherlands, Portugal…)',
          'United Kingdom',
          'Canada',
          'Australia and New Zealand',
          'Israel, Japan, Switzerland, Iran, North Korea and other sanctioned territories',
        ] },
        { type: 'p', text: 'Residents of these countries will see a “service not available in your region” message during registration or be asked for proof of address from an accepted country during verification.' },
        { type: 'warn', title: 'VPN is not a workaround', text: 'Registering through a VPN from a restricted country breaches the terms. Verification requires a passport or ID and proof of address; a mismatch leads to account closure and forfeiture of the balance. Do not risk your money.' },
        { type: 'h2', id: 'regional', text: 'What differs by region' },
        { type: 'ul', items: [
          'Payment methods — the deposit page shows only the options for your country; global methods (cards, crypto, Skrill, Neteller) are available almost everywhere.',
          'Account currency — USD by default, with local currencies (BRL, INR, IDR, NGN…) available in some countries; choose carefully, it cannot be changed later.',
          'Interface language — English, Portuguese, Spanish, Russian, Indonesian, Hindi, Turkish, Arabic, Thai, Vietnamese and more.',
          'Support — chat and email in the main languages; response times are similar across regions.',
          'Trading conditions — assets, payouts, minimum deposit ($5) and minimum trade ($1) are the same in all countries.',
        ] },
        { type: 'h2', id: 'check', text: 'How to check availability in your country' },
        { type: 'image', src: IMG_REGISTER, alt: 'Pocket Option registration form with country selection', caption: 'The country field in the registration form lists only accepted countries.' },
        { type: 'ol', items: [
          'Open the registration page — if your country is missing from the list, it is restricted.',
          'Create a free demo account: no deposit or documents are required.',
          'Go to Finance → Deposit to see which payment methods and currencies are offered for your region.',
          'If you move to another country, notify support; the account can be updated after re-verification.',
        ] },
        { type: 'tip', title: 'Travelling?', text: 'Trading while travelling in a restricted country is generally tolerated for short periods if your registered residence is accepted, but deposits and withdrawals may be flagged. Keep your account documents current.' },
        { type: 'cta', text: 'Check if Pocket Option is available for you — open a free demo account in one minute.', label: 'Open free demo' },
      ],
      faq: [
        { q: 'Is Pocket Option available in the USA?', a: 'No. Residents of the United States cannot open an account, and US traders should not attempt to register via VPN.' },
        { q: 'Is Pocket Option available in Europe?', a: 'Not in EU/EEA countries, the UK or Switzerland. It is available in some non-EU European countries such as Turkey, Serbia and Georgia.' },
        { q: 'Which countries use Pocket Option the most?', a: 'India, Brazil, Indonesia, Nigeria, Pakistan, Bangladesh, Mexico, Colombia, South Africa and Vietnam are among the largest markets.' },
        { q: 'Can I use a VPN to access Pocket Option?', a: 'Using a VPN from a restricted country violates the terms. Verification will reveal your real residence and the account can be closed.' },
        { q: 'Does Pocket Option accept Indian, Brazilian or Nigerian traders?', a: 'Yes, all three are accepted, with local payment methods such as UPI, Pix and bank transfer.' },
        { q: 'Where is Pocket Option regulated?', a: 'The operator holds a licence from the Mwali International Services Authority (MISA) in the Comoros.' },
      ],
    },
    pt: {
      title: 'Pocket Option: países disponíveis',
      metaTitle: 'Países da Pocket Option: onde está disponível e onde é restrita (2026)',
      metaDescription:
        'Quais países a Pocket Option aceita e quais são restritos (EUA, UE, Reino Unido, Canadá, Austrália…). Métodos de pagamento regionais, idiomas e o que acontece se operar de país proibido.',
      excerpt:
        'A Pocket Option atende traders em mais de 90 países, mas bloqueia EUA, UE, Reino Unido e outros. Veja o mapa de disponibilidade, opções de pagamento regionais e as regras que precisa conhecer.',
      coverAlt: 'Estatísticas da Pocket Option: usuários ativos, volume negociado e mais de 94 países e regiões',
      keyTakeaways: [
        'A Pocket Option aceita clientes da maior parte da Ásia, América Latina, África, Oriente Médio e CEI.',
        'Restritos: EUA, países da UE/EEE, Reino Unido, Canadá, Austrália, Israel, Japão, Suíça e alguns outros.',
        'Métodos locais (Pix, UPI, M-Pesa, QRIS, bKash…) e mais de 15 idiomas de interface são adaptados por região.',
        'Usar VPN para se cadastrar de país restrito viola os termos e pode levar ao encerramento da conta sem pagamento.',
      ],
      blocks: [
        { type: 'p', text: 'A Pocket Option é uma corretora global — segundo números próprios, atende traders de mais de 90 países e regiões. Mas não está disponível em todo lugar: como plataforma offshore de opções binárias, não aceita residentes de jurisdições onde esse produto é proibido para o varejo. Este guia lista onde a pocketoption está disponível, onde é restrita e o que muda por região.' },
        { type: 'h2', id: 'available', text: 'Países onde a Pocket Option está disponível' },
        { type: 'p', text: 'O cadastro está aberto para a maior parte do mundo fora da América do Norte, Europa Ocidental e Oceania. As maiores bases de usuários estão nestas regiões:' },
        { type: 'table', head: ['Região', 'Exemplos de países aceitos', 'Pagamentos locais populares'], rows: [
          ['Sul e Sudeste Asiático', 'Índia, Indonésia, Paquistão, Bangladesh, Vietnã, Tailândia, Filipinas, Malásia', 'UPI, QRIS, DANA, bKash, JazzCash, PromptPay, GCash'],
          ['América Latina', 'Brasil, México, Colômbia, Argentina, Peru, Chile', 'Pix, Mercado Pago, SPEI, PSE, Nequi'],
          ['África', 'Nigéria, África do Sul, Quênia, Gana, Uganda, Egito', 'M-Pesa, MTN Mobile Money, Airtel Money, transferência bancária'],
          ['Oriente Médio', 'Emirados, Arábia Saudita, Turquia, Iraque', 'Cartões, cripto, transferência local'],
          ['CEI', 'Cazaquistão, Uzbequistão, Quirguistão, Azerbaijão, Armênia', 'Cartões, Kaspi, cripto'],
        ] },
        { type: 'image', src: IMG_STATS, alt: 'Números da Pocket Option: mais de 99.000 usuários ativos, mais de 94 países e regiões', caption: 'Números publicados na página oficial Sobre nós.' },
        { type: 'h2', id: 'restricted', text: 'Países restritos' },
        { type: 'p', text: 'A Pocket Option não abre contas para residentes das jurisdições abaixo. A lista vem dos Termos e Condições da plataforma e pode mudar sem aviso:' },
        { type: 'ul', items: [
          'Estados Unidos e territórios',
          'Estados-membros da UE/EEE (Alemanha, França, Espanha, Itália, Polônia, Holanda, Portugal…)',
          'Reino Unido',
          'Canadá',
          'Austrália e Nova Zelândia',
          'Israel, Japão, Suíça, Irã, Coreia do Norte e outros territórios sancionados',
        ] },
        { type: 'p', text: 'Residentes desses países verão a mensagem “serviço indisponível na sua região” no cadastro ou terão de apresentar comprovante de endereço de um país aceito na verificação.' },
        { type: 'warn', title: 'VPN não é solução', text: 'Cadastrar-se por VPN a partir de país restrito viola os termos. A verificação exige passaporte ou identidade e comprovante de endereço; divergência leva ao encerramento da conta e perda do saldo. Não arrisque seu dinheiro.' },
        { type: 'h2', id: 'regional', text: 'O que muda por região' },
        { type: 'ul', items: [
          'Métodos de pagamento — a página de depósito mostra só as opções do seu país; métodos globais (cartões, cripto, Skrill, Neteller) existem quase em todo lugar.',
          'Moeda da conta — USD por padrão, com moedas locais (BRL, INR, IDR, NGN…) em alguns países; escolha com cuidado, não pode ser alterada depois.',
          'Idioma da interface — inglês, português, espanhol, russo, indonésio, hindi, turco, árabe, tailandês, vietnamita e outros.',
          'Suporte — chat e e-mail nos principais idiomas; tempos de resposta semelhantes entre regiões.',
          'Condições de negociação — ativos, payouts, depósito mínimo ($5) e operação mínima ($1) são iguais em todos os países.',
        ] },
        { type: 'h2', id: 'check', text: 'Como verificar a disponibilidade no seu país' },
        { type: 'image', src: IMG_REGISTER, alt: 'Formulário de cadastro da Pocket Option com seleção de país', caption: 'O campo de país no cadastro lista apenas países aceitos.' },
        { type: 'ol', items: [
          'Abra a página de cadastro — se seu país não estiver na lista, é restrito.',
          'Crie uma conta demo gratuita: não exige depósito nem documentos.',
          'Vá em Finanças → Depósito para ver métodos e moedas oferecidos na sua região.',
          'Se mudar de país, avise o suporte; a conta pode ser atualizada após nova verificação.',
        ] },
        { type: 'tip', title: 'Viajando?', text: 'Operar em viagem por país restrito costuma ser tolerado por períodos curtos se sua residência cadastrada for aceita, mas depósitos e saques podem ser sinalizados. Mantenha os documentos da conta atualizados.' },
        { type: 'cta', text: 'Veja se a Pocket Option está disponível para você — abra uma conta demo gratuita em um minuto.', label: 'Abrir demo grátis' },
      ],
      faq: [
        { q: 'A Pocket Option está disponível nos EUA?', a: 'Não. Residentes dos Estados Unidos não podem abrir conta e não devem tentar se cadastrar por VPN.' },
        { q: 'A Pocket Option está disponível na Europa?', a: 'Não nos países da UE/EEE, Reino Unido ou Suíça. Está disponível em alguns países europeus fora da UE, como Turquia, Sérvia e Geórgia.' },
        { q: 'A Pocket Option aceita Brasil?', a: 'Sim. O Brasil é um dos maiores mercados, com Pix como método de pagamento local. As condições podem mudar — confira no cadastro.' },
        { q: 'Posso usar VPN para acessar a Pocket Option?', a: 'Usar VPN a partir de país restrito viola os termos. A verificação revelará sua residência real e a conta pode ser encerrada.' },
        { q: 'Quais países mais usam a Pocket Option?', a: 'Índia, Brasil, Indonésia, Nigéria, Paquistão, Bangladesh, México, Colômbia, África do Sul e Vietnã estão entre os maiores mercados.' },
        { q: 'Onde a Pocket Option é regulada?', a: 'A operadora tem licença da Mwali International Services Authority (MISA), nas Comores.' },
      ],
    },
    es: {
      title: 'Pocket Option: países disponibles',
      metaTitle: 'Países de Pocket Option: dónde está disponible y dónde está restringido (2026)',
      metaDescription:
        'Qué países acepta Pocket Option y cuáles están restringidos (EE. UU., UE, Reino Unido, Canadá, Australia…). Métodos de pago regionales, idiomas y qué pasa si operas desde un país prohibido.',
      excerpt:
        'Pocket Option atiende a traders en más de 90 países pero bloquea EE. UU., UE, Reino Unido y otros. Aquí el mapa de disponibilidad, pagos regionales y las reglas que debes conocer.',
      coverAlt: 'Estadísticas de Pocket Option: usuarios activos, volumen operado y más de 94 países y regiones',
      keyTakeaways: [
        'Pocket Option acepta clientes de la mayor parte de Asia, Latinoamérica, África, Oriente Medio y la CEI.',
        'Restringidos: EE. UU., países de la UE/EEE, Reino Unido, Canadá, Australia, Israel, Japón, Suiza y algunos más.',
        'Métodos locales (Pix, UPI, M-Pesa, QRIS, Mercado Pago…) y más de 15 idiomas de interfaz adaptados por región.',
        'Usar VPN para registrarse desde un país restringido viola los términos y puede acabar en cierre de cuenta sin pago.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option es un bróker global — según sus propias cifras atiende a traders de más de 90 países y regiones. Pero no está disponible en todas partes: como plataforma offshore de opciones binarias, no acepta residentes de jurisdicciones donde este producto está prohibido para minoristas. Esta guía enumera dónde está disponible pocketoption, dónde está restringido y qué cambia por región.' },
        { type: 'h2', id: 'available', text: 'Países donde Pocket Option está disponible' },
        { type: 'p', text: 'El registro está abierto en la mayor parte del mundo fuera de Norteamérica, Europa Occidental y Oceanía. Las mayores bases de usuarios están en estas regiones:' },
        { type: 'table', head: ['Región', 'Ejemplos de países aceptados', 'Pagos locales populares'], rows: [
          ['Sur y Sudeste Asiático', 'India, Indonesia, Pakistán, Bangladés, Vietnam, Tailandia, Filipinas, Malasia', 'UPI, QRIS, DANA, bKash, JazzCash, PromptPay, GCash'],
          ['Latinoamérica', 'Brasil, México, Colombia, Argentina, Perú, Chile', 'Pix, Mercado Pago, SPEI, PSE, Nequi'],
          ['África', 'Nigeria, Sudáfrica, Kenia, Ghana, Uganda, Egipto', 'M-Pesa, MTN Mobile Money, Airtel Money, transferencia bancaria'],
          ['Oriente Medio', 'EAU, Arabia Saudita, Turquía, Irak', 'Tarjetas, cripto, transferencia local'],
          ['CEI', 'Kazajistán, Uzbekistán, Kirguistán, Azerbaiyán, Armenia', 'Tarjetas, Kaspi, cripto'],
        ] },
        { type: 'image', src: IMG_STATS, alt: 'Cifras de Pocket Option: más de 99.000 usuarios activos, más de 94 países y regiones', caption: 'Cifras publicadas en la página oficial Sobre nosotros.' },
        { type: 'h2', id: 'restricted', text: 'Países restringidos' },
        { type: 'p', text: 'Pocket Option no abre cuentas a residentes de las siguientes jurisdicciones. La lista procede de los Términos y Condiciones de la plataforma y puede cambiar sin aviso:' },
        { type: 'ul', items: [
          'Estados Unidos y sus territorios',
          'Estados miembros de la UE/EEE (Alemania, Francia, España, Italia, Polonia, Países Bajos, Portugal…)',
          'Reino Unido',
          'Canadá',
          'Australia y Nueva Zelanda',
          'Israel, Japón, Suiza, Irán, Corea del Norte y otros territorios sancionados',
        ] },
        { type: 'p', text: 'Los residentes de estos países verán el mensaje “servicio no disponible en su región” al registrarse o deberán presentar comprobante de domicilio de un país aceptado durante la verificación.' },
        { type: 'warn', title: 'La VPN no es una solución', text: 'Registrarse con VPN desde un país restringido incumple los términos. La verificación exige pasaporte o DNI y comprobante de domicilio; una discrepancia lleva al cierre de la cuenta y la pérdida del saldo. No arriesgues tu dinero.' },
        { type: 'h2', id: 'regional', text: 'Qué cambia por región' },
        { type: 'ul', items: [
          'Métodos de pago — la página de depósito solo muestra las opciones de tu país; los métodos globales (tarjetas, cripto, Skrill, Neteller) están casi en todas partes.',
          'Moneda de la cuenta — USD por defecto, con monedas locales (BRL, INR, IDR, NGN…) en algunos países; elige con cuidado, no se puede cambiar después.',
          'Idioma de la interfaz — inglés, español, portugués, ruso, indonesio, hindi, turco, árabe, tailandés, vietnamita y más.',
          'Soporte — chat y correo en los idiomas principales; tiempos de respuesta similares entre regiones.',
          'Condiciones de trading — activos, pagos, depósito mínimo ($5) y operación mínima ($1) son iguales en todos los países.',
        ] },
        { type: 'h2', id: 'check', text: 'Cómo comprobar la disponibilidad en tu país' },
        { type: 'image', src: IMG_REGISTER, alt: 'Formulario de registro de Pocket Option con selección de país', caption: 'El campo de país del registro solo muestra países aceptados.' },
        { type: 'ol', items: [
          'Abre la página de registro — si tu país no aparece en la lista, está restringido.',
          'Crea una cuenta demo gratis: no requiere depósito ni documentos.',
          'Ve a Finanzas → Depósito para ver los métodos y monedas disponibles en tu región.',
          'Si te mudas a otro país, avisa a soporte; la cuenta puede actualizarse tras una nueva verificación.',
        ] },
        { type: 'tip', title: '¿De viaje?', text: 'Operar de viaje en un país restringido suele tolerarse por períodos cortos si tu residencia registrada está aceptada, pero depósitos y retiros pueden marcarse. Mantén tus documentos al día.' },
        { type: 'cta', text: 'Comprueba si Pocket Option está disponible para ti — abre una cuenta demo gratis en un minuto.', label: 'Abrir demo gratis' },
      ],
      faq: [
        { q: '¿Pocket Option está disponible en EE. UU.?', a: 'No. Los residentes de Estados Unidos no pueden abrir cuenta y no deberían intentar registrarse con VPN.' },
        { q: '¿Pocket Option está disponible en España o Europa?', a: 'No en países de la UE/EEE, Reino Unido ni Suiza. Sí en algunos países europeos fuera de la UE, como Turquía, Serbia y Georgia.' },
        { q: '¿Pocket Option acepta México, Colombia o Argentina?', a: 'Sí, la mayor parte de Latinoamérica está aceptada, con métodos locales como Mercado Pago, SPEI, PSE y Nequi. Las condiciones pueden cambiar — compruébalo al registrarte.' },
        { q: '¿Puedo usar VPN para acceder a Pocket Option?', a: 'Usar VPN desde un país restringido viola los términos. La verificación revelará tu residencia real y la cuenta puede cerrarse.' },
        { q: '¿Qué países usan más Pocket Option?', a: 'India, Brasil, Indonesia, Nigeria, Pakistán, Bangladés, México, Colombia, Sudáfrica y Vietnam están entre los mayores mercados.' },
        { q: '¿Dónde está regulado Pocket Option?', a: 'El operador tiene licencia de la Mwali International Services Authority (MISA) en las Comoras.' },
      ],
    },
    ru: {
      title: 'Pocket Option: в каких странах доступен',
      metaTitle: 'Страны Pocket Option: где доступен и где запрещён (2026)',
      metaDescription:
        'В каких странах Pocket Option принимает клиентов, а где запрещён (США, ЕС, Великобритания, Канада, Австралия…). Региональные способы оплаты, языки и что будет при торговле из запрещённой страны.',
      excerpt:
        'Pocket Option обслуживает трейдеров более чем в 90 странах, но блокирует США, ЕС, Великобританию и ряд других. Карта доступности, региональные платежи и правила, которые нужно знать.',
      coverAlt: 'Статистика Pocket Option: активные пользователи, торговый оборот и более 94 стран и регионов',
      keyTakeaways: [
        'Pocket Option принимает клиентов из большинства стран Азии, Латинской Америки, Африки, Ближнего Востока и СНГ.',
        'Запрещены: США, страны ЕС/ЕЭЗ, Великобритания, Канада, Австралия, Израиль, Япония, Швейцария и некоторые другие.',
        'Локальные способы оплаты (Pix, UPI, M-Pesa, Kaspi…) и 15+ языков интерфейса адаптированы под регионы.',
        'Регистрация через VPN из запрещённой страны нарушает условия и может привести к закрытию счёта без выплаты.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option — глобальный брокер: по собственным данным он обслуживает трейдеров более чем из 90 стран и регионов. Но доступен он не везде: как офшорная платформа бинарных опционов, он не принимает резидентов юрисдикций, где этот продукт запрещён для розничных клиентов. В этом руководстве — где pocketoption доступен, где ограничен и чем отличаются регионы.' },
        { type: 'h2', id: 'available', text: 'Страны, где Pocket Option доступен' },
        { type: 'p', text: 'Регистрация открыта для большей части мира за пределами Северной Америки, Западной Европы и Океании. Крупнейшие аудитории — в этих регионах:' },
        { type: 'table', head: ['Регион', 'Примеры принимаемых стран', 'Популярные локальные платежи'], rows: [
          ['Южная и Юго-Восточная Азия', 'Индия, Индонезия, Пакистан, Бангладеш, Вьетнам, Таиланд, Филиппины, Малайзия', 'UPI, QRIS, DANA, bKash, JazzCash, PromptPay, GCash'],
          ['Латинская Америка', 'Бразилия, Мексика, Колумбия, Аргентина, Перу, Чили', 'Pix, Mercado Pago, SPEI, PSE, Nequi'],
          ['Африка', 'Нигерия, ЮАР, Кения, Гана, Уганда, Египет', 'M-Pesa, MTN Mobile Money, Airtel Money, банковский перевод'],
          ['Ближний Восток', 'ОАЭ, Саудовская Аравия, Турция, Ирак', 'Карты, крипта, локальный банковский перевод'],
          ['СНГ', 'Казахстан, Узбекистан, Кыргызстан, Азербайджан, Армения', 'Карты, Kaspi, крипта'],
        ] },
        { type: 'image', src: IMG_STATS, alt: 'Цифры Pocket Option: более 99 000 активных пользователей, более 94 стран и регионов', caption: 'Данные с официальной страницы «О компании».' },
        { type: 'h2', id: 'restricted', text: 'Запрещённые страны' },
        { type: 'p', text: 'Pocket Option не открывает счета резидентам следующих юрисдикций. Список взят из Условий использования платформы и может меняться без уведомления:' },
        { type: 'ul', items: [
          'США и их территории',
          'Страны ЕС/ЕЭЗ (Германия, Франция, Испания, Италия, Польша, Нидерланды, Португалия…)',
          'Великобритания',
          'Канада',
          'Австралия и Новая Зеландия',
          'Израиль, Япония, Швейцария, Иран, Северная Корея и другие санкционные территории',
        ] },
        { type: 'p', text: 'Резиденты этих стран увидят сообщение «сервис недоступен в вашем регионе» при регистрации или получат запрос подтверждения адреса из разрешённой страны при верификации.' },
        { type: 'warn', title: 'VPN — не выход', text: 'Регистрация через VPN из запрещённой страны нарушает условия. Для верификации нужны паспорт и подтверждение адреса; несоответствие ведёт к закрытию счёта и потере баланса. Не рискуйте деньгами.' },
        { type: 'h2', id: 'regional', text: 'Чем отличаются регионы' },
        { type: 'ul', items: [
          'Способы оплаты — на странице пополнения показаны только варианты для вашей страны; глобальные методы (карты, крипта, Skrill, Neteller) доступны почти везде.',
          'Валюта счёта — по умолчанию USD, в некоторых странах доступны локальные валюты (BRL, INR, IDR, NGN…); выбирайте внимательно — изменить потом нельзя.',
          'Язык интерфейса — английский, русский, португальский, испанский, индонезийский, хинди, турецкий, арабский, тайский, вьетнамский и другие.',
          'Поддержка — чат и email на основных языках; время ответа примерно одинаковое во всех регионах.',
          'Торговые условия — активы, выплаты, минимальный депозит ($5) и минимальная сделка ($1) одинаковы во всех странах.',
        ] },
        { type: 'h2', id: 'check', text: 'Как проверить доступность в вашей стране' },
        { type: 'image', src: IMG_REGISTER, alt: 'Форма регистрации Pocket Option с выбором страны', caption: 'В поле «Страна» при регистрации перечислены только разрешённые страны.' },
        { type: 'ol', items: [
          'Откройте страницу регистрации — если вашей страны нет в списке, она ограничена.',
          'Создайте бесплатный демо-счёт: депозит и документы не нужны.',
          'Зайдите в Финансы → Пополнение, чтобы увидеть способы оплаты и валюты для вашего региона.',
          'При переезде в другую страну сообщите в поддержку; счёт обновят после повторной верификации.',
        ] },
        { type: 'tip', title: 'В поездке?', text: 'Торговля во время короткой поездки в запрещённую страну обычно допускается, если зарегистрированное место жительства разрешено, но депозиты и выводы могут попасть под проверку. Держите документы актуальными.' },
        { type: 'cta', text: 'Проверьте, доступен ли Pocket Option для вас — откройте бесплатный демо-счёт за минуту.', label: 'Открыть бесплатное демо' },
      ],
      faq: [
        { q: 'Доступен ли Pocket Option в США?', a: 'Нет. Резиденты США не могут открыть счёт, и пытаться регистрироваться через VPN не стоит.' },
        { q: 'Доступен ли Pocket Option в Европе?', a: 'Не в странах ЕС/ЕЭЗ, Великобритании и Швейцарии. Доступен в некоторых европейских странах вне ЕС — Турции, Сербии, Грузии.' },
        { q: 'Работает ли Pocket Option в России и Казахстане?', a: 'Доступность зависит от страны и может меняться; Казахстан и большинство стран СНГ принимаются. Проверьте список стран при регистрации.' },
        { q: 'Можно ли использовать VPN для доступа к Pocket Option?', a: 'Использование VPN из запрещённой страны нарушает условия. Верификация покажет реальное место жительства, и счёт могут закрыть.' },
        { q: 'В каких странах Pocket Option используют больше всего?', a: 'Индия, Бразилия, Индонезия, Нигерия, Пакистан, Бангладеш, Мексика, Колумбия, ЮАР и Вьетнам — среди крупнейших рынков.' },
        { q: 'Где регулируется Pocket Option?', a: 'Оператор имеет лицензию Mwali International Services Authority (MISA) на Коморских островах.' },
      ],
    },
    id: {
      title: 'Negara yang Didukung Pocket Option',
      metaTitle: 'Negara Pocket Option: Di Mana Tersedia dan Dibatasi (2026)',
      metaDescription:
        'Negara mana yang diterima Pocket Option dan mana yang dibatasi (AS, UE, Inggris, Kanada, Australia…). Metode pembayaran regional, bahasa, dan apa yang terjadi jika trading dari negara terlarang.',
      excerpt:
        'Pocket Option melayani trader di 90+ negara tetapi memblokir AS, UE, Inggris, dan beberapa lainnya. Ini peta ketersediaan, opsi pembayaran regional, dan aturan yang perlu Anda tahu.',
      coverAlt: 'Statistik Pocket Option: pengguna aktif, volume trading, dan 94+ negara dan wilayah',
      keyTakeaways: [
        'Pocket Option menerima klien dari sebagian besar Asia, Amerika Latin, Afrika, Timur Tengah, dan CIS.',
        'Dibatasi: AS, negara UE/EEA, Inggris, Kanada, Australia, Israel, Jepang, Swiss, dan beberapa lainnya.',
        'Metode pembayaran lokal (QRIS, DANA, OVO, UPI, Pix, M-Pesa…) dan 15+ bahasa antarmuka disesuaikan per wilayah.',
        'Memakai VPN untuk mendaftar dari negara terlarang melanggar ketentuan dan bisa berujung penutupan akun tanpa pembayaran.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option adalah broker global — menurut datanya sendiri melayani trader dari lebih dari 90 negara dan wilayah. Tetapi tidak tersedia di mana-mana: sebagai platform offshore yang menawarkan opsi biner, ia tidak menerima penduduk yurisdiksi yang melarang produk ini untuk klien ritel. Panduan ini merinci di mana pocketoption tersedia, di mana dibatasi, dan apa yang berbeda per wilayah.' },
        { type: 'h2', id: 'available', text: 'Negara tempat Pocket Option tersedia' },
        { type: 'p', text: 'Pendaftaran terbuka untuk sebagian besar dunia di luar Amerika Utara, Eropa Barat, dan Oseania. Basis pengguna terbesar ada di wilayah berikut:' },
        { type: 'table', head: ['Wilayah', 'Contoh negara yang diterima', 'Pembayaran lokal populer'], rows: [
          ['Asia Selatan & Tenggara', 'Indonesia, India, Pakistan, Bangladesh, Vietnam, Thailand, Filipina, Malaysia', 'QRIS, DANA, OVO, UPI, bKash, JazzCash, PromptPay, GCash'],
          ['Amerika Latin', 'Brasil, Meksiko, Kolombia, Argentina, Peru, Chili', 'Pix, Mercado Pago, SPEI, PSE, Nequi'],
          ['Afrika', 'Nigeria, Afrika Selatan, Kenya, Ghana, Uganda, Mesir', 'M-Pesa, MTN Mobile Money, Airtel Money, transfer bank'],
          ['Timur Tengah', 'UEA, Arab Saudi, Turki, Irak', 'Kartu, kripto, transfer bank lokal'],
          ['CIS', 'Kazakhstan, Uzbekistan, Kirgistan, Azerbaijan, Armenia', 'Kartu, Kaspi, kripto'],
        ] },
        { type: 'image', src: IMG_STATS, alt: 'Angka perusahaan Pocket Option: 99.000+ pengguna aktif, 94+ negara dan wilayah', caption: 'Angka yang dipublikasikan di halaman resmi Tentang Kami.' },
        { type: 'h2', id: 'restricted', text: 'Negara yang dibatasi' },
        { type: 'p', text: 'Pocket Option tidak membuka akun untuk penduduk yurisdiksi berikut. Daftar ini berasal dari Syarat & Ketentuan platform dan dapat berubah tanpa pemberitahuan:' },
        { type: 'ul', items: [
          'Amerika Serikat dan wilayahnya',
          'Negara anggota UE/EEA (Jerman, Prancis, Spanyol, Italia, Polandia, Belanda, Portugal…)',
          'Inggris Raya',
          'Kanada',
          'Australia dan Selandia Baru',
          'Israel, Jepang, Swiss, Iran, Korea Utara, dan wilayah tersanksi lainnya',
        ] },
        { type: 'p', text: 'Penduduk negara-negara ini akan melihat pesan “layanan tidak tersedia di wilayah Anda” saat mendaftar atau diminta bukti alamat dari negara yang diterima saat verifikasi.' },
        { type: 'warn', title: 'VPN bukan solusi', text: 'Mendaftar lewat VPN dari negara terlarang melanggar ketentuan. Verifikasi membutuhkan paspor/KTP dan bukti alamat; ketidakcocokan berujung penutupan akun dan hangusnya saldo. Jangan pertaruhkan uang Anda.' },
        { type: 'h2', id: 'regional', text: 'Apa yang berbeda per wilayah' },
        { type: 'ul', items: [
          'Metode pembayaran — halaman deposit hanya menampilkan opsi untuk negara Anda; metode global (kartu, kripto, Skrill, Neteller) tersedia hampir di mana saja.',
          'Mata uang akun — USD secara default, dengan mata uang lokal (IDR, BRL, INR, NGN…) di beberapa negara; pilih dengan hati-hati, tidak bisa diubah nanti.',
          'Bahasa antarmuka — Inggris, Indonesia, Portugis, Spanyol, Rusia, Hindi, Turki, Arab, Thai, Vietnam, dan lainnya.',
          'Dukungan — chat dan email dalam bahasa utama; waktu respons serupa di semua wilayah.',
          'Kondisi trading — aset, payout, deposit minimum ($5), dan trade minimum ($1) sama di semua negara.',
        ] },
        { type: 'h2', id: 'check', text: 'Cara mengecek ketersediaan di negara Anda' },
        { type: 'image', src: IMG_REGISTER, alt: 'Formulir pendaftaran Pocket Option dengan pilihan negara', caption: 'Kolom negara di formulir pendaftaran hanya menampilkan negara yang diterima.' },
        { type: 'ol', items: [
          'Buka halaman pendaftaran — jika negara Anda tidak ada di daftar, berarti dibatasi.',
          'Buat akun demo gratis: tidak perlu deposit atau dokumen.',
          'Masuk ke Keuangan → Deposit untuk melihat metode pembayaran dan mata uang yang ditawarkan di wilayah Anda.',
          'Jika pindah negara, beri tahu dukungan; akun dapat diperbarui setelah verifikasi ulang.',
        ] },
        { type: 'tip', title: 'Sedang bepergian?', text: 'Trading saat bepergian singkat di negara terlarang umumnya ditoleransi jika domisili terdaftar Anda diterima, tetapi deposit dan penarikan bisa ditandai. Jaga dokumen akun tetap terkini.' },
        { type: 'cta', text: 'Cek apakah Pocket Option tersedia untuk Anda — buka akun demo gratis dalam satu menit.', label: 'Buka demo gratis' },
      ],
      faq: [
        { q: 'Apakah Pocket Option tersedia di Indonesia?', a: 'Ya, Indonesia termasuk pasar terbesar, dengan metode lokal seperti QRIS, DANA, dan OVO. Ketentuan dapat berubah — cek saat mendaftar.' },
        { q: 'Apakah Pocket Option tersedia di AS?', a: 'Tidak. Penduduk Amerika Serikat tidak bisa membuka akun dan sebaiknya tidak mencoba mendaftar lewat VPN.' },
        { q: 'Apakah Pocket Option tersedia di Eropa?', a: 'Tidak di negara UE/EEA, Inggris, atau Swiss. Tersedia di beberapa negara Eropa non-UE seperti Turki, Serbia, dan Georgia.' },
        { q: 'Bolehkah memakai VPN untuk mengakses Pocket Option?', a: 'Memakai VPN dari negara terlarang melanggar ketentuan. Verifikasi akan mengungkap domisili asli Anda dan akun bisa ditutup.' },
        { q: 'Negara mana yang paling banyak memakai Pocket Option?', a: 'India, Brasil, Indonesia, Nigeria, Pakistan, Bangladesh, Meksiko, Kolombia, Afrika Selatan, dan Vietnam termasuk pasar terbesar.' },
        { q: 'Di mana Pocket Option diregulasi?', a: 'Operatornya memegang lisensi dari Mwali International Services Authority (MISA) di Komoro.' },
      ],
    },
  },
};
