import type { BlogPost } from '../types';

const IMG_TERMINAL = '/images/quick-start/1_1.webp';
const IMG_TRADE = '/images/quick-start/3_2.webp';

export const pocketOptionMobileApp: BlogPost = {
  slug: 'pocket-option-mobile-app',
  category: 'platform',
  cover: '/images/blog/pocket-option-mobile-app.webp',
  publishedAt: '2026-10-01',
  updatedAt: '2026-10-01',
  readingMinutes: 7,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option mobile app: how to download it on Android and iOS, features and trading from your phone',
      metaTitle: 'Pocket Option app for Android and iOS: download, install and trade from your phone',
      metaDescription:
        'Pocket Option mobile app guide: how to download the Android APK or iOS app, log in, use the mobile terminal, demo account, deposits and withdrawals on the phone, notifications and the differences from the web platform.',
      excerpt:
        'The pocketoption app puts the full terminal in your pocket. Here is how to install it on Android and iPhone, what it can do, how it differs from the web version and how to trade safely on a small screen.',
      coverAlt: 'Hand holding a smartphone with the Pocket Option trading app open',
      keyTakeaways: [
        'The Pocket Option app is free for Android (Google Play or APK from the official site) and iOS (App Store); a web version also works in the mobile browser.',
        'Demo and real accounts, 100+ assets, indicators, deposits and withdrawals are all available from the phone.',
        'Always download from the official site or the official stores — fake “Pocket Option” apps exist.',
        'On a small screen, keep it simple: one asset, one indicator, 3–5 minute expirations and the same 1–2% position size.',
      ],
      blocks: [
        { type: 'p', text: 'Most Pocket Option traders open their first trade on a phone. The mobile app gives access to the same account, balance, assets and payouts as the web terminal, adds push notifications and works over mobile data. This guide explains how to download the pocketoption app on Android and iOS, what the mobile terminal looks like and how to keep trading disciplined when the platform is always in your pocket.' },
        { type: 'h2', id: 'versions', text: 'Which versions of the Pocket Option app exist' },
        { type: 'table', head: ['Platform', 'How to get it', 'Notes'], rows: [
          ['Android', 'Google Play or APK from the official website', 'Android 5.0+; the APK is the fallback where Play is not available'],
          ['iOS (iPhone / iPad)', 'App Store', 'Search “Pocket Option Broker”; iOS 12+'],
          ['Mobile browser', 'Open pocketoption.com and log in', 'Full terminal without installing; works on any phone'],
          ['Windows / macOS', 'Desktop app from the official website', 'Same account, larger charts'],
        ] },
        { type: 'warn', title: 'Only official sources', text: 'Third-party stores host modified “Pocket Option” APKs that steal logins. Download only from Google Play, the App Store or the download page inside your account on the official site.' },
        { type: 'h2', id: 'install', text: 'How to download and install the app' },
        { type: 'ol', items: [
          'Android: open Google Play, search for Pocket Option and tap Install. If Play is unavailable in your region, log in to your account in the browser, open the “Apps” section and download the APK; allow installation from this source when prompted.',
          'iOS: open the App Store, search for Pocket Option and tap Get. Confirm with Face ID or your Apple ID.',
          'Open the app and log in with the same email and password as the website, or register a new account directly in the app.',
          'Allow notifications if you want alerts about closed trades, deposits and tournaments.',
          'Switch to the demo account from the balance menu to explore without risk.',
        ] },
        { type: 'h2', id: 'terminal', text: 'The mobile terminal: what is where' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Pocket Option mobile terminal with chart and trade buttons', caption: 'Chart on top, trade controls at the bottom — the mobile layout of the Pocket Option terminal.' },
        { type: 'ul', items: [
          'Top bar — asset name with payout; tap it to open the asset list and search.',
          'Chart — pinch to zoom, swipe to scroll; tap the chart icon to switch candles/line and the timeframe.',
          'Indicators and drawing tools — the tools icon at the edge of the chart; the same set as on the web.',
          'Trade panel — expiration time, amount and the Up / Down buttons at the bottom of the screen.',
          'Menu — balance switch (demo / real), Finance (deposit, withdrawal, history), profile, support chat, tournaments and social trading.',
        ] },
        { type: 'h2', id: 'trade', text: 'Placing a trade from the phone' },
        { type: 'image', src: IMG_TRADE, alt: 'Confirming an Up trade in the Pocket Option app', caption: 'Set time and amount, then tap Up or Down.' },
        { type: 'p', text: 'Choose the asset, set the expiration (3–5 minutes is a comfortable minimum on a small screen), enter the amount — minimum $1 — and tap Up or Down. The open trade appears on the chart with a countdown; the result is shown as soon as it closes. Everything happens on the same account as the web version, so a trade opened on the phone can be watched on the desktop and vice versa.' },
        { type: 'tip', title: 'Landscape mode for charts', text: 'Rotate the phone for a wider chart when analysing, then back to portrait to trade. It is the closest a phone gets to a desktop view.' },
        { type: 'h2', id: 'finance', text: 'Deposits, withdrawals and verification in the app' },
        { type: 'p', text: 'The Finance section of the app offers the same payment methods as the website: cards, crypto, e-wallets and local methods, with the same $5 minimum deposit and $10 minimum withdrawal. Verification is often easier on the phone — you photograph your ID and proof of address with the camera and upload them directly from the Profile section. Withdrawals are requested and tracked in Finance → Transaction history exactly as on the web.' },
        { type: 'h2', id: 'web-vs-app', text: 'App vs web version: what is different' },
        { type: 'table', head: ['Feature', 'Mobile app', 'Web terminal'], rows: [
          ['Account, balance, assets, payouts', 'Same', 'Same'],
          ['Indicators and drawing tools', 'Full set, smaller workspace', 'Full set, several charts at once'],
          ['Push notifications', 'Yes', 'Browser notifications only'],
          ['Biometric login', 'Face ID / fingerprint', 'Password + 2FA'],
          ['Multiple charts on one screen', 'No', 'Yes'],
          ['Data usage', 'Low, optimised for mobile', 'Higher'],
        ] },
        { type: 'h2', id: 'tips', text: 'Trading discipline on a small screen' },
        { type: 'ul', items: [
          'Keep the position size at 1–2% of the balance — the phone makes it easy to tap “+” a few times too many.',
          'Enable biometric login and 2FA, and never trade on public Wi-Fi without a VPN.',
          'Avoid 5-second trades on mobile; a delayed tap or a network hiccup matters more at that speed.',
          'Do not trade while walking or in transit. Notifications can tell you a trade closed; they should not tempt you to open the next one immediately.',
          'Use the same journal as on desktop — the trade history in the app is exportable to your notes.',
        ] },
        { type: 'warn', title: 'Risk warning', text: 'Trading on the Pocket Option app carries the same risk as on the web: you can lose the deposited funds. Convenience is not a strategy — follow your rules on every device.' },
        { type: 'cta', text: 'Register on Pocket Option, download the app from your account and start with the free $50,000 demo on your phone.', label: 'Open Pocket Option account' },
      ],
      faq: [
        { q: 'Is the Pocket Option app free?', a: 'Yes. The app for Android and iOS is free to download, and there are no subscription fees. You only fund your own trading balance.' },
        { q: 'How do I download the Pocket Option APK?', a: 'Log in to your account on the official website, open the Apps or Download section and save the APK to your Android phone. Allow installation from that source when the system asks. Do not use APKs from third-party sites.' },
        { q: 'Is there a Pocket Option app for iPhone?', a: 'Yes, it is available in the App Store. If the app is not shown in your region, the web terminal works fully in Safari on iPhone and iPad.' },
        { q: 'Can I use the demo account in the app?', a: 'Yes. Switch to the demo account from the balance menu; it has the same $50,000 virtual balance as on the web.' },
        { q: 'Can I deposit and withdraw from the app?', a: 'Yes. The Finance section offers the same payment methods, the $5 minimum deposit and the $10 minimum withdrawal as the website.' },
        { q: 'Are quotes and payouts the same in the app and on the web?', a: 'Yes. The app connects to the same account and price feed, so assets, quotes and payouts are identical.' },
      ],
    },
    pt: {
      title: 'App Pocket Option: como baixar no Android e iOS, recursos e como operar pelo celular',
      metaTitle: 'App Pocket Option para Android e iOS: baixar, instalar e operar pelo celular',
      metaDescription:
        'Guia do app Pocket Option: como baixar o APK Android ou o app iOS, fazer login, usar o terminal mobile, conta demo, depósitos e saques pelo celular, notificações e diferenças para a versão web.',
      excerpt:
        'O app pocketoption coloca o terminal completo no seu bolso. Veja como instalar no Android e iPhone, o que ele faz, como difere da versão web e como operar com segurança em uma tela pequena.',
      coverAlt: 'Mão segurando um smartphone com o app de trading da Pocket Option aberto',
      keyTakeaways: [
        'O app Pocket Option é gratuito para Android (Google Play ou APK do site oficial) e iOS (App Store); a versão web também funciona no navegador do celular.',
        'Conta demo e real, 100+ ativos, indicadores, depósitos e saques estão todos disponíveis pelo celular.',
        'Baixe sempre do site oficial ou das lojas oficiais — existem apps “Pocket Option” falsos.',
        'Em tela pequena, simplifique: um ativo, um indicador, expirações de 3–5 minutos e o mesmo tamanho de posição de 1–2%.',
      ],
      blocks: [
        { type: 'p', text: 'A maioria dos traders da Pocket Option abre a primeira operação pelo celular. O app dá acesso à mesma conta, saldo, ativos e payouts do terminal web, adiciona notificações push e funciona com dados móveis. Este guia explica como baixar o app pocketoption no Android e iOS, como é o terminal mobile e como manter a disciplina quando a plataforma está sempre no seu bolso.' },
        { type: 'h2', id: 'versions', text: 'Quais versões do app Pocket Option existem' },
        { type: 'table', head: ['Plataforma', 'Como obter', 'Observações'], rows: [
          ['Android', 'Google Play ou APK do site oficial', 'Android 5.0+; o APK é a alternativa onde a Play não está disponível'],
          ['iOS (iPhone / iPad)', 'App Store', 'Busque “Pocket Option Broker”; iOS 12+'],
          ['Navegador mobile', 'Abra pocketoption.com e faça login', 'Terminal completo sem instalar; funciona em qualquer celular'],
          ['Windows / macOS', 'App desktop do site oficial', 'Mesma conta, gráficos maiores'],
        ] },
        { type: 'warn', title: 'Apenas fontes oficiais', text: 'Lojas de terceiros hospedam APKs “Pocket Option” modificados que roubam logins. Baixe apenas do Google Play, da App Store ou da página de download dentro da sua conta no site oficial.' },
        { type: 'h2', id: 'install', text: 'Como baixar e instalar o app' },
        { type: 'ol', items: [
          'Android: abra o Google Play, busque Pocket Option e toque em Instalar. Se a Play não estiver disponível na sua região, entre na conta pelo navegador, abra a seção “Apps” e baixe o APK; permita a instalação dessa fonte quando solicitado.',
          'iOS: abra a App Store, busque Pocket Option e toque em Obter. Confirme com Face ID ou Apple ID.',
          'Abra o app e faça login com o mesmo e-mail e senha do site, ou cadastre uma nova conta direto no app.',
          'Permita notificações se quiser alertas de operações fechadas, depósitos e torneios.',
          'Mude para a conta demo no menu de saldo para explorar sem risco.',
        ] },
        { type: 'h2', id: 'terminal', text: 'O terminal mobile: o que fica onde' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal mobile da Pocket Option com gráfico e botões de operação', caption: 'Gráfico em cima, controles de operação embaixo — o layout mobile do terminal Pocket Option.' },
        { type: 'ul', items: [
          'Barra superior — nome do ativo com payout; toque para abrir a lista de ativos e buscar.',
          'Gráfico — pince para zoom, arraste para rolar; toque no ícone de gráfico para alternar candles/linha e o timeframe.',
          'Indicadores e ferramentas de desenho — ícone de ferramentas na borda do gráfico; mesmo conjunto da web.',
          'Painel de operação — tempo de expiração, valor e botões Para cima / Para baixo na parte inferior.',
          'Menu — troca de saldo (demo / real), Finanças (depósito, saque, histórico), perfil, chat de suporte, torneios e social trading.',
        ] },
        { type: 'h2', id: 'trade', text: 'Abrindo uma operação pelo celular' },
        { type: 'image', src: IMG_TRADE, alt: 'Confirmando uma operação Para cima no app Pocket Option', caption: 'Defina tempo e valor, depois toque em Para cima ou Para baixo.' },
        { type: 'p', text: 'Escolha o ativo, defina a expiração (3–5 minutos é um mínimo confortável em tela pequena), digite o valor — mínimo $1 — e toque em Para cima ou Para baixo. A operação aberta aparece no gráfico com contagem regressiva; o resultado é exibido assim que fecha. Tudo acontece na mesma conta da versão web, então uma operação aberta no celular pode ser acompanhada no desktop e vice-versa.' },
        { type: 'tip', title: 'Modo paisagem para gráficos', text: 'Gire o celular para um gráfico mais largo ao analisar, depois volte ao retrato para operar. É o mais perto que um celular chega da visão desktop.' },
        { type: 'h2', id: 'finance', text: 'Depósitos, saques e verificação no app' },
        { type: 'p', text: 'A seção Finanças do app oferece os mesmos métodos de pagamento do site: cartões, cripto, carteiras e métodos locais, com o mesmo depósito mínimo de $5 e saque mínimo de $10. A verificação costuma ser mais fácil no celular — você fotografa o documento e o comprovante de endereço com a câmera e envia direto pela seção Perfil. Saques são solicitados e acompanhados em Finanças → Histórico exatamente como na web.' },
        { type: 'h2', id: 'web-vs-app', text: 'App vs versão web: o que muda' },
        { type: 'table', head: ['Recurso', 'App mobile', 'Terminal web'], rows: [
          ['Conta, saldo, ativos, payouts', 'Iguais', 'Iguais'],
          ['Indicadores e ferramentas de desenho', 'Conjunto completo, espaço menor', 'Conjunto completo, vários gráficos ao mesmo tempo'],
          ['Notificações push', 'Sim', 'Apenas notificações do navegador'],
          ['Login biométrico', 'Face ID / digital', 'Senha + 2FA'],
          ['Vários gráficos em uma tela', 'Não', 'Sim'],
          ['Uso de dados', 'Baixo, otimizado para mobile', 'Maior'],
        ] },
        { type: 'h2', id: 'tips', text: 'Disciplina de trading em tela pequena' },
        { type: 'ul', items: [
          'Mantenha o tamanho da posição em 1–2% do saldo — no celular é fácil tocar “+” algumas vezes a mais.',
          'Ative login biométrico e 2FA, e nunca opere em Wi-Fi público sem VPN.',
          'Evite operações de 5 segundos no mobile; um toque atrasado ou uma oscilação de rede pesam mais nessa velocidade.',
          'Não opere andando ou em trânsito. As notificações podem avisar que uma operação fechou; não devem tentá-lo a abrir a próxima imediatamente.',
          'Use o mesmo diário do desktop — o histórico de operações do app pode ser copiado para suas anotações.',
        ] },
        { type: 'warn', title: 'Aviso de risco', text: 'Operar no app Pocket Option tem o mesmo risco da web: você pode perder os fundos depositados. Conveniência não é estratégia — siga suas regras em qualquer dispositivo.' },
        { type: 'cta', text: 'Cadastre-se na Pocket Option, baixe o app pela sua conta e comece com a demo gratuita de $50.000 no celular.', label: 'Abrir conta Pocket Option' },
      ],
      faq: [
        { q: 'O app Pocket Option é gratuito?', a: 'Sim. O app para Android e iOS é gratuito para baixar e não há assinaturas. Você só financia o seu próprio saldo de negociação.' },
        { q: 'Como baixo o APK da Pocket Option?', a: 'Entre na sua conta no site oficial, abra a seção Apps ou Download e salve o APK no celular Android. Permita a instalação dessa fonte quando o sistema pedir. Não use APKs de sites de terceiros.' },
        { q: 'Existe app Pocket Option para iPhone?', a: 'Sim, está disponível na App Store. Se o app não aparecer na sua região, o terminal web funciona totalmente no Safari em iPhone e iPad.' },
        { q: 'Posso usar a conta demo no app?', a: 'Sim. Mude para a conta demo no menu de saldo; ela tem o mesmo saldo virtual de $50.000 da web.' },
        { q: 'Posso depositar e sacar pelo app?', a: 'Sim. A seção Finanças oferece os mesmos métodos de pagamento, depósito mínimo de $5 e saque mínimo de $10 do site.' },
        { q: 'As cotações e payouts são iguais no app e na web?', a: 'Sim. O app se conecta à mesma conta e ao mesmo feed de preços, então ativos, cotações e payouts são idênticos.' },
      ],
    },
    es: {
      title: 'App de Pocket Option: cómo descargarla en Android e iOS, funciones y operar desde el móvil',
      metaTitle: 'App Pocket Option para Android e iOS: descargar, instalar y operar desde el móvil',
      metaDescription:
        'Guía de la app de Pocket Option: cómo descargar el APK de Android o la app de iOS, iniciar sesión, usar el terminal móvil, cuenta demo, depósitos y retiros desde el móvil, notificaciones y diferencias con la versión web.',
      excerpt:
        'La app pocketoption pone el terminal completo en tu bolsillo. Así se instala en Android e iPhone, qué puede hacer, en qué se diferencia de la versión web y cómo operar con seguridad en una pantalla pequeña.',
      coverAlt: 'Mano sosteniendo un smartphone con la app de trading de Pocket Option abierta',
      keyTakeaways: [
        'La app de Pocket Option es gratuita para Android (Google Play o APK desde el sitio oficial) e iOS (App Store); la versión web también funciona en el navegador del móvil.',
        'Cuentas demo y real, 100+ activos, indicadores, depósitos y retiros están disponibles desde el móvil.',
        'Descarga siempre desde el sitio oficial o las tiendas oficiales — existen apps “Pocket Option” falsas.',
        'En pantalla pequeña, simplifica: un activo, un indicador, expiraciones de 3–5 minutos y el mismo tamaño de posición del 1–2%.',
      ],
      blocks: [
        { type: 'p', text: 'La mayoría de traders de Pocket Option abre su primera operación desde el móvil. La app da acceso a la misma cuenta, saldo, activos y pagos que el terminal web, añade notificaciones push y funciona con datos móviles. Esta guía explica cómo descargar la app pocketoption en Android e iOS, cómo es el terminal móvil y cómo mantener la disciplina cuando la plataforma está siempre en tu bolsillo.' },
        { type: 'h2', id: 'versions', text: 'Qué versiones de la app de Pocket Option existen' },
        { type: 'table', head: ['Plataforma', 'Cómo obtenerla', 'Notas'], rows: [
          ['Android', 'Google Play o APK desde el sitio oficial', 'Android 5.0+; el APK es la alternativa donde Play no está disponible'],
          ['iOS (iPhone / iPad)', 'App Store', 'Busca “Pocket Option Broker”; iOS 12+'],
          ['Navegador móvil', 'Abre pocketoption.com e inicia sesión', 'Terminal completo sin instalar; funciona en cualquier móvil'],
          ['Windows / macOS', 'App de escritorio desde el sitio oficial', 'Misma cuenta, gráficos más grandes'],
        ] },
        { type: 'warn', title: 'Solo fuentes oficiales', text: 'Las tiendas de terceros alojan APKs “Pocket Option” modificados que roban credenciales. Descarga solo desde Google Play, la App Store o la página de descarga dentro de tu cuenta en el sitio oficial.' },
        { type: 'h2', id: 'install', text: 'Cómo descargar e instalar la app' },
        { type: 'ol', items: [
          'Android: abre Google Play, busca Pocket Option y pulsa Instalar. Si Play no está disponible en tu región, inicia sesión en tu cuenta desde el navegador, abre la sección “Apps” y descarga el APK; permite la instalación desde esa fuente cuando se te pida.',
          'iOS: abre la App Store, busca Pocket Option y pulsa Obtener. Confirma con Face ID o tu Apple ID.',
          'Abre la app e inicia sesión con el mismo correo y contraseña que en la web, o regístrate directamente en la app.',
          'Permite las notificaciones si quieres avisos de operaciones cerradas, depósitos y torneos.',
          'Cambia a la cuenta demo desde el menú de saldo para explorar sin riesgo.',
        ] },
        { type: 'h2', id: 'terminal', text: 'El terminal móvil: qué hay en cada sitio' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal móvil de Pocket Option con gráfico y botones de operación', caption: 'Gráfico arriba, controles de operación abajo — el diseño móvil del terminal de Pocket Option.' },
        { type: 'ul', items: [
          'Barra superior — nombre del activo con el pago; tócalo para abrir la lista de activos y buscar.',
          'Gráfico — pellizca para hacer zoom, desliza para desplazarte; toca el icono de gráfico para cambiar velas/línea y el marco temporal.',
          'Indicadores y herramientas de dibujo — el icono de herramientas en el borde del gráfico; el mismo conjunto que en la web.',
          'Panel de operación — tiempo de expiración, importe y los botones Arriba / Abajo en la parte inferior.',
          'Menú — cambio de saldo (demo / real), Finanzas (depósito, retiro, historial), perfil, chat de soporte, torneos y social trading.',
        ] },
        { type: 'h2', id: 'trade', text: 'Abrir una operación desde el móvil' },
        { type: 'image', src: IMG_TRADE, alt: 'Confirmando una operación Arriba en la app de Pocket Option', caption: 'Fija tiempo e importe y luego pulsa Arriba o Abajo.' },
        { type: 'p', text: 'Elige el activo, fija la expiración (3–5 minutos es un mínimo cómodo en pantalla pequeña), introduce el importe — mínimo $1 — y pulsa Arriba o Abajo. La operación abierta aparece en el gráfico con una cuenta atrás; el resultado se muestra al cerrar. Todo ocurre en la misma cuenta que la versión web, así que una operación abierta en el móvil puede seguirse en el escritorio y viceversa.' },
        { type: 'tip', title: 'Modo horizontal para los gráficos', text: 'Gira el móvil para un gráfico más ancho al analizar y vuelve a vertical para operar. Es lo más cerca que un móvil llega a una vista de escritorio.' },
        { type: 'h2', id: 'finance', text: 'Depósitos, retiros y verificación en la app' },
        { type: 'p', text: 'La sección Finanzas de la app ofrece los mismos métodos de pago que la web: tarjetas, cripto, monederos y métodos locales, con el mismo depósito mínimo de $5 y retiro mínimo de $10. La verificación suele ser más fácil en el móvil — fotografías tu documento y el comprobante de domicilio con la cámara y los subes directamente desde la sección Perfil. Los retiros se solicitan y siguen en Finanzas → Historial exactamente como en la web.' },
        { type: 'h2', id: 'web-vs-app', text: 'App vs versión web: qué cambia' },
        { type: 'table', head: ['Característica', 'App móvil', 'Terminal web'], rows: [
          ['Cuenta, saldo, activos, pagos', 'Iguales', 'Iguales'],
          ['Indicadores y herramientas de dibujo', 'Conjunto completo, espacio menor', 'Conjunto completo, varios gráficos a la vez'],
          ['Notificaciones push', 'Sí', 'Solo notificaciones del navegador'],
          ['Inicio de sesión biométrico', 'Face ID / huella', 'Contraseña + 2FA'],
          ['Varios gráficos en una pantalla', 'No', 'Sí'],
          ['Uso de datos', 'Bajo, optimizado para móvil', 'Mayor'],
        ] },
        { type: 'h2', id: 'tips', text: 'Disciplina de trading en pantalla pequeña' },
        { type: 'ul', items: [
          'Mantén el tamaño de posición en el 1–2% del saldo — en el móvil es fácil pulsar “+” unas veces de más.',
          'Activa el inicio de sesión biométrico y el 2FA, y nunca operes en Wi-Fi público sin VPN.',
          'Evita operaciones de 5 segundos en el móvil; un toque tardío o un corte de red pesan más a esa velocidad.',
          'No operes caminando ni en transporte. Las notificaciones pueden avisarte de que una operación cerró; no deben tentarte a abrir la siguiente de inmediato.',
          'Usa el mismo diario que en el escritorio — el historial de operaciones de la app puede copiarse a tus notas.',
        ] },
        { type: 'warn', title: 'Aviso de riesgo', text: 'Operar en la app de Pocket Option conlleva el mismo riesgo que en la web: puedes perder los fondos depositados. La comodidad no es una estrategia — sigue tus reglas en cualquier dispositivo.' },
        { type: 'cta', text: 'Regístrate en Pocket Option, descarga la app desde tu cuenta y empieza con la demo gratuita de $50.000 en tu móvil.', label: 'Abrir cuenta Pocket Option' },
      ],
      faq: [
        { q: '¿La app de Pocket Option es gratuita?', a: 'Sí. La app para Android e iOS se descarga gratis y no hay cuotas de suscripción. Solo fondeas tu propio saldo de trading.' },
        { q: '¿Cómo descargo el APK de Pocket Option?', a: 'Inicia sesión en tu cuenta en el sitio oficial, abre la sección Apps o Descargas y guarda el APK en tu móvil Android. Permite la instalación desde esa fuente cuando el sistema lo pida. No uses APKs de sitios de terceros.' },
        { q: '¿Hay app de Pocket Option para iPhone?', a: 'Sí, está disponible en la App Store. Si la app no aparece en tu región, el terminal web funciona por completo en Safari en iPhone e iPad.' },
        { q: '¿Puedo usar la cuenta demo en la app?', a: 'Sí. Cambia a la cuenta demo desde el menú de saldo; tiene el mismo saldo virtual de $50.000 que en la web.' },
        { q: '¿Puedo depositar y retirar desde la app?', a: 'Sí. La sección Finanzas ofrece los mismos métodos de pago, el depósito mínimo de $5 y el retiro mínimo de $10 que el sitio web.' },
        { q: '¿Las cotizaciones y pagos son iguales en la app y en la web?', a: 'Sí. La app se conecta a la misma cuenta y al mismo feed de precios, así que activos, cotizaciones y pagos son idénticos.' },
      ],
    },
    ru: {
      title: 'Мобильное приложение Pocket Option: как скачать на Android и iOS, функции и торговля с телефона',
      metaTitle: 'Приложение Pocket Option для Android и iOS: скачать, установить и торговать с телефона',
      metaDescription:
        'Руководство по приложению Pocket Option: как скачать APK для Android или приложение для iOS, войти, пользоваться мобильным терминалом, демо-счётом, пополнять и выводить с телефона, уведомления и отличия от веб-версии.',
      excerpt:
        'Приложение pocketoption помещает полный терминал в карман. Как установить его на Android и iPhone, что оно умеет, чем отличается от веб-версии и как безопасно торговать на маленьком экране.',
      coverAlt: 'Рука держит смартфон с открытым торговым приложением Pocket Option',
      keyTakeaways: [
        'Приложение Pocket Option бесплатно для Android (Google Play или APK с официального сайта) и iOS (App Store); веб-версия также работает в мобильном браузере.',
        'Демо- и реальный счёт, 100+ активов, индикаторы, пополнение и вывод — всё доступно с телефона.',
        'Скачивайте только с официального сайта или из официальных магазинов — существуют поддельные приложения «Pocket Option».',
        'На маленьком экране упрощайте: один актив, один индикатор, экспирации 3–5 минут и тот же размер позиции 1–2%.',
      ],
      blocks: [
        { type: 'p', text: 'Большинство трейдеров Pocket Option открывают первую сделку с телефона. Мобильное приложение даёт доступ к тому же счёту, балансу, активам и выплатам, что и веб-терминал, добавляет push-уведомления и работает через мобильный интернет. В этом руководстве — как скачать приложение pocketoption на Android и iOS, как выглядит мобильный терминал и как сохранять дисциплину, когда платформа всегда в кармане.' },
        { type: 'h2', id: 'versions', text: 'Какие версии приложения Pocket Option существуют' },
        { type: 'table', head: ['Платформа', 'Как получить', 'Примечания'], rows: [
          ['Android', 'Google Play или APK с официального сайта', 'Android 5.0+; APK — запасной вариант, где Play недоступен'],
          ['iOS (iPhone / iPad)', 'App Store', 'Ищите «Pocket Option Broker»; iOS 12+'],
          ['Мобильный браузер', 'Откройте pocketoption.com и войдите', 'Полный терминал без установки; работает на любом телефоне'],
          ['Windows / macOS', 'Десктопное приложение с официального сайта', 'Тот же счёт, большие графики'],
        ] },
        { type: 'warn', title: 'Только официальные источники', text: 'Сторонние магазины размещают изменённые APK «Pocket Option», которые крадут логины. Скачивайте только из Google Play, App Store или со страницы загрузки внутри вашего аккаунта на официальном сайте.' },
        { type: 'h2', id: 'install', text: 'Как скачать и установить приложение' },
        { type: 'ol', items: [
          'Android: откройте Google Play, найдите Pocket Option и нажмите «Установить». Если Play недоступен в вашем регионе, войдите в аккаунт через браузер, откройте раздел «Приложения» и скачайте APK; разрешите установку из этого источника по запросу системы.',
          'iOS: откройте App Store, найдите Pocket Option и нажмите «Загрузить». Подтвердите через Face ID или Apple ID.',
          'Откройте приложение и войдите с тем же email и паролем, что на сайте, или зарегистрируйте новый аккаунт прямо в приложении.',
          'Разрешите уведомления, если хотите получать оповещения о закрытых сделках, пополнениях и турнирах.',
          'Переключитесь на демо-счёт в меню баланса, чтобы изучить платформу без риска.',
        ] },
        { type: 'h2', id: 'terminal', text: 'Мобильный терминал: что где находится' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Мобильный терминал Pocket Option с графиком и кнопками сделок', caption: 'График сверху, элементы управления сделкой снизу — мобильная компоновка терминала Pocket Option.' },
        { type: 'ul', items: [
          'Верхняя панель — название актива с выплатой; нажмите, чтобы открыть список активов и поиск.',
          'График — щипок для масштабирования, свайп для прокрутки; иконка графика переключает свечи/линию и таймфрейм.',
          'Индикаторы и инструменты рисования — иконка инструментов у края графика; тот же набор, что в вебе.',
          'Панель сделки — время экспирации, сумма и кнопки «Вверх» / «Вниз» внизу экрана.',
          'Меню — переключение баланса (демо / реальный), Финансы (пополнение, вывод, история), профиль, чат поддержки, турниры и социальный трейдинг.',
        ] },
        { type: 'h2', id: 'trade', text: 'Открытие сделки с телефона' },
        { type: 'image', src: IMG_TRADE, alt: 'Подтверждение сделки «Вверх» в приложении Pocket Option', caption: 'Задайте время и сумму, затем нажмите «Вверх» или «Вниз».' },
        { type: 'p', text: 'Выберите актив, задайте экспирацию (3–5 минут — комфортный минимум на маленьком экране), введите сумму — минимум $1 — и нажмите «Вверх» или «Вниз». Открытая сделка появится на графике с обратным отсчётом; результат отображается сразу после закрытия. Всё происходит на том же счёте, что и в веб-версии, поэтому сделку, открытую с телефона, можно отслеживать на компьютере и наоборот.' },
        { type: 'tip', title: 'Горизонтальный режим для графиков', text: 'Поверните телефон для более широкого графика при анализе, затем вернитесь в портретный режим для торговли. Это максимально близко к десктопному виду на телефоне.' },
        { type: 'h2', id: 'finance', text: 'Пополнение, вывод и верификация в приложении' },
        { type: 'p', text: 'Раздел «Финансы» в приложении предлагает те же способы оплаты, что и сайт: карты, криптовалюту, кошельки и локальные методы, с тем же минимальным депозитом $5 и минимальным выводом $10. Верификация на телефоне часто проще — вы фотографируете документ и подтверждение адреса камерой и загружаете их прямо из раздела «Профиль». Вывод запрашивается и отслеживается в Финансы → История транзакций точно так же, как в вебе.' },
        { type: 'h2', id: 'web-vs-app', text: 'Приложение и веб-версия: в чём разница' },
        { type: 'table', head: ['Функция', 'Мобильное приложение', 'Веб-терминал'], rows: [
          ['Счёт, баланс, активы, выплаты', 'Одинаково', 'Одинаково'],
          ['Индикаторы и инструменты рисования', 'Полный набор, меньше места', 'Полный набор, несколько графиков одновременно'],
          ['Push-уведомления', 'Да', 'Только уведомления браузера'],
          ['Биометрический вход', 'Face ID / отпечаток', 'Пароль + 2FA'],
          ['Несколько графиков на экране', 'Нет', 'Да'],
          ['Расход трафика', 'Низкий, оптимизирован для мобильных', 'Выше'],
        ] },
        { type: 'h2', id: 'tips', text: 'Торговая дисциплина на маленьком экране' },
        { type: 'ul', items: [
          'Держите размер позиции на уровне 1–2% баланса — на телефоне легко нажать «+» несколько лишних раз.',
          'Включите биометрический вход и 2FA и никогда не торгуйте через публичный Wi-Fi без VPN.',
          'Избегайте 5-секундных сделок на мобильном; запоздалое нажатие или сбой сети на такой скорости значат больше.',
          'Не торгуйте на ходу или в транспорте. Уведомления могут сообщить, что сделка закрылась; они не должны подталкивать сразу открывать следующую.',
          'Ведите тот же дневник, что и на компьютере — историю сделок из приложения можно перенести в заметки.',
        ] },
        { type: 'warn', title: 'Предупреждение о рисках', text: 'Торговля в приложении Pocket Option несёт тот же риск, что и в вебе: вы можете потерять внесённые средства. Удобство — не стратегия; соблюдайте свои правила на любом устройстве.' },
        { type: 'cta', text: 'Зарегистрируйтесь на Pocket Option, скачайте приложение из аккаунта и начните с бесплатного демо на $50 000 прямо на телефоне.', label: 'Открыть счёт Pocket Option' },
      ],
      faq: [
        { q: 'Приложение Pocket Option бесплатное?', a: 'Да. Приложение для Android и iOS скачивается бесплатно, подписок нет. Вы пополняете только собственный торговый баланс.' },
        { q: 'Как скачать APK Pocket Option?', a: 'Войдите в аккаунт на официальном сайте, откройте раздел «Приложения» или «Скачать» и сохраните APK на Android-телефон. Разрешите установку из этого источника по запросу системы. Не используйте APK со сторонних сайтов.' },
        { q: 'Есть ли приложение Pocket Option для iPhone?', a: 'Да, оно доступно в App Store. Если приложение не отображается в вашем регионе, веб-терминал полностью работает в Safari на iPhone и iPad.' },
        { q: 'Можно ли пользоваться демо-счётом в приложении?', a: 'Да. Переключитесь на демо-счёт в меню баланса; у него тот же виртуальный баланс $50 000, что и в вебе.' },
        { q: 'Можно ли пополнять и выводить через приложение?', a: 'Да. Раздел «Финансы» предлагает те же способы оплаты, минимальный депозит $5 и минимальный вывод $10, что и сайт.' },
        { q: 'Котировки и выплаты одинаковы в приложении и в вебе?', a: 'Да. Приложение подключается к тому же счёту и потоку цен, поэтому активы, котировки и выплаты идентичны.' },
      ],
    },
    id: {
      title: 'Aplikasi mobile Pocket Option: cara download di Android dan iOS, fitur, dan trading dari HP',
      metaTitle: 'Aplikasi Pocket Option untuk Android dan iOS: download, instal, dan trading dari HP',
      metaDescription:
        'Panduan aplikasi mobile Pocket Option: cara download APK Android atau aplikasi iOS, login, memakai terminal mobile, akun demo, deposit dan penarikan dari HP, notifikasi, dan perbedaannya dengan versi web.',
      excerpt:
        'Aplikasi pocketoption membawa terminal lengkap ke kantong Anda. Begini cara menginstalnya di Android dan iPhone, apa yang bisa dilakukan, perbedaannya dengan versi web, dan cara trading aman di layar kecil.',
      coverAlt: 'Tangan memegang smartphone dengan aplikasi trading Pocket Option terbuka',
      keyTakeaways: [
        'Aplikasi Pocket Option gratis untuk Android (Google Play atau APK dari situs resmi) dan iOS (App Store); versi web juga berfungsi di browser HP.',
        'Akun demo dan riil, 100+ aset, indikator, deposit, dan penarikan semuanya tersedia dari HP.',
        'Selalu download dari situs resmi atau toko resmi — ada aplikasi “Pocket Option” palsu.',
        'Di layar kecil, sederhanakan: satu aset, satu indikator, kedaluwarsa 3–5 menit, dan ukuran posisi 1–2% yang sama.',
      ],
      blocks: [
        { type: 'p', text: 'Sebagian besar trader Pocket Option membuka trade pertamanya dari HP. Aplikasi mobile memberi akses ke akun, saldo, aset, dan payout yang sama dengan terminal web, menambah notifikasi push, dan berjalan lewat data seluler. Panduan ini menjelaskan cara download aplikasi pocketoption di Android dan iOS, seperti apa terminal mobile-nya, dan cara menjaga disiplin trading ketika platform selalu ada di kantong.' },
        { type: 'h2', id: 'versions', text: 'Versi aplikasi Pocket Option yang tersedia' },
        { type: 'table', head: ['Platform', 'Cara mendapatkan', 'Catatan'], rows: [
          ['Android', 'Google Play atau APK dari situs resmi', 'Android 5.0+; APK adalah alternatif jika Play tidak tersedia'],
          ['iOS (iPhone / iPad)', 'App Store', 'Cari “Pocket Option Broker”; iOS 12+'],
          ['Browser mobile', 'Buka pocketoption.com dan login', 'Terminal lengkap tanpa instalasi; berfungsi di HP apa pun'],
          ['Windows / macOS', 'Aplikasi desktop dari situs resmi', 'Akun sama, grafik lebih besar'],
        ] },
        { type: 'warn', title: 'Hanya sumber resmi', text: 'Toko pihak ketiga menyimpan APK “Pocket Option” modifikasi yang mencuri login. Download hanya dari Google Play, App Store, atau halaman download di dalam akun Anda di situs resmi.' },
        { type: 'h2', id: 'install', text: 'Cara download dan instal aplikasi' },
        { type: 'ol', items: [
          'Android: buka Google Play, cari Pocket Option, dan ketuk Instal. Jika Play tidak tersedia di wilayah Anda, login ke akun lewat browser, buka bagian “Aplikasi” dan download APK; izinkan instalasi dari sumber ini saat diminta.',
          'iOS: buka App Store, cari Pocket Option, dan ketuk Dapatkan. Konfirmasi dengan Face ID atau Apple ID.',
          'Buka aplikasi dan login dengan email dan kata sandi yang sama seperti di situs, atau daftar akun baru langsung di aplikasi.',
          'Izinkan notifikasi jika ingin peringatan trade yang ditutup, deposit, dan turnamen.',
          'Beralih ke akun demo dari menu saldo untuk menjelajah tanpa risiko.',
        ] },
        { type: 'h2', id: 'terminal', text: 'Terminal mobile: letak setiap bagian' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal mobile Pocket Option dengan grafik dan tombol trade', caption: 'Grafik di atas, kontrol trade di bawah — tata letak mobile terminal Pocket Option.' },
        { type: 'ul', items: [
          'Bar atas — nama aset dengan payout; ketuk untuk membuka daftar aset dan pencarian.',
          'Grafik — cubit untuk zoom, geser untuk scroll; ketuk ikon grafik untuk mengganti candle/garis dan timeframe.',
          'Indikator dan alat gambar — ikon alat di tepi grafik; set yang sama dengan web.',
          'Panel trade — waktu kedaluwarsa, jumlah, dan tombol Naik / Turun di bagian bawah layar.',
          'Menu — ganti saldo (demo / riil), Keuangan (deposit, penarikan, riwayat), profil, chat dukungan, turnamen, dan social trading.',
        ] },
        { type: 'h2', id: 'trade', text: 'Membuka trade dari HP' },
        { type: 'image', src: IMG_TRADE, alt: 'Mengonfirmasi trade Naik di aplikasi Pocket Option', caption: 'Atur waktu dan jumlah, lalu ketuk Naik atau Turun.' },
        { type: 'p', text: 'Pilih aset, atur kedaluwarsa (3–5 menit adalah minimum yang nyaman di layar kecil), masukkan jumlah — minimum $1 — dan ketuk Naik atau Turun. Trade yang terbuka muncul di grafik dengan hitung mundur; hasilnya ditampilkan segera setelah ditutup. Semuanya terjadi di akun yang sama dengan versi web, sehingga trade yang dibuka dari HP bisa dipantau di desktop dan sebaliknya.' },
        { type: 'tip', title: 'Mode lanskap untuk grafik', text: 'Putar HP untuk grafik lebih lebar saat menganalisis, lalu kembali ke potret untuk trading. Ini yang paling dekat dengan tampilan desktop di HP.' },
        { type: 'h2', id: 'finance', text: 'Deposit, penarikan, dan verifikasi di aplikasi' },
        { type: 'p', text: 'Bagian Keuangan di aplikasi menawarkan metode pembayaran yang sama dengan situs: kartu, kripto, e-wallet, dan metode lokal, dengan deposit minimum $5 dan penarikan minimum $10 yang sama. Verifikasi sering lebih mudah di HP — Anda memotret identitas dan bukti alamat dengan kamera dan mengunggahnya langsung dari bagian Profil. Penarikan diajukan dan dipantau di Keuangan → Riwayat transaksi persis seperti di web.' },
        { type: 'h2', id: 'web-vs-app', text: 'Aplikasi vs versi web: apa yang berbeda' },
        { type: 'table', head: ['Fitur', 'Aplikasi mobile', 'Terminal web'], rows: [
          ['Akun, saldo, aset, payout', 'Sama', 'Sama'],
          ['Indikator dan alat gambar', 'Set lengkap, ruang kerja lebih kecil', 'Set lengkap, beberapa grafik sekaligus'],
          ['Notifikasi push', 'Ya', 'Hanya notifikasi browser'],
          ['Login biometrik', 'Face ID / sidik jari', 'Kata sandi + 2FA'],
          ['Beberapa grafik dalam satu layar', 'Tidak', 'Ya'],
          ['Penggunaan data', 'Rendah, dioptimalkan untuk mobile', 'Lebih tinggi'],
        ] },
        { type: 'h2', id: 'tips', text: 'Disiplin trading di layar kecil' },
        { type: 'ul', items: [
          'Pertahankan ukuran posisi 1–2% saldo — di HP mudah mengetuk “+” beberapa kali terlalu banyak.',
          'Aktifkan login biometrik dan 2FA, dan jangan pernah trading di Wi-Fi publik tanpa VPN.',
          'Hindari trade 5 detik di mobile; ketukan terlambat atau gangguan jaringan lebih berpengaruh pada kecepatan itu.',
          'Jangan trading sambil berjalan atau di perjalanan. Notifikasi boleh memberi tahu trade ditutup; jangan sampai menggoda Anda langsung membuka trade berikutnya.',
          'Gunakan jurnal yang sama seperti di desktop — riwayat trade di aplikasi bisa disalin ke catatan Anda.',
        ] },
        { type: 'warn', title: 'Peringatan risiko', text: 'Trading di aplikasi Pocket Option membawa risiko yang sama dengan web: Anda bisa kehilangan dana yang disetor. Kenyamanan bukan strategi — ikuti aturan Anda di setiap perangkat.' },
        { type: 'cta', text: 'Daftar di Pocket Option, download aplikasi dari akun Anda, dan mulai dengan demo gratis $50.000 di HP.', label: 'Buka akun Pocket Option' },
      ],
      faq: [
        { q: 'Apakah aplikasi Pocket Option gratis?', a: 'Ya. Aplikasi untuk Android dan iOS gratis diunduh dan tidak ada biaya langganan. Anda hanya mengisi saldo trading Anda sendiri.' },
        { q: 'Bagaimana cara download APK Pocket Option?', a: 'Login ke akun Anda di situs resmi, buka bagian Aplikasi atau Download, dan simpan APK ke HP Android. Izinkan instalasi dari sumber itu saat sistem meminta. Jangan gunakan APK dari situs pihak ketiga.' },
        { q: 'Apakah ada aplikasi Pocket Option untuk iPhone?', a: 'Ya, tersedia di App Store. Jika aplikasi tidak muncul di wilayah Anda, terminal web berfungsi penuh di Safari pada iPhone dan iPad.' },
        { q: 'Bisakah saya memakai akun demo di aplikasi?', a: 'Ya. Beralih ke akun demo dari menu saldo; saldonya virtual $50.000, sama seperti di web.' },
        { q: 'Bisakah deposit dan menarik dana dari aplikasi?', a: 'Ya. Bagian Keuangan menawarkan metode pembayaran yang sama, deposit minimum $5, dan penarikan minimum $10 seperti di situs web.' },
        { q: 'Apakah kuotasi dan payout sama di aplikasi dan web?', a: 'Ya. Aplikasi terhubung ke akun dan feed harga yang sama, sehingga aset, kuotasi, dan payout identik.' },
      ],
    },
  },
};
