import type { BlogPost } from '../types';

const IMG_FEATURES = '/images/blog/po-copy-trading-features.webp';
const IMG_INTERFACE = '/images/blog/po-trading-interface.webp';
const IMG_TOURN_PANEL = '/images/blog/po-tournaments-panel.webp';

export const pocketOptionSocialTrading: BlogPost = {
  slug: 'pocket-option-social-trading',
  category: 'platform',
  cover: '/images/blog/pocket-option-social-trading.webp',
  publishedAt: '2026-09-16',
  updatedAt: '2026-09-16',
  readingMinutes: 9,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option social trading (copy trading): how it works, how to choose traders and the real risks',
      metaTitle: 'Pocket Option Social Trading – Copy Trading Guide 2026',
      metaDescription:
        'Pocket Option social trading explained: how copy trading works, where to find the Social Trading panel, how to pick traders to copy, fees, position sizing and the risks you must know.',
      excerpt:
        'A practical guide to pocketoption Social Trading: what copying a trader actually does to your balance, how to read trader statistics, and how to limit losses when a leader has a bad week.',
      coverAlt: 'Copy trading features illustration — transparency, risk controls and proportional sizing on Pocket Option',
      keyTakeaways: [
        'Social Trading on Pocket Option lets you automatically repeat the trades of other traders (“leaders”) on your own balance, proportionally or with a fixed amount.',
        'The panel is inside the trading terminal — right sidebar → Social Trading — and works on both demo and real accounts.',
        'Judge a trader by a long history, moderate drawdown and consistency, not by a single big profit day or a high “win rate” over 20 trades.',
        'Copying does not remove risk: when the leader loses, you lose in the same proportion. Set a per-trade amount and a stop for the copy.',
        'Start by copying on the demo account for at least a week before committing real funds.',
      ],
      blocks: [
        { type: 'p', text: 'Social trading is one of the features that made Pocket Option popular with beginners: instead of learning technical analysis first, you can look at what experienced traders are doing in real time and copy their trades on your own account. It sounds simple, and technically it is — but the results depend entirely on whom you copy and how much you allocate. This guide explains how pocketoption Social Trading works, how to read trader statistics, and how to set limits so that one bad leader cannot wipe out your balance.' },
        { type: 'h2', id: 'what', text: 'What is Social Trading on Pocket Option?' },
        { type: 'p', text: 'Social Trading (often called copy trading) is a built-in section of the Pocket Option terminal that shows a live feed of trades made by other users and a ranking of the most successful traders. You can watch their entries, open the same trade manually with one click, or enable automatic copying: every time the chosen trader opens a position, the platform opens the same asset, direction and expiry on your account with the amount you defined.' },
        { type: 'image', src: IMG_FEATURES, alt: 'Copy trading platform features: transparency, risk controls, proportional sizing, ease of setup, demo availability', caption: 'The five things a copy-trading feature should offer — Pocket Option covers all of them.' },
        { type: 'ul', items: [
          'Live trade feed — see the assets, directions, amounts and results of recent trades across the platform.',
          'Trader ranking — sorted by profit, number of trades or copiers, with a profile page per trader.',
          'One-click copy — repeat a single trade manually while it is still open.',
          'Auto-copy — subscribe to a trader; their trades are mirrored automatically until you stop.',
          'Available on demo — you can test copying with virtual money.',
        ] },
        { type: 'h2', id: 'where', text: 'Where to find it and how to start copying' },
        { type: 'image', src: IMG_TOURN_PANEL, alt: 'Pocket Option terminal right sidebar with Signals, Social Trading, Express Trades and Tournaments icons', caption: 'Social Trading sits in the right sidebar of the terminal, next to Signals and Tournaments.' },
        { type: 'ol', items: [
          'Log in and open the trading terminal (demo or real).',
          'In the right sidebar click Social Trading (the icon with people).',
          'Browse the Top traders tab — open a profile to see the history, profit chart, favourite assets and number of copiers.',
          'Click Copy on the trader you selected.',
          'Set the copy parameters: amount per trade (fixed) or proportion of the leader’s trade, maximum number of simultaneous trades, and optionally a total loss limit.',
          'Confirm. Trades will appear in your Trades panel with a “copied” mark; you can stop copying at any time.',
        ] },
        { type: 'tip', title: 'Fixed amount beats proportional for beginners', text: 'If the leader trades $500 per position and you copy proportionally at 10%, you still risk $50 per trade. A fixed amount ($1–$5) keeps your risk predictable regardless of how aggressive the leader becomes.' },
        { type: 'h2', id: 'choose', text: 'How to choose a trader to copy' },
        { type: 'table', head: ['Metric', 'What to look for', 'Red flag'], rows: [
          ['Trading history', 'At least 3 months and 300+ trades', 'A profile created last week with a 90% win rate'],
          ['Profit curve', 'Steady upward line with small dips', 'Vertical jumps followed by long flat lines (one lucky streak)'],
          ['Drawdown', 'Largest losing streak under 20–25% of balance', 'Several 50%+ drawdowns recovered with martingale'],
          ['Trade size', 'Consistent amounts', 'Amounts doubling after each loss'],
          ['Assets & expiry', 'A few assets they clearly specialise in, 1–5 minute expiries', 'Random assets, 5-second trades'],
          ['Copiers', 'Growing number of copiers over time', 'Thousands of copiers gained in one day (promoted account)'],
        ] },
        { type: 'p', text: 'Diversify: copy 2–3 traders with different styles and assets rather than one “star”. If one has a losing week, the others may compensate. Review your copy list every weekend and remove traders whose behaviour changed (larger sizes, new assets, sudden losses).' },
        { type: 'h2', id: 'risks', text: 'The real risks of copy trading' },
        { type: 'warn', title: 'Copying is not passive income', text: 'Binary options carry a high risk: you can lose the full amount of each trade. The leader’s past results do not guarantee future results, and you have no control over their decisions once auto-copy is on. Never copy with money you cannot afford to lose.' },
        { type: 'ul', items: [
          'Leader risk — many top-ranked traders use martingale; they look great until one sequence wipes them out, and your copied trades with them.',
          'Timing risk — your trade opens a fraction of a second after theirs, sometimes at a slightly different price; on short expiries this can change the outcome.',
          'Payout difference — payouts vary by account status and moment; the leader may earn 92% while your copy pays 85%.',
          'Over-allocation — copying five traders at $10 each on a $100 balance means 50% of your money can be at risk simultaneously.',
          'Demo vs real — some leaders are ranked by demo results. Check the account type shown in the profile.',
        ] },
        { type: 'h2', id: 'settings', text: 'Recommended copy settings for a small balance' },
        { type: 'image', src: IMG_INTERFACE, alt: 'Pocket Option trading interface on laptop and phone', caption: 'Copying works identically on the web terminal and in the mobile app.' },
        { type: 'table', head: ['Balance', 'Amount per copied trade', 'Max traders copied', 'Daily loss limit'], rows: [
          ['$50', '$1', '2', '$5 (10%)'],
          ['$100–$200', '$1–$3', '2–3', '10%'],
          ['$500+', '1% of balance', '3–5', '10%'],
        ] },
        { type: 'p', text: 'These are conservative figures based on the 1–2% risk rule used in our risk management guide. When the daily limit is hit, pause all copies for the rest of the day — a losing leader rarely recovers within hours.' },
        { type: 'h2', id: 'vs-signals', text: 'Social trading vs signals vs manual trading' },
        { type: 'p', text: 'Signals tell you what to trade but leave the decision and sizing to you; social trading executes automatically; manual trading is fully yours. Beginners often combine them: copy 1–2 traders with a small fixed amount while learning to trade manually on the demo. Over time most successful users reduce copying and trade their own tested strategy.' },
        { type: 'cta', text: 'Try Social Trading with virtual funds first: open a free demo account, copy two traders for a week and evaluate the results before any real deposit.', label: 'Open a free demo account' },
      ],
      faq: [
        { q: 'Is social trading available on the Pocket Option demo account?', a: 'Yes. The Social Trading panel is available on the $50,000 demo account, so you can test copying without risk.' },
        { q: 'Does Pocket Option charge a fee for copy trading?', a: 'There is no separate subscription fee for copying; you only risk the amount of each copied trade. Terms may change, so check the platform rules.' },
        { q: 'Can I stop copying at any time?', a: 'Yes. Click Stop on the trader in your copy list. Already open trades run until expiry; no new trades will be opened.' },
        { q: 'Why did my copied trade lose when the leader won?', a: 'Usually because of a slight entry delay or price difference on very short expiries. Prefer leaders who trade 1–5 minute expiries.' },
        { q: 'How much should I copy with?', a: 'A fixed $1–$3 per trade on a $100 balance, and no more than 2–3 traders at the same time.' },
        { q: 'Can I become a leader others copy?', a: 'Traders with a public profile and positive history appear in the ranking automatically; check the privacy settings in your profile.' },
      ],
    },
    pt: {
      title: 'Social trading na Pocket Option (copy trading): como funciona, como escolher traders e os riscos reais',
      metaTitle: 'Pocket Option Social Trading – Guia de Copy Trading 2026',
      metaDescription:
        'Social trading na Pocket Option explicado: como funciona o copy trading, onde fica o painel Social Trading, como escolher traders, valores por operação e os riscos que precisa conhecer.',
      excerpt:
        'Guia prático do Social Trading da pocketoption: o que copiar um trader faz ao seu saldo, como ler as estatísticas e como limitar perdas quando um líder tem uma semana ruim.',
      coverAlt: 'Ilustração das funções de copy trading — transparência, controle de risco e proporção na Pocket Option',
      keyTakeaways: [
        'O Social Trading da Pocket Option repete automaticamente as operações de outros traders (“líderes”) no seu saldo, de forma proporcional ou com valor fixo.',
        'O painel fica dentro do terminal — barra lateral direita → Social Trading — e funciona na conta demo e na real.',
        'Avalie um trader pelo histórico longo, drawdown moderado e consistência, não por um dia de lucro alto ou uma “taxa de acerto” em 20 operações.',
        'Copiar não elimina o risco: quando o líder perde, você perde na mesma proporção. Defina valor por operação e um limite para a cópia.',
        'Comece copiando na conta demo por pelo menos uma semana antes de usar dinheiro real.',
      ],
      blocks: [
        { type: 'p', text: 'O social trading é um dos recursos que tornou a Pocket Option popular entre iniciantes: em vez de aprender análise técnica primeiro, você pode ver o que traders experientes estão fazendo em tempo real e copiar as operações na sua conta. Parece simples — e tecnicamente é — mas o resultado depende inteiramente de quem você copia e de quanto aloca. Este guia explica como funciona o Social Trading da pocketoption, como ler as estatísticas e como definir limites para que um líder ruim não zere o seu saldo.' },
        { type: 'h2', id: 'what', text: 'O que é o Social Trading na Pocket Option?' },
        { type: 'p', text: 'Social Trading (ou copy trading) é uma seção integrada do terminal que mostra um feed ao vivo das operações de outros usuários e um ranking dos traders mais lucrativos. Você pode observar as entradas, abrir a mesma operação manualmente com um clique ou ativar a cópia automática: sempre que o trader escolhido abre uma posição, a plataforma abre o mesmo ativo, direção e expiração na sua conta com o valor definido por você.' },
        { type: 'image', src: IMG_FEATURES, alt: 'Funções de copy trading: transparência, controle de risco, proporção, facilidade e conta demo', caption: 'Cinco pontos essenciais de um bom copy trading — a Pocket Option cobre todos.' },
        { type: 'ul', items: [
          'Feed ao vivo — ativos, direções, valores e resultados das operações recentes.',
          'Ranking de traders — por lucro, número de operações ou copiadores, com página de perfil.',
          'Cópia com um clique — repita uma operação manualmente enquanto ainda está aberta.',
          'Cópia automática — assine um trader; as operações são espelhadas até você parar.',
          'Disponível na demo — teste com dinheiro virtual.',
        ] },
        { type: 'h2', id: 'where', text: 'Onde encontrar e como começar a copiar' },
        { type: 'image', src: IMG_TOURN_PANEL, alt: 'Barra lateral do terminal Pocket Option com Signals, Social Trading, Express Trades e Tournaments', caption: 'O Social Trading fica na barra lateral direita, ao lado de Sinais e Torneios.' },
        { type: 'ol', items: [
          'Faça login e abra o terminal (demo ou real).',
          'Na barra lateral direita clique em Social Trading (ícone de pessoas).',
          'Abra a aba Top traders — entre no perfil para ver histórico, gráfico de lucro, ativos preferidos e número de copiadores.',
          'Clique em Copiar no trader escolhido.',
          'Defina os parâmetros: valor por operação (fixo) ou proporção da operação do líder, número máximo de operações simultâneas e, se possível, limite total de perda.',
          'Confirme. As operações aparecem no painel Trades com marca de “copiada”; você pode parar a qualquer momento.',
        ] },
        { type: 'tip', title: 'Valor fixo é melhor para iniciantes', text: 'Se o líder opera $500 por posição e você copia 10% proporcional, ainda arrisca $50 por operação. Um valor fixo ($1–$5) mantém o risco previsível independentemente da agressividade do líder.' },
        { type: 'h2', id: 'choose', text: 'Como escolher um trader para copiar' },
        { type: 'table', head: ['Métrica', 'O que procurar', 'Sinal de alerta'], rows: [
          ['Histórico', 'Pelo menos 3 meses e 300+ operações', 'Perfil criado na semana passada com 90% de acerto'],
          ['Curva de lucro', 'Linha ascendente constante com pequenas quedas', 'Saltos verticais seguidos de longas linhas planas (uma sequência de sorte)'],
          ['Drawdown', 'Maior sequência de perdas abaixo de 20–25% do saldo', 'Vários drawdowns de 50%+ recuperados com martingale'],
          ['Tamanho das operações', 'Valores consistentes', 'Valores dobrando após cada perda'],
          ['Ativos e expiração', 'Poucos ativos de especialidade, expirações de 1–5 minutos', 'Ativos aleatórios, operações de 5 segundos'],
          ['Copiadores', 'Número crescendo com o tempo', 'Milhares de copiadores em um dia (conta promovida)'],
        ] },
        { type: 'p', text: 'Diversifique: copie 2–3 traders com estilos e ativos diferentes em vez de uma “estrela”. Revise a lista todo fim de semana e remova traders cujo comportamento mudou (valores maiores, novos ativos, perdas repentinas).' },
        { type: 'h2', id: 'risks', text: 'Os riscos reais do copy trading' },
        { type: 'warn', title: 'Copiar não é renda passiva', text: 'Opções binárias têm risco alto: você pode perder todo o valor de cada operação. Resultados passados do líder não garantem resultados futuros e você não controla as decisões dele com a cópia automática ligada. Nunca copie com dinheiro que não pode perder.' },
        { type: 'ul', items: [
          'Risco do líder — muitos traders do topo usam martingale; parecem ótimos até uma sequência zerar a conta deles e as suas operações copiadas.',
          'Risco de timing — sua operação abre uma fração de segundo depois, às vezes a um preço diferente; em expirações curtas isso muda o resultado.',
          'Diferença de payout — o líder pode receber 92% enquanto sua cópia paga 85%.',
          'Alocação excessiva — copiar cinco traders a $10 cada com saldo de $100 coloca 50% do dinheiro em risco ao mesmo tempo.',
          'Demo vs real — alguns líderes são ranqueados por resultados demo. Verifique o tipo de conta no perfil.',
        ] },
        { type: 'h2', id: 'settings', text: 'Configurações recomendadas para saldo pequeno' },
        { type: 'image', src: IMG_INTERFACE, alt: 'Interface de trading da Pocket Option no laptop e no celular', caption: 'A cópia funciona igual no terminal web e no app.' },
        { type: 'table', head: ['Saldo', 'Valor por operação copiada', 'Máx. traders', 'Limite diário de perda'], rows: [
          ['$50', '$1', '2', '$5 (10%)'],
          ['$100–$200', '$1–$3', '2–3', '10%'],
          ['$500+', '1% do saldo', '3–5', '10%'],
        ] },
        { type: 'p', text: 'São valores conservadores baseados na regra de 1–2% do nosso guia de gestão de risco. Ao atingir o limite diário, pause todas as cópias até o dia seguinte.' },
        { type: 'h2', id: 'vs-signals', text: 'Social trading vs sinais vs operar manualmente' },
        { type: 'p', text: 'Sinais dizem o que operar mas deixam a decisão e o valor com você; o social trading executa automaticamente; o manual é totalmente seu. Iniciantes costumam combinar: copiar 1–2 traders com valor fixo pequeno enquanto aprendem a operar na demo. Com o tempo, a maioria reduz a cópia e opera a própria estratégia testada.' },
        { type: 'cta', text: 'Teste o Social Trading com fundos virtuais: abra a conta demo gratuita, copie dois traders por uma semana e avalie antes de depositar.', label: 'Abrir conta demo gratuita' },
      ],
      faq: [
        { q: 'O social trading está disponível na conta demo da Pocket Option?', a: 'Sim. O painel Social Trading funciona na conta demo de $50.000, então você pode testar sem risco.' },
        { q: 'A Pocket Option cobra taxa pelo copy trading?', a: 'Não há assinatura separada; você arrisca apenas o valor de cada operação copiada. As condições podem mudar — confira as regras da plataforma.' },
        { q: 'Posso parar de copiar a qualquer momento?', a: 'Sim. Clique em Parar no trader da sua lista. Operações já abertas seguem até a expiração; novas não serão abertas.' },
        { q: 'Por que minha operação copiada perdeu quando o líder ganhou?', a: 'Normalmente por um pequeno atraso na entrada ou diferença de preço em expirações muito curtas. Prefira líderes com expirações de 1–5 minutos.' },
        { q: 'Com quanto devo copiar?', a: 'Valor fixo de $1–$3 por operação com saldo de $100, e no máximo 2–3 traders ao mesmo tempo.' },
        { q: 'Posso me tornar um líder copiado por outros?', a: 'Traders com perfil público e histórico positivo aparecem no ranking automaticamente; verifique as configurações de privacidade do perfil.' },
      ],
    },
    es: {
      title: 'Social trading en Pocket Option (copy trading): cómo funciona, cómo elegir traders y los riesgos reales',
      metaTitle: 'Pocket Option Social Trading – Guía de Copy Trading 2026',
      metaDescription:
        'Social trading en Pocket Option: cómo funciona el copy trading, dónde está el panel Social Trading, cómo elegir traders para copiar, importe por operación y los riesgos que debes conocer.',
      excerpt:
        'Guía práctica del Social Trading de pocketoption: qué hace copiar a un trader con tu saldo, cómo leer sus estadísticas y cómo limitar pérdidas cuando un líder tiene una mala semana.',
      coverAlt: 'Ilustración de funciones de copy trading — transparencia, control de riesgo y tamaño proporcional en Pocket Option',
      keyTakeaways: [
        'El Social Trading de Pocket Option repite automáticamente las operaciones de otros traders (“líderes”) en tu saldo, de forma proporcional o con importe fijo.',
        'El panel está dentro del terminal — barra lateral derecha → Social Trading — y funciona en cuenta demo y real.',
        'Valora a un trader por un historial largo, drawdown moderado y consistencia, no por un día de gran beneficio o una “tasa de acierto” sobre 20 operaciones.',
        'Copiar no elimina el riesgo: cuando el líder pierde, tú pierdes en la misma proporción. Fija un importe por operación y un límite para la copia.',
        'Empieza copiando en la cuenta demo al menos una semana antes de usar fondos reales.',
      ],
      blocks: [
        { type: 'p', text: 'El social trading es una de las funciones que hizo popular a Pocket Option entre principiantes: en lugar de aprender análisis técnico primero, puedes ver lo que hacen traders experimentados en tiempo real y copiar sus operaciones en tu cuenta. Suena simple — y técnicamente lo es — pero el resultado depende por completo de a quién copies y cuánto asignes. Esta guía explica cómo funciona el Social Trading de pocketoption, cómo leer las estadísticas y cómo fijar límites para que un mal líder no arruine tu saldo.' },
        { type: 'h2', id: 'what', text: '¿Qué es el Social Trading en Pocket Option?' },
        { type: 'p', text: 'Social Trading (o copy trading) es una sección integrada del terminal que muestra un feed en vivo de operaciones de otros usuarios y un ranking de los traders más rentables. Puedes observar sus entradas, abrir la misma operación manualmente con un clic o activar la copia automática: cada vez que el trader elegido abre una posición, la plataforma abre el mismo activo, dirección y expiración en tu cuenta con el importe que definiste.' },
        { type: 'image', src: IMG_FEATURES, alt: 'Funciones de copy trading: transparencia, control de riesgo, tamaño proporcional, facilidad y cuenta demo', caption: 'Los cinco puntos que debe ofrecer un copy trading — Pocket Option cubre todos.' },
        { type: 'ul', items: [
          'Feed en vivo — activos, direcciones, importes y resultados de operaciones recientes.',
          'Ranking de traders — por beneficio, número de operaciones o copiadores, con página de perfil.',
          'Copia con un clic — repite una operación manualmente mientras sigue abierta.',
          'Copia automática — suscríbete a un trader; sus operaciones se replican hasta que pares.',
          'Disponible en demo — prueba con dinero virtual.',
        ] },
        { type: 'h2', id: 'where', text: 'Dónde encontrarlo y cómo empezar a copiar' },
        { type: 'image', src: IMG_TOURN_PANEL, alt: 'Barra lateral del terminal Pocket Option con Signals, Social Trading, Express Trades y Tournaments', caption: 'Social Trading está en la barra lateral derecha, junto a Señales y Torneos.' },
        { type: 'ol', items: [
          'Inicia sesión y abre el terminal (demo o real).',
          'En la barra lateral derecha haz clic en Social Trading (icono de personas).',
          'Abre la pestaña Top traders — entra en un perfil para ver historial, gráfico de beneficio, activos favoritos y número de copiadores.',
          'Haz clic en Copiar en el trader elegido.',
          'Define los parámetros: importe por operación (fijo) o proporción de la operación del líder, máximo de operaciones simultáneas y, si es posible, límite total de pérdida.',
          'Confirma. Las operaciones aparecen en el panel Trades marcadas como “copiadas”; puedes parar en cualquier momento.',
        ] },
        { type: 'tip', title: 'Importe fijo mejor que proporcional para principiantes', text: 'Si el líder opera $500 por posición y copias un 10% proporcional, sigues arriesgando $50 por operación. Un importe fijo ($1–$5) mantiene tu riesgo previsible sin importar la agresividad del líder.' },
        { type: 'h2', id: 'choose', text: 'Cómo elegir un trader para copiar' },
        { type: 'table', head: ['Métrica', 'Qué buscar', 'Señal de alerta'], rows: [
          ['Historial', 'Al menos 3 meses y 300+ operaciones', 'Perfil creado la semana pasada con 90% de acierto'],
          ['Curva de beneficio', 'Línea ascendente constante con pequeñas caídas', 'Saltos verticales seguidos de largas líneas planas (una racha de suerte)'],
          ['Drawdown', 'Mayor racha perdedora bajo el 20–25% del saldo', 'Varios drawdowns de 50%+ recuperados con martingala'],
          ['Tamaño de operación', 'Importes consistentes', 'Importes que se duplican tras cada pérdida'],
          ['Activos y expiración', 'Pocos activos de especialidad, expiraciones de 1–5 minutos', 'Activos aleatorios, operaciones de 5 segundos'],
          ['Copiadores', 'Número creciente con el tiempo', 'Miles de copiadores en un día (cuenta promocionada)'],
        ] },
        { type: 'p', text: 'Diversifica: copia 2–3 traders con estilos y activos distintos en lugar de una “estrella”. Revisa la lista cada fin de semana y elimina a quienes cambiaron su comportamiento (importes mayores, nuevos activos, pérdidas repentinas).' },
        { type: 'h2', id: 'risks', text: 'Los riesgos reales del copy trading' },
        { type: 'warn', title: 'Copiar no es ingreso pasivo', text: 'Las opciones binarias tienen riesgo alto: puedes perder el importe completo de cada operación. Los resultados pasados del líder no garantizan resultados futuros y no controlas sus decisiones con la copia automática activada. Nunca copies con dinero que no puedas perder.' },
        { type: 'ul', items: [
          'Riesgo del líder — muchos traders del top usan martingala; parecen excelentes hasta que una secuencia los liquida, junto con tus operaciones copiadas.',
          'Riesgo de timing — tu operación abre una fracción de segundo después, a veces a un precio distinto; en expiraciones cortas cambia el resultado.',
          'Diferencia de payout — el líder puede cobrar 92% mientras tu copia paga 85%.',
          'Sobreasignación — copiar cinco traders a $10 cada uno con saldo de $100 pone el 50% del dinero en riesgo simultáneamente.',
          'Demo vs real — algunos líderes se clasifican por resultados demo. Comprueba el tipo de cuenta en el perfil.',
        ] },
        { type: 'h2', id: 'settings', text: 'Configuración recomendada para saldo pequeño' },
        { type: 'image', src: IMG_INTERFACE, alt: 'Interfaz de trading de Pocket Option en portátil y móvil', caption: 'La copia funciona igual en el terminal web y en la app.' },
        { type: 'table', head: ['Saldo', 'Importe por operación copiada', 'Máx. traders', 'Límite diario de pérdida'], rows: [
          ['$50', '$1', '2', '$5 (10%)'],
          ['$100–$200', '$1–$3', '2–3', '10%'],
          ['$500+', '1% del saldo', '3–5', '10%'],
        ] },
        { type: 'p', text: 'Son cifras conservadoras basadas en la regla del 1–2% de nuestra guía de gestión del riesgo. Al alcanzar el límite diario, pausa todas las copias hasta el día siguiente.' },
        { type: 'h2', id: 'vs-signals', text: 'Social trading vs señales vs trading manual' },
        { type: 'p', text: 'Las señales dicen qué operar pero dejan la decisión y el importe en tus manos; el social trading ejecuta automáticamente; el manual es totalmente tuyo. Los principiantes suelen combinarlos: copiar 1–2 traders con importe fijo pequeño mientras aprenden a operar en demo. Con el tiempo, la mayoría reduce la copia y opera su propia estrategia probada.' },
        { type: 'cta', text: 'Prueba el Social Trading con fondos virtuales: abre la cuenta demo gratuita, copia a dos traders durante una semana y evalúa antes de depositar.', label: 'Abrir cuenta demo gratis' },
      ],
      faq: [
        { q: '¿El social trading está disponible en la cuenta demo de Pocket Option?', a: 'Sí. El panel Social Trading funciona en la cuenta demo de $50.000, así que puedes probar sin riesgo.' },
        { q: '¿Pocket Option cobra comisión por el copy trading?', a: 'No hay suscripción aparte; solo arriesgas el importe de cada operación copiada. Las condiciones pueden cambiar — revisa las reglas de la plataforma.' },
        { q: '¿Puedo dejar de copiar en cualquier momento?', a: 'Sí. Pulsa Detener en el trader de tu lista. Las operaciones abiertas siguen hasta expirar; no se abrirán nuevas.' },
        { q: '¿Por qué mi operación copiada perdió cuando el líder ganó?', a: 'Normalmente por un ligero retraso de entrada o diferencia de precio en expiraciones muy cortas. Prefiere líderes con expiraciones de 1–5 minutos.' },
        { q: '¿Con cuánto debo copiar?', a: 'Importe fijo de $1–$3 por operación con saldo de $100, y no más de 2–3 traders a la vez.' },
        { q: '¿Puedo convertirme en líder al que otros copien?', a: 'Los traders con perfil público e historial positivo aparecen en el ranking automáticamente; revisa la configuración de privacidad de tu perfil.' },
      ],
    },
    ru: {
      title: 'Социальный трейдинг Pocket Option (копирование сделок): как работает, как выбрать трейдера и реальные риски',
      metaTitle: 'Pocket Option Social Trading – копитрейдинг: гайд 2026',
      metaDescription:
        'Социальный трейдинг на Pocket Option: как работает копирование сделок, где панель Social Trading, как выбирать трейдеров, размер ставки и риски, о которых нужно знать.',
      excerpt:
        'Практическое руководство по Social Trading pocketoption: что копирование делает с вашим балансом, как читать статистику трейдера и как ограничить убытки в неудачную неделю лидера.',
      coverAlt: 'Иллюстрация функций копитрейдинга — прозрачность, контроль риска и пропорциональный объём на Pocket Option',
      keyTakeaways: [
        'Social Trading на Pocket Option автоматически повторяет сделки других трейдеров («лидеров») на вашем балансе — пропорционально или фиксированной суммой.',
        'Панель находится в терминале — правая боковая панель → Social Trading — и работает на демо и реальном счёте.',
        'Оценивайте трейдера по длинной истории, умеренной просадке и стабильности, а не по одному прибыльному дню или «винрейту» на 20 сделках.',
        'Копирование не убирает риск: когда лидер теряет, вы теряете в той же пропорции. Задайте сумму на сделку и лимит для копирования.',
        'Начните с копирования на демо-счёте минимум неделю, прежде чем вкладывать реальные деньги.',
      ],
      blocks: [
        { type: 'p', text: 'Социальный трейдинг — одна из функций, сделавших Pocket Option популярным у новичков: вместо изучения технического анализа можно смотреть, что делают опытные трейдеры в реальном времени, и копировать их сделки на своём счёте. Звучит просто — и технически так и есть, — но результат полностью зависит от того, кого вы копируете и сколько выделяете. В этом гайде разбираем, как работает Social Trading pocketoption, как читать статистику и как выставить лимиты, чтобы один неудачный лидер не обнулил ваш баланс.' },
        { type: 'h2', id: 'what', text: 'Что такое Social Trading на Pocket Option?' },
        { type: 'p', text: 'Social Trading (копитрейдинг) — встроенный раздел терминала с живой лентой сделок других пользователей и рейтингом самых успешных трейдеров. Можно наблюдать за их входами, открыть такую же сделку вручную одним кликом или включить автокопирование: каждый раз, когда выбранный трейдер открывает позицию, платформа открывает тот же актив, направление и экспирацию на вашем счёте с заданной вами суммой.' },
        { type: 'image', src: IMG_FEATURES, alt: 'Функции копитрейдинга: прозрачность, контроль риска, пропорциональный объём, простота настройки, демо', caption: 'Пять требований к копитрейдингу — Pocket Option закрывает все.' },
        { type: 'ul', items: [
          'Живая лента — активы, направления, суммы и результаты недавних сделок.',
          'Рейтинг трейдеров — по прибыли, числу сделок или подписчиков, со страницей профиля.',
          'Копирование в один клик — повторите отдельную сделку, пока она открыта.',
          'Автокопирование — подпишитесь на трейдера; сделки зеркалятся, пока вы не остановите.',
          'Доступно на демо — тестируйте на виртуальных деньгах.',
        ] },
        { type: 'h2', id: 'where', text: 'Где найти и как начать копировать' },
        { type: 'image', src: IMG_TOURN_PANEL, alt: 'Правая панель терминала Pocket Option: Signals, Social Trading, Express Trades, Tournaments', caption: 'Social Trading — в правой боковой панели, рядом с Сигналами и Турнирами.' },
        { type: 'ol', items: [
          'Войдите и откройте терминал (демо или реальный).',
          'В правой панели нажмите Social Trading (иконка с людьми).',
          'Откройте вкладку Top traders — зайдите в профиль, чтобы увидеть историю, график прибыли, любимые активы и число подписчиков.',
          'Нажмите «Копировать» у выбранного трейдера.',
          'Задайте параметры: сумма на сделку (фиксированная) или доля от сделки лидера, максимум одновременных сделок и, по возможности, общий лимит убытка.',
          'Подтвердите. Сделки появятся в панели Trades с пометкой «скопировано»; остановить можно в любой момент.',
        ] },
        { type: 'tip', title: 'Новичкам — фиксированная сумма', text: 'Если лидер ставит $500 на позицию, а вы копируете 10% пропорционально, вы всё равно рискуете $50 на сделку. Фиксированная сумма ($1–$5) делает риск предсказуемым независимо от агрессивности лидера.' },
        { type: 'h2', id: 'choose', text: 'Как выбрать трейдера для копирования' },
        { type: 'table', head: ['Метрика', 'Что искать', 'Красный флаг'], rows: [
          ['История', 'Минимум 3 месяца и 300+ сделок', 'Профиль создан на прошлой неделе с винрейтом 90%'],
          ['Кривая прибыли', 'Ровный рост с небольшими откатами', 'Вертикальные скачки и длинные плоские участки (одна удачная серия)'],
          ['Просадка', 'Максимальная серия убытков менее 20–25% баланса', 'Несколько просадок 50%+, отбитых мартингейлом'],
          ['Размер сделок', 'Стабильные суммы', 'Суммы удваиваются после каждого убытка'],
          ['Активы и экспирация', 'Несколько профильных активов, экспирации 1–5 минут', 'Случайные активы, сделки по 5 секунд'],
          ['Подписчики', 'Число растёт постепенно', 'Тысячи подписчиков за день (раскрученный аккаунт)'],
        ] },
        { type: 'p', text: 'Диверсифицируйте: копируйте 2–3 трейдеров с разными стилями и активами, а не одну «звезду». Пересматривайте список каждые выходные и убирайте тех, чьё поведение изменилось (большие суммы, новые активы, внезапные убытки).' },
        { type: 'h2', id: 'risks', text: 'Реальные риски копитрейдинга' },
        { type: 'warn', title: 'Копирование — не пассивный доход', text: 'Бинарные опционы — высокий риск: вы можете потерять всю сумму каждой сделки. Прошлые результаты лидера не гарантируют будущих, и вы не контролируете его решения при включённом автокопировании. Никогда не копируйте на деньги, которые не можете позволить себе потерять.' },
        { type: 'ul', items: [
          'Риск лидера — многие топовые трейдеры используют мартингейл; выглядят отлично, пока одна серия не обнулит их счёт вместе с вашими скопированными сделками.',
          'Риск задержки — ваша сделка открывается на доли секунды позже, иногда по другой цене; на коротких экспирациях это меняет результат.',
          'Разница выплат — лидер может получать 92%, а ваша копия — 85%.',
          'Переаллокация — копирование пяти трейдеров по $10 при балансе $100 ставит под риск 50% денег одновременно.',
          'Демо vs реал — некоторые лидеры ранжируются по результатам на демо. Проверяйте тип счёта в профиле.',
        ] },
        { type: 'h2', id: 'settings', text: 'Рекомендуемые настройки для небольшого баланса' },
        { type: 'image', src: IMG_INTERFACE, alt: 'Торговый интерфейс Pocket Option на ноутбуке и телефоне', caption: 'Копирование работает одинаково в веб-терминале и мобильном приложении.' },
        { type: 'table', head: ['Баланс', 'Сумма на скопированную сделку', 'Макс. трейдеров', 'Дневной лимит убытка'], rows: [
          ['$50', '$1', '2', '$5 (10%)'],
          ['$100–$200', '$1–$3', '2–3', '10%'],
          ['$500+', '1% баланса', '3–5', '10%'],
        ] },
        { type: 'p', text: 'Это консервативные цифры по правилу 1–2% из нашего гайда по риск-менеджменту. При достижении дневного лимита ставьте все копии на паузу до следующего дня.' },
        { type: 'h2', id: 'vs-signals', text: 'Социальный трейдинг vs сигналы vs ручная торговля' },
        { type: 'p', text: 'Сигналы говорят, что торговать, но решение и сумма — за вами; социальный трейдинг исполняет автоматически; ручная торговля полностью ваша. Новички часто совмещают: копируют 1–2 трейдеров небольшой фиксированной суммой, пока учатся торговать на демо. Со временем большинство сокращает копирование и торгует собственную протестированную стратегию.' },
        { type: 'cta', text: 'Попробуйте Social Trading на виртуальных средствах: откройте бесплатный демо-счёт, копируйте двух трейдеров неделю и оцените результат до реального депозита.', label: 'Открыть бесплатный демо-счёт' },
      ],
      faq: [
        { q: 'Доступен ли социальный трейдинг на демо-счёте Pocket Option?', a: 'Да. Панель Social Trading работает на демо-счёте с $50 000, так что копирование можно протестировать без риска.' },
        { q: 'Берёт ли Pocket Option комиссию за копирование?', a: 'Отдельной подписки нет; вы рискуете только суммой каждой скопированной сделки. Условия могут меняться — проверяйте правила платформы.' },
        { q: 'Можно ли остановить копирование в любой момент?', a: 'Да. Нажмите «Стоп» у трейдера в списке. Открытые сделки доработают до экспирации; новые не откроются.' },
        { q: 'Почему моя скопированная сделка проиграла, а у лидера выиграла?', a: 'Обычно из-за небольшой задержки входа или разницы в цене на очень коротких экспирациях. Выбирайте лидеров с экспирацией 1–5 минут.' },
        { q: 'Какой суммой копировать?', a: 'Фиксированно $1–$3 на сделку при балансе $100 и не более 2–3 трейдеров одновременно.' },
        { q: 'Могу ли я стать лидером, которого копируют?', a: 'Трейдеры с публичным профилем и положительной историей попадают в рейтинг автоматически; проверьте настройки приватности в профиле.' },
      ],
    },
    id: {
      title: 'Social trading Pocket Option (copy trading): cara kerja, cara memilih trader, dan risiko nyatanya',
      metaTitle: 'Pocket Option Social Trading – Panduan Copy Trading 2026',
      metaDescription:
        'Social trading Pocket Option dijelaskan: cara kerja copy trading, letak panel Social Trading, cara memilih trader yang dicopy, nominal per trade, dan risiko yang wajib diketahui.',
      excerpt:
        'Panduan praktis Social Trading pocketoption: apa yang terjadi pada saldo Anda saat menyalin trader, cara membaca statistik trader, dan cara membatasi kerugian saat leader mengalami minggu buruk.',
      coverAlt: 'Ilustrasi fitur copy trading — transparansi, kontrol risiko, dan ukuran proporsional di Pocket Option',
      keyTakeaways: [
        'Social Trading di Pocket Option otomatis mengulang trade trader lain (“leader”) di saldo Anda, secara proporsional atau dengan nominal tetap.',
        'Panelnya ada di dalam terminal — sidebar kanan → Social Trading — dan berfungsi di akun demo maupun riil.',
        'Nilai trader dari riwayat panjang, drawdown moderat, dan konsistensi, bukan dari satu hari profit besar atau “win rate” tinggi dari 20 trade.',
        'Menyalin tidak menghilangkan risiko: saat leader rugi, Anda rugi dengan proporsi yang sama. Tetapkan nominal per trade dan batas untuk copy.',
        'Mulailah menyalin di akun demo minimal seminggu sebelum memakai dana riil.',
      ],
      blocks: [
        { type: 'p', text: 'Social trading adalah salah satu fitur yang membuat Pocket Option populer di kalangan pemula: alih-alih belajar analisis teknikal dulu, Anda bisa melihat apa yang dilakukan trader berpengalaman secara real time dan menyalin trade mereka di akun sendiri. Terdengar sederhana — dan secara teknis memang begitu — tetapi hasilnya sepenuhnya bergantung pada siapa yang Anda salin dan berapa yang Anda alokasikan. Panduan ini menjelaskan cara kerja Social Trading pocketoption, cara membaca statistik trader, dan cara menetapkan batas agar satu leader buruk tidak menghabiskan saldo Anda.' },
        { type: 'h2', id: 'what', text: 'Apa itu Social Trading di Pocket Option?' },
        { type: 'p', text: 'Social Trading (sering disebut copy trading) adalah bagian bawaan terminal Pocket Option yang menampilkan feed langsung trade pengguna lain dan peringkat trader paling sukses. Anda bisa mengamati entry mereka, membuka trade yang sama secara manual dengan satu klik, atau mengaktifkan penyalinan otomatis: setiap kali trader pilihan membuka posisi, platform membuka aset, arah, dan expiry yang sama di akun Anda dengan nominal yang Anda tentukan.' },
        { type: 'image', src: IMG_FEATURES, alt: 'Fitur copy trading: transparansi, kontrol risiko, ukuran proporsional, mudah disiapkan, tersedia demo', caption: 'Lima hal yang harus ada di fitur copy trading — Pocket Option memenuhi semuanya.' },
        { type: 'ul', items: [
          'Feed trade langsung — aset, arah, nominal, dan hasil trade terbaru di platform.',
          'Peringkat trader — berdasarkan profit, jumlah trade, atau jumlah copier, dengan halaman profil.',
          'Copy satu klik — ulangi satu trade secara manual selagi masih terbuka.',
          'Auto-copy — berlangganan ke trader; trade mereka disalin otomatis sampai Anda berhenti.',
          'Tersedia di demo — uji penyalinan dengan uang virtual.',
        ] },
        { type: 'h2', id: 'where', text: 'Letaknya dan cara mulai menyalin' },
        { type: 'image', src: IMG_TOURN_PANEL, alt: 'Sidebar kanan terminal Pocket Option dengan ikon Signals, Social Trading, Express Trades, dan Tournaments', caption: 'Social Trading berada di sidebar kanan terminal, di samping Signals dan Tournaments.' },
        { type: 'ol', items: [
          'Login dan buka terminal trading (demo atau riil).',
          'Di sidebar kanan klik Social Trading (ikon orang).',
          'Buka tab Top traders — buka profil untuk melihat riwayat, grafik profit, aset favorit, dan jumlah copier.',
          'Klik Copy pada trader yang dipilih.',
          'Atur parameter copy: nominal per trade (tetap) atau proporsi dari trade leader, jumlah maksimum trade bersamaan, dan bila ada, batas total kerugian.',
          'Konfirmasi. Trade akan muncul di panel Trades dengan tanda “copied”; Anda bisa berhenti kapan saja.',
        ] },
        { type: 'tip', title: 'Nominal tetap lebih aman untuk pemula', text: 'Jika leader trading $500 per posisi dan Anda menyalin proporsional 10%, Anda tetap mempertaruhkan $50 per trade. Nominal tetap ($1–$5) menjaga risiko tetap terukur berapa pun agresifnya leader.' },
        { type: 'h2', id: 'choose', text: 'Cara memilih trader untuk disalin' },
        { type: 'table', head: ['Metrik', 'Yang dicari', 'Tanda bahaya'], rows: [
          ['Riwayat trading', 'Minimal 3 bulan dan 300+ trade', 'Profil dibuat minggu lalu dengan win rate 90%'],
          ['Kurva profit', 'Garis naik stabil dengan penurunan kecil', 'Lonjakan vertikal diikuti garis datar panjang (satu kali beruntung)'],
          ['Drawdown', 'Rentetan rugi terbesar di bawah 20–25% saldo', 'Beberapa drawdown 50%+ yang dipulihkan dengan martingale'],
          ['Ukuran trade', 'Nominal konsisten', 'Nominal berlipat ganda setelah setiap kerugian'],
          ['Aset & expiry', 'Sedikit aset yang benar-benar dikuasai, expiry 1–5 menit', 'Aset acak, trade 5 detik'],
          ['Copier', 'Jumlah copier bertambah bertahap', 'Ribuan copier dalam sehari (akun promosi)'],
        ] },
        { type: 'p', text: 'Diversifikasi: salin 2–3 trader dengan gaya dan aset berbeda daripada satu “bintang”. Tinjau daftar copy setiap akhir pekan dan hapus trader yang perilakunya berubah (ukuran membesar, aset baru, rugi mendadak).' },
        { type: 'h2', id: 'risks', text: 'Risiko nyata copy trading' },
        { type: 'warn', title: 'Menyalin bukan penghasilan pasif', text: 'Opsi biner berisiko tinggi: Anda bisa kehilangan seluruh nominal setiap trade. Hasil masa lalu leader tidak menjamin hasil masa depan, dan Anda tidak mengontrol keputusannya saat auto-copy aktif. Jangan pernah menyalin dengan uang yang tidak sanggup Anda rugikan.' },
        { type: 'ul', items: [
          'Risiko leader — banyak trader peringkat atas memakai martingale; tampak hebat sampai satu rentetan menghabiskan akun mereka, dan trade salinan Anda ikut hilang.',
          'Risiko timing — trade Anda terbuka sepersekian detik setelah mereka, kadang di harga sedikit berbeda; pada expiry pendek ini bisa mengubah hasil.',
          'Perbedaan payout — leader mungkin mendapat 92% sementara salinan Anda dibayar 85%.',
          'Alokasi berlebihan — menyalin lima trader $10 masing-masing dengan saldo $100 berarti 50% uang berisiko sekaligus.',
          'Demo vs riil — beberapa leader diperingkat berdasarkan hasil demo. Periksa tipe akun di profil.',
        ] },
        { type: 'h2', id: 'settings', text: 'Pengaturan copy yang disarankan untuk saldo kecil' },
        { type: 'image', src: IMG_INTERFACE, alt: 'Antarmuka trading Pocket Option di laptop dan ponsel', caption: 'Penyalinan bekerja sama persis di terminal web dan aplikasi mobile.' },
        { type: 'table', head: ['Saldo', 'Nominal per trade salinan', 'Maks. trader', 'Batas rugi harian'], rows: [
          ['$50', '$1', '2', '$5 (10%)'],
          ['$100–$200', '$1–$3', '2–3', '10%'],
          ['$500+', '1% saldo', '3–5', '10%'],
        ] },
        { type: 'p', text: 'Angka ini konservatif, mengikuti aturan risiko 1–2% dari panduan manajemen risiko kami. Saat batas harian tercapai, jeda semua copy sampai hari berikutnya — leader yang sedang rugi jarang pulih dalam hitungan jam.' },
        { type: 'h2', id: 'vs-signals', text: 'Social trading vs sinyal vs trading manual' },
        { type: 'p', text: 'Sinyal memberi tahu apa yang ditradingkan tetapi keputusan dan nominal tetap di tangan Anda; social trading mengeksekusi otomatis; trading manual sepenuhnya milik Anda. Pemula sering menggabungkannya: menyalin 1–2 trader dengan nominal tetap kecil sambil belajar trading manual di demo. Seiring waktu, kebanyakan pengguna sukses mengurangi copy dan menjalankan strategi teruji sendiri.' },
        { type: 'cta', text: 'Coba Social Trading dengan dana virtual dulu: buka akun demo gratis, salin dua trader selama seminggu, dan evaluasi hasilnya sebelum deposit riil.', label: 'Buka akun demo gratis' },
      ],
      faq: [
        { q: 'Apakah social trading tersedia di akun demo Pocket Option?', a: 'Ya. Panel Social Trading tersedia di akun demo $50.000, sehingga Anda bisa menguji penyalinan tanpa risiko.' },
        { q: 'Apakah Pocket Option memungut biaya copy trading?', a: 'Tidak ada biaya langganan terpisah; Anda hanya mempertaruhkan nominal setiap trade salinan. Ketentuan bisa berubah — cek aturan platform.' },
        { q: 'Bisakah saya berhenti menyalin kapan saja?', a: 'Ya. Klik Stop pada trader di daftar copy Anda. Trade yang sudah terbuka berjalan sampai expiry; trade baru tidak akan dibuka.' },
        { q: 'Kenapa trade salinan saya rugi padahal leader-nya profit?', a: 'Biasanya karena sedikit keterlambatan entry atau perbedaan harga pada expiry sangat pendek. Pilih leader yang trading dengan expiry 1–5 menit.' },
        { q: 'Berapa nominal yang sebaiknya dipakai untuk menyalin?', a: 'Nominal tetap $1–$3 per trade untuk saldo $100, dan tidak lebih dari 2–3 trader sekaligus.' },
        { q: 'Bisakah saya menjadi leader yang disalin orang lain?', a: 'Trader dengan profil publik dan riwayat positif muncul di peringkat secara otomatis; periksa pengaturan privasi di profil Anda.' },
      ],
    },
  },
};
