import type { BlogPost } from '../types';

const IMG_DEMO = '/images/quick-start/2_1.webp';
const IMG_SWITCH = '/images/quick-start/3_1.webp';

export const pocketOptionDemoAccount: BlogPost = {
  slug: 'pocket-option-demo-account',
  category: 'tutorial',
  cover: '/images/blog/pocket-option-demo-account.webp',
  publishedAt: '2026-09-23',
  updatedAt: '2026-09-23',
  readingMinutes: 7,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option demo account: how to open it, $50,000 virtual balance and a 2-week practice plan',
      metaTitle: 'Pocket Option demo account guide: open in 1 minute, $50,000 balance, practice plan',
      metaDescription:
        'How the Pocket Option demo account works: how to open it without a deposit, the $50,000 virtual balance, differences from the real account, how to refill demo funds and a two-week practice plan before going live.',
      excerpt:
        'A practical guide to the pocketoption demo: what it is, how to open it in one minute, what it can and cannot teach you, and a structured plan to make the practice count.',
      coverAlt: 'Finger pressing a blue DEMO key on a keyboard — Pocket Option demo account',
      keyTakeaways: [
        'The demo account is free, requires no deposit and gives $50,000 of virtual funds with real-time quotes.',
        'Demo and real accounts share the same terminal, assets, payouts and indicators — only the money is virtual.',
        'Demo balance can be refilled at any time; that is exactly why it teaches nothing about the emotions of real losses.',
        'Use the demo with a plan: fixed trade size, one or two assets, a journal — and switch to real with $5 only when results are stable.',
      ],
      blocks: [
        { type: 'p', text: 'The Pocket Option demo account is the fastest way to see the platform from the inside. It opens without a deposit, has a $50,000 virtual balance and uses the same live quotes as the real terminal. This guide explains how to open the pocketoption demo, what makes it different from real trading and how to structure practice so that the switch to real money is not a shock.' },
        { type: 'h2', id: 'what', text: 'What the Pocket Option demo account is' },
        { type: 'p', text: 'A demo account is a copy of the trading terminal that runs on virtual money. Every asset, expiration, payout, indicator and drawing tool available on the real account is available on demo. Trades are executed on the same price feed, so results reflect what would have happened with real funds. The difference is that losses cost nothing and profits cannot be withdrawn.' },
        { type: 'image', src: IMG_DEMO, alt: 'Pocket Option demo account with $50,000 virtual balance', caption: 'The demo account starts with $50,000 in virtual funds.' },
        { type: 'h2', id: 'open', text: 'How to open a Pocket Option demo account' },
        { type: 'ol', items: [
          'Register on Pocket Option with an email address or a Google/Facebook account. No deposit is required.',
          'Confirm the email and log in. The platform opens the terminal directly.',
          'Click the balance in the top right corner and select “Demo account”. The $50,000 virtual balance appears.',
          'Trade exactly as on the real account: choose an asset, set the time and amount, click Up or Down.',
          'Switch back to the real account from the same menu whenever you want to trade with real funds.',
        ] },
        { type: 'tip', title: 'One account — two balances', text: 'You do not need a separate login for the demo. Demo and real balances live in the same account and you switch between them in one click.' },
        { type: 'h2', id: 'difference', text: 'Demo vs real account: the honest comparison' },
        { type: 'table', head: ['Feature', 'Demo account', 'Real account'], rows: [
          ['Balance', '$50,000 virtual, refillable', 'Your deposit, from $5'],
          ['Quotes and payouts', 'Live, identical', 'Live, identical'],
          ['Assets and tools', '100+ assets, all indicators', '100+ assets, all indicators'],
          ['Withdrawals', 'Not possible', 'From $10, ~24 h processing'],
          ['Tournaments and bonuses', 'Free tournaments only', 'All tournaments, deposit bonuses'],
          ['Emotional pressure', 'None', 'Real — the main difference'],
        ] },
        { type: 'h2', id: 'refill', text: 'How to refill the demo balance' },
        { type: 'p', text: 'If the virtual balance drops, open the balance menu and click “Refill” (or “Top up demo”) — it returns to $50,000 instantly and as many times as you need. Use this consciously: a trader who refills every hour is practising clicking, not risk management. A useful habit is to treat the demo as if it were a $100 account and stop for the day after losing 5% of that.' },
        { type: 'h2', id: 'plan', text: 'A two-week demo practice plan' },
        { type: 'ol', items: [
          'Days 1–2: learn the terminal. Open 20 trades of $1–$10 on one asset with different expirations and note how payout changes during the day.',
          'Days 3–5: pick one strategy (for example, a moving-average crossover or support/resistance bounces on 1-minute candles) and trade only that.',
          'Days 6–9: fix the trade size at 1–2% of an imaginary $100 balance ($1–$2) and record every trade: asset, time, reason for entry, result.',
          'Days 10–12: review the journal. Remove the setups that lose, keep the ones with a positive result over at least 50 trades.',
          'Days 13–14: simulate a real week — a daily loss limit, a maximum number of trades, no refills.',
        ] },
        { type: 'image', src: IMG_SWITCH, alt: 'Switching from the demo to the real account on Pocket Option', caption: 'Move to the real account only when demo results are stable.' },
        { type: 'h2', id: 'switch', text: 'When to switch to a real account' },
        { type: 'p', text: 'There is no perfect moment, but three conditions help: your journal shows a stable result over 50–100 demo trades, you follow your own rules without refilling and you have an amount you can afford to lose. Pocket Option makes the step small — the minimum deposit is $5 and the minimum trade is $1, so the first real trades can be as low-stakes as the demo ones.' },
        { type: 'warn', title: 'Demo results are not a forecast', text: 'A good demo run proves you understand the terminal and a strategy; it does not guarantee profit on a real account. Trading involves a risk of losing the deposited funds — only trade with money you can afford to lose.' },
        { type: 'cta', text: 'Open your free Pocket Option demo account and start practising with $50,000 in virtual funds.', label: 'Open free demo account' },
      ],
      faq: [
        { q: 'Is the Pocket Option demo account free?', a: 'Yes. The demo account is free, requires no deposit and is available immediately after registration.' },
        { q: 'How much virtual money does the demo give?', a: '$50,000 in virtual funds. The balance can be refilled to $50,000 at any time.' },
        { q: 'Are demo quotes the same as real ones?', a: 'Yes. Demo and real accounts use the same live price feed, the same assets and the same payouts.' },
        { q: 'Can I withdraw money from the demo account?', a: 'No. Demo funds are virtual and cannot be withdrawn. Only the real-account balance can be withdrawn.' },
        { q: 'Is there a time limit on the demo account?', a: 'No, the pocketoption demo account has no expiry. You can use it alongside the real account for as long as you like.' },
        { q: 'How do I switch from demo to real?', a: 'Click the balance in the top right corner of the terminal and choose the real account. To trade, fund it with a deposit from $5.' },
      ],
    },
    pt: {
      title: 'Conta demo da Pocket Option: como abrir, saldo virtual de $50.000 e plano de prática de 2 semanas',
      metaTitle: 'Guia da conta demo Pocket Option: abra em 1 minuto, saldo de $50.000, plano de prática',
      metaDescription:
        'Como funciona a conta demo da Pocket Option: como abrir sem depósito, o saldo virtual de $50.000, diferenças para a conta real, como recarregar os fundos demo e um plano de prática de duas semanas antes de operar com dinheiro real.',
      excerpt:
        'Guia prático da demo pocketoption: o que é, como abrir em um minuto, o que ela ensina (e não ensina) e um plano estruturado para aproveitar a prática.',
      coverAlt: 'Dedo pressionando uma tecla azul DEMO no teclado — conta demo da Pocket Option',
      keyTakeaways: [
        'A conta demo é gratuita, não exige depósito e oferece $50.000 em fundos virtuais com cotações em tempo real.',
        'Demo e conta real compartilham o mesmo terminal, ativos, payouts e indicadores — só o dinheiro é virtual.',
        'O saldo demo pode ser recarregado a qualquer momento; por isso ela não ensina as emoções das perdas reais.',
        'Use a demo com um plano: tamanho fixo de operação, um ou dois ativos, diário — e passe para a real com $5 só quando os resultados forem estáveis.',
      ],
      blocks: [
        { type: 'p', text: 'A conta demo da Pocket Option é o caminho mais rápido para conhecer a plataforma por dentro. Abre sem depósito, tem saldo virtual de $50.000 e usa as mesmas cotações ao vivo do terminal real. Este guia explica como abrir a demo pocketoption, o que a diferencia da negociação real e como estruturar a prática para que a passagem ao dinheiro real não seja um choque.' },
        { type: 'h2', id: 'what', text: 'O que é a conta demo da Pocket Option' },
        { type: 'p', text: 'A conta demo é uma cópia do terminal de negociação que roda com dinheiro virtual. Todo ativo, expiração, payout, indicador e ferramenta de desenho disponível na conta real está disponível na demo. As operações são executadas no mesmo feed de preços, então os resultados refletem o que teria acontecido com fundos reais. A diferença é que as perdas não custam nada e os lucros não podem ser sacados.' },
        { type: 'image', src: IMG_DEMO, alt: 'Conta demo da Pocket Option com saldo virtual de $50.000', caption: 'A conta demo começa com $50.000 em fundos virtuais.' },
        { type: 'h2', id: 'open', text: 'Como abrir uma conta demo na Pocket Option' },
        { type: 'ol', items: [
          'Cadastre-se na Pocket Option com e-mail ou conta Google/Facebook. Nenhum depósito é necessário.',
          'Confirme o e-mail e faça login. A plataforma abre o terminal diretamente.',
          'Clique no saldo no canto superior direito e selecione “Conta demo”. O saldo virtual de $50.000 aparece.',
          'Opere exatamente como na conta real: escolha o ativo, defina tempo e valor, clique em Para cima ou Para baixo.',
          'Volte à conta real pelo mesmo menu sempre que quiser operar com fundos reais.',
        ] },
        { type: 'tip', title: 'Uma conta — dois saldos', text: 'Você não precisa de login separado para a demo. Saldos demo e real ficam na mesma conta e a troca é feita com um clique.' },
        { type: 'h2', id: 'difference', text: 'Demo vs conta real: a comparação honesta' },
        { type: 'table', head: ['Recurso', 'Conta demo', 'Conta real'], rows: [
          ['Saldo', '$50.000 virtual, recarregável', 'Seu depósito, a partir de $5'],
          ['Cotações e payouts', 'Ao vivo, idênticos', 'Ao vivo, idênticos'],
          ['Ativos e ferramentas', '100+ ativos, todos os indicadores', '100+ ativos, todos os indicadores'],
          ['Saques', 'Não é possível', 'A partir de $10, ~24 h de processamento'],
          ['Torneios e bônus', 'Apenas torneios gratuitos', 'Todos os torneios, bônus de depósito'],
          ['Pressão emocional', 'Nenhuma', 'Real — a principal diferença'],
        ] },
        { type: 'h2', id: 'refill', text: 'Como recarregar o saldo demo' },
        { type: 'p', text: 'Se o saldo virtual cair, abra o menu de saldo e clique em “Recarregar” — ele volta a $50.000 na hora, quantas vezes precisar. Use isso com consciência: quem recarrega a cada hora está praticando cliques, não gestão de risco. Um bom hábito é tratar a demo como se fosse uma conta de $100 e parar pelo dia após perder 5% disso.' },
        { type: 'h2', id: 'plan', text: 'Plano de prática demo de duas semanas' },
        { type: 'ol', items: [
          'Dias 1–2: aprenda o terminal. Abra 20 operações de $1–$10 em um ativo com expirações diferentes e note como o payout muda ao longo do dia.',
          'Dias 3–5: escolha uma estratégia (por exemplo, cruzamento de médias móveis ou repiques em suporte/resistência em velas de 1 minuto) e opere só ela.',
          'Dias 6–9: fixe o tamanho da operação em 1–2% de um saldo imaginário de $100 ($1–$2) e registre cada operação: ativo, horário, motivo da entrada, resultado.',
          'Dias 10–12: revise o diário. Elimine os setups que perdem, mantenha os que têm resultado positivo em pelo menos 50 operações.',
          'Dias 13–14: simule uma semana real — limite diário de perda, número máximo de operações, sem recargas.',
        ] },
        { type: 'image', src: IMG_SWITCH, alt: 'Trocando da conta demo para a conta real na Pocket Option', caption: 'Passe para a conta real só quando os resultados na demo forem estáveis.' },
        { type: 'h2', id: 'switch', text: 'Quando passar para a conta real' },
        { type: 'p', text: 'Não existe momento perfeito, mas três condições ajudam: seu diário mostra resultado estável em 50–100 operações demo, você segue as próprias regras sem recarregar e tem um valor que pode perder. A Pocket Option torna o passo pequeno — depósito mínimo de $5 e operação mínima de $1, então as primeiras operações reais podem ter apostas tão baixas quanto na demo.' },
        { type: 'warn', title: 'Resultados na demo não são previsão', text: 'Um bom desempenho na demo prova que você entende o terminal e uma estratégia; não garante lucro na conta real. Negociar envolve risco de perder os fundos depositados — opere apenas com dinheiro que pode perder.' },
        { type: 'cta', text: 'Abra sua conta demo gratuita na Pocket Option e comece a praticar com $50.000 em fundos virtuais.', label: 'Abrir conta demo grátis' },
      ],
      faq: [
        { q: 'A conta demo da Pocket Option é gratuita?', a: 'Sim. A conta demo é gratuita, não exige depósito e fica disponível logo após o cadastro.' },
        { q: 'Quanto dinheiro virtual a demo oferece?', a: '$50.000 em fundos virtuais. O saldo pode ser recarregado para $50.000 a qualquer momento.' },
        { q: 'As cotações da demo são iguais às reais?', a: 'Sim. Demo e conta real usam o mesmo feed de preços ao vivo, os mesmos ativos e os mesmos payouts.' },
        { q: 'Posso sacar dinheiro da conta demo?', a: 'Não. Os fundos demo são virtuais e não podem ser sacados. Apenas o saldo da conta real pode ser sacado.' },
        { q: 'A conta demo tem prazo de validade?', a: 'Não, a demo pocketoption não expira. Você pode usá-la junto com a conta real pelo tempo que quiser.' },
        { q: 'Como troco da demo para a real?', a: 'Clique no saldo no canto superior direito do terminal e escolha a conta real. Para operar, faça um depósito a partir de $5.' },
      ],
    },
    es: {
      title: 'Cuenta demo de Pocket Option: cómo abrirla, saldo virtual de $50.000 y plan de práctica de 2 semanas',
      metaTitle: 'Guía de la cuenta demo Pocket Option: ábrela en 1 minuto, saldo de $50.000, plan de práctica',
      metaDescription:
        'Cómo funciona la cuenta demo de Pocket Option: cómo abrirla sin depósito, el saldo virtual de $50.000, diferencias con la cuenta real, cómo recargar los fondos demo y un plan de práctica de dos semanas antes de operar en real.',
      excerpt:
        'Guía práctica de la demo pocketoption: qué es, cómo abrirla en un minuto, qué enseña (y qué no) y un plan estructurado para que la práctica cuente.',
      coverAlt: 'Dedo pulsando una tecla azul DEMO en un teclado — cuenta demo de Pocket Option',
      keyTakeaways: [
        'La cuenta demo es gratuita, no exige depósito y ofrece $50.000 en fondos virtuales con cotizaciones en tiempo real.',
        'Demo y cuenta real comparten el mismo terminal, activos, pagos e indicadores — solo el dinero es virtual.',
        'El saldo demo se puede recargar en cualquier momento; por eso no enseña las emociones de las pérdidas reales.',
        'Usa la demo con un plan: tamaño fijo de operación, uno o dos activos, un diario — y pasa a real con $5 solo cuando los resultados sean estables.',
      ],
      blocks: [
        { type: 'p', text: 'La cuenta demo de Pocket Option es la forma más rápida de ver la plataforma desde dentro. Se abre sin depósito, tiene un saldo virtual de $50.000 y usa las mismas cotizaciones en vivo que el terminal real. Esta guía explica cómo abrir la demo pocketoption, qué la diferencia de operar en real y cómo estructurar la práctica para que el paso al dinero real no sea un choque.' },
        { type: 'h2', id: 'what', text: 'Qué es la cuenta demo de Pocket Option' },
        { type: 'p', text: 'Una cuenta demo es una copia del terminal de trading que funciona con dinero virtual. Todos los activos, expiraciones, pagos, indicadores y herramientas de dibujo de la cuenta real están disponibles en la demo. Las operaciones se ejecutan sobre el mismo feed de precios, así que los resultados reflejan lo que habría pasado con fondos reales. La diferencia es que las pérdidas no cuestan nada y los beneficios no se pueden retirar.' },
        { type: 'image', src: IMG_DEMO, alt: 'Cuenta demo de Pocket Option con saldo virtual de $50.000', caption: 'La cuenta demo empieza con $50.000 en fondos virtuales.' },
        { type: 'h2', id: 'open', text: 'Cómo abrir una cuenta demo en Pocket Option' },
        { type: 'ol', items: [
          'Regístrate en Pocket Option con un correo o una cuenta de Google/Facebook. No se requiere depósito.',
          'Confirma el correo e inicia sesión. La plataforma abre el terminal directamente.',
          'Haz clic en el saldo de la esquina superior derecha y selecciona “Cuenta demo”. Aparece el saldo virtual de $50.000.',
          'Opera exactamente como en la cuenta real: elige un activo, fija tiempo e importe, pulsa Arriba o Abajo.',
          'Vuelve a la cuenta real desde el mismo menú cuando quieras operar con fondos reales.',
        ] },
        { type: 'tip', title: 'Una cuenta — dos saldos', text: 'No necesitas un acceso separado para la demo. Los saldos demo y real viven en la misma cuenta y cambias entre ellos con un clic.' },
        { type: 'h2', id: 'difference', text: 'Demo vs cuenta real: la comparación honesta' },
        { type: 'table', head: ['Característica', 'Cuenta demo', 'Cuenta real'], rows: [
          ['Saldo', '$50.000 virtual, recargable', 'Tu depósito, desde $5'],
          ['Cotizaciones y pagos', 'En vivo, idénticos', 'En vivo, idénticos'],
          ['Activos y herramientas', '100+ activos, todos los indicadores', '100+ activos, todos los indicadores'],
          ['Retiros', 'No es posible', 'Desde $10, ~24 h de procesamiento'],
          ['Torneos y bonos', 'Solo torneos gratuitos', 'Todos los torneos, bonos de depósito'],
          ['Presión emocional', 'Ninguna', 'Real — la principal diferencia'],
        ] },
        { type: 'h2', id: 'refill', text: 'Cómo recargar el saldo demo' },
        { type: 'p', text: 'Si el saldo virtual baja, abre el menú de saldo y pulsa “Recargar” — vuelve a $50.000 al instante y tantas veces como necesites. Úsalo con conciencia: quien recarga cada hora practica hacer clic, no gestión del riesgo. Un buen hábito es tratar la demo como si fuera una cuenta de $100 y parar por el día tras perder el 5% de eso.' },
        { type: 'h2', id: 'plan', text: 'Plan de práctica demo de dos semanas' },
        { type: 'ol', items: [
          'Días 1–2: aprende el terminal. Abre 20 operaciones de $1–$10 en un activo con distintas expiraciones y anota cómo cambia el pago durante el día.',
          'Días 3–5: elige una estrategia (por ejemplo, cruce de medias móviles o rebotes en soporte/resistencia en velas de 1 minuto) y opera solo esa.',
          'Días 6–9: fija el tamaño de operación en 1–2% de un saldo imaginario de $100 ($1–$2) y registra cada operación: activo, hora, motivo de entrada, resultado.',
          'Días 10–12: revisa el diario. Elimina los setups que pierden, conserva los que tienen resultado positivo en al menos 50 operaciones.',
          'Días 13–14: simula una semana real — límite diario de pérdida, número máximo de operaciones, sin recargas.',
        ] },
        { type: 'image', src: IMG_SWITCH, alt: 'Cambio de la cuenta demo a la cuenta real en Pocket Option', caption: 'Pasa a la cuenta real solo cuando los resultados en demo sean estables.' },
        { type: 'h2', id: 'switch', text: 'Cuándo pasar a una cuenta real' },
        { type: 'p', text: 'No hay un momento perfecto, pero tres condiciones ayudan: tu diario muestra un resultado estable en 50–100 operaciones demo, sigues tus propias reglas sin recargar y dispones de una cantidad que puedes permitirte perder. Pocket Option hace el paso pequeño — el depósito mínimo es $5 y la operación mínima $1, así que las primeras operaciones reales pueden ser tan pequeñas como las de la demo.' },
        { type: 'warn', title: 'Los resultados en demo no son un pronóstico', text: 'Una buena racha en demo demuestra que entiendes el terminal y una estrategia; no garantiza beneficios en la cuenta real. Operar implica riesgo de perder los fondos depositados — opera solo con dinero que puedas permitirte perder.' },
        { type: 'cta', text: 'Abre tu cuenta demo gratuita de Pocket Option y empieza a practicar con $50.000 en fondos virtuales.', label: 'Abrir cuenta demo gratis' },
      ],
      faq: [
        { q: '¿La cuenta demo de Pocket Option es gratuita?', a: 'Sí. La cuenta demo es gratuita, no requiere depósito y está disponible inmediatamente tras registrarte.' },
        { q: '¿Cuánto dinero virtual ofrece la demo?', a: '$50.000 en fondos virtuales. El saldo se puede recargar a $50.000 en cualquier momento.' },
        { q: '¿Las cotizaciones de la demo son iguales a las reales?', a: 'Sí. Demo y cuenta real usan el mismo feed de precios en vivo, los mismos activos y los mismos pagos.' },
        { q: '¿Puedo retirar dinero de la cuenta demo?', a: 'No. Los fondos demo son virtuales y no se pueden retirar. Solo el saldo de la cuenta real es retirable.' },
        { q: '¿La cuenta demo tiene límite de tiempo?', a: 'No, la demo pocketoption no caduca. Puedes usarla junto a la cuenta real todo el tiempo que quieras.' },
        { q: '¿Cómo paso de demo a real?', a: 'Haz clic en el saldo de la esquina superior derecha del terminal y elige la cuenta real. Para operar, fondéala con un depósito desde $5.' },
      ],
    },
    ru: {
      title: 'Демо-счёт Pocket Option: как открыть, виртуальный баланс $50 000 и план практики на 2 недели',
      metaTitle: 'Демо-счёт Pocket Option: открыть за 1 минуту, баланс $50 000, план практики',
      metaDescription:
        'Как работает демо-счёт Pocket Option: как открыть без депозита, виртуальный баланс $50 000, отличия от реального счёта, как пополнить демо-средства и двухнедельный план практики перед переходом на реальные деньги.',
      excerpt:
        'Практическое руководство по демо pocketoption: что это, как открыть за минуту, чему демо учит (и чему нет) и структурированный план, чтобы практика была полезной.',
      coverAlt: 'Палец нажимает синюю клавишу DEMO на клавиатуре — демо-счёт Pocket Option',
      keyTakeaways: [
        'Демо-счёт бесплатный, не требует депозита и даёт $50 000 виртуальных средств с котировками в реальном времени.',
        'Демо и реальный счёт используют один терминал, активы, выплаты и индикаторы — виртуальны только деньги.',
        'Демо-баланс можно пополнить в любой момент; именно поэтому демо не учит эмоциям реальных убытков.',
        'Используйте демо по плану: фиксированный размер сделки, один-два актива, дневник — и переходите на реальный счёт с $5 только при стабильных результатах.',
      ],
      blocks: [
        { type: 'p', text: 'Демо-счёт Pocket Option — самый быстрый способ увидеть платформу изнутри. Он открывается без депозита, имеет виртуальный баланс $50 000 и использует те же живые котировки, что и реальный терминал. В этом руководстве — как открыть демо pocketoption, чем оно отличается от реальной торговли и как выстроить практику, чтобы переход на реальные деньги не стал шоком.' },
        { type: 'h2', id: 'what', text: 'Что такое демо-счёт Pocket Option' },
        { type: 'p', text: 'Демо-счёт — копия торгового терминала, работающая на виртуальных деньгах. Все активы, экспирации, выплаты, индикаторы и инструменты рисования реального счёта доступны на демо. Сделки исполняются по тому же потоку цен, поэтому результаты отражают то, что произошло бы с реальными средствами. Разница в том, что убытки ничего не стоят, а прибыль нельзя вывести.' },
        { type: 'image', src: IMG_DEMO, alt: 'Демо-счёт Pocket Option с виртуальным балансом $50 000', caption: 'Демо-счёт начинается с $50 000 виртуальных средств.' },
        { type: 'h2', id: 'open', text: 'Как открыть демо-счёт на Pocket Option' },
        { type: 'ol', items: [
          'Зарегистрируйтесь на Pocket Option по электронной почте или через аккаунт Google/Facebook. Депозит не нужен.',
          'Подтвердите почту и войдите. Платформа сразу откроет терминал.',
          'Нажмите на баланс в правом верхнем углу и выберите «Демо-счёт». Появится виртуальный баланс $50 000.',
          'Торгуйте так же, как на реальном счёте: выберите актив, задайте время и сумму, нажмите «Вверх» или «Вниз».',
          'Возвращайтесь на реальный счёт через то же меню, когда захотите торговать реальными средствами.',
        ] },
        { type: 'tip', title: 'Один аккаунт — два баланса', text: 'Для демо не нужен отдельный логин. Демо- и реальный балансы находятся в одном аккаунте, переключение — в один клик.' },
        { type: 'h2', id: 'difference', text: 'Демо и реальный счёт: честное сравнение' },
        { type: 'table', head: ['Параметр', 'Демо-счёт', 'Реальный счёт'], rows: [
          ['Баланс', '$50 000 виртуальных, пополняемый', 'Ваш депозит, от $5'],
          ['Котировки и выплаты', 'Живые, одинаковые', 'Живые, одинаковые'],
          ['Активы и инструменты', '100+ активов, все индикаторы', '100+ активов, все индикаторы'],
          ['Вывод средств', 'Невозможен', 'От $10, обработка ~24 ч'],
          ['Турниры и бонусы', 'Только бесплатные турниры', 'Все турниры, бонусы на депозит'],
          ['Эмоциональное давление', 'Нет', 'Есть — главное отличие'],
        ] },
        { type: 'h2', id: 'refill', text: 'Как пополнить демо-баланс' },
        { type: 'p', text: 'Если виртуальный баланс уменьшился, откройте меню баланса и нажмите «Пополнить» — он мгновенно вернётся к $50 000, и так сколько угодно раз. Пользуйтесь этим осознанно: трейдер, пополняющий демо каждый час, тренирует клики, а не управление риском. Полезная привычка — относиться к демо как к счёту на $100 и заканчивать день после потери 5% от него.' },
        { type: 'h2', id: 'plan', text: 'План практики на демо на две недели' },
        { type: 'ol', items: [
          'Дни 1–2: изучите терминал. Откройте 20 сделок по $1–$10 на одном активе с разными экспирациями и отметьте, как меняется выплата в течение дня.',
          'Дни 3–5: выберите одну стратегию (например, пересечение скользящих средних или отскоки от поддержки/сопротивления на минутных свечах) и торгуйте только по ней.',
          'Дни 6–9: зафиксируйте размер сделки на уровне 1–2% от воображаемого баланса $100 ($1–$2) и записывайте каждую сделку: актив, время, причина входа, результат.',
          'Дни 10–12: проанализируйте дневник. Уберите убыточные сетапы, оставьте те, что дают положительный результат минимум на 50 сделках.',
          'Дни 13–14: смоделируйте реальную неделю — дневной лимит убытка, максимум сделок, без пополнений.',
        ] },
        { type: 'image', src: IMG_SWITCH, alt: 'Переключение с демо на реальный счёт на Pocket Option', caption: 'Переходите на реальный счёт только при стабильных результатах на демо.' },
        { type: 'h2', id: 'switch', text: 'Когда переходить на реальный счёт' },
        { type: 'p', text: 'Идеального момента нет, но помогают три условия: дневник показывает стабильный результат на 50–100 демо-сделках, вы соблюдаете собственные правила без пополнений и у вас есть сумма, которую вы можете позволить себе потерять. Pocket Option делает шаг небольшим — минимальный депозит $5 и минимальная сделка $1, так что первые реальные сделки могут быть такими же скромными, как на демо.' },
        { type: 'warn', title: 'Результаты на демо — не прогноз', text: 'Хорошая серия на демо доказывает, что вы понимаете терминал и стратегию; она не гарантирует прибыль на реальном счёте. Торговля связана с риском потери внесённых средств — торгуйте только деньгами, которые можете позволить себе потерять.' },
        { type: 'cta', text: 'Откройте бесплатный демо-счёт Pocket Option и начните практику с $50 000 виртуальных средств.', label: 'Открыть бесплатный демо-счёт' },
      ],
      faq: [
        { q: 'Демо-счёт Pocket Option бесплатный?', a: 'Да. Демо-счёт бесплатный, не требует депозита и доступен сразу после регистрации.' },
        { q: 'Сколько виртуальных денег даёт демо?', a: '$50 000 виртуальных средств. Баланс можно в любой момент восстановить до $50 000.' },
        { q: 'Котировки на демо такие же, как на реальном счёте?', a: 'Да. Демо и реальный счёт используют один живой поток цен, одни активы и одни выплаты.' },
        { q: 'Можно ли вывести деньги с демо-счёта?', a: 'Нет. Демо-средства виртуальны и не выводятся. Вывести можно только баланс реального счёта.' },
        { q: 'Есть ли у демо-счёта ограничение по времени?', a: 'Нет, демо-счёт pocketoption не имеет срока действия. Им можно пользоваться параллельно с реальным счётом сколько угодно.' },
        { q: 'Как перейти с демо на реальный счёт?', a: 'Нажмите на баланс в правом верхнем углу терминала и выберите реальный счёт. Для торговли пополните его депозитом от $5.' },
      ],
    },
    id: {
      title: 'Akun demo Pocket Option: cara membukanya, saldo virtual $50.000, dan rencana latihan 2 minggu',
      metaTitle: 'Panduan akun demo Pocket Option: buka dalam 1 menit, saldo $50.000, rencana latihan',
      metaDescription:
        'Cara kerja akun demo Pocket Option: cara membukanya tanpa deposit, saldo virtual $50.000, perbedaan dengan akun riil, cara mengisi ulang dana demo, dan rencana latihan dua minggu sebelum trading riil.',
      excerpt:
        'Panduan praktis demo pocketoption: apa itu, cara membukanya dalam satu menit, apa yang bisa dan tidak bisa diajarkannya, serta rencana terstruktur agar latihan berarti.',
      coverAlt: 'Jari menekan tombol DEMO biru di keyboard — akun demo Pocket Option',
      keyTakeaways: [
        'Akun demo gratis, tidak butuh deposit, dan memberi $50.000 dana virtual dengan kuotasi real-time.',
        'Akun demo dan riil memakai terminal, aset, payout, dan indikator yang sama — hanya uangnya yang virtual.',
        'Saldo demo bisa diisi ulang kapan saja; itulah sebabnya demo tidak mengajarkan emosi kerugian nyata.',
        'Gunakan demo dengan rencana: ukuran trade tetap, satu atau dua aset, jurnal — dan beralih ke riil dengan $5 hanya ketika hasilnya stabil.',
      ],
      blocks: [
        { type: 'p', text: 'Akun demo Pocket Option adalah cara tercepat melihat platform dari dalam. Dibuka tanpa deposit, memiliki saldo virtual $50.000, dan memakai kuotasi langsung yang sama dengan terminal riil. Panduan ini menjelaskan cara membuka demo pocketoption, apa yang membedakannya dari trading riil, dan cara menyusun latihan agar peralihan ke uang riil tidak mengejutkan.' },
        { type: 'h2', id: 'what', text: 'Apa itu akun demo Pocket Option' },
        { type: 'p', text: 'Akun demo adalah salinan terminal trading yang berjalan dengan uang virtual. Semua aset, waktu kedaluwarsa, payout, indikator, dan alat gambar yang tersedia di akun riil juga tersedia di demo. Trade dieksekusi pada feed harga yang sama, sehingga hasilnya mencerminkan apa yang akan terjadi dengan dana riil. Perbedaannya: kerugian tidak berbiaya dan profit tidak bisa ditarik.' },
        { type: 'image', src: IMG_DEMO, alt: 'Akun demo Pocket Option dengan saldo virtual $50.000', caption: 'Akun demo dimulai dengan $50.000 dana virtual.' },
        { type: 'h2', id: 'open', text: 'Cara membuka akun demo Pocket Option' },
        { type: 'ol', items: [
          'Daftar di Pocket Option dengan alamat email atau akun Google/Facebook. Tidak perlu deposit.',
          'Konfirmasi email dan masuk. Platform langsung membuka terminal.',
          'Klik saldo di pojok kanan atas dan pilih “Akun demo”. Saldo virtual $50.000 muncul.',
          'Trading persis seperti di akun riil: pilih aset, atur waktu dan jumlah, klik Naik atau Turun.',
          'Kembali ke akun riil dari menu yang sama kapan pun Anda ingin trading dengan dana riil.',
        ] },
        { type: 'tip', title: 'Satu akun — dua saldo', text: 'Anda tidak perlu login terpisah untuk demo. Saldo demo dan riil berada di akun yang sama dan berpindah cukup satu klik.' },
        { type: 'h2', id: 'difference', text: 'Demo vs akun riil: perbandingan jujur' },
        { type: 'table', head: ['Fitur', 'Akun demo', 'Akun riil'], rows: [
          ['Saldo', '$50.000 virtual, bisa diisi ulang', 'Deposit Anda, mulai $5'],
          ['Kuotasi dan payout', 'Langsung, identik', 'Langsung, identik'],
          ['Aset dan alat', '100+ aset, semua indikator', '100+ aset, semua indikator'],
          ['Penarikan', 'Tidak bisa', 'Mulai $10, proses ~24 jam'],
          ['Turnamen dan bonus', 'Hanya turnamen gratis', 'Semua turnamen, bonus deposit'],
          ['Tekanan emosional', 'Tidak ada', 'Nyata — perbedaan utama'],
        ] },
        { type: 'h2', id: 'refill', text: 'Cara mengisi ulang saldo demo' },
        { type: 'p', text: 'Jika saldo virtual turun, buka menu saldo dan klik “Isi ulang” — saldo langsung kembali ke $50.000, sebanyak yang Anda perlukan. Gunakan dengan sadar: trader yang mengisi ulang tiap jam melatih klik, bukan manajemen risiko. Kebiasaan yang berguna: perlakukan demo seolah akun $100 dan berhenti untuk hari itu setelah kehilangan 5% darinya.' },
        { type: 'h2', id: 'plan', text: 'Rencana latihan demo dua minggu' },
        { type: 'ol', items: [
          'Hari 1–2: pelajari terminal. Buka 20 trade $1–$10 pada satu aset dengan kedaluwarsa berbeda dan catat bagaimana payout berubah sepanjang hari.',
          'Hari 3–5: pilih satu strategi (misalnya persilangan moving average atau pantulan support/resistance pada candle 1 menit) dan trading hanya dengan itu.',
          'Hari 6–9: tetapkan ukuran trade 1–2% dari saldo bayangan $100 ($1–$2) dan catat setiap trade: aset, waktu, alasan masuk, hasil.',
          'Hari 10–12: tinjau jurnal. Buang setup yang rugi, pertahankan yang hasilnya positif dalam minimal 50 trade.',
          'Hari 13–14: simulasikan minggu riil — batas rugi harian, jumlah trade maksimum, tanpa isi ulang.',
        ] },
        { type: 'image', src: IMG_SWITCH, alt: 'Beralih dari akun demo ke akun riil di Pocket Option', caption: 'Pindah ke akun riil hanya ketika hasil demo sudah stabil.' },
        { type: 'h2', id: 'switch', text: 'Kapan beralih ke akun riil' },
        { type: 'p', text: 'Tidak ada momen sempurna, tetapi tiga kondisi membantu: jurnal Anda menunjukkan hasil stabil dalam 50–100 trade demo, Anda mengikuti aturan sendiri tanpa isi ulang, dan Anda punya jumlah yang sanggup hilang. Pocket Option membuat langkahnya kecil — deposit minimum $5 dan trade minimum $1, sehingga trade riil pertama bisa sama kecil taruhannya dengan demo.' },
        { type: 'warn', title: 'Hasil demo bukan ramalan', text: 'Performa demo yang baik membuktikan Anda memahami terminal dan sebuah strategi; itu tidak menjamin profit di akun riil. Trading mengandung risiko kehilangan dana yang disetor — trading hanya dengan uang yang sanggup Anda hilangkan.' },
        { type: 'cta', text: 'Buka akun demo Pocket Option gratis Anda dan mulai berlatih dengan $50.000 dana virtual.', label: 'Buka akun demo gratis' },
      ],
      faq: [
        { q: 'Apakah akun demo Pocket Option gratis?', a: 'Ya. Akun demo gratis, tidak memerlukan deposit, dan tersedia segera setelah pendaftaran.' },
        { q: 'Berapa uang virtual yang diberikan demo?', a: '$50.000 dana virtual. Saldo bisa diisi ulang ke $50.000 kapan saja.' },
        { q: 'Apakah kuotasi demo sama dengan riil?', a: 'Ya. Akun demo dan riil memakai feed harga langsung, aset, dan payout yang sama.' },
        { q: 'Bisakah saya menarik uang dari akun demo?', a: 'Tidak. Dana demo bersifat virtual dan tidak bisa ditarik. Hanya saldo akun riil yang bisa ditarik.' },
        { q: 'Apakah akun demo ada batas waktunya?', a: 'Tidak, akun demo pocketoption tidak kedaluwarsa. Anda bisa memakainya bersama akun riil selama yang Anda mau.' },
        { q: 'Bagaimana beralih dari demo ke riil?', a: 'Klik saldo di pojok kanan atas terminal dan pilih akun riil. Untuk trading, isi dengan deposit mulai $5.' },
      ],
    },
  },
};
