import type { BlogPost } from '../types';

const IMG_DEPOSIT = '/images/quick-start/4_1.webp';
const IMG_CONFIRM = '/images/quick-start/4_2.webp';

export const pocketOptionDeposit: BlogPost = {
  slug: 'pocket-option-deposit',
  category: 'payments',
  cover: '/images/blog/pocket-option-deposit-guide.webp',
  publishedAt: '2026-09-22',
  updatedAt: '2026-09-22',
  readingMinutes: 7,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option deposit: how to fund your account from $5, methods, time and fees',
      metaTitle: 'Pocket Option Deposit Guide – Minimum $5, Methods and Fees',
      metaDescription:
        'How to deposit on Pocket Option step by step: minimum $5, cards, crypto, e-wallets and local methods, processing time, bonus rules and what to do if money is missing.',
      excerpt:
        'Everything about funding a pocketoption account: the $5 minimum, which payment methods are fastest, deposit bonuses and the reasons a deposit can be delayed.',
      coverAlt: 'Bitcoin, USDT, Ethereum and other crypto coins — deposit methods on Pocket Option',
      keyTakeaways: [
        'The minimum deposit on Pocket Option is $5 for most methods; the platform charges no deposit fee.',
        'Cards, crypto, e-wallets and local methods (Pix, UPI, M-Pesa…) are available depending on your country.',
        'Crypto and e-wallet deposits are credited within minutes; card deposits usually instantly, sometimes up to a few hours.',
        'A deposit bonus comes with a trading turnover requirement — read it before accepting.',
      ],
      blocks: [
        { type: 'p', text: 'Depositing on Pocket Option takes about two minutes: open Finance → Deposit, pick a payment method, enter the amount and confirm on the provider’s side. The minimum is only $5, which makes pocketoption one of the most accessible platforms for a first real trade. This guide covers every step, the available methods, processing times, bonus conditions and troubleshooting.' },
        { type: 'h2', id: 'minimum', text: 'Minimum deposit and fees on Pocket Option' },
        { type: 'p', text: 'The minimum deposit is $5 (or the equivalent in your currency) for the majority of methods; some local providers set their own minimum of $10. Pocket Option does not charge a fee for deposits — the only costs that can appear are third-party ones: a blockchain network fee, a currency conversion by your bank or an e-wallet commission. The minimum trade after funding is $1.' },
        { type: 'tip', title: 'Start small', text: 'A $5–$20 first deposit is enough to test the full cycle — deposit, a few $1 trades, withdrawal — before committing a larger sum.' },
        { type: 'h2', id: 'steps', text: 'How to deposit on Pocket Option step by step' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Pocket Option deposit page with payment methods and amount field', caption: 'Finance → Deposit: choose the method and enter the amount.' },
        { type: 'ol', items: [
          'Log in to your pocketoption account and open Finance → Deposit in the left menu.',
          'Select a payment method. The list is filtered by your country and account currency.',
          'Enter the amount (at least $5). If a bonus is offered, decide whether to activate it — see the bonus section below.',
          'Click Deposit and complete the payment on the provider’s page: card 3-D Secure code, wallet login or a crypto transfer to the address shown.',
          'Return to the platform. The funds appear in the real balance and the transaction shows as “Completed” in Finance → Transaction history.',
        ] },
        { type: 'image', src: IMG_CONFIRM, alt: 'Deposit confirmed on Pocket Option — real balance updated', caption: 'A completed deposit is visible immediately in the account balance.' },
        { type: 'h2', id: 'methods', text: 'Payment methods and how long a deposit takes' },
        { type: 'p', text: 'Pocket Option lists 50+ methods. What you see depends on your region, but they fall into four groups:' },
        { type: 'table', head: ['Method', 'Typical crediting time', 'Notes'], rows: [
          ['Visa / Mastercard', 'Instant – a few hours', '3-D Secure confirmation; card must be in your name'],
          ['Cryptocurrency (USDT, BTC, ETH, LTC…)', 'After network confirmations, ~5–30 min', 'Send the exact amount to the address shown; check the network (TRC-20, ERC-20…)'],
          ['E-wallets (Skrill, Neteller, Perfect Money, AdvCash)', 'Instant', 'Wallet must be in your name'],
          ['Local methods (Pix, UPI, Mercado Pago, M-Pesa, bKash…)', 'Instant – 1 hour', 'Availability depends on the country'],
          ['Bank transfer', '1–3 business days', 'Selected countries only'],
        ] },
        { type: 'warn', title: 'Crypto deposits: pick the right network', text: 'USDT exists on several networks (TRC-20, ERC-20, BEP-20). Sending to an address of a different network than the one selected in the deposit form usually means the funds are lost. Double-check before confirming.' },
        { type: 'h2', id: 'bonus', text: 'Deposit bonus and promo codes' },
        { type: 'p', text: 'Pocket Option regularly offers a percentage bonus on the deposit (for example +50%), activated with a promo code or from the offers shown on the deposit page. Bonus funds are added to the trading balance, but to withdraw them you have to trade a turnover several times the bonus amount. If you plan to withdraw soon, it is often simpler to deposit without a bonus. The bonus terms are always displayed before activation — read them.' },
        { type: 'h2', id: 'problems', text: 'Deposit not credited: what to check' },
        { type: 'ul', items: [
          'Card payment declined — the issuer blocked an online or foreign transaction; call the bank or use another method.',
          'Crypto transfer still pending — wait for the required number of network confirmations; check the hash in a blockchain explorer.',
          'Wrong amount sent for a crypto deposit — contact support with the transaction hash; it is usually credited manually.',
          'Payment completed but balance unchanged — refresh the page, check Transaction history and allow up to one hour for the provider to notify the platform.',
          'Third-party card or wallet — payments from accounts not in your name may be rejected during verification.',
        ] },
        { type: 'p', text: 'If the problem persists, open the support chat inside the platform and provide the payment date, method, amount and transaction ID.' },
        { type: 'cta', text: 'Ready to make your first Pocket Option deposit? Register, choose your method and start from $5.', label: 'Open Pocket Option account' },
      ],
      faq: [
        { q: 'What is the minimum deposit on Pocket Option?', a: 'The minimum deposit is $5 for most payment methods. Some local providers set a minimum of $10.' },
        { q: 'Does Pocket Option charge a deposit fee?', a: 'No, the platform does not charge for deposits. Network, bank conversion or e-wallet fees may apply on the provider side.' },
        { q: 'How long does a Pocket Option deposit take?', a: 'Cards, e-wallets and local methods are usually credited instantly; crypto within about 5–30 minutes after network confirmations; bank transfers within 1–3 business days.' },
        { q: 'Which payment methods can I use?', a: 'Visa/Mastercard, cryptocurrencies (USDT, BTC, ETH, LTC and others), e-wallets and local methods such as Pix, UPI, Mercado Pago, M-Pesa or bKash — the exact list depends on your country.' },
        { q: 'Should I take the deposit bonus?', a: 'The bonus increases the trading balance but requires a trading turnover before the bonus part can be withdrawn. Take it only if you plan to trade actively and understand the terms.' },
        { q: 'Can I deposit with someone else’s card?', a: 'No. Payments should come from a card or wallet in your own name; otherwise the deposit or a later withdrawal can be rejected during verification.' },
      ],
    },
    pt: {
      title: 'Depósito na Pocket Option: como financiar a conta a partir de $5, métodos, prazos e taxas',
      metaTitle: 'Guia de Depósito Pocket Option – Mínimo $5, Métodos e Taxas',
      metaDescription:
        'Como depositar na Pocket Option passo a passo: mínimo de $5, cartões, cripto, carteiras eletrônicas e métodos locais, prazos, regras de bônus e problemas comuns.',
      excerpt:
        'Tudo sobre como financiar uma conta pocketoption: o mínimo de $5, quais métodos são mais rápidos, bônus de depósito e os motivos de atraso.',
      coverAlt: 'Moedas Bitcoin, USDT, Ethereum e outras criptos — métodos de depósito na Pocket Option',
      keyTakeaways: [
        'O depósito mínimo na Pocket Option é $5 na maioria dos métodos; a plataforma não cobra taxa de depósito.',
        'Cartões, cripto, carteiras eletrônicas e métodos locais (Pix, UPI, M-Pesa…) disponíveis conforme o país.',
        'Depósitos em cripto e carteiras são creditados em minutos; cartão normalmente na hora, às vezes em algumas horas.',
        'O bônus de depósito exige um volume de negociação — leia as condições antes de aceitar.',
      ],
      blocks: [
        { type: 'p', text: 'Depositar na Pocket Option leva cerca de dois minutos: abra Finanças → Depósito, escolha o método, digite o valor e confirme no lado do provedor. O mínimo é apenas $5, o que torna a pocketoption uma das plataformas mais acessíveis para a primeira operação real. Este guia cobre cada etapa, os métodos disponíveis, prazos, condições de bônus e solução de problemas.' },
        { type: 'h2', id: 'minimum', text: 'Depósito mínimo e taxas na Pocket Option' },
        { type: 'p', text: 'O depósito mínimo é $5 (ou equivalente na sua moeda) para a maioria dos métodos; alguns provedores locais definem mínimo próprio de $10. A Pocket Option não cobra taxa de depósito — os únicos custos possíveis são de terceiros: taxa de rede blockchain, conversão de moeda pelo banco ou comissão da carteira. A operação mínima após o depósito é $1.' },
        { type: 'tip', title: 'Comece pequeno', text: 'Um primeiro depósito de $5–$20 basta para testar o ciclo completo — depósito, algumas operações de $1, saque — antes de investir mais.' },
        { type: 'h2', id: 'steps', text: 'Como depositar na Pocket Option passo a passo' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Página de depósito da Pocket Option com métodos de pagamento e campo de valor', caption: 'Finanças → Depósito: escolha o método e digite o valor.' },
        { type: 'ol', items: [
          'Entre na sua conta pocketoption e abra Finanças → Depósito no menu lateral.',
          'Selecione o método de pagamento. A lista é filtrada pelo seu país e moeda da conta.',
          'Digite o valor (mínimo $5). Se houver bônus, decida se quer ativá-lo — veja a seção de bônus abaixo.',
          'Clique em Depositar e conclua o pagamento na página do provedor: código 3-D Secure do cartão, login da carteira ou transferência cripto para o endereço exibido.',
          'Volte à plataforma. Os fundos aparecem no saldo real e a transação fica como “Concluída” em Finanças → Histórico.',
        ] },
        { type: 'image', src: IMG_CONFIRM, alt: 'Depósito confirmado na Pocket Option — saldo real atualizado', caption: 'Um depósito concluído aparece imediatamente no saldo da conta.' },
        { type: 'h2', id: 'methods', text: 'Métodos de pagamento e prazo de crédito' },
        { type: 'p', text: 'A Pocket Option lista mais de 50 métodos. O que você vê depende da região, mas eles se dividem em quatro grupos:' },
        { type: 'table', head: ['Método', 'Prazo típico de crédito', 'Observações'], rows: [
          ['Visa / Mastercard', 'Imediato – algumas horas', 'Confirmação 3-D Secure; cartão em seu nome'],
          ['Criptomoedas (USDT, BTC, ETH, LTC…)', 'Após confirmações da rede, ~5–30 min', 'Envie o valor exato ao endereço exibido; confira a rede (TRC-20, ERC-20…)'],
          ['Carteiras (Skrill, Neteller, Perfect Money, AdvCash)', 'Imediato', 'Carteira em seu nome'],
          ['Métodos locais (Pix, UPI, Mercado Pago, M-Pesa, bKash…)', 'Imediato – 1 hora', 'Disponibilidade por país'],
          ['Transferência bancária', '1–3 dias úteis', 'Apenas em países selecionados'],
        ] },
        { type: 'warn', title: 'Depósitos em cripto: escolha a rede certa', text: 'USDT existe em várias redes (TRC-20, ERC-20, BEP-20). Enviar para um endereço de rede diferente da selecionada no formulário geralmente significa perder os fundos. Verifique antes de confirmar.' },
        { type: 'h2', id: 'bonus', text: 'Bônus de depósito e códigos promocionais' },
        { type: 'p', text: 'A Pocket Option oferece regularmente um bônus percentual sobre o depósito (por exemplo +50%), ativado com código promocional ou pelas ofertas exibidas na página de depósito. Os fundos do bônus entram no saldo de negociação, mas para sacá-los é preciso negociar um volume várias vezes maior que o bônus. Se você pretende sacar em breve, costuma ser mais simples depositar sem bônus. As condições sempre aparecem antes da ativação — leia-as.' },
        { type: 'h2', id: 'problems', text: 'Depósito não creditado: o que verificar' },
        { type: 'ul', items: [
          'Pagamento com cartão recusado — o emissor bloqueou uma transação online ou internacional; ligue para o banco ou use outro método.',
          'Transferência cripto pendente — aguarde o número necessário de confirmações; confira o hash em um explorador de blockchain.',
          'Valor errado enviado em cripto — contate o suporte com o hash da transação; normalmente é creditado manualmente.',
          'Pagamento concluído mas saldo inalterado — atualize a página, confira o histórico e aguarde até uma hora para o provedor notificar a plataforma.',
          'Cartão ou carteira de terceiros — pagamentos de contas que não estão em seu nome podem ser rejeitados na verificação.',
        ] },
        { type: 'p', text: 'Se o problema continuar, abra o chat de suporte dentro da plataforma e informe data, método, valor e ID da transação.' },
        { type: 'cta', text: 'Pronto para o primeiro depósito na Pocket Option? Cadastre-se, escolha o método e comece com $5.', label: 'Abrir conta Pocket Option' },
      ],
      faq: [
        { q: 'Qual é o depósito mínimo na Pocket Option?', a: 'O depósito mínimo é $5 na maioria dos métodos. Alguns provedores locais definem mínimo de $10.' },
        { q: 'A Pocket Option cobra taxa de depósito?', a: 'Não, a plataforma não cobra por depósitos. Taxas de rede, conversão bancária ou da carteira podem ser aplicadas pelo provedor.' },
        { q: 'Quanto tempo demora um depósito na Pocket Option?', a: 'Cartões, carteiras e métodos locais normalmente são creditados na hora; cripto em cerca de 5–30 minutos após as confirmações; transferência bancária em 1–3 dias úteis.' },
        { q: 'Quais métodos de pagamento posso usar?', a: 'Visa/Mastercard, criptomoedas (USDT, BTC, ETH, LTC e outras), carteiras eletrônicas e métodos locais como Pix, UPI, Mercado Pago, M-Pesa ou bKash — a lista exata depende do país.' },
        { q: 'Devo aceitar o bônus de depósito?', a: 'O bônus aumenta o saldo de negociação, mas exige volume negociado antes que a parte do bônus possa ser sacada. Aceite apenas se pretende operar ativamente e entende as condições.' },
        { q: 'Posso depositar com o cartão de outra pessoa?', a: 'Não. Os pagamentos devem vir de cartão ou carteira em seu nome; caso contrário o depósito ou um saque posterior pode ser rejeitado na verificação.' },
      ],
    },
    es: {
      title: 'Depósito en Pocket Option: cómo fondear tu cuenta desde $5, métodos, tiempos y comisiones',
      metaTitle: 'Guía de Depósito Pocket Option – Mínimo $5, Métodos y Comisiones',
      metaDescription:
        'Cómo depositar en Pocket Option paso a paso: mínimo $5, tarjetas, cripto, monederos y métodos locales, cuánto tarda, reglas del bono y problemas comunes.',
      excerpt:
        'Todo sobre cómo fondear una cuenta pocketoption: el mínimo de $5, qué métodos son más rápidos, bonos de depósito y los motivos de una demora.',
      coverAlt: 'Monedas de Bitcoin, USDT, Ethereum y otras criptos — métodos de depósito en Pocket Option',
      keyTakeaways: [
        'El depósito mínimo en Pocket Option es $5 en la mayoría de métodos; la plataforma no cobra comisión por depositar.',
        'Tarjetas, cripto, monederos y métodos locales (Pix, UPI, M-Pesa…) según tu país.',
        'Los depósitos en cripto y monederos se acreditan en minutos; con tarjeta suelen ser instantáneos, a veces hasta unas horas.',
        'El bono de depósito exige un volumen de operaciones — lee las condiciones antes de aceptarlo.',
      ],
      blocks: [
        { type: 'p', text: 'Depositar en Pocket Option lleva unos dos minutos: abre Finanzas → Depósito, elige un método de pago, introduce el importe y confirma en la página del proveedor. El mínimo es de solo $5, lo que convierte a pocketoption en una de las plataformas más accesibles para una primera operación real. Esta guía cubre cada paso, los métodos disponibles, tiempos, condiciones del bono y solución de problemas.' },
        { type: 'h2', id: 'minimum', text: 'Depósito mínimo y comisiones en Pocket Option' },
        { type: 'p', text: 'El depósito mínimo es $5 (o el equivalente en tu moneda) para la mayoría de métodos; algunos proveedores locales fijan un mínimo propio de $10. Pocket Option no cobra comisión por depósitos — los únicos costes posibles son de terceros: comisión de red blockchain, conversión de divisa de tu banco o comisión del monedero. La operación mínima tras fondear es $1.' },
        { type: 'tip', title: 'Empieza en pequeño', text: 'Un primer depósito de $5–$20 basta para probar el ciclo completo — depósito, unas operaciones de $1, retiro — antes de comprometer una suma mayor.' },
        { type: 'h2', id: 'steps', text: 'Cómo depositar en Pocket Option paso a paso' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Página de depósito de Pocket Option con métodos de pago y campo de importe', caption: 'Finanzas → Depósito: elige el método e introduce el importe.' },
        { type: 'ol', items: [
          'Inicia sesión en tu cuenta pocketoption y abre Finanzas → Depósito en el menú izquierdo.',
          'Selecciona un método de pago. La lista se filtra por tu país y la moneda de la cuenta.',
          'Introduce el importe (mínimo $5). Si se ofrece un bono, decide si activarlo — ver la sección de bonos más abajo.',
          'Pulsa Depositar y completa el pago en la página del proveedor: código 3-D Secure de la tarjeta, acceso al monedero o transferencia cripto a la dirección mostrada.',
          'Vuelve a la plataforma. Los fondos aparecen en el saldo real y la transacción figura como “Completada” en Finanzas → Historial.',
        ] },
        { type: 'image', src: IMG_CONFIRM, alt: 'Depósito confirmado en Pocket Option — saldo real actualizado', caption: 'Un depósito completado se ve de inmediato en el saldo de la cuenta.' },
        { type: 'h2', id: 'methods', text: 'Métodos de pago y cuánto tarda un depósito' },
        { type: 'p', text: 'Pocket Option ofrece más de 50 métodos. Lo que ves depende de tu región, pero se agrupan en cuatro categorías:' },
        { type: 'table', head: ['Método', 'Tiempo típico de acreditación', 'Notas'], rows: [
          ['Visa / Mastercard', 'Instantáneo – unas horas', 'Confirmación 3-D Secure; la tarjeta debe estar a tu nombre'],
          ['Criptomonedas (USDT, BTC, ETH, LTC…)', 'Tras confirmaciones de red, ~5–30 min', 'Envía el importe exacto a la dirección mostrada; revisa la red (TRC-20, ERC-20…)'],
          ['Monederos (Skrill, Neteller, Perfect Money, AdvCash)', 'Instantáneo', 'El monedero debe estar a tu nombre'],
          ['Métodos locales (Pix, UPI, Mercado Pago, M-Pesa, bKash…)', 'Instantáneo – 1 hora', 'Disponibilidad según el país'],
          ['Transferencia bancaria', '1–3 días hábiles', 'Solo en países seleccionados'],
        ] },
        { type: 'warn', title: 'Depósitos cripto: elige la red correcta', text: 'USDT existe en varias redes (TRC-20, ERC-20, BEP-20). Enviar a una dirección de una red distinta a la seleccionada en el formulario normalmente implica perder los fondos. Verifica antes de confirmar.' },
        { type: 'h2', id: 'bonus', text: 'Bono de depósito y códigos promocionales' },
        { type: 'p', text: 'Pocket Option ofrece con regularidad un bono porcentual sobre el depósito (por ejemplo +50%), activado con un código promocional o desde las ofertas de la página de depósito. Los fondos del bono se suman al saldo de operaciones, pero para retirarlos hay que operar un volumen varias veces superior al bono. Si planeas retirar pronto, suele ser más sencillo depositar sin bono. Las condiciones siempre se muestran antes de activarlo — léelas.' },
        { type: 'h2', id: 'problems', text: 'Depósito no acreditado: qué revisar' },
        { type: 'ul', items: [
          'Pago con tarjeta rechazado — el emisor bloqueó una operación online o internacional; llama al banco o usa otro método.',
          'Transferencia cripto pendiente — espera las confirmaciones necesarias; revisa el hash en un explorador de blockchain.',
          'Importe incorrecto en un depósito cripto — contacta con soporte con el hash de la transacción; suele acreditarse manualmente.',
          'Pago completado pero saldo sin cambios — actualiza la página, revisa el historial y espera hasta una hora a que el proveedor notifique a la plataforma.',
          'Tarjeta o monedero de terceros — los pagos desde cuentas que no están a tu nombre pueden rechazarse en la verificación.',
        ] },
        { type: 'p', text: 'Si el problema persiste, abre el chat de soporte dentro de la plataforma e indica fecha, método, importe e ID de la transacción.' },
        { type: 'cta', text: '¿Listo para tu primer depósito en Pocket Option? Regístrate, elige tu método y empieza desde $5.', label: 'Abrir cuenta Pocket Option' },
      ],
      faq: [
        { q: '¿Cuál es el depósito mínimo en Pocket Option?', a: 'El depósito mínimo es $5 en la mayoría de métodos de pago. Algunos proveedores locales fijan un mínimo de $10.' },
        { q: '¿Pocket Option cobra comisión por depositar?', a: 'No, la plataforma no cobra por depósitos. Pueden aplicarse comisiones de red, conversión bancaria o del monedero por parte del proveedor.' },
        { q: '¿Cuánto tarda un depósito en Pocket Option?', a: 'Tarjetas, monederos y métodos locales suelen acreditarse al instante; cripto en unos 5–30 minutos tras las confirmaciones; transferencias bancarias en 1–3 días hábiles.' },
        { q: '¿Qué métodos de pago puedo usar?', a: 'Visa/Mastercard, criptomonedas (USDT, BTC, ETH, LTC y otras), monederos electrónicos y métodos locales como Pix, UPI, Mercado Pago, M-Pesa o bKash — la lista exacta depende de tu país.' },
        { q: '¿Debo aceptar el bono de depósito?', a: 'El bono aumenta el saldo de operaciones pero exige un volumen operado antes de poder retirar la parte del bono. Acéptalo solo si vas a operar activamente y entiendes las condiciones.' },
        { q: '¿Puedo depositar con la tarjeta de otra persona?', a: 'No. Los pagos deben proceder de una tarjeta o monedero a tu nombre; de lo contrario el depósito o un retiro posterior pueden rechazarse en la verificación.' },
      ],
    },
    ru: {
      title: 'Депозит на Pocket Option: как пополнить счёт от $5, способы, сроки и комиссии',
      metaTitle: 'Пополнение Pocket Option – минимум $5, способы и комиссии',
      metaDescription:
        'Как пополнить счёт на Pocket Option: минимум $5, карты, криптовалюта, электронные кошельки и локальные методы, сроки зачисления, условия бонуса и частые проблемы.',
      excerpt:
        'Всё о пополнении счёта pocketoption: минимум $5, какие способы самые быстрые, бонусы на депозит и причины задержек.',
      coverAlt: 'Монеты Bitcoin, USDT, Ethereum и другие криптовалюты — способы пополнения Pocket Option',
      keyTakeaways: [
        'Минимальный депозит на Pocket Option — $5 для большинства способов; платформа не берёт комиссию за пополнение.',
        'Карты, криптовалюта, электронные кошельки и локальные методы (Pix, UPI, M-Pesa…) — в зависимости от страны.',
        'Крипта и кошельки зачисляются за минуты; карты обычно мгновенно, иногда до нескольких часов.',
        'Бонус на депозит требует торгового оборота — прочитайте условия до активации.',
      ],
      blocks: [
        { type: 'p', text: 'Пополнение счёта на Pocket Option занимает около двух минут: откройте Финансы → Пополнение, выберите способ, укажите сумму и подтвердите на стороне провайдера. Минимум — всего $5, поэтому pocketoption считается одной из самых доступных платформ для первой реальной сделки. В этом руководстве — каждый шаг, доступные способы, сроки, условия бонуса и решение проблем.' },
        { type: 'h2', id: 'minimum', text: 'Минимальный депозит и комиссии Pocket Option' },
        { type: 'p', text: 'Минимальный депозит — $5 (или эквивалент в вашей валюте) для большинства способов; некоторые локальные провайдеры устанавливают собственный минимум $10. Pocket Option не берёт комиссию за пополнение — возможны только сторонние расходы: комиссия сети блокчейна, конвертация валюты банком или комиссия кошелька. Минимальная сделка после пополнения — $1.' },
        { type: 'tip', title: 'Начните с малого', text: 'Первого депозита $5–$20 достаточно, чтобы проверить весь цикл — пополнение, несколько сделок по $1, вывод — прежде чем вносить крупную сумму.' },
        { type: 'h2', id: 'steps', text: 'Как пополнить Pocket Option пошагово' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Страница пополнения Pocket Option со способами оплаты и полем суммы', caption: 'Финансы → Пополнение: выберите способ и введите сумму.' },
        { type: 'ol', items: [
          'Войдите в аккаунт pocketoption и откройте Финансы → Пополнение в левом меню.',
          'Выберите способ оплаты. Список зависит от страны и валюты счёта.',
          'Введите сумму (минимум $5). Если предлагается бонус, решите, активировать ли его — см. раздел о бонусе ниже.',
          'Нажмите «Пополнить» и завершите оплату на странице провайдера: код 3-D Secure карты, вход в кошелёк или перевод криптовалюты на указанный адрес.',
          'Вернитесь на платформу. Средства появятся на реальном балансе, а транзакция получит статус «Завершено» в Финансы → История.',
        ] },
        { type: 'image', src: IMG_CONFIRM, alt: 'Депозит зачислен на Pocket Option — реальный баланс обновлён', caption: 'Завершённый депозит сразу отображается в балансе счёта.' },
        { type: 'h2', id: 'methods', text: 'Способы оплаты и сроки зачисления' },
        { type: 'p', text: 'Pocket Option поддерживает более 50 способов. Доступный набор зависит от региона, но делится на четыре группы:' },
        { type: 'table', head: ['Способ', 'Типичный срок зачисления', 'Примечания'], rows: [
          ['Visa / Mastercard', 'Мгновенно – несколько часов', 'Подтверждение 3-D Secure; карта на ваше имя'],
          ['Криптовалюта (USDT, BTC, ETH, LTC…)', 'После подтверждений сети, ~5–30 мин', 'Отправляйте точную сумму на указанный адрес; проверяйте сеть (TRC-20, ERC-20…)'],
          ['Кошельки (Skrill, Neteller, Perfect Money, AdvCash)', 'Мгновенно', 'Кошелёк на ваше имя'],
          ['Локальные методы (Pix, UPI, Mercado Pago, M-Pesa, bKash…)', 'Мгновенно – 1 час', 'Зависит от страны'],
          ['Банковский перевод', '1–3 рабочих дня', 'Только в отдельных странах'],
        ] },
        { type: 'warn', title: 'Крипто-депозит: выбирайте правильную сеть', text: 'USDT существует в нескольких сетях (TRC-20, ERC-20, BEP-20). Перевод на адрес другой сети, чем выбрана в форме, как правило, означает потерю средств. Проверьте перед подтверждением.' },
        { type: 'h2', id: 'bonus', text: 'Бонус на депозит и промокоды' },
        { type: 'p', text: 'Pocket Option регулярно предлагает процентный бонус на депозит (например +50%), который активируется промокодом или из предложений на странице пополнения. Бонусные средства добавляются к торговому балансу, но для их вывода нужно наторговать оборот, в несколько раз превышающий бонус. Если вы планируете скоро выводить деньги, часто проще пополнить без бонуса. Условия всегда показаны до активации — прочитайте их.' },
        { type: 'h2', id: 'problems', text: 'Депозит не зачислен: что проверить' },
        { type: 'ul', items: [
          'Оплата картой отклонена — банк заблокировал онлайн- или международную операцию; позвоните в банк или используйте другой способ.',
          'Крипто-перевод в ожидании — дождитесь нужного числа подтверждений; проверьте хеш в обозревателе блокчейна.',
          'Отправлена неверная сумма в крипте — напишите в поддержку с хешем транзакции; обычно зачисляют вручную.',
          'Оплата прошла, но баланс не изменился — обновите страницу, проверьте историю и подождите до часа, пока провайдер уведомит платформу.',
          'Чужая карта или кошелёк — платежи со счетов не на ваше имя могут быть отклонены при верификации.',
        ] },
        { type: 'p', text: 'Если проблема сохраняется, откройте чат поддержки внутри платформы и укажите дату, способ, сумму и ID транзакции.' },
        { type: 'cta', text: 'Готовы сделать первый депозит на Pocket Option? Зарегистрируйтесь, выберите способ и начните с $5.', label: 'Открыть счёт Pocket Option' },
      ],
      faq: [
        { q: 'Какой минимальный депозит на Pocket Option?', a: 'Минимальный депозит — $5 для большинства способов оплаты. Некоторые локальные провайдеры устанавливают минимум $10.' },
        { q: 'Берёт ли Pocket Option комиссию за пополнение?', a: 'Нет, платформа не берёт комиссию за депозиты. Со стороны провайдера возможны комиссии сети, банковской конвертации или кошелька.' },
        { q: 'Сколько идёт депозит на Pocket Option?', a: 'Карты, кошельки и локальные методы обычно зачисляются мгновенно; криптовалюта — за 5–30 минут после подтверждений сети; банковский перевод — 1–3 рабочих дня.' },
        { q: 'Какие способы оплаты доступны?', a: 'Visa/Mastercard, криптовалюты (USDT, BTC, ETH, LTC и другие), электронные кошельки и локальные методы вроде Pix, UPI, Mercado Pago, M-Pesa или bKash — точный список зависит от страны.' },
        { q: 'Стоит ли брать бонус на депозит?', a: 'Бонус увеличивает торговый баланс, но требует торгового оборота до вывода бонусной части. Берите его, только если планируете активно торговать и понимаете условия.' },
        { q: 'Можно ли пополнить чужой картой?', a: 'Нет. Платежи должны поступать с карты или кошелька на ваше имя; иначе депозит или последующий вывод могут быть отклонены при верификации.' },
      ],
    },
    id: {
      title: 'Deposit Pocket Option: cara mengisi saldo mulai $5, metode, waktu, dan biaya',
      metaTitle: 'Panduan Deposit Pocket Option – Minimum $5, Metode, dan Biaya',
      metaDescription:
        'Cara deposit di Pocket Option langkah demi langkah: minimum $5, kartu, kripto, e-wallet dan metode lokal, waktu proses, aturan bonus, dan solusi masalah umum.',
      excerpt:
        'Semua tentang mengisi saldo akun pocketoption: minimum $5, metode mana yang paling cepat, bonus deposit, dan penyebab deposit tertunda.',
      coverAlt: 'Koin Bitcoin, USDT, Ethereum dan kripto lainnya — metode deposit di Pocket Option',
      keyTakeaways: [
        'Deposit minimum di Pocket Option adalah $5 untuk sebagian besar metode; platform tidak memungut biaya deposit.',
        'Kartu, kripto, e-wallet, dan metode lokal (Pix, UPI, M-Pesa…) tersedia tergantung negara.',
        'Deposit kripto dan e-wallet masuk dalam hitungan menit; kartu biasanya instan, terkadang hingga beberapa jam.',
        'Bonus deposit disertai syarat volume trading — baca dulu sebelum menerimanya.',
      ],
      blocks: [
        { type: 'p', text: 'Deposit di Pocket Option hanya butuh sekitar dua menit: buka Keuangan → Deposit, pilih metode pembayaran, masukkan jumlah, dan konfirmasi di sisi penyedia. Minimumnya hanya $5, yang membuat pocketoption menjadi salah satu platform paling mudah diakses untuk trade riil pertama. Panduan ini membahas setiap langkah, metode yang tersedia, waktu proses, syarat bonus, dan pemecahan masalah.' },
        { type: 'h2', id: 'minimum', text: 'Deposit minimum dan biaya di Pocket Option' },
        { type: 'p', text: 'Deposit minimum adalah $5 (atau setara dalam mata uang Anda) untuk mayoritas metode; beberapa penyedia lokal menetapkan minimum sendiri $10. Pocket Option tidak memungut biaya deposit — satu-satunya biaya yang mungkin muncul berasal dari pihak ketiga: biaya jaringan blockchain, konversi mata uang oleh bank, atau komisi e-wallet. Trade minimum setelah deposit adalah $1.' },
        { type: 'tip', title: 'Mulai dari kecil', text: 'Deposit pertama $5–$20 sudah cukup untuk menguji siklus lengkap — deposit, beberapa trade $1, penarikan — sebelum menyetor jumlah lebih besar.' },
        { type: 'h2', id: 'steps', text: 'Cara deposit di Pocket Option langkah demi langkah' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Halaman deposit Pocket Option dengan metode pembayaran dan kolom jumlah', caption: 'Keuangan → Deposit: pilih metode dan masukkan jumlah.' },
        { type: 'ol', items: [
          'Masuk ke akun pocketoption Anda dan buka Keuangan → Deposit di menu kiri.',
          'Pilih metode pembayaran. Daftar difilter berdasarkan negara dan mata uang akun Anda.',
          'Masukkan jumlah (minimal $5). Jika ada bonus, putuskan apakah ingin mengaktifkannya — lihat bagian bonus di bawah.',
          'Klik Deposit dan selesaikan pembayaran di halaman penyedia: kode 3-D Secure kartu, login e-wallet, atau transfer kripto ke alamat yang ditampilkan.',
          'Kembali ke platform. Dana muncul di saldo riil dan transaksi berstatus “Selesai” di Keuangan → Riwayat transaksi.',
        ] },
        { type: 'image', src: IMG_CONFIRM, alt: 'Deposit dikonfirmasi di Pocket Option — saldo riil diperbarui', caption: 'Deposit yang selesai langsung terlihat di saldo akun.' },
        { type: 'h2', id: 'methods', text: 'Metode pembayaran dan berapa lama deposit masuk' },
        { type: 'p', text: 'Pocket Option menyediakan 50+ metode. Yang Anda lihat tergantung wilayah, tetapi semuanya terbagi dalam empat kelompok:' },
        { type: 'table', head: ['Metode', 'Waktu masuk tipikal', 'Catatan'], rows: [
          ['Visa / Mastercard', 'Instan – beberapa jam', 'Konfirmasi 3-D Secure; kartu atas nama Anda'],
          ['Kripto (USDT, BTC, ETH, LTC…)', 'Setelah konfirmasi jaringan, ~5–30 mnt', 'Kirim jumlah persis ke alamat yang ditampilkan; cek jaringan (TRC-20, ERC-20…)'],
          ['E-wallet (Skrill, Neteller, Perfect Money, AdvCash)', 'Instan', 'E-wallet atas nama Anda'],
          ['Metode lokal (Pix, UPI, Mercado Pago, M-Pesa, bKash…)', 'Instan – 1 jam', 'Ketersediaan tergantung negara'],
          ['Transfer bank', '1–3 hari kerja', 'Hanya negara tertentu'],
        ] },
        { type: 'warn', title: 'Deposit kripto: pilih jaringan yang benar', text: 'USDT ada di beberapa jaringan (TRC-20, ERC-20, BEP-20). Mengirim ke alamat jaringan yang berbeda dari yang dipilih di formulir deposit biasanya berarti dana hilang. Periksa ulang sebelum konfirmasi.' },
        { type: 'h2', id: 'bonus', text: 'Bonus deposit dan kode promo' },
        { type: 'p', text: 'Pocket Option rutin menawarkan bonus persentase atas deposit (misalnya +50%), yang diaktifkan dengan kode promo atau dari penawaran di halaman deposit. Dana bonus ditambahkan ke saldo trading, tetapi untuk menariknya Anda harus mencapai volume trading beberapa kali lipat jumlah bonus. Jika Anda berencana menarik dana segera, sering kali lebih sederhana deposit tanpa bonus. Syaratnya selalu ditampilkan sebelum aktivasi — bacalah.' },
        { type: 'h2', id: 'problems', text: 'Deposit belum masuk: yang perlu diperiksa' },
        { type: 'ul', items: [
          'Pembayaran kartu ditolak — penerbit memblokir transaksi online atau luar negeri; hubungi bank atau gunakan metode lain.',
          'Transfer kripto masih tertunda — tunggu jumlah konfirmasi jaringan yang dibutuhkan; cek hash di blockchain explorer.',
          'Jumlah yang dikirim salah pada deposit kripto — hubungi dukungan dengan hash transaksi; biasanya dikreditkan manual.',
          'Pembayaran selesai tetapi saldo tidak berubah — muat ulang halaman, cek riwayat transaksi, dan beri waktu hingga satu jam agar penyedia memberi notifikasi ke platform.',
          'Kartu atau e-wallet pihak ketiga — pembayaran dari akun yang bukan atas nama Anda dapat ditolak saat verifikasi.',
        ] },
        { type: 'p', text: 'Jika masalah berlanjut, buka chat dukungan di dalam platform dan berikan tanggal pembayaran, metode, jumlah, dan ID transaksi.' },
        { type: 'cta', text: 'Siap melakukan deposit pertama di Pocket Option? Daftar, pilih metode, dan mulai dari $5.', label: 'Buka akun Pocket Option' },
      ],
      faq: [
        { q: 'Berapa deposit minimum di Pocket Option?', a: 'Deposit minimum adalah $5 untuk sebagian besar metode pembayaran. Beberapa penyedia lokal menetapkan minimum $10.' },
        { q: 'Apakah Pocket Option memungut biaya deposit?', a: 'Tidak, platform tidak memungut biaya deposit. Biaya jaringan, konversi bank, atau e-wallet dapat berlaku di sisi penyedia.' },
        { q: 'Berapa lama deposit Pocket Option masuk?', a: 'Kartu, e-wallet, dan metode lokal biasanya masuk instan; kripto sekitar 5–30 menit setelah konfirmasi jaringan; transfer bank 1–3 hari kerja.' },
        { q: 'Metode pembayaran apa yang bisa saya gunakan?', a: 'Visa/Mastercard, kripto (USDT, BTC, ETH, LTC dan lainnya), e-wallet, serta metode lokal seperti Pix, UPI, Mercado Pago, M-Pesa, atau bKash — daftar pastinya tergantung negara Anda.' },
        { q: 'Apakah saya harus mengambil bonus deposit?', a: 'Bonus menambah saldo trading tetapi mensyaratkan volume trading sebelum bagian bonus bisa ditarik. Ambil hanya jika Anda berencana trading aktif dan memahami syaratnya.' },
        { q: 'Bisakah saya deposit dengan kartu orang lain?', a: 'Tidak. Pembayaran harus berasal dari kartu atau e-wallet atas nama Anda sendiri; jika tidak, deposit atau penarikan berikutnya bisa ditolak saat verifikasi.' },
      ],
    },
  },
};
