import type { BlogPost } from '../types';

const IMG_AMOUNT = '/images/quick-start/1_2.webp';
const IMG_HISTORY = '/images/quick-start/6_1.webp';

export const pocketOptionRiskManagement: BlogPost = {
  slug: 'pocket-option-risk-management',
  category: 'strategy',
  cover: '/images/blog/pocket-option-risk-management.webp',
  publishedAt: '2026-09-25',
  updatedAt: '2026-09-25',
  readingMinutes: 8,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Risk management on Pocket Option: the 1–2% rule, daily limits and how not to blow a $50 account',
      metaTitle: 'Pocket Option Risk Management – Position Size & Loss Limits',
      metaDescription:
        'Practical risk management for Pocket Option: how much to risk per trade, the 1–2% rule with fixed payouts, daily loss limits and a simple trading journal.',
      excerpt:
        'Most pocketoption accounts are lost not to bad analysis but to bad sizing. Here is a complete risk framework: per-trade size, daily limits, break-even math and the habits that keep a small account alive.',
      coverAlt: 'Trader watching a price chart on a monitor at night — managing risk on Pocket Option',
      keyTakeaways: [
        'Risk 1–2% of the balance per trade: with $100 that is $1–$2, exactly the minimum trade on Pocket Option.',
        'With a 92% payout you need to win about 52% of trades just to break even — the win rate must beat that with room to spare.',
        'Set a daily loss limit (3 losses in a row or −5%) and stop. Tomorrow’s market will still be there.',
        'Martingale does not fix a losing strategy; it turns a small losing streak into a blown account.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option makes it easy to start — $5 deposit, $1 trades, 5-second expirations. That accessibility is also the risk: it is possible to place fifty trades in an hour and lose a balance before lunch. Risk management is the set of rules that stops this. It does not need to be complicated; the framework below fits on one page and works for a $50 account as well as a $5,000 one.' },
        { type: 'h2', id: 'why', text: 'Why risk management matters more with fixed payouts' },
        { type: 'p', text: 'In a Pocket Option trade the outcome is asymmetric by design: a correct forecast returns the payout (say 92% of the stake), a wrong one loses 100% of the stake. That means a 50% win rate loses money. The table shows the minimum win rate needed to break even at different payouts:' },
        { type: 'table', head: ['Payout', 'Break-even win rate', 'Meaning'], rows: [
          ['92%', '52.1%', 'You need 53 winners out of 100 to be slightly ahead'],
          ['85%', '54.1%', 'Every 100 trades, 55 must win'],
          ['80%', '55.6%', 'Lower payouts demand better accuracy'],
          ['70%', '58.8%', 'Trade low-payout assets rarely'],
        ] },
        { type: 'p', text: 'Two conclusions follow. First, prefer assets with the highest payout when your setup allows it — the same accuracy earns more. Second, no win rate survives oversized trades: a 60% win rate with 20% of the balance per trade still blows up on a normal losing streak of four.' },
        { type: 'h2', id: 'size', text: 'Rule 1 — position size: 1–2% of the balance' },
        { type: 'image', src: IMG_AMOUNT, alt: 'Trade amount field on Pocket Option set to a small fixed sum', caption: 'Fix the trade amount before the session, not during it.' },
        { type: 'p', text: 'The stake for one trade should be 1–2% of the current balance. For a $100 account that is $1–$2; for $50 it is $1 — the minimum trade on pocketoption, which is why $50 is a sensible smallest real deposit if you want to follow this rule properly. The size stays fixed for the session; recalculate it weekly, not after each trade. A fixed size means ten losses in a row cost 10–20% of the account — painful but recoverable.' },
        { type: 'h2', id: 'daily', text: 'Rule 2 — daily loss limit and trade count' },
        { type: 'ul', items: [
          'Stop for the day after three consecutive losses or when the day’s loss reaches 5% of the balance.',
          'Cap the number of trades per session (e.g. 10). Overtrading is the most common way a good morning becomes a bad day.',
          'Never trade in the first minutes after major news or right after a big loss — both push toward impulsive entries.',
          'Take a profit target too: closing the session at +5–10% avoids giving winnings back in the afternoon.',
        ] },
        { type: 'tip', title: 'Use the platform’s own limits', text: 'Pocket Option shows the balance and the result of every closed trade in the terminal in real time. Write your daily limit on paper next to the screen — the simplest tools work best.' },
        { type: 'h2', id: 'martingale', text: 'Rule 3 — no martingale' },
        { type: 'p', text: 'Martingale means doubling the stake after each loss to recover everything on the next win. With a $1 start, the sixth trade in a losing streak is $32 and the total at risk is $63 — on a $100 account you are one loss from ruin, chasing a $1 profit. Losing streaks of six happen regularly even with a 55% win rate. Martingale does not change the odds of a single trade; it only guarantees that eventually one streak takes the whole account.' },
        { type: 'warn', title: 'The house-money effect', text: 'After a winning streak traders tend to increase the size “because it is profit”. Profit is your money the moment the trade closes. Keep the same 1–2% size regardless of the last result.' },
        { type: 'h2', id: 'expiration', text: 'Rule 4 — expiration and asset discipline' },
        { type: 'p', text: 'Risk also lives in what you trade. Five-second expirations are closer to a coin flip than to analysis; 3–15 minute expirations give your setup time to work. Stick to two or three liquid assets you know (for example EUR/USD, GBP/USD, BTC/USD), check their payout before entering and avoid switching to an unknown OTC asset just because its payout is higher at that moment.' },
        { type: 'h2', id: 'journal', text: 'Rule 5 — the trading journal' },
        { type: 'image', src: IMG_HISTORY, alt: 'Pocket Option trade history with closed trades and results', caption: 'The Trades tab shows every closed trade — the raw material for your journal.' },
        { type: 'p', text: 'A journal turns a string of trades into data. For each trade record: date and time, asset, expiration, amount, direction, reason for entry (which signal) and result. Once a week, sort by reason for entry: setups with a positive result over 50+ trades stay, the rest go. The Pocket Option trade history keeps every closed trade, so you can fill the journal after the session rather than during it.' },
        { type: 'h2', id: 'plan', text: 'A one-page risk plan for a $50 account' },
        { type: 'ol', items: [
          'Trade size: $1 (2% of $50). Do not change it for the first month.',
          'Assets: EUR/USD and one more you have tested on demo. Payout at entry ≥ 80%.',
          'Expiration: 3–5 minutes on a 1-minute chart.',
          'Daily stop: 3 losses in a row or −$2.50. Daily target: +$3–$5.',
          'Maximum 10 trades per day, no trading 15 minutes around scheduled news.',
          'Journal every trade; review on Sunday; adjust one rule at a time.',
        ] },
        { type: 'p', text: 'Followed strictly, this plan makes a wipe-out nearly impossible in the short term and gives you fifty or more real trades of data before you decide whether to deposit more. It will not make you rich in a month — that is the point.' },
        { type: 'warn', title: 'Risk disclosure', text: 'Trading on Pocket Option involves a high level of risk and can result in the loss of all deposited funds. Risk management reduces the speed of losses; it does not turn trading into a guaranteed income. Only trade with money you can afford to lose.' },
        { type: 'cta', text: 'Practise the plan on the free $50,000 demo first — then start real trading on Pocket Option from $5.', label: 'Open Pocket Option account' },
      ],
      faq: [
        { q: 'How much should I risk per trade on Pocket Option?', a: '1–2% of the current balance. On a $100 account that is $1–$2 per trade, which matches the platform’s $1 minimum trade.' },
        { q: 'What win rate do I need to be profitable?', a: 'At a 92% payout the break-even win rate is about 52%; at 80% it is about 56%. To be reliably profitable the win rate must be several points above break-even over a large sample of trades.' },
        { q: 'Is martingale a good strategy on Pocket Option?', a: 'No. Martingale doubles the stake after each loss; a normal losing streak of five or six trades exhausts a small account. It does not improve the odds of any single trade.' },
        { q: 'What is a reasonable daily loss limit?', a: 'A common rule is to stop after three consecutive losses or when the day’s loss reaches 5% of the balance, whichever comes first.' },
        { q: 'Should I trade 5-second expirations?', a: 'Very short expirations are dominated by noise and make risk control harder. Beginners usually get more consistent results with 3–15 minute expirations.' },
        { q: 'Does the demo account help with risk management?', a: 'Yes, for learning the rules and building the journal habit. It cannot simulate the emotions of real losses, so start real trading with the smallest size and keep the same rules.' },
      ],
    },
    pt: {
      title: 'Gestão de risco na Pocket Option: a regra de 1–2%, limites diários e como não zerar uma conta de $50',
      metaTitle: 'Gestão de Risco Pocket Option – Posição e Limite de Perda',
      metaDescription:
        'Gestão de risco prática na Pocket Option: quanto arriscar por operação, regra de 1–2% com payouts fixos, limite diário de perda e diário de trading.',
      excerpt:
        'A maioria das contas pocketoption é perdida não por má análise, mas por mau dimensionamento. Aqui está um framework de risco completo: tamanho por operação, limites diários, matemática do ponto de equilíbrio e os hábitos que mantêm uma conta pequena viva.',
      coverAlt: 'Trader observando um gráfico de preços em um monitor à noite — gerindo risco na Pocket Option',
      keyTakeaways: [
        'Arrisque 1–2% do saldo por operação: com $100 são $1–$2, exatamente a operação mínima da Pocket Option.',
        'Com payout de 92% você precisa acertar cerca de 52% das operações só para empatar — a taxa de acerto precisa superar isso com folga.',
        'Defina um limite diário de perda (3 perdas seguidas ou −5%) e pare. O mercado de amanhã ainda estará lá.',
        'Martingale não conserta uma estratégia perdedora; transforma uma pequena sequência de perdas em conta zerada.',
      ],
      blocks: [
        { type: 'p', text: 'A Pocket Option facilita o começo — depósito de $5, operações de $1, expirações de 5 segundos. Essa acessibilidade também é o risco: é possível abrir cinquenta operações em uma hora e perder o saldo antes do almoço. Gestão de risco é o conjunto de regras que impede isso. Não precisa ser complicada; o framework abaixo cabe em uma página e funciona tanto para uma conta de $50 quanto de $5.000.' },
        { type: 'h2', id: 'why', text: 'Por que a gestão de risco importa mais com payouts fixos' },
        { type: 'p', text: 'Em uma operação na Pocket Option o resultado é assimétrico por natureza: uma previsão correta devolve o payout (digamos 92% do valor), uma errada perde 100% do valor. Isso significa que 50% de acerto perde dinheiro. A tabela mostra a taxa de acerto mínima para empatar em diferentes payouts:' },
        { type: 'table', head: ['Payout', 'Taxa de acerto para empatar', 'Significado'], rows: [
          ['92%', '52,1%', 'Você precisa de 53 acertos em 100 para ficar levemente à frente'],
          ['85%', '54,1%', 'A cada 100 operações, 55 precisam ganhar'],
          ['80%', '55,6%', 'Payouts menores exigem mais precisão'],
          ['70%', '58,8%', 'Opere ativos de payout baixo raramente'],
        ] },
        { type: 'p', text: 'Duas conclusões. Primeiro, prefira ativos com o maior payout quando seu setup permitir — a mesma precisão rende mais. Segundo, nenhuma taxa de acerto sobrevive a operações grandes demais: 60% de acerto com 20% do saldo por operação ainda zera a conta em uma sequência normal de quatro perdas.' },
        { type: 'h2', id: 'size', text: 'Regra 1 — tamanho da posição: 1–2% do saldo' },
        { type: 'image', src: IMG_AMOUNT, alt: 'Campo de valor da operação na Pocket Option com uma quantia pequena e fixa', caption: 'Fixe o valor da operação antes da sessão, não durante.' },
        { type: 'p', text: 'O valor de uma operação deve ser 1–2% do saldo atual. Para uma conta de $100 são $1–$2; para $50 é $1 — a operação mínima na pocketoption, e por isso $50 é um depósito real mínimo sensato se você quer seguir essa regra corretamente. O tamanho fica fixo durante a sessão; recalcule semanalmente, não a cada operação. Tamanho fixo significa que dez perdas seguidas custam 10–20% da conta — doloroso, mas recuperável.' },
        { type: 'h2', id: 'daily', text: 'Regra 2 — limite diário de perda e número de operações' },
        { type: 'ul', items: [
          'Pare pelo dia após três perdas consecutivas ou quando a perda do dia atingir 5% do saldo.',
          'Limite o número de operações por sessão (ex. 10). Operar demais é a forma mais comum de uma boa manhã virar um dia ruim.',
          'Nunca opere nos primeiros minutos após notícias importantes ou logo depois de uma perda grande — ambos levam a entradas impulsivas.',
          'Tenha também uma meta de lucro: encerrar a sessão em +5–10% evita devolver os ganhos à tarde.',
        ] },
        { type: 'tip', title: 'Use os próprios limites da plataforma', text: 'A Pocket Option mostra o saldo e o resultado de cada operação fechada no terminal em tempo real. Escreva seu limite diário em papel ao lado da tela — as ferramentas mais simples funcionam melhor.' },
        { type: 'h2', id: 'martingale', text: 'Regra 3 — sem martingale' },
        { type: 'p', text: 'Martingale significa dobrar o valor após cada perda para recuperar tudo no próximo acerto. Começando com $1, a sexta operação de uma sequência perdedora é $32 e o total em risco é $63 — em uma conta de $100 você está a uma perda da ruína, perseguindo $1 de lucro. Sequências de seis perdas acontecem regularmente mesmo com 55% de acerto. Martingale não muda as chances de uma operação; só garante que, cedo ou tarde, uma sequência leva a conta inteira.' },
        { type: 'warn', title: 'O efeito “dinheiro da casa”', text: 'Depois de uma sequência de ganhos, traders tendem a aumentar o tamanho “porque é lucro”. Lucro é seu dinheiro no momento em que a operação fecha. Mantenha o mesmo tamanho de 1–2% independentemente do último resultado.' },
        { type: 'h2', id: 'expiration', text: 'Regra 4 — disciplina de expiração e ativos' },
        { type: 'p', text: 'O risco também está no que você opera. Expirações de cinco segundos estão mais perto de um cara ou coroa do que de análise; expirações de 3–15 minutos dão tempo ao seu setup. Fique com dois ou três ativos líquidos que conhece (por exemplo EUR/USD, GBP/USD, BTC/USD), confira o payout antes de entrar e evite mudar para um ativo OTC desconhecido só porque o payout está maior naquele momento.' },
        { type: 'h2', id: 'journal', text: 'Regra 5 — o diário de trading' },
        { type: 'image', src: IMG_HISTORY, alt: 'Histórico de operações da Pocket Option com operações fechadas e resultados', caption: 'A aba Operações mostra cada operação fechada — a matéria-prima do seu diário.' },
        { type: 'p', text: 'Um diário transforma uma sequência de operações em dados. Para cada operação registre: data e hora, ativo, expiração, valor, direção, motivo da entrada (qual sinal) e resultado. Uma vez por semana, ordene por motivo de entrada: setups com resultado positivo em 50+ operações ficam, o resto sai. O histórico da Pocket Option guarda cada operação fechada, então você pode preencher o diário depois da sessão em vez de durante.' },
        { type: 'h2', id: 'plan', text: 'Plano de risco de uma página para uma conta de $50' },
        { type: 'ol', items: [
          'Tamanho da operação: $1 (2% de $50). Não altere no primeiro mês.',
          'Ativos: EUR/USD e mais um que você testou na demo. Payout na entrada ≥ 80%.',
          'Expiração: 3–5 minutos em gráfico de 1 minuto.',
          'Stop diário: 3 perdas seguidas ou −$2,50. Meta diária: +$3–$5.',
          'Máximo 10 operações por dia, sem operar 15 minutos ao redor de notícias agendadas.',
          'Registre cada operação; revise no domingo; ajuste uma regra por vez.',
        ] },
        { type: 'p', text: 'Seguido à risca, esse plano torna a perda total quase impossível no curto prazo e dá cinquenta ou mais operações reais de dados antes de decidir se deposita mais. Não vai deixá-lo rico em um mês — esse é o ponto.' },
        { type: 'warn', title: 'Aviso de risco', text: 'Negociar na Pocket Option envolve alto nível de risco e pode resultar na perda de todos os fundos depositados. A gestão de risco reduz a velocidade das perdas; não transforma o trading em renda garantida. Opere apenas com dinheiro que pode perder.' },
        { type: 'cta', text: 'Pratique o plano primeiro na demo gratuita de $50.000 — depois comece a operar de verdade na Pocket Option a partir de $5.', label: 'Abrir conta Pocket Option' },
      ],
      faq: [
        { q: 'Quanto devo arriscar por operação na Pocket Option?', a: '1–2% do saldo atual. Em uma conta de $100 são $1–$2 por operação, o que coincide com a operação mínima de $1 da plataforma.' },
        { q: 'Que taxa de acerto preciso para ser lucrativo?', a: 'Com payout de 92% a taxa de acerto para empatar é cerca de 52%; com 80%, cerca de 56%. Para ser lucrativo de forma consistente a taxa de acerto precisa ficar vários pontos acima do empate em uma amostra grande de operações.' },
        { q: 'Martingale é uma boa estratégia na Pocket Option?', a: 'Não. O martingale dobra o valor após cada perda; uma sequência normal de cinco ou seis perdas esgota uma conta pequena. Ele não melhora as chances de nenhuma operação individual.' },
        { q: 'Qual é um limite diário de perda razoável?', a: 'Uma regra comum é parar após três perdas consecutivas ou quando a perda do dia atingir 5% do saldo, o que vier primeiro.' },
        { q: 'Devo operar expirações de 5 segundos?', a: 'Expirações muito curtas são dominadas por ruído e dificultam o controle de risco. Iniciantes costumam ter resultados mais consistentes com expirações de 3–15 minutos.' },
        { q: 'A conta demo ajuda na gestão de risco?', a: 'Sim, para aprender as regras e criar o hábito do diário. Ela não simula as emoções das perdas reais, então comece a operar de verdade com o menor tamanho e mantenha as mesmas regras.' },
      ],
    },
    es: {
      title: 'Gestión del riesgo en Pocket Option: la regla del 1–2%, límites diarios y cómo no quemar una cuenta de $50',
      metaTitle: 'Gestión del Riesgo Pocket Option – Posición y Límite de Pérdida',
      metaDescription:
        'Gestión del riesgo práctica en Pocket Option: cuánto arriesgar por operación, regla del 1–2% con pagos fijos, límite diario de pérdida y diario de trading.',
      excerpt:
        'La mayoría de cuentas pocketoption se pierden no por mal análisis sino por mal dimensionamiento. Aquí un marco de riesgo completo: tamaño por operación, límites diarios, matemática del punto de equilibrio y los hábitos que mantienen viva una cuenta pequeña.',
      coverAlt: 'Trader observando un gráfico de precios en un monitor de noche — gestionando el riesgo en Pocket Option',
      keyTakeaways: [
        'Arriesga el 1–2% del saldo por operación: con $100 son $1–$2, exactamente la operación mínima de Pocket Option.',
        'Con un pago del 92% necesitas acertar alrededor del 52% de las operaciones solo para empatar — la tasa de acierto debe superarlo con margen.',
        'Fija un límite diario de pérdida (3 pérdidas seguidas o −5%) y para. El mercado de mañana seguirá ahí.',
        'La martingala no arregla una estrategia perdedora; convierte una pequeña racha de pérdidas en una cuenta quemada.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option facilita empezar — depósito de $5, operaciones de $1, expiraciones de 5 segundos. Esa accesibilidad es también el riesgo: es posible abrir cincuenta operaciones en una hora y perder el saldo antes de comer. La gestión del riesgo es el conjunto de reglas que lo impide. No tiene que ser complicada; el marco de abajo cabe en una página y funciona igual para una cuenta de $50 que para una de $5.000.' },
        { type: 'h2', id: 'why', text: 'Por qué la gestión del riesgo importa más con pagos fijos' },
        { type: 'p', text: 'En una operación de Pocket Option el resultado es asimétrico por diseño: un pronóstico correcto devuelve el pago (digamos el 92% de la apuesta), uno erróneo pierde el 100%. Eso significa que una tasa de acierto del 50% pierde dinero. La tabla muestra la tasa mínima de acierto para empatar con distintos pagos:' },
        { type: 'table', head: ['Pago', 'Tasa de acierto de equilibrio', 'Significado'], rows: [
          ['92%', '52,1%', 'Necesitas 53 aciertos de 100 para ir ligeramente por delante'],
          ['85%', '54,1%', 'De cada 100 operaciones, 55 deben ganar'],
          ['80%', '55,6%', 'Pagos más bajos exigen mayor precisión'],
          ['70%', '58,8%', 'Opera activos de pago bajo raramente'],
        ] },
        { type: 'p', text: 'Dos conclusiones. Primera, prefiere los activos con el mayor pago cuando tu setup lo permita — la misma precisión rinde más. Segunda, ninguna tasa de acierto sobrevive a operaciones sobredimensionadas: un 60% de acierto con el 20% del saldo por operación sigue quemando la cuenta en una racha normal de cuatro pérdidas.' },
        { type: 'h2', id: 'size', text: 'Regla 1 — tamaño de posición: 1–2% del saldo' },
        { type: 'image', src: IMG_AMOUNT, alt: 'Campo de importe de la operación en Pocket Option con una suma pequeña y fija', caption: 'Fija el importe de la operación antes de la sesión, no durante.' },
        { type: 'p', text: 'La apuesta de una operación debe ser el 1–2% del saldo actual. Para una cuenta de $100 son $1–$2; para $50 es $1 — la operación mínima en pocketoption, y por eso $50 es un depósito real mínimo sensato si quieres seguir esta regla correctamente. El tamaño se mantiene fijo durante la sesión; recalcúlalo semanalmente, no tras cada operación. Un tamaño fijo significa que diez pérdidas seguidas cuestan el 10–20% de la cuenta — doloroso pero recuperable.' },
        { type: 'h2', id: 'daily', text: 'Regla 2 — límite diario de pérdida y número de operaciones' },
        { type: 'ul', items: [
          'Para por hoy tras tres pérdidas consecutivas o cuando la pérdida del día llegue al 5% del saldo.',
          'Limita el número de operaciones por sesión (p. ej. 10). Sobreoperar es la forma más común de que una buena mañana acabe en un mal día.',
          'Nunca operes en los primeros minutos tras noticias importantes ni justo después de una gran pérdida — ambos empujan a entradas impulsivas.',
          'Ten también un objetivo de beneficio: cerrar la sesión en +5–10% evita devolver las ganancias por la tarde.',
        ] },
        { type: 'tip', title: 'Usa los propios límites de la plataforma', text: 'Pocket Option muestra el saldo y el resultado de cada operación cerrada en el terminal en tiempo real. Escribe tu límite diario en papel junto a la pantalla — las herramientas más simples funcionan mejor.' },
        { type: 'h2', id: 'martingale', text: 'Regla 3 — nada de martingala' },
        { type: 'p', text: 'La martingala consiste en doblar la apuesta tras cada pérdida para recuperar todo en el siguiente acierto. Empezando con $1, la sexta operación de una racha perdedora es de $32 y el total en riesgo es $63 — en una cuenta de $100 estás a una pérdida de la ruina persiguiendo $1 de beneficio. Rachas de seis pérdidas ocurren con regularidad incluso con un 55% de acierto. La martingala no cambia las probabilidades de una operación; solo garantiza que, tarde o temprano, una racha se lleva toda la cuenta.' },
        { type: 'warn', title: 'El efecto “dinero de la casa”', text: 'Tras una racha ganadora los traders tienden a aumentar el tamaño “porque es beneficio”. El beneficio es tu dinero desde que la operación cierra. Mantén el mismo tamaño del 1–2% sea cual sea el último resultado.' },
        { type: 'h2', id: 'expiration', text: 'Regla 4 — disciplina de expiración y activos' },
        { type: 'p', text: 'El riesgo también está en lo que operas. Las expiraciones de cinco segundos están más cerca de una moneda al aire que del análisis; las de 3–15 minutos dan tiempo a tu setup. Quédate con dos o tres activos líquidos que conozcas (por ejemplo EUR/USD, GBP/USD, BTC/USD), revisa su pago antes de entrar y evita cambiar a un activo OTC desconocido solo porque su pago sea mayor en ese momento.' },
        { type: 'h2', id: 'journal', text: 'Regla 5 — el diario de trading' },
        { type: 'image', src: IMG_HISTORY, alt: 'Historial de operaciones de Pocket Option con operaciones cerradas y resultados', caption: 'La pestaña Operaciones muestra cada operación cerrada — la materia prima de tu diario.' },
        { type: 'p', text: 'Un diario convierte una serie de operaciones en datos. Para cada operación registra: fecha y hora, activo, expiración, importe, dirección, motivo de entrada (qué señal) y resultado. Una vez por semana, ordena por motivo de entrada: los setups con resultado positivo en 50+ operaciones se quedan, el resto se va. El historial de Pocket Option guarda cada operación cerrada, así que puedes rellenar el diario tras la sesión en lugar de durante.' },
        { type: 'h2', id: 'plan', text: 'Plan de riesgo de una página para una cuenta de $50' },
        { type: 'ol', items: [
          'Tamaño de operación: $1 (2% de $50). No lo cambies el primer mes.',
          'Activos: EUR/USD y uno más que hayas probado en demo. Pago en la entrada ≥ 80%.',
          'Expiración: 3–5 minutos en gráfico de 1 minuto.',
          'Stop diario: 3 pérdidas seguidas o −$2,50. Objetivo diario: +$3–$5.',
          'Máximo 10 operaciones al día, sin operar 15 minutos alrededor de noticias programadas.',
          'Registra cada operación; revisa el domingo; ajusta una regla a la vez.',
        ] },
        { type: 'p', text: 'Seguido con rigor, este plan hace casi imposible perder todo a corto plazo y te da cincuenta o más operaciones reales de datos antes de decidir si depositar más. No te hará rico en un mes — ese es el punto.' },
        { type: 'warn', title: 'Aviso de riesgo', text: 'Operar en Pocket Option implica un alto nivel de riesgo y puede resultar en la pérdida de todos los fondos depositados. La gestión del riesgo reduce la velocidad de las pérdidas; no convierte el trading en un ingreso garantizado. Opera solo con dinero que puedas permitirte perder.' },
        { type: 'cta', text: 'Practica el plan primero en la demo gratuita de $50.000 — luego empieza a operar en real en Pocket Option desde $5.', label: 'Abrir cuenta Pocket Option' },
      ],
      faq: [
        { q: '¿Cuánto debo arriesgar por operación en Pocket Option?', a: 'El 1–2% del saldo actual. En una cuenta de $100 son $1–$2 por operación, lo que coincide con la operación mínima de $1 de la plataforma.' },
        { q: '¿Qué tasa de acierto necesito para ser rentable?', a: 'Con un pago del 92% la tasa de acierto de equilibrio es de alrededor del 52%; con el 80%, alrededor del 56%. Para ser rentable de forma fiable la tasa de acierto debe estar varios puntos por encima del equilibrio en una muestra grande de operaciones.' },
        { q: '¿Es la martingala una buena estrategia en Pocket Option?', a: 'No. La martingala dobla la apuesta tras cada pérdida; una racha normal de cinco o seis pérdidas agota una cuenta pequeña. No mejora las probabilidades de ninguna operación individual.' },
        { q: '¿Cuál es un límite diario de pérdida razonable?', a: 'Una regla común es parar tras tres pérdidas consecutivas o cuando la pérdida del día llegue al 5% del saldo, lo que ocurra primero.' },
        { q: '¿Debo operar expiraciones de 5 segundos?', a: 'Las expiraciones muy cortas están dominadas por el ruido y dificultan el control del riesgo. Los principiantes suelen obtener resultados más consistentes con expiraciones de 3–15 minutos.' },
        { q: '¿La cuenta demo ayuda con la gestión del riesgo?', a: 'Sí, para aprender las reglas y crear el hábito del diario. No puede simular las emociones de las pérdidas reales, así que empieza en real con el tamaño más pequeño y mantén las mismas reglas.' },
      ],
    },
    ru: {
      title: 'Управление риском на Pocket Option: правило 1–2%, дневные лимиты и как не слить счёт в $50',
      metaTitle: 'Риск-менеджмент Pocket Option – размер позиции и лимиты',
      metaDescription:
        'Практический риск-менеджмент на Pocket Option: сколько рисковать в сделке, правило 1–2% при фиксированных выплатах, дневной лимит убытка и дневник.',
      excerpt:
        'Большинство счетов pocketoption теряются не из-за плохого анализа, а из-за неправильного размера сделок. Полная система риска: размер сделки, дневные лимиты, математика безубыточности и привычки, которые сохраняют маленький счёт.',
      coverAlt: 'Трейдер смотрит на график цены на мониторе ночью — управление риском на Pocket Option',
      keyTakeaways: [
        'Рискуйте 1–2% баланса в сделке: при $100 это $1–$2 — ровно минимальная сделка на Pocket Option.',
        'При выплате 92% нужно выигрывать около 52% сделок только для безубыточности — винрейт должен превышать это с запасом.',
        'Установите дневной лимит убытка (3 убытка подряд или −5%) и остановитесь. Завтра рынок никуда не денется.',
        'Мартингейл не исправляет убыточную стратегию; он превращает короткую серию убытков в слитый счёт.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option упрощает старт — депозит $5, сделки по $1, экспирации от 5 секунд. Эта доступность одновременно и риск: можно открыть пятьдесят сделок за час и потерять баланс до обеда. Управление риском — набор правил, который это предотвращает. Оно не должно быть сложным: система ниже умещается на одной странице и работает как для счёта в $50, так и для $5000.' },
        { type: 'h2', id: 'why', text: 'Почему риск-менеджмент важнее при фиксированных выплатах' },
        { type: 'p', text: 'В сделке на Pocket Option результат асимметричен по определению: верный прогноз приносит выплату (скажем, 92% от ставки), неверный теряет 100% ставки. Значит, винрейт 50% приносит убыток. В таблице — минимальный винрейт для безубыточности при разных выплатах:' },
        { type: 'table', head: ['Выплата', 'Безубыточный винрейт', 'Что это значит'], rows: [
          ['92%', '52,1%', 'Нужно 53 выигрыша из 100, чтобы быть чуть в плюсе'],
          ['85%', '54,1%', 'Из каждых 100 сделок 55 должны быть прибыльными'],
          ['80%', '55,6%', 'Низкие выплаты требуют большей точности'],
          ['70%', '58,8%', 'Активы с низкой выплатой торгуйте редко'],
        ] },
        { type: 'p', text: 'Два вывода. Первый: предпочитайте активы с максимальной выплатой, когда ваш сетап это позволяет — та же точность приносит больше. Второй: никакой винрейт не выдерживает завышенных ставок: 60% выигрышей при 20% баланса на сделку всё равно сливают счёт на обычной серии из четырёх убытков.' },
        { type: 'h2', id: 'size', text: 'Правило 1 — размер позиции: 1–2% баланса' },
        { type: 'image', src: IMG_AMOUNT, alt: 'Поле суммы сделки на Pocket Option с небольшой фиксированной суммой', caption: 'Фиксируйте сумму сделки до сессии, а не во время неё.' },
        { type: 'p', text: 'Ставка на одну сделку должна составлять 1–2% текущего баланса. Для счёта $100 это $1–$2; для $50 — $1, минимальная сделка на pocketoption, поэтому $50 — разумный минимальный реальный депозит, если вы хотите соблюдать это правило. Размер фиксирован на сессию; пересчитывайте его раз в неделю, а не после каждой сделки. Фиксированный размер означает, что десять убытков подряд стоят 10–20% счёта — больно, но восстановимо.' },
        { type: 'h2', id: 'daily', text: 'Правило 2 — дневной лимит убытка и число сделок' },
        { type: 'ul', items: [
          'Останавливайтесь на день после трёх убытков подряд или когда дневной убыток достигает 5% баланса.',
          'Ограничьте число сделок за сессию (например, 10). Овертрейдинг — самый частый способ превратить хорошее утро в плохой день.',
          'Никогда не торгуйте в первые минуты после важных новостей или сразу после крупного убытка — и то и другое толкает к импульсивным входам.',
          'Ставьте и цель по прибыли: закрытие сессии на +5–10% не даёт отдать выигрыш во второй половине дня.',
        ] },
        { type: 'tip', title: 'Используйте возможности платформы', text: 'Pocket Option в реальном времени показывает баланс и результат каждой закрытой сделки в терминале. Запишите дневной лимит на бумаге рядом с экраном — простейшие инструменты работают лучше всего.' },
        { type: 'h2', id: 'martingale', text: 'Правило 3 — никакого мартингейла' },
        { type: 'p', text: 'Мартингейл — удвоение ставки после каждого убытка, чтобы отыграть всё следующим выигрышем. Начав с $1, шестая сделка убыточной серии — $32, а общий риск — $63; на счёте $100 вы в одном убытке от разорения, гонясь за прибылью в $1. Серии из шести убытков случаются регулярно даже при винрейте 55%. Мартингейл не меняет шансы отдельной сделки; он лишь гарантирует, что рано или поздно одна серия забирает весь счёт.' },
        { type: 'warn', title: 'Эффект «чужих денег»', text: 'После серии выигрышей трейдеры склонны увеличивать размер, «потому что это прибыль». Прибыль — ваши деньги с момента закрытия сделки. Сохраняйте те же 1–2% независимо от последнего результата.' },
        { type: 'h2', id: 'expiration', text: 'Правило 4 — дисциплина в экспирации и активах' },
        { type: 'p', text: 'Риск также в том, чем вы торгуете. Пятисекундные экспирации ближе к подбрасыванию монеты, чем к анализу; экспирации 3–15 минут дают сетапу время сработать. Держитесь двух-трёх ликвидных активов, которые знаете (например, EUR/USD, GBP/USD, BTC/USD), проверяйте выплату перед входом и не переключайтесь на незнакомый OTC-актив только потому, что его выплата сейчас выше.' },
        { type: 'h2', id: 'journal', text: 'Правило 5 — торговый дневник' },
        { type: 'image', src: IMG_HISTORY, alt: 'История сделок Pocket Option с закрытыми сделками и результатами', caption: 'Вкладка «Сделки» показывает каждую закрытую сделку — основу вашего дневника.' },
        { type: 'p', text: 'Дневник превращает череду сделок в данные. Для каждой сделки записывайте: дату и время, актив, экспирацию, сумму, направление, причину входа (какой сигнал) и результат. Раз в неделю сортируйте по причине входа: сетапы с положительным результатом на 50+ сделках остаются, остальные уходят. История сделок Pocket Option хранит каждую закрытую сделку, поэтому дневник можно заполнять после сессии, а не во время неё.' },
        { type: 'h2', id: 'plan', text: 'План риска на одну страницу для счёта $50' },
        { type: 'ol', items: [
          'Размер сделки: $1 (2% от $50). Не меняйте его в первый месяц.',
          'Активы: EUR/USD и ещё один, протестированный на демо. Выплата при входе ≥ 80%.',
          'Экспирация: 3–5 минут на минутном графике.',
          'Дневной стоп: 3 убытка подряд или −$2,50. Дневная цель: +$3–$5.',
          'Максимум 10 сделок в день, без торговли за 15 минут до и после запланированных новостей.',
          'Записывайте каждую сделку; анализируйте в воскресенье; меняйте по одному правилу за раз.',
        ] },
        { type: 'p', text: 'При строгом соблюдении этот план делает полный слив почти невозможным в краткосрочной перспективе и даёт пятьдесят и более реальных сделок данных, прежде чем вы решите, пополнять ли счёт. Он не сделает вас богатым за месяц — в этом и смысл.' },
        { type: 'warn', title: 'Предупреждение о рисках', text: 'Торговля на Pocket Option связана с высоким уровнем риска и может привести к потере всех внесённых средств. Управление риском снижает скорость потерь, но не превращает трейдинг в гарантированный доход. Торгуйте только деньгами, которые можете позволить себе потерять.' },
        { type: 'cta', text: 'Сначала отработайте план на бесплатном демо с $50 000 — затем начните реальную торговлю на Pocket Option от $5.', label: 'Открыть счёт Pocket Option' },
      ],
      faq: [
        { q: 'Сколько рисковать в одной сделке на Pocket Option?', a: '1–2% текущего баланса. На счёте $100 это $1–$2 за сделку, что совпадает с минимальной сделкой платформы $1.' },
        { q: 'Какой винрейт нужен для прибыльности?', a: 'При выплате 92% безубыточный винрейт около 52%; при 80% — около 56%. Для стабильной прибыли винрейт должен быть на несколько пунктов выше безубыточного на большой выборке сделок.' },
        { q: 'Мартингейл — хорошая стратегия для Pocket Option?', a: 'Нет. Мартингейл удваивает ставку после каждого убытка; обычная серия из пяти-шести убытков исчерпывает небольшой счёт. Он не улучшает шансы ни одной отдельной сделки.' },
        { q: 'Какой дневной лимит убытка разумен?', a: 'Распространённое правило — остановиться после трёх убытков подряд или когда дневной убыток достигает 5% баланса, в зависимости от того, что наступит раньше.' },
        { q: 'Стоит ли торговать 5-секундные экспирации?', a: 'Очень короткие экспирации подчинены шуму и усложняют контроль риска. Новички обычно получают более стабильные результаты на экспирациях 3–15 минут.' },
        { q: 'Помогает ли демо-счёт в управлении риском?', a: 'Да — для изучения правил и выработки привычки вести дневник. Он не имитирует эмоции реальных потерь, поэтому начинайте реальную торговлю с минимального размера и с теми же правилами.' },
      ],
    },
    id: {
      title: 'Manajemen risiko di Pocket Option: aturan 1–2%, batas harian, dan cara agar akun $50 tidak habis',
      metaTitle: 'Manajemen Risiko Pocket Option – Ukuran Posisi & Batas Rugi',
      metaDescription:
        'Manajemen risiko praktis di Pocket Option: berapa risiko per trade, aturan 1–2% dengan payout tetap, batas rugi harian, dan jurnal trading sederhana.',
      excerpt:
        'Kebanyakan akun pocketoption hilang bukan karena analisis buruk, tetapi karena ukuran trade yang salah. Ini kerangka risiko lengkap: ukuran per trade, batas harian, matematika impas, dan kebiasaan yang menjaga akun kecil tetap hidup.',
      coverAlt: 'Trader mengamati grafik harga di monitor pada malam hari — mengelola risiko di Pocket Option',
      keyTakeaways: [
        'Risikokan 1–2% saldo per trade: dengan $100 itu $1–$2, persis trade minimum di Pocket Option.',
        'Dengan payout 92% Anda perlu menang sekitar 52% trade hanya untuk impas — win rate harus melampauinya dengan margin.',
        'Tetapkan batas rugi harian (3 rugi berturut atau −5%) dan berhenti. Pasar besok masih ada.',
        'Martingale tidak memperbaiki strategi yang rugi; ia mengubah rentetan rugi kecil menjadi akun habis.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option memudahkan memulai — deposit $5, trade $1, kedaluwarsa 5 detik. Kemudahan itu juga risikonya: mungkin membuka lima puluh trade dalam satu jam dan kehilangan saldo sebelum makan siang. Manajemen risiko adalah seperangkat aturan yang mencegah hal itu. Tidak perlu rumit; kerangka di bawah muat dalam satu halaman dan berfungsi untuk akun $50 maupun $5.000.' },
        { type: 'h2', id: 'why', text: 'Mengapa manajemen risiko lebih penting dengan payout tetap' },
        { type: 'p', text: 'Dalam trade Pocket Option hasilnya asimetris sejak awal: prakiraan benar mengembalikan payout (misalnya 92% dari taruhan), yang salah kehilangan 100% taruhan. Artinya win rate 50% tetap rugi. Tabel berikut menunjukkan win rate minimum untuk impas pada berbagai payout:' },
        { type: 'table', head: ['Payout', 'Win rate impas', 'Artinya'], rows: [
          ['92%', '52,1%', 'Anda perlu 53 menang dari 100 untuk sedikit di depan'],
          ['85%', '54,1%', 'Setiap 100 trade, 55 harus menang'],
          ['80%', '55,6%', 'Payout lebih rendah menuntut akurasi lebih tinggi'],
          ['70%', '58,8%', 'Jarang-jarang trading aset payout rendah'],
        ] },
        { type: 'p', text: 'Dua kesimpulan. Pertama, pilih aset dengan payout tertinggi saat setup Anda memungkinkan — akurasi yang sama menghasilkan lebih banyak. Kedua, tidak ada win rate yang bertahan dengan trade terlalu besar: win rate 60% dengan 20% saldo per trade tetap menghabiskan akun pada rentetan normal empat kali rugi.' },
        { type: 'h2', id: 'size', text: 'Aturan 1 — ukuran posisi: 1–2% saldo' },
        { type: 'image', src: IMG_AMOUNT, alt: 'Kolom jumlah trade di Pocket Option diatur ke jumlah kecil dan tetap', caption: 'Tetapkan jumlah trade sebelum sesi, bukan selama sesi.' },
        { type: 'p', text: 'Taruhan satu trade sebaiknya 1–2% dari saldo saat ini. Untuk akun $100 itu $1–$2; untuk $50 itu $1 — trade minimum di pocketoption, karena itu $50 adalah deposit riil terkecil yang masuk akal jika Anda ingin mengikuti aturan ini dengan benar. Ukuran tetap selama sesi; hitung ulang mingguan, bukan setelah setiap trade. Ukuran tetap berarti sepuluh rugi berturut memakan 10–20% akun — menyakitkan tetapi bisa dipulihkan.' },
        { type: 'h2', id: 'daily', text: 'Aturan 2 — batas rugi harian dan jumlah trade' },
        { type: 'ul', items: [
          'Berhenti untuk hari itu setelah tiga rugi berturut atau saat rugi harian mencapai 5% saldo.',
          'Batasi jumlah trade per sesi (mis. 10). Overtrading adalah cara paling umum pagi yang baik berubah jadi hari buruk.',
          'Jangan pernah trading di menit-menit pertama setelah berita besar atau tepat setelah rugi besar — keduanya mendorong entri impulsif.',
          'Tetapkan juga target profit: menutup sesi di +5–10% menghindari mengembalikan keuntungan di sore hari.',
        ] },
        { type: 'tip', title: 'Manfaatkan fitur platform', text: 'Pocket Option menampilkan saldo dan hasil setiap trade yang ditutup di terminal secara real-time. Tulis batas harian Anda di kertas di samping layar — alat paling sederhana bekerja paling baik.' },
        { type: 'h2', id: 'martingale', text: 'Aturan 3 — tidak ada martingale' },
        { type: 'p', text: 'Martingale berarti menggandakan taruhan setelah setiap rugi untuk memulihkan semuanya di kemenangan berikutnya. Mulai dari $1, trade keenam dalam rentetan rugi adalah $32 dan total yang dipertaruhkan $63 — di akun $100 Anda satu rugi dari bangkrut, demi mengejar profit $1. Rentetan enam rugi terjadi secara rutin bahkan dengan win rate 55%. Martingale tidak mengubah peluang satu trade; ia hanya memastikan pada akhirnya satu rentetan mengambil seluruh akun.' },
        { type: 'warn', title: 'Efek “uang rumah”', text: 'Setelah rentetan menang, trader cenderung menaikkan ukuran “karena itu profit”. Profit adalah uang Anda sejak trade ditutup. Pertahankan ukuran 1–2% yang sama apa pun hasil terakhirnya.' },
        { type: 'h2', id: 'expiration', text: 'Aturan 4 — disiplin kedaluwarsa dan aset' },
        { type: 'p', text: 'Risiko juga ada pada apa yang Anda tradingkan. Kedaluwarsa lima detik lebih dekat ke lempar koin daripada analisis; kedaluwarsa 3–15 menit memberi waktu bagi setup Anda. Tetap pada dua atau tiga aset likuid yang Anda kenal (misalnya EUR/USD, GBP/USD, BTC/USD), cek payout sebelum masuk, dan hindari berpindah ke aset OTC asing hanya karena payout-nya lebih tinggi saat itu.' },
        { type: 'h2', id: 'journal', text: 'Aturan 5 — jurnal trading' },
        { type: 'image', src: IMG_HISTORY, alt: 'Riwayat trade Pocket Option dengan trade yang ditutup dan hasilnya', caption: 'Tab Trade menampilkan setiap trade yang ditutup — bahan mentah jurnal Anda.' },
        { type: 'p', text: 'Jurnal mengubah rangkaian trade menjadi data. Untuk setiap trade catat: tanggal dan waktu, aset, kedaluwarsa, jumlah, arah, alasan masuk (sinyal apa), dan hasil. Sekali seminggu, urutkan berdasarkan alasan masuk: setup dengan hasil positif dalam 50+ trade dipertahankan, sisanya dibuang. Riwayat trade Pocket Option menyimpan setiap trade yang ditutup, sehingga Anda bisa mengisi jurnal setelah sesi, bukan selama sesi.' },
        { type: 'h2', id: 'plan', text: 'Rencana risiko satu halaman untuk akun $50' },
        { type: 'ol', items: [
          'Ukuran trade: $1 (2% dari $50). Jangan ubah selama bulan pertama.',
          'Aset: EUR/USD dan satu lagi yang sudah Anda uji di demo. Payout saat masuk ≥ 80%.',
          'Kedaluwarsa: 3–5 menit pada grafik 1 menit.',
          'Stop harian: 3 rugi berturut atau −$2,50. Target harian: +$3–$5.',
          'Maksimal 10 trade per hari, tidak trading 15 menit di sekitar berita terjadwal.',
          'Catat setiap trade; tinjau hari Minggu; ubah satu aturan pada satu waktu.',
        ] },
        { type: 'p', text: 'Jika diikuti ketat, rencana ini membuat akun habis hampir tidak mungkin dalam jangka pendek dan memberi Anda lima puluh atau lebih trade riil sebagai data sebelum memutuskan deposit lagi. Ini tidak akan membuat Anda kaya dalam sebulan — itulah intinya.' },
        { type: 'warn', title: 'Peringatan risiko', text: 'Trading di Pocket Option mengandung risiko tinggi dan dapat mengakibatkan hilangnya semua dana yang disetor. Manajemen risiko memperlambat kerugian; ia tidak mengubah trading menjadi penghasilan terjamin. Trading hanya dengan uang yang sanggup Anda hilangkan.' },
        { type: 'cta', text: 'Latih rencananya dulu di demo gratis $50.000 — lalu mulai trading riil di Pocket Option dari $5.', label: 'Buka akun Pocket Option' },
      ],
      faq: [
        { q: 'Berapa risiko per trade di Pocket Option?', a: '1–2% dari saldo saat ini. Di akun $100 itu $1–$2 per trade, sesuai trade minimum platform $1.' },
        { q: 'Win rate berapa yang saya perlukan untuk profit?', a: 'Pada payout 92% win rate impas sekitar 52%; pada 80% sekitar 56%. Untuk profit yang andal, win rate harus beberapa poin di atas impas pada sampel trade yang besar.' },
        { q: 'Apakah martingale strategi yang baik di Pocket Option?', a: 'Tidak. Martingale menggandakan taruhan setelah setiap rugi; rentetan normal lima atau enam rugi menghabiskan akun kecil. Ia tidak meningkatkan peluang trade mana pun.' },
        { q: 'Berapa batas rugi harian yang wajar?', a: 'Aturan umum adalah berhenti setelah tiga rugi berturut atau saat rugi harian mencapai 5% saldo, mana yang lebih dulu.' },
        { q: 'Haruskah saya trading kedaluwarsa 5 detik?', a: 'Kedaluwarsa sangat pendek didominasi noise dan mempersulit kontrol risiko. Pemula biasanya mendapat hasil lebih konsisten dengan kedaluwarsa 3–15 menit.' },
        { q: 'Apakah akun demo membantu manajemen risiko?', a: 'Ya, untuk mempelajari aturan dan membangun kebiasaan jurnal. Demo tidak bisa mensimulasikan emosi rugi nyata, jadi mulailah trading riil dengan ukuran terkecil dan pertahankan aturan yang sama.' },
      ],
    },
  },
};
