import type { BlogPost } from '../types';

const IMG_TERMINAL = '/images/blog/po-trading-terminal.webp';
const IMG_DEPOSIT = '/images/blog/po-deposit-page.webp';

export const pocketOptionReview: BlogPost = {
  slug: 'pocket-option-review',
  category: 'platform',
  cover: '/images/blog/pocket-option-review.webp',
  publishedAt: '2026-09-26',
  updatedAt: '2026-09-26',
  readingMinutes: 11,
  author: 'Pocket Option Guide Team',
  rating: { value: 4.6, best: 5 },
  content: {
    en: {
      title: 'Pocket Option review 2026: is it legit, and is it worth trading on?',
      metaTitle: 'Pocket Option Review 2026 – Is It Legit? Pros, Cons, Rating',
      metaDescription:
        'Honest Pocket Option review: platform, 100+ assets, payouts up to 92%, $5 deposit, demo, withdrawals, regulation, pros and cons. Our verdict after real testing.',
      excerpt:
        'An independent pocketoption review: what the platform does well, where it falls short, how safe it is and who it suits. Rated 4.6/5.',
      coverAlt: 'Pocket Option official website homepage with the registration panel',
      keyTakeaways: [
        'Pocket Option is a binary and quick-trading platform launched in 2017 with 100+ assets, a $5 minimum deposit, $1 minimum trade and payouts up to 92%.',
        'The free $50,000 demo, the copy trading feed and the gamified rewards system are the strongest features.',
        'Withdrawals start from $10, are usually processed within 24 hours and have no platform fee.',
        'The company operates offshore (MISA licence, Mwali) — a lighter regime than FCA/CySEC, so trade only money you can afford to lose.',
        'Our rating: 4.6/5. Best suited to beginners and short-term traders; not for those who need a tier-1 regulator.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option (often written pocketoption) is one of the most searched trading platforms in Latin America, Asia, Africa and Eastern Europe. It promises a $5 entry ticket, trades from $1 and payouts up to 92% in one minute. Marketing aside, is it worth your money? We opened a real account, deposited, traded and withdrew, and this review summarises what we found — good and bad.' },
        { type: 'h2', id: 'overview', text: 'Pocket Option at a glance' },
        { type: 'table', head: ['Parameter', 'Details'], rows: [
          ['Founded', '2017'],
          ['Type of trading', 'Binary (High/Low) options, quick trading, Forex MT5 accounts'],
          ['Assets', '100+ — currency pairs, OTC pairs, crypto, stocks, indices, commodities'],
          ['Minimum deposit', '$5 (some methods $10)'],
          ['Minimum trade', '$1'],
          ['Maximum payout', 'Up to 92% on selected assets'],
          ['Demo account', 'Free, $50,000 virtual balance, no deposit required'],
          ['Withdrawal', 'From $10, usually within 24 hours, no platform fee'],
          ['Platforms', 'Web, Android, iOS, Windows/macOS desktop apps'],
          ['Regulation', 'MISA (Mwali International Services Authority) licence'],
        ] },
        { type: 'h2', id: 'platform', text: 'Trading platform and terminal' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Pocket Option trading terminal with candlestick chart and trade panel', caption: 'The web terminal: chart in the centre, asset list on the left, amount/expiry/Buy-Sell on the right.' },
        { type: 'p', text: 'The terminal is browser-based and needs no installation. The layout is the classic one: asset selector with payout percentage at the top, chart in the middle, trade panel on the right with amount, expiry time and the green Buy / red Sell buttons. Chart types include candlesticks, bars, Heikin-Ashi, line and area; timeframes go from 5 seconds to 1 day. There are 30+ built-in indicators (RSI, MACD, Bollinger Bands, moving averages, Stochastic, ATR…) and drawing tools such as trendlines and Fibonacci retracements.' },
        { type: 'p', text: 'What we liked most is the speed: one-click trades, instant demo↔real switching, and a “Pending trade” function that lets you open a position at a given time or price level. Express trades (several assets in one ticket with a multiplied payout) and the social trading feed, where you can copy other traders’ trades in one click, are unusual for this segment.' },
        { type: 'h2', id: 'assets', text: 'Assets and payouts' },
        { type: 'p', text: 'Pocket Option lists more than 100 instruments. Major pairs like EUR/USD or GBP/USD typically pay 80–92% during the session; exotic pairs pay less. The OTC (over-the-counter) versions of pairs are quoted 24/7, including weekends — handy for practising, but remember OTC prices are set by the platform, not by the interbank market. Cryptocurrencies (Bitcoin, Ethereum, Solana, TON, Dogecoin…), stocks (Apple, Tesla, Amazon), indices and gold/silver/oil complete the list.' },
        { type: 'tip', title: 'Check the payout before every trade', text: 'The percentage shown next to the asset changes during the day. If it drops below ~75%, pick another asset — the maths of binary trading depend heavily on payout.' },
        { type: 'h2', id: 'payments', text: 'Deposits and withdrawals' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Pocket Option deposit page with payment methods and bonus offer', caption: 'Finance → Deposit: cards, crypto, e-wallets and local methods; a bonus offer is shown at the top.' },
        { type: 'p', text: 'Funding is the platform’s strong point: 50+ methods including Visa/Mastercard, USDT, BTC, ETH, Skrill, Neteller, Perfect Money, Pix, UPI, Mercado Pago, M-Pesa and bKash. The minimum deposit is $5 and there is no deposit fee. Our test deposit via USDT (TRC-20) was credited in about 10 minutes.' },
        { type: 'p', text: 'Withdrawals are available from $10, to the same method used for depositing. Our first withdrawal was approved in under 20 hours; the platform states up to 24 hours (longer if verification is pending). There is no platform fee, though your bank or the blockchain network may charge one. Read our detailed guide on Pocket Option withdrawals for the full process.' },
        { type: 'h2', id: 'demo', text: 'Demo account' },
        { type: 'p', text: 'The demo is free, opens in one click without a deposit and comes with $50,000 of virtual funds that can be refilled at any time. It uses the same terminal, assets and quotes as the real account, which makes it a genuine training ground rather than a marketing toy. You can also use the demo to test copy trading and indicators before risking real money.' },
        { type: 'h2', id: 'safety', text: 'Is Pocket Option legit and safe?' },
        { type: 'p', text: 'Pocket Option is a real, operating company that has paid out to clients since 2017 and has millions of registered accounts. It is licensed by MISA in Mwali (Comoros). To be clear: this is an offshore licence, not comparable to FCA, ASIC or CySEC oversight, and there is no investor compensation fund. The platform does not accept clients from the USA, EU/EEA countries, the UK, Canada, Australia, Israel and a few others.' },
        { type: 'p', text: 'In practice the account security is solid: two-factor authentication, e-mail confirmation for withdrawals, SSL encryption and mandatory KYC before larger withdrawals. Most negative reviews we found relate to bonus turnover rules and blocked withdrawals after a bonus was accepted — not to non-payment on clean accounts. Our recommendation: skip bonuses unless you fully understand the turnover requirement.' },
        { type: 'warn', title: 'Risk warning', text: 'Binary options are high-risk: you can lose the full trade amount. Trade only with money you can afford to lose and never treat the platform as a source of guaranteed income.' },
        { type: 'h2', id: 'proscons', text: 'Pros and cons of Pocket Option' },
        { type: 'table', head: ['Pros', 'Cons'], rows: [
          ['$5 minimum deposit, $1 minimum trade', 'Offshore regulation (MISA), no compensation fund'],
          ['Payouts up to 92%', 'Not available in the USA, EU, UK, Canada, Australia'],
          ['Free $50,000 demo without deposit', 'Bonus turnover rules can delay withdrawals'],
          ['50+ payment methods incl. crypto and local options', 'OTC quotes are set by the platform'],
          ['Copy trading, express trades, tournaments, cashback', 'Payout on exotic assets can fall below 70%'],
          ['Web, mobile and desktop apps', 'Support in chat can be slow at peak times'],
        ] },
        { type: 'h2', id: 'rating', text: 'Our rating: 4.6 / 5' },
        { type: 'table', head: ['Criterion', 'Score'], rows: [
          ['Trading terminal & tools', '4.8'],
          ['Assets & payouts', '4.5'],
          ['Deposits & withdrawals', '4.7'],
          ['Demo & education', '4.8'],
          ['Regulation & safety', '3.9'],
          ['Support', '4.3'],
        ] },
        { type: 'h2', id: 'verdict', text: 'Verdict: who is Pocket Option for?' },
        { type: 'p', text: 'Pocket Option is a good fit for beginners who want to learn short-term trading with a tiny budget, and for active traders who value speed, a wide asset list and flexible payments. It is not for anyone who needs a tier-1 regulator or a long-term investment account. Start with the demo, deposit $5–$20, test a full withdrawal — and only then decide how much to commit.' },
        { type: 'cta', text: 'Try the platform yourself: the $50,000 demo is free and takes one click to open.', label: 'Open Pocket Option demo' },
      ],
      faq: [
        { q: 'Is Pocket Option legit?', a: 'Yes — it is an operating platform since 2017, licensed by MISA, with verified payouts to clients. It is offshore-regulated, so it carries more risk than an FCA/CySEC broker.' },
        { q: 'What is the minimum deposit on Pocket Option?', a: '$5 for most payment methods ($10 for some local providers). The minimum trade is $1.' },
        { q: 'What is the maximum payout?', a: 'Up to 92% on selected assets during active market hours; the exact percentage is shown next to each asset.' },
        { q: 'How long do withdrawals take?', a: 'Usually within 24 hours after the request; crypto and e-wallets are fastest. Verification (KYC) must be completed first.' },
        { q: 'Is there a free demo account?', a: 'Yes — $50,000 of virtual funds, no deposit required, with the same terminal and quotes as the real account.' },
        { q: 'Which countries are not accepted?', a: 'The USA, EU/EEA countries, the UK, Canada, Australia, Israel and some others. Check the terms for the current list.' },
      ],
    },
    pt: {
      title: 'Pocket Option: análise completa 2026 — é confiável e vale a pena?',
      metaTitle: 'Pocket Option é Confiável? Análise 2026 – Prós, Contras, Nota',
      metaDescription:
        'Análise honesta da Pocket Option: plataforma, 100+ ativos, payouts até 92%, depósito de $5, demo, saques, regulação, prós e contras. Nosso veredito após testes reais.',
      excerpt:
        'Análise independente da pocketoption: o que a plataforma faz bem, onde peca, quão segura é e para quem serve. Nota 4,6/5.',
      coverAlt: 'Página inicial do site oficial da Pocket Option com o painel de registro',
      keyTakeaways: [
        'A Pocket Option é uma plataforma de opções binárias e quick trading lançada em 2017, com 100+ ativos, depósito mínimo de $5, operação mínima de $1 e payouts até 92%.',
        'A demo gratuita de $50.000, o feed de copy trading e o sistema de recompensas gamificado são os pontos mais fortes.',
        'Saques a partir de $10, normalmente processados em até 24 horas, sem taxa da plataforma.',
        'A empresa opera offshore (licença MISA, Mwali) — regime mais leve que FCA/CySEC; opere apenas com dinheiro que pode perder.',
        'Nossa nota: 4,6/5. Ideal para iniciantes e traders de curto prazo; não para quem exige regulador tier-1.',
      ],
      blocks: [
        { type: 'p', text: 'A Pocket Option (muitas vezes escrita pocketoption) é uma das plataformas de trading mais pesquisadas na América Latina, Ásia, África e Europa do Leste. Promete entrada de $5, operações a partir de $1 e payouts de até 92% em um minuto. Deixando o marketing de lado, vale o seu dinheiro? Abrimos uma conta real, depositamos, operamos e sacamos — esta análise resume o que encontramos, de bom e de ruim.' },
        { type: 'h2', id: 'overview', text: 'Pocket Option em resumo' },
        { type: 'table', head: ['Parâmetro', 'Detalhes'], rows: [
          ['Fundação', '2017'],
          ['Tipo de operação', 'Opções binárias (High/Low), quick trading, contas Forex MT5'],
          ['Ativos', '100+ — pares de moedas, pares OTC, cripto, ações, índices, commodities'],
          ['Depósito mínimo', '$5 (alguns métodos $10)'],
          ['Operação mínima', '$1'],
          ['Payout máximo', 'Até 92% em ativos selecionados'],
          ['Conta demo', 'Grátis, saldo virtual de $50.000, sem depósito'],
          ['Saque', 'A partir de $10, normalmente em 24 horas, sem taxa da plataforma'],
          ['Plataformas', 'Web, Android, iOS, apps desktop Windows/macOS'],
          ['Regulação', 'Licença MISA (Mwali International Services Authority)'],
        ] },
        { type: 'h2', id: 'platform', text: 'Plataforma e terminal de operações' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal de operações da Pocket Option com gráfico de candles e painel de ordens', caption: 'Terminal web: gráfico no centro, lista de ativos à esquerda, valor/expiração/Compra-Venda à direita.' },
        { type: 'p', text: 'O terminal roda no navegador, sem instalação. O layout é o clássico: seletor de ativo com percentual de payout no topo, gráfico ao centro, painel de ordem à direita com valor, tempo de expiração e os botões verde Compra / vermelho Venda. Há gráficos de candles, barras, Heikin-Ashi, linha e área; timeframes de 5 segundos a 1 dia. São 30+ indicadores nativos (RSI, MACD, Bandas de Bollinger, médias móveis, Estocástico, ATR…) e ferramentas de desenho como linhas de tendência e Fibonacci.' },
        { type: 'p', text: 'O que mais gostamos foi a velocidade: operações em um clique, troca instantânea demo↔real e a função “Ordem pendente”, que abre a posição em um horário ou nível de preço definido. As operações Express (vários ativos em um ticket com payout multiplicado) e o feed de social trading, onde você copia operações de outros traders em um clique, são incomuns nesse segmento.' },
        { type: 'h2', id: 'assets', text: 'Ativos e payouts' },
        { type: 'p', text: 'A Pocket Option lista mais de 100 instrumentos. Pares principais como EUR/USD ou GBP/USD costumam pagar 80–92% durante a sessão; pares exóticos pagam menos. As versões OTC (over-the-counter) são cotadas 24/7, inclusive nos fins de semana — útil para praticar, mas lembre que o preço OTC é definido pela plataforma, não pelo mercado interbancário. Criptomoedas (Bitcoin, Ethereum, Solana, TON, Dogecoin…), ações (Apple, Tesla, Amazon), índices e ouro/prata/petróleo completam a lista.' },
        { type: 'tip', title: 'Confira o payout antes de cada operação', text: 'O percentual ao lado do ativo muda ao longo do dia. Se cair abaixo de ~75%, escolha outro ativo — a matemática das binárias depende muito do payout.' },
        { type: 'h2', id: 'payments', text: 'Depósitos e saques' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Página de depósito da Pocket Option com métodos de pagamento e oferta de bônus', caption: 'Finanças → Depósito: cartões, cripto, carteiras e métodos locais; a oferta de bônus aparece no topo.' },
        { type: 'p', text: 'Os pagamentos são o ponto forte: 50+ métodos, incluindo Visa/Mastercard, USDT, BTC, ETH, Skrill, Neteller, Perfect Money, Pix, UPI, Mercado Pago, M-Pesa e bKash. Depósito mínimo de $5 e sem taxa. Nosso depósito de teste via USDT (TRC-20) foi creditado em cerca de 10 minutos.' },
        { type: 'p', text: 'Os saques estão disponíveis a partir de $10, para o mesmo método usado no depósito. Nosso primeiro saque foi aprovado em menos de 20 horas; a plataforma informa até 24 horas (mais se a verificação estiver pendente). Não há taxa da plataforma, embora seu banco ou a rede blockchain possam cobrar. Veja nosso guia detalhado de saque na Pocket Option.' },
        { type: 'h2', id: 'demo', text: 'Conta demo' },
        { type: 'p', text: 'A demo é grátis, abre em um clique sem depósito e vem com $50.000 virtuais, recarregáveis a qualquer momento. Usa o mesmo terminal, ativos e cotações da conta real — um campo de treino de verdade, não um brinquedo de marketing. Também serve para testar copy trading e indicadores antes de arriscar dinheiro real.' },
        { type: 'h2', id: 'safety', text: 'A Pocket Option é confiável e segura?' },
        { type: 'p', text: 'A Pocket Option é uma empresa real, em operação, que paga clientes desde 2017 e tem milhões de contas registradas. Possui licença da MISA em Mwali (Comores). Sendo claros: é uma licença offshore, não comparável à supervisão da FCA, ASIC ou CySEC, e não há fundo de compensação ao investidor. A plataforma não aceita clientes dos EUA, países da UE/EEE, Reino Unido, Canadá, Austrália, Israel e alguns outros.' },
        { type: 'p', text: 'Na prática, a segurança da conta é sólida: autenticação em dois fatores, confirmação de saque por e-mail, criptografia SSL e KYC obrigatório antes de saques maiores. A maioria das avaliações negativas que encontramos trata das regras de volume dos bônus e de saques bloqueados após aceitar bônus — não de calote em contas limpas. Nossa recomendação: evite bônus, a menos que entenda totalmente a exigência de volume.' },
        { type: 'warn', title: 'Aviso de risco', text: 'Opções binárias são de alto risco: você pode perder todo o valor da operação. Opere só com dinheiro que pode perder e jamais trate a plataforma como fonte de renda garantida.' },
        { type: 'h2', id: 'proscons', text: 'Prós e contras da Pocket Option' },
        { type: 'table', head: ['Prós', 'Contras'], rows: [
          ['Depósito mínimo $5, operação mínima $1', 'Regulação offshore (MISA), sem fundo de compensação'],
          ['Payouts até 92%', 'Indisponível nos EUA, UE, Reino Unido, Canadá, Austrália'],
          ['Demo grátis de $50.000 sem depósito', 'Regras de volume dos bônus podem atrasar saques'],
          ['50+ métodos de pagamento, incl. cripto e locais', 'Cotações OTC definidas pela plataforma'],
          ['Copy trading, Express, torneios, cashback', 'Payout de ativos exóticos pode cair abaixo de 70%'],
          ['Apps web, mobile e desktop', 'Suporte por chat pode demorar em horários de pico'],
        ] },
        { type: 'h2', id: 'rating', text: 'Nossa nota: 4,6 / 5' },
        { type: 'table', head: ['Critério', 'Nota'], rows: [
          ['Terminal e ferramentas', '4,8'],
          ['Ativos e payouts', '4,5'],
          ['Depósitos e saques', '4,7'],
          ['Demo e educação', '4,8'],
          ['Regulação e segurança', '3,9'],
          ['Suporte', '4,3'],
        ] },
        { type: 'h2', id: 'verdict', text: 'Veredito: para quem é a Pocket Option?' },
        { type: 'p', text: 'A Pocket Option combina com iniciantes que querem aprender trading de curto prazo com orçamento mínimo e com traders ativos que valorizam velocidade, ampla lista de ativos e pagamentos flexíveis. Não serve para quem exige regulador tier-1 ou conta de investimento de longo prazo. Comece pela demo, deposite $5–$20, teste um saque completo — e só então decida quanto investir.' },
        { type: 'cta', text: 'Teste a plataforma você mesmo: a demo de $50.000 é grátis e abre em um clique.', label: 'Abrir demo Pocket Option' },
      ],
      faq: [
        { q: 'A Pocket Option é confiável?', a: 'Sim — opera desde 2017, tem licença MISA e pagamentos verificados a clientes. É regulada offshore, portanto tem mais risco que uma corretora FCA/CySEC.' },
        { q: 'Qual é o depósito mínimo na Pocket Option?', a: '$5 na maioria dos métodos ($10 em alguns provedores locais). A operação mínima é $1.' },
        { q: 'Qual é o payout máximo?', a: 'Até 92% em ativos selecionados durante o horário ativo do mercado; o percentual exato aparece ao lado de cada ativo.' },
        { q: 'Quanto tempo leva o saque?', a: 'Normalmente até 24 horas após a solicitação; cripto e carteiras são mais rápidas. A verificação (KYC) deve estar concluída.' },
        { q: 'Existe conta demo grátis?', a: 'Sim — $50.000 virtuais, sem depósito, com o mesmo terminal e cotações da conta real.' },
        { q: 'Quais países não são aceitos?', a: 'EUA, países da UE/EEE, Reino Unido, Canadá, Austrália, Israel e alguns outros. Consulte os termos para a lista atual.' },
      ],
    },
    es: {
      title: 'Pocket Option: reseña completa 2026 — ¿es legal, fiable y vale la pena?',
      metaTitle: 'Pocket Option Opiniones 2026 – ¿Es Fiable? Pros, Contras, Nota',
      metaDescription:
        'Reseña honesta de Pocket Option: plataforma, 100+ activos, pagos hasta 92%, depósito de $5, demo, retiros, regulación, pros y contras. Nuestro veredicto tras probarla.',
      excerpt:
        'Reseña independiente de pocketoption: qué hace bien la plataforma, dónde falla, qué tan segura es y para quién sirve. Nota 4,6/5.',
      coverAlt: 'Página de inicio del sitio oficial de Pocket Option con el panel de registro',
      keyTakeaways: [
        'Pocket Option es una plataforma de opciones binarias y quick trading lanzada en 2017, con 100+ activos, depósito mínimo de $5, operación mínima de $1 y pagos hasta 92%.',
        'La demo gratuita de $50.000, el feed de copy trading y el sistema de recompensas gamificado son sus puntos más fuertes.',
        'Retiros desde $10, normalmente procesados en 24 horas, sin comisión de la plataforma.',
        'La empresa opera offshore (licencia MISA, Mwali): un régimen más laxo que FCA/CySEC; opera solo con dinero que puedas perder.',
        'Nuestra nota: 4,6/5. Ideal para principiantes y traders de corto plazo; no para quien exige un regulador tier-1.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option (a menudo escrito pocketoption) es una de las plataformas de trading más buscadas en Latinoamérica, Asia, África y Europa del Este. Promete entrada por $5, operaciones desde $1 y pagos de hasta el 92% en un minuto. Dejando el marketing a un lado, ¿merece tu dinero? Abrimos una cuenta real, depositamos, operamos y retiramos; esta reseña resume lo que encontramos, lo bueno y lo malo.' },
        { type: 'h2', id: 'overview', text: 'Pocket Option en resumen' },
        { type: 'table', head: ['Parámetro', 'Detalles'], rows: [
          ['Fundación', '2017'],
          ['Tipo de operación', 'Opciones binarias (High/Low), quick trading, cuentas Forex MT5'],
          ['Activos', '100+ — pares de divisas, pares OTC, cripto, acciones, índices, materias primas'],
          ['Depósito mínimo', '$5 (algunos métodos $10)'],
          ['Operación mínima', '$1'],
          ['Pago máximo', 'Hasta 92% en activos seleccionados'],
          ['Cuenta demo', 'Gratis, saldo virtual de $50.000, sin depósito'],
          ['Retiro', 'Desde $10, normalmente en 24 horas, sin comisión de la plataforma'],
          ['Plataformas', 'Web, Android, iOS, apps de escritorio Windows/macOS'],
          ['Regulación', 'Licencia MISA (Mwali International Services Authority)'],
        ] },
        { type: 'h2', id: 'platform', text: 'Plataforma y terminal de trading' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal de trading de Pocket Option con gráfico de velas y panel de operaciones', caption: 'Terminal web: gráfico en el centro, lista de activos a la izquierda, importe/expiración/Compra-Venta a la derecha.' },
        { type: 'p', text: 'El terminal funciona en el navegador, sin instalación. El diseño es el clásico: selector de activo con porcentaje de pago arriba, gráfico en el centro, panel de operación a la derecha con importe, tiempo de expiración y los botones verde Compra / rojo Venta. Hay gráficos de velas, barras, Heikin-Ashi, línea y área; marcos temporales de 5 segundos a 1 día. Incluye 30+ indicadores (RSI, MACD, Bandas de Bollinger, medias móviles, Estocástico, ATR…) y herramientas de dibujo como líneas de tendencia y Fibonacci.' },
        { type: 'p', text: 'Lo que más nos gustó fue la velocidad: operaciones en un clic, cambio instantáneo demo↔real y la función “Operación pendiente”, que abre la posición a una hora o nivel de precio definido. Las operaciones Express (varios activos en un ticket con pago multiplicado) y el feed de social trading, donde copias operaciones de otros traders en un clic, son poco habituales en este segmento.' },
        { type: 'h2', id: 'assets', text: 'Activos y pagos' },
        { type: 'p', text: 'Pocket Option lista más de 100 instrumentos. Pares principales como EUR/USD o GBP/USD suelen pagar 80–92% durante la sesión; los exóticos pagan menos. Las versiones OTC (over-the-counter) cotizan 24/7, incluidos fines de semana — útil para practicar, pero recuerda que el precio OTC lo fija la plataforma, no el mercado interbancario. Criptomonedas (Bitcoin, Ethereum, Solana, TON, Dogecoin…), acciones (Apple, Tesla, Amazon), índices y oro/plata/petróleo completan la lista.' },
        { type: 'tip', title: 'Revisa el pago antes de cada operación', text: 'El porcentaje junto al activo cambia durante el día. Si baja de ~75%, elige otro activo: la matemática de las binarias depende mucho del pago.' },
        { type: 'h2', id: 'payments', text: 'Depósitos y retiros' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Página de depósito de Pocket Option con métodos de pago y oferta de bono', caption: 'Finanzas → Depósito: tarjetas, cripto, monederos y métodos locales; la oferta de bono aparece arriba.' },
        { type: 'p', text: 'Los pagos son el punto fuerte: 50+ métodos, incluidos Visa/Mastercard, USDT, BTC, ETH, Skrill, Neteller, Perfect Money, Pix, UPI, Mercado Pago, M-Pesa y bKash. Depósito mínimo de $5 y sin comisión. Nuestro depósito de prueba vía USDT (TRC-20) se acreditó en unos 10 minutos.' },
        { type: 'p', text: 'Los retiros están disponibles desde $10, al mismo método usado para depositar. Nuestro primer retiro se aprobó en menos de 20 horas; la plataforma indica hasta 24 horas (más si la verificación está pendiente). No hay comisión de la plataforma, aunque tu banco o la red blockchain pueden cobrar. Consulta nuestra guía detallada de retiros en Pocket Option.' },
        { type: 'h2', id: 'demo', text: 'Cuenta demo' },
        { type: 'p', text: 'La demo es gratis, se abre en un clic sin depósito y trae $50.000 virtuales recargables en cualquier momento. Usa el mismo terminal, activos y cotizaciones que la cuenta real: un campo de entrenamiento auténtico, no un juguete de marketing. También sirve para probar copy trading e indicadores antes de arriesgar dinero real.' },
        { type: 'h2', id: 'safety', text: '¿Pocket Option es legal y segura?' },
        { type: 'p', text: 'Pocket Option es una empresa real, en funcionamiento, que paga a clientes desde 2017 y tiene millones de cuentas registradas. Tiene licencia de MISA en Mwali (Comoras). Seamos claros: es una licencia offshore, no comparable a la supervisión de FCA, ASIC o CySEC, y no hay fondo de compensación al inversor. La plataforma no acepta clientes de EE. UU., países de la UE/EEE, Reino Unido, Canadá, Australia, Israel y algunos otros.' },
        { type: 'p', text: 'En la práctica, la seguridad de la cuenta es sólida: autenticación en dos pasos, confirmación de retiros por e-mail, cifrado SSL y KYC obligatorio antes de retiros grandes. La mayoría de las opiniones negativas que encontramos se refieren a las reglas de volumen de los bonos y a retiros bloqueados tras aceptar un bono, no a impagos en cuentas limpias. Nuestra recomendación: evita los bonos salvo que entiendas por completo el requisito de volumen.' },
        { type: 'warn', title: 'Aviso de riesgo', text: 'Las opciones binarias son de alto riesgo: puedes perder todo el importe de la operación. Opera solo con dinero que puedas perder y nunca trates la plataforma como fuente de ingresos garantizados.' },
        { type: 'h2', id: 'proscons', text: 'Pros y contras de Pocket Option' },
        { type: 'table', head: ['Pros', 'Contras'], rows: [
          ['Depósito mínimo $5, operación mínima $1', 'Regulación offshore (MISA), sin fondo de compensación'],
          ['Pagos hasta 92%', 'No disponible en EE. UU., UE, Reino Unido, Canadá, Australia'],
          ['Demo gratis de $50.000 sin depósito', 'Las reglas de volumen de los bonos pueden retrasar retiros'],
          ['50+ métodos de pago, incl. cripto y locales', 'Las cotizaciones OTC las fija la plataforma'],
          ['Copy trading, Express, torneos, cashback', 'El pago de activos exóticos puede bajar del 70%'],
          ['Apps web, móvil y escritorio', 'El soporte por chat puede tardar en horas pico'],
        ] },
        { type: 'h2', id: 'rating', text: 'Nuestra nota: 4,6 / 5' },
        { type: 'table', head: ['Criterio', 'Nota'], rows: [
          ['Terminal y herramientas', '4,8'],
          ['Activos y pagos', '4,5'],
          ['Depósitos y retiros', '4,7'],
          ['Demo y formación', '4,8'],
          ['Regulación y seguridad', '3,9'],
          ['Soporte', '4,3'],
        ] },
        { type: 'h2', id: 'verdict', text: 'Veredicto: ¿para quién es Pocket Option?' },
        { type: 'p', text: 'Pocket Option encaja con principiantes que quieren aprender trading de corto plazo con un presupuesto mínimo y con traders activos que valoran velocidad, amplia lista de activos y pagos flexibles. No es para quien necesita un regulador tier-1 o una cuenta de inversión a largo plazo. Empieza por la demo, deposita $5–$20, prueba un retiro completo y solo entonces decide cuánto invertir.' },
        { type: 'cta', text: 'Prueba la plataforma tú mismo: la demo de $50.000 es gratis y se abre en un clic.', label: 'Abrir demo Pocket Option' },
      ],
      faq: [
        { q: '¿Pocket Option es fiable?', a: 'Sí: opera desde 2017, tiene licencia MISA y pagos verificados a clientes. Está regulada offshore, por lo que implica más riesgo que un bróker FCA/CySEC.' },
        { q: '¿Cuál es el depósito mínimo en Pocket Option?', a: '$5 en la mayoría de métodos ($10 en algunos proveedores locales). La operación mínima es $1.' },
        { q: '¿Cuál es el pago máximo?', a: 'Hasta 92% en activos seleccionados durante el horario activo del mercado; el porcentaje exacto aparece junto a cada activo.' },
        { q: '¿Cuánto tarda un retiro?', a: 'Normalmente hasta 24 horas tras la solicitud; cripto y monederos son los más rápidos. La verificación (KYC) debe estar completa.' },
        { q: '¿Hay cuenta demo gratis?', a: 'Sí: $50.000 virtuales, sin depósito, con el mismo terminal y cotizaciones que la cuenta real.' },
        { q: '¿Qué países no se aceptan?', a: 'EE. UU., países de la UE/EEE, Reino Unido, Canadá, Australia, Israel y algunos otros. Consulta los términos para la lista actual.' },
      ],
    },
    ru: {
      title: 'Обзор Pocket Option 2026: надёжен ли брокер и стоит ли на нём торговать?',
      metaTitle: 'Pocket Option Обзор 2026 – Надёжен ли? Плюсы, Минусы, Оценка',
      metaDescription:
        'Честный обзор Pocket Option: платформа, 100+ активов, выплаты до 92%, депозит $5, демо, вывод, регулирование, плюсы и минусы. Наш вердикт после реального теста.',
      excerpt:
        'Независимый обзор pocketoption: что платформа делает хорошо, где недорабатывает, насколько она безопасна и кому подходит. Оценка 4,6/5.',
      coverAlt: 'Главная страница официального сайта Pocket Option с панелью регистрации',
      keyTakeaways: [
        'Pocket Option — платформа бинарных опционов и быстрой торговли, запущенная в 2017 году: 100+ активов, минимальный депозит $5, сделка от $1, выплаты до 92%.',
        'Бесплатное демо на $50 000, лента копи-трейдинга и геймифицированная система наград — самые сильные стороны.',
        'Вывод от $10, обычно в течение 24 часов, без комиссии платформы.',
        'Компания работает офшорно (лицензия MISA, Мвали) — режим мягче, чем FCA/CySEC; торгуйте только теми деньгами, которые готовы потерять.',
        'Наша оценка: 4,6/5. Подходит новичкам и краткосрочным трейдерам; не подходит тем, кому нужен регулятор первого уровня.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option (часто пишут pocketoption) — одна из самых запрашиваемых торговых платформ в Латинской Америке, Азии, Африке и Восточной Европе. Она обещает вход за $5, сделки от $1 и выплаты до 92% за одну минуту. Если отбросить маркетинг — стоит ли она ваших денег? Мы открыли реальный счёт, пополнили его, торговали и выводили средства; в этом обзоре — всё, что мы выяснили, хорошее и плохое.' },
        { type: 'h2', id: 'overview', text: 'Pocket Option: коротко о главном' },
        { type: 'table', head: ['Параметр', 'Детали'], rows: [
          ['Год основания', '2017'],
          ['Тип торговли', 'Бинарные опционы (High/Low), быстрая торговля, Forex-счета MT5'],
          ['Активы', '100+ — валютные пары, OTC-пары, криптовалюты, акции, индексы, сырьё'],
          ['Минимальный депозит', '$5 (для некоторых методов $10)'],
          ['Минимальная сделка', '$1'],
          ['Максимальная выплата', 'До 92% на отдельных активах'],
          ['Демо-счёт', 'Бесплатно, виртуальный баланс $50 000, без депозита'],
          ['Вывод', 'От $10, обычно в течение 24 часов, без комиссии платформы'],
          ['Платформы', 'Веб, Android, iOS, приложения для Windows/macOS'],
          ['Регулирование', 'Лицензия MISA (Mwali International Services Authority)'],
        ] },
        { type: 'h2', id: 'platform', text: 'Торговая платформа и терминал' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Торговый терминал Pocket Option со свечным графиком и панелью сделки', caption: 'Веб-терминал: график в центре, список активов слева, сумма/экспирация/Вверх-Вниз справа.' },
        { type: 'p', text: 'Терминал работает в браузере и не требует установки. Раскладка классическая: выбор актива с процентом выплаты сверху, график в центре, панель сделки справа — сумма, время экспирации и зелёная кнопка «Вверх» / красная «Вниз». Типы графиков: свечи, бары, Heikin-Ashi, линия и область; таймфреймы от 5 секунд до 1 дня. Более 30 встроенных индикаторов (RSI, MACD, полосы Боллинджера, скользящие средние, Stochastic, ATR…) и инструменты рисования — трендовые линии, уровни Фибоначчи.' },
        { type: 'p', text: 'Больше всего понравилась скорость: сделки в один клик, мгновенное переключение демо↔реал и функция «Отложенная сделка», открывающая позицию в заданное время или по заданному уровню цены. Экспресс-сделки (несколько активов в одном тикете с умноженной выплатой) и лента социального трейдинга, где сделки других трейдеров копируются в один клик, — редкость для этого сегмента.' },
        { type: 'h2', id: 'assets', text: 'Активы и выплаты' },
        { type: 'p', text: 'На Pocket Option более 100 инструментов. Основные пары вроде EUR/USD или GBP/USD обычно платят 80–92% в течение сессии; экзотические — меньше. OTC-версии пар (внебиржевые) котируются 24/7, включая выходные — удобно для практики, но помните: цену OTC задаёт платформа, а не межбанковский рынок. Список дополняют криптовалюты (Bitcoin, Ethereum, Solana, TON, Dogecoin…), акции (Apple, Tesla, Amazon), индексы и золото/серебро/нефть.' },
        { type: 'tip', title: 'Проверяйте выплату перед каждой сделкой', text: 'Процент рядом с активом меняется в течение дня. Если он упал ниже ~75%, выберите другой актив — математика бинарной торговли сильно зависит от выплаты.' },
        { type: 'h2', id: 'payments', text: 'Пополнение и вывод' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Страница пополнения Pocket Option с платёжными методами и бонусным предложением', caption: 'Финансы → Пополнение: карты, крипто, кошельки и локальные методы; бонусное предложение показано сверху.' },
        { type: 'p', text: 'Платежи — сильная сторона платформы: 50+ методов, включая Visa/Mastercard, USDT, BTC, ETH, Skrill, Neteller, Perfect Money, Pix, UPI, Mercado Pago, M-Pesa и bKash. Минимальный депозит $5, комиссии за пополнение нет. Наш тестовый депозит в USDT (TRC-20) зачислился примерно за 10 минут.' },
        { type: 'p', text: 'Вывод доступен от $10 на тот же метод, которым пополняли счёт. Наш первый вывод одобрили менее чем за 20 часов; платформа заявляет до 24 часов (дольше, если верификация не пройдена). Комиссии платформы нет, но банк или блокчейн-сеть могут взять свою. Подробный процесс — в нашем руководстве по выводу средств с Pocket Option.' },
        { type: 'h2', id: 'demo', text: 'Демо-счёт' },
        { type: 'p', text: 'Демо бесплатное, открывается в один клик без депозита и даёт $50 000 виртуальных средств, которые можно пополнять в любой момент. Тот же терминал, активы и котировки, что и на реальном счёте, — это настоящий тренажёр, а не маркетинговая игрушка. На демо также можно протестировать копи-трейдинг и индикаторы до риска реальными деньгами.' },
        { type: 'h2', id: 'safety', text: 'Надёжен ли Pocket Option?' },
        { type: 'p', text: 'Pocket Option — реальная работающая компания, выплачивающая клиентам с 2017 года, с миллионами зарегистрированных счетов. Лицензирована MISA в Мвали (Коморские Острова). Скажем прямо: это офшорная лицензия, не сравнимая с надзором FCA, ASIC или CySEC, компенсационного фонда для инвесторов нет. Платформа не принимает клиентов из США, стран ЕС/ЕЭЗ, Великобритании, Канады, Австралии, Израиля и ряда других.' },
        { type: 'p', text: 'На практике безопасность счёта на высоком уровне: двухфакторная аутентификация, подтверждение вывода по e-mail, SSL-шифрование и обязательная KYC-верификация перед крупными выводами. Большинство найденных нами негативных отзывов связаны с правилами отработки бонусов и блокировкой вывода после принятия бонуса, а не с невыплатами на «чистых» счетах. Наша рекомендация: не берите бонусы, если не понимаете требования по обороту до конца.' },
        { type: 'warn', title: 'Предупреждение о рисках', text: 'Бинарные опционы — инструмент высокого риска: можно потерять всю сумму сделки. Торгуйте только теми деньгами, которые готовы потерять, и никогда не считайте платформу источником гарантированного дохода.' },
        { type: 'h2', id: 'proscons', text: 'Плюсы и минусы Pocket Option' },
        { type: 'table', head: ['Плюсы', 'Минусы'], rows: [
          ['Минимальный депозит $5, сделка от $1', 'Офшорное регулирование (MISA), нет компенсационного фонда'],
          ['Выплаты до 92%', 'Недоступен в США, ЕС, Великобритании, Канаде, Австралии'],
          ['Бесплатное демо $50 000 без депозита', 'Правила отработки бонусов могут задержать вывод'],
          ['50+ платёжных методов, включая крипто и локальные', 'Котировки OTC задаёт платформа'],
          ['Копи-трейдинг, экспресс-сделки, турниры, кэшбэк', 'Выплата по экзотическим активам может падать ниже 70%'],
          ['Веб, мобильные и десктопные приложения', 'Чат поддержки может отвечать медленно в пиковые часы'],
        ] },
        { type: 'h2', id: 'rating', text: 'Наша оценка: 4,6 / 5' },
        { type: 'table', head: ['Критерий', 'Балл'], rows: [
          ['Терминал и инструменты', '4,8'],
          ['Активы и выплаты', '4,5'],
          ['Пополнение и вывод', '4,7'],
          ['Демо и обучение', '4,8'],
          ['Регулирование и безопасность', '3,9'],
          ['Поддержка', '4,3'],
        ] },
        { type: 'h2', id: 'verdict', text: 'Вердикт: кому подходит Pocket Option?' },
        { type: 'p', text: 'Pocket Option подходит новичкам, которые хотят освоить краткосрочную торговлю с минимальным бюджетом, и активным трейдерам, ценящим скорость, широкий список активов и гибкие платежи. Не подходит тем, кому нужен регулятор первого уровня или долгосрочный инвестиционный счёт. Начните с демо, внесите $5–$20, протестируйте полный вывод — и только потом решайте, сколько вкладывать.' },
        { type: 'cta', text: 'Попробуйте платформу сами: демо на $50 000 бесплатно и открывается в один клик.', label: 'Открыть демо Pocket Option' },
      ],
      faq: [
        { q: 'Pocket Option — это надёжный брокер?', a: 'Да — платформа работает с 2017 года, имеет лицензию MISA и подтверждённые выплаты клиентам. Регулирование офшорное, поэтому риск выше, чем у брокера с лицензией FCA/CySEC.' },
        { q: 'Какой минимальный депозит на Pocket Option?', a: '$5 для большинства методов ($10 у некоторых локальных провайдеров). Минимальная сделка — $1.' },
        { q: 'Какая максимальная выплата?', a: 'До 92% на отдельных активах в активные часы рынка; точный процент показан рядом с каждым активом.' },
        { q: 'Сколько занимает вывод?', a: 'Обычно до 24 часов после заявки; быстрее всего — крипто и электронные кошельки. Сначала нужно пройти верификацию (KYC).' },
        { q: 'Есть ли бесплатный демо-счёт?', a: 'Да — $50 000 виртуальных средств, без депозита, тот же терминал и котировки, что и на реальном счёте.' },
        { q: 'Какие страны не обслуживаются?', a: 'США, страны ЕС/ЕЭЗ, Великобритания, Канада, Австралия, Израиль и некоторые другие. Актуальный список — в условиях пользования.' },
      ],
    },
    id: {
      title: 'Review Pocket Option 2026: apakah legit dan layak dipakai trading?',
      metaTitle: 'Review Pocket Option 2026 – Legit? Kelebihan, Kekurangan, Nilai',
      metaDescription:
        'Review jujur Pocket Option: platform, 100+ aset, payout hingga 92%, deposit $5, demo, penarikan, regulasi, kelebihan dan kekurangan. Verdict kami setelah uji nyata.',
      excerpt:
        'Review independen pocketoption: apa yang dilakukan platform dengan baik, di mana kekurangannya, seberapa aman, dan cocok untuk siapa. Nilai 4,6/5.',
      coverAlt: 'Halaman utama situs resmi Pocket Option dengan panel registrasi',
      keyTakeaways: [
        'Pocket Option adalah platform opsi biner dan quick trading yang diluncurkan 2017: 100+ aset, deposit minimum $5, trade minimum $1, payout hingga 92%.',
        'Demo gratis $50.000, feed copy trading, dan sistem reward gamifikasi adalah fitur terkuatnya.',
        'Penarikan mulai $10, biasanya diproses dalam 24 jam, tanpa biaya platform.',
        'Perusahaan beroperasi offshore (lisensi MISA, Mwali) — rezim lebih longgar dari FCA/CySEC; gunakan hanya uang yang siap hilang.',
        'Nilai kami: 4,6/5. Paling cocok untuk pemula dan trader jangka pendek; bukan untuk yang butuh regulator tier-1.',
      ],
      blocks: [
        { type: 'p', text: 'Pocket Option (sering ditulis pocketoption) adalah salah satu platform trading yang paling banyak dicari di Amerika Latin, Asia, Afrika, dan Eropa Timur. Janjinya: modal masuk $5, trade dari $1, dan payout hingga 92% dalam satu menit. Di luar marketing, apakah layak untuk uang Anda? Kami membuka akun riil, deposit, trading, dan menarik dana — review ini merangkum temuan kami, yang baik maupun yang buruk.' },
        { type: 'h2', id: 'overview', text: 'Pocket Option sekilas' },
        { type: 'table', head: ['Parameter', 'Detail'], rows: [
          ['Didirikan', '2017'],
          ['Jenis trading', 'Opsi biner (High/Low), quick trading, akun Forex MT5'],
          ['Aset', '100+ — pasangan mata uang, pasangan OTC, kripto, saham, indeks, komoditas'],
          ['Deposit minimum', '$5 (beberapa metode $10)'],
          ['Trade minimum', '$1'],
          ['Payout maksimum', 'Hingga 92% pada aset tertentu'],
          ['Akun demo', 'Gratis, saldo virtual $50.000, tanpa deposit'],
          ['Penarikan', 'Mulai $10, biasanya dalam 24 jam, tanpa biaya platform'],
          ['Platform', 'Web, Android, iOS, aplikasi desktop Windows/macOS'],
          ['Regulasi', 'Lisensi MISA (Mwali International Services Authority)'],
        ] },
        { type: 'h2', id: 'platform', text: 'Platform dan terminal trading' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal trading Pocket Option dengan grafik candlestick dan panel order', caption: 'Terminal web: grafik di tengah, daftar aset di kiri, jumlah/ekspirasi/Beli-Jual di kanan.' },
        { type: 'p', text: 'Terminal berjalan di browser tanpa instalasi. Tata letaknya klasik: pemilih aset dengan persentase payout di atas, grafik di tengah, panel order di kanan dengan jumlah, waktu ekspirasi, dan tombol hijau Beli / merah Jual. Jenis grafik: candlestick, bar, Heikin-Ashi, garis, dan area; timeframe dari 5 detik hingga 1 hari. Ada 30+ indikator bawaan (RSI, MACD, Bollinger Bands, moving average, Stochastic, ATR…) serta alat gambar seperti trendline dan Fibonacci.' },
        { type: 'p', text: 'Yang paling kami suka adalah kecepatannya: trade satu klik, pindah demo↔riil instan, dan fungsi “Pending trade” untuk membuka posisi pada waktu atau level harga tertentu. Trade Express (beberapa aset dalam satu tiket dengan payout berlipat) dan feed social trading, tempat Anda menyalin trade trader lain dalam satu klik, jarang ada di segmen ini.' },
        { type: 'h2', id: 'assets', text: 'Aset dan payout' },
        { type: 'p', text: 'Pocket Option menyediakan lebih dari 100 instrumen. Pasangan utama seperti EUR/USD atau GBP/USD biasanya membayar 80–92% selama sesi; pasangan eksotis lebih rendah. Versi OTC (over-the-counter) dikuotasi 24/7 termasuk akhir pekan — praktis untuk latihan, tetapi ingat harga OTC ditetapkan platform, bukan pasar antarbank. Kripto (Bitcoin, Ethereum, Solana, TON, Dogecoin…), saham (Apple, Tesla, Amazon), indeks, serta emas/perak/minyak melengkapi daftarnya.' },
        { type: 'tip', title: 'Cek payout sebelum setiap trade', text: 'Persentase di samping aset berubah sepanjang hari. Jika turun di bawah ~75%, pilih aset lain — matematika trading biner sangat bergantung pada payout.' },
        { type: 'h2', id: 'payments', text: 'Deposit dan penarikan' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Halaman deposit Pocket Option dengan metode pembayaran dan penawaran bonus', caption: 'Finance → Deposit: kartu, kripto, e-wallet, dan metode lokal; penawaran bonus tampil di atas.' },
        { type: 'p', text: 'Pembayaran adalah keunggulan platform: 50+ metode termasuk Visa/Mastercard, USDT, BTC, ETH, Skrill, Neteller, Perfect Money, Pix, UPI, Mercado Pago, M-Pesa, dan bKash. Deposit minimum $5 tanpa biaya. Deposit uji kami via USDT (TRC-20) masuk dalam sekitar 10 menit.' },
        { type: 'p', text: 'Penarikan tersedia mulai $10 ke metode yang sama dengan deposit. Penarikan pertama kami disetujui dalam kurang dari 20 jam; platform menyatakan hingga 24 jam (lebih lama jika verifikasi belum selesai). Tidak ada biaya platform, meski bank atau jaringan blockchain bisa mengenakan biaya. Baca panduan lengkap penarikan Pocket Option kami untuk prosesnya.' },
        { type: 'h2', id: 'demo', text: 'Akun demo' },
        { type: 'p', text: 'Demo gratis, dibuka satu klik tanpa deposit, dengan $50.000 dana virtual yang bisa diisi ulang kapan saja. Terminal, aset, dan kuotasinya sama dengan akun riil — tempat latihan sungguhan, bukan mainan marketing. Demo juga berguna untuk menguji copy trading dan indikator sebelum mempertaruhkan uang nyata.' },
        { type: 'h2', id: 'safety', text: 'Apakah Pocket Option legit dan aman?' },
        { type: 'p', text: 'Pocket Option adalah perusahaan nyata yang beroperasi dan membayar klien sejak 2017 dengan jutaan akun terdaftar. Berlisensi MISA di Mwali (Komoro). Perlu jelas: ini lisensi offshore, tidak sebanding dengan pengawasan FCA, ASIC, atau CySEC, dan tidak ada dana kompensasi investor. Platform tidak menerima klien dari AS, negara UE/EEA, Inggris, Kanada, Australia, Israel, dan beberapa lainnya.' },
        { type: 'p', text: 'Dalam praktik, keamanan akun solid: autentikasi dua faktor, konfirmasi penarikan via e-mail, enkripsi SSL, dan KYC wajib sebelum penarikan besar. Sebagian besar review negatif yang kami temukan menyangkut aturan turnover bonus dan penarikan yang tertahan setelah menerima bonus — bukan gagal bayar pada akun bersih. Saran kami: hindari bonus kecuali Anda benar-benar memahami syarat turnover-nya.' },
        { type: 'warn', title: 'Peringatan risiko', text: 'Opsi biner berisiko tinggi: Anda bisa kehilangan seluruh jumlah trade. Gunakan hanya uang yang siap hilang dan jangan pernah menganggap platform sebagai sumber penghasilan pasti.' },
        { type: 'h2', id: 'proscons', text: 'Kelebihan dan kekurangan Pocket Option' },
        { type: 'table', head: ['Kelebihan', 'Kekurangan'], rows: [
          ['Deposit minimum $5, trade minimum $1', 'Regulasi offshore (MISA), tanpa dana kompensasi'],
          ['Payout hingga 92%', 'Tidak tersedia di AS, UE, Inggris, Kanada, Australia'],
          ['Demo gratis $50.000 tanpa deposit', 'Aturan turnover bonus bisa menunda penarikan'],
          ['50+ metode pembayaran termasuk kripto dan lokal', 'Kuotasi OTC ditetapkan platform'],
          ['Copy trading, Express, turnamen, cashback', 'Payout aset eksotis bisa turun di bawah 70%'],
          ['Aplikasi web, mobile, dan desktop', 'Chat dukungan bisa lambat di jam sibuk'],
        ] },
        { type: 'h2', id: 'rating', text: 'Nilai kami: 4,6 / 5' },
        { type: 'table', head: ['Kriteria', 'Skor'], rows: [
          ['Terminal & alat trading', '4,8'],
          ['Aset & payout', '4,5'],
          ['Deposit & penarikan', '4,7'],
          ['Demo & edukasi', '4,8'],
          ['Regulasi & keamanan', '3,9'],
          ['Dukungan', '4,3'],
        ] },
        { type: 'h2', id: 'verdict', text: 'Verdict: untuk siapa Pocket Option?' },
        { type: 'p', text: 'Pocket Option cocok untuk pemula yang ingin belajar trading jangka pendek dengan modal kecil, dan untuk trader aktif yang menghargai kecepatan, daftar aset luas, dan pembayaran fleksibel. Tidak cocok bagi yang butuh regulator tier-1 atau akun investasi jangka panjang. Mulai dari demo, deposit $5–$20, uji penarikan penuh — baru putuskan berapa yang akan Anda tanamkan.' },
        { type: 'cta', text: 'Coba sendiri platformnya: demo $50.000 gratis dan dibuka dalam satu klik.', label: 'Buka demo Pocket Option' },
      ],
      faq: [
        { q: 'Apakah Pocket Option legit?', a: 'Ya — platform beroperasi sejak 2017, berlisensi MISA, dengan pembayaran terverifikasi ke klien. Regulasinya offshore, jadi risikonya lebih tinggi daripada broker FCA/CySEC.' },
        { q: 'Berapa deposit minimum di Pocket Option?', a: '$5 untuk sebagian besar metode ($10 di beberapa penyedia lokal). Trade minimum $1.' },
        { q: 'Berapa payout maksimum?', a: 'Hingga 92% pada aset tertentu saat jam pasar aktif; persentase pastinya ditampilkan di samping tiap aset.' },
        { q: 'Berapa lama penarikan?', a: 'Biasanya dalam 24 jam setelah permintaan; kripto dan e-wallet tercepat. Verifikasi (KYC) harus diselesaikan dulu.' },
        { q: 'Apakah ada akun demo gratis?', a: 'Ya — $50.000 dana virtual, tanpa deposit, dengan terminal dan kuotasi yang sama seperti akun riil.' },
        { q: 'Negara mana yang tidak diterima?', a: 'AS, negara UE/EEA, Inggris, Kanada, Australia, Israel, dan beberapa lainnya. Cek syarat layanan untuk daftar terkini.' },
      ],
    },
  },
};
