import type { BlogPost } from '../types';

const IMG_TERMINAL = '/images/blog/po-trading-terminal.webp';
const IMG_MACD = '/images/blog/po-macd-lines.webp';

export const pocketOptionStrategies: BlogPost = {
  slug: 'pocket-option-strategies',
  category: 'strategy',
  cover: '/images/blog/pocket-option-strategies.webp',
  publishedAt: '2026-09-19',
  updatedAt: '2026-09-19',
  readingMinutes: 10,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Best Pocket Option strategies for beginners: 5 simple setups that actually make sense',
      metaTitle: 'Pocket Option Strategy Guide – 5 Best Setups for Beginners',
      metaDescription:
        'Five Pocket Option strategies explained step by step: EMA trend, support/resistance, RSI reversal, MACD crossover and breakout — with timeframes, expiry and money management.',
      excerpt:
        'A practical pocketoption strategy guide: five beginner-friendly setups, which timeframe and expiry to use, and the money-management rules that keep you in the game.',
      coverAlt: 'Bullish MACD crossover example on a Pocket Option chart',
      keyTakeaways: [
        'No strategy wins every trade; a good Pocket Option strategy is a repeatable set of rules with a positive expectancy over many trades.',
        'Beginners do best with trend-following setups (EMA 9/21, MACD crossover) on 1–5 minute charts with expiry of 2–5 candles.',
        'Trade in the direction of the higher timeframe trend, avoid the first minutes after news, and pick assets with payout above 80%.',
        'Risk 1–2% of the balance per trade and stop after 3 consecutive losses — money management matters more than the indicator.',
        'Test every strategy on the free $50,000 demo for at least 50 trades before using real money.',
      ],
      blocks: [
        { type: 'p', text: 'Search “Pocket Option strategy” and you will find hundreds of videos promising 95% win rates. The reality: binary options are a probability game, and the traders who last are the ones with clear entry rules, sensible expiry times and strict risk limits. Below are five strategies that beginners can actually follow on pocketoption — each with the indicator settings, timeframe and expiry we recommend — plus the money-management framework that ties them together.' },
        { type: 'h2', id: 'basics', text: 'Before the strategies: three rules that apply to all of them' },
        { type: 'ul', items: [
          'Trade with the trend of the higher timeframe. If the 15-minute chart is rising, look only for Buy signals on the 1-minute chart.',
          'Choose assets with a payout of 80%+ (shown next to the asset name). At 80% payout you need to win about 56% of trades to break even.',
          'Avoid the first 5–10 minutes after major economic news and the very quiet Asian session hours, when spreads widen and price moves randomly.',
        ] },
        { type: 'image', src: IMG_TERMINAL, alt: 'Pocket Option trading terminal with chart, indicators panel and trade buttons', caption: 'Indicators are added from the “Indicators” button in the top toolbar; expiry and amount are set on the right.' },
        { type: 'h2', id: 'ema', text: 'Strategy 1: EMA 9/21 trend following' },
        { type: 'p', text: 'Two exponential moving averages show the short-term trend. When the fast EMA (9) is above the slow EMA (21) the trend is up; you buy on pullbacks to the EMA 9. When it is below, you sell on rallies back to the EMA 9.' },
        { type: 'table', head: ['Setting', 'Value'], rows: [
          ['Indicators', 'EMA 9 and EMA 21'],
          ['Timeframe', '1 minute (or 5 minutes for calmer entries)'],
          ['Expiry', '3–5 candles (3–5 min on M1)'],
          ['Buy signal', 'EMA 9 > EMA 21, price touches EMA 9 and prints a bullish candle'],
          ['Sell signal', 'EMA 9 < EMA 21, price touches EMA 9 and prints a bearish candle'],
          ['Skip when', 'EMAs are flat and intertwined (no trend)'],
        ] },
        { type: 'h2', id: 'sr', text: 'Strategy 2: support and resistance bounce' },
        { type: 'p', text: 'Price tends to react at levels where it reversed before. Mark the last 2–3 swing highs and lows on the 5-minute chart with horizontal lines. When price returns to a level and forms a rejection candle (a pin bar or engulfing candle), enter in the direction of the bounce.' },
        { type: 'ol', items: [
          'Draw horizontal lines at clear recent highs and lows (at least two touches).',
          'Wait for price to reach a level — do not anticipate.',
          'Confirm with a rejection candle: long wick into the level, close back inside.',
          'Enter with an expiry of 3–5 candles. Skip the trade if the candle closes beyond the level (possible breakout).',
        ] },
        { type: 'tip', title: 'Combine with RSI', text: 'A bounce from support is stronger when RSI is below 30, and a bounce from resistance when RSI is above 70. The two-factor confirmation filters out many false signals.' },
        { type: 'h2', id: 'rsi', text: 'Strategy 3: RSI reversal (overbought / oversold)' },
        { type: 'p', text: 'The Relative Strength Index measures momentum. Readings above 70 suggest the asset is overbought, below 30 oversold. On its own RSI gives many false signals in a strong trend, so use it in ranging markets or as a filter for the two strategies above.' },
        { type: 'table', head: ['Setting', 'Value'], rows: [
          ['Indicator', 'RSI, period 14 (or 7 for faster signals)'],
          ['Timeframe', '1–5 minutes'],
          ['Expiry', '2–3 candles'],
          ['Buy signal', 'RSI drops below 30 and then crosses back above 30'],
          ['Sell signal', 'RSI rises above 70 and then crosses back below 70'],
          ['Skip when', 'A strong one-directional trend is in progress (RSI stays pinned above 70 / below 30)'],
        ] },
        { type: 'h2', id: 'macd', text: 'Strategy 4: MACD crossover' },
        { type: 'image', src: IMG_MACD, alt: 'MACD line crossing above the signal line — bullish crossover example', caption: 'A bullish MACD crossover: the MACD line (blue) crosses above the signal line (orange) below the zero line.' },
        { type: 'p', text: 'MACD (12, 26, 9) combines trend and momentum. A bullish crossover happens when the MACD line crosses above the signal line; a bearish crossover when it crosses below. The best signals occur when the crossover agrees with the direction of the EMA trend and the histogram starts growing.' },
        { type: 'ol', items: [
          'Add MACD with the default settings 12 / 26 / 9 on the 5-minute chart.',
          'Wait for the MACD line to cross the signal line and for the candle to close.',
          'Check the higher timeframe (15 min): trade only crossovers in that direction.',
          'Enter with an expiry of 3–5 candles (15–25 minutes on M5).',
        ] },
        { type: 'h2', id: 'breakout', text: 'Strategy 5: consolidation breakout with confirmation' },
        { type: 'p', text: 'When price moves sideways in a narrow range for 10–20 candles, it is storing energy. A breakout from that range often continues for several candles. The trap is the false breakout — so enter only after the breakout candle closes outside the range and, ideally, after a small retest of the broken level.' },
        { type: 'ul', items: [
          'Timeframe: 1–5 minutes; expiry: 3–5 candles.',
          'Range must be clearly defined: at least 10 candles between two flat levels.',
          'Confirmation: a full-bodied candle closing outside the range with rising volume (if the asset shows volume).',
          'Never trade breakouts during major news — spikes reverse in seconds.',
        ] },
        { type: 'h2', id: 'money', text: 'Money management: the part most beginners skip' },
        { type: 'p', text: 'A 60% win rate with poor money management still empties the account. Use fixed fractional sizing: risk 1–2% of your balance per trade, always the same amount. With a $100 balance that is $1–$2 per trade — which Pocket Option allows, since the minimum trade is $1.' },
        { type: 'table', head: ['Rule', 'Why'], rows: [
          ['Risk 1–2% per trade', 'Survives losing streaks; 10 losses in a row cost only 10–20%'],
          ['Stop after 3 losses in a row', 'Prevents revenge trading when the market or your focus is off'],
          ['Daily loss limit 5–6%', 'Caps a bad day; come back tomorrow'],
          ['Never use martingale (doubling after a loss)', 'A few losses in a row exceed your balance or the maximum trade size'],
          ['Keep a trade journal', 'Only way to know which strategy actually works for you'],
        ] },
        { type: 'warn', title: 'Trading involves risk', text: 'No strategy — including those above — guarantees profit. Binary options can result in the loss of the full trade amount. Use only money you can afford to lose and treat every strategy as a hypothesis to test on demo first.' },
        { type: 'h2', id: 'demo', text: 'How to test a strategy on Pocket Option' },
        { type: 'ol', items: [
          'Open the free demo account ($50,000 virtual balance).',
          'Choose one strategy and one asset (e.g. EUR/USD) — do not mix.',
          'Make at least 50 trades following the rules exactly, logging each result.',
          'Calculate the win rate. You need about 56% at 80% payout; aim for 60%+ before going live.',
          'Move to a real account with a small deposit ($10–$50) and the same 1–2% risk.',
        ] },
        { type: 'cta', text: 'Test these strategies without risk: the Pocket Option demo has the same charts, indicators and quotes as the real account.', label: 'Open free demo' },
      ],
      faq: [
        { q: 'What is the best strategy for Pocket Option?', a: 'For beginners, a trend-following setup such as EMA 9/21 or MACD crossover on 1–5 minute charts, combined with strict 1–2% risk per trade. The “best” strategy is the one you can follow consistently.' },
        { q: 'Which timeframe should I use?', a: '1-minute charts give more signals but more noise; 5-minute charts are calmer and better for learning. Always check the 15-minute chart for the overall trend.' },
        { q: 'Which expiry time is best?', a: 'A rule of thumb is 3–5 candles of your chart timeframe: 3–5 minutes on M1, 15–25 minutes on M5.' },
        { q: 'Is there a 100% winning strategy?', a: 'No. Anyone promising guaranteed results is misleading you. Realistic strategies win 55–65% of trades over a large sample.' },
        { q: 'Does martingale work on Pocket Option?', a: 'It can look profitable briefly but one long losing streak wipes the account. We do not recommend it.' },
        { q: 'Can I use these strategies on OTC assets?', a: 'Yes, but OTC quotes are generated by the platform and behave differently from live markets. Test separately on demo before trading OTC with real money.' },
      ],
    },
    pt: {
      title: 'Melhores estratégias Pocket Option para iniciantes: 5 setups simples que fazem sentido',
      metaTitle: 'Estratégias Pocket Option – 5 Melhores Setups para Iniciantes',
      metaDescription:
        'Cinco estratégias Pocket Option explicadas passo a passo: tendência EMA, suporte/resistência, reversão RSI, cruzamento MACD e rompimento — com timeframes, expiração e gestão.',
      excerpt:
        'Guia prático de estratégias pocketoption: cinco setups para iniciantes, qual timeframe e expiração usar e as regras de gestão de risco que mantêm você no jogo.',
      coverAlt: 'Exemplo de cruzamento MACD de alta em um gráfico da Pocket Option',
      keyTakeaways: [
        'Nenhuma estratégia vence todas as operações; uma boa estratégia Pocket Option é um conjunto de regras repetível com expectativa positiva em muitas operações.',
        'Iniciantes se dão melhor com setups de tendência (EMA 9/21, cruzamento MACD) em gráficos de 1–5 minutos com expiração de 2–5 candles.',
        'Opere na direção da tendência do timeframe maior, evite os primeiros minutos após notícias e escolha ativos com payout acima de 80%.',
        'Arrisque 1–2% do saldo por operação e pare após 3 perdas seguidas — a gestão de risco importa mais que o indicador.',
        'Teste cada estratégia na demo gratuita de $50.000 por pelo menos 50 operações antes de usar dinheiro real.',
      ],
      blocks: [
        { type: 'p', text: 'Pesquise “estratégia Pocket Option” e encontrará centenas de vídeos prometendo 95% de acerto. A realidade: opções binárias são um jogo de probabilidade, e os traders que duram são os que têm regras de entrada claras, expirações sensatas e limites de risco rígidos. Abaixo, cinco estratégias que iniciantes conseguem de fato seguir na pocketoption — cada uma com configuração de indicador, timeframe e expiração recomendados — mais a estrutura de gestão de risco que une tudo.' },
        { type: 'h2', id: 'basics', text: 'Antes das estratégias: três regras que valem para todas' },
        { type: 'ul', items: [
          'Opere a favor da tendência do timeframe maior. Se o gráfico de 15 minutos sobe, procure apenas sinais de Compra no gráfico de 1 minuto.',
          'Escolha ativos com payout de 80%+ (ao lado do nome do ativo). Com payout de 80% você precisa acertar cerca de 56% das operações para empatar.',
          'Evite os primeiros 5–10 minutos após notícias econômicas importantes e as horas muito calmas da sessão asiática, quando o preço se move de forma aleatória.',
        ] },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal de operações da Pocket Option com gráfico, painel de indicadores e botões de operação', caption: 'Indicadores são adicionados pelo botão “Indicadores” na barra superior; expiração e valor ficam à direita.' },
        { type: 'h2', id: 'ema', text: 'Estratégia 1: seguir a tendência com EMA 9/21' },
        { type: 'p', text: 'Duas médias móveis exponenciais mostram a tendência de curto prazo. Quando a EMA rápida (9) está acima da lenta (21), a tendência é de alta; você compra nos recuos até a EMA 9. Quando está abaixo, você vende nos repiques até a EMA 9.' },
        { type: 'table', head: ['Configuração', 'Valor'], rows: [
          ['Indicadores', 'EMA 9 e EMA 21'],
          ['Timeframe', '1 minuto (ou 5 minutos para entradas mais calmas)'],
          ['Expiração', '3–5 candles (3–5 min em M1)'],
          ['Sinal de compra', 'EMA 9 > EMA 21, preço toca a EMA 9 e forma candle de alta'],
          ['Sinal de venda', 'EMA 9 < EMA 21, preço toca a EMA 9 e forma candle de baixa'],
          ['Não operar quando', 'EMAs planas e entrelaçadas (sem tendência)'],
        ] },
        { type: 'h2', id: 'sr', text: 'Estratégia 2: repique em suporte e resistência' },
        { type: 'p', text: 'O preço tende a reagir em níveis onde reverteu antes. Marque os últimos 2–3 topos e fundos do gráfico de 5 minutos com linhas horizontais. Quando o preço volta a um nível e forma um candle de rejeição (pin bar ou engolfo), entre na direção do repique.' },
        { type: 'ol', items: [
          'Desenhe linhas horizontais em topos e fundos recentes claros (pelo menos dois toques).',
          'Espere o preço chegar ao nível — não antecipe.',
          'Confirme com candle de rejeição: pavio longo no nível, fechamento de volta para dentro.',
          'Entre com expiração de 3–5 candles. Pule a operação se o candle fechar além do nível (possível rompimento).',
        ] },
        { type: 'tip', title: 'Combine com RSI', text: 'Um repique no suporte é mais forte quando o RSI está abaixo de 30, e na resistência quando o RSI está acima de 70. A confirmação dupla filtra muitos sinais falsos.' },
        { type: 'h2', id: 'rsi', text: 'Estratégia 3: reversão com RSI (sobrecomprado / sobrevendido)' },
        { type: 'p', text: 'O Índice de Força Relativa mede o momentum. Leituras acima de 70 sugerem ativo sobrecomprado; abaixo de 30, sobrevendido. Sozinho, o RSI gera muitos sinais falsos em tendência forte, então use-o em mercados laterais ou como filtro para as duas estratégias acima.' },
        { type: 'table', head: ['Configuração', 'Valor'], rows: [
          ['Indicador', 'RSI, período 14 (ou 7 para sinais mais rápidos)'],
          ['Timeframe', '1–5 minutos'],
          ['Expiração', '2–3 candles'],
          ['Sinal de compra', 'RSI cai abaixo de 30 e depois cruza de volta acima de 30'],
          ['Sinal de venda', 'RSI sobe acima de 70 e depois cruza de volta abaixo de 70'],
          ['Não operar quando', 'Tendência forte em uma direção (RSI preso acima de 70 / abaixo de 30)'],
        ] },
        { type: 'h2', id: 'macd', text: 'Estratégia 4: cruzamento MACD' },
        { type: 'image', src: IMG_MACD, alt: 'Linha MACD cruzando acima da linha de sinal — exemplo de cruzamento de alta', caption: 'Cruzamento MACD de alta: a linha MACD (azul) cruza acima da linha de sinal (laranja) abaixo da linha zero.' },
        { type: 'p', text: 'O MACD (12, 26, 9) combina tendência e momentum. O cruzamento de alta ocorre quando a linha MACD cruza acima da linha de sinal; o de baixa, quando cruza abaixo. Os melhores sinais acontecem quando o cruzamento concorda com a direção da tendência das EMAs e o histograma começa a crescer.' },
        { type: 'ol', items: [
          'Adicione o MACD com as configurações padrão 12 / 26 / 9 no gráfico de 5 minutos.',
          'Espere a linha MACD cruzar a linha de sinal e o candle fechar.',
          'Confira o timeframe maior (15 min): opere apenas cruzamentos naquela direção.',
          'Entre com expiração de 3–5 candles (15–25 minutos em M5).',
        ] },
        { type: 'h2', id: 'breakout', text: 'Estratégia 5: rompimento de consolidação com confirmação' },
        { type: 'p', text: 'Quando o preço anda de lado em uma faixa estreita por 10–20 candles, está acumulando energia. O rompimento dessa faixa costuma continuar por vários candles. A armadilha é o rompimento falso — então entre só após o candle de rompimento fechar fora da faixa e, idealmente, após um pequeno reteste do nível rompido.' },
        { type: 'ul', items: [
          'Timeframe: 1–5 minutos; expiração: 3–5 candles.',
          'A faixa deve ser bem definida: pelo menos 10 candles entre dois níveis planos.',
          'Confirmação: candle de corpo cheio fechando fora da faixa com volume crescente (se o ativo mostrar volume).',
          'Nunca opere rompimentos durante notícias importantes — picos revertem em segundos.',
        ] },
        { type: 'h2', id: 'money', text: 'Gestão de risco: a parte que a maioria dos iniciantes pula' },
        { type: 'p', text: 'Uma taxa de acerto de 60% com gestão ruim ainda esvazia a conta. Use tamanho fracionário fixo: arrisque 1–2% do saldo por operação, sempre o mesmo valor. Com saldo de $100 são $1–$2 por operação — o que a Pocket Option permite, já que a operação mínima é $1.' },
        { type: 'table', head: ['Regra', 'Por quê'], rows: [
          ['Arriscar 1–2% por operação', 'Sobrevive a sequências de perdas; 10 perdas seguidas custam só 10–20%'],
          ['Parar após 3 perdas seguidas', 'Evita operar por vingança quando o mercado ou o foco não estão bons'],
          ['Limite de perda diária 5–6%', 'Limita um dia ruim; volte amanhã'],
          ['Nunca usar martingale (dobrar após perda)', 'Poucas perdas seguidas ultrapassam o saldo ou o tamanho máximo da operação'],
          ['Manter um diário de operações', 'Única forma de saber qual estratégia realmente funciona para você'],
        ] },
        { type: 'warn', title: 'Operar envolve risco', text: 'Nenhuma estratégia — incluindo as acima — garante lucro. Opções binárias podem resultar na perda de todo o valor da operação. Use apenas dinheiro que pode perder e trate cada estratégia como hipótese a testar primeiro na demo.' },
        { type: 'h2', id: 'demo', text: 'Como testar uma estratégia na Pocket Option' },
        { type: 'ol', items: [
          'Abra a conta demo gratuita (saldo virtual de $50.000).',
          'Escolha uma estratégia e um ativo (ex.: EUR/USD) — não misture.',
          'Faça pelo menos 50 operações seguindo as regras à risca, registrando cada resultado.',
          'Calcule a taxa de acerto. Você precisa de cerca de 56% com payout de 80%; busque 60%+ antes de ir para o real.',
          'Passe para a conta real com depósito pequeno ($10–$50) e o mesmo risco de 1–2%.',
        ] },
        { type: 'cta', text: 'Teste estas estratégias sem risco: a demo da Pocket Option tem os mesmos gráficos, indicadores e cotações da conta real.', label: 'Abrir demo grátis' },
      ],
      faq: [
        { q: 'Qual é a melhor estratégia para a Pocket Option?', a: 'Para iniciantes, um setup de tendência como EMA 9/21 ou cruzamento MACD em gráficos de 1–5 minutos, com risco rígido de 1–2% por operação. A “melhor” estratégia é a que você consegue seguir com consistência.' },
        { q: 'Qual timeframe devo usar?', a: 'Gráficos de 1 minuto dão mais sinais, porém mais ruído; 5 minutos são mais calmos e melhores para aprender. Sempre confira o gráfico de 15 minutos para a tendência geral.' },
        { q: 'Qual expiração é melhor?', a: 'Uma regra prática é 3–5 candles do timeframe do gráfico: 3–5 minutos em M1, 15–25 minutos em M5.' },
        { q: 'Existe estratégia 100% vencedora?', a: 'Não. Quem promete resultado garantido está enganando você. Estratégias realistas acertam 55–65% das operações em uma amostra grande.' },
        { q: 'Martingale funciona na Pocket Option?', a: 'Pode parecer lucrativo por pouco tempo, mas uma sequência longa de perdas zera a conta. Não recomendamos.' },
        { q: 'Posso usar essas estratégias em ativos OTC?', a: 'Sim, mas as cotações OTC são geradas pela plataforma e se comportam diferente do mercado real. Teste separadamente na demo antes de operar OTC com dinheiro real.' },
      ],
    },
    es: {
      title: 'Mejores estrategias Pocket Option para principiantes: 5 setups simples que tienen sentido',
      metaTitle: 'Estrategias Pocket Option – 5 Mejores Setups para Principiantes',
      metaDescription:
        'Cinco estrategias Pocket Option explicadas paso a paso: tendencia EMA, soporte/resistencia, reversión RSI, cruce MACD y ruptura, con marcos temporales, expiración y gestión.',
      excerpt:
        'Guía práctica de estrategias pocketoption: cinco setups para principiantes, qué marco temporal y expiración usar y las reglas de gestión del riesgo que te mantienen en el juego.',
      coverAlt: 'Ejemplo de cruce MACD alcista en un gráfico de Pocket Option',
      keyTakeaways: [
        'Ninguna estrategia gana todas las operaciones; una buena estrategia Pocket Option es un conjunto de reglas repetible con expectativa positiva en muchas operaciones.',
        'Los principiantes rinden mejor con setups de tendencia (EMA 9/21, cruce MACD) en gráficos de 1–5 minutos con expiración de 2–5 velas.',
        'Opera en la dirección de la tendencia del marco mayor, evita los primeros minutos tras noticias y elige activos con pago superior al 80%.',
        'Arriesga 1–2% del saldo por operación y para tras 3 pérdidas seguidas: la gestión del dinero importa más que el indicador.',
        'Prueba cada estrategia en la demo gratuita de $50.000 durante al menos 50 operaciones antes de usar dinero real.',
      ],
      blocks: [
        { type: 'p', text: 'Busca “estrategia Pocket Option” y encontrarás cientos de vídeos prometiendo un 95% de aciertos. La realidad: las opciones binarias son un juego de probabilidad, y los traders que duran son los que tienen reglas de entrada claras, expiraciones sensatas y límites de riesgo estrictos. A continuación, cinco estrategias que los principiantes sí pueden seguir en pocketoption — cada una con la configuración del indicador, el marco temporal y la expiración recomendados — más el marco de gestión del dinero que las une.' },
        { type: 'h2', id: 'basics', text: 'Antes de las estrategias: tres reglas que aplican a todas' },
        { type: 'ul', items: [
          'Opera con la tendencia del marco temporal mayor. Si el gráfico de 15 minutos sube, busca solo señales de Compra en el de 1 minuto.',
          'Elige activos con pago del 80%+ (junto al nombre del activo). Con un pago del 80% necesitas ganar cerca del 56% de las operaciones para no perder.',
          'Evita los primeros 5–10 minutos tras noticias económicas importantes y las horas muy tranquilas de la sesión asiática, cuando el precio se mueve al azar.',
        ] },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal de trading de Pocket Option con gráfico, panel de indicadores y botones de operación', caption: 'Los indicadores se añaden desde el botón “Indicadores” de la barra superior; la expiración y el importe se fijan a la derecha.' },
        { type: 'h2', id: 'ema', text: 'Estrategia 1: seguimiento de tendencia con EMA 9/21' },
        { type: 'p', text: 'Dos medias móviles exponenciales muestran la tendencia a corto plazo. Cuando la EMA rápida (9) está por encima de la lenta (21), la tendencia es alcista; compras en los retrocesos a la EMA 9. Cuando está por debajo, vendes en los rebotes hacia la EMA 9.' },
        { type: 'table', head: ['Ajuste', 'Valor'], rows: [
          ['Indicadores', 'EMA 9 y EMA 21'],
          ['Marco temporal', '1 minuto (o 5 minutos para entradas más tranquilas)'],
          ['Expiración', '3–5 velas (3–5 min en M1)'],
          ['Señal de compra', 'EMA 9 > EMA 21, el precio toca la EMA 9 y forma vela alcista'],
          ['Señal de venta', 'EMA 9 < EMA 21, el precio toca la EMA 9 y forma vela bajista'],
          ['No operar cuando', 'Las EMAs están planas y entrelazadas (sin tendencia)'],
        ] },
        { type: 'h2', id: 'sr', text: 'Estrategia 2: rebote en soporte y resistencia' },
        { type: 'p', text: 'El precio tiende a reaccionar en niveles donde ya giró antes. Marca los últimos 2–3 máximos y mínimos del gráfico de 5 minutos con líneas horizontales. Cuando el precio vuelve a un nivel y forma una vela de rechazo (pin bar o envolvente), entra en la dirección del rebote.' },
        { type: 'ol', items: [
          'Dibuja líneas horizontales en máximos y mínimos recientes claros (al menos dos toques).',
          'Espera a que el precio llegue al nivel; no te anticipes.',
          'Confirma con una vela de rechazo: mecha larga hacia el nivel, cierre de vuelta dentro.',
          'Entra con expiración de 3–5 velas. Descarta la operación si la vela cierra más allá del nivel (posible ruptura).',
        ] },
        { type: 'tip', title: 'Combínalo con RSI', text: 'Un rebote en soporte es más fuerte cuando el RSI está por debajo de 30, y en resistencia cuando el RSI supera 70. La doble confirmación filtra muchas señales falsas.' },
        { type: 'h2', id: 'rsi', text: 'Estrategia 3: reversión con RSI (sobrecompra / sobreventa)' },
        { type: 'p', text: 'El Índice de Fuerza Relativa mide el momentum. Lecturas por encima de 70 sugieren sobrecompra; por debajo de 30, sobreventa. Por sí solo el RSI da muchas señales falsas en tendencias fuertes, así que úsalo en mercados laterales o como filtro para las dos estrategias anteriores.' },
        { type: 'table', head: ['Ajuste', 'Valor'], rows: [
          ['Indicador', 'RSI, periodo 14 (o 7 para señales más rápidas)'],
          ['Marco temporal', '1–5 minutos'],
          ['Expiración', '2–3 velas'],
          ['Señal de compra', 'El RSI cae bajo 30 y luego vuelve a cruzar por encima de 30'],
          ['Señal de venta', 'El RSI sube sobre 70 y luego vuelve a cruzar por debajo de 70'],
          ['No operar cuando', 'Hay una tendencia fuerte en una dirección (RSI fijado sobre 70 / bajo 30)'],
        ] },
        { type: 'h2', id: 'macd', text: 'Estrategia 4: cruce MACD' },
        { type: 'image', src: IMG_MACD, alt: 'Línea MACD cruzando por encima de la línea de señal — ejemplo de cruce alcista', caption: 'Cruce MACD alcista: la línea MACD (azul) cruza por encima de la línea de señal (naranja) bajo la línea cero.' },
        { type: 'p', text: 'El MACD (12, 26, 9) combina tendencia y momentum. El cruce alcista ocurre cuando la línea MACD cruza por encima de la línea de señal; el bajista, cuando cruza por debajo. Las mejores señales se dan cuando el cruce coincide con la dirección de la tendencia de las EMAs y el histograma empieza a crecer.' },
        { type: 'ol', items: [
          'Añade el MACD con los ajustes por defecto 12 / 26 / 9 en el gráfico de 5 minutos.',
          'Espera a que la línea MACD cruce la de señal y a que la vela cierre.',
          'Revisa el marco mayor (15 min): opera solo cruces en esa dirección.',
          'Entra con expiración de 3–5 velas (15–25 minutos en M5).',
        ] },
        { type: 'h2', id: 'breakout', text: 'Estrategia 5: ruptura de consolidación con confirmación' },
        { type: 'p', text: 'Cuando el precio se mueve lateralmente en un rango estrecho durante 10–20 velas, acumula energía. La ruptura de ese rango suele continuar varias velas. La trampa es la ruptura falsa, así que entra solo cuando la vela de ruptura cierre fuera del rango y, idealmente, tras un pequeño retest del nivel roto.' },
        { type: 'ul', items: [
          'Marco temporal: 1–5 minutos; expiración: 3–5 velas.',
          'El rango debe estar bien definido: al menos 10 velas entre dos niveles planos.',
          'Confirmación: vela de cuerpo completo cerrando fuera del rango con volumen creciente (si el activo muestra volumen).',
          'Nunca operes rupturas durante noticias importantes: los picos revierten en segundos.',
        ] },
        { type: 'h2', id: 'money', text: 'Gestión del dinero: la parte que la mayoría se salta' },
        { type: 'p', text: 'Un 60% de aciertos con mala gestión del dinero también vacía la cuenta. Usa tamaño fraccional fijo: arriesga 1–2% del saldo por operación, siempre el mismo importe. Con un saldo de $100 son $1–$2 por operación, algo que Pocket Option permite, ya que la operación mínima es $1.' },
        { type: 'table', head: ['Regla', 'Por qué'], rows: [
          ['Arriesgar 1–2% por operación', 'Sobrevive a rachas perdedoras; 10 pérdidas seguidas cuestan solo 10–20%'],
          ['Parar tras 3 pérdidas seguidas', 'Evita operar por venganza cuando el mercado o tu concentración fallan'],
          ['Límite de pérdida diaria 5–6%', 'Acota un mal día; vuelve mañana'],
          ['Nunca usar martingala (doblar tras perder)', 'Unas pocas pérdidas seguidas superan tu saldo o el tamaño máximo de operación'],
          ['Llevar un diario de operaciones', 'La única forma de saber qué estrategia te funciona de verdad'],
        ] },
        { type: 'warn', title: 'Operar implica riesgo', text: 'Ninguna estrategia, incluidas las anteriores, garantiza beneficios. Las opciones binarias pueden suponer la pérdida de todo el importe de la operación. Usa solo dinero que puedas perder y trata cada estrategia como una hipótesis a probar primero en demo.' },
        { type: 'h2', id: 'demo', text: 'Cómo probar una estrategia en Pocket Option' },
        { type: 'ol', items: [
          'Abre la cuenta demo gratuita (saldo virtual de $50.000).',
          'Elige una estrategia y un activo (p. ej. EUR/USD); no mezcles.',
          'Haz al menos 50 operaciones siguiendo las reglas al pie de la letra y registra cada resultado.',
          'Calcula la tasa de aciertos. Necesitas cerca del 56% con pago del 80%; apunta a 60%+ antes de pasar a real.',
          'Pasa a la cuenta real con un depósito pequeño ($10–$50) y el mismo riesgo del 1–2%.',
        ] },
        { type: 'cta', text: 'Prueba estas estrategias sin riesgo: la demo de Pocket Option tiene los mismos gráficos, indicadores y cotizaciones que la cuenta real.', label: 'Abrir demo gratis' },
      ],
      faq: [
        { q: '¿Cuál es la mejor estrategia para Pocket Option?', a: 'Para principiantes, un setup de tendencia como EMA 9/21 o cruce MACD en gráficos de 1–5 minutos, con un riesgo estricto del 1–2% por operación. La “mejor” estrategia es la que puedes seguir con constancia.' },
        { q: '¿Qué marco temporal debo usar?', a: 'Los gráficos de 1 minuto dan más señales pero más ruido; los de 5 minutos son más tranquilos y mejores para aprender. Revisa siempre el gráfico de 15 minutos para la tendencia general.' },
        { q: '¿Qué expiración es mejor?', a: 'Una regla práctica es 3–5 velas del marco temporal de tu gráfico: 3–5 minutos en M1, 15–25 minutos en M5.' },
        { q: '¿Existe una estrategia 100% ganadora?', a: 'No. Quien promete resultados garantizados te engaña. Las estrategias realistas ganan el 55–65% de las operaciones en una muestra grande.' },
        { q: '¿Funciona la martingala en Pocket Option?', a: 'Puede parecer rentable un tiempo, pero una racha larga de pérdidas vacía la cuenta. No la recomendamos.' },
        { q: '¿Puedo usar estas estrategias en activos OTC?', a: 'Sí, pero las cotizaciones OTC las genera la plataforma y se comportan distinto al mercado real. Pruébalas aparte en demo antes de operar OTC con dinero real.' },
      ],
    },
    ru: {
      title: 'Лучшие стратегии Pocket Option для новичков: 5 простых сетапов, которые действительно работают',
      metaTitle: 'Стратегии Pocket Option – 5 Лучших Сетапов для Новичков',
      metaDescription:
        'Пять стратегий Pocket Option по шагам: тренд по EMA, поддержка/сопротивление, разворот по RSI, пересечение MACD и пробой — с таймфреймами, экспирацией и риск-менеджментом.',
      excerpt:
        'Практический гид по стратегиям pocketoption: пять сетапов для новичков, какой таймфрейм и экспирацию выбрать и правила управления капиталом, которые сохраняют депозит.',
      coverAlt: 'Пример бычьего пересечения MACD на графике Pocket Option',
      keyTakeaways: [
        'Ни одна стратегия не выигрывает каждую сделку; хорошая стратегия Pocket Option — это повторяемый набор правил с положительным матожиданием на большом числе сделок.',
        'Новичкам лучше всего подходят трендовые сетапы (EMA 9/21, пересечение MACD) на графиках 1–5 минут с экспирацией 2–5 свечей.',
        'Торгуйте по тренду старшего таймфрейма, избегайте первых минут после новостей и выбирайте активы с выплатой выше 80%.',
        'Рискуйте 1–2% баланса на сделку и останавливайтесь после 3 убытков подряд — управление капиталом важнее индикатора.',
        'Тестируйте каждую стратегию на бесплатном демо $50 000 минимум 50 сделок, прежде чем переходить на реальные деньги.',
      ],
      blocks: [
        { type: 'p', text: 'Введите в поиск «стратегия Pocket Option» — и найдёте сотни видео с обещаниями 95% прибыльных сделок. Реальность: бинарные опционы — игра вероятностей, и надолго остаются те трейдеры, у кого есть чёткие правила входа, разумная экспирация и строгие лимиты риска. Ниже — пять стратегий, которым новичок реально может следовать на pocketoption, с настройками индикаторов, таймфреймом и экспирацией, а также система управления капиталом, которая их объединяет.' },
        { type: 'h2', id: 'basics', text: 'Перед стратегиями: три правила для всех' },
        { type: 'ul', items: [
          'Торгуйте по тренду старшего таймфрейма. Если 15-минутный график растёт, ищите на 1-минутном только сигналы «Вверх».',
          'Выбирайте активы с выплатой 80%+ (указана рядом с названием актива). При выплате 80% для выхода в ноль нужно выигрывать около 56% сделок.',
          'Избегайте первых 5–10 минут после важных экономических новостей и очень тихих часов азиатской сессии, когда цена движется хаотично.',
        ] },
        { type: 'image', src: IMG_TERMINAL, alt: 'Торговый терминал Pocket Option с графиком, панелью индикаторов и кнопками сделки', caption: 'Индикаторы добавляются кнопкой «Индикаторы» на верхней панели; экспирация и сумма задаются справа.' },
        { type: 'h2', id: 'ema', text: 'Стратегия 1: следование тренду по EMA 9/21' },
        { type: 'p', text: 'Две экспоненциальные скользящие средние показывают краткосрочный тренд. Когда быстрая EMA (9) выше медленной EMA (21), тренд восходящий — покупайте на откатах к EMA 9. Когда ниже — продавайте на отскоках к EMA 9.' },
        { type: 'table', head: ['Параметр', 'Значение'], rows: [
          ['Индикаторы', 'EMA 9 и EMA 21'],
          ['Таймфрейм', '1 минута (или 5 минут для более спокойных входов)'],
          ['Экспирация', '3–5 свечей (3–5 мин на M1)'],
          ['Сигнал «Вверх»', 'EMA 9 > EMA 21, цена касается EMA 9 и формирует бычью свечу'],
          ['Сигнал «Вниз»', 'EMA 9 < EMA 21, цена касается EMA 9 и формирует медвежью свечу'],
          ['Пропускать, когда', 'EMA идут горизонтально и переплетаются (нет тренда)'],
        ] },
        { type: 'h2', id: 'sr', text: 'Стратегия 2: отскок от поддержки и сопротивления' },
        { type: 'p', text: 'Цена склонна реагировать на уровни, где уже разворачивалась. Отметьте последние 2–3 максимума и минимума на 5-минутном графике горизонтальными линиями. Когда цена возвращается к уровню и формирует свечу отказа (пин-бар или поглощение), входите в направлении отскока.' },
        { type: 'ol', items: [
          'Проведите горизонтальные линии по чётким недавним максимумам и минимумам (минимум два касания).',
          'Дождитесь, когда цена дойдёт до уровня, — не опережайте.',
          'Подтвердите свечой отказа: длинная тень к уровню, закрытие обратно внутри.',
          'Входите с экспирацией 3–5 свечей. Пропустите сделку, если свеча закрылась за уровнем (возможен пробой).',
        ] },
        { type: 'tip', title: 'Комбинируйте с RSI', text: 'Отскок от поддержки сильнее, когда RSI ниже 30, а от сопротивления — когда RSI выше 70. Двойное подтверждение отсеивает много ложных сигналов.' },
        { type: 'h2', id: 'rsi', text: 'Стратегия 3: разворот по RSI (перекупленность / перепроданность)' },
        { type: 'p', text: 'Индекс относительной силы измеряет импульс. Значения выше 70 указывают на перекупленность, ниже 30 — на перепроданность. Сам по себе RSI даёт много ложных сигналов в сильном тренде, поэтому используйте его во флэте или как фильтр для двух стратегий выше.' },
        { type: 'table', head: ['Параметр', 'Значение'], rows: [
          ['Индикатор', 'RSI, период 14 (или 7 для более быстрых сигналов)'],
          ['Таймфрейм', '1–5 минут'],
          ['Экспирация', '2–3 свечи'],
          ['Сигнал «Вверх»', 'RSI опускается ниже 30, затем пересекает 30 снизу вверх'],
          ['Сигнал «Вниз»', 'RSI поднимается выше 70, затем пересекает 70 сверху вниз'],
          ['Пропускать, когда', 'Идёт сильный однонаправленный тренд (RSI «прилип» выше 70 / ниже 30)'],
        ] },
        { type: 'h2', id: 'macd', text: 'Стратегия 4: пересечение MACD' },
        { type: 'image', src: IMG_MACD, alt: 'Линия MACD пересекает сигнальную линию снизу вверх — пример бычьего пересечения', caption: 'Бычье пересечение MACD: линия MACD (синяя) пересекает сигнальную (оранжевую) снизу вверх ниже нулевой линии.' },
        { type: 'p', text: 'MACD (12, 26, 9) объединяет тренд и импульс. Бычье пересечение — когда линия MACD пересекает сигнальную снизу вверх; медвежье — сверху вниз. Лучшие сигналы возникают, когда пересечение совпадает с направлением тренда по EMA, а гистограмма начинает расти.' },
        { type: 'ol', items: [
          'Добавьте MACD со стандартными настройками 12 / 26 / 9 на 5-минутный график.',
          'Дождитесь пересечения линии MACD с сигнальной и закрытия свечи.',
          'Проверьте старший таймфрейм (15 мин): торгуйте только пересечения в его направлении.',
          'Входите с экспирацией 3–5 свечей (15–25 минут на M5).',
        ] },
        { type: 'h2', id: 'breakout', text: 'Стратегия 5: пробой консолидации с подтверждением' },
        { type: 'p', text: 'Когда цена 10–20 свечей движется в узком боковике, она накапливает энергию. Пробой такого диапазона часто продолжается несколько свечей. Ловушка — ложный пробой, поэтому входите только после закрытия пробойной свечи за пределами диапазона и, в идеале, после небольшого ретеста пробитого уровня.' },
        { type: 'ul', items: [
          'Таймфрейм: 1–5 минут; экспирация: 3–5 свечей.',
          'Диапазон должен быть чётким: минимум 10 свечей между двумя горизонтальными уровнями.',
          'Подтверждение: полнотелая свеча закрывается за диапазоном при растущем объёме (если по активу есть объём).',
          'Никогда не торгуйте пробои во время важных новостей — шпильки разворачиваются за секунды.',
        ] },
        { type: 'h2', id: 'money', text: 'Управление капиталом: то, что большинство новичков пропускает' },
        { type: 'p', text: 'Даже 60% прибыльных сделок при плохом управлении капиталом обнуляют счёт. Используйте фиксированную долю: рискуйте 1–2% баланса на сделку, всегда одной и той же суммой. При балансе $100 это $1–$2 на сделку — Pocket Option это позволяет, так как минимальная сделка $1.' },
        { type: 'table', head: ['Правило', 'Почему'], rows: [
          ['Риск 1–2% на сделку', 'Переживёте серию убытков; 10 убытков подряд стоят лишь 10–20%'],
          ['Стоп после 3 убытков подряд', 'Защищает от «отыгрыша», когда рынок или ваша концентрация не в форме'],
          ['Дневной лимит убытка 5–6%', 'Ограничивает плохой день; вернитесь завтра'],
          ['Никогда не использовать мартингейл (удвоение после убытка)', 'Несколько убытков подряд превышают баланс или максимальный размер сделки'],
          ['Ведите журнал сделок', 'Единственный способ понять, какая стратегия реально работает у вас'],
        ] },
        { type: 'warn', title: 'Торговля связана с риском', text: 'Ни одна стратегия — включая описанные выше — не гарантирует прибыль. Бинарные опционы могут привести к потере всей суммы сделки. Используйте только те деньги, которые готовы потерять, и относитесь к каждой стратегии как к гипотезе, которую нужно сначала проверить на демо.' },
        { type: 'h2', id: 'demo', text: 'Как тестировать стратегию на Pocket Option' },
        { type: 'ol', items: [
          'Откройте бесплатный демо-счёт (виртуальный баланс $50 000).',
          'Выберите одну стратегию и один актив (например, EUR/USD) — не смешивайте.',
          'Сделайте минимум 50 сделок строго по правилам, записывая каждый результат.',
          'Посчитайте процент прибыльных сделок. При выплате 80% нужно около 56%; стремитесь к 60%+ перед выходом на реал.',
          'Переходите на реальный счёт с небольшим депозитом ($10–$50) и тем же риском 1–2%.',
        ] },
        { type: 'cta', text: 'Проверьте эти стратегии без риска: на демо Pocket Option те же графики, индикаторы и котировки, что и на реальном счёте.', label: 'Открыть бесплатное демо' },
      ],
      faq: [
        { q: 'Какая стратегия лучше всего подходит для Pocket Option?', a: 'Новичкам — трендовый сетап вроде EMA 9/21 или пересечения MACD на графиках 1–5 минут в сочетании со строгим риском 1–2% на сделку. «Лучшая» стратегия — та, которой вы можете следовать последовательно.' },
        { q: 'Какой таймфрейм использовать?', a: '1-минутные графики дают больше сигналов, но и больше шума; 5-минутные спокойнее и лучше для обучения. Всегда проверяйте общий тренд на 15-минутном графике.' },
        { q: 'Какая экспирация лучше?', a: 'Практическое правило — 3–5 свечей вашего таймфрейма: 3–5 минут на M1, 15–25 минут на M5.' },
        { q: 'Существует ли стратегия со 100% выигрышем?', a: 'Нет. Тот, кто обещает гарантированный результат, вводит вас в заблуждение. Реалистичные стратегии выигрывают 55–65% сделок на большой выборке.' },
        { q: 'Работает ли мартингейл на Pocket Option?', a: 'Он может недолго выглядеть прибыльным, но одна длинная серия убытков обнуляет счёт. Мы его не рекомендуем.' },
        { q: 'Можно ли применять эти стратегии на OTC-активах?', a: 'Да, но котировки OTC генерируются платформой и ведут себя иначе, чем живой рынок. Отдельно протестируйте на демо, прежде чем торговать OTC на реальные деньги.' },
      ],
    },
    id: {
      title: 'Strategi Pocket Option terbaik untuk pemula: 5 setup sederhana yang benar-benar masuk akal',
      metaTitle: 'Strategi Pocket Option – 5 Setup Terbaik untuk Pemula',
      metaDescription:
        'Lima strategi Pocket Option dijelaskan langkah demi langkah: tren EMA, support/resistance, reversal RSI, crossover MACD, dan breakout — dengan timeframe, ekspirasi, dan manajemen modal.',
      excerpt:
        'Panduan praktis strategi pocketoption: lima setup ramah pemula, timeframe dan ekspirasi yang dipakai, serta aturan manajemen modal yang membuat Anda tetap bertahan.',
      coverAlt: 'Contoh crossover MACD bullish pada grafik Pocket Option',
      keyTakeaways: [
        'Tidak ada strategi yang menang di setiap trade; strategi Pocket Option yang baik adalah aturan yang dapat diulang dengan ekspektasi positif dalam banyak trade.',
        'Pemula paling cocok dengan setup mengikuti tren (EMA 9/21, crossover MACD) pada grafik 1–5 menit dengan ekspirasi 2–5 candle.',
        'Trading searah tren timeframe lebih tinggi, hindari menit-menit pertama setelah berita, dan pilih aset dengan payout di atas 80%.',
        'Risikokan 1–2% saldo per trade dan berhenti setelah 3 kali rugi berturut — manajemen modal lebih penting daripada indikator.',
        'Uji setiap strategi di demo gratis $50.000 minimal 50 trade sebelum memakai uang nyata.',
      ],
      blocks: [
        { type: 'p', text: 'Cari “strategi Pocket Option” dan Anda akan menemukan ratusan video yang menjanjikan win rate 95%. Kenyataannya: opsi biner adalah permainan probabilitas, dan trader yang bertahan adalah yang punya aturan entry jelas, waktu ekspirasi masuk akal, dan batas risiko ketat. Berikut lima strategi yang benar-benar bisa diikuti pemula di pocketoption — masing-masing dengan pengaturan indikator, timeframe, dan ekspirasi yang kami rekomendasikan — plus kerangka manajemen modal yang mengikat semuanya.' },
        { type: 'h2', id: 'basics', text: 'Sebelum strategi: tiga aturan yang berlaku untuk semuanya' },
        { type: 'ul', items: [
          'Trading searah tren timeframe lebih tinggi. Jika grafik 15 menit naik, cari sinyal Beli saja di grafik 1 menit.',
          'Pilih aset dengan payout 80%+ (ditampilkan di samping nama aset). Pada payout 80% Anda perlu menang sekitar 56% trade untuk impas.',
          'Hindari 5–10 menit pertama setelah berita ekonomi besar dan jam-jam sesi Asia yang sangat sepi, saat harga bergerak acak.',
        ] },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal trading Pocket Option dengan grafik, panel indikator, dan tombol trade', caption: 'Indikator ditambahkan dari tombol “Indikator” di toolbar atas; ekspirasi dan jumlah diatur di kanan.' },
        { type: 'h2', id: 'ema', text: 'Strategi 1: mengikuti tren dengan EMA 9/21' },
        { type: 'p', text: 'Dua exponential moving average menunjukkan tren jangka pendek. Saat EMA cepat (9) di atas EMA lambat (21), tren naik; Anda beli saat harga pullback ke EMA 9. Saat di bawah, Anda jual saat harga rally kembali ke EMA 9.' },
        { type: 'table', head: ['Pengaturan', 'Nilai'], rows: [
          ['Indikator', 'EMA 9 dan EMA 21'],
          ['Timeframe', '1 menit (atau 5 menit untuk entry lebih tenang)'],
          ['Ekspirasi', '3–5 candle (3–5 menit di M1)'],
          ['Sinyal beli', 'EMA 9 > EMA 21, harga menyentuh EMA 9 dan membentuk candle bullish'],
          ['Sinyal jual', 'EMA 9 < EMA 21, harga menyentuh EMA 9 dan membentuk candle bearish'],
          ['Lewati saat', 'EMA datar dan saling silang (tanpa tren)'],
        ] },
        { type: 'h2', id: 'sr', text: 'Strategi 2: pantulan support dan resistance' },
        { type: 'p', text: 'Harga cenderung bereaksi di level tempat ia berbalik sebelumnya. Tandai 2–3 swing high dan low terakhir di grafik 5 menit dengan garis horizontal. Saat harga kembali ke level dan membentuk candle penolakan (pin bar atau engulfing), masuk searah pantulan.' },
        { type: 'ol', items: [
          'Gambar garis horizontal di high dan low terbaru yang jelas (minimal dua sentuhan).',
          'Tunggu harga mencapai level — jangan mendahului.',
          'Konfirmasi dengan candle penolakan: sumbu panjang ke level, ditutup kembali di dalam.',
          'Masuk dengan ekspirasi 3–5 candle. Lewati jika candle ditutup melewati level (kemungkinan breakout).',
        ] },
        { type: 'tip', title: 'Gabungkan dengan RSI', text: 'Pantulan dari support lebih kuat saat RSI di bawah 30, dan pantulan dari resistance saat RSI di atas 70. Konfirmasi dua faktor menyaring banyak sinyal palsu.' },
        { type: 'h2', id: 'rsi', text: 'Strategi 3: reversal RSI (overbought / oversold)' },
        { type: 'p', text: 'Relative Strength Index mengukur momentum. Nilai di atas 70 menandakan aset overbought, di bawah 30 oversold. Sendirian, RSI memberi banyak sinyal palsu dalam tren kuat, jadi gunakan di pasar sideways atau sebagai filter untuk dua strategi di atas.' },
        { type: 'table', head: ['Pengaturan', 'Nilai'], rows: [
          ['Indikator', 'RSI, periode 14 (atau 7 untuk sinyal lebih cepat)'],
          ['Timeframe', '1–5 menit'],
          ['Ekspirasi', '2–3 candle'],
          ['Sinyal beli', 'RSI turun di bawah 30 lalu kembali naik melewati 30'],
          ['Sinyal jual', 'RSI naik di atas 70 lalu kembali turun melewati 70'],
          ['Lewati saat', 'Tren kuat satu arah sedang berlangsung (RSI tertahan di atas 70 / di bawah 30)'],
        ] },
        { type: 'h2', id: 'macd', text: 'Strategi 4: crossover MACD' },
        { type: 'image', src: IMG_MACD, alt: 'Garis MACD memotong ke atas garis sinyal — contoh crossover bullish', caption: 'Crossover MACD bullish: garis MACD (biru) memotong ke atas garis sinyal (oranye) di bawah garis nol.' },
        { type: 'p', text: 'MACD (12, 26, 9) menggabungkan tren dan momentum. Crossover bullish terjadi saat garis MACD memotong ke atas garis sinyal; crossover bearish saat memotong ke bawah. Sinyal terbaik muncul saat crossover searah dengan tren EMA dan histogram mulai membesar.' },
        { type: 'ol', items: [
          'Tambahkan MACD dengan pengaturan default 12 / 26 / 9 di grafik 5 menit.',
          'Tunggu garis MACD memotong garis sinyal dan candle ditutup.',
          'Cek timeframe lebih tinggi (15 menit): trading hanya crossover searah tren itu.',
          'Masuk dengan ekspirasi 3–5 candle (15–25 menit di M5).',
        ] },
        { type: 'h2', id: 'breakout', text: 'Strategi 5: breakout konsolidasi dengan konfirmasi' },
        { type: 'p', text: 'Saat harga bergerak sideways dalam rentang sempit selama 10–20 candle, ia menyimpan energi. Breakout dari rentang itu sering berlanjut beberapa candle. Jebakannya adalah breakout palsu — jadi masuk hanya setelah candle breakout ditutup di luar rentang dan, idealnya, setelah retest kecil pada level yang ditembus.' },
        { type: 'ul', items: [
          'Timeframe: 1–5 menit; ekspirasi: 3–5 candle.',
          'Rentang harus jelas: minimal 10 candle di antara dua level datar.',
          'Konfirmasi: candle berbadan penuh ditutup di luar rentang dengan volume meningkat (jika aset menampilkan volume).',
          'Jangan pernah trading breakout saat berita besar — lonjakan berbalik dalam hitungan detik.',
        ] },
        { type: 'h2', id: 'money', text: 'Manajemen modal: bagian yang paling sering dilewati pemula' },
        { type: 'p', text: 'Win rate 60% dengan manajemen modal buruk tetap mengosongkan akun. Gunakan ukuran fraksional tetap: risikokan 1–2% saldo per trade, selalu dengan jumlah yang sama. Dengan saldo $100 itu berarti $1–$2 per trade — yang dimungkinkan Pocket Option karena trade minimum $1.' },
        { type: 'table', head: ['Aturan', 'Alasan'], rows: [
          ['Risiko 1–2% per trade', 'Bertahan dari rentetan rugi; 10 kali rugi berturut hanya kehilangan 10–20%'],
          ['Berhenti setelah 3 kali rugi berturut', 'Mencegah revenge trading saat pasar atau fokus Anda tidak kondusif'],
          ['Batas rugi harian 5–6%', 'Membatasi hari buruk; kembali lagi besok'],
          ['Jangan pernah martingale (menggandakan setelah rugi)', 'Beberapa kali rugi berturut melampaui saldo atau ukuran trade maksimum'],
          ['Buat jurnal trading', 'Satu-satunya cara mengetahui strategi mana yang benar-benar berhasil untuk Anda'],
        ] },
        { type: 'warn', title: 'Trading mengandung risiko', text: 'Tidak ada strategi — termasuk yang di atas — yang menjamin profit. Opsi biner dapat menyebabkan kehilangan seluruh jumlah trade. Gunakan hanya uang yang siap hilang dan anggap setiap strategi sebagai hipotesis yang diuji dulu di demo.' },
        { type: 'h2', id: 'demo', text: 'Cara menguji strategi di Pocket Option' },
        { type: 'ol', items: [
          'Buka akun demo gratis (saldo virtual $50.000).',
          'Pilih satu strategi dan satu aset (misalnya EUR/USD) — jangan dicampur.',
          'Lakukan minimal 50 trade dengan mengikuti aturan secara persis, catat setiap hasil.',
          'Hitung win rate. Anda butuh sekitar 56% pada payout 80%; targetkan 60%+ sebelum ke akun riil.',
          'Pindah ke akun riil dengan deposit kecil ($10–$50) dan risiko 1–2% yang sama.',
        ] },
        { type: 'cta', text: 'Uji strategi ini tanpa risiko: demo Pocket Option memiliki grafik, indikator, dan kuotasi yang sama dengan akun riil.', label: 'Buka demo gratis' },
      ],
      faq: [
        { q: 'Apa strategi terbaik untuk Pocket Option?', a: 'Untuk pemula, setup mengikuti tren seperti EMA 9/21 atau crossover MACD di grafik 1–5 menit, dipadukan dengan risiko ketat 1–2% per trade. Strategi “terbaik” adalah yang bisa Anda ikuti secara konsisten.' },
        { q: 'Timeframe mana yang harus dipakai?', a: 'Grafik 1 menit memberi lebih banyak sinyal tetapi lebih banyak noise; grafik 5 menit lebih tenang dan lebih baik untuk belajar. Selalu cek grafik 15 menit untuk tren keseluruhan.' },
        { q: 'Waktu ekspirasi mana yang terbaik?', a: 'Patokan umum adalah 3–5 candle dari timeframe grafik Anda: 3–5 menit di M1, 15–25 menit di M5.' },
        { q: 'Apakah ada strategi 100% menang?', a: 'Tidak. Siapa pun yang menjanjikan hasil pasti sedang menyesatkan Anda. Strategi realistis menang 55–65% trade dalam sampel besar.' },
        { q: 'Apakah martingale berhasil di Pocket Option?', a: 'Bisa tampak menguntungkan sesaat, tetapi satu rentetan rugi panjang menghabiskan akun. Kami tidak merekomendasikannya.' },
        { q: 'Bisakah strategi ini dipakai di aset OTC?', a: 'Bisa, tetapi kuotasi OTC dibuat oleh platform dan berperilaku berbeda dari pasar riil. Uji terpisah di demo sebelum trading OTC dengan uang nyata.' },
      ],
    },
  },
};
