import type { BlogPost } from '../types';

const IMG_CONDITIONS = '/images/blog/po-trading-conditions.webp';
const IMG_TERMINAL = '/images/blog/po-trading-interface.webp';

export const pocketOptionFees: BlogPost = {
  slug: 'pocket-option-fees',
  category: 'platform',
  cover: '/images/blog/pocket-option-fees.webp',
  publishedAt: '2026-09-27',
  updatedAt: '2026-09-27',
  readingMinutes: 6,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option Fees',
      metaTitle: 'Pocket Option Fees: Deposits, Withdrawals, Spreads and Hidden Costs',
      metaDescription:
        'Complete breakdown of Pocket Option fees in 2026: $0 deposit and withdrawal fees, no commissions on trades, how the broker earns via payout percentage, and the real costs to watch.',
      excerpt:
        'Pocket Option advertises zero fees — mostly true. Here is what you actually pay: payout spread, network and bank charges, bonus turnover and the inactivity rule.',
      coverAlt: 'Pocket Option payment method logos: Visa, Mastercard, Pix, UPI, M-Pesa and more',
      keyTakeaways: [
        'Pocket Option charges $0 for deposits and withdrawals and no commission per trade.',
        'The broker earns from the payout gap: a losing trade costs 100%, a winning one pays 50–92% — that is the real “fee”.',
        'External costs can apply: crypto network fees, card currency conversion, e-wallet charges.',
        'Bonuses carry a turnover requirement; the inactivity fee kicks in only after long periods without trades.',
      ],
      blocks: [
        { type: 'p', text: 'One of the reasons Pocket Option is popular is its simple pricing: no deposit fee, no withdrawal fee, no per-trade commission, no swap. But “no fees” does not mean “no cost”. This guide explains exactly how pocketoption makes money, which third-party charges you can still run into and which rules in the terms can quietly reduce your balance.' },
        { type: 'h2', id: 'overview', text: 'Pocket Option fee schedule at a glance' },
        { type: 'image', src: IMG_CONDITIONS, alt: 'Pocket Option conditions showing $0 commission on deposit and withdrawal', caption: '“$0 — no commission on deposit and withdrawal” on the official homepage.' },
        { type: 'table', head: ['Item', 'Pocket Option fee', 'Notes'], rows: [
          ['Deposit', '$0', 'Payment provider / network may charge'],
          ['Withdrawal', '$0', 'Minimum $10; provider fee possible'],
          ['Commission per trade', '$0', 'Cost is built into the payout %'],
          ['Spread', 'None on quick trading', 'Built-in spread on Forex/MT5 accounts'],
          ['Overnight swap', 'None', 'Trades expire, no positions held overnight'],
          ['Account currency conversion', '$0 by platform', 'Bank/card issuer may convert at its rate'],
          ['Inactivity', 'Possible after long inactivity', 'See terms; trade or log in periodically'],
        ] },
        { type: 'h2', id: 'how-they-earn', text: 'How Pocket Option actually earns money' },
        { type: 'p', text: 'On quick and binary trades you never see a commission line because the cost is in the payout percentage. A trade with a 92% payout means: win and you get $1.92 back on $1 — lose and you lose the full $1. Statistically, the gap between 100% and the payout is the broker’s margin. On a 70% payout asset that margin is much bigger than on a 92% one, which is why choosing high-payout assets is the single most effective way to reduce your trading cost.' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Pocket Option terminal with payout percentage displayed next to the asset', caption: 'The payout percentage next to the asset name is the only trading cost on quick trades.' },
        { type: 'tip', title: 'Rule of thumb', text: 'Stick to assets paying 80% or more. At 92% you need a 52% win rate to break even; at 70% you need 59%.' },
        { type: 'h2', id: 'deposit-fees', text: 'Deposit fees: platform vs. payment provider' },
        { type: 'p', text: 'Pocket Option credits the full deposit amount. Any deduction comes from outside the platform:' },
        { type: 'ul', items: [
          'Crypto — blockchain network fee paid by you when sending (USDT TRC-20 ≈ $1, ERC-20 can be $5+). The platform does not deduct anything on arrival.',
          'Cards — your bank may apply a foreign-transaction or currency-conversion fee (typically 1–3%) if the card currency differs from USD.',
          'E-wallets — Skrill, Neteller and others may charge their own sending fee.',
          'Local methods — Pix, UPI and most mobile money transfers are usually free for the sender.',
        ] },
        { type: 'h2', id: 'withdrawal-fees', text: 'Withdrawal fees' },
        { type: 'p', text: 'Withdrawals are free on the platform side, from a $10 minimum, and processed on average within 24 hours. The same external costs apply as for deposits: the crypto network fee is deducted from the sent amount, and a bank may charge for receiving an international card refund. Withdrawing to the method you deposited with, in the same currency, avoids most of these charges.' },
        { type: 'warn', title: 'Frequent small withdrawals', text: 'There is no fee for many withdrawals, but each crypto payout carries a network fee. Withdrawing $10 ten times to an ERC-20 wallet can cost more than one $100 withdrawal. Batch when you can.' },
        { type: 'h2', id: 'hidden', text: 'Costs that are not called fees' },
        { type: 'ol', items: [
          'Bonus turnover — accepting a deposit bonus locks the balance until you trade the required volume (often bonus × 50 or more). Withdrawing early may cancel the bonus and related profit.',
          'Inactivity rule — after a long period with no trades the terms allow a maintenance charge on dormant balances. Logging in and placing a demo trade does not count; a real trade does. Withdraw funds you are not using.',
          'Currency conversion — an account in USD funded from a BRL/INR/IDR card pays the bank’s rate twice (in and out). Choosing a local account currency avoids this where offered.',
          'Chargeback rule — disputing a card deposit with your bank leads to account closure and a penalty under the terms.',
        ] },
        { type: 'h2', id: 'compare', text: 'How Pocket Option fees compare' },
        { type: 'table', head: ['Broker', 'Deposit / withdrawal fee', 'Min deposit', 'Max payout'], rows: [
          ['Pocket Option', '$0 / $0', '$5', 'up to 92%'],
          ['Quotex', '$0 / $0', '$10', 'up to 95%'],
          ['IQ Option', '$0 / $0 (bank wire fee)', '$10', 'up to 95%'],
          ['Olymp Trade', '$0 / $0', '$10', 'up to 93%'],
        ] },
        { type: 'p', text: 'Values are as of writing and change frequently — check the platforms directly. In practice, the fee structure of all major binary brokers is similar; payout percentage and execution quality matter more than headline “zero fees”.' },
        { type: 'cta', text: 'Trade with $0 deposit and withdrawal fees — open a Pocket Option account from $5.', label: 'Open Pocket Option account' },
      ],
      faq: [
        { q: 'Does Pocket Option charge deposit fees?', a: 'No. The platform credits 100% of the deposit. Only your bank, e-wallet or the crypto network may charge.' },
        { q: 'Does Pocket Option charge withdrawal fees?', a: 'No platform fee. Minimum withdrawal is $10; crypto network fees and bank charges may apply externally.' },
        { q: 'Is there a commission per trade on Pocket Option?', a: 'No. The cost is built into the payout percentage — the difference between 100% and the payout you receive on a win.' },
        { q: 'Does Pocket Option have an inactivity fee?', a: 'The terms allow a charge on accounts with no trading activity for an extended period. Place a real trade occasionally or withdraw idle funds.' },
        { q: 'Is Pocket Option cheaper than Quotex or IQ Option?', a: 'All three have $0 deposit and withdrawal fees. Pocket Option has the lowest minimum deposit ($5); maximum payouts are comparable.' },
        { q: 'Why did I receive less than I deposited?', a: 'Usually a crypto network fee or your card issuer’s currency conversion. Pocket Option itself does not deduct from deposits.' },
      ],
    },
    pt: {
      title: 'Taxas da Pocket Option',
      metaTitle: 'Taxas da Pocket Option: depósito, saque, spread e custos ocultos',
      metaDescription:
        'Detalhamento completo das taxas da Pocket Option em 2026: $0 em depósito e saque, sem comissão por operação, como a corretora ganha pelo payout e os custos reais a observar.',
      excerpt:
        'A Pocket Option anuncia taxa zero — em grande parte verdade. Veja o que você realmente paga: diferença de payout, taxas de rede e banco, giro de bônus e regra de inatividade.',
      coverAlt: 'Logos de métodos de pagamento da Pocket Option: Visa, Mastercard, Pix, UPI, M-Pesa e outros',
      keyTakeaways: [
        'A Pocket Option cobra $0 em depósitos e saques e nenhuma comissão por operação.',
        'A corretora ganha na diferença do payout: perda custa 100%, ganho paga 50–92% — essa é a “taxa” real.',
        'Custos externos podem existir: taxa de rede cripto, conversão de moeda do cartão, tarifas de e-wallet.',
        'Bônus têm exigência de giro; a taxa de inatividade só aparece após longos períodos sem operar.',
      ],
      blocks: [
        { type: 'p', text: 'Um dos motivos da popularidade da Pocket Option é o preço simples: sem taxa de depósito, sem taxa de saque, sem comissão por operação, sem swap. Mas “sem taxas” não significa “sem custo”. Este guia explica exatamente como a pocketoption ganha dinheiro, quais cobranças de terceiros você ainda pode encontrar e quais regras dos termos podem reduzir seu saldo discretamente.' },
        { type: 'h2', id: 'overview', text: 'Tabela de taxas da Pocket Option em resumo' },
        { type: 'image', src: IMG_CONDITIONS, alt: 'Condições da Pocket Option mostrando $0 de comissão em depósito e saque', caption: '“$0 — sem comissão em depósito e saque” na página inicial oficial.' },
        { type: 'table', head: ['Item', 'Taxa Pocket Option', 'Observações'], rows: [
          ['Depósito', '$0', 'Provedor de pagamento / rede pode cobrar'],
          ['Saque', '$0', 'Mínimo $10; taxa do provedor possível'],
          ['Comissão por operação', '$0', 'Custo embutido no % de payout'],
          ['Spread', 'Nenhum no quick trading', 'Spread embutido em contas Forex/MT5'],
          ['Swap overnight', 'Nenhum', 'Operações expiram, nada fica aberto'],
          ['Conversão de moeda', '$0 pela plataforma', 'Banco/emissor pode converter à sua taxa'],
          ['Inatividade', 'Possível após longa inatividade', 'Ver termos; opere ou entre periodicamente'],
        ] },
        { type: 'h2', id: 'how-they-earn', text: 'Como a Pocket Option realmente ganha dinheiro' },
        { type: 'p', text: 'Em operações rápidas e binárias você nunca vê linha de comissão porque o custo está no percentual de payout. Uma operação com payout de 92% significa: ganhando, você recebe $1,92 por $1 — perdendo, perde o $1 inteiro. Estatisticamente, a diferença entre 100% e o payout é a margem da corretora. Num ativo com payout de 70% essa margem é bem maior que num de 92%, por isso escolher ativos de payout alto é a forma mais eficaz de reduzir seu custo.' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal da Pocket Option com percentual de payout ao lado do ativo', caption: 'O percentual de payout ao lado do ativo é o único custo nas operações rápidas.' },
        { type: 'tip', title: 'Regra prática', text: 'Fique em ativos que pagam 80% ou mais. Com 92% você precisa de 52% de acerto para empatar; com 70%, de 59%.' },
        { type: 'h2', id: 'deposit-fees', text: 'Taxas de depósito: plataforma vs. provedor' },
        { type: 'p', text: 'A Pocket Option credita o valor integral do depósito. Qualquer desconto vem de fora da plataforma:' },
        { type: 'ul', items: [
          'Cripto — taxa de rede paga por você ao enviar (USDT TRC-20 ≈ $1, ERC-20 pode passar de $5). A plataforma não desconta nada na chegada.',
          'Cartões — seu banco pode aplicar taxa de transação internacional ou conversão (1–3%) se a moeda do cartão for diferente de USD.',
          'E-wallets — Skrill, Neteller e outros podem cobrar taxa de envio própria.',
          'Métodos locais — Pix e a maioria das transferências móveis costumam ser gratuitos para quem envia.',
        ] },
        { type: 'h2', id: 'withdrawal-fees', text: 'Taxas de saque' },
        { type: 'p', text: 'Saques são gratuitos do lado da plataforma, a partir de $10, processados em média em até 24 horas. Valem os mesmos custos externos dos depósitos: a taxa de rede cripto é descontada do valor enviado e um banco pode cobrar por receber reembolso internacional em cartão. Sacar pelo mesmo método do depósito, na mesma moeda, evita a maioria dessas cobranças.' },
        { type: 'warn', title: 'Saques pequenos frequentes', text: 'Não há taxa por muitos saques, mas cada pagamento em cripto tem taxa de rede. Sacar $10 dez vezes para uma carteira ERC-20 pode custar mais que um saque de $100. Agrupe quando possível.' },
        { type: 'h2', id: 'hidden', text: 'Custos que não se chamam taxas' },
        { type: 'ol', items: [
          'Giro de bônus — aceitar bônus de depósito trava o saldo até você operar o volume exigido (muitas vezes bônus × 50 ou mais). Sacar antes pode cancelar o bônus e o lucro relacionado.',
          'Regra de inatividade — após longo período sem operações, os termos permitem cobrança de manutenção em saldos parados. Entrar e operar na demo não conta; operação real conta. Saque fundos que não usa.',
          'Conversão de moeda — conta em USD alimentada por cartão em BRL paga a taxa do banco duas vezes (entrada e saída). Escolher moeda local da conta evita isso, onde disponível.',
          'Regra de chargeback — contestar um depósito de cartão no banco leva ao encerramento da conta e penalidade prevista nos termos.',
        ] },
        { type: 'h2', id: 'compare', text: 'Comparação das taxas da Pocket Option' },
        { type: 'table', head: ['Corretora', 'Taxa depósito / saque', 'Depósito mín.', 'Payout máx.'], rows: [
          ['Pocket Option', '$0 / $0', '$5', 'até 92%'],
          ['Quotex', '$0 / $0', '$10', 'até 95%'],
          ['IQ Option', '$0 / $0 (taxa em wire)', '$10', 'até 95%'],
          ['Olymp Trade', '$0 / $0', '$10', 'até 93%'],
        ] },
        { type: 'p', text: 'Valores na data da redação, mudam com frequência — confira diretamente nas plataformas. Na prática, a estrutura de taxas das grandes corretoras binárias é parecida; payout e qualidade de execução importam mais que o slogan “taxa zero”.' },
        { type: 'cta', text: 'Opere com $0 de taxa em depósito e saque — abra uma conta Pocket Option a partir de $5.', label: 'Abrir conta Pocket Option' },
      ],
      faq: [
        { q: 'A Pocket Option cobra taxa de depósito?', a: 'Não. A plataforma credita 100% do depósito. Só seu banco, e-wallet ou a rede cripto podem cobrar.' },
        { q: 'A Pocket Option cobra taxa de saque?', a: 'Sem taxa da plataforma. Saque mínimo $10; taxas de rede cripto e bancárias podem existir externamente.' },
        { q: 'Há comissão por operação na Pocket Option?', a: 'Não. O custo está embutido no percentual de payout — a diferença entre 100% e o payout recebido no ganho.' },
        { q: 'A Pocket Option tem taxa de inatividade?', a: 'Os termos permitem cobrança em contas sem atividade de negociação por período prolongado. Faça uma operação real ocasionalmente ou saque fundos parados.' },
        { q: 'A Pocket Option é mais barata que Quotex ou IQ Option?', a: 'As três têm $0 em depósito e saque. A Pocket Option tem o menor depósito mínimo ($5); payouts máximos são comparáveis.' },
        { q: 'Por que recebi menos do que depositei?', a: 'Geralmente taxa de rede cripto ou conversão de moeda do emissor do cartão. A Pocket Option não desconta dos depósitos.' },
      ],
    },
    es: {
      title: 'Comisiones de Pocket Option',
      metaTitle: 'Comisiones de Pocket Option: depósitos, retiros, spread y costes ocultos',
      metaDescription:
        'Desglose completo de las comisiones de Pocket Option en 2026: $0 en depósitos y retiros, sin comisión por operación, cómo gana el bróker con el porcentaje de pago y los costes reales a vigilar.',
      excerpt:
        'Pocket Option anuncia cero comisiones — en gran parte cierto. Esto es lo que pagas de verdad: diferencia de pago, comisiones de red y banco, volumen de bonos y la regla de inactividad.',
      coverAlt: 'Logos de métodos de pago de Pocket Option: Visa, Mastercard, Pix, UPI, M-Pesa y más',
      keyTakeaways: [
        'Pocket Option cobra $0 por depósitos y retiros y ninguna comisión por operación.',
        'El bróker gana con la diferencia de pago: una operación perdedora cuesta 100%, una ganadora paga 50–92% — esa es la “comisión” real.',
        'Pueden aplicarse costes externos: comisiones de red cripto, conversión de divisa de la tarjeta, cargos del monedero.',
        'Los bonos exigen volumen de operaciones; la comisión por inactividad solo aparece tras largos períodos sin operar.',
      ],
      blocks: [
        { type: 'p', text: 'Una de las razones de la popularidad de Pocket Option es su precio sencillo: sin comisión de depósito, sin comisión de retiro, sin comisión por operación, sin swap. Pero “sin comisiones” no significa “sin coste”. Esta guía explica exactamente cómo gana dinero pocketoption, qué cargos de terceros puedes encontrar y qué reglas de los términos pueden reducir tu saldo sin que lo notes.' },
        { type: 'h2', id: 'overview', text: 'Comisiones de Pocket Option de un vistazo' },
        { type: 'image', src: IMG_CONDITIONS, alt: 'Condiciones de Pocket Option mostrando $0 de comisión en depósito y retiro', caption: '“$0 — sin comisión en depósito y retiro” en la página oficial.' },
        { type: 'table', head: ['Concepto', 'Comisión Pocket Option', 'Notas'], rows: [
          ['Depósito', '$0', 'El proveedor de pago / la red puede cobrar'],
          ['Retiro', '$0', 'Mínimo $10; posible comisión del proveedor'],
          ['Comisión por operación', '$0', 'El coste va en el % de pago'],
          ['Spread', 'Ninguno en quick trading', 'Spread integrado en cuentas Forex/MT5'],
          ['Swap nocturno', 'Ninguno', 'Las operaciones expiran, nada queda abierto'],
          ['Conversión de divisa', '$0 por la plataforma', 'El banco/emisor puede convertir a su tipo'],
          ['Inactividad', 'Posible tras larga inactividad', 'Ver términos; opera o entra periódicamente'],
        ] },
        { type: 'h2', id: 'how-they-earn', text: 'Cómo gana dinero realmente Pocket Option' },
        { type: 'p', text: 'En operaciones rápidas y binarias nunca ves una línea de comisión porque el coste está en el porcentaje de pago. Una operación con pago del 92% significa: si ganas recibes $1,92 por cada $1 — si pierdes, pierdes el $1 entero. Estadísticamente, la diferencia entre el 100% y el pago es el margen del bróker. En un activo con pago del 70% ese margen es mucho mayor que en uno del 92%, por eso elegir activos de pago alto es la forma más eficaz de reducir tu coste.' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal de Pocket Option con el porcentaje de pago junto al activo', caption: 'El porcentaje de pago junto al nombre del activo es el único coste en operaciones rápidas.' },
        { type: 'tip', title: 'Regla práctica', text: 'Quédate con activos que paguen 80% o más. Al 92% necesitas un 52% de aciertos para empatar; al 70%, un 59%.' },
        { type: 'h2', id: 'deposit-fees', text: 'Comisiones de depósito: plataforma vs. proveedor' },
        { type: 'p', text: 'Pocket Option acredita el importe íntegro del depósito. Cualquier descuento viene de fuera de la plataforma:' },
        { type: 'ul', items: [
          'Cripto — comisión de red que pagas al enviar (USDT TRC-20 ≈ $1, ERC-20 puede superar $5). La plataforma no descuenta nada al recibir.',
          'Tarjetas — tu banco puede aplicar comisión por transacción internacional o conversión (1–3%) si la moneda de la tarjeta no es USD.',
          'Monederos — Skrill, Neteller y otros pueden cobrar su propia comisión de envío.',
          'Métodos locales — Pix, SPEI, Mercado Pago y la mayoría de transferencias móviles suelen ser gratis para quien envía.',
        ] },
        { type: 'h2', id: 'withdrawal-fees', text: 'Comisiones de retiro' },
        { type: 'p', text: 'Los retiros son gratis por parte de la plataforma, desde $10, y se procesan de media en menos de 24 horas. Aplican los mismos costes externos que en depósitos: la comisión de red cripto se descuenta del importe enviado y un banco puede cobrar por recibir una devolución internacional a tarjeta. Retirar por el mismo método del depósito, en la misma moneda, evita la mayoría de estos cargos.' },
        { type: 'warn', title: 'Retiros pequeños frecuentes', text: 'No hay comisión por retirar muchas veces, pero cada pago en cripto lleva comisión de red. Retirar $10 diez veces a un monedero ERC-20 puede costar más que un solo retiro de $100. Agrupa cuando puedas.' },
        { type: 'h2', id: 'hidden', text: 'Costes que no se llaman comisiones' },
        { type: 'ol', items: [
          'Volumen del bono — aceptar un bono de depósito bloquea el saldo hasta operar el volumen exigido (a menudo bono × 50 o más). Retirar antes puede cancelar el bono y el beneficio asociado.',
          'Regla de inactividad — tras un largo período sin operaciones, los términos permiten un cargo de mantenimiento en saldos inactivos. Entrar y operar en demo no cuenta; una operación real sí. Retira los fondos que no uses.',
          'Conversión de divisa — una cuenta en USD financiada con tarjeta en MXN/COP/ARS paga el tipo del banco dos veces (entrada y salida). Elegir moneda local de cuenta lo evita donde esté disponible.',
          'Regla de contracargo — disputar un depósito con tarjeta en tu banco lleva al cierre de la cuenta y una penalización según los términos.',
        ] },
        { type: 'h2', id: 'compare', text: 'Comparativa de comisiones de Pocket Option' },
        { type: 'table', head: ['Bróker', 'Comisión depósito / retiro', 'Depósito mín.', 'Pago máx.'], rows: [
          ['Pocket Option', '$0 / $0', '$5', 'hasta 92%'],
          ['Quotex', '$0 / $0', '$10', 'hasta 95%'],
          ['IQ Option', '$0 / $0 (comisión en transferencia)', '$10', 'hasta 95%'],
          ['Olymp Trade', '$0 / $0', '$10', 'hasta 93%'],
        ] },
        { type: 'p', text: 'Valores a fecha de redacción, cambian con frecuencia — compruébalo directamente en las plataformas. En la práctica, la estructura de comisiones de los grandes brókers binarios es similar; el porcentaje de pago y la calidad de ejecución importan más que el eslogan “cero comisiones”.' },
        { type: 'cta', text: 'Opera con $0 de comisión en depósito y retiro — abre una cuenta Pocket Option desde $5.', label: 'Abrir cuenta Pocket Option' },
      ],
      faq: [
        { q: '¿Pocket Option cobra comisión por depositar?', a: 'No. La plataforma acredita el 100% del depósito. Solo tu banco, monedero o la red cripto pueden cobrar.' },
        { q: '¿Pocket Option cobra comisión por retirar?', a: 'Sin comisión de la plataforma. Retiro mínimo $10; comisiones de red cripto y bancarias pueden aplicarse externamente.' },
        { q: '¿Hay comisión por operación en Pocket Option?', a: 'No. El coste está integrado en el porcentaje de pago — la diferencia entre el 100% y el pago que recibes al ganar.' },
        { q: '¿Pocket Option tiene comisión por inactividad?', a: 'Los términos permiten un cargo en cuentas sin actividad de trading durante un período prolongado. Haz una operación real ocasionalmente o retira los fondos inactivos.' },
        { q: '¿Pocket Option es más barato que Quotex o IQ Option?', a: 'Los tres tienen $0 en depósito y retiro. Pocket Option tiene el depósito mínimo más bajo ($5); los pagos máximos son comparables.' },
        { q: '¿Por qué recibí menos de lo que deposité?', a: 'Normalmente una comisión de red cripto o la conversión de divisa del emisor de tu tarjeta. Pocket Option no descuenta de los depósitos.' },
      ],
    },
    ru: {
      title: 'Комиссии Pocket Option',
      metaTitle: 'Комиссии Pocket Option: депозит, вывод, спред и скрытые расходы',
      metaDescription:
        'Полный разбор комиссий Pocket Option в 2026 году: $0 за депозит и вывод, нет комиссии за сделки, как брокер зарабатывает на проценте выплаты и какие реальные расходы стоит учитывать.',
      excerpt:
        'Pocket Option заявляет нулевые комиссии — в основном это правда. Вот что вы платите на самом деле: разница выплаты, комиссии сети и банка, оборот бонуса и правило неактивности.',
      coverAlt: 'Логотипы способов оплаты Pocket Option: Visa, Mastercard, Pix, UPI, M-Pesa и другие',
      keyTakeaways: [
        'Pocket Option берёт $0 за депозиты и выводы и не взимает комиссию за сделки.',
        'Брокер зарабатывает на разнице выплаты: убыточная сделка стоит 100%, прибыльная приносит 50–92% — это и есть реальная «комиссия».',
        'Возможны внешние расходы: комиссия криптосети, конвертация валюты по карте, сборы кошельков.',
        'Бонусы требуют оборота; комиссия за неактивность применяется только после долгого отсутствия сделок.',
      ],
      blocks: [
        { type: 'p', text: 'Одна из причин популярности Pocket Option — простые условия: нет комиссии за депозит, за вывод, за сделку, нет свопов. Но «без комиссий» не значит «бесплатно». В этом руководстве — как именно pocketoption зарабатывает, с какими сторонними сборами вы всё же можете столкнуться и какие правила из условий могут незаметно уменьшить баланс.' },
        { type: 'h2', id: 'overview', text: 'Комиссии Pocket Option вкратце' },
        { type: 'image', src: IMG_CONDITIONS, alt: 'Условия Pocket Option: $0 комиссии за депозит и вывод', caption: '«$0 — без комиссии за депозит и вывод» на официальной главной странице.' },
        { type: 'table', head: ['Статья', 'Комиссия Pocket Option', 'Примечания'], rows: [
          ['Депозит', '$0', 'Платёжный провайдер / сеть могут брать сбор'],
          ['Вывод', '$0', 'Минимум $10; возможна комиссия провайдера'],
          ['Комиссия за сделку', '$0', 'Расход заложен в % выплаты'],
          ['Спред', 'Нет в быстрой торговле', 'Встроенный спред на Forex/MT5-счетах'],
          ['Своп за перенос', 'Нет', 'Сделки экспирируют, позиции не переносятся'],
          ['Конвертация валюты', '$0 со стороны платформы', 'Банк/эмитент может конвертировать по своему курсу'],
          ['Неактивность', 'Возможна после долгой неактивности', 'См. условия; торгуйте или заходите периодически'],
        ] },
        { type: 'h2', id: 'how-they-earn', text: 'Как Pocket Option на самом деле зарабатывает' },
        { type: 'p', text: 'В быстрых и бинарных сделках вы никогда не видите строку комиссии, потому что расход зашит в процент выплаты. Сделка с выплатой 92% означает: при выигрыше вы получаете $1,92 на $1 — при проигрыше теряете весь $1. Статистически разница между 100% и выплатой — маржа брокера. На активе с выплатой 70% эта маржа гораздо больше, чем на 92%, поэтому выбор активов с высокой выплатой — самый эффективный способ снизить торговые расходы.' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Терминал Pocket Option с процентом выплаты рядом с активом', caption: 'Процент выплаты рядом с названием актива — единственный торговый расход в быстрых сделках.' },
        { type: 'tip', title: 'Практическое правило', text: 'Держитесь активов с выплатой от 80%. При 92% для безубытка нужно 52% прибыльных сделок; при 70% — уже 59%.' },
        { type: 'h2', id: 'deposit-fees', text: 'Комиссии за депозит: платформа и провайдер' },
        { type: 'p', text: 'Pocket Option зачисляет депозит полностью. Любое удержание происходит вне платформы:' },
        { type: 'ul', items: [
          'Крипта — комиссию сети вы платите при отправке (USDT TRC-20 ≈ $1, ERC-20 может быть $5+). Платформа при получении ничего не удерживает.',
          'Карты — банк может взять сбор за международную операцию или конвертацию (обычно 1–3%), если валюта карты отличается от USD.',
          'Электронные кошельки — Skrill, Neteller и другие могут брать свою комиссию за отправку.',
          'Локальные способы — Kaspi, Pix, UPI и большинство мобильных переводов обычно бесплатны для отправителя.',
        ] },
        { type: 'h2', id: 'withdrawal-fees', text: 'Комиссии за вывод' },
        { type: 'p', text: 'Вывод бесплатен со стороны платформы, от $10, обрабатывается в среднем до 24 часов. Действуют те же внешние расходы, что и при депозите: комиссия криптосети вычитается из отправляемой суммы, а банк может брать сбор за получение международного возврата на карту. Вывод тем же способом, которым пополняли, и в той же валюте избавляет от большинства сборов.' },
        { type: 'warn', title: 'Частые мелкие выводы', text: 'Комиссии за количество выводов нет, но каждая криптовыплата несёт комиссию сети. Десять выводов по $10 на ERC-20-кошелёк могут обойтись дороже одного вывода на $100. По возможности объединяйте.' },
        { type: 'h2', id: 'hidden', text: 'Расходы, которые не называют комиссиями' },
        { type: 'ol', items: [
          'Оборот бонуса — принятие бонуса на депозит блокирует баланс до наторговки требуемого объёма (часто бонус × 50 и более). Досрочный вывод может отменить бонус и связанную прибыль.',
          'Правило неактивности — после долгого отсутствия сделок условия допускают сбор за обслуживание спящих балансов. Вход и сделки на демо не считаются; реальная сделка — да. Выводите неиспользуемые средства.',
          'Конвертация валюты — счёт в USD, пополняемый с карты в KZT/UZS, платит курс банка дважды (на вход и на выход). Локальная валюта счёта, где доступна, решает проблему.',
          'Правило чарджбэка — оспаривание карточного депозита через банк ведёт к закрытию счёта и штрафу по условиям.',
        ] },
        { type: 'h2', id: 'compare', text: 'Сравнение комиссий Pocket Option' },
        { type: 'table', head: ['Брокер', 'Комиссия депозит / вывод', 'Мин. депозит', 'Макс. выплата'], rows: [
          ['Pocket Option', '$0 / $0', '$5', 'до 92%'],
          ['Quotex', '$0 / $0', '$10', 'до 95%'],
          ['IQ Option', '$0 / $0 (сбор за банковский перевод)', '$10', 'до 95%'],
          ['Olymp Trade', '$0 / $0', '$10', 'до 93%'],
        ] },
        { type: 'p', text: 'Значения на момент написания, часто меняются — проверяйте на самих платформах. На практике структура комиссий у всех крупных бинарных брокеров похожа; процент выплаты и качество исполнения важнее лозунга «нулевые комиссии».' },
        { type: 'cta', text: 'Торгуйте с $0 комиссии за депозит и вывод — откройте счёт Pocket Option от $5.', label: 'Открыть счёт Pocket Option' },
      ],
      faq: [
        { q: 'Берёт ли Pocket Option комиссию за депозит?', a: 'Нет. Платформа зачисляет 100% депозита. Комиссию могут брать только ваш банк, кошелёк или криптосеть.' },
        { q: 'Берёт ли Pocket Option комиссию за вывод?', a: 'Комиссии платформы нет. Минимальный вывод $10; внешне возможны комиссия криптосети и банковские сборы.' },
        { q: 'Есть ли комиссия за сделку на Pocket Option?', a: 'Нет. Расход заложен в процент выплаты — разницу между 100% и выплатой, которую вы получаете при выигрыше.' },
        { q: 'Есть ли у Pocket Option комиссия за неактивность?', a: 'Условия допускают сбор со счетов без торговой активности в течение длительного периода. Периодически совершайте реальную сделку или выводите неиспользуемые средства.' },
        { q: 'Pocket Option дешевле Quotex или IQ Option?', a: 'У всех трёх $0 за депозит и вывод. У Pocket Option самый низкий минимальный депозит ($5); максимальные выплаты сопоставимы.' },
        { q: 'Почему я получил меньше, чем внёс?', a: 'Обычно комиссия криптосети или конвертация валюты банком-эмитентом. Сама Pocket Option из депозитов ничего не удерживает.' },
      ],
    },
    id: {
      title: 'Biaya Pocket Option',
      metaTitle: 'Biaya Pocket Option: Deposit, Penarikan, Spread & Biaya Tersembunyi',
      metaDescription:
        'Rincian lengkap biaya Pocket Option 2026: biaya deposit dan penarikan $0, tanpa komisi per trade, cara broker mendapat untung lewat persentase payout, dan biaya nyata yang perlu diwaspadai.',
      excerpt:
        'Pocket Option mengiklankan nol biaya — sebagian besar benar. Ini yang sebenarnya Anda bayar: selisih payout, biaya jaringan dan bank, turnover bonus, dan aturan inaktivitas.',
      coverAlt: 'Logo metode pembayaran Pocket Option: Visa, Mastercard, Pix, UPI, M-Pesa, dan lainnya',
      keyTakeaways: [
        'Pocket Option mengenakan $0 untuk deposit dan penarikan serta tanpa komisi per trade.',
        'Broker mendapat untung dari selisih payout: trade kalah menghabiskan 100%, trade menang membayar 50–92% — itulah “biaya” sebenarnya.',
        'Biaya eksternal bisa berlaku: biaya jaringan kripto, konversi mata uang kartu, biaya e-wallet.',
        'Bonus membawa syarat turnover; biaya inaktivitas hanya berlaku setelah lama tidak trading.',
      ],
      blocks: [
        { type: 'p', text: 'Salah satu alasan Pocket Option populer adalah struktur harganya yang sederhana: tanpa biaya deposit, tanpa biaya penarikan, tanpa komisi per trade, tanpa swap. Tetapi “tanpa biaya” tidak berarti “tanpa ongkos”. Panduan ini menjelaskan persis bagaimana pocketoption menghasilkan uang, biaya pihak ketiga apa yang masih bisa Anda temui, dan aturan mana dalam ketentuan yang diam-diam bisa mengurangi saldo Anda.' },
        { type: 'h2', id: 'overview', text: 'Ringkasan biaya Pocket Option' },
        { type: 'image', src: IMG_CONDITIONS, alt: 'Kondisi Pocket Option menampilkan komisi $0 untuk deposit dan penarikan', caption: '“$0 — tanpa komisi deposit dan penarikan” di beranda resmi.' },
        { type: 'table', head: ['Item', 'Biaya Pocket Option', 'Catatan'], rows: [
          ['Deposit', '$0', 'Penyedia pembayaran / jaringan mungkin mengenakan biaya'],
          ['Penarikan', '$0', 'Minimum $10; biaya penyedia mungkin ada'],
          ['Komisi per trade', '$0', 'Biaya sudah termasuk di % payout'],
          ['Spread', 'Tidak ada di quick trading', 'Spread bawaan di akun Forex/MT5'],
          ['Swap semalam', 'Tidak ada', 'Trade kedaluwarsa, tidak ada posisi menginap'],
          ['Konversi mata uang', '$0 oleh platform', 'Bank/penerbit kartu bisa mengonversi dengan kursnya'],
          ['Inaktivitas', 'Mungkin setelah lama tidak aktif', 'Lihat ketentuan; trading atau login berkala'],
        ] },
        { type: 'h2', id: 'how-they-earn', text: 'Bagaimana Pocket Option sebenarnya mendapat untung' },
        { type: 'p', text: 'Pada quick trade dan opsi biner Anda tidak pernah melihat baris komisi karena biayanya ada di persentase payout. Trade dengan payout 92% berarti: menang, Anda dapat $1,92 dari $1 — kalah, Anda kehilangan $1 penuh. Secara statistik, selisih antara 100% dan payout adalah margin broker. Pada aset payout 70% margin itu jauh lebih besar daripada di 92%, itulah sebabnya memilih aset payout tinggi adalah cara paling efektif menekan biaya trading Anda.' },
        { type: 'image', src: IMG_TERMINAL, alt: 'Terminal Pocket Option dengan persentase payout di samping aset', caption: 'Persentase payout di samping nama aset adalah satu-satunya biaya trading pada quick trade.' },
        { type: 'tip', title: 'Aturan praktis', text: 'Pilih aset dengan payout 80% ke atas. Di 92% Anda butuh win rate 52% untuk impas; di 70% butuh 59%.' },
        { type: 'h2', id: 'deposit-fees', text: 'Biaya deposit: platform vs. penyedia pembayaran' },
        { type: 'p', text: 'Pocket Option mengkredit jumlah deposit penuh. Potongan apa pun berasal dari luar platform:' },
        { type: 'ul', items: [
          'Kripto — biaya jaringan blockchain Anda bayar saat mengirim (USDT TRC-20 ≈ $1, ERC-20 bisa $5+). Platform tidak memotong apa pun saat dana masuk.',
          'Kartu — bank Anda mungkin mengenakan biaya transaksi luar negeri atau konversi mata uang (biasanya 1–3%) jika mata uang kartu berbeda dari USD.',
          'E-wallet — Skrill, Neteller, dan lainnya mungkin mengenakan biaya kirim sendiri.',
          'Metode lokal — QRIS, transfer bank lokal, dan sebagian besar e-wallet Indonesia biasanya gratis bagi pengirim.',
        ] },
        { type: 'h2', id: 'withdrawal-fees', text: 'Biaya penarikan' },
        { type: 'p', text: 'Penarikan gratis dari sisi platform, minimum $10, diproses rata-rata dalam 24 jam. Biaya eksternal yang sama seperti deposit berlaku: biaya jaringan kripto dipotong dari jumlah yang dikirim, dan bank mungkin mengenakan biaya menerima refund kartu internasional. Menarik ke metode yang sama dengan deposit, dalam mata uang yang sama, menghindari sebagian besar biaya ini.' },
        { type: 'warn', title: 'Penarikan kecil yang sering', text: 'Tidak ada biaya untuk banyak penarikan, tetapi setiap pembayaran kripto membawa biaya jaringan. Menarik $10 sepuluh kali ke wallet ERC-20 bisa lebih mahal daripada satu penarikan $100. Gabungkan bila bisa.' },
        { type: 'h2', id: 'hidden', text: 'Biaya yang tidak disebut biaya' },
        { type: 'ol', items: [
          'Turnover bonus — menerima bonus deposit mengunci saldo sampai Anda mencapai volume yang disyaratkan (sering bonus × 50 atau lebih). Menarik lebih awal bisa membatalkan bonus dan profit terkait.',
          'Aturan inaktivitas — setelah lama tanpa trade, ketentuan memperbolehkan biaya pemeliharaan pada saldo tidak aktif. Login dan trade di demo tidak dihitung; trade riil dihitung. Tarik dana yang tidak Anda pakai.',
          'Konversi mata uang — akun USD yang didanai dari kartu IDR membayar kurs bank dua kali (masuk dan keluar). Memilih mata uang akun lokal menghindarinya bila tersedia.',
          'Aturan chargeback — menyengketakan deposit kartu lewat bank berujung penutupan akun dan penalti sesuai ketentuan.',
        ] },
        { type: 'h2', id: 'compare', text: 'Perbandingan biaya Pocket Option' },
        { type: 'table', head: ['Broker', 'Biaya deposit / penarikan', 'Deposit min.', 'Payout maks.'], rows: [
          ['Pocket Option', '$0 / $0', '$5', 'hingga 92%'],
          ['Quotex', '$0 / $0', '$10', 'hingga 95%'],
          ['IQ Option', '$0 / $0 (biaya transfer bank)', '$10', 'hingga 95%'],
          ['Olymp Trade', '$0 / $0', '$10', 'hingga 93%'],
        ] },
        { type: 'p', text: 'Nilai per saat penulisan dan sering berubah — cek langsung di platform. Praktiknya, struktur biaya semua broker biner besar serupa; persentase payout dan kualitas eksekusi lebih penting daripada slogan “nol biaya”.' },
        { type: 'cta', text: 'Trading dengan biaya deposit dan penarikan $0 — buka akun Pocket Option mulai $5.', label: 'Buka akun Pocket Option' },
      ],
      faq: [
        { q: 'Apakah Pocket Option mengenakan biaya deposit?', a: 'Tidak. Platform mengkredit 100% deposit. Hanya bank, e-wallet, atau jaringan kripto Anda yang mungkin mengenakan biaya.' },
        { q: 'Apakah Pocket Option mengenakan biaya penarikan?', a: 'Tidak ada biaya platform. Penarikan minimum $10; biaya jaringan kripto dan bank bisa berlaku secara eksternal.' },
        { q: 'Apakah ada komisi per trade di Pocket Option?', a: 'Tidak. Biayanya tertanam di persentase payout — selisih antara 100% dan payout yang Anda terima saat menang.' },
        { q: 'Apakah Pocket Option punya biaya inaktivitas?', a: 'Ketentuan memperbolehkan biaya pada akun tanpa aktivitas trading dalam periode panjang. Lakukan trade riil sesekali atau tarik dana menganggur.' },
        { q: 'Apakah Pocket Option lebih murah dari Quotex atau IQ Option?', a: 'Ketiganya punya biaya deposit dan penarikan $0. Pocket Option punya deposit minimum terendah ($5); payout maksimum sebanding.' },
        { q: 'Kenapa saya menerima kurang dari yang saya setor?', a: 'Biasanya biaya jaringan kripto atau konversi mata uang penerbit kartu. Pocket Option sendiri tidak memotong deposit.' },
      ],
    },
  },
};
