import type { BlogPost } from '../types';

const IMG_ARROWS = '/images/blog/po-terminal-signal-arrows.webp';
const IMG_CANDLES = '/images/blog/po-candlestick-guide.webp';
const IMG_PANEL = '/images/blog/po-tournaments-panel.webp';

export const pocketOptionSignals: BlogPost = {
  slug: 'pocket-option-signals',
  category: 'strategy',
  cover: '/images/blog/pocket-option-signals.webp',
  publishedAt: '2026-09-10',
  updatedAt: '2026-09-10',
  readingMinutes: 9,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option signals: built-in signals, Telegram channels and bots — what works and what to avoid',
      metaTitle: 'Pocket Option Signals – Built-in, Telegram & Bots Explained',
      metaDescription:
        'How Pocket Option signals work: the built-in Signals panel, paid Telegram channels, free bots and AI signals — how to test them on demo, filter them and avoid scams.',
      excerpt:
        'A realistic guide to pocketoption trading signals: what the terminal’s Signals panel shows, how to judge third-party Telegram signals and bots, and a filter that separates useful signals from noise.',
      coverAlt: 'Pocket Option trading terminal with candlestick chart — signals are shown in the right sidebar',
      keyTakeaways: [
        'Pocket Option has a free built-in Signals panel in the terminal that shows the direction, strength and horizon of a trend for each asset — a starting point, not a trade instruction.',
        'Third-party Telegram signals, bots and “AI signal” apps are not affiliated with the platform; most publish only winning screenshots and hide the losing streaks.',
        'Test any signal source on the demo for at least 100 signals and record the win rate against the payout break-even (52–56%).',
        'Use signals as a filter, not a trigger: take only those that agree with your own analysis of trend, support/resistance and session.',
        'Never pay for signals with a “guaranteed 90% accuracy” promise, never share your login, and never let a bot trade a real balance you cannot afford to lose.',
      ],
      blocks: [
        { type: 'p', text: '“Pocket Option signals” is one of the most searched phrases around the platform — and one of the most abused. The term covers three very different things: the free Signals panel built into the pocketoption terminal, paid or free Telegram channels run by third parties, and automated bots or “AI” apps that promise to trade for you. This guide explains what each one is, how to test it honestly on a demo account and how to spot the scams that cost beginners their first deposit.' },
        { type: 'h2', id: 'builtin', text: 'The built-in Signals panel on Pocket Option' },
        { type: 'image', src: IMG_PANEL, alt: 'Pocket Option terminal right sidebar with Signals, Social Trading, Express Trades and Tournaments', caption: 'Signals is the first item in the right sidebar of the terminal.' },
        { type: 'p', text: 'Click Signals in the right sidebar of the terminal and you will see a list of assets with a direction (Up/Down), a strength indicator and a time horizon (for example 1 minute, 5 minutes, 30 minutes). The signals are generated automatically from technical indicators such as moving averages, RSI and MACD — they summarise the current trend, they do not predict the future. They are free, updated in real time, and available on demo and real accounts.' },
        { type: 'table', head: ['Element', 'What it shows', 'How to use it'], rows: [
          ['Direction', 'Dominant trend on the chosen horizon', 'Trade only in the direction of the signal on the same or a longer timeframe'],
          ['Strength', 'How many indicators agree', 'Prefer strong signals; skip weak or mixed ones'],
          ['Horizon', 'Timeframe the signal refers to', 'Match your expiry to it — a 5-minute signal is not for 5-second trades'],
          ['Asset payout', 'Shown next to the asset', 'Skip signals on assets below your minimum payout (75–80%)'],
        ] },
        { type: 'tip', title: 'Confirm with the chart', text: 'Open the asset, look at the last 20–30 candles and the nearest support/resistance. If the signal says Up but the price is right below a strong resistance, wait for a breakout or skip. Signals confirm your analysis; they do not replace it.' },
        { type: 'image', src: IMG_ARROWS, alt: 'Pocket Option chart with up and down signal arrows on candles', caption: 'Signal arrows on the chart mark candles where indicators aligned — always check the context around them.' },
        { type: 'h2', id: 'telegram', text: 'Telegram signals and paid channels' },
        { type: 'p', text: 'Hundreds of Telegram channels sell “Pocket Option VIP signals”. They are not connected to the platform. The business model is usually one of these: a monthly subscription, an affiliate link where the channel earns from your deposits, or an upsell to “account management”. Some are honest analysts with a modest edge; many are marketing machines. The tell-tale signs of a bad channel:' },
        { type: 'ul', items: [
          'Only winning screenshots, never a full daily record including losses.',
          'Claims of 90–98% accuracy — realistically excellent binary traders sit around 60–65%.',
          'Pressure to deposit through their link or to hand over your login.',
          'Martingale “recovery” instructions after a loss (double the amount until you win).',
          'Signals with 5–30 second expiries — nobody can reliably signal that horizon by hand.',
        ] },
        { type: 'warn', title: 'Never share your login or let anyone “manage” your account', text: 'Pocket Option, like every broker, prohibits account management by third parties. Scammers who receive your password either drain the balance or run martingale until the account is empty, then disappear. No legitimate signal provider needs your credentials.' },
        { type: 'h2', id: 'bots', text: 'Bots, robots and “AI signals”' },
        { type: 'p', text: 'Automated bots claim to read the chart and place trades for you. Some run as browser extensions, others as apps that ask for your Pocket Option session. Three things to know: first, using unauthorised automation may violate the platform rules and lead to account restrictions; second, most bots are simple indicator crossovers wrapped in a slick interface, with results that break down as soon as volatility changes; third, a bot with your credentials has the same risks as account management above. Pocket Option itself offers built-in tools — signals, social trading, express trades — that stay within the rules; use them instead of third-party automation.' },
        { type: 'h2', id: 'test', text: 'How to test any signal source honestly' },
        { type: 'ol', items: [
          'Open a demo account and pick one signal source (the built-in panel, a channel, a bot).',
          'Follow every signal exactly as given — same asset, direction, expiry — for at least 100 signals or two weeks.',
          'Record each result in a spreadsheet: date, asset, direction, expiry, payout, win/loss.',
          'Calculate the win rate and compare it with the break-even for the average payout: 52.1% at 92%, 55.6% at 80%, 58.8% at 70%.',
          'Only if the win rate stays above break-even plus a margin (about 5 percentage points) across the whole sample should you consider real money — with $1–$2 trades first.',
        ] },
        { type: 'image', src: IMG_CANDLES, alt: 'Candlestick chart explanation with bullish and bearish candles', caption: 'Understanding candles yourself is the best filter for any signal — you will spot when a signal contradicts the price action.' },
        { type: 'h2', id: 'filter', text: 'A simple filter that improves most signals' },
        { type: 'p', text: 'Even average signals become more useful when you filter them. Take a signal only if all of the following are true:' },
        { type: 'ul', items: [
          'The asset payout is at or above your minimum (75–80%).',
          'The direction matches the trend on a higher timeframe (e.g. signal on 1 minute, trend on 5–15 minutes).',
          'The price is not sitting right at a strong support or resistance against the signal direction.',
          'No high-impact news is scheduled for that currency in the next 15 minutes.',
          'You have not yet reached your daily loss limit (e.g. 3 losses or 5% of balance).',
        ] },
        { type: 'p', text: 'Expect to skip more than half of all signals. That is the point — the ones you take are the ones with several factors in your favour.' },
        { type: 'h2', id: 'compare', text: 'Signals vs social trading vs your own strategy' },
        { type: 'table', head: ['Approach', 'Cost', 'Control', 'Best for'], rows: [
          ['Built-in signals', 'Free', 'Full — you decide each trade', 'Beginners learning to read trends'],
          ['Telegram signals', 'Free or $30–$200/month', 'Medium — you follow someone else’s timing', 'Traders who want ideas but will verify them'],
          ['Bots / AI apps', 'Often paid, plus your risk', 'Low — the software trades', 'Not recommended; rule and security risks'],
          ['Social trading', 'Free (copy from $1)', 'Medium — automatic copying with your limits', 'Small balances that want to learn from top traders'],
          ['Own strategy', 'Time', 'Full', 'Long-term consistent trading'],
        ] },
        { type: 'cta', text: 'Try the built-in signals for free: open a demo account, enable the Signals panel and test the filter above before risking a single dollar.', label: 'Open a free demo account' },
      ],
      faq: [
        { q: 'Does Pocket Option have free signals?', a: 'Yes. The Signals panel in the terminal is free and shows the direction, strength and horizon of the trend for each asset, on demo and real accounts.' },
        { q: 'Are Pocket Option Telegram signals accurate?', a: 'They vary widely and are not affiliated with the platform. Test any channel on demo for at least 100 signals and compare the win rate with the payout break-even before trusting it.' },
        { q: 'Are signal bots allowed on Pocket Option?', a: 'Third-party automation is not officially supported and may violate the rules; it also requires sharing your session or credentials, which is a security risk. Use the built-in tools instead.' },
        { q: 'What win rate do signals need to be profitable?', a: 'Above the break-even for your average payout: about 52% at 92% payout, 56% at 80% and 59% at 70%. Aim for at least 5 points above that.' },
        { q: 'Can I trade only with signals?', a: 'You can, but results are usually better when signals are filtered by your own analysis of trend, levels, payout and news.' },
        { q: 'Should I pay for VIP signals?', a: 'Only after a documented demo test proves the channel’s edge. Avoid any channel that promises guaranteed accuracy, asks for your login or recommends martingale.' },
      ],
    },
    pt: {
      title: 'Sinais da Pocket Option: sinais integrados, canais do Telegram e bots — o que funciona e o que evitar',
      metaTitle: 'Sinais Pocket Option – Integrados, Telegram e Bots Explicados',
      metaDescription:
        'Como funcionam os sinais da Pocket Option: o painel Signals integrado, canais pagos do Telegram, bots gratuitos e sinais de IA — como testar na demo, filtrar e evitar golpes.',
      excerpt:
        'Guia realista sobre sinais de trading da pocketoption: o que o painel Signals do terminal mostra, como avaliar sinais de Telegram e bots, e um filtro que separa sinais úteis de ruído.',
      coverAlt: 'Terminal de trading da Pocket Option com gráfico de velas — sinais aparecem na barra lateral direita',
      keyTakeaways: [
        'A Pocket Option tem um painel Signals gratuito no terminal que mostra direção, força e horizonte da tendência de cada ativo — um ponto de partida, não uma ordem de operação.',
        'Sinais de Telegram, bots e apps de “sinais de IA” de terceiros não têm relação com a plataforma; a maioria publica só prints de ganhos e esconde as sequências de perdas.',
        'Teste qualquer fonte de sinais na demo por pelo menos 100 sinais e registre a taxa de acerto contra o ponto de equilíbrio do payout (52–56%).',
        'Use sinais como filtro, não como gatilho: aceite apenas os que concordam com sua análise de tendência, suporte/resistência e sessão.',
        'Nunca pague por sinais com promessa de “90% de acerto garantido”, nunca compartilhe seu login e nunca deixe um bot operar saldo real que você não pode perder.',
      ],
      blocks: [
        { type: 'p', text: '“Sinais Pocket Option” é uma das buscas mais frequentes sobre a plataforma — e uma das mais exploradas por golpistas. O termo cobre três coisas muito diferentes: o painel Signals gratuito integrado ao terminal da pocketoption, canais do Telegram pagos ou gratuitos de terceiros, e bots ou apps de “IA” que prometem operar por você. Este guia explica o que é cada um, como testar honestamente na demo e como identificar os golpes que custam o primeiro depósito de muitos iniciantes.' },
        { type: 'h2', id: 'builtin', text: 'O painel Signals integrado da Pocket Option' },
        { type: 'image', src: IMG_PANEL, alt: 'Barra lateral direita do terminal Pocket Option com Signals, Social Trading, Express Trades e Tournaments', caption: 'Signals é o primeiro item da barra lateral direita do terminal.' },
        { type: 'p', text: 'Clique em Signals na barra lateral direita e verá uma lista de ativos com direção (Alta/Baixa), indicador de força e horizonte de tempo (por exemplo 1 minuto, 5 minutos, 30 minutos). Os sinais são gerados automaticamente a partir de indicadores técnicos como médias móveis, RSI e MACD — resumem a tendência atual, não preveem o futuro. São gratuitos, atualizados em tempo real e disponíveis na demo e na conta real.' },
        { type: 'table', head: ['Elemento', 'O que mostra', 'Como usar'], rows: [
          ['Direção', 'Tendência dominante no horizonte escolhido', 'Opere só na direção do sinal no mesmo timeframe ou maior'],
          ['Força', 'Quantos indicadores concordam', 'Prefira sinais fortes; ignore fracos ou mistos'],
          ['Horizonte', 'Timeframe a que o sinal se refere', 'Alinhe a expiração — sinal de 5 minutos não é para operações de 5 segundos'],
          ['Payout do ativo', 'Mostrado ao lado do ativo', 'Ignore sinais em ativos abaixo do seu payout mínimo (75–80%)'],
        ] },
        { type: 'tip', title: 'Confirme no gráfico', text: 'Abra o ativo, olhe as últimas 20–30 velas e o suporte/resistência mais próximo. Se o sinal diz Alta mas o preço está logo abaixo de uma resistência forte, espere o rompimento ou pule. Sinais confirmam sua análise; não a substituem.' },
        { type: 'image', src: IMG_ARROWS, alt: 'Gráfico da Pocket Option com setas de sinal de alta e baixa nas velas', caption: 'Setas de sinal no gráfico marcam velas onde os indicadores se alinharam — sempre confira o contexto ao redor.' },
        { type: 'h2', id: 'telegram', text: 'Sinais no Telegram e canais pagos' },
        { type: 'p', text: 'Centenas de canais do Telegram vendem “sinais VIP Pocket Option”. Não têm ligação com a plataforma. O modelo de negócio costuma ser: assinatura mensal, link de afiliado em que o canal ganha com seus depósitos, ou venda de “gestão de conta”. Alguns são analistas honestos com vantagem modesta; muitos são máquinas de marketing. Sinais de um canal ruim:' },
        { type: 'ul', items: [
          'Só prints de ganhos, nunca um registro diário completo incluindo perdas.',
          'Alegações de 90–98% de acerto — traders binários excelentes ficam realisticamente em 60–65%.',
          'Pressão para depositar pelo link deles ou entregar seu login.',
          'Instruções de “recuperação” martingale após perda (dobrar o valor até ganhar).',
          'Sinais com expiração de 5–30 segundos — ninguém sinaliza esse horizonte com confiabilidade manualmente.',
        ] },
        { type: 'warn', title: 'Nunca compartilhe seu login nem deixe alguém “gerir” sua conta', text: 'A Pocket Option, como toda corretora, proíbe gestão de conta por terceiros. Golpistas que recebem sua senha esvaziam o saldo ou rodam martingale até a conta zerar, e desaparecem. Nenhum provedor legítimo precisa das suas credenciais.' },
        { type: 'h2', id: 'bots', text: 'Bots, robôs e “sinais de IA”' },
        { type: 'p', text: 'Bots automáticos afirmam ler o gráfico e operar por você. Alguns rodam como extensão do navegador, outros como apps que pedem sua sessão da Pocket Option. Três pontos: primeiro, automação não autorizada pode violar as regras da plataforma e gerar restrições na conta; segundo, a maioria dos bots é um simples cruzamento de indicadores com interface bonita, cujos resultados desmoronam quando a volatilidade muda; terceiro, um bot com suas credenciais tem os mesmos riscos da gestão de conta acima. A própria Pocket Option oferece ferramentas integradas — sinais, social trading, express trades — dentro das regras; use-as em vez de automação de terceiros.' },
        { type: 'h2', id: 'test', text: 'Como testar qualquer fonte de sinais com honestidade' },
        { type: 'ol', items: [
          'Abra uma conta demo e escolha uma fonte (painel integrado, canal, bot).',
          'Siga cada sinal exatamente como dado — mesmo ativo, direção, expiração — por pelo menos 100 sinais ou duas semanas.',
          'Registre cada resultado em planilha: data, ativo, direção, expiração, payout, ganho/perda.',
          'Calcule a taxa de acerto e compare com o ponto de equilíbrio do payout médio: 52,1% a 92%, 55,6% a 80%, 58,8% a 70%.',
          'Só se a taxa ficar acima do equilíbrio com margem (cerca de 5 pontos) em toda a amostra considere dinheiro real — com operações de $1–$2 primeiro.',
        ] },
        { type: 'image', src: IMG_CANDLES, alt: 'Explicação de gráfico de velas com velas de alta e baixa', caption: 'Entender velas por conta própria é o melhor filtro para qualquer sinal — você percebe quando um sinal contradiz o price action.' },
        { type: 'h2', id: 'filter', text: 'Um filtro simples que melhora a maioria dos sinais' },
        { type: 'p', text: 'Até sinais medianos ficam mais úteis quando filtrados. Aceite um sinal só se tudo abaixo for verdade:' },
        { type: 'ul', items: [
          'O payout do ativo está no seu mínimo ou acima (75–80%).',
          'A direção coincide com a tendência de um timeframe maior (ex.: sinal em 1 minuto, tendência em 5–15 minutos).',
          'O preço não está colado em suporte/resistência forte contra a direção do sinal.',
          'Não há notícia de alto impacto para aquela moeda nos próximos 15 minutos.',
          'Você ainda não atingiu seu limite diário de perda (ex.: 3 perdas ou 5% do saldo).',
        ] },
        { type: 'p', text: 'Espere pular mais da metade dos sinais. É esse o objetivo — os que você aceita são os com vários fatores a seu favor.' },
        { type: 'h2', id: 'compare', text: 'Sinais vs social trading vs estratégia própria' },
        { type: 'table', head: ['Abordagem', 'Custo', 'Controle', 'Melhor para'], rows: [
          ['Sinais integrados', 'Grátis', 'Total — você decide cada operação', 'Iniciantes aprendendo a ler tendências'],
          ['Sinais no Telegram', 'Grátis ou $30–$200/mês', 'Médio — você segue o timing de outro', 'Quem quer ideias mas vai verificá-las'],
          ['Bots / apps de IA', 'Geralmente pagos, mais seu risco', 'Baixo — o software opera', 'Não recomendado; risco de regras e segurança'],
          ['Social trading', 'Grátis (cópia a partir de $1)', 'Médio — cópia automática com seus limites', 'Saldos pequenos que querem aprender com top traders'],
          ['Estratégia própria', 'Tempo', 'Total', 'Trading consistente de longo prazo'],
        ] },
        { type: 'cta', text: 'Experimente os sinais integrados de graça: abra uma conta demo, ative o painel Signals e teste o filtro acima antes de arriscar um dólar.', label: 'Abrir conta demo gratuita' },
      ],
      faq: [
        { q: 'A Pocket Option tem sinais gratuitos?', a: 'Sim. O painel Signals do terminal é gratuito e mostra direção, força e horizonte da tendência de cada ativo, na demo e na conta real.' },
        { q: 'Os sinais de Telegram da Pocket Option são precisos?', a: 'Variam muito e não têm ligação com a plataforma. Teste qualquer canal na demo por pelo menos 100 sinais e compare a taxa de acerto com o equilíbrio do payout antes de confiar.' },
        { q: 'Bots de sinais são permitidos na Pocket Option?', a: 'Automação de terceiros não é oficialmente suportada e pode violar as regras; também exige compartilhar sessão ou credenciais, um risco de segurança. Use as ferramentas integradas.' },
        { q: 'Que taxa de acerto os sinais precisam para dar lucro?', a: 'Acima do equilíbrio do seu payout médio: cerca de 52% a 92% de payout, 56% a 80% e 59% a 70%. Busque pelo menos 5 pontos acima disso.' },
        { q: 'Posso operar só com sinais?', a: 'Pode, mas os resultados costumam ser melhores quando os sinais são filtrados pela sua análise de tendência, níveis, payout e notícias.' },
        { q: 'Devo pagar por sinais VIP?', a: 'Só depois de um teste documentado na demo comprovar a vantagem do canal. Evite qualquer canal que prometa acerto garantido, peça seu login ou recomende martingale.' },
      ],
    },
    es: {
      title: 'Señales de Pocket Option: señales integradas, canales de Telegram y bots — qué funciona y qué evitar',
      metaTitle: 'Señales Pocket Option – Integradas, Telegram y Bots Explicados',
      metaDescription:
        'Cómo funcionan las señales de Pocket Option: el panel Signals integrado, canales de Telegram de pago, bots gratuitos y señales de IA — cómo probarlas en demo, filtrarlas y evitar estafas.',
      excerpt:
        'Guía realista sobre señales de trading de pocketoption: qué muestra el panel Signals del terminal, cómo juzgar señales de Telegram y bots, y un filtro que separa las señales útiles del ruido.',
      coverAlt: 'Terminal de trading de Pocket Option con gráfico de velas — las señales aparecen en la barra lateral derecha',
      keyTakeaways: [
        'Pocket Option tiene un panel Signals gratuito en el terminal que muestra dirección, fuerza y horizonte de la tendencia de cada activo — un punto de partida, no una orden de operar.',
        'Las señales de Telegram, bots y apps de “señales IA” de terceros no están afiliadas a la plataforma; la mayoría publica solo capturas ganadoras y oculta las rachas perdedoras.',
        'Prueba cualquier fuente de señales en demo durante al menos 100 señales y registra la tasa de acierto frente al punto de equilibrio del payout (52–56%).',
        'Usa las señales como filtro, no como disparador: toma solo las que coincidan con tu propio análisis de tendencia, soporte/resistencia y sesión.',
        'Nunca pagues señales con promesa de “90% de precisión garantizada”, nunca compartas tu login y nunca dejes que un bot opere saldo real que no puedas perder.',
      ],
      blocks: [
        { type: 'p', text: '“Señales Pocket Option” es una de las búsquedas más frecuentes sobre la plataforma — y una de las más explotadas. El término abarca tres cosas muy distintas: el panel Signals gratuito integrado en el terminal de pocketoption, canales de Telegram de pago o gratuitos gestionados por terceros, y bots o apps de “IA” que prometen operar por ti. Esta guía explica qué es cada uno, cómo probarlo honestamente en demo y cómo detectar las estafas que cuestan a los principiantes su primer depósito.' },
        { type: 'h2', id: 'builtin', text: 'El panel Signals integrado de Pocket Option' },
        { type: 'image', src: IMG_PANEL, alt: 'Barra lateral derecha del terminal Pocket Option con Signals, Social Trading, Express Trades y Tournaments', caption: 'Signals es el primer elemento de la barra lateral derecha del terminal.' },
        { type: 'p', text: 'Haz clic en Signals en la barra lateral derecha y verás una lista de activos con dirección (Arriba/Abajo), un indicador de fuerza y un horizonte temporal (por ejemplo 1 minuto, 5 minutos, 30 minutos). Las señales se generan automáticamente a partir de indicadores técnicos como medias móviles, RSI y MACD — resumen la tendencia actual, no predicen el futuro. Son gratuitas, se actualizan en tiempo real y están disponibles en demo y cuenta real.' },
        { type: 'table', head: ['Elemento', 'Qué muestra', 'Cómo usarlo'], rows: [
          ['Dirección', 'Tendencia dominante en el horizonte elegido', 'Opera solo en la dirección de la señal en el mismo timeframe o uno mayor'],
          ['Fuerza', 'Cuántos indicadores coinciden', 'Prefiere señales fuertes; descarta las débiles o mixtas'],
          ['Horizonte', 'Timeframe al que se refiere la señal', 'Ajusta tu expiración — una señal de 5 minutos no es para operaciones de 5 segundos'],
          ['Payout del activo', 'Se muestra junto al activo', 'Descarta señales en activos por debajo de tu payout mínimo (75–80%)'],
        ] },
        { type: 'tip', title: 'Confirma con el gráfico', text: 'Abre el activo, mira las últimas 20–30 velas y el soporte/resistencia más cercano. Si la señal dice Arriba pero el precio está justo debajo de una resistencia fuerte, espera la ruptura o descártala. Las señales confirman tu análisis; no lo sustituyen.' },
        { type: 'image', src: IMG_ARROWS, alt: 'Gráfico de Pocket Option con flechas de señal alcistas y bajistas en las velas', caption: 'Las flechas de señal en el gráfico marcan velas donde los indicadores coincidieron — comprueba siempre el contexto alrededor.' },
        { type: 'h2', id: 'telegram', text: 'Señales de Telegram y canales de pago' },
        { type: 'p', text: 'Cientos de canales de Telegram venden “señales VIP Pocket Option”. No están conectados con la plataforma. El modelo de negocio suele ser: suscripción mensual, enlace de afiliado con el que el canal gana con tus depósitos, o venta de “gestión de cuenta”. Algunos son analistas honestos con una ventaja modesta; muchos son máquinas de marketing. Señales de alarma de un mal canal:' },
        { type: 'ul', items: [
          'Solo capturas ganadoras, nunca un registro diario completo con pérdidas.',
          'Afirmaciones de 90–98% de precisión — los traders binarios excelentes están realistamente en 60–65%.',
          'Presión para depositar por su enlace o entregar tu login.',
          'Instrucciones de “recuperación” martingala tras una pérdida (doblar el importe hasta ganar).',
          'Señales con expiración de 5–30 segundos — nadie puede señalar ese horizonte de forma fiable a mano.',
        ] },
        { type: 'warn', title: 'Nunca compartas tu login ni dejes que nadie “gestione” tu cuenta', text: 'Pocket Option, como todo bróker, prohíbe la gestión de cuentas por terceros. Los estafadores que reciben tu contraseña vacían el saldo o aplican martingala hasta agotar la cuenta y desaparecen. Ningún proveedor legítimo de señales necesita tus credenciales.' },
        { type: 'h2', id: 'bots', text: 'Bots, robots y “señales de IA”' },
        { type: 'p', text: 'Los bots automáticos afirman leer el gráfico y operar por ti. Algunos funcionan como extensiones del navegador, otros como apps que piden tu sesión de Pocket Option. Tres cosas que debes saber: primero, la automatización no autorizada puede violar las reglas de la plataforma y provocar restricciones en la cuenta; segundo, la mayoría de bots son simples cruces de indicadores con una interfaz vistosa, cuyos resultados se derrumban en cuanto cambia la volatilidad; tercero, un bot con tus credenciales tiene los mismos riesgos que la gestión de cuenta anterior. La propia Pocket Option ofrece herramientas integradas — señales, social trading, express trades — dentro de las reglas; úsalas en lugar de automatización de terceros.' },
        { type: 'h2', id: 'test', text: 'Cómo probar cualquier fuente de señales con honestidad' },
        { type: 'ol', items: [
          'Abre una cuenta demo y elige una fuente de señales (panel integrado, canal, bot).',
          'Sigue cada señal exactamente como se da — mismo activo, dirección, expiración — durante al menos 100 señales o dos semanas.',
          'Registra cada resultado en una hoja de cálculo: fecha, activo, dirección, expiración, payout, ganancia/pérdida.',
          'Calcula la tasa de acierto y compárala con el punto de equilibrio del payout medio: 52,1% al 92%, 55,6% al 80%, 58,8% al 70%.',
          'Solo si la tasa se mantiene por encima del equilibrio con margen (unos 5 puntos) en toda la muestra, considera dinero real — con operaciones de $1–$2 primero.',
        ] },
        { type: 'image', src: IMG_CANDLES, alt: 'Explicación de gráfico de velas con velas alcistas y bajistas', caption: 'Entender las velas por ti mismo es el mejor filtro para cualquier señal — notarás cuándo una señal contradice la acción del precio.' },
        { type: 'h2', id: 'filter', text: 'Un filtro simple que mejora la mayoría de señales' },
        { type: 'p', text: 'Incluso las señales mediocres son más útiles cuando las filtras. Toma una señal solo si se cumple todo lo siguiente:' },
        { type: 'ul', items: [
          'El payout del activo está en tu mínimo o por encima (75–80%).',
          'La dirección coincide con la tendencia en un timeframe superior (p. ej. señal en 1 minuto, tendencia en 5–15 minutos).',
          'El precio no está pegado a un soporte o resistencia fuerte en contra de la dirección de la señal.',
          'No hay noticias de alto impacto programadas para esa divisa en los próximos 15 minutos.',
          'Aún no has alcanzado tu límite diario de pérdidas (p. ej. 3 pérdidas o 5% del saldo).',
        ] },
        { type: 'p', text: 'Espera descartar más de la mitad de las señales. Esa es la idea — las que tomas son las que tienen varios factores a tu favor.' },
        { type: 'h2', id: 'compare', text: 'Señales vs social trading vs estrategia propia' },
        { type: 'table', head: ['Enfoque', 'Coste', 'Control', 'Ideal para'], rows: [
          ['Señales integradas', 'Gratis', 'Total — tú decides cada operación', 'Principiantes aprendiendo a leer tendencias'],
          ['Señales de Telegram', 'Gratis o $30–$200/mes', 'Medio — sigues el timing de otro', 'Traders que quieren ideas pero las verificarán'],
          ['Bots / apps de IA', 'A menudo de pago, más tu riesgo', 'Bajo — el software opera', 'No recomendado; riesgos de reglas y seguridad'],
          ['Social trading', 'Gratis (copia desde $1)', 'Medio — copia automática con tus límites', 'Saldos pequeños que quieren aprender de los mejores'],
          ['Estrategia propia', 'Tiempo', 'Total', 'Trading consistente a largo plazo'],
        ] },
        { type: 'cta', text: 'Prueba las señales integradas gratis: abre una cuenta demo, activa el panel Signals y prueba el filtro anterior antes de arriesgar un solo dólar.', label: 'Abrir cuenta demo gratis' },
      ],
      faq: [
        { q: '¿Pocket Option tiene señales gratuitas?', a: 'Sí. El panel Signals del terminal es gratuito y muestra dirección, fuerza y horizonte de la tendencia de cada activo, en demo y cuenta real.' },
        { q: '¿Son precisas las señales de Telegram de Pocket Option?', a: 'Varían mucho y no están afiliadas a la plataforma. Prueba cualquier canal en demo durante al menos 100 señales y compara la tasa de acierto con el equilibrio del payout antes de confiar.' },
        { q: '¿Están permitidos los bots de señales en Pocket Option?', a: 'La automatización de terceros no está oficialmente soportada y puede violar las reglas; además exige compartir tu sesión o credenciales, un riesgo de seguridad. Usa las herramientas integradas.' },
        { q: '¿Qué tasa de acierto necesitan las señales para ser rentables?', a: 'Por encima del equilibrio de tu payout medio: cerca del 52% con payout del 92%, 56% con 80% y 59% con 70%. Apunta a al menos 5 puntos por encima.' },
        { q: '¿Puedo operar solo con señales?', a: 'Puedes, pero los resultados suelen ser mejores cuando las señales se filtran con tu propio análisis de tendencia, niveles, payout y noticias.' },
        { q: '¿Debo pagar por señales VIP?', a: 'Solo después de que una prueba documentada en demo demuestre la ventaja del canal. Evita cualquier canal que prometa precisión garantizada, pida tu login o recomiende martingala.' },
      ],
    },
    ru: {
      title: 'Сигналы Pocket Option: встроенные сигналы, Telegram-каналы и боты — что работает, а чего избегать',
      metaTitle: 'Сигналы Pocket Option – встроенные, Telegram и боты',
      metaDescription:
        'Как работают сигналы Pocket Option: встроенная панель Signals, платные Telegram-каналы, бесплатные боты и ИИ-сигналы — как тестировать на демо, фильтровать и не попасть на мошенников.',
      excerpt:
        'Реалистичный гайд по торговым сигналам pocketoption: что показывает панель Signals в терминале, как оценивать сторонние Telegram-сигналы и боты, и фильтр, отделяющий полезные сигналы от шума.',
      coverAlt: 'Торговый терминал Pocket Option со свечным графиком — сигналы показаны в правой панели',
      keyTakeaways: [
        'В терминале Pocket Option есть бесплатная панель Signals с направлением, силой и горизонтом тренда по каждому активу — это отправная точка, а не инструкция к сделке.',
        'Сторонние Telegram-сигналы, боты и приложения с «ИИ-сигналами» не связаны с платформой; большинство публикует только выигрышные скриншоты и скрывает серии убытков.',
        'Тестируйте любой источник сигналов на демо минимум на 100 сигналах и сравнивайте винрейт с безубытком по выплате (52–56%).',
        'Используйте сигналы как фильтр, а не триггер: берите только те, что согласуются с вашим анализом тренда, уровней и сессии.',
        'Никогда не платите за сигналы с обещанием «гарантированных 90% точности», не передавайте логин и не давайте боту торговать реальным балансом, который не можете потерять.',
      ],
      blocks: [
        { type: 'p', text: '«Сигналы Pocket Option» — один из самых частых запросов о платформе и один из самых злоупотребляемых. Под этим термином скрываются три очень разные вещи: бесплатная панель Signals, встроенная в терминал pocketoption, платные или бесплатные Telegram-каналы третьих лиц и автоматические боты или «ИИ»-приложения, обещающие торговать за вас. В этом гайде разбираем, что представляет собой каждый вариант, как честно протестировать его на демо и как распознать мошенников, из-за которых новички теряют первый депозит.' },
        { type: 'h2', id: 'builtin', text: 'Встроенная панель Signals на Pocket Option' },
        { type: 'image', src: IMG_PANEL, alt: 'Правая панель терминала Pocket Option: Signals, Social Trading, Express Trades, Tournaments', caption: 'Signals — первый пункт правой панели терминала.' },
        { type: 'p', text: 'Нажмите Signals в правой панели терминала — откроется список активов с направлением (вверх/вниз), индикатором силы и горизонтом времени (например, 1 минута, 5 минут, 30 минут). Сигналы формируются автоматически на основе технических индикаторов — скользящих средних, RSI, MACD; они обобщают текущий тренд, а не предсказывают будущее. Они бесплатны, обновляются в реальном времени и доступны на демо и реальном счёте.' },
        { type: 'table', head: ['Элемент', 'Что показывает', 'Как использовать'], rows: [
          ['Направление', 'Доминирующий тренд на выбранном горизонте', 'Торгуйте только по направлению сигнала на том же или большем таймфрейме'],
          ['Сила', 'Сколько индикаторов согласны', 'Предпочитайте сильные сигналы; слабые и смешанные пропускайте'],
          ['Горизонт', 'Таймфрейм, к которому относится сигнал', 'Подбирайте экспирацию — 5-минутный сигнал не для 5-секундных сделок'],
          ['Выплата по активу', 'Показана рядом с активом', 'Пропускайте сигналы по активам ниже вашей минимальной выплаты (75–80%)'],
        ] },
        { type: 'tip', title: 'Подтверждайте графиком', text: 'Откройте актив, посмотрите последние 20–30 свечей и ближайшие поддержку/сопротивление. Если сигнал говорит «вверх», а цена прямо под сильным сопротивлением — ждите пробоя или пропустите. Сигналы подтверждают ваш анализ, а не заменяют его.' },
        { type: 'image', src: IMG_ARROWS, alt: 'График Pocket Option со стрелками сигналов вверх и вниз на свечах', caption: 'Стрелки сигналов на графике отмечают свечи, где индикаторы совпали — всегда проверяйте контекст вокруг.' },
        { type: 'h2', id: 'telegram', text: 'Telegram-сигналы и платные каналы' },
        { type: 'p', text: 'Сотни Telegram-каналов продают «VIP-сигналы Pocket Option». С платформой они не связаны. Бизнес-модель обычно одна из трёх: месячная подписка, партнёрская ссылка, по которой канал зарабатывает с ваших депозитов, или продажа «управления счётом». Кто-то — честный аналитик со скромным преимуществом, но многие — маркетинговые машины. Признаки плохого канала:' },
        { type: 'ul', items: [
          'Только выигрышные скриншоты, никогда — полная дневная статистика с убытками.',
          'Заявления о точности 90–98% — реально отличные бинарные трейдеры держатся в районе 60–65%.',
          'Давление: депозит только по их ссылке или передача логина.',
          'Инструкции по «отбиванию» мартингейлом после убытка (удваивать сумму до выигрыша).',
          'Сигналы с экспирацией 5–30 секунд — такой горизонт никто не может надёжно сигналить вручную.',
        ] },
        { type: 'warn', title: 'Никогда не передавайте логин и не разрешайте «управлять» счётом', text: 'Pocket Option, как и любой брокер, запрещает управление счётом третьими лицами. Мошенники, получившие ваш пароль, либо выводят баланс, либо крутят мартингейл до нуля и исчезают. Легитимному поставщику сигналов ваши учётные данные не нужны.' },
        { type: 'h2', id: 'bots', text: 'Боты, роботы и «ИИ-сигналы»' },
        { type: 'p', text: 'Автоматические боты заявляют, что читают график и открывают сделки за вас. Одни работают как расширения браузера, другие — как приложения, запрашивающие вашу сессию Pocket Option. Три факта: во-первых, неавторизованная автоматизация может нарушать правила платформы и привести к ограничениям аккаунта; во-вторых, большинство ботов — простое пересечение индикаторов в красивой обёртке, результаты которого рассыпаются при смене волатильности; в-третьих, бот с вашими данными несёт те же риски, что и «управление счётом» выше. У Pocket Option есть собственные инструменты — сигналы, социальный трейдинг, экспресс-сделки — в рамках правил; используйте их вместо сторонней автоматизации.' },
        { type: 'h2', id: 'test', text: 'Как честно протестировать любой источник сигналов' },
        { type: 'ol', items: [
          'Откройте демо-счёт и выберите один источник (встроенная панель, канал, бот).',
          'Следуйте каждому сигналу точно как дан — тот же актив, направление, экспирация — минимум 100 сигналов или две недели.',
          'Фиксируйте каждый результат в таблице: дата, актив, направление, экспирация, выплата, выигрыш/проигрыш.',
          'Посчитайте винрейт и сравните с безубытком для средней выплаты: 52,1% при 92%, 55,6% при 80%, 58,8% при 70%.',
          'Только если винрейт держится выше безубытка с запасом (около 5 п.п.) на всей выборке — рассматривайте реальные деньги, сначала сделками по $1–$2.',
        ] },
        { type: 'image', src: IMG_CANDLES, alt: 'Объяснение свечного графика с бычьими и медвежьими свечами', caption: 'Умение самостоятельно читать свечи — лучший фильтр для любого сигнала: вы заметите, когда сигнал противоречит движению цены.' },
        { type: 'h2', id: 'filter', text: 'Простой фильтр, улучшающий большинство сигналов' },
        { type: 'p', text: 'Даже средние сигналы становятся полезнее с фильтром. Берите сигнал, только если выполняется всё перечисленное:' },
        { type: 'ul', items: [
          'Выплата по активу не ниже вашего минимума (75–80%).',
          'Направление совпадает с трендом на старшем таймфрейме (например, сигнал на 1 минуте, тренд на 5–15 минутах).',
          'Цена не стоит вплотную к сильной поддержке/сопротивлению против направления сигнала.',
          'В ближайшие 15 минут нет важных новостей по этой валюте.',
          'Вы ещё не достигли дневного лимита убытков (например, 3 убытка или 5% баланса).',
        ] },
        { type: 'p', text: 'Готовьтесь пропускать больше половины сигналов. В этом и смысл — те, что вы берёте, имеют несколько факторов в вашу пользу.' },
        { type: 'h2', id: 'compare', text: 'Сигналы vs социальный трейдинг vs собственная стратегия' },
        { type: 'table', head: ['Подход', 'Стоимость', 'Контроль', 'Кому подходит'], rows: [
          ['Встроенные сигналы', 'Бесплатно', 'Полный — вы решаете каждую сделку', 'Новичкам, учащимся читать тренды'],
          ['Telegram-сигналы', 'Бесплатно или $30–$200/мес', 'Средний — вы следуете чужому таймингу', 'Тем, кто хочет идеи, но будет их проверять'],
          ['Боты / ИИ-приложения', 'Часто платно, плюс ваш риск', 'Низкий — торгует программа', 'Не рекомендуется; риски правил и безопасности'],
          ['Социальный трейдинг', 'Бесплатно (копирование от $1)', 'Средний — автокопирование с вашими лимитами', 'Небольшим балансам, желающим учиться у топ-трейдеров'],
          ['Собственная стратегия', 'Время', 'Полный', 'Стабильная долгосрочная торговля'],
        ] },
        { type: 'cta', text: 'Попробуйте встроенные сигналы бесплатно: откройте демо-счёт, включите панель Signals и протестируйте фильтр выше, не рискуя ни долларом.', label: 'Открыть бесплатный демо-счёт' },
      ],
      faq: [
        { q: 'Есть ли у Pocket Option бесплатные сигналы?', a: 'Да. Панель Signals в терминале бесплатна и показывает направление, силу и горизонт тренда по каждому активу на демо и реальном счёте.' },
        { q: 'Точны ли Telegram-сигналы Pocket Option?', a: 'Они сильно различаются и не связаны с платформой. Тестируйте любой канал на демо минимум на 100 сигналах и сравнивайте винрейт с безубытком по выплате, прежде чем доверять.' },
        { q: 'Разрешены ли боты для сигналов на Pocket Option?', a: 'Сторонняя автоматизация официально не поддерживается и может нарушать правила; она также требует передачи сессии или учётных данных, что небезопасно. Используйте встроенные инструменты.' },
        { q: 'Какой винрейт нужен сигналам для прибыльности?', a: 'Выше безубытка для вашей средней выплаты: около 52% при выплате 92%, 56% при 80% и 59% при 70%. Целитесь минимум на 5 пунктов выше.' },
        { q: 'Можно ли торговать только по сигналам?', a: 'Можно, но результаты обычно лучше, когда сигналы фильтруются вашим анализом тренда, уровней, выплаты и новостей.' },
        { q: 'Стоит ли платить за VIP-сигналы?', a: 'Только после задокументированного теста на демо, подтверждающего преимущество канала. Избегайте каналов, обещающих гарантированную точность, просящих логин или рекомендующих мартингейл.' },
      ],
    },
    id: {
      title: 'Sinyal Pocket Option: sinyal bawaan, channel Telegram, dan bot — mana yang berguna dan mana yang harus dihindari',
      metaTitle: 'Sinyal Pocket Option – Bawaan, Telegram & Bot Dijelaskan',
      metaDescription:
        'Cara kerja sinyal Pocket Option: panel Signals bawaan, channel Telegram berbayar, bot gratis, dan sinyal AI — cara mengujinya di demo, menyaringnya, dan menghindari penipuan.',
      excerpt:
        'Panduan realistis sinyal trading pocketoption: apa yang ditampilkan panel Signals di terminal, cara menilai sinyal Telegram dan bot pihak ketiga, plus filter yang memisahkan sinyal berguna dari noise.',
      coverAlt: 'Terminal trading Pocket Option dengan grafik candlestick — sinyal ditampilkan di sidebar kanan',
      keyTakeaways: [
        'Pocket Option punya panel Signals gratis di terminal yang menampilkan arah, kekuatan, dan horizon tren tiap aset — titik awal, bukan instruksi trade.',
        'Sinyal Telegram, bot, dan aplikasi “sinyal AI” pihak ketiga tidak berafiliasi dengan platform; kebanyakan hanya memposting screenshot menang dan menyembunyikan rentetan kalah.',
        'Uji sumber sinyal apa pun di demo minimal 100 sinyal dan catat win rate dibanding titik impas payout (52–56%).',
        'Gunakan sinyal sebagai filter, bukan pemicu: ambil hanya yang sejalan dengan analisis Anda sendiri soal tren, support/resistance, dan sesi.',
        'Jangan pernah bayar sinyal dengan janji “akurasi 90% terjamin”, jangan bagikan login, dan jangan biarkan bot trading saldo riil yang tidak sanggup Anda rugikan.',
      ],
      blocks: [
        { type: 'p', text: '“Sinyal Pocket Option” adalah salah satu frasa paling banyak dicari seputar platform ini — dan salah satu yang paling disalahgunakan. Istilah ini mencakup tiga hal sangat berbeda: panel Signals gratis yang terpasang di terminal pocketoption, channel Telegram berbayar atau gratis milik pihak ketiga, dan bot otomatis atau aplikasi “AI” yang menjanjikan trading untuk Anda. Panduan ini menjelaskan apa itu masing-masing, cara mengujinya secara jujur di akun demo, dan cara mengenali penipuan yang membuat pemula kehilangan deposit pertama.' },
        { type: 'h2', id: 'builtin', text: 'Panel Signals bawaan di Pocket Option' },
        { type: 'image', src: IMG_PANEL, alt: 'Sidebar kanan terminal Pocket Option dengan Signals, Social Trading, Express Trades, dan Tournaments', caption: 'Signals adalah item pertama di sidebar kanan terminal.' },
        { type: 'p', text: 'Klik Signals di sidebar kanan terminal dan Anda akan melihat daftar aset dengan arah (Up/Down), indikator kekuatan, dan horizon waktu (misalnya 1 menit, 5 menit, 30 menit). Sinyal dihasilkan otomatis dari indikator teknikal seperti moving average, RSI, dan MACD — merangkum tren saat ini, bukan memprediksi masa depan. Gratis, diperbarui real time, dan tersedia di akun demo maupun riil.' },
        { type: 'table', head: ['Elemen', 'Yang ditampilkan', 'Cara memakainya'], rows: [
          ['Arah', 'Tren dominan pada horizon yang dipilih', 'Trading hanya searah sinyal pada timeframe sama atau lebih panjang'],
          ['Kekuatan', 'Berapa banyak indikator yang sepakat', 'Utamakan sinyal kuat; lewati yang lemah atau campuran'],
          ['Horizon', 'Timeframe yang dirujuk sinyal', 'Sesuaikan expiry — sinyal 5 menit bukan untuk trade 5 detik'],
          ['Payout aset', 'Tampil di samping aset', 'Lewati sinyal di aset di bawah payout minimum Anda (75–80%)'],
        ] },
        { type: 'tip', title: 'Konfirmasi dengan grafik', text: 'Buka aset, lihat 20–30 candle terakhir dan support/resistance terdekat. Jika sinyal bilang Up tetapi harga tepat di bawah resistance kuat, tunggu breakout atau lewati. Sinyal mengonfirmasi analisis Anda; bukan menggantikannya.' },
        { type: 'image', src: IMG_ARROWS, alt: 'Grafik Pocket Option dengan panah sinyal naik dan turun pada candle', caption: 'Panah sinyal di grafik menandai candle saat indikator selaras — selalu periksa konteks di sekitarnya.' },
        { type: 'h2', id: 'telegram', text: 'Sinyal Telegram dan channel berbayar' },
        { type: 'p', text: 'Ratusan channel Telegram menjual “sinyal VIP Pocket Option”. Mereka tidak terhubung dengan platform. Model bisnisnya biasanya salah satu dari: langganan bulanan, link afiliasi di mana channel dapat komisi dari deposit Anda, atau upsell ke “manajemen akun”. Ada analis jujur dengan edge kecil; banyak yang hanya mesin marketing. Tanda channel buruk:' },
        { type: 'ul', items: [
          'Hanya screenshot menang, tidak pernah catatan harian lengkap termasuk kalah.',
          'Klaim akurasi 90–98% — trader biner yang benar-benar hebat realistisnya di sekitar 60–65%.',
          'Desakan deposit lewat link mereka atau menyerahkan login Anda.',
          'Instruksi “recovery” martingale setelah kalah (gandakan nominal sampai menang).',
          'Sinyal dengan expiry 5–30 detik — tidak ada yang bisa memberi sinyal horizon itu secara andal dengan tangan.',
        ] },
        { type: 'warn', title: 'Jangan pernah bagikan login atau biarkan orang lain “mengelola” akun Anda', text: 'Pocket Option, seperti semua broker, melarang pengelolaan akun oleh pihak ketiga. Penipu yang menerima password Anda akan menguras saldo atau menjalankan martingale sampai akun kosong, lalu menghilang. Penyedia sinyal yang sah tidak butuh kredensial Anda.' },
        { type: 'h2', id: 'bots', text: 'Bot, robot, dan “sinyal AI”' },
        { type: 'p', text: 'Bot otomatis mengklaim bisa membaca grafik dan membuka trade untuk Anda. Ada yang berjalan sebagai ekstensi browser, ada yang berupa aplikasi yang meminta sesi Pocket Option Anda. Tiga hal yang perlu diketahui: pertama, otomatisasi tanpa izin bisa melanggar aturan platform dan berujung pembatasan akun; kedua, kebanyakan bot hanyalah crossover indikator sederhana berbalut antarmuka mengilap, dengan hasil yang runtuh saat volatilitas berubah; ketiga, bot dengan kredensial Anda memiliki risiko yang sama dengan manajemen akun di atas. Pocket Option sendiri menyediakan alat bawaan — sinyal, social trading, express trades — yang tetap sesuai aturan; gunakan itu alih-alih otomatisasi pihak ketiga.' },
        { type: 'h2', id: 'test', text: 'Cara menguji sumber sinyal apa pun secara jujur' },
        { type: 'ol', items: [
          'Buka akun demo dan pilih satu sumber sinyal (panel bawaan, channel, bot).',
          'Ikuti setiap sinyal persis seperti diberikan — aset, arah, expiry yang sama — minimal 100 sinyal atau dua minggu.',
          'Catat setiap hasil di spreadsheet: tanggal, aset, arah, expiry, payout, menang/kalah.',
          'Hitung win rate dan bandingkan dengan titik impas payout rata-rata: 52,1% pada 92%, 55,6% pada 80%, 58,8% pada 70%.',
          'Hanya jika win rate tetap di atas impas plus margin (sekitar 5 poin) di seluruh sampel, pertimbangkan uang riil — dengan trade $1–$2 dulu.',
        ] },
        { type: 'image', src: IMG_CANDLES, alt: 'Penjelasan grafik candlestick dengan candle bullish dan bearish', caption: 'Memahami candle sendiri adalah filter terbaik untuk sinyal apa pun — Anda akan tahu saat sinyal bertentangan dengan price action.' },
        { type: 'h2', id: 'filter', text: 'Filter sederhana yang memperbaiki kebanyakan sinyal' },
        { type: 'p', text: 'Bahkan sinyal rata-rata menjadi lebih berguna saat difilter. Ambil sinyal hanya jika semua berikut terpenuhi:' },
        { type: 'ul', items: [
          'Payout aset berada di atau di atas minimum Anda (75–80%).',
          'Arahnya sesuai tren di timeframe lebih tinggi (misalnya sinyal di 1 menit, tren di 5–15 menit).',
          'Harga tidak tepat di support atau resistance kuat yang berlawanan dengan arah sinyal.',
          'Tidak ada berita berdampak tinggi untuk mata uang itu dalam 15 menit ke depan.',
          'Anda belum mencapai batas rugi harian (misalnya 3 kali kalah atau 5% saldo).',
        ] },
        { type: 'p', text: 'Bersiaplah melewatkan lebih dari separuh sinyal. Itulah tujuannya — yang Anda ambil adalah yang punya beberapa faktor menguntungkan.' },
        { type: 'h2', id: 'compare', text: 'Sinyal vs social trading vs strategi sendiri' },
        { type: 'table', head: ['Pendekatan', 'Biaya', 'Kontrol', 'Cocok untuk'], rows: [
          ['Sinyal bawaan', 'Gratis', 'Penuh — Anda memutuskan setiap trade', 'Pemula yang belajar membaca tren'],
          ['Sinyal Telegram', 'Gratis atau $30–$200/bulan', 'Sedang — Anda mengikuti timing orang lain', 'Trader yang ingin ide tapi akan memverifikasinya'],
          ['Bot / aplikasi AI', 'Sering berbayar, plus risiko Anda', 'Rendah — software yang trading', 'Tidak disarankan; risiko aturan dan keamanan'],
          ['Social trading', 'Gratis (copy mulai $1)', 'Sedang — copy otomatis dengan batas Anda', 'Saldo kecil yang ingin belajar dari trader top'],
          ['Strategi sendiri', 'Waktu', 'Penuh', 'Trading konsisten jangka panjang'],
        ] },
        { type: 'cta', text: 'Coba sinyal bawaan gratis: buka akun demo, aktifkan panel Signals, dan uji filter di atas sebelum mempertaruhkan satu dolar pun.', label: 'Buka akun demo gratis' },
      ],
      faq: [
        { q: 'Apakah Pocket Option punya sinyal gratis?', a: 'Ya. Panel Signals di terminal gratis dan menampilkan arah, kekuatan, dan horizon tren tiap aset, di akun demo maupun riil.' },
        { q: 'Apakah sinyal Telegram Pocket Option akurat?', a: 'Sangat bervariasi dan tidak berafiliasi dengan platform. Uji channel apa pun di demo minimal 100 sinyal dan bandingkan win rate dengan impas payout sebelum mempercayainya.' },
        { q: 'Apakah bot sinyal diizinkan di Pocket Option?', a: 'Otomatisasi pihak ketiga tidak didukung resmi dan bisa melanggar aturan; juga mengharuskan berbagi sesi atau kredensial, yang berisiko keamanan. Gunakan alat bawaan.' },
        { q: 'Win rate berapa yang dibutuhkan sinyal agar profit?', a: 'Di atas titik impas payout rata-rata Anda: sekitar 52% pada payout 92%, 56% pada 80%, dan 59% pada 70%. Targetkan minimal 5 poin di atasnya.' },
        { q: 'Bisakah trading hanya dengan sinyal?', a: 'Bisa, tetapi hasilnya biasanya lebih baik saat sinyal difilter dengan analisis Anda sendiri soal tren, level, payout, dan berita.' },
        { q: 'Haruskah saya bayar sinyal VIP?', a: 'Hanya setelah uji demo terdokumentasi membuktikan edge channel tersebut. Hindari channel yang menjanjikan akurasi terjamin, meminta login, atau merekomendasikan martingale.' },
      ],
    },
  },
};
