import type { BlogPost } from '../types';

const IMG_PROMO_PAGE = '/images/blog/po-promo-codes-page.webp';
const IMG_DEPOSIT = '/images/blog/po-deposit-page.webp';
const IMG_REG_PANEL = '/images/blog/po-registration-panel.webp';

export const pocketOptionPromoCode: BlogPost = {
  slug: 'pocket-option-promo-code',
  category: 'payments',
  cover: '/images/blog/pocket-option-promo-code.webp',
  publishedAt: '2026-09-26',
  updatedAt: '2026-09-26',
  readingMinutes: 8,
  author: 'Pocket Option Guide Team',
  content: {
    en: {
      title: 'Pocket Option promo code 2026: 50START bonus, how to activate it and the rules',
      metaTitle: 'Pocket Option Promo Code 2026 – 50START Bonus & How to Use',
      metaDescription:
        'Pocket Option promo code guide: the official 50START code (+50% on first deposit), where to enter it, deposit bonus rules, turnover requirements and Gems market codes.',
      excerpt:
        'How pocketoption promo codes work: the 50START welcome bonus, activation at registration or deposit, turnover rules and when a bonus is not worth it.',
      coverAlt: 'Pocket Option promo codes — tickets with the 50START code and gold coins',
      keyTakeaways: [
        'The official Pocket Option welcome promo code is 50START: +50% on a first deposit from $50 (e.g. $50 → $75 balance).',
        'Enter the code in the “Promo code” field at registration or on the deposit page before paying — it cannot be applied afterwards.',
        'Bonus funds require a trading turnover before the bonus portion can be withdrawn; your own deposit is not locked.',
        'Extra codes (20–110% deposit bonus, cashback, risk-free trades) can be bought with Gems in the platform Market.',
        'Skip the bonus if you plan to withdraw quickly or trade small — the turnover rule may not suit you.',
      ],
      blocks: [
        { type: 'p', text: 'A Pocket Option promo code adds bonus money to your deposit — the most popular one, 50START, gives +50% on a first deposit. It sounds simple, but many withdrawal complaints start with a bonus that was accepted without reading the terms. This guide explains the current pocketoption codes, exactly where to enter them, the turnover rules, and how to decide whether a bonus is a good idea for you.' },
        { type: 'h2', id: 'codes', text: 'Current Pocket Option promo codes' },
        { type: 'table', head: ['Code / bonus', 'What you get', 'Conditions'], rows: [
          ['50START', '+50% on your first deposit', 'Deposit from $50; first deposit only; enter before paying'],
          ['Deposit bonus 20–110%', 'Percentage added to a deposit of $50+', 'Bought with Gems in the Market; applies to the next deposit'],
          ['Cashback 2–10%', 'Part of losing trades returned monthly', 'Bought with Gems; valid one year'],
          ['Risk-free trade', 'Cancel one losing trade and get the amount back', 'Bought with Gems; activate in Market → Purchases'],
          ['Balance bonus $5–$100', 'Instant credit to real balance', 'Exchanged for Gems; no turnover required'],
        ] },
        { type: 'p', text: 'Codes tied to promotions (city-themed, sport-themed, anniversary offers) appear from time to time in Chat → Notifications → Promo inside the platform and on the official blog. They change quickly, so treat any “secret 200% code” you see on third-party sites with suspicion — if it is not shown inside your account, it will not work.' },
        { type: 'h2', id: 'register', text: 'Method 1: enter the promo code at registration' },
        { type: 'image', src: IMG_REG_PANEL, alt: 'Pocket Option registration panel with e-mail, password and promo code fields', caption: 'The registration form has a dedicated “Promo code” field.' },
        { type: 'ol', items: [
          'Open the Pocket Option registration form (e-mail + password).',
          'Type 50START in the “Promo code” field — no spaces, capital letters.',
          'Accept the public offer agreement and click Sign up.',
          'Confirm your e-mail. The bonus is attached to your profile and will be offered on your first deposit.',
        ] },
        { type: 'h2', id: 'deposit', text: 'Method 2: activate the code on the deposit page' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Pocket Option deposit page showing the limited-offer bonus block', caption: 'Finance → Deposit: the bonus offer is displayed above the payment methods.' },
        { type: 'ol', items: [
          'Log in and open Finance → Deposit.',
          'Choose a payment method and enter an amount of at least $50 (the bonus minimum).',
          'Click “Have a promo code?” / the promo field and paste 50START, or select the offered bonus block.',
          'Check that the summary shows the bonus (e.g. $50 + $25 bonus).',
          'Pay. The bonus is credited together with the deposit.',
        ] },
        { type: 'warn', title: 'Enter the code before paying', text: 'A promo code cannot be applied to a deposit that has already been made. If you forgot the code, the only option is to use it on the next deposit — and 50START is valid for the first deposit only.' },
        { type: 'h2', id: 'market', text: 'Where to find more codes: Gems and the Market' },
        { type: 'image', src: IMG_PROMO_PAGE, alt: 'Pocket Option promo codes page with available codes and activation button', caption: 'Profile → Promo codes: see available codes, check a code and activate it.' },
        { type: 'p', text: 'Pocket Option has a loyalty system based on Gems (crystals). You earn Gems by trading, completing achievements, taking part in the lottery, copying trades with a Mining licence or selling items in the Market. In the Market you can exchange Gems for deposit-bonus codes (20% to 110%), cashback, risk-free trades or an instant balance bonus. Purchased codes appear in Profile → Promo codes, where you can check and activate them.' },
        { type: 'h2', id: 'rules', text: 'Bonus rules: turnover and withdrawals' },
        { type: 'p', text: 'The key rule: bonus money is not withdrawable until you trade a certain turnover (the total volume of trades) — typically a multiple of the bonus amount, stated in the bonus terms before activation. Your own deposited funds are never locked and can be withdrawn at any time; if you withdraw before completing the turnover, the unused bonus is simply cancelled. Profit made with bonus funds counts as real money once the turnover is met.' },
        { type: 'ul', items: [
          'Read the exact turnover multiplier in the bonus pop-up before confirming.',
          'Trades on demo and cancelled/refunded trades do not count towards turnover.',
          'One bonus per deposit; you cannot stack two percentage codes.',
          'Bonuses can be changed or withdrawn by the platform at any time — check the current offer in your account.',
        ] },
        { type: 'h2', id: 'worth', text: 'Is the Pocket Option bonus worth taking?' },
        { type: 'p', text: 'Take the bonus if you plan to trade actively for weeks and a larger balance helps you follow your risk-management rules (e.g. 2% per trade). Skip it if you want to test the platform with a quick deposit-trade-withdraw cycle, if you deposit less than $50, or if you dislike any restriction on when you can withdraw profits. There is no bonus on the demo account — practice there first.' },
        { type: 'tip', title: 'Our recommendation for a first deposit', text: 'Deposit $5–$20 without a bonus, make a few $1 trades and withdraw. Once you are happy with the process, make a second, larger deposit and decide about the bonus then.' },
        { type: 'cta', text: 'Ready to register? Use the promo code 50START at sign-up to keep the +50% first-deposit bonus available.', label: 'Register on Pocket Option' },
      ],
      faq: [
        { q: 'What is the current Pocket Option promo code?', a: 'The official welcome code is 50START — +50% on a first deposit of $50 or more. Other codes are available for Gems in the platform Market.' },
        { q: 'Where do I enter the promo code?', a: 'In the “Promo code” field of the registration form, or on the deposit page (Finance → Deposit) before completing the payment.' },
        { q: 'Can I add a promo code after depositing?', a: 'No. Bonuses apply only to deposits made after the code is entered.' },
        { q: 'Can I withdraw the bonus?', a: 'The bonus part becomes withdrawable after you complete the required trading turnover. Your own deposit is not locked.' },
        { q: 'Is there a no-deposit bonus?', a: 'Not in cash. The $50,000 demo account is free, and small balance bonuses ($5–$100) can be exchanged for Gems earned on the platform.' },
        { q: 'Are promo codes on other websites real?', a: 'Only codes shown inside your account, on the official blog or in official channels work. Treat “exclusive 200%” codes from unknown sites as unreliable.' },
      ],
    },
    pt: {
      title: 'Código promocional Pocket Option 2026: bônus 50START, como ativar e regras',
      metaTitle: 'Código Promocional Pocket Option 2026 – Bônus 50START',
      metaDescription:
        'Guia do código promocional Pocket Option: código oficial 50START (+50% no primeiro depósito), onde inserir, regras do bônus de depósito, volume exigido e códigos por Gems.',
      excerpt:
        'Como funcionam os códigos promocionais pocketoption: bônus de boas-vindas 50START, ativação no cadastro ou depósito, regras de volume e quando o bônus não vale a pena.',
      coverAlt: 'Códigos promocionais Pocket Option — tickets com o código 50START e moedas de ouro',
      keyTakeaways: [
        'O código de boas-vindas oficial da Pocket Option é 50START: +50% no primeiro depósito a partir de $50 (ex.: $50 → saldo de $75).',
        'Insira o código no campo “Código promocional” no cadastro ou na página de depósito antes de pagar — não pode ser aplicado depois.',
        'O bônus exige um volume de negociação antes que a parte bônus possa ser sacada; seu depósito não fica bloqueado.',
        'Códigos extras (bônus de 20–110%, cashback, operações sem risco) podem ser comprados com Gems no Mercado da plataforma.',
        'Dispense o bônus se pretende sacar rápido ou operar valores pequenos — a regra de volume pode não compensar.',
      ],
      blocks: [
        { type: 'p', text: 'Um código promocional Pocket Option adiciona dinheiro de bônus ao seu depósito — o mais popular, 50START, dá +50% no primeiro depósito. Parece simples, mas muitas reclamações de saque começam com um bônus aceito sem ler os termos. Este guia explica os códigos pocketoption atuais, exatamente onde inseri-los, as regras de volume e como decidir se o bônus é uma boa ideia para você.' },
        { type: 'h2', id: 'codes', text: 'Códigos promocionais Pocket Option atuais' },
        { type: 'table', head: ['Código / bônus', 'O que você recebe', 'Condições'], rows: [
          ['50START', '+50% no primeiro depósito', 'Depósito a partir de $50; só no primeiro depósito; inserir antes de pagar'],
          ['Bônus de depósito 20–110%', 'Percentual adicionado a depósito de $50+', 'Comprado com Gems no Mercado; vale para o próximo depósito'],
          ['Cashback 2–10%', 'Parte das operações perdedoras devolvida mensalmente', 'Comprado com Gems; válido por um ano'],
          ['Operação sem risco', 'Cancele uma operação perdedora e receba o valor de volta', 'Comprado com Gems; ative em Mercado → Compras'],
          ['Bônus de saldo $5–$100', 'Crédito imediato no saldo real', 'Trocado por Gems; sem exigência de volume'],
        ] },
        { type: 'p', text: 'Códigos ligados a promoções (temas de cidades, esportes, aniversário) aparecem de tempos em tempos em Chat → Notificações → Promo dentro da plataforma e no blog oficial. Mudam rápido, então desconfie de qualquer “código secreto de 200%” em sites de terceiros — se não aparece na sua conta, não vai funcionar.' },
        { type: 'h2', id: 'register', text: 'Método 1: inserir o código no cadastro' },
        { type: 'image', src: IMG_REG_PANEL, alt: 'Painel de cadastro da Pocket Option com campos de e-mail, senha e código promocional', caption: 'O formulário de cadastro tem um campo próprio “Código promocional”.' },
        { type: 'ol', items: [
          'Abra o formulário de cadastro da Pocket Option (e-mail + senha).',
          'Digite 50START no campo “Código promocional” — sem espaços, em maiúsculas.',
          'Aceite o contrato de oferta pública e clique em Cadastrar.',
          'Confirme seu e-mail. O bônus fica vinculado ao perfil e será oferecido no primeiro depósito.',
        ] },
        { type: 'h2', id: 'deposit', text: 'Método 2: ativar o código na página de depósito' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Página de depósito da Pocket Option mostrando o bloco de oferta limitada de bônus', caption: 'Finanças → Depósito: a oferta de bônus aparece acima dos métodos de pagamento.' },
        { type: 'ol', items: [
          'Faça login e abra Finanças → Depósito.',
          'Escolha um método de pagamento e informe um valor de pelo menos $50 (mínimo do bônus).',
          'Clique em “Tem código promocional?” / no campo promo e cole 50START, ou selecione o bloco de bônus oferecido.',
          'Verifique se o resumo mostra o bônus (ex.: $50 + $25 de bônus).',
          'Pague. O bônus é creditado junto com o depósito.',
        ] },
        { type: 'warn', title: 'Insira o código antes de pagar', text: 'Um código promocional não pode ser aplicado a um depósito já feito. Se esqueceu o código, a única opção é usá-lo no próximo depósito — e o 50START vale apenas para o primeiro.' },
        { type: 'h2', id: 'market', text: 'Onde encontrar mais códigos: Gems e o Mercado' },
        { type: 'image', src: IMG_PROMO_PAGE, alt: 'Página de códigos promocionais da Pocket Option com códigos disponíveis e botão de ativação', caption: 'Perfil → Códigos promocionais: veja os códigos disponíveis, verifique e ative.' },
        { type: 'p', text: 'A Pocket Option tem um sistema de fidelidade baseado em Gems (cristais). Você ganha Gems operando, completando conquistas, participando da loteria, copiando operações com licença de Mineração ou vendendo itens no Mercado. No Mercado, troque Gems por códigos de bônus de depósito (20% a 110%), cashback, operações sem risco ou bônus de saldo imediato. Códigos comprados aparecem em Perfil → Códigos promocionais, onde podem ser verificados e ativados.' },
        { type: 'h2', id: 'rules', text: 'Regras do bônus: volume e saques' },
        { type: 'p', text: 'A regra principal: o dinheiro do bônus não pode ser sacado até que você negocie um determinado volume (soma das operações) — normalmente um múltiplo do valor do bônus, informado nos termos antes da ativação. Seus fundos depositados nunca ficam bloqueados e podem ser sacados a qualquer momento; se sacar antes de completar o volume, o bônus não utilizado é simplesmente cancelado. O lucro obtido com o bônus vira dinheiro real quando o volume é cumprido.' },
        { type: 'ul', items: [
          'Leia o multiplicador de volume exato no pop-up do bônus antes de confirmar.',
          'Operações na demo e operações canceladas/reembolsadas não contam para o volume.',
          'Um bônus por depósito; não é possível acumular dois códigos percentuais.',
          'A plataforma pode alterar ou encerrar bônus a qualquer momento — confira a oferta atual na sua conta.',
        ] },
        { type: 'h2', id: 'worth', text: 'Vale a pena aceitar o bônus da Pocket Option?' },
        { type: 'p', text: 'Aceite o bônus se pretende operar ativamente por semanas e um saldo maior ajuda a seguir suas regras de gestão de risco (ex.: 2% por operação). Dispense se quer testar a plataforma com um ciclo rápido depósito-operação-saque, se deposita menos de $50 ou se não gosta de qualquer restrição sobre quando sacar lucros. Não há bônus na conta demo — pratique lá primeiro.' },
        { type: 'tip', title: 'Nossa recomendação para o primeiro depósito', text: 'Deposite $5–$20 sem bônus, faça algumas operações de $1 e saque. Quando estiver satisfeito com o processo, faça um segundo depósito maior e decida sobre o bônus.' },
        { type: 'cta', text: 'Pronto para se cadastrar? Use o código 50START no cadastro para manter o bônus de +50% do primeiro depósito disponível.', label: 'Cadastrar na Pocket Option' },
      ],
      faq: [
        { q: 'Qual é o código promocional atual da Pocket Option?', a: 'O código de boas-vindas oficial é 50START — +50% no primeiro depósito de $50 ou mais. Outros códigos estão disponíveis por Gems no Mercado da plataforma.' },
        { q: 'Onde insiro o código promocional?', a: 'No campo “Código promocional” do formulário de cadastro ou na página de depósito (Finanças → Depósito) antes de concluir o pagamento.' },
        { q: 'Posso adicionar o código depois de depositar?', a: 'Não. Os bônus se aplicam apenas a depósitos feitos após inserir o código.' },
        { q: 'Posso sacar o bônus?', a: 'A parte bônus pode ser sacada após cumprir o volume de negociação exigido. Seu depósito não fica bloqueado.' },
        { q: 'Existe bônus sem depósito?', a: 'Não em dinheiro. A conta demo de $50.000 é grátis, e pequenos bônus de saldo ($5–$100) podem ser trocados por Gems ganhos na plataforma.' },
        { q: 'Os códigos de outros sites são reais?', a: 'Só funcionam os códigos mostrados na sua conta, no blog oficial ou em canais oficiais. Considere códigos “exclusivos de 200%” de sites desconhecidos como não confiáveis.' },
      ],
    },
    es: {
      title: 'Código promocional Pocket Option 2026: bono 50START, cómo activarlo y reglas',
      metaTitle: 'Código Promocional Pocket Option 2026 – Bono 50START',
      metaDescription:
        'Guía del código promocional Pocket Option: código oficial 50START (+50% en el primer depósito), dónde introducirlo, reglas del bono, volumen exigido y códigos por Gems.',
      excerpt:
        'Cómo funcionan los códigos promocionales pocketoption: bono de bienvenida 50START, activación al registrarse o depositar, reglas de volumen y cuándo no conviene.',
      coverAlt: 'Códigos promocionales Pocket Option — tickets con el código 50START y monedas de oro',
      keyTakeaways: [
        'El código de bienvenida oficial de Pocket Option es 50START: +50% en un primer depósito desde $50 (p. ej. $50 → saldo de $75).',
        'Introduce el código en el campo “Código promocional” al registrarte o en la página de depósito antes de pagar; no se puede aplicar después.',
        'El bono exige un volumen de operaciones antes de poder retirar la parte del bono; tu depósito no queda bloqueado.',
        'Códigos extra (bono de depósito 20–110%, cashback, operaciones sin riesgo) se compran con Gems en el Mercado de la plataforma.',
        'Rechaza el bono si piensas retirar pronto u operar poco: la regla de volumen puede no convenirte.',
      ],
      blocks: [
        { type: 'p', text: 'Un código promocional de Pocket Option añade dinero de bono a tu depósito; el más popular, 50START, da +50% en el primer depósito. Suena simple, pero muchas quejas de retiro empiezan con un bono aceptado sin leer las condiciones. Esta guía explica los códigos pocketoption actuales, exactamente dónde introducirlos, las reglas de volumen y cómo decidir si el bono te conviene.' },
        { type: 'h2', id: 'codes', text: 'Códigos promocionales Pocket Option vigentes' },
        { type: 'table', head: ['Código / bono', 'Qué recibes', 'Condiciones'], rows: [
          ['50START', '+50% en el primer depósito', 'Depósito desde $50; solo primer depósito; introducir antes de pagar'],
          ['Bono de depósito 20–110%', 'Porcentaje añadido a un depósito de $50+', 'Se compra con Gems en el Mercado; aplica al siguiente depósito'],
          ['Cashback 2–10%', 'Parte de las operaciones perdedoras devuelta cada mes', 'Se compra con Gems; válido un año'],
          ['Operación sin riesgo', 'Cancela una operación perdedora y recupera el importe', 'Se compra con Gems; se activa en Mercado → Compras'],
          ['Bono de saldo $5–$100', 'Abono inmediato al saldo real', 'Se canjea por Gems; sin volumen exigido'],
        ] },
        { type: 'p', text: 'Los códigos ligados a promociones (temáticas de ciudades, deportes, aniversario) aparecen de vez en cuando en Chat → Notificaciones → Promo dentro de la plataforma y en el blog oficial. Cambian rápido, así que desconfía de cualquier “código secreto del 200%” en sitios de terceros: si no aparece en tu cuenta, no funcionará.' },
        { type: 'h2', id: 'register', text: 'Método 1: introducir el código al registrarte' },
        { type: 'image', src: IMG_REG_PANEL, alt: 'Panel de registro de Pocket Option con campos de e-mail, contraseña y código promocional', caption: 'El formulario de registro tiene un campo específico “Código promocional”.' },
        { type: 'ol', items: [
          'Abre el formulario de registro de Pocket Option (e-mail + contraseña).',
          'Escribe 50START en el campo “Código promocional”, sin espacios y en mayúsculas.',
          'Acepta el acuerdo de oferta pública y pulsa Registrarse.',
          'Confirma tu e-mail. El bono queda vinculado a tu perfil y se ofrecerá en tu primer depósito.',
        ] },
        { type: 'h2', id: 'deposit', text: 'Método 2: activar el código en la página de depósito' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Página de depósito de Pocket Option mostrando el bloque de oferta limitada de bono', caption: 'Finanzas → Depósito: la oferta de bono se muestra sobre los métodos de pago.' },
        { type: 'ol', items: [
          'Inicia sesión y abre Finanzas → Depósito.',
          'Elige un método de pago e introduce un importe de al menos $50 (mínimo del bono).',
          'Pulsa “¿Tienes código promocional?” / el campo promo y pega 50START, o selecciona el bloque de bono ofrecido.',
          'Comprueba que el resumen muestra el bono (p. ej. $50 + $25 de bono).',
          'Paga. El bono se abona junto con el depósito.',
        ] },
        { type: 'warn', title: 'Introduce el código antes de pagar', text: 'Un código promocional no puede aplicarse a un depósito ya realizado. Si lo olvidaste, la única opción es usarlo en el siguiente depósito, y 50START solo vale para el primero.' },
        { type: 'h2', id: 'market', text: 'Dónde encontrar más códigos: Gems y el Mercado' },
        { type: 'image', src: IMG_PROMO_PAGE, alt: 'Página de códigos promocionales de Pocket Option con códigos disponibles y botón de activación', caption: 'Perfil → Códigos promocionales: consulta los códigos disponibles, verifica y activa.' },
        { type: 'p', text: 'Pocket Option tiene un sistema de fidelidad basado en Gems (cristales). Ganas Gems operando, completando logros, participando en la lotería, copiando operaciones con una licencia de Minería o vendiendo objetos en el Mercado. En el Mercado puedes canjear Gems por códigos de bono de depósito (del 20% al 110%), cashback, operaciones sin riesgo o un bono de saldo inmediato. Los códigos comprados aparecen en Perfil → Códigos promocionales, donde puedes verificarlos y activarlos.' },
        { type: 'h2', id: 'rules', text: 'Reglas del bono: volumen y retiros' },
        { type: 'p', text: 'La regla clave: el dinero del bono no se puede retirar hasta operar cierto volumen (la suma de tus operaciones), normalmente un múltiplo del importe del bono indicado en las condiciones antes de activarlo. Tus fondos depositados nunca quedan bloqueados y puedes retirarlos en cualquier momento; si retiras antes de completar el volumen, el bono no usado simplemente se cancela. El beneficio obtenido con fondos del bono se convierte en dinero real al cumplir el volumen.' },
        { type: 'ul', items: [
          'Lee el multiplicador de volumen exacto en la ventana del bono antes de confirmar.',
          'Las operaciones en demo y las canceladas/reembolsadas no cuentan para el volumen.',
          'Un bono por depósito; no se pueden acumular dos códigos porcentuales.',
          'La plataforma puede modificar o retirar bonos en cualquier momento: revisa la oferta vigente en tu cuenta.',
        ] },
        { type: 'h2', id: 'worth', text: '¿Conviene aceptar el bono de Pocket Option?' },
        { type: 'p', text: 'Acepta el bono si vas a operar activamente durante semanas y un saldo mayor te ayuda a seguir tus reglas de gestión del riesgo (p. ej. 2% por operación). Recházalo si quieres probar la plataforma con un ciclo rápido depósito-operación-retiro, si depositas menos de $50 o si no te gusta ninguna restricción sobre cuándo retirar beneficios. En la cuenta demo no hay bono: practica allí primero.' },
        { type: 'tip', title: 'Nuestra recomendación para el primer depósito', text: 'Deposita $5–$20 sin bono, haz algunas operaciones de $1 y retira. Cuando estés conforme con el proceso, haz un segundo depósito mayor y decide entonces sobre el bono.' },
        { type: 'cta', text: '¿Listo para registrarte? Usa el código 50START al registrarte para mantener disponible el bono de +50% del primer depósito.', label: 'Registrarse en Pocket Option' },
      ],
      faq: [
        { q: '¿Cuál es el código promocional actual de Pocket Option?', a: 'El código de bienvenida oficial es 50START: +50% en un primer depósito de $50 o más. Otros códigos se consiguen por Gems en el Mercado de la plataforma.' },
        { q: '¿Dónde introduzco el código promocional?', a: 'En el campo “Código promocional” del formulario de registro, o en la página de depósito (Finanzas → Depósito) antes de completar el pago.' },
        { q: '¿Puedo añadir un código después de depositar?', a: 'No. Los bonos solo se aplican a depósitos realizados después de introducir el código.' },
        { q: '¿Puedo retirar el bono?', a: 'La parte del bono se puede retirar tras completar el volumen de operaciones exigido. Tu depósito no queda bloqueado.' },
        { q: '¿Hay bono sin depósito?', a: 'No en efectivo. La cuenta demo de $50.000 es gratis, y pequeños bonos de saldo ($5–$100) se canjean por Gems ganados en la plataforma.' },
        { q: '¿Los códigos de otros sitios web son reales?', a: 'Solo funcionan los códigos que aparecen en tu cuenta, en el blog oficial o en canales oficiales. Considera poco fiables los códigos “exclusivos del 200%” de sitios desconocidos.' },
      ],
    },
    ru: {
      title: 'Промокод Pocket Option 2026: бонус 50START, как активировать и правила',
      metaTitle: 'Промокод Pocket Option 2026 – Бонус 50START и Как Использовать',
      metaDescription:
        'Гид по промокодам Pocket Option: официальный код 50START (+50% к первому депозиту), где вводить, правила бонуса на депозит, требования по обороту и коды за Gems.',
      excerpt:
        'Как работают промокоды pocketoption: приветственный бонус 50START, активация при регистрации или пополнении, правила оборота и когда бонус не стоит брать.',
      coverAlt: 'Промокоды Pocket Option — билеты с кодом 50START и золотые монеты',
      keyTakeaways: [
        'Официальный приветственный промокод Pocket Option — 50START: +50% к первому депозиту от $50 (например, $50 → баланс $75).',
        'Вводите код в поле «Промокод» при регистрации или на странице пополнения до оплаты — задним числом он не применяется.',
        'Бонусные средства требуют торгового оборота, прежде чем бонусную часть можно вывести; ваш собственный депозит не блокируется.',
        'Дополнительные коды (бонус 20–110% на депозит, кэшбэк, безрисковые сделки) покупаются за Gems в Маркете платформы.',
        'Откажитесь от бонуса, если планируете быстро выводить или торговать малыми суммами — правило оборота может вам не подойти.',
      ],
      blocks: [
        { type: 'p', text: 'Промокод Pocket Option добавляет бонусные деньги к депозиту — самый популярный, 50START, даёт +50% к первому пополнению. Звучит просто, но многие жалобы на вывод начинаются с бонуса, принятого без чтения условий. В этом гиде — действующие коды pocketoption, точное место ввода, правила оборота и как решить, нужен ли бонус именно вам.' },
        { type: 'h2', id: 'codes', text: 'Действующие промокоды Pocket Option' },
        { type: 'table', head: ['Код / бонус', 'Что вы получаете', 'Условия'], rows: [
          ['50START', '+50% к первому депозиту', 'Депозит от $50; только первый депозит; ввести до оплаты'],
          ['Бонус на депозит 20–110%', 'Процент к депозиту от $50', 'Покупается за Gems в Маркете; применяется к следующему депозиту'],
          ['Кэшбэк 2–10%', 'Часть убыточных сделок возвращается ежемесячно', 'Покупается за Gems; действует один год'],
          ['Безрисковая сделка', 'Отмена одной убыточной сделки с возвратом суммы', 'Покупается за Gems; активация в Маркет → Покупки'],
          ['Бонус на баланс $5–$100', 'Мгновенное зачисление на реальный баланс', 'Обмен на Gems; без требования оборота'],
        ] },
        { type: 'p', text: 'Коды, привязанные к акциям (городские, спортивные, юбилейные), время от времени появляются в разделе Чат → Уведомления → Промо внутри платформы и в официальном блоге. Они быстро меняются, поэтому к любому «секретному коду на 200%» с сторонних сайтов относитесь с подозрением — если код не показан в вашем аккаунте, он не сработает.' },
        { type: 'h2', id: 'register', text: 'Способ 1: ввести промокод при регистрации' },
        { type: 'image', src: IMG_REG_PANEL, alt: 'Панель регистрации Pocket Option с полями e-mail, пароля и промокода', caption: 'В форме регистрации есть отдельное поле «Промокод».' },
        { type: 'ol', items: [
          'Откройте форму регистрации Pocket Option (e-mail + пароль).',
          'Введите 50START в поле «Промокод» — без пробелов, заглавными буквами.',
          'Примите публичную оферту и нажмите «Регистрация».',
          'Подтвердите e-mail. Бонус закрепляется за профилем и будет предложен при первом пополнении.',
        ] },
        { type: 'h2', id: 'deposit', text: 'Способ 2: активировать код на странице пополнения' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Страница пополнения Pocket Option с блоком ограниченного бонусного предложения', caption: 'Финансы → Пополнение: бонусное предложение показано над платёжными методами.' },
        { type: 'ol', items: [
          'Войдите в аккаунт и откройте Финансы → Пополнение.',
          'Выберите платёжный метод и введите сумму не менее $50 (минимум для бонуса).',
          'Нажмите «Есть промокод?» / поле промокода и вставьте 50START либо выберите предложенный бонусный блок.',
          'Проверьте, что в итоге отображается бонус (например, $50 + $25 бонуса).',
          'Оплатите. Бонус зачисляется вместе с депозитом.',
        ] },
        { type: 'warn', title: 'Вводите код до оплаты', text: 'Промокод нельзя применить к уже сделанному депозиту. Если забыли код, единственный вариант — использовать его при следующем пополнении, а 50START действует только на первый депозит.' },
        { type: 'h2', id: 'market', text: 'Где взять больше кодов: Gems и Маркет' },
        { type: 'image', src: IMG_PROMO_PAGE, alt: 'Страница промокодов Pocket Option с доступными кодами и кнопкой активации', caption: 'Профиль → Промокоды: просмотр доступных кодов, проверка и активация.' },
        { type: 'p', text: 'В Pocket Option есть система лояльности на основе Gems (кристаллов). Gems начисляются за торговлю, достижения, участие в лотерее, копирование сделок с лицензией майнинга или продажу предметов в Маркете. В Маркете Gems обмениваются на коды бонуса к депозиту (от 20% до 110%), кэшбэк, безрисковые сделки или мгновенный бонус на баланс. Купленные коды появляются в разделе Профиль → Промокоды, где их можно проверить и активировать.' },
        { type: 'h2', id: 'rules', text: 'Правила бонуса: оборот и вывод' },
        { type: 'p', text: 'Главное правило: бонусные деньги нельзя вывести, пока вы не наторгуете определённый оборот (суммарный объём сделок) — как правило, кратный сумме бонуса и указанный в условиях до активации. Ваши собственные средства никогда не блокируются, их можно вывести в любой момент; при выводе до выполнения оборота неиспользованный бонус просто аннулируется. Прибыль, полученная на бонусные средства, становится реальными деньгами после выполнения оборота.' },
        { type: 'ul', items: [
          'Прочитайте точный множитель оборота во всплывающем окне бонуса до подтверждения.',
          'Сделки на демо и отменённые/возвращённые сделки в оборот не засчитываются.',
          'Один бонус на депозит; два процентных кода не суммируются.',
          'Платформа может изменить или отменить бонусы в любой момент — проверяйте актуальное предложение в аккаунте.',
        ] },
        { type: 'h2', id: 'worth', text: 'Стоит ли брать бонус Pocket Option?' },
        { type: 'p', text: 'Берите бонус, если планируете активно торговать неделями и больший баланс помогает соблюдать правила риск-менеджмента (например, 2% на сделку). Откажитесь, если хотите протестировать платформу быстрым циклом «депозит — сделка — вывод», вносите меньше $50 или не хотите никаких ограничений на вывод прибыли. На демо-счёте бонусов нет — сначала потренируйтесь там.' },
        { type: 'tip', title: 'Наша рекомендация для первого депозита', text: 'Внесите $5–$20 без бонуса, сделайте несколько сделок по $1 и выведите средства. Когда процесс вас устроит, внесите второй, больший депозит и тогда решайте насчёт бонуса.' },
        { type: 'cta', text: 'Готовы зарегистрироваться? Введите промокод 50START при регистрации, чтобы сохранить бонус +50% к первому депозиту.', label: 'Регистрация на Pocket Option' },
      ],
      faq: [
        { q: 'Какой сейчас действует промокод Pocket Option?', a: 'Официальный приветственный код — 50START: +50% к первому депозиту от $50. Другие коды доступны за Gems в Маркете платформы.' },
        { q: 'Где вводить промокод?', a: 'В поле «Промокод» формы регистрации или на странице пополнения (Финансы → Пополнение) до завершения оплаты.' },
        { q: 'Можно ли добавить промокод после пополнения?', a: 'Нет. Бонусы применяются только к депозитам, сделанным после ввода кода.' },
        { q: 'Можно ли вывести бонус?', a: 'Бонусная часть становится доступной к выводу после выполнения требуемого торгового оборота. Ваш собственный депозит не блокируется.' },
        { q: 'Есть ли бездепозитный бонус?', a: 'Не деньгами. Демо-счёт на $50 000 бесплатен, а небольшие бонусы на баланс ($5–$100) можно обменять на Gems, заработанные на платформе.' },
        { q: 'Работают ли промокоды с других сайтов?', a: 'Работают только коды, показанные в вашем аккаунте, в официальном блоге или официальных каналах. «Эксклюзивные коды на 200%» с неизвестных сайтов считайте ненадёжными.' },
      ],
    },
    id: {
      title: 'Kode promo Pocket Option 2026: bonus 50START, cara mengaktifkan, dan aturannya',
      metaTitle: 'Kode Promo Pocket Option 2026 – Bonus 50START & Cara Pakai',
      metaDescription:
        'Panduan kode promo Pocket Option: kode resmi 50START (+50% deposit pertama), tempat memasukkannya, aturan bonus deposit, syarat turnover, dan kode dari Gems.',
      excerpt:
        'Cara kerja kode promo pocketoption: bonus sambutan 50START, aktivasi saat registrasi atau deposit, aturan turnover, dan kapan bonus tidak layak diambil.',
      coverAlt: 'Kode promo Pocket Option — tiket dengan kode 50START dan koin emas',
      keyTakeaways: [
        'Kode promo sambutan resmi Pocket Option adalah 50START: +50% untuk deposit pertama mulai $50 (contoh: $50 → saldo $75).',
        'Masukkan kode di kolom “Kode promo” saat registrasi atau di halaman deposit sebelum membayar — tidak bisa diterapkan setelahnya.',
        'Dana bonus memerlukan turnover trading sebelum bagian bonus bisa ditarik; deposit Anda sendiri tidak dikunci.',
        'Kode tambahan (bonus deposit 20–110%, cashback, trade bebas risiko) dapat dibeli dengan Gems di Market platform.',
        'Lewati bonus jika Anda ingin cepat menarik dana atau trading kecil — aturan turnover mungkin tidak cocok.',
      ],
      blocks: [
        { type: 'p', text: 'Kode promo Pocket Option menambahkan uang bonus ke deposit Anda — yang paling populer, 50START, memberi +50% pada deposit pertama. Terdengar sederhana, tetapi banyak keluhan penarikan bermula dari bonus yang diterima tanpa membaca syaratnya. Panduan ini menjelaskan kode pocketoption yang berlaku, tempat memasukkannya, aturan turnover, dan cara memutuskan apakah bonus cocok untuk Anda.' },
        { type: 'h2', id: 'codes', text: 'Kode promo Pocket Option yang berlaku' },
        { type: 'table', head: ['Kode / bonus', 'Yang Anda dapat', 'Syarat'], rows: [
          ['50START', '+50% pada deposit pertama', 'Deposit mulai $50; hanya deposit pertama; masukkan sebelum bayar'],
          ['Bonus deposit 20–110%', 'Persentase ditambahkan ke deposit $50+', 'Dibeli dengan Gems di Market; berlaku untuk deposit berikutnya'],
          ['Cashback 2–10%', 'Sebagian trade rugi dikembalikan bulanan', 'Dibeli dengan Gems; berlaku satu tahun'],
          ['Trade bebas risiko', 'Batalkan satu trade rugi dan dapatkan jumlahnya kembali', 'Dibeli dengan Gems; aktifkan di Market → Pembelian'],
          ['Bonus saldo $5–$100', 'Kredit langsung ke saldo riil', 'Ditukar dengan Gems; tanpa syarat turnover'],
        ] },
        { type: 'p', text: 'Kode yang terkait promosi (tema kota, olahraga, ulang tahun) muncul sesekali di Chat → Notifikasi → Promo dalam platform dan di blog resmi. Kode ini cepat berubah, jadi curigai “kode rahasia 200%” dari situs pihak ketiga — jika tidak tampil di akun Anda, kode itu tidak akan berfungsi.' },
        { type: 'h2', id: 'register', text: 'Cara 1: masukkan kode promo saat registrasi' },
        { type: 'image', src: IMG_REG_PANEL, alt: 'Panel registrasi Pocket Option dengan kolom e-mail, kata sandi, dan kode promo', caption: 'Formulir registrasi memiliki kolom khusus “Kode promo”.' },
        { type: 'ol', items: [
          'Buka formulir registrasi Pocket Option (e-mail + kata sandi).',
          'Ketik 50START di kolom “Kode promo” — tanpa spasi, huruf kapital.',
          'Setujui perjanjian penawaran publik dan klik Daftar.',
          'Konfirmasi e-mail Anda. Bonus terlampir ke profil dan akan ditawarkan pada deposit pertama.',
        ] },
        { type: 'h2', id: 'deposit', text: 'Cara 2: aktifkan kode di halaman deposit' },
        { type: 'image', src: IMG_DEPOSIT, alt: 'Halaman deposit Pocket Option menampilkan blok penawaran bonus terbatas', caption: 'Finance → Deposit: penawaran bonus ditampilkan di atas metode pembayaran.' },
        { type: 'ol', items: [
          'Masuk dan buka Finance → Deposit.',
          'Pilih metode pembayaran dan masukkan jumlah minimal $50 (minimum bonus).',
          'Klik “Punya kode promo?” / kolom promo dan tempel 50START, atau pilih blok bonus yang ditawarkan.',
          'Pastikan ringkasan menampilkan bonus (contoh: $50 + bonus $25).',
          'Bayar. Bonus dikreditkan bersama deposit.',
        ] },
        { type: 'warn', title: 'Masukkan kode sebelum membayar', text: 'Kode promo tidak bisa diterapkan pada deposit yang sudah dilakukan. Jika lupa memasukkan kode, satu-satunya pilihan adalah memakainya pada deposit berikutnya — dan 50START hanya berlaku untuk deposit pertama.' },
        { type: 'h2', id: 'market', text: 'Tempat mencari kode lain: Gems dan Market' },
        { type: 'image', src: IMG_PROMO_PAGE, alt: 'Halaman kode promo Pocket Option dengan kode yang tersedia dan tombol aktivasi', caption: 'Profil → Kode promo: lihat kode yang tersedia, cek kode, dan aktifkan.' },
        { type: 'p', text: 'Pocket Option memiliki sistem loyalitas berbasis Gems (kristal). Gems didapat dari trading, menyelesaikan pencapaian, ikut lotre, menyalin trade dengan lisensi Mining, atau menjual item di Market. Di Market, Gems bisa ditukar dengan kode bonus deposit (20% hingga 110%), cashback, trade bebas risiko, atau bonus saldo instan. Kode yang dibeli muncul di Profil → Kode promo, tempat Anda bisa mengecek dan mengaktifkannya.' },
        { type: 'h2', id: 'rules', text: 'Aturan bonus: turnover dan penarikan' },
        { type: 'p', text: 'Aturan utamanya: uang bonus tidak bisa ditarik sampai Anda mencapai turnover tertentu (total volume trade) — biasanya kelipatan dari jumlah bonus, tercantum dalam syarat bonus sebelum aktivasi. Dana deposit Anda sendiri tidak pernah dikunci dan bisa ditarik kapan saja; jika menarik sebelum turnover selesai, bonus yang belum terpakai hanya dibatalkan. Profit dari dana bonus menjadi uang riil setelah turnover terpenuhi.' },
        { type: 'ul', items: [
          'Baca pengali turnover yang tepat di pop-up bonus sebelum konfirmasi.',
          'Trade di demo dan trade yang dibatalkan/dikembalikan tidak dihitung ke turnover.',
          'Satu bonus per deposit; dua kode persentase tidak bisa digabung.',
          'Platform dapat mengubah atau mencabut bonus kapan saja — cek penawaran terkini di akun Anda.',
        ] },
        { type: 'h2', id: 'worth', text: 'Apakah bonus Pocket Option layak diambil?' },
        { type: 'p', text: 'Ambil bonus jika Anda berencana trading aktif selama berminggu-minggu dan saldo lebih besar membantu Anda mengikuti aturan manajemen risiko (misalnya 2% per trade). Lewati jika Anda ingin menguji platform dengan siklus cepat deposit-trade-tarik, deposit kurang dari $50, atau tidak suka pembatasan apa pun soal waktu penarikan profit. Tidak ada bonus di akun demo — latihan dulu di sana.' },
        { type: 'tip', title: 'Saran kami untuk deposit pertama', text: 'Deposit $5–$20 tanpa bonus, lakukan beberapa trade $1, lalu tarik. Setelah puas dengan prosesnya, lakukan deposit kedua yang lebih besar dan putuskan soal bonus saat itu.' },
        { type: 'cta', text: 'Siap mendaftar? Gunakan kode promo 50START saat registrasi agar bonus +50% deposit pertama tetap tersedia.', label: 'Daftar di Pocket Option' },
      ],
      faq: [
        { q: 'Apa kode promo Pocket Option saat ini?', a: 'Kode sambutan resmi adalah 50START — +50% untuk deposit pertama $50 atau lebih. Kode lain tersedia dengan Gems di Market platform.' },
        { q: 'Di mana memasukkan kode promo?', a: 'Di kolom “Kode promo” pada formulir registrasi, atau di halaman deposit (Finance → Deposit) sebelum menyelesaikan pembayaran.' },
        { q: 'Bisakah menambahkan kode promo setelah deposit?', a: 'Tidak. Bonus hanya berlaku untuk deposit yang dilakukan setelah kode dimasukkan.' },
        { q: 'Bisakah bonus ditarik?', a: 'Bagian bonus bisa ditarik setelah Anda menyelesaikan turnover trading yang disyaratkan. Deposit Anda sendiri tidak dikunci.' },
        { q: 'Apakah ada bonus tanpa deposit?', a: 'Tidak dalam bentuk uang. Akun demo $50.000 gratis, dan bonus saldo kecil ($5–$100) bisa ditukar dengan Gems yang didapat di platform.' },
        { q: 'Apakah kode promo di situs lain asli?', a: 'Hanya kode yang tampil di akun Anda, blog resmi, atau kanal resmi yang berfungsi. Anggap kode “eksklusif 200%” dari situs tak dikenal sebagai tidak dapat diandalkan.' },
      ],
    },
  },
};
