import type { Locale } from '@/lib/i18n/config';
import type { BlogDictionary, BlogPost } from './types';
import { howToTradeOnPocketOption } from './posts/how-to-trade-on-pocket-option';
import { pocketOptionWithdrawal } from './posts/pocket-option-withdrawal';

export const blogPosts: BlogPost[] = [pocketOptionWithdrawal, howToTradeOnPocketOption].sort(
  (a, b) => (a.publishedAt < b.publishedAt ? 1 : -1),
);

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find(p => p.slug === slug);
}

const dictionaries: Record<Locale, BlogDictionary> = {
  en: {
    home: 'Home',
    breadcrumb: 'Blog',
    eyebrow: 'Pocket Option blog',
    title: 'Pocket Option tutorials,',
    titleAccent: 'guides and platform news',
    subtitle: 'Practical articles about trading on Pocket Option: how the terminal works, deposits and withdrawals, demo practice, indicators and risk management. Written for beginners, useful for everyone.',
    latest: 'Latest articles',
    readMore: 'Read article',
    minRead: 'min read',
    published: 'Published',
    updated: 'Updated',
    author: 'Author',
    onThisPage: 'On this page',
    keyTakeaways: 'Key takeaways',
    faqTitle: 'Frequently asked questions',
    faqEyebrow: 'FAQ',
    related: 'Keep reading',
    ctaEyebrow: 'Start now',
    ctaTitle: 'Try it on the Pocket Option demo account',
    ctaText: '$50,000 virtual balance, the same terminal and assets as the real account. No deposit required.',
    ctaButton: 'Open free demo',
    ctaSecondary: 'Quick start guide',
    categories: { tutorial: 'Tutorial', payments: 'Deposits & withdrawals', platform: 'Platform', strategy: 'Strategy' },
    disclaimer: 'This is an independent Pocket Option affiliate website. Articles are for information only and are not investment advice. Trading involves risk.',
  },
  pt: {
    home: 'Início',
    breadcrumb: 'Blog',
    eyebrow: 'Blog Pocket Option',
    title: 'Tutoriais, guias e novidades',
    titleAccent: 'da plataforma Pocket Option',
    subtitle: 'Artigos práticos sobre trading na Pocket Option: como funciona o terminal, depósitos e saques, prática na demo, indicadores e gestão de risco. Escritos para iniciantes, úteis para todos.',
    latest: 'Artigos recentes',
    readMore: 'Ler artigo',
    minRead: 'min de leitura',
    published: 'Publicado',
    updated: 'Atualizado',
    author: 'Autor',
    onThisPage: 'Nesta página',
    keyTakeaways: 'Pontos principais',
    faqTitle: 'Perguntas frequentes',
    faqEyebrow: 'FAQ',
    related: 'Continue lendo',
    ctaEyebrow: 'Comece agora',
    ctaTitle: 'Teste na conta demo da Pocket Option',
    ctaText: 'Saldo virtual de $50.000, o mesmo terminal e os mesmos ativos da conta real. Sem depósito.',
    ctaButton: 'Abrir demo grátis',
    ctaSecondary: 'Guia de início rápido',
    categories: { tutorial: 'Tutorial', payments: 'Depósitos e saques', platform: 'Plataforma', strategy: 'Estratégia' },
    disclaimer: 'Este é um site afiliado independente da Pocket Option. Os artigos são apenas informativos e não constituem recomendação de investimento. Operar envolve risco.',
  },
  es: {
    home: 'Inicio',
    breadcrumb: 'Blog',
    eyebrow: 'Blog Pocket Option',
    title: 'Tutoriales, guías y novedades',
    titleAccent: 'de la plataforma Pocket Option',
    subtitle: 'Artículos prácticos sobre trading en Pocket Option: cómo funciona el terminal, depósitos y retiros, práctica en demo, indicadores y gestión del riesgo. Escritos para principiantes, útiles para todos.',
    latest: 'Últimos artículos',
    readMore: 'Leer artículo',
    minRead: 'min de lectura',
    published: 'Publicado',
    updated: 'Actualizado',
    author: 'Autor',
    onThisPage: 'En esta página',
    keyTakeaways: 'Puntos clave',
    faqTitle: 'Preguntas frecuentes',
    faqEyebrow: 'FAQ',
    related: 'Sigue leyendo',
    ctaEyebrow: 'Empieza ahora',
    ctaTitle: 'Pruébalo en la cuenta demo de Pocket Option',
    ctaText: 'Saldo virtual de $50.000, el mismo terminal y los mismos activos que la cuenta real. Sin depósito.',
    ctaButton: 'Abrir demo gratis',
    ctaSecondary: 'Guía de inicio rápido',
    categories: { tutorial: 'Tutorial', payments: 'Depósitos y retiros', platform: 'Plataforma', strategy: 'Estrategia' },
    disclaimer: 'Este es un sitio afiliado independiente de Pocket Option. Los artículos son solo informativos y no constituyen asesoramiento de inversión. Operar implica riesgo.',
  },
  ru: {
    home: 'Главная',
    breadcrumb: 'Блог',
    eyebrow: 'Блог Pocket Option',
    title: 'Обучение, руководства',
    titleAccent: 'и новости платформы Pocket Option',
    subtitle: 'Практические статьи о торговле на Pocket Option: как устроен терминал, депозиты и выводы, практика на демо, индикаторы и управление риском. Написано для новичков, полезно всем.',
    latest: 'Последние статьи',
    readMore: 'Читать статью',
    minRead: 'мин чтения',
    published: 'Опубликовано',
    updated: 'Обновлено',
    author: 'Автор',
    onThisPage: 'На этой странице',
    keyTakeaways: 'Главное',
    faqTitle: 'Частые вопросы',
    faqEyebrow: 'FAQ',
    related: 'Читайте также',
    ctaEyebrow: 'Начните сейчас',
    ctaTitle: 'Попробуйте на демо-счёте Pocket Option',
    ctaText: 'Виртуальный баланс $50 000, тот же терминал и активы, что и на реальном счёте. Без депозита.',
    ctaButton: 'Открыть бесплатное демо',
    ctaSecondary: 'Быстрый старт',
    categories: { tutorial: 'Обучение', payments: 'Депозиты и выводы', platform: 'Платформа', strategy: 'Стратегии' },
    disclaimer: 'Это независимый партнёрский сайт Pocket Option. Статьи носят информационный характер и не являются инвестиционной рекомендацией. Торговля связана с риском.',
  },
  id: {
    home: 'Beranda',
    breadcrumb: 'Blog',
    eyebrow: 'Blog Pocket Option',
    title: 'Tutorial, panduan, dan berita',
    titleAccent: 'platform Pocket Option',
    subtitle: 'Artikel praktis tentang trading di Pocket Option: cara kerja terminal, deposit dan penarikan, latihan demo, indikator, dan manajemen risiko. Ditulis untuk pemula, berguna bagi semua.',
    latest: 'Artikel terbaru',
    readMore: 'Baca artikel',
    minRead: 'menit baca',
    published: 'Diterbitkan',
    updated: 'Diperbarui',
    author: 'Penulis',
    onThisPage: 'Di halaman ini',
    keyTakeaways: 'Poin penting',
    faqTitle: 'Pertanyaan umum',
    faqEyebrow: 'FAQ',
    related: 'Baca juga',
    ctaEyebrow: 'Mulai sekarang',
    ctaTitle: 'Coba di akun demo Pocket Option',
    ctaText: 'Saldo virtual $50.000, terminal dan aset yang sama seperti akun riil. Tanpa deposit.',
    ctaButton: 'Buka demo gratis',
    ctaSecondary: 'Panduan mulai cepat',
    categories: { tutorial: 'Tutorial', payments: 'Deposit & penarikan', platform: 'Platform', strategy: 'Strategi' },
    disclaimer: 'Ini adalah situs afiliasi Pocket Option independen. Artikel bersifat informatif dan bukan saran investasi. Trading melibatkan risiko.',
  },
};

export function getBlogDictionary(lang: string): BlogDictionary {
  return dictionaries[lang as Locale] ?? dictionaries.en;
}

export const blogIndexSeo: Record<Locale, { title: string; description: string }> = {
  en: {
    title: 'Pocket Option blog: tutorials, trading guides and platform news',
    description: 'Pocket Option blog with step-by-step tutorials for beginners: how the trading terminal works, deposits and withdrawals, demo account practice, indicators and risk management on pocketoption.',
  },
  pt: {
    title: 'Blog Pocket Option: tutoriais, guias de trading e novidades da plataforma',
    description: 'Blog da Pocket Option com tutoriais passo a passo para iniciantes: como funciona o terminal, depósitos e saques, prática na conta demo, indicadores e gestão de risco na pocketoption.',
  },
  es: {
    title: 'Blog Pocket Option: tutoriales, guías de trading y novedades de la plataforma',
    description: 'Blog de Pocket Option con tutoriales paso a paso para principiantes: cómo funciona el terminal, depósitos y retiros, práctica en la cuenta demo, indicadores y gestión del riesgo en pocketoption.',
  },
  ru: {
    title: 'Блог Pocket Option: обучение, руководства по торговле и новости платформы',
    description: 'Блог Pocket Option с пошаговыми руководствами для новичков: как устроен торговый терминал, депозиты и выводы, практика на демо-счёте, индикаторы и управление риском на pocketoption.',
  },
  id: {
    title: 'Blog Pocket Option: tutorial, panduan trading, dan berita platform',
    description: 'Blog Pocket Option dengan tutorial langkah demi langkah untuk pemula: cara kerja terminal trading, deposit dan penarikan, latihan akun demo, indikator, dan manajemen risiko di pocketoption.',
  },
};

export type { BlogPost, BlogPostContent, BlogBlock, BlogDictionary, BlogCategory } from './types';
